### ISSUE TITLE
Delta Chat spanish website 

### ISSUE THREAD

**Issue by rizzopablo** [deltachat/deltachat-android#100]
I would like to share the Delta Chat website to spanish readers, I could help translating the website.

**Comment by r10s** [comment]
We would be glad to have a spanish website.

The easiest way to create one is to clone the https://github.com/r10s/deltachat-pages/ repository, copy the `en`  folder to `es`, translate its content and do a PR.

**Comment by rizzopablo** [comment]
Ok, I just forked the pages and started translating the index:

https://rizzopablo.github.io/deltachat-pages/es/

I'll send a merge request when finished the translation.

**Comment by r10s** [comment]
Thanks, I've merged the PR and gave you access to the repository.
Also feel free to post in the english blog, BTW. Maybe a little hint to the new spanish site. Or whatever has to do with Delta or Messengers.
