### ISSUE TITLE
Copy content of message info dialog to clipboard

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1001]
Useful for debuging

**Comment by r10s** [comment]
i think as no one is working on that, we can close this issue for now.

also, at some point we will rework the whole dialog and the text as it exists currently will disappear at all, so, i do not think it is really worth thinking too much about that now.

**Comment by Simon-Laux** [comment]
crosslinking back to an related forum topic: https://support.delta.chat/t/select-and-copy-just-a-part-of-message-dc-ios-android/728/25
