### ISSUE TITLE
Mailto still partly broken

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1005]
[@adbenitez found this issue]
```
mailto:simplebot@riseup.net?body=!web%20https%3A%2F%2Fduckduckgo.com%2Flite%3Fq%3Dduck%2520it
```
DeltaChat parses only the part before the urlencoded equal sign:
```
!web https://duckduckgo.com/lite?q
```
K9 parses it correctly:
```
!web https://duckduckgo.com/lite?q=duck%20it
```
PS: we should also make sure that the urlencoded `&` and `#` are parsed correctly

**Comment by Boehrsi** [comment]
I will have another look at this topic.

**Comment by r10s** [comment]
cool :)

**Comment by adbenitez** [comment]
urlencoded & cause the contact list to open when clicking the mailto link, bot no "do you want to chat with X?" is sown, urlencoded # works fine, and ":" makes DC to show the "share with" dialog instead of opening the chat with the user specified in the mailto link

**Comment by Boehrsi** [comment]
Will hopefully finish that one today, as the last weeks sadly to many other tasks came up to finish this problem.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/1024
