### ISSUE TITLE
Don't show prompt "do you want to chat with x" if a chat with x already exists

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1007]
with the new bot when an user taps in a mailto link in the form `mailto:BOT-ADDR?body=some-text`
they can open that link with Delta Chat, but every time the tap such a link, Delta ask if you want to chat with that contact as it was the first time you try to chat with that contact even when you already has an active chat wth the contact this should not be asked and the chat with that contact should be opened directly with the text prefilled.
This issue is not especific of mailto links, if you press the "+" then select to chat with a contact you already has a chat, a prompt is shown instead of opening directly, for the bot UX this is really annoying since you has to confirm this prompt quite often

- Platform (android/blackberry/anbox):Android 6
- Delta Chat Version: 0.510.1
- Steps to reproduce the problem: click a mailto link that points to an already acepted contact

**Comment by r10s** [comment]
> This issue is not especific of mailto links, if you press the "+" then select to chat with a contact you already has a chat, a prompt is shown instead of opening directly, for the bot UX this is really annoying since you has to confirm this prompt quite often

well, we had this behavior for the contact-list before. but the issue then was, that it was not clear to the user what will happen on a tap on a contact - and that at least some of them do not understand why they're sometimes asked and sometimes not.

but i have no strong opinion here, we would show the contact in the contact-list differently when there is a contact, however, this might also raise more confusion.

maybe the first idea, not to ask when there is already a chat, is just the way to go. but i would change this for both, mailto-links and contact-clicks.

**Comment by adbenitez** [comment]
yay!!! Thanks! <3

**Comment by r10s** [comment]
@adbenitez thanks for waiting so long :)
