### ISSUE TITLE
Emoticon compatibility problems.

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1009]
- Platform (android/blackberry/anbox): Android 
- Device:Xiaomy MI A1- Alcatel 4015X
- Delta Chat Version: 0.510.1
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem: These are Emoticons sent from another mobile with Android 4.2.2. I have reference of equal behavior in an akcatel with Android 5 On the other mobile the received ones and those sent in mine xiaomy are normal, with Android 9. I can not see the receive.Emoticons. 
Screenshots: 
![Screenshot_20190718-162718](https://user-images.githubusercontent.com/52469394/61553521-95ca7d00-aa28-11e9-8076-ba75bbfdcfcb.png)

- Logs:

**Comment by hpk42** [comment]
thanks for reporting. 

technical sidenote for other devs: I am not sure it's related but from working with the new rust-core we discovered that likely the current Android produces possibly double-encoded emojis -- first with utf-16, then with utf-8.  This results in bytestrings like '\xed\xa0\xbd\xed\xb8\x80' which according to https://stackoverflow.com/questions/35670238/emoji-in-r-utf-8-encoding indicates this double-encoding.  This is not strict analysis and is more meant for anyone who wants to check what Android/C-Core and iconv do when it comes to encoding emojis.

**Comment by adbenitez** [comment]
maybe related:
my Delta Chat since some version ago is showing repeated emojis in the emoji picker, they are emojis that has a male and female representation, but I get two male emojis instead
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by r10s** [comment]
i think this can be treated as a duplicate of https://github.com/deltachat/deltachat-android/issues/1027 - let's continue the discussion there.
