### ISSUE TITLE
Protect email configuration view

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1012]
In the email settings the password is exposed (with the eye icon), this view should be protected like the export backup option 

- Delta Chat Version: 0.510.1

**Comment by r10s** [comment]
maybe we can just not offer the eye-icon-functionality when the account is already configured.

**Comment by adbenitez** [comment]
well yeah that will be the simplest solution I guess

**Comment by Boehrsi** [comment]
I would implement that today.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/1014
