### ISSUE TITLE
Delta Chat does not come up anymore

### ISSUE THREAD

**Issue by simonsan** [deltachat/deltachat-android#1018]
- Platform: LineageOS 16.0 / Android 9 (Build 20190809-nightly) / Kernel 3.4.113 
- Device: Samsung S5 - G900F
- Delta Chat Version: 0.510.1 (F-Droid)
- Expected behavior: Delta Chat starts
- Actual behavior: Delta Chat does not start anymore (GUI does not come up)
- Steps to reproduce the problem: Click Delta Chat Icon
- Logs:

Output of  `adb logcat -v time -s DeltaChat`:

08-09 21:15:48.556 I/DeltaChat( 8141): SMTP-idle started...
08-09 21:15:48.562 I/DeltaChat( 8141): ###################### MVBOX-Thread started. ######################
08-09 21:15:48.742 I/DeltaChat( 8171): Opened "/mnt/expand/`<partition-ID>`/user/0/com.b44t.messenger/files/messenger.db".
08-09 21:15:48.745 I/DeltaChat( 8171): ###################### MVBOX-Thread started. ######################
08-09 21:15:48.746 I/DeltaChat( 8171): ###################### IMAP-Thread started. ######################
08-09 21:15:48.748 I/DeltaChat( 8171): INBOX-jobs started...
08-09 21:15:48.748 I/DeltaChat( 8171): INBOX-jobs ended.
08-09 21:15:48.750 I/DeltaChat( 8171): ###################### SENTBOX-Thread started. ######################
08-09 21:15:48.754 I/DeltaChat( 8171): ###################### SMTP-Thread started. ######################
08-09 21:15:48.755 I/DeltaChat( 8171): SMTP-jobs started...
08-09 21:15:48.755 I/DeltaChat( 8171): SMTP-jobs ended.
08-09 21:15:48.758 I/DeltaChat( 8171): SMTP-idle started...

Further Information:
I got a message of someone (Delta Chat version of communication partner is **0.304.0**). Screenshot from the persons phone below. I couldn't open the messages in this single chat anymore, actually from this messages on I was unable to open the whole chat). Delta Chat was crashing every time. After a few warnings it wouldn't start anymore. So I cleaned the cache, which was not helping. After that I tried to do a Downgrade with F-Droid, but the setup gives an error. I think somehow the database got corrupted, maybe by the emotes?

![screen-dc](https://user-images.githubusercontent.com/14062932/62804350-4b9b5f80-baed-11e9-8276-adca7068fe94.png)

Let me know, if you need any other things for diagnosing the issue. The log output does not look very meaningful.

**Comment by csb0730** [comment]
If You have the possibility try to copy messenger.db to PC.
Try to open it with a sqlite browser (for example "sqlitebrowser", debian linux).
Try to find the related message (it should be one of the last ones in the messages table).
Delete it.
save the db file.
overwrite messenger.db file at phone.

This should solve the problem.

I had a similar situation with uuencoded big messages (two years ago?).

There is a closed issue existing where I describe the repair process in details :-)

I hope this helps for You.

**Comment by simonsan** [comment]
Didn't change anything, but looks like an Update to LineageOS changed something that it's working again. I will keep an eye on if there are API/lib changes in the future to LineageOS that break Deltachat in some way and update this issue.
