### ISSUE TITLE
voice message which is shared from whatsapp isn't played

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1020]
Android 8.0.0
DC v0.510.1 from Google Play

Steps to reproduce:
- select a voice message in whatsapp
- select share this message
- select DC and a desired contact
- try to play this message (isn't played now)

Findings:
- voice message in DC has file extension ".null"
- if file is exported to a file, renamed to .aac, it can be played.

Seems to be similar to closed #916. Here the problem has been solved.

EDIT: In chat to whom the message is forwarded, this forwarded message can be played locally!

**Comment by csb0730** [comment]
If someone can give me a hint where a startpoint could be I would investigate
@r10s do You are able to assist?

**Comment by r10s** [comment]
@csb0730 of course i can review and try to get answer to questions, however, currently i am also very busy with ios and other delta-things. but there are also others around here, so i a pretty sure, you're not alone when asking for help :)

**Comment by csb0730** [comment]
@cyBerta 
Do You have a hint for me?

**Comment by r10s** [comment]
i just tried this, if was fixed by one of @cyBerta's last share-fixes and works nicely with Delta Chat 1.0
