### ISSUE TITLE
Autocrypt not working when communicating with Thunderbird/pretty Easy privacy client

### ISSUE THREAD

**Issue by mbeko** [deltachat/deltachat-android#1021]
- **Platform:** Android
- **Delta Chat version:** 0.510.1
- **Expected behavior:** When communicating with a Thunderbird client with Enigmail in pretty Easy privacy (p≡p, pEp) mode, messages should be encrypted after a first exchange as both clients claim to support Autocrypt
- **Actual behavior:** Messages are not encrypted, the public key is attached by Thunderbird with every sent mail and showed as attachment `pEpkey-${incrementing number}.asc`
- **Steps to reproduce the problem:**
  - Put Enigmail in p≡p mode via _Preferences > Privacy > Enigmail Junior Mode > Force using p≡p (Pretty Easy Privacy)_
  - Restart Thunderbird so the setting takes effect
  - Make sure that the key of the Delta Chat client doesn't exist under _Enigmail/p≡p > Key management_
  - Write messages between Delta Chat and Thunderbird

It works as expected with Thunderbird set to _Preferences > Privacy > Enigmail Junior Mode > Force using S/MIME and Enigmail_. Even if encrypted communication has already been established with that setup, it stops working after following the steps to reproduce.

**Comment by r10s** [comment]
these modes in enigmail are a bit weird, afaik, eg. pep-mode is not compatible to autocrypt.

> It works as expected with Thunderbird set to Preferences > Privacy > Enigmail Junior Mode > Force using S/MIME and Enigmail.

so, as it seems to work in general, i think, you should move this issue to thunderbird, delta chat cannot influence the modes defined by thunderbird.

closing as there is no actionable item or deltachat-android.

**Comment by mbeko** [comment]
All right, I thought maybe you'd know if I did something wrong (because isn't Autocrypt one of the main points of pEp?) or if it's a known issue because you may be in touch with the pEp people regarding Autocrypt.

So I'll report it to the pEp/Enigmail people, thanks.

**Comment by hpk42** [comment]
On Tue, Oct 29, 2019 at 14:11 -0700, mbeko wrote:
> All right, I thought maybe you'd know if I did something wrong (because isn't Autocrypt one of the main points of pEp?) or if it's a known issue because you may be in touch with the pEp people regarding Autocrypt.

I heart about considerations from the pEp engine folks to support Autocrypt 
but don't know if/how that advanced. One thing that is still pending is
that we could read key attachments (pep sends keys in attachments) and 
treat them as an Autocrypt key.  That could help with a common practise
of sending keys.

**Comment by mbeko** [comment]
Ah right, I forgot that pEp attaches the key while in Autocrypt it's all done via the headers. Thanks for the heads-up.
