### ISSUE TITLE
Voice message stops when screen locks

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1022]
IMO it should continue to play as the screen turns off.
What do you think?

**Comment by csb0730** [comment]
yes, I agree

**Comment by r10s** [comment]
yip, this may make some sense. but it may also be expected the other way round, so i would not call this a bug :)

**Comment by r10s** [comment]
okay, now i understand: if the voice message stops playing when the screen turns off by the system timeout, in fact, this should not happen.

however, when the screen is turned of _manually_, it might be be okay if playback stops.

**Comment by gerryfrancis** [comment]
https://github.com/deltachat/deltachat-android/pull/1357 was closed. Will there be a successor?

**Comment by r10s** [comment]
the idea is to add a little player to the status bar, that can exist on its own. you can pause from there and go to previous/next title (separated for voice-messages and other audio).

the player is removed when playback is stopped - that can be done in the player or as of now from the chat.

there is some code in the [old telegram-ui](https://github.com/deltachat/deltachat-android-old/), maybe there are some things that can be reused (iirc, the code was refactored that time and is not that bad as the remaining telegram code :)

**Comment by adbenitez** [comment]
this issue is open since 2019, while the promising solution of a builtin player has never arrived so far, would be good to have a temporal solution like #1357 to at least keep screen on and avoid this annoyance until the builtin arrive finally

**Comment by r10s** [comment]
let's port the player after the next release :)

**Comment by hpk42** [comment]
On Wed, Apr 28, 2021 at 12:59 -0700, Asiel Díaz Benítez wrote:
> this issue is open since 2019, while the promising solution of a builtin player has never arrived so far, would be good to have a temporal solution like #1357 to at least keep screen on and avoid this annoyance until the builtin arrive finally

+1

**Comment by Gh0stz0x** [comment]
![Screenshot_20230205_204520](https://user-images.githubusercontent.com/74795149/216841265-756b5902-82af-4db9-859a-1d6715051999.jpg)

Signal uses a player in notifications.
Couldn't you get the code from there?

**Comment by r10s** [comment]
yeah, sth. like that would be great, also for playing mp3 ... we just never came to doing it :)

**Comment by bmivzkrp** [comment]
Dear developers
Many blind users turn off the screen manually while listening to a voice message. So the current situation causes discomfort. Could you please expedite the resolution of this issue? At least - as far as possible.
I will be very grateful.

**Comment by Gh0stz0x** [comment]
@bmivzkrp 
I agree.

There is also Tiny Music Player from which you could copy the code (I haven't seen what license it has yet) 

https://github.com/martinmimigames/tiny-music-player 

It is GPL 3 🤔

@bmivzkrp Thanks for reporting this issue, I'm happy and would like Delta Chat to be as accessible as possible for the visually impaired

**Comment by gerryfrancis** [comment]
Workaround for now: Export the audio file and open it with an app that is capable of playing audio in doze mode.

**Comment by r10s** [comment]
four years later: fixed

really wondering if people can now live without this bug
