### ISSUE TITLE
Crash on missing/not working camera or sensors

### ISSUE THREAD

**Issue by lnjX** [deltachat/deltachat-android#1023]
- Platform android:
- Device: bq Aquaris U
- Delta Chat Version: `0.500.0`
- Expected behavior: Start as usual
- Actual behavior: Total application crash
- Steps to reproduce the problem: Break your sensors / cameraserver firmware
- Screenshots:
- Logs: tbd

**Comment by r10s** [comment]
> Steps to reproduce the problem: Break your sensors

+1 :)

**Comment by r10s** [comment]
probably a try-catch is missing at some point, however, [Camera.open() seems to be already fine](https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/components/camera/CameraView.java#L109).

@lnjX can you tell what exactly causes the crash? and when? just opening the app? using the build-in camera? starting the camera-intent? etc.

**Comment by lnjX** [comment]
It occured on every fourth startup I'd say. I actually only reported the problem, it occured on @jbbgameich's device.

@jbbgameich Could you try to get a log or something?

**Comment by r10s** [comment]
> Again, this device is a very special case, so not sure whether this is in the scope of delta chat to fix.

tbh, i have also no idea, what we can really do about that.
there is nor really an actionable item in this issue and the issue is a bit stale, closing it therefore.
