### ISSUE TITLE
forward one message to several recipients

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1025]
Current behavior:
- select one message
- select forward
- select a chat or a group
- go back to chat or main screen

To forward to next receipient this full batch of steps has to be repeated AND message has to be reselected again every time!

Desired behaviour:
- select one message
- select forward
- (1) select a chat or a group
(now keep selected message)
- (2) select next chat or group
- (3) select next chat or group
--> go back to chat where messag has been selected or main screen

Important with desired feature is to keep selected message selected until all recipients are choosen.

In the moment a message can only sent to multiple recipients by first creating a group.

**Comment by r10s** [comment]
seems no-one is working on that currently. i think, if needed, we can continue the discussion in the [forum](https://support.delta.chat); also as it is not only android-releated.
