### ISSUE TITLE
Sending smileys on android 4.4.4 results in garbage

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#1027]
Sent a smiley with android 4.4.4 but was received as garbage on other device (desktop) and also on recipients android (I think, @Simon-Laux)

**Comment by Simon-Laux** [comment]
maybe related:
https://support.delta.chat/t/emoji-old-new-android-arent-displayed-correctly/557/4
https://github.com/deltachat/deltachat-android/issues/1009#issuecomment-513466877

**Comment by cyBerta** [comment]
it's very likely that this issue is a duplicate of #1065 . That's why I'm closing this for now
