### ISSUE TITLE
Domain Factory mailbox integration

### ISSUE THREAD

**Issue by sniperle** [deltachat/deltachat-android#103]
I have a Domain Factory mailbox and Delta Chat is flooding my Inbox. The Chats folder isn't created nor are the mails moved to there if I create the folder manually. Maybe it's because of the special folder structure. Only the inbox is a top folder, all other folders are created as subfolders, e.g. Inbox/Chats

![mb-df](https://user-images.githubusercontent.com/3104188/27116259-746dce40-50d0-11e7-9c56-bd98bb99a94d.png)

Maybe or not the same problem as described in #28 ?!

**Comment by t-oster** [comment]
It works on DomainFactory if I change the folder (in the core sourcecode) form `Chats` to `INBOX.Chats`.
Maybe we should generally use INBOX. as prefix if the creation of the folder fails? Or we should make this configurable.
