### ISSUE TITLE
Publish a version on amazons appstore

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1030]
Amazon android hardware comes with this appstore so it might be worth it to put it tomake DC availible there, too. https://www.amazon.com/gp/feature.html?docId=1002999431&_encoding=UTF8&ref_=get_appstore&ref_=mas_rw_ldg

https://developer.amazon.com/apps-and-games

**Comment by r10s** [comment]
yip, i think once we're done with the rust core and have new android releases out there, we can go for that. probably makes some sense.

**Comment by r10s** [comment]
here we are: https://www.amazon.com/dp/B0864PKVW3/

**Comment by r10s** [comment]
this is what it looks like:

<img width=400 src=https://user-images.githubusercontent.com/9800740/77226025-369fa800-6b75-11ea-8d22-db7fdab13891.png>
