### ISSUE TITLE
Don't try to compress or change file attachment if sent as raw attachment

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1031]
Android, v0.500.0

- Current behaviour:
If attaching a video file as real file attachment DC tries to compress it and breaks down with error message "not able to handle compression of this file type" (or similar).

- Desired behaviour:
DC should not touch any file which is attached as file attachment and should simply send it.

Maybe this issue is intended for core but at the end core needs to know how the attachment is intended to send: file attachment or as dedicated file format which needs compression handling.

**Comment by r10s** [comment]
> DC should not touch any file which is attached as file attachment and should simply send it.

well, however, i think for most video files there is no chance to sent them uncompressed as they're way too large. a short 1 minute video has easily 100mb.

not sure about the error, however. this may be another issue.

we're thinking about ways to send large files in different ways, we can discuss options on that in the forum at https://support.delta.chat

finally, there is not much android can do about that.

**Comment by csb0730** [comment]
At v0.500.0 with Android 4

Tried to send an apk file to a friend by sharing it in devices file manager. But DC shows it in chat's window with a red cross. Filename "Unbekannt ...".
After pressing the send butten DC sends that file but DC replaced the current filename by current date and time with extension ".apk"

Maybe this is fixed in newer DC versions but we should check it.

**Comment by csb0730** [comment]
@r10s 
maybe reopen?

**Comment by csb0730** [comment]
@r10s 
I think this issue isn't solved. It should be reopened.
