### ISSUE TITLE
Emojis are not displayed on all phones/Emojis werden nicht auf allen Handys angezeigt

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#1032]
Hi,
 
My mobile phone: Neptune Pine, Android 4.1.2 DeltaChat 0.510.1
My wife's mobile phone: Samsung Galaxy S10, Android 9, DeltaChat 0.510.1
My sister's mobile phone: Samsung Galaxy S7, Android < 9, DeltaChat 0.510
Mobile 4: Samsung Galaxy S4, Android 9 (Lineage 16), DeltaChat 0.510.1

 
When I send Emoji's to my wife, only very few arrive. The rest is displayed as question marks (see appendix [https://up.picr.de/36730410jm.jpg(url) (below which I sent, at the top the picture of her)).
Now I thought to myself that the Emojis are a font. The fonts are stored under /system/fonts. I have compared the directories of our mobile phones. Since my mobile phone is rooted, I copied all fonts of my wife into the font directory of my mobile phone. With mit the font AndroidEmoji.ttf was saved, with her it was missing. That's why I deleted it.
After restarting both phones (the fonts remained saved), it still didn't work. I can see all her emojis, but she can't see mine.
When communicating with my sister's mobile phone, all emojis are displayed. 
With the S4, not all emojis are displayed with the S4 either.
What else can I do?
Thanks a lot!
 
Yours sincerely
 
Mike

Translate whit deepl.com
-----------Original----------
Hi,
 
Mein Handy: Neptune Pine, Android 4.1.2 DeltaChat 0.510.1
Handy meiner Frau: Samsung Galaxy S10, Android 9, DeltaChat 0.510.1
Handy meiner Schwester: Samsung Galaxy S7, Android < 9, DeltaChat 0.510
Handy 4: Samsung Galaxy S4, Android 9 (Lineage 16), DeltaChat 0.510.1

 
Wenn ich meiner Frau Emoji's schicke, kommen nur ganz wenige an. Der Rest wird als Fragezeichen dargestellt (siehe Anhang [https://up.picr.de/36730410jm.jpg(url) (unten die ich geschickt habe, oben die Darstellung bei ihr)).
Nun dachte ich mir, dass die Emojis eine Schriftart sind. Die Schriftarten sind unter /system/fonts gespeichert. Ich habe die Verzeichnisse unserer Handys verglichen. Da mein Handy gerootet ist, habe ich alle Schriftarten meiner Frau bei meinen Handy in das Schriftartverzeichnis kopiert. Bei mit war noch die Schriftart AndroidEmoji.ttf gespeichert, bei ihr fehlte diese. Deshalb habe ich sie gelöscht.
Nach einem Neustart beider Handy (die Schriftarten blieben gespeichert), hat es trotzdem nicht funktioniert. Ich kann alle ihre Emojis sehen, nur sie meine nicht.
Beim kommunizieren mit den Handy meiner Schwester werden alle Emojis angezeigt. 
Mit dem S4 werden beim S4 ebenfalls nicht alle Emojis angezeigt.
Was kann ich noch tun?
Vielen Dank!
 
Mit freundlichen Grüßen
 
Mike

**Comment by Simon-Laux** [comment]
It's probably the same issue as https://github.com/deltachat/deltachat-android/issues/1027

**Comment by Simon-Laux** [comment]
Also changing the font doesn't do anything as long as "use System Emojis instead" is deactivated in the settings. It's likely an encoding problem.

**Comment by r10s** [comment]
yip, i think this is a duplicate of https://github.com/deltachat/deltachat-android/issues/1027 - let's continue the discussion there.
