### ISSUE TITLE
Sound notifications problems

### ISSUE THREAD

**Issue by DarkMaster088** [deltachat/deltachat-android#1033]
A problem occurred to me, I have a Xiaomi Redmi 6A Android 9 Delta works fine, but when a new messages arrives 2 sounds plays at the same time, and when unlock phone and open Delta (was in background) another sound notification (too many for my taste) even the sounds aren't the same. sorry by my english.

**Comment by 19hundreds** [comment]
maybe you have an email client running which is also watching your mailbox?

**Comment by poorboy70** [comment]
I have the same problem. Using DeltaChat 0.510.1 on Redmi Note 7 with Miui 10.
Intresting: If go to Android's Setting - Notifications & status bar -App notifications - Delta Chat
I see the categorie New messages two times.
If i switch of the sound in booth i will hear the notification sound only once.
Except these i hear it 3 times..

Any suggestions how to eleminate the unnecessary "New messages" category ?

**Comment by r10s** [comment]
i assume this is related to having one sound in the notification channel and the other played directly by delta chat, we will stop the second and leave things completely up to the system with #1369
