### ISSUE TITLE
delta chat not respecting do not disturb mode

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#1034]
Android 7.0 Samsung s7 
Latest delta chat from fdroid.
Delta chat still makes new mail notification sounds when in do not disturb mode.

**Comment by webratte** [comment]
Very often I use the don't disturb mode (e.g. in cinema).
All notifications like phone calls or calendar notifications are silent.
And it's really embarrassing if I got a DC messages and the sound is playing.

Is there a chance to push this forward very soon?

**Comment by hpk42** [comment]
On Sun, Feb 09, 2020 at 05:16 -0800, webratte wrote:
> Very often I use the don't disturb mode (e.g. in cinema).
> All notifications like phone calls or calendar notifications are silent.
> And it's really embarrassing if I got a DC messages and the sound is playing.
> 
> Is there a chance to push this forward very soon?

on many phones it works but it's a known issue that setting notification
options (vibrate/led/sounds) from within Delta/Android is increasingly difficult. 

I think @r10's plan is to move towards letting the system handle notification
settings and not try anymore to override/do things from within DC.

**Comment by webratte** [comment]
DC is the only App on my phone which make trouble this way.
The missing LED notification and also the badge counter is "only" annoying.

But ignore silent mode is definitely a no go.

Sorry but I have to say:
To say letting handle the system this things is IMHO a dusty answer.

**Comment by hpk42** [comment]
On Mon, Feb 10, 2020 at 06:57 -0800, webratte wrote:
> DC is the only App on my phone which make trouble this way.
> The missing LED notification and also the badge counter is "only" annoying.
> 
> But ignore silent mode is definitely a no go.
> 
> Sorry but I have to say:
> To say letting handle the system this things is IMHO a dusty answer.

Not sure if there is a misunderstanding ... Do you really want to know
the development details? I think @r10s or others could provide them, i can't.

I just stated the high-level view: right now we have a lot of code that tries
to make notifications configurable *inside* the Delta Chat app.  And it increasingly
hits barrriers as the Android ecosystem is moving towards configuring notification
behaviour *outside* of apps.  This means we need to remove code and configurability
and rely on what the operating system allows (in terms of whether you
can configure LED colors, vibration etc.).  It would not be part anymore of
the Delta Chat In-App settings screen. This probably means several days 
of concentrated work. 

Hope this answer is less "dusty" in your ears :)

**Comment by webratte** [comment]
Of course, I understand it's not that easy.

But I (and more important, other users) see other Apps works fine. Only DC makes trouble.
Please don't misunderstand me. DC has more then 50.000 downloads in Play Store.
The time where only technical interested people uses DC is over.
"Normal" users wan't to know why DC dosn't works correctly. 

They only will see Whatsapp and Signal, or what ever, works as expected. DC does not.

I think you know what I mean.

**Comment by hpk42** [comment]
On Mon, Feb 10, 2020 at 11:09 -0800, webratte wrote:
> Of course, I understand it's not that easy.
> 
> But I (and more important, other users) see other Apps works fine. Only DC makes trouble.
> Please don't misunderstand me. DC has more then 50.000 downloads in Play Store.
> The time where only technical interested people uses DC is over.
> "Normal" users wan't to know why DC dosn't works correctly. 
> 
> They only will see Whatsapp and Signal, or what ever, works as expected. DC does not.

no question -- notifications don't work correctly on some phones. 
And i understood it annoyed you while sitting in a cinema -- hope it was a 
good movie experience nevertheless.

for now, maybe you could switch off vibration and sounds for DC? 

> I think you know what I mean.

i think so.  A little patience is needed, though.  Or someone experienced
appearing who is ready to refactor the notification integration with Android.

**Comment by webratte** [comment]
OK, so I will wait 👍

BTW. The cinema just was a easy to describe example.
In fact in sensible situations I switch off the whole phone.
There other, more complicated situations.
