### ISSUE TITLE
Remove previous text form a reply

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-android#1048]
Hello,
I'm thinking if there could be any way to remove the previous text from a reply.

I'm writing from Delta Chat to Thunderbird. When I reply FROM thuderbird I see the attached text in Delta Chat (the reply + the previous text below)

![photo_2019-10-05_10-03-54](https://user-images.githubusercontent.com/28478027/66252130-e4e69b00-e757-11e9-9f61-9d650c98d3a9.jpg)

Is there any way to remove the previous text?

**Comment by r10s** [comment]
in general, delta chat cuts out various footers, quotes etc. if the emai-client follows the standards.

not totally sure about the example, but this may lack some unique identifier and does not follow some standards.

see https://github.com/deltachat/deltachat-android/issues/81#issuecomment-299649094 for some more explanations.

**Comment by sbadux** [comment]
Ok thanks a lot. 
I'm using Hotmail through Thunderbird (in italian, if this can make a difference). Not a big issue, maybe I'm the only one with this problem.

**Comment by r10s** [comment]
closing, no direct actionable item, also more core-related.
