### ISSUE TITLE
Exported backups are not visible over MTP

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#1050]
This is a known bug on android that some files are not shown over mtp, see https://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp. What seems to be the problem, and why google never fixed this, is that somehow the app itself when creating a file needs to do it in a special way so that it's getting into the MTP index. Sounds like MTP is a dump of shit, but needing to clear my mediastorage cache and rebooting my device to see that file is not really userfriendly too. 

I have an old device so no idea how it behaves on newer devices/androids, but probably the same.

**Comment by r10s** [comment]
it is an android bug.

there is a "file announcement", however, this does not really fix the problem, we did this in the old ui, see https://github.com/deltachat/deltachat-android-old/blob/0d0f9edbe9c0283c9bd8706f179abdf95206e718/MessengerProj/src/main/java/com/b44t/messenger/SettingsAdvFragment.java#L587 , however, tbh, i have not seen any improvement on system having that bug. so we did not add this to the new ui.

you may have have same problem when trying to download photos taken from the camera.

i always do a reboot in all cases where i want to access sth. via mtp.

**Comment by r10s** [comment]
closing, no actionable item.

**Comment by Jikstra** [comment]
mtp is a desaster.

**Comment by SebiderSushi** [comment]
What i usually do to make new files appear in MTP is "Rescan Media" in the proprietary file manager FX (package `nextapp.fx`) that i use. If you don't (want to) use this application there also is [SD Scanner available on F-Droid.](https://f-droid.org/en/packages/com.gmail.jerickson314.sdscanner/)

And for large transfers i usually rebot to TWRP, the MTP in there is much more reliable and quicker.
Again, this depends on whether you (can/want to) use TWRP...
