### ISSUE TITLE
Is Socks Proxy Support in the Roadmap?

### ISSUE THREAD

**Issue by Adrianzo** [deltachat/deltachat-android#1066]
something in the lines of [this](https://mstajbakhsh.ir/my-contribution-in-k9-android-mail-client/) would be useful for securing group communications. thanks!

**Comment by r10s** [comment]
hi @Adrianzo, welcome!

there are no no concrete plans for the next weeks or months of ppl i know. but these things may change quickly if someone really starts doing things on that. maybe you can help on this issue?

and, if you define "roadmap" as things someone has thought+talked about, yes, this happens already several times :)

in general, please use the support forum for questions and discussion. the support forum is also cross-platform, which also makes much more sense on general questions or feature requests.

https://support.delta.chat (you can log in with your github account)

**Comment by r10s** [comment]
i think, if needed, we can continue the discussion in the [forum](https://support.delta.chat); also as it is not only android-releated
