### ISSUE TITLE
Video format

### ISSUE THREAD

**Issue by reno-a** [deltachat/deltachat-android#107]
Hello,
When I filming with stock camera application, the video format is MP4.
When I filming with Delta Chat, the video format is MOV.
Is it possible make MP4 video in DeltaChat ? (and how?)
Than-you,

**Comment by r10s** [comment]
I've just tested it (and send the video to the wrong person accidentally ...) - and all Videos are MP4 on my device. No MOV anywhere.

**Comment by Almtesh** [comment]
Yes, and I anwsered with a video too and it's mp4 too (so no MOV for me either).
The file command returns `ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]`.

**Comment by reno-a** [comment]
Hello, @r10s @Almtesh 
You're right. I try again and the video is MP4.
Sorry, it's probably my mistake.
I close the subject.
