### ISSUE TITLE
preserve selection when new messages come in

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1071]
- You don't see what messages you have selected
- Bug: you can select the same message multiple times and the counter of selected messages will increase indefinitely.

**Comment by r10s** [comment]
how can you reproduce this bug? 
if i try to select a selected message a second time, it gets deselected and the counter decreases.

**Comment by Simon-Laux** [comment]
select message a then message b then message a again and so on

**Comment by r10s** [comment]
> then message a again

hm, this deselects message a for me. 
can you reproduce this on different devices? maybe it happens on some android versions?

**Comment by Simon-Laux** [comment]
It's a very rare bug that appears sometimes after spam touching.
The more common bug with spam touching is that the counter stays at a higher number even when all messages look deselected.
I would say this could be a reason to review that code part again, but it's nothing urgent.

**Comment by adbenitez** [comment]
actually I face this bug quite often, and it is easy to reproduce:
1. Select some messages
2. Receive a new message from any chat
3. Current selection disappears, but selection counter is preserved and top bar still is in select mode
4. Select previously selected messages again

**Comment by r10s** [comment]
@adbenitez thanks for clarifying, this is pretty useful :)

**Comment by agutierrez25249** [comment]
Another way to cause the same effect. 
. Select a memsage 
. Then scroll through many messages 
. Then flies at the beginning

This causes the same effect

**Comment by agutierrez25249** [comment]
Also when you click send, and when the message is sent, 
Apparently anything that causes an update of the chat view causes this error in the selection of a message.
