### ISSUE TITLE
Chats folder not created or used

### ISSUE THREAD

**Issue by svictor9** [deltachat/deltachat-android#108]
Delta Chat did not create a "chats" folder, neither on my (self-hosted) server, nor on my wife’s gmail account. All our chats arrive currently in Inbox. We have version 0.9.0 from Fdroid (I think  we started with 0.1.36). Should we create the "chats" folder manually?

**Comment by r10s** [comment]
On gmail, the folder is not created currently, on the self-hosted, it should (except, if you're using a gmail or googlemail address, see https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_configure.c#L494 )

**Comment by allo-** [comment]
Same problem here. And on a newly created account it didn't create a sent folder (and displayed an error it cannot find one). There is an IMAP command (in newer RFCs?) to find the name of the sent folder on a server, this may be used to create one if neccessary.

**Comment by licaon-kter** [comment]
Same problem on self-hosted here.

Where should this magical "Chats" folder be actually located?

**Comment by phormanns** [comment]
Same problem with "Dovecot" IMAP server. Normaly all folders are prefixed with "INBOX.". I didn't find any code respecting that. DeltaChat should create a folder "INBOX.Chats" and put its messages there.

**Comment by r10s** [comment]
Is putting outgoing messages to `INBOX.Chats` a good idea? At least it may look a little illogical.

**Comment by phormanns** [comment]
Why? I would like to separate all chat messages from emails. So deltachat should move incomming messages to the folder INDOX.Chats and put outgoing messages to the same folder. 
In normal email usage I move all email messages, incoming and outgoing, belonging to the same thread in one folder.

**Comment by r10s** [comment]
> Why?

Just because of the name _IN_ BOX ... from INcoming ...
But I understand the point that it is very useful to keep things together.

**Comment by phormanns** [comment]
Ok, the important points I could not mediate:
In IMAP servers there is a folder hierarchy. The root folder mostly is called "INBOX", but this is a server configuration. IMAP clients only create subfolders to INBOX. So the standard folders are INBOX, INBOX.Sent, INBOX.Drafts, INBOX.Trash and so on. Therefore DeltaChat should create INBOX.Chats in this hierarchy. But everythig is configurable: common separators are "." and "/". "INBOX" could be "#mbox" and so on.

**Comment by STPKITT** [comment]
Separate folders might be useful when dealing with Delta Chat content from a standard E-Mail-client or webmail. To the user experience in Delta Chat it would make no difference since Delta Chat would show those two folders combined.

**Comment by r10s** [comment]
> INBOX. So the standard folders are INBOX, INBOX.Sent, INBOX.Drafts, INBOX.Trash and so on.

Ahh, okay, didn't know this (or forgot it ;)

**Comment by csb0730** [comment]
Hello all,
I'm using gmx an here are all these folders in root, not as subfolders.

Only for Information



Am 5. Oktober 2017 14:55:27 MESZ schrieb "Björn Petersen" <notifications@github.com>:
>> INBOX. So the standard folders are INBOX, INBOX.Sent, INBOX.Drafts,
>INBOX.Trash and so on.
>
>Ahh, okay, didn't know this (or forgot it ;)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-android/issues/108#issuecomment-334456050

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by phormanns** [comment]
> I'm using gmx an here are all these folders in root, not as subfolders.

You are right. I tried a gmx account: The "Chats" folder is created.

**Comment by hewi1** [comment]
Take a look at SMS Backup+. Those guys archive SMS in email folder. It works even in Gmail. https://github.com/jberkel/sms-backup-plus

**Comment by r10s** [comment]
@hewi1 good hint, I will have a look at this as soon as this issue gets into my focus again ...

**Comment by cryptix** [comment]
Also a dovecot user here.

I have a `Chats` folder in the root of my account and my outgoing message go there but incoming once stay in `INBOX`. 

I tried to manually create `INBOX.Chats` to see if they are moved there but that didn't help either.
Also the incoming mail's aren't marked as read.

(ps for future reference: it is fine to move them manually, I think I might deploy a rule based on the subject to move them until this is fixed)

**Comment by ericzolf** [comment]
This issue is quite a show stopper for using Delta Chat: I don't want to have another email address but I also don't want chat messages to pollute my inbox (or even less the one of friends). I also have dovecot and sieve and would need to be able to filter out all chat-mails to a specific folder for Delta Chat to use them (this should also work with gmail BTW). Thanks!

**Comment by r10s** [comment]
Yeah - we should fix this. To make things more visible, and not to be forgotten I've just added the Milestone-Tag "Release 1.0" just now (btw. I wish I could move issues to different repositores, in fact, this belongs to deltachat-core)

**Comment by r10s** [comment]
folders are not created below INBOX if normal creation fails, this should fix this problem in the upcoming release (0.18.0 or later)
if not, please feel free to re-open this issue.
