### ISSUE TITLE
3 Dots behind every message sent from OX-Coi to Delta Chat

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1082]
**Describe the bug**
If I send a message from the OX-Coi Android App to the Delta Chat Android- and Desktop Client I have behind every message 3 Dots [...]

See also the attached screenshots

**To Reproduce**
Occurrence: always
1. Send a message via OX-Coi Android App and receive this message via Delta Chat client
2. See what I described

**App information (please complete the following information):**
 - App version: OX-Coi V. beta-2 (2002) Delta Chat V.0.510.1 
 - Delta Chat Core version: I don't know
 - Flutter version: I dont know

**Smartphone (please complete the following information):**
 - Device: Huawei nova
 - OS: Android 7.0

**Additional context**
I have no idea is this a OX issue or a Delta Chat issue.

But I'm sure the OX team and the Delta Chat team have to work together and have to keep there clients 100% compatible.
Only if the good boys work together there is a chance against the big players.

I think with Chat over E-mail there is a realistic chance to replace WhatsApp with E-mail ;-)

I also opened a issue for OX-coi:
https://github.com/open-xchange/ox-coi/issues/221

![ox-coi](https://user-images.githubusercontent.com/6864851/67359802-9a8d5880-f564-11e9-8067-d7da3c875a6b.png)
![Deltachat](https://user-images.githubusercontent.com/6864851/67359803-9a8d5880-f564-11e9-9f7b-b5a3d89a389c.png)

**Comment by hpk42** [comment]
could you get the mail source with Thunderbird or so 
of the message which is displayed with the extra "..." from DC? 
I am particularly interested in the Message-Id header.
thanks!  (sidenote: it's "sent" not "sendet" ... and don't worry - i
learned english by correcting mistake-by-mistake and still make tons ;)

**Comment by r10s** [comment]
i just tried it with OX COI beta-2 (1002) to both, Delta Chat 0.510.0 and 0.930.2 and did not see the dots.

in general, the dots appear when there is sth. truncated from the message and/or the message is not sent by a recognized mail-over-chat client.

so, yip, the source file would be interesting.

**Comment by webratte** [comment]
After hours of playing around and reinstalling OX-Coi it seems to work again.

So I will close this issue.
I will test more things. If I will find other things, I will reopen it.

**Comment by webratte** [comment]
It seems this happens, if I switch off encryption and only with my GMX Account not with Mailbox.org

**Comment by r10s** [comment]
might be that gmx adds some stuff to the mail, not sure. can you post the belonging mail source here?

**Comment by webratte** [comment]
Here are the concerned messages.

One is the sent message from the deltachat folder in the GMX account.
And the other is the received message from the deltachat folder in the mailbox.org account.

[messagesGMXtoMAILBOX_ORG.zip](https://github.com/deltachat/deltachat-android/files/3765821/messagesGMXtoMAILBOX_ORG.zip)

**Comment by r10s** [comment]
hm, seems as if the signature does not follow the [signature convention](https://en.wikipedia.org/wiki/Signature_block#Signatures_in_Usenet_postings), we assume a signature to start with the characters `-- \n` to be recognized as such.

the ox-signature is introduced by just two minus, formatted as `=2D-` - the space is missing - therefore the stuff is truncated, but as we cannot be 100% sure that this is correct, the truncation is shown to the user.

so i'd say, ox should figure that out - or are there some reasons for that? where does this come from? ping @mneumann @Boehrsi @robert-virkus

**Comment by webratte** [comment]
I can reproduce this `=2D-\n` by sending a message with Thunderbird (Autocrypt is on).

**Comment by r10s** [comment]
okay, thanks for coming back.

do you get this `=2D-\n` also when sending using Delta Chat on GMX?
in this case, we can assume a core issue as the the bad behavior is the same for ox and Delta Chat.
otherwise, it seems to be a ox-only-issue.

showing the three points as such is correct on the given input.

**Comment by webratte** [comment]
Just installed DC on a test phone and GMX as account.
If I switch off encryption I can see the three dots.

I have not checked the source text.

But I think it will be the same problem.

**Comment by r10s** [comment]
k, so

- it is not a compatibility problem, delta and ox behave similar
- core-rust uses [`-- \n`](https://github.com/deltachat/deltachat-core-rust/blob/master/src/mimefactory.rs#L464) as signature divider which is handled correctly on delta and ox
- it happens with gmx only
- it happens only for unencrypted mails
- showing the three dots as such is correct on the given input

maybe gmx rewrites the body? and replaces `-- \n` by `2D-\n` for some reasons (i cannot imagine any, however)

**Comment by webratte** [comment]
Another test.

Sending via k9, GMX, unencrypted, signature and autocrypt on (key on the header) works as expected. No three dots.

Later I will provide the source text of a message sent by k9 to compare with message sent by DC.

**Comment by webratte** [comment]
here the promised mail
[sentByK9.zip](https://github.com/deltachat/deltachat-android/files/3774570/sentByK9.zip)

**Comment by r10s** [comment]
k9 uses a different content encoding, so maybe this is not directly comparable. gmx may change the one but not the other.

hard to say who is doing sth. "wrong" here, however, is this happens only for gmx, this seem to be a strong hint. maybe there are some ox imap specialists who have an idea.
