### ISSUE TITLE
Error when opening profile of contact I have not active 1:1 chat with

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1085]
When I try to see the profile of a contact I have no 1:1 chat, the profile is shown, but a toast with this error message is shown:
```
Failed to get chat: Sqlite Error: QueryReturnedNoRows
```

- Android version: 7
- Delta Chat version: 0.930.2

**Comment by r10s** [comment]
probably a bit too nervous core-rust :) i'll have a look tomorrow.
