### ISSUE TITLE
Email address as IMAP login name uses only username

### ISSUE THREAD

**Issue by samtuke** [deltachat/deltachat-android#1086]
It appears that when using an email address as an IMAP / SMTP user name, only the first part of the address (the email username) is used. Eg `name` instead of `name@domain.com` is used. 

This is my conclusion from viewing the attached error mesage (the provided login name as mail@domain.com).

- Android version:
- Device: Huawei BTV-DL09
- Delta Chat version: 0.510.1

![IMG_20191024_220933](https://user-images.githubusercontent.com/695422/67523308-b9980180-f6ae-11e9-8658-1959e6762206.png)

```
device=HUAWEI BTV-DL09 (BEETHOVEN)
android=7.0 (C100B311, BTV-DL09C100B311)
sdk=24
memory=10M (21.84% free, 512M max)
memoryClass=384
host=wuhjk0381cna
applicationId=chat.delta
app=Delta Chat 0.510.1-gplay
installer=com.android.vending
ignoreBatteryOptimizations=false

deltachat_core_version=v0.45.0
sqlite_version=3.26.0
sqlite_thread_safe=1
libetpan_version=1.8
openssl_version=1.0.1t
rpgp_enabled=0
compile_date=Jul  9 2019, 17:20:36
arch=32
number_of_chats=0
number_of_chat_messages=0
messages_in_contact_requests=0
number_of_contacts=0
database_dir=/data/user/0/chat.delta/files/messenger.db
database_version=55
blobdir=/data/user/0/chat.delta/files/messenger.db-blobs
display_name=0
is_configured=0
entered_account_settings=mail@domain.com mail@domain.com:***:mail.gandi.net:143 mail@domain.com:***:mail.gandi.net:25 0
used_account_settings=0 0:0:0:0 0:0:0:0 0
inbox_watch=1
sentbox_watch=1
mvbox_watch=1
mvbox_move=1
folders_configured=0
configured_sentbox_folder=<unset>
configured_mvbox_folder=<unset>
show_emails=0
mdns_enabled=1
e2ee_enabled=1
private_key_count=0
public_key_count=0
fingerprint=<Not yet calculated>
```

**Comment by r10s** [comment]
hi @samtuke, thanks for filing the issue.

the combination "only username" is only probed if the "full email address" has already failed; this is needed as some servers expect exactly this.

so the problem is probably another one.

but i agree that the shown messages should be different on that.

**Comment by samtuke** [comment]
Thanks for the speedy clarification
