### ISSUE TITLE
Location streaming does not work with 0.930.2

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1087]
When I enable location streaming, either in chat with myself or in chat with my other account, the client sends the message notifying that location streaming is enabled, but no messages with `location.kml`.

Also, messages from other users with `location.kml` are not processed, as no locations are found in the sqlite database after backup export.

It is still possible to send `message.kml` by clicking on the map and writing a message.

**Comment by cyBerta** [comment]
Closing here as it appears to be an core issue. 

Discussion continues here: https://github.com/deltachat/deltachat-core-rust/issues/757

**Comment by cyBerta** [comment]
I reopened the issue to keep it visible as unresolved issue with impact on DC Android.

**Comment by cyBerta** [comment]
location streaming was fixed in core
