### ISSUE TITLE
Crash while first log in

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1089]
- Android version: 9
- Device: Sony Xperia XZ1
- Delta Chat version: 0.501.1 (play store)
- Expected behavior: initial log in should work
- Actual behavior: crash by log in
- Steps to reproduce the problem:
1. Start DC
2. Add a GMX address
3. Add your password
4. The spinner starts to turn and count to 100%
5. chrash
- Screenshots: not needed
- Logs: I can't provide logs.

**Comment by r10s** [comment]
does the same happen also for 0.930.2?

**Comment by webratte** [comment]
I don't know. It happens on a phone of a friend of me.
There I can't sideload apps.

Probably I have to wait until you release the next version in Google
play store

**Comment by r10s** [comment]
there is https://github.com/orgs/deltachat/projects/15 where the progress can be followed.

**Comment by webratte** [comment]
Thank you.

If I understand correctly the next version will released if todo is zero?!

**Comment by r10s** [comment]
plus-minus, yes :)

**Comment by webratte** [comment]
Probably the same issue as https://github.com/deltachat/deltachat-android/issues/879

**Comment by r10s** [comment]
okay, so i close this in favor to #879
