### ISSUE TITLE
Check marks

### ISSUE THREAD

**Issue by Rochambeau** [deltachat/deltachat-android#109]
In earlier versions of deltachat there was an option to enable/disable read reciepts. Since this functionality hadn't been implemented, the option was removed. 

What are the plans to include this feature again?

**Comment by JobbeDeluxe** [comment]
#105

**Comment by r10s** [comment]
Read receipts will be available in 0.9.3.

**Comment by r10s** [comment]
Some background information: https://github.com/deltachat/deltachat-android/issues/113
