### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by rizzopablo** [deltachat/deltachat-android#110]
Though I try not to use gplay, but to install everything from F-Droid, most friends still use gplay. When do you estimate to publish Delta in the google platform?
Thanks

**Comment by r10s** [comment]
When testing is done so far and we have a stable 1.0. Maybe in one or two months, maybe sooner, it depends (however, not just before my holidays :-o

In between, we push F-Droid :-)

**Comment by kskarthik** [comment]
I feel the problem is  that most people use gmail. They usually complaint that their inbox is getting filled up with DC msgs. Any update on this bug? (can't call it bug, Google's fault). all guys comment about this in & may give low ratings. We need to be careful before launching on play store.

**Comment by r10s** [comment]
I fully agree, we have to check gmail over before launching in Play Store.

**Comment by kskarthik** [comment]
@r10s I observed that two folders were created named `imap/trash` & `imap/sent` I am using aosp mail client. So, you should also add function for delta chat folder as imap/chats instead of chats if the user uses gmail.

**Comment by rizzopablo** [comment]
What about the debate about using in-reply-to, with some limit to avoid infinite/very large threads? This would address the flooded up folders/inbox problem too.

**Comment by r10s** [comment]
In-Reply-To does not work, however, we're working on another solution which will be available for testing in 0.9.2

**Comment by r10s** [comment]
in between, we have a milestone for an 1.0 release that should also go to the Google Play store then: https://github.com/deltachat/deltachat-android/milestone/1 -
