### ISSUE TITLE
Really laggy and drains battery

### ISSUE THREAD

**Issue by buddabrod** [deltachat/deltachat-android#1101]
- Android version: LineageOS 15.1, built on October 27 in 2019
- Device: Sony XPeria SP (Huashan)
- Delta Chat version: 0.510.1 (F-Droid)
- Expected behavior: Should work smoothly and not drain battery :-)
- Actual behavior: the opposite
- Steps to reproduce the problem:
Open Deltachat. Sometimes it takes a minute with a blank screen, until I see the list of conversations (I only have one). Then open the conversation, wait another 20-60 seconds. This does not always happen, sometimes it's even fast.

Sending/receiving messages regularly makes the device freeze for a few seconds.

I am not sure if it is linked to this version, because some weeks ago it worked fast. Maybe I hit a internal message count/size related barrier, which leads to bad slowdowns on this old devices?

I am using my own mailserver (dovecot) and see nothing suspicious there. The log looks really strange compared to how it looks on my wife's (way more powerful) device using the same mail server. She does not have all those "Interrupting SMTP-idle.." entries.

I went through "backup->reset delta chat and import backup", but it is of no use. 

This will also drain my phone's battery within a day.

[deltachat.log](https://github.com/deltachat/deltachat-android/files/3798049/deltachat.log)

**Comment by r10s** [comment]
hi @buddabrod - thanks for reporting

wow, there are more than 3.5 millon jobs-ids, all releated to location streaming. not sure if pending or just records in the table. 

however, as the job things are completely rewritten, i do not think it is worth researching for the reason.

i would recommend to try over with the 0.940.2 beta - however, maybe better do a new installation without import as otherwise the jobs will be pulled over to the new version.

**Comment by buddabrod** [comment]
hi @r10s thanks for your reply.

I have tried location streaming in the past, but there were some problem which I don't really remember. Didn't bother to report, since it's flagged as experimental.

I will try the beta, thanks for the hint!

**Comment by buddabrod** [comment]
Deleting the data and doing a fresh setup also works on 0.510.1, sad thing is that no old messages are shown although I use the same key as before. Seems like I have to live with that..

It would be neat if there was an option like "scan existing messages", that restores the chat history.

I'll try the beta some time this weekend. Thanks again for that great app!

**Comment by webratte** [comment]
As a workaround you could move your DC messages from the imap folder "deltachat" into the inbox.

So DC will think that's are new messages and show all messages again in the app.

I'm not sure if you have they back again into the "deltachat" folder.

**Comment by r10s** [comment]
> scan existing messages

yip, this would be nice to have :)

**Comment by buddabrod** [comment]
> As a workaround you could move your DC messages from the imap folder "deltachat" into the inbox. So DC will think that's are new messages and show all messages again in the app. I'm not sure if you have they move back again into the "deltachat" folder manually.

Of course xD It's working, thanks. Just takes some time.. Delta first seems to import the mails in batches of a few thousand something? and then even moves them into the DeltaChat folder without (!) resending any confirmations :-)

**Comment by buddabrod** [comment]
Delta Chat 0.510.1 finished importing and moving all messages after about three hours. I can confirm that it works as expected. A slight bit slower than without messages ;-D, but lagfree, no logspam, and overall very fast, so it was definitely some leftover from me playing around with experimental options :-)

Thanks for your support!

**Comment by r10s** [comment]
you're welcome, thanks for coming back to this!
