### ISSUE TITLE
BCC messages stay in the inbox

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1103]
- Platform (android/blackberry/anbox): Android 9
- Device: Samsung Galaxy S8
- Delta Chat Version: 0.940.2
- Expected behavior: If I have enabled "send copy to self", BCC sent messages should moved to the deltachat folder
- Actual behavior: they stay in the inbox
- Steps to reproduce the problem: send a message and take a look in the inbox.

- Logs: If you need logs, I can it offer later.

**Comment by webratte** [comment]
It seems this is fixed in https://github.com/deltachat/deltachat-core-rust/pull/898

So I will close this issue.

**Comment by r10s** [comment]
thanks for re-checking, @webratte :)
