### ISSUE TITLE
No notifications after a few minutes standby of the phone

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1104]
- Android version: Android 9
- Device: Samsung Galaxy S8
- Delta Chat version: 0.940.2
- Expected behavior: Notification for incoming messages
- Actual behavior: No notification if the phone is in standby for a few minutes. I have played around with all battery saving options and turned all off.

- Steps to reproduce the problem:
1. set the phone in standby
2. wait 15-30 minutes
3. receive a message
4. you got no notification
- Screenshots:
- Logs:
I will create a log and post it here later

**Comment by webratte** [comment]
Here are the log.

- Roudabout 18:30 I switched off the screen
- 18:45 I sent the test message
- 19:00 I unlocked the phone and opened DC. This was the moment I received the test message

[2019-11-03-19-08.zip](https://github.com/deltachat/deltachat-android/files/3801963/2019-11-03-19-08.zip)

**Comment by r10s** [comment]
seems as if samsung is very good on killing things :/ https://dontkillmyapp.com/samsung

maybe you can check out the information.
might be that samsung kills apps unconditionally, [seems as if manufactors do that to squeeze a little extra battery out of their phones](https://dontkillmyapp.com) - with huge drawbacks, obviously.

as it is harder and harder to get a reliable background task, maybe we should switch to a timer at some point to get some reliable basic checks.

**Comment by r10s** [comment]
cmp https://github.com/deltachat/deltachat-android/issues/1105

**Comment by webratte** [comment]
This sounds like really bad news.
So it seems there is no way to run DC reasonable in Background 😱

**Comment by r10s** [comment]
> So it seems there is no way to run DC reasonable in Background 

depends on the device manufactor who made their devices ["becoming dumbphones again"](https://dontkillmyapp.com/problem) - or not.

**Comment by webratte** [comment]
I have tested Version 0.960.0 on a fresh factory reseted Samsung Galaxy S8 Android 9.
All settings (phone and DC) default.

And it works 👍

Thank you.
