### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#111]
Translating Delta Chat can now also be done via Transifex, a collaborative localisation platform that seems to be widely used.

Our page there: <https://www.transifex.com/delta-chat/delta-chat-android/> - Thanks to Transifex supporting Open Source projects!

I've uploaded the existing translations, but, to be honest, I do not know much about the system.

So, I would be glad, if someone else can maintain the page. Maybe one of the existing translators?

**Comment by guland2000** [comment]
Page not found ((( and link is broken
![screenshot from 2017-06-28 19-57-39](https://user-images.githubusercontent.com/10272327/27652511-5c559834-5c3c-11e7-8ebf-4021cfa4fbb9.png)

**Comment by r10s** [comment]
Can you retry please? Works for  me ...

**Comment by guland2000** [comment]
No... i dont now, why.Same thing.

**Comment by licaon-kter** [comment]
Same 404 here, can you try in a "Private window"? Maybe if you're logged in it works, maybe you did not yet publish it for public access or something.

**Comment by r10s** [comment]
Hmm. Works for me on a clean device without login.

Does it work for _anyone_ else here??

**Comment by r10s** [comment]
Or is anyone else using transifex here? I would happily make him a collaborateuerm

**Comment by licaon-kter** [comment]
It's ok now! :)

**Comment by r10s** [comment]
Fine - we also got translators for Russian, Polish and German :-)

**Comment by calbasi** [comment]
U use transifex, but not in an advanced mode :-) But if I can help you, just tell me. By now, I'm going to try to translate some strings to Catalan and Spanish ;-)

**Comment by r10s** [comment]
Thank you, I would be glad to make you a collaborator. (I'm not in  the office at the moment, ao I cannot check it out now. It may be helpful if you send me your transifex name)

**Comment by calbasi** [comment]
Hi @r10s , I've applied to be a collaborator from Transifex interface... My nick is calbasi . And I ask for a new language, Catalan. I think you should accept both :-)
Regards

**Comment by r10s** [comment]
Hi @calbasi , I've made you a "Project Maintainer" on Transifex. Feel free to do everything what is needed to do. And let me know, if these rights are not even sufficient. My email address is r10s at b44t dot com

**Comment by luisfsr** [comment]
I couldn't find the page...

**Comment by r10s** [comment]
Do you have you still problems? Seems as if the connection to Transifex is weired from time to time ...

**Comment by luisfsr** [comment]
I just tried to access delta-chat page on transifex and it returned a 404 error.

**Comment by calbasi** [comment]
Try this: https://www.transifex.com/delta-chat/delta-chat-android/

**Comment by r10s** [comment]
Great :-)

**Comment by luisfsr** [comment]
Working! :)

**Comment by sbadux** [comment]
Page not found from https://www.transifex.com/delta-chat/

It works from https://www.transifex.com/delta-chat/delta-chat-android/

**Comment by licaon-kter** [comment]
Works fine here, no 404s.

**Comment by r10s** [comment]
Funny, it always works for me. Maybe one of the people with problems can post a bug report to Transifex?

However, I've changed the URLs to https://www.transifex.com/delta-chat/delta-chat-android/ which seems to work everywhere.

**Comment by sbadux** [comment]
Hi, I've translated most of the untranslated strings (italian). There are 5 strings that I can't translate because I can't save my translation, the Save button doesn't appears. It's a pity to leave only 5 strings untranslated. Can you help me?

**Comment by r10s** [comment]
Ciao @sbadux !

The missing strings are strings with plural forms, you have to enter two translations per string  (eg. _1 contact_ and _2 contact**s**_). To switch between the strings you have to click the buttons `1` and  `other` top right of the field.

![bildschirmfoto vom 2017-07-15 19-41-20](https://user-images.githubusercontent.com/9800740/28241479-9dc5a618-6995-11e7-9116-da06bb04271c.png)

As soon as you've entered both forms, the save buttons should become clickable.

**Comment by sbadux** [comment]
Thank you very much for your help @r10s! I never used this function on Transifex.

Now Delta Chat is fully translated in italian :+1:

**Comment by r10s** [comment]
Great! It will be avalabe in 0.9.4 then (0.9.3 is already on the way to F-Droid). Regarding Transifex: is it easy to use and a benefit for Delta? (I have no experiences with it)

**Comment by sbadux** [comment]
Yes, IMHO It's a huge benefit because a lot of people use it. I'm using it for translating other projects like Xfce, calibre, supertux and others and it's familiar for me.
To be honest, I wouldn't have translated your app without Transifex or CrowdIn. I'm happy to help but I can't install Android Studio (I don't even know exactly what it is) only for translating a hundred strings :-)

**Comment by luisfsr** [comment]
@r10s, transifex works great. I'm translating some few strings left of the portuguese xml and revising the ones already translated, which is a lot easier with transifex.

**Comment by guland2000** [comment]
Since from today Russian language is 100%

**Comment by r10s** [comment]
Great! I will add them to the next verison. There will be some additional strings regarding the status needed the next days (see #97), however, I believe for 1.0 we're close to being feature-complete then :-)
