### ISSUE TITLE
check if different minSdkVersions for 32/64bit are okay

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1118]
to support a wide range of devices, we have a lower sdk-version for 32bit than or 64bit

- 64bit requires to target at least sdk21 (android 5, lollipop) - so we cannot get lower
- for 32bit we allow devices down to sdk18 (android 4.3, partly jelly bean)
- the overall app is targeted with sdk18 in build.gradle. 

the question is if this is sufficient, telegram-foss does some [min-version-sheanigans in build.gradle](https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/build.gradle#L151) - but does a lollipop with 64 bit exists? or which combinations can cause troubles?

**Comment by cyBerta** [comment]
There are no 64 bit phones running Android Kitkat or lower. Android's support for 64 bit started with Android 5 (Lollipop).

The mentioned telegram-foss example makes use of stripped down apks including only native binaries for one architecture. We had a similar discussion about this possibility wrt the download and storage size, but it's another issue. 

With regard to the question - I think we're fine having a default minSdk of 18.

**Comment by darkestDark** [comment]
i think an arm64 support for device less than nougat is useless. If it is a flagship wit
