### ISSUE TITLE
Not all text of a mail (subject and content) is shown - add option?

### ISSUE THREAD

**Issue by Foxdelmar** [deltachat/deltachat-android#112]
Hi everyone,
this app looks great and I really like that you are pushing the development.

I did some tests and want to give you the feedback that is most important in my opinion:

when I send a delta-chat message to someone else and he uses Thunderbird and answers me, i sometime get the subject, sometimes the content of the mail and sometimes only a small bit of the mailcontent.

Could you add an option that the whole mail, including the subject is visible within a chat log?
I saw that I can watch the whole mail when I long press the message and tap in the menu on "Info". But in my opinion there should be an option to bring the whole content to the chatlog. I want to make sure that I never miss something that a non-Delta-Chat (Outlook, Thunderbird) contact is sending me.

Maybe you can use colors or set the color to grey for every word that Delta Chat would normally exclude from the chat view. This option would also be good for testing/debugging.

Or you show the content to show always in Bold:

example:
Subject: **This is a test message**
Content: **and here the text starts of the message**

best regards
Fox

**Comment by Hocceruser** [comment]
On my device, up to now, Delta Chat always showed the message's content and it just cut off something like "On Sunday, 2 July XY sent: ...". This makes sense because you can see what you sent in Delta Chat's log.

Also I assume that I would realize it if important information was cut off or in the subject (because I would simply not understand the content 😁)

But of course an option like you suggested would not harm anybody 😉 and maybe some day it will become useful for me as well, I just think that it is not that important.

**Comment by Foxdelmar** [comment]
But in my case I had a bad behaviour.
I replied to a Delta Chat Message via Thunderbird and the Delta Chat Log shows only "Am 02.07.2017 um 19:12 schrieb blablabla@mail.de:" and there it ends. The mail continues with the quotation of the former mail that is excluded from the delta chat log. Delta Chat seems to ignore the lines because they begin with ">"
"> First Delta chat first line
> First Delta chat last line"

In the mail I added text to the Subject and changed nothing in the content of the mailtext. So here information is lost if a chat/mail partner ist only using/changing the Subject. Maybe this could be corrected. I know some people who write short mails and only use the subject.

My subject was something like: "Chat: Larifari jaskldjfklasjd asjdkflasjd".

**Comment by Hocceruser** [comment]
Foxdelmar wrote:
> I know some people who write short mails and only use the subject.
Of course this is a potential problem, I did not think about this.

What about this idea: If the subject was changed (and not only Re: or AW: or something was added) DC also shows the subject.

Or do you think that an option to show the whole mail content and subject would be better? Or both an option and this?

**Comment by Foxdelmar** [comment]
> What about this idea: If the subject was changed (and not only Re: or AW: or something was added) DC also shows the subject.
I like your idea. 

--> never show the subject if there is no difference to the earlier one apart from a list of prefixes like "Re: ", "AW: ", ...

> Or do you think that an option to show the whole mail content and subject would be better? Or both an option and this?
--> not necassarily if there is no difference in the subject or mailcontent.

So the app should always compare the latest inbound with the last inbound and the latest outbound mail.

**Comment by csb0730** [comment]
I can confirm this. Foxdelmar is right.
Sometimes I'm using only the _subject_ to indicate short issues too. So it would be useful to compare the _subjects_ and show them if a change has been detected (as proposed above).

**Comment by csb0730** [comment]
Hi @r10s ,
if the MUA is not DC then all this is getting important. I have some friend who only uses non DC MUA and here I always have to check by _Info_ the complete message including subject to get correct information.

Maybe
 a) showing always the subject text appropriate if opposite MUA is not DC? or
 b) an option to activate subject always by chat partner?

One of these solutions should be available.

**Comment by r10s** [comment]
Unless there are additional volunteers, I do not think we have the resources to do much on this issue before 1.0.
Maybe three dots indicating that something was cutted is sufficient? As mentioned above, the full text is already available.

**Comment by r10s** [comment]
> Maybe three dots indicating that something was cutted is sufficient? As mentioned above, the full text is already available.

this is done with https://github.com/deltachat/deltachat-core/commit/7b135c3fce55f4ca27132b46071c268695f8409a :

![ellipsis](https://user-images.githubusercontent.com/9800740/37232529-abda6350-23ef-11e8-8aa5-efa93188479f.png)

Regarding the subject, this is shown when it does not start with _Re:_ etc - or via the Info function.

I think, this solution fixes the problem that one does not get informed about additional content. To make showing the additional content more convenient and nicer should be another issue. However, I think, this won't be important for a Release 1.0, then.

**Comment by testbird** [comment]
The […] solution is a great. :)


Re-reading this issue I suspect that this is where I may have unmindfully tickled you a bit. To explain, I didn't think it would be a large deal adding it to the 1.0 milestone, as I thought not showing part of the message is a clear thing an adding it had simply been forgotten. If the issue first wasn't thought to be of larger importance, it would be good example how selecting the user-impact labels correctly assessed the importance, and now already helped to avoid future user frustration.

In the example you write about full quotes. As I understood the issue it was about MUA responses with message content in the subject. Does the solution cover this? What I had thought about was to cut of the usual Re: and Chat: prefixes from the subject and then cut off the remaining subject from the regular message content. (Which I thought could remove the redundancy from the deltachat messages, and simple replies of MUAs, but retain changed subjects.)

Oh just thought about it, maybe clicking the dots could directly open the full message text (info).

**Comment by JonasDralle** [comment]
I think this is very good.

Can we replace `...` (tree dots) with `…` (horizontal ellipsis)?
It's UTF8 char `U+2026`

--

@testbird used `U+2026` in his entries to reason about the ellipsis. Yet the implementation uses three dots.

I would open a pull request but I don't know where this is implemented. Searching for `[...]` both in core and in android yielded no results (GH on-side search)

**Comment by testbird** [comment]
BTW, there seem to exist some (outlook?) TOFU mails, forwarded, including a long history of responses from others that does not seem to get cut out. (Users have to scoll up several meters to read the new text.)

**Comment by testbird** [comment]
Maybe these hits help?: https://github.com/deltachat/deltachat-android/search?utf8=%E2%9C%93&q=ellipsis&type=
