### ISSUE TITLE
Feature request: add "is writing" etc via socket

### ISSUE THREAD

**Issue by Piruzzolo** [deltachat/deltachat-android#1124]
It would be cool to add some extra features one normally expects from a chat client, i.e. "is writing" while writing, status and optionally videochat and calls.

This could be accomplished using a socket (I mean, in a p2p fashion), using the email stuff to exchange IPs and do NAT traversal. Then, emails would deliver messages as is now, plus we could got these extra feats via this socket.

It surely it is an additional feature, but it would surely be a quality of life improvement since emails have longer lags than standard instant messaging services

**Comment by webratte** [comment]
I think this will come if the mail provider will support COI:
https://www.coi-dev.org/

Mailbox.org will starting to test COI:
https://mailbox.org/en/post/ox-summit-2019-in-madrid-mailbox-org-and-enterprise-partners-meet

And I'm sure the OX devs and the Delta Chat devs will work together :+1: 
https://www.coi-dev.org/coi-partners/

The world need as much as possible compatible clients.

**Comment by hpk42** [comment]
that's all true but nothing that is planned by any developer.  We are discussing integrations with various P2P devs but it's a long while off, at this point.  @Piruzzolo thanks for bringing it up but please in the future rather discuss things at https://support.delta.chat -- this issue tracker is for bug reports and features where there is some commitment in the shorter term from developers.
