### ISSUE TITLE
Provide unstripped ndk core library binaries together with releases

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1134]
There is an [ndk-stack](https://developer.android.com/ndk/guides/ndk-stack) tool that matches addresses from stacktrace that users can provide using current releases to line numbers. If these binaries are attached on the release page, they can be used to get line numbers without increasing APK size.

**Comment by link2xt** [comment]
We don't get crashes these days and Rust core is nearly free of `unsafe` code, so I am closing this.

**Comment by r10s** [comment]
> Rust core is nearly free of unsafe code

yeeeaaaaahhhh! \o/

**Comment by r10s** [comment]
```
.venv|~/projects/deltachat-core-rust/src[master|✔]$ ./top_evil_rs.py 
context.rs                unsafe:   1 free:   0 unsafe-fn:   0 chars:   0 libc:   0

total unsafe: 1
total free: 0
total unsafe-fn: 0
total c_chars: 0
total libc: 0
```

nice!
