### ISSUE TITLE
Add arabic to Delta Chat

### ISSUE THREAD

**Issue by BoFFire** [deltachat/deltachat-android#1136]
Please add arabic to Delta Chat.
Regards,

**Comment by BoFFire** [comment]
On the way : https://github.com/deltachat/deltachat-android/pull/1135

**Comment by r10s** [comment]
great you push that forward :) \o/

**Comment by r10s** [comment]
merged that, looks good, everything right-to-left :)

**Comment by BoFFire** [comment]
@ r10s \o/
