### ISSUE TITLE
Show warnings for providers which are not working

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-android#1137]
- Delta Chat version: all of them
- Expected behavior: when I choose a not working provider like outlook or hotmail, it warns me that they don't work with Delta Chat.
- Actual behavior: it tries to connect to those providers and doesn't work in the one or other way. users don't know whether they need a better configuration, a different provider, or whether it doesn't work for other reasons.
- Steps to reproduce the problem: open Delta Chat and register with outlook. message around a bit and realize that problems occur which make Delta pretty much unusable.

in the provider-db we have already some entries of providers which are not working; we could show a simple warning if users try to login with one of their domains.

**Comment by webratte** [comment]
I also think this could be a good idea.

28.11.2019 8:24:47 nachm. missytake <notifications@github.com>:

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/1219
