### ISSUE TITLE
crash on my lineageOS

### ISSUE THREAD

**Issue by 12042016** [deltachat/deltachat-android#114]
Hello, 
I try to use DeltaChat, but it always crashed on startup. 

 I have Wileyfow Swift with lineageOS. 

Ty.

**Comment by r10s** [comment]
Thank you for your report.

I know from several devices using LineageOS, so it does not seems to be a general problem, maybe a "Wileyfow Swift" problem.

Can you please check, if the problem still exist with the most recent version, and, if so, re-open the issue with more detailed information.
