### ISSUE TITLE
annoying version check warning

### ISSUE THREAD

**Issue by bokf** [deltachat/deltachat-android#1141]
![version_500](https://user-images.githubusercontent.com/25562831/70389123-61496480-19bb-11ea-9ccc-189f166903bc.png)
Suddenly I get a warning for a version check and cannot close it. I have the newest version from f-droid, so I do not see the reason to launch a warning for old version and it is not possible to remove the warning.

**Comment by r10s** [comment]
hm, wondering why the warning appears for f-droid. this should not be the case. can you please have a look what the line `installer=` at "settings / advanced / view log" reads like? only if there is no installer, the warning should pop up.

but yes, we have already mitigated the warning a bit and probably we will shift it to the device chat and make it less annoying.

**Comment by bokf** [comment]
The line shows:
installer=null
I think it would be OK to launch the warning once per day (or similar) but it should be possible to remove it.

**Comment by r10s** [comment]
thanks a lot, so it seems as if the getInstallerPackageName() is an unreliable thing, at least for fdroid.

> I think it would be OK to launch the warning once per day (or similar) but it should be possible to remove it.

when we put it to the device chat, this should be much better.

also, the long delay for an fdroid update was unexpected that time. when we introduced the warning, we had an update about every 3-6 weeks. but then came the rust-move :)

**Comment by r10s** [comment]
i've file a new issue at https://github.com/deltachat/deltachat-android/issues/1152 , closing this one.
