### ISSUE TITLE
move doze-reminder to device-chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1152]
- the current doze-reminder is more sth. the just just clicks away. it is easier and better to add a device message for that - this way, there is nothing the user has to click away and he can come back to the issue later as needed.

- ~~the current outdated-reminder is not working well, see #1141, we should remove it completely from here. the core can add a device-message if a version is older than 6 month or so (maybe even more ;)~~ this is another issue, for now, we leave it. it is unlikely, we will run into these issues again

**Comment by hpk42** [comment]
On Sun, Dec 08, 2019 at 05:35 -0800, björn petersen wrote:
> the current doze-reminder is more sth. the just just clicks away. it is easier and better to add a device message for that - this way, there is nothing the user has to click away and he can come back to the issue later as needed.

yes, in fact i'd had several people who were, after clicking it away the info, 
struggling to find the suggested setting.
