### ISSUE TITLE
renaming when sending a file

### ISSUE THREAD

**Issue by M4ss1ck** [deltachat/deltachat-android#1155]
- Android version: 8.0
- Device: Samsung Galaxy A7
- Delta Chat version: 0.950.0
- Expected behavior:
When I send a file, I want the filename to stay the same
- Actual behavior:
DC adds a "-n" (n is a number) before the file extension, but this breaks extensions like .html.zip
- Steps to reproduce the problem:
In any chat:
1. Press the "clip" button, then "File"
2. Choose a file. "RSS-3182,html.zip" in my case.
3. Send it

the sent file is now named "RSS-3182.html-2.zip" (first time it was ...html-1.zip)

*this doesn't happen when forwarding

**Comment by hpk42** [comment]
thanks but this is fixed with 0.973 already.
