### ISSUE TITLE
Sometimes, can't play voice message until restarting the app

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1161]
when I press the play button a toast with the text "error" is shown, I can't play the audio until I stop and reopen the app, I think I have this issue since version like 0.510.1

- Delta Chat version: 0.950.0
- Logs:
[deltachat-log-20191214-234516.txt](https://github.com/deltachat/deltachat-android/files/3964649/deltachat-log-20191214-234516.txt)

**Comment by r10s** [comment]
hm, the log points to a bug in ExoPlayer. maybe we should check for an update.

**Comment by solidboredom** [comment]
i and 2 of my friends using DC have this issue pretty often too.

**Comment by EchedeyLR** [comment]
The issue is confirmed by a friend that just started to use the app.

![image-2](https://user-images.githubusercontent.com/56733813/82152490-77582c80-9859-11ea-9b81-0f69f1062f9e.png)

PD: I have no issue no censuring my mail address.

**Comment by EchedeyLR** [comment]
@r10s any update into this?

**Comment by EchedeyLR** [comment]
After enabling permanent notification you must force the app to stop from Applications menu in the Android Settings. Is that or restart the phone.

**Comment by angelo-fuchs** [comment]
@adbenitez @EchedeyLR  Is this issue still present? The exoplayer version was increased in master 13 days ago and will be in the next version (1.8.1 still has the old one).

**Comment by EchedeyLR** [comment]
Let's wait for @adbenitez as I only use stable releases.

**Comment by adbenitez** [comment]
I have not seen this anymore, I will reopen if I get it again, thanks @angelo-fuchs
