### ISSUE TITLE
androidx - Class not found errors

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1163]
the logs mentioned in this issue: https://github.com/deltachat/deltachat-core-rust/issues/1054 show a lot of NoClassDefFoundErrors. AFAIK they're 'only' polluting the logs. I searched a little bit and it seems that this issue might result from the libraries we're using. 
A possible fix for this can be found here: https://github.com/facebook/flipper/issues/146#issuecomment-463667556

**Comment by angelo-fuchs** [comment]
Known issue https://issuetracker.google.com/issues/120750246
Resolution is to go to a newer Android Studio & gradle version afaics.
I think we should do this once async-core is stable and we start with the polishing.
As no one is currently working on it, I close this and put it to Project Resurrection.
