### ISSUE TITLE
no refreshing sent/received times in a chat when idle

### ISSUE THREAD

**Issue by M4ss1ck** [deltachat/deltachat-android#1167]
- Android version: 8.0.0
- Device: Samsung Galaxy A7 (2017)
- Delta Chat version: 1.0.0
- Expected behavior: 
In a chat:
Received/sent time refreshes every minute or so by itself 
- Actual behavior:
To see any change, you need to go back and then re-enter
- Steps to reproduce the problem:
Open any chat, send a message, keep your hands off your phone and look at the numbers in the low right corner 

*I'm putting this here, but I don't know if this is this way by design

**Comment by r10s** [comment]
this relates to the displayed times, as "2 minutes ago" etc? yip, this should be updated every minute or so.

**Comment by M4ss1ck** [comment]
it is updated, but only if the user act (e.g. send a different message, go back, etc)

**Comment by r10s** [comment]
had a closer look at the things, doing the update would have some undesired side-effects. eg. it is not only updating the time, the whole bubble may get wider, which results in more place for the text in width which results in lesser heights.

this may be a bit annoying and unexpected.

regarding the fact that fixing the issue will have some drawbacks and is some effort in itself, i think we should just leave this alone for now.

also, i think in the very most situations, this is not really an issue on mobile phones - normally, the user does not have its screen that long on - and if the screen goes on+off, things are already updated.

also had a look at signal: they don't do it as well (not saying that they are doing everything right, but still)

another fix might be to always use absolute timestamp, but this is another discussion, so we can shift this to the forum.
