### ISSUE TITLE
Sometimes doesn't work in background

### ISSUE THREAD

**Issue by M4ss1ck** [deltachat/deltachat-android#1168]
- Android version: 8.0.0
- Device: Samsung Galaxy A7 (2017)
- Delta Chat version: 1.0.0
- Expected behavior:
Receive a notification everytime a message arrives
- Actual behavior:
DC usually only loads messages on startup (and while running foreground)
- Steps to reproduce the problem:
I just notice old messages being notified when opening DC. I've set DC to be ignored by battery optimization.
- Logs:
[deltachat-log-20191217-144931.txt](https://github.com/deltachat/deltachat-android/files/3975257/deltachat-log-20191217-144931.txt)

**Comment by r10s** [comment]
hm, there is a TransactionTooLargeException in the log, not sure where it comes from, needs some investigations.

**Comment by gitgerardo** [comment]
Update:
 after the last update of Lineage OS on oneplus 6  I don't have any longer problems with notifications!

**Comment by csb0730** [comment]
Still confirm this behaviour. 

DC v1.3 from gplay.
Android 8 at Huawei Y7.

Actual behaviour:
- Sent a message
- DC not running in foreground
- No points at startpage icon, no delta icon at top status line
- After starting DC there are some new messages indicated in chat overview (badges).
- delta icon in status line appears now


-

**Comment by csb0730** [comment]
This issue should be opened again. IMHO it's not solved.
