### ISSUE TITLE
Which data should be promoted on forwarding messages?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#117]
Forwarding messages is implemented since ages and works like a charm.

A forwarded message looks the same as a normally forwarded E-Mail:

    ---------- Forwarded message ----------
    From: Name <address@domain.org>
    
    Message text...

This is the status quo. However, I am unsure if it is okay to forward the email address in all cases. Esp. when an already forwarded messages is forwarded to others. Maybe we should forward only the name in this case? Or always forward only the name? We always forward the name set by the original author to avoid sth. like "Daddy" or "Honey" - but if the user has _no_ name set at all, and we do not want to forward the email address - what can we display then?

**Comment by thenktor** [comment]
IMHO in an instant messenger the original author of a forwarded message should be removed completely. If I want others to know the source I'll tell them myself.

**Comment by r10s** [comment]
> IMHO in an instant messenger the original author of a forwarded message should be removed completely. If I want others to know the source I'll tell them myself.

I think this is a good approach. At least it does not let the user spread some data unexpectedly.
We will implement it this way in the next release (0.9.4 then)

**Comment by r10s** [comment]
Implemented in 0.9.4
