### ISSUE TITLE
do not try to recode eg. webm when attached as files

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1174]
currently, `recompress = DcMsg.DC_MSG_VIDEO` is set if `MediaUtil.isVideoType(contentType)` returns true - which may be the case for webm _images_ which results in the error "recoding for FILE.webm failed: cannot get info".

two things:
- we should not try to recode things attached as FILE
- ~~maybe we should try to attach normally if recoding fails~~ EDIT: no, this might be unexpected for the user as the video becomes _much_ larger than expected. the user can always attache as a file

**Comment by hpk42** [comment]
isn't the recoding attempt a core issue?

**Comment by r10s** [comment]
no, this is android. core does not recode videos, core currently _only_ recodes avatars.

**Comment by csb0730** [comment]
Still get complaints that video cannot be sent from a friend (file < 10MB, but it is not sent) Even me cannot sent a video when attaching it as a file! DC tries to recode the video, but why???
It simply should send the file if it not exceeds max size.

@r10s You wrote:
"maybe we should try to attach normally if recoding fails EDIT: no, this might be unexpected for the user as the video becomes much larger than expected. the user can always attache as a file"

My recommendation:
If size of attachment (e.g. video) doesn't extend max size it should be sent as it is and it sould not recoded in any case.
IMHO: This force for recoding makes more problems than is solves!
