### ISSUE TITLE
Sending Picture failed with GMX

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1179]
Try to send a picture ends in endless spinner turning

- Android version: 7 and 9
- Device: Huawei Nova and Samsung Galaxy S8
- Delta Chat version: 1.0.0
- Expected behavior: Sent Pics
- Actual behavior: dosn't work

This happens only with my GMX Account. With mailbox.org it works fine.
It happens with the Android version 1.0.0 and also with desktop client 0.900
Also the Avatar pic will not sent. 

**Sending the same picture with OX-Coi Client, Thunderbird, K9 and DC-androidclient v.0.950.0  works fine.**
So it's not only related to GMX.
It seems GMX and DC works not together very vell.

Maybe the attached  log file will help

- Logs: 
[log-dc-pic.txt](https://github.com/deltachat/deltachat-android/files/3986987/log-dc-pic.txt)

**Comment by webratte** [comment]
Also send the Autocryptmessge fails. So probably all attachments are affected.
I have not tested all yet.

**Comment by hpk42** [comment]
this is not avatar-sending but attachments in general, right? 
Would be good if you could provide a gmx-test account for us, to test ourselves.

**Comment by gitgerardo** [comment]
**I'm  also using a gmx account.**

I reported the issue of the impossibility to open PDF and docx files inside DC .
https://github.com/deltachat/deltachat-android/issues/1154#issue-536330586

**Comment by hpk42** [comment]
This might be fixed with https://github.com/deltachat/deltachat-core-rust/pull/1078/files merged today morning.

**Comment by gitgerardo** [comment]
> @gitgerardo this is probably a different issue, and more has to do with Android. It's being investigated.

@hpk42 you are right, I just checked with a gmail account and I can't open PDF files.

**Comment by webratte** [comment]
Can you provide a apk?
So I could test it.

And if you need a GMX Testaccount, probably it's easier to create one for your own. It's for free and account creation needs roundabout 5 minutes 😉

**Comment by hpk42** [comment]
the apk (1.0.2) is in preparation and will appear in a few hours

**Comment by webratte** [comment]
> this is not avatar-sending but attachments in general, right?

Yes, it's related to all kind of attachment I suppose.
So avatar sending also fails. I think the avatar is attachment too!?

**Comment by webratte** [comment]
> the apk (1.0.2) is in preparation and will appear in a few hours

Great, I will try it as soon it's available for me.
Will it also published in Play Store?
So my friends could also test it.

**Comment by gitgerardo** [comment]
> > the apk (1.0.2) is in preparation and will appear in a few hours
> 
> Great, I will try it as soon it's available for me.
> Will it also published in Play Store?
> So my friends could also test it.

It works!!

**Comment by webratte** [comment]
Great to know 👍

Thank you to the devs.

**Comment by hpk42** [comment]
https://get.delta.chat and the "apk" section.  gplay is in the making.

**Comment by webratte** [comment]
It works only if messages will sent une crypted.
Encrypted messages are still impossible to send.

BTW. switch off encryption has no effect.
I will open a new issue.

**Comment by r10s** [comment]
can you please also file an issue for the gmx-encrypted-attachment-failure? i think this should go directly to https://github.com/deltachat/deltachat-core-rust as android probably cannot do much about it.

**Comment by webratte** [comment]
Yes, I will do it later and also I will offer a log file.
