### ISSUE TITLE
support android8 notification badge/dots

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1189]
once we target [all these notify issues](https://github.com/deltachat/deltachat-android/issues?utf8=✓&q=is%3Aissue+label%3Anotify+), we should also make sure, we support these badges/dots that are available since android8: https://developer.android.com/training/notify-user/badges

i do not think we should try to target special launchers or so, maybe at a far later point, the important thing for now is to get things reliable on a basic level.

**Comment by adbenitez** [comment]
the badge works for me on a Samsung Galaxy A10, Android 9, default launcher

**Comment by r10s** [comment]
already now?

**Comment by adbenitez** [comment]
yes, with 1.0.2, but I think it is because the system support this, I see badges for apps that doesn't used to have in my previous phone, seems like the OS(or launcher) puts badges with the count of notificactions for every app

**Comment by r10s** [comment]
great, this is what i expected, however, i never really tried that out - or have overseen it :)

**Comment by adbenitez** [comment]
for example just now:

![Screenshot_20191222-175742_One UI Home](https://user-images.githubusercontent.com/24558636/71328436-29770c80-24e5-11ea-8ef1-fa29be77984f.jpg)

**Comment by r10s** [comment]
great, so we can regard this as done :) i added a comment to the corresponding lines so that we do not degrade this state when touching the other notification issues.

maybe we can have a look at older systems at some later point, but this will result in many troubles with different launchers etc., so i do not think we will go this way soon.

**Comment by adbenitez** [comment]
for example just now:

![Screenshot_20191222-175742_One UI Home](https://user-images.githubusercontent.com/24558636/71328436-29770c80-24e5-11ea-8ef1-fa29be77984f.jpg)

**Comment by r10s** [comment]
btw, i think the new adaptive-delta-icon looks pretty nice on your screen :)

**Comment by adbenitez** [comment]
agree :)

**Comment by csb0730** [comment]
We should reopen the badge issue(s).
I'm getting complaints of all of my friends that they don't see or see very late new messages due to no badge counter (different Android versions 4 ... 10).

**Comment by r10s** [comment]
see https://github.com/deltachat/deltachat-android/issues/962#issuecomment-571636936
