### ISSUE TITLE
DS 1.0.3 shows email provider ads

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-android#1194]
- Android version: 9
- Device: BQ X2 pro
- Delta Chat version: 1.0.3 from g-play
- Expected behavior: only Delta Messages are shown in DS
- Actual behavior: Provider Web.de: sometimes when Web.de sends his own ads they are shown in DS
- Screenshots: 
![image-3668407727](https://user-images.githubusercontent.com/37833326/71542079-3622b700-2962-11ea-966d-834129b46c05.png)

![image-2263081893](https://user-images.githubusercontent.com/37833326/71542082-3c189800-2962-11ea-8fed-ea7aa4ecde66.png)

**Comment by webratte** [comment]
Hi there

that happens if you enabled "show all E-Mails" in settings.

Now there are two ways.

Just enable "show only chats".
Or
Press "Kontakt blockieren" and you never will see Adds from this address.

That's it.

**Comment by g6094199** [comment]
Is this a default setting? After an upgrade or reinstall?  My girlfriend swears not to changed any seeting,

**Then it shouldnt be set to this.** Save should be "Akteptiere Kontakte"

THX

**Comment by webratte** [comment]
I'm not absolutely sure.
But I believe the default setting is "show only chats".

And let me say. If I have to do technical support for my friends they always sweare to have did nothing 😂

**Comment by r10s** [comment]
the default is "chats only", so normal mails should not pop up as contact requests.

in general, delta chat has no spam filter or so, so if you decide to display "all mails", you might also get spam there - as for any other mail client.
