### ISSUE TITLE
Selected chat message not deleted on server after positive confirmation by user

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1199]
**- Android version:**
10.

**- Device:**
Google Pixel 3a.

**- Delta Chat version:**
1.0.3.

**- Expected behavior:**
An incoming chat message (mail) is deleted in the Inbox (on mail server) after the user has explicitly confirmed deletion of one selected message locally "and on server".

**- Actual behavior:**
An incoming chat message (mail) is not deleted in the Inbox (on mail server) after the user has explicitly confirmed deletion of one selected message locally "and on server". At least it is deleted on the Android device.

**- Logs:**
No log available.

**- Further test information:**
- Only one incoming message was selected to be deleted.
- The incoming message was no initial contact request because a chat with this contact has been established earlier.
- The incoming message was sent with a different mailer than Delta Chat.

**Comment by agutierrez25249** [comment]
Same problem

device=Xiaomi Redmi 8 (olive)
android=9 (V11.0.1.0.PCNMIXM, ZQL2115-olive-build-20191127144358)
sdk=28
memory=13M (27.30% free, 256M max)
memoryClass=192
host=c4-miui-ota-bd103.bj
applicationId=chat.delta
app=Delta Chat 1.0.3-gplay
installer=com.google.android.packageinstaller
ignoreBatteryOptimizations=true

*@nauta.cu

**Comment by r10s** [comment]
i think, this is fixed by https://github.com/deltachat/deltachat-core-rust/pull/1197, if not, please reopen - and thanks for helping!
