### ISSUE TITLE
Why Delta opens conversations with strangers?

### ISSUE THREAD

**Issue by rizzopablo** [deltachat/deltachat-android#120]
I don't understand why Delta show conversations width people not in my contact list, they only participate in mailing list which I'm subscribed to. Please, look at the screenshot, all the chats which have unread or silenced messages are not contacts of mine, our only relation is a mailman list. But it does not happen with all the hundreds of people which are subscribed to these mailman lists, only with some of them. It's quite annoying anyway.
Whats the criteria Delta follows to open a conversation or not to do it?

![delta-chat-with-strangers](https://user-images.githubusercontent.com/13275003/28346371-0f0a9bf8-6c07-11e7-967d-d282c653d852.jpg)

**Comment by Ampli-fier** [comment]
I think this is because Delta Chat auto-collects email addresses, see [#32](https://github.com/deltachat/deltachat-core/issues/32). They are added to the Delta Chat _contacts_ database on first receival of, eg a mailing list mail and on the next receival DC opens a chat as the contact is "known".
Maybe DC fails to parse them all, maybe the list is too long, or it is only done for addresses in the "To" field?

**Comment by r10s** [comment]
I assume @rizzopablo has written to the mailing list and all the new chats are answers to this post?

I think for "normal" mails, it is fine to show up answers from different addresses - if you text me at r10s@domain and I answer from bpetersen@domain, it's okay if this opens a new chat. Obviously, it's not perfect for mailing lists. 

See https://delta.chat/en/help#which-messages-do-appear-in-delta-chat about which messages start a new chat.

However, I do not have a concrete idea how to change things to fit into both scenarios.
Is there a way to reliable detect mailing lists?

**Comment by rizzopablo** [comment]
Ah, ok. Yes Björn, there is a way to detect mailing lists, the List-Id header, virtually all mailing lists set this headers, in fact I use this header to move this emails to a Lists folder in my mail server, it works.
19 de julio del 2017 6:29, "Björn Petersen"  escribió:
	I assume @rizzopablo (https://github.com/rizzopablo) has written to the mailing list and all the new chats are answers to this post?

	I think for "normal" mails, it is fine to show up answers from different addresses - if you text me at r10s@domain and I answer from bpetersen@domain, it's okay if this opens a new chat. Obviously, it's not perfect for mailing lists.

	See https://delta.chat/en/help#which-messages-do-appear-in-delta-chat (https://delta.chat/en/help#which-messages-do-appear-in-delta-chat) about which messages start a new chat.

	However, I do not have a concrete idea how to change things to fit into both scenarios.
Is there a way to reliable detect mailing lists?

**Comment by r10s** [comment]
Ahh,  `List-Id` - this sounds as if there exists a proper solution :-)

**Comment by r10s** [comment]
Okay, Delta Chat ~ 0.9.4 should fix this issue, see https://github.com/deltachat/deltachat-core/commit/b01e8eea500f5e1641c7c3b5fa1b69e939a8556b

The fix will only affect _new_ chats; it won't fix chats accidentally stated in the past.

**Comment by rizzopablo** [comment]
Thanks!!

**Comment by r10s** [comment]
I think, we can close this issue now as the mailing list stuff should be fixed, if not, feel free to open a new issue and reference this one.

BTW: there are still "unwanted" messages, they're handle by this issue: https://github.com/deltachat/deltachat-android/issues/49
