### ISSUE TITLE
list of 100% compatible free email providers?

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#1202]
I understand that Microsoft Outlook is not 100% compatible and Google gmail automatically resets 'use nonsecure apps' if you are not constantly using one (for those who don't want 2step verification and other' security extras'(also wants a phone#  )

What are the free email providers who are 100% compatible with Delta chat?

**Comment by r10s** [comment]
i think, this question is more sth. for the forum at https://support.delta.chat

however, there are lots of email providers working very nicely with Delta Chat, users start to collect some information at https://providers.delta.chat (formerly https://support.delta.chat/t/provider-overview/56 )
