### ISSUE TITLE
LED notification dosn't work on some devices

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1203]
- Android version: 7.0
- Device: Huawei Nova
- Delta Chat version: 1.0.3 GPlay
- Expected behavior: show LED notification for incoming messages
- Actual behavior: No LED notification (tested with different colores)

- Logs: 
[2020-01-02-12-06.txt](https://github.com/deltachat/deltachat-android/files/4015676/2020-01-02-12-06.txt)

**Comment by r10s** [comment]
we will rewrite this area and move towards the android notification channels. these channels does not really allow the apps to finetune notification behavior, instead, this is offered by the system - which may or may not support notification leds.

so, i think, further invetigations does not make much sense currently.

**Comment by angelo-fuchs** [comment]
I agree with @r10s. Error seems to stem from a ringtone that could not be played (line 159 in the log) for some reason.
So for you @webratte it is most likely sufficient to select a different ringtone and for the rest of us, stuff like this should go away after switching to channels.

**Comment by webratte** [comment]
The LED is not that important for me.

But it's strange. The ringtone is played.
So for me the ringtone is no problem.

**Comment by r10s** [comment]
anyway, closing this. there is no actionable item.
