### ISSUE TITLE
importing an old backup leads to ANRs

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1205]
I've imported a backup that was some months old.

After the initial import the UI became unresponsable and after a while the app crashed.
The core seems to struggle with duplicated database entries:
https://gist.github.com/cyBerta/5a7c6c64b44f1fc05e43853961da1302

Tested on a Samsung Galaxy S4 mini, Android 9, latest deltachat master branch (a6f9110a85b0df5da4fb00ed34ddfd21aa93be25)

**Comment by cyBerta** [comment]
I would low priotize that for now because I really don't know how old the backup was and if it came from a stable release version or not.

**Comment by r10s** [comment]
closing this, this might be solved by https://github.com/deltachat/deltachat-core-rust/pull/1492, and as you said, might also be related to other problems. we can reopen if it happens again and we know that this is sth. in android.
