### ISSUE TITLE
Google Play: Buzzwords missing to find DS

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-android#1206]
Hi,

when users try to search for a secure messenger in gplay users havent even the chance to find DS.

When you search for "secure messenger", "encrypted messenger" , etc DS doesnt even show up on the huge results list. I would be nice to optimize the search result for DS!

Sash

**Comment by r10s** [comment]
thanks for pointing this out.

currently, we're still in the beta-track.  
as far as i know, delta is not suggested in this mode at all and you will find delta chat only when really searching for "delta chat".

but, as we want to leave the beta-track soon™ i've taken this issue as a chance to add some tags, this is what i've done:

<img width="977" alt="Screen Shot 2020-01-04 at 12 04 06" src="https://user-images.githubusercontent.com/9800740/71764628-8235a480-2eea-11ea-8f31-2282194b3354.png">

**Comment by g6094199** [comment]
Hi,

good start.

 I dont know how google handles tags. Maybe "privacy & security" should be seperate tags? Maybe "open source", "autocrypt", "encrypted" and "messenger" would also be nice.

THX!

Sash

**Comment by r10s** [comment]
> I dont know how google handles tags. 

the tags are predefined and there are not that many tags at all. the existing tags are rather coarse therefore.
