### ISSUE TITLE
Back button on the Unlock screen allows to read the chat list

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-android#1208]
Hello,
I've noticed that a quick press of the the back button on the Unlock screen allows to read the chat list of Delta Chat. Please see https://youtu.be/mxhMDceLySc

A third person could read the contacts and the preview of the messages from a video like this just pausing it.

- Android version: /e/OS (Android 9)
- Device: Google Pixel
- Delta Chat version: 1.0.3

**Comment by webratte** [comment]
Hi there,

Delta Chat has no Unlock screen.
So I think the Unlock screen in the video is a third party app or supported by the OS.

I  this case it's not a bug I Delta Chat.

Or did I misunderstood?

**Comment by sbadux** [comment]
Hello.
I've activated the Unlock screen in the Settings menu -> Privacy -> Screen Lock, so it should be a native delta chat feature

**Comment by webratte** [comment]
Sorry my fault. 

I didn't realize this feature exist.

So it seems to be a DC bug

**Comment by r10s** [comment]
>  so it should be a native delta chat feature.

not really. it just shows the devices unlock screen. eg. i've never seen the screen in the video :)

**Comment by r10s** [comment]
@sbadux ah, and another thing: please also try to enable "screen security".

**Comment by sbadux** [comment]
Yes, I can't be sure this is related to Delta Chat's code, but could you please try if you see the same behaviour on your device? It's not a big issue, but since Delta Chat is an privacy-focused app I think this could be a problem that needs a fix (also if it's an Android bug).

**Comment by angelo-fuchs** [comment]
Can't reproduce (Fairphone 2, Android 7)

**Comment by r10s** [comment]
the reasons seems to be that when firing multiple back-button-events, the activity-livetime is triggered somehow.

i added some logging when `android.R.id.content` is accessed - and while fireing back-button-events, BaseActionBarActivity.onStop() --> findViewById(android.R.id.content).setVisibility(View.GONE);  is called several times as well as BaseActionBarActivity.onStart()-->findViewById(android.R.id.content).setVisibility(View.VISIBLE);

**Comment by angelo-fuchs** [comment]
I could reproduce this after turning security on and of and restarting the app.
Then only when I two finger back AND cancel. When it shows, it is interactive, so I could open a chat and if I had pointed a cam on the screen I would even be able to read what was written. (tested on 1.2.1, 1.3.0 and nightly-2020-04-13)

**Comment by Hocuri** [comment]
Now I could reproduce this, too, I just wasn't fast enough ;-)

**Comment by Hocuri** [comment]
@angelo-fuchs ?

**Comment by RubenDavidPerezJimenez** [comment]
it are 1.12.1 in and see the chats too if you are really fast and navigate maybe will be better to put a screen before open the app with the security active

**Comment by r10s** [comment]
the unlock-screen will be removed in once of the next versions and there is already a warning added by #1627, so there is no actionable item left.
