### ISSUE TITLE
"Default" language doesn't restore the OS-language

### ISSUE THREAD

**Issue by sbadux** [deltachat/deltachat-android#1209]
Hello,
I'm italian so I correctly got Delta Chat in italian when installed. Then I've switched the language from Default to English to do a bug report. 
Now, I've switched back to "Default" but Delta Chat remains in English. If I choose "Italian" it works correcly, but "Default" is always English. It seems that the App can't restore the Android native language after swhitching from Default to any other language.

/e/OS (Android Pie)
Delta Chat 1.0.3

**Comment by angelo-fuchs** [comment]
I can reproduce this, but needed to restart phone.
Default Lang is DE in my case.

1. Change setting Language to EN (UI switches to English)
2. Restart phone (or other force kill DC, probably)
3. Change setting Language to default. (UI stays English)
4. Restart phone and language changes to proper default again

Error is in Step 3, UI should change immediately.

**Comment by angelo-fuchs** [comment]
It seems that the language is always set to whatever the app started in.
So, if the app started in "Esperanto" and you change to "German" it works. If you then switch to "Default" it becomes "Esperanto" again.

**Comment by AndreazLattmann** [comment]
I have a similar problem: I install DC and it is in Italian, I add my backup email account and everything is fine, I add another account, I import the backup and I have all translated into Italian except "Device messages" which is in English.

**Comment by r10s** [comment]
device messages are "really sent" messages you "really receive" - they are not updated at all.

**Comment by AndreazLattmann** [comment]
So I receive the first time the messages in Italian and then adding another account I receive them in English? Or do I get them in English and does DC use the translated version by reading the set language setting?

**Comment by r10s** [comment]
the device-messages are generated on your device in the language set at the moment the message is generated. the device-message is not changed afterwards.
