### ISSUE TITLE
Handle weired MDNs or avoid them

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#121]
Delta Chat 0.9.3 introduces so called Read receipts.

They are requested by the header `Disposition-Notification-To` and Delta Chat expects _no answer_ or an _answer following RFC 8098_. Both is fine.

However, many MUAs seem to send the MDNs in an _undocumented, weird freetext format_. I've seen MDNs from Samsung Mail (?) and from Koma Mail here that do not follow the standard and cannot be parsed and also lack important information (eg. Samsung does not even transmit the original message-id)

As a result, Delta Chat cannot draw the "second check" beside the messages. But even more worse, the freetext MDNs appear in the chat as normal messages from the contact. This is even more weird if the MDN in a single chat refers to a messages send in another group. 

What can we do?

- I'm not 100% sure if I have done anything wrong when requesting the MDNs, however, I've not seen an option that says "always return parsable, struct MDNs" or sth. like that.

- we can try to parse these freetext MDNs, however, we would never reach 100% here and there will be MDNs left that show up in the chats. Even worse, it may happen, that we think a freetext message is an MDN but it is not.

- we could request the MDNs by another header, eg. `Chat-Disposition-Notification-To` or `Strict-Disposition-Notification-To`. The disadvantage would be that Delta Chat won't receive MDNs by non-messengers and the "the user requested a MDN for this messages" won't pop up. However, maybe at least the latter one may be an advantage.

**Comment by r10s** [comment]
Well, but this is how an MDNs from a Samsung phone (?) looks like:

```
Return-Path: <user1@gmx.net>
X-Original-To: user2@b44t.com
Date: Mon, 17 Jul 2017 21:34:01 +0200
Subject: Lesebericht : Chat: Our meeting
Message-ID: <8mbxg2db47f7jyxj6q81gj2r.1500320041496@email.android.com>
Importance: normal
From: user1@gmx.net
To: user2@b44t.com
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="--_com.android.email_525878214237380"

----_com.android.email_525878214237380
Content-Type: text/plain

Empfänger: user1@gmx.net
Lesezeitpunkt : 17.07.2017 09:34 PM
Betreff: Chat: Our meeting

----_com.android.email_525878214237380
Content-Type: text/html

<html><head></head><body><div style="word-break;keep-all;">
Empfänger: user1@gmx.net<br>
Lesezeitpunkt : 17.07.2017 09:34 PM<br>
Betreff: Chat: Our meeting
</div></body></html>

----_com.android.email_525878214237380--
```

(Empfänger/Lesezeitpunkt/Betreff are germand words for Receiver/Reading time/Subject)

I do not see how I can parse this sensefully. There are only a few localized lines, _nothing_ that differs from a normal mail, no multipart/report, nothing :-(

**Comment by r10s** [comment]
I removed the label "bug" because I'm not sure if this is really a bug. At least, it is no bug in Delta Chat.

**Comment by r10s** [comment]
Well, as there were lots of other weird disposition notifications I've seen in between, we go for option 3 and use the `Chat-Disposition-Notification-To` header which results. Using only MDNs between Delta Chat is better than receiving unwanted and unexpected trash ...

**Comment by csb0730** [comment]
This choice is probably a good one in this Situation but I would recommend to make a user setting to activate RFC compliant MDN in addition!
This to use even with non DC MUA's if desired. The individual users contacts may require this.

**Comment by r10s** [comment]
Yes, maybe this is an good idea. We will think over this later, maybe we'll find another smarter solution, however, for now, other things seems to be more important...
