### ISSUE TITLE
remove image from "no chats" view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1211]
as we show the device chat by default, the whole "empty" screen is shown very rarely.

we have such images in the device chat now.

**Comment by cyBerta** [comment]
At the moment it is possible to delete the device chat and the save messages chat so that there can be this empty screen. Having the background image is nicer than the blank screen. 
Is your aim to reduce the apk size with this ticket?

**Comment by r10s** [comment]
i would just not add images to places that are normally not visible. also i do not think that the image fits nicely to the material design, we can better add it as a device-chat message at some point.

apk size is also one aspect, however.
