### ISSUE TITLE
add search to chatview and to help

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1217]
i filed the same issue for both as this seems to be very similar.

- add "Search" as the first menu item  - not: a magnifier-icon in the titlebar as on the chatlist - (reason is that there is few place in the chatview titlebar and we want to be consistent)

- a click opens a search-bar, similar to the one from the chatlist

- in the search-bar, right of the search field, there should be up/down arrows that allow jumping to all results (if the input field is empty, this can be used to jump to the beginning/end, a bit hidden, but well, #892)

- the view should jump immediately to the first occurence found, no need to tap on search or so

to get all matching messages in a chatlist, there is [dc_search_msgs()](https://c.delta.chat/classdc__context__t.html#a777bb1e11d7ea0288984ad23c2d8663b).  
to get all matching text in the help, [WebView.findAllAsync()](https://developer.android.com/reference/android/webkit/WebView.html#findAllAsync(java.lang.String)) and [WebView.findNext()](https://developer.android.com/reference/android/webkit/WebView.html#findNext(boolean)) should do the job.

**Comment by csb0730** [comment]
Jump to 1st message is needed urgently to delete old messages manually

**Comment by csb0730** [comment]
Will do a PR for #892.

For myself I've implemented it already :-)

**Comment by r10s** [comment]
i think, we'll use the standard android search: https://developer.android.com/training/search/setup
