### ISSUE TITLE
Show existing threads on new install

### ISSUE THREAD

**Issue by DreamFlasher** [deltachat/deltachat-android#123]
I just installed the app and logged in with my gmail account -- and the app is empty. I would have expected to see my current email threads as chats in DeltaChat. Or at least the threads with people who are in my adress book.

**Comment by r10s** [comment]
Delta Chat starts empty. This is by design, at least for now :)

**Comment by DreamFlasher** [comment]
I think this should at least be an option. For example in the initial setup screen there could be a final question "Do you want a clean start or do you want your existing mail threads to be imported".

**Comment by rootuser1** [comment]
I'd like to see this feature too. I assumed that this is already the case (see #101).

**Comment by testbird** [comment]
Having threads available on the server, for downloading and syncing is a large feature of IMAP email servers.

At least for exiting chat messages, this should be the default when deltachat is installed and finds a chat folder, IMHO. Together with giving instruction to the user to import or send the corresponding setup.

**Comment by testbird** [comment]
You should be able to see the unapproved emails (aka "contact requests") using the menu
 -> https://github.com/deltachat/deltachat-core/issues/48

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
