### ISSUE TITLE
Avatar priority

### ISSUE THREAD

**Issue by eatanimals** [deltachat/deltachat-android#1236]
Ran out of support posts..

Avatar set by contact should override android Contacts Provider (system address book)

Provide an option for user preference of order like analogous Pix-Art messenger does for xmpp.

Image I set for her > avatar she uploads to her account > my contact for her in my phone 

I prefer the updating avatar from people who change it around weekly or whenever whimsy strikes.

**Comment by r10s** [comment]
> Avatar set by contact should override android Contacts Provider

afaik, this is the case currently. i am skeptical wrt to an option, this would make multi-device even more complicated, and result in complicated ux questions. so i would not target that before the other, much more pressing multi-device-sync questions are solved.

**Comment by r10s** [comment]
also here, this should can be discussed in the forum, also at is not only affects android.
