### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by eatanimals** [deltachat/deltachat-android#1237]
For the same partitioning reasons I keep multiple email addresses, and multiple xmpp addresses I would like this in DC

**Comment by thackel** [comment]
I think this is a long standing feature requests. The devs will close this issue for sure, because "features should be discussed in the forum".
I really can't imagine that all the mobile devs of the project have only one account where they do deltachat communication...

**Comment by r10s** [comment]
be assured, that we also _like_ multiple-account and we want to see this feature as being implemented as well, in fact, desktop already has it. however, it's all about prioritization and what is maintainable and doable with the existing resources at some point.

this may change quickly, of course, if there are some new volunteers who want to get that in soon :)

**Comment by hpk42** [comment]
On Mon, Feb 03, 2020 at 07:37 -0800, Thomas Hackel wrote:
> I think this is a long standing feature requests. The devs will close this issue for sure, because "features should be discussed in the forum".
> I really can't imagine that all the mobile devs of the project have only one account where they do deltachat communication...

it's true for me ;)  Note that Desktop has multi account UX.

every bigger feature we do will cause not only the work we do
but a trail of issues / feedback we then want and need to handle,
i.e. maintenance.  Android and iOS have (combined) currently three
core devs who are working on it, but also on dcc core sometimes.
iOS still has several other basic things missing. And Android
also has a list of things/issues to care for. 

If you know of Android and iOS devs who want to help a bit,
please try motivate them to help -- what we can tackle also
depends on the people contributing in code.

**Comment by hpk42** [comment]
and @thackel was right, i am closing this now. 

@eatanimals please try to not open lots of feature requests, and things for other people to work on. We appreciate feedback but most of what is opened here as feature requests has been discussed/feedbacked before.  Currently we depend on enough people helping with coding, and not  on getting yet more ideas and feedback.

**Comment by link2xt** [comment]
@eatanimals As a workaround for Android you can use a version from F-Droid which has a different ID and signature and can be installed in parallel with Google Play version. There are apps that can clone APKs but it is nearly impossible to verify if they are malware or not, so I can't recommend any.

Personally I use Android for my primary account and Desktop which has multiple accounts for secondary.

**Comment by zgzgng** [comment]
> here are apps that can clone APKs but it is nearly impossible to verify if they are malware 

@link2xt The lucky one with the yellow emoji smile that can patcher things?  or disable app activities?  I wish there was a safe version of that app with only the app activity disable menu.  (is there one?)  I use it exclusively for adblocking.

I wish there were some kind of building system I could quickly install into vultr or digitalocean to few-click generate my own multiple ID versions.  (not a programmer)

**Comment by link2xt** [comment]
I haven't tried it, but it looks like [apktool](https://ibotpeaches.github.io/Apktool/documentation/), which is packaged in Debian, can repack existing APKs.
