### ISSUE TITLE
Export advanced account config

### ISSUE THREAD

**Issue by eatanimals** [deltachat/deltachat-android#1238]
I can export my key for later import. Can I not export account settings?

Because auto configure isn't always available. Advanced configuration tedium awaits 

(Also export authentication)

**Comment by r10s** [comment]
you can export a whole backup, this includes all account settings - maybe that helps?

apart from that, also here, feature-request should be discussed in the forum, also at is not only affects android.

this issue tracker is mainly for bugs and to coordinate things among developers actually working on things.
