### ISSUE TITLE
Please send attachments without resizeing as option

### ISSUE THREAD

**Issue by webermike** [deltachat/deltachat-android#1241]
Hello, Please allow to send attachments without resizeing as Option. Thx

**Comment by hpk42** [comment]
On Fri, Feb 07, 2020 at 03:37 -0800, webermike wrote:
> Hello, Please allow to send attachments without resizeing as Option. Thx

if you send an attachment as a file, it should not be resized.

**Comment by webermike** [comment]
Meant was: gallery, share image, delta chat. Images are resized. Better make a pop up to define resized or as is. Friends would like to have the full picture  ressource, not a small file. Thx.

**Comment by r10s** [comment]
@webermike, thank you for your post.

there are already several ongoing discussions about that in the forum, eg. at
https://support.delta.chat/t/ideas-for-image-compression-feature/313, so i think it is better to continue the discussion there.

in general, this issue tracker is mainly for bugs and for things some devs actually subscribed to work on.
