### ISSUE TITLE
Landscape Background is streched

### ISSUE THREAD

**Issue by MisterTechnik** [deltachat/deltachat-android#1245]
- Android version: 10
- Device: Samsung Galaxy S10+
- Delta Chat version: 1.1.2.
- Expected behavior: something else than
- Actual behavior: if I put my phone into landscape, the custom background is extremely streched
- Steps to reproduce the problem: put phone into landscape
- Screenshots: you'll see if you try
- Logs: not needed I guess

- Additional: a solution would may be to add a 2nd background for landscape

**Comment by r10s** [comment]
see reopened https://github.com/deltachat/deltachat-android/issues/466
