### ISSUE TITLE
On some devices the newer version 1.1.x does not work (not or delayed receiving messages)

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-android#1247]
- Android version: 6,
- Device: Shiftphone
- Delta Chat version: 1.1.2 / 0.5.x
- Expected behavior: after upgrade to 1.1.2 messages should be received immediately
- Actual behavior: no messages
- Steps to reproduce the problem: downdate tp 0.5.x (f_droid) and all messages are there
- Screenshots:
- Logs: maybe later - it's not my phone

I recognized trouble with receiving messages on Xiaomi phones Android 9 and 10 starting December. I reported it here, but it was closed due to a change related to Android 9 that might have been the reason.
But 1.1.2 version did not change behavior on my and sons phone (I have sometimes a delay, but restarting will trigger fetching mails and he didn't get any message any more)
Yesterday I updated my wife's phone (Shiftphone Android 6) in F_Droid store from 0.5.x to 1.1.2 and she received no messages any more. So I downgraded her phone (F-Droid allows it - good feature:-) ) and everything is fine again.
So I don't think it is a problem of the provider (we all use the same provider - Kontent.de), because of working with downgraded device and independent of that there is a samsung note 10 device with 1.1.2 running all the time (Cyanomodgen). Same with Linux desktop.
There must be change  around version 1.0 in core (maybe one or two versions earlier or later) that raises this trouble (isn't that the time where the server was moved from C to rust ?)
The problem is that it is not blocked in general, but due to some special constraints or timing on the phones.
At least a chat-system, that does not show messages is broken and so I wonder, that all post related to this issue (e.g.#1239) are focusing on provider or special content (all content is blocked and from different providers) and typically the threads are closed.
I will add the log of my wife's phone to this thread if it is not reset after downgrade.

**Comment by gerryfrancis** [comment]
> At least a chat-system, that does not show messages is broken and so I wonder, that all post related to this issue (e.g.#1239) are focusing on provider or special content (all content is blocked and from different providers) and typically the threads are closed.

https://github.com/deltachat/deltachat-android/issues/1239 is not closed. The reason seems to be unknown right now, so please be patient, provide your log in there where the others can see it, and close here, as the behavior is the same. Thanks.

**Comment by wenzler** [comment]
Same problem here with two Xiaomi (both running MIUI10 on Android 7.1.1 and 8.1.0 with battery saver disabled for deltachat)

Initial message was received at 13:17, triggering no display while device locked
Receive time according to SMTP Mon, 10 Feb 2020 12:17:56 +0000 (UTC)

Next message at 13:18 triggered display at ~13:20 of both messages
Receive time according to SMTP Mon, 10 Feb 2020 12:18:53 +0000 (UTC)

[deltachat-log-20200210-132149.txt](https://github.com/deltachat/deltachat-android/files/4180758/deltachat-log-20200210-132149.txt)

**Comment by gerryfrancis** [comment]
@wenzler Thank you for sharing, please continue here: https://github.com/deltachat/deltachat-android/issues/1239

**Comment by haeckser** [comment]
closed due to active thread #1239 which is covering this experiences too now
