### ISSUE TITLE
Delta does not read some emails correctly

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1248]
- Android version: 9
- Device: xiaomi mi a3
- Delta Chat version: v1.1.2
- Actual behavior:
Just show the matter,
This error started with versions following v0.510
- Screenshots:
![deltachat-2020-02-08-162157](https://user-images.githubusercontent.com/52469394/74092318-09e57480-4a90-11ea-8a5a-3c600d75097e.jpg)

This is a capture of the email mentioned
[Efemerides del dia  5 de febrero.eml.txt](https://github.com/deltachat/deltachat-android/files/4175240/Efemerides.del.dia.5.de.febrero.eml.txt)

**Comment by r10s** [comment]
this is a core-issue, see https://github.com/deltachat/deltachat-core-rust/issues/1373

**Comment by r10s** [comment]
seems to be fixed, if not, please reopen. thanks for helping :)
