### ISSUE TITLE
Landscape photograph is black after turning from portrait

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#1249]
(from the second half of #1234 )
- Android: 9
- Device: Huawei HMA-L29
- Delta Chat version: 1.1.2 - 1.2.0
- Expected Behaviour: When one opens the the photo attachment in portrait mode and then rotates to landscape the camera continues working.
- Actual Behaviour: The camera turns black.
- Workaround: Tap the icon to switch to front/back camera. Tap it again to switch to the camera you want to use, it then works as expected.

**Comment by Hocuri** [comment]
I couldn't reproduce this (Android 7, DC 1.3.0).

**Comment by angelo-fuchs** [comment]
@Hocuri what device were you using? It seems that it occurs on a Huawai device (It works on my Fairphone)
@AndreasLattmann can you report if the issue is still present on your device?

**Comment by AndreazLattmann** [comment]
With version 1.5.0 (nightly) of 13-04-2020 I no longer have this problem! 😄 🎉🎊

**Comment by AndreazLattmann** [comment]
Sorry, but I couldn't access my account anymore. Now I'm AndreazLattmann 😅

**Comment by angelo-fuchs** [comment]
@AndreazLattmann Okay, then I'll close this issue for now. If it comes back, feel free to revive it or open a new one.

**Comment by AndreazLattmann** [comment]
I rejoiced too soon... If I can do auto-rotation, the problem reoccurs. 🥺

**Comment by Hocuri** [comment]
I am using a Moto G3 with Lineageos and Android 7. And the it works fine both with auto-rotation disabled and enabled.

**Comment by angelo-fuchs** [comment]
@AndreazLattmann Do you have that issue in other apps as well when you use the rotation? It seems it is bound to your device / setup.
If it is only Deltachat could you attach your Logfile? Maybe we find something in there.
