### ISSUE TITLE
Inform user when we drop a message

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#1250]
In Issue #1239 a mail is investigated that gets dropped because of some attachment issue. Figuring out that there is a problem and what is the problem was quite complicated and would have been far easier if we had a message from "device@localhost" telling the user that a message got dropped.

I think the message should read something like:

> Sorry to inform you that message $Number got dropped because $Reason. If you think that is an error, please do file a bug report here. There is no way to recover that message from DeltaChat.
> We could recover this metadata:
> Subject: $Subject
> Sender: $Sender
> [...]

That way the user knows that something got dropped and has as much information as possible to react to the situation. We also might get more and better reports about which mails get dropped so that we can fix this.

Here is the log segment that showed that a message got dropped.

> src/dc_receive_imf.rs:42: Receiving message INBOX/23599...
> src/imap/mod.rs:777: dc_receive_imf failed for imap-message INBOX/23599: Message("missing attachment")
> src/imap/mod.rs:686: 1 mails read from "INBOX".

**Comment by hpk42** [comment]
I closed the core issue so i'd also close this here.  I suggest to first discuss at https://support.delta.chat and find out if people have surprises wrt not seeing a message they expected.

**Comment by angelo-fuchs** [comment]
@hpk42 I would not have opened the issue if this was not something that users have encountered. #1239 had this and I have encountered it myself.
We silently drop some mail (e.g. from mailinglists) while we do show regular email, so this is not a feature. The way we currently handle it, its clearly a bug. Also fixing it would be very cheap (at least for lists) as we already print a line in the logs, we just need to promote that message to the frontend somehow.

**Comment by r10s** [comment]
well, there are ongoing efforts to handle and show mailinglists, so, sooner or later this is fixed by just showing mailing lists :)
