### ISSUE TITLE
Use Rust Gradle plugin to build native library

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1253]
Instead of our ad-hoc scripts, such as https://github.com/deltachat/deltachat-android/blob/master/ndk-make.sh, we could use "official" (from Mozilla) Rust plugin for gradle: https://github.com/mozilla/rust-android-gradle

**Comment by angelo-fuchs** [comment]
the rust-android-gradle still requires the dev to perform some activity (like the rustup commands) that we need to somehow communicate to new devs. Currently they are in a comment in ndk-make.sh.

When we switch to rust-android-gradle we should check if we can include a relevant check into the gradle to see if the setup is already present and good and if not fail with a meaningful error message.

**Comment by r10s** [comment]
closing this for now, there is no real need, also f-droid is happy with our ad-hoc script.
