### ISSUE TITLE
Change default background

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1255]
Change default background to the one used in DeltaChat Desktop: https://github.com/deltachat/deltachat-desktop/blob/master/images/background_light.svg

**Comment by csb0730** [comment]
Big picture 796kb. Isn't that slowing down app?

**Comment by r10s** [comment]
i think it is needed to adapt the picture to some colors anyway. in general, i would re-use the existing color scheme which is fine-tuned (really ;) to the message-boxes and to the title-bar. so, for now, i would not see this as a priority.

**Comment by Hocuri** [comment]
We now use the same background as Desktop.
