### ISSUE TITLE
reproducible crash when generating a qr-code with core1.26

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1259]
trying to generate a qr code with unreleased android 1.2.1 using core1.26 crashes reliably. not sure, where it comes from, maybe also an build failure or so.

[log](https://gist.github.com/r10s/8cf5802c67e5e2edcb3108f9483a465c) (the log does not say much, i should try over with RUSTFLAGS=-g)

**Comment by r10s** [comment]
[log with RUSTFLAGS=-g](https://gist.github.com/r10s/e92911621b5f81c960be7eace2fbad95) - so, the problem seems to be related to Key::from_slice()

**Comment by r10s** [comment]
hm, tested that with a fresh account, noticed that basically nothing works without crashes, export (i tried to save the state and test it in the repl tool) but also not sending. 

so maybe there is just sth. broken during build. or the created keys is invalid.

**Comment by r10s** [comment]
i retried it, it is not related to a special key, but it requires an armv7 target for crashing.

with 1.25, things work out, i filed a core issue at https://github.com/deltachat/deltachat-core-rust/issues/1326

**Comment by dignifiedquire** [comment]
@r10s what is the command exactly you used to build dc?

**Comment by r10s** [comment]
the corresponding command from [ndk-make.sh](https://github.com/deltachat/deltachat-android/blob/master/ndk-make.sh) is:
```
TARGET_CC=armv7a-linux-androideabi16-clang \
cargo build --release --target armv7-linux-androideabi -p deltachat_ffi
```

maybe i have to do some rustup or cargo update?

**Comment by r10s** [comment]
> at least trying over with rustup updated.

tried over after doing a `rustup update`, does not make a difference. 1.25 works, 1.26 crashes

**Comment by dignifiedquire** [comment]
fix is here: https://github.com/rpgp/rpgp/pull/90

I don't know what slice_deuques exact issue is, but I am gonna just drop it, it is not worth it

**Comment by dignifiedquire** [comment]
https://github.com/deltachat/deltachat-core-rust/pull/1327

**Comment by r10s** [comment]
@dignifiedquire thanks a lot! great! works like a charm +1
