### ISSUE TITLE
Show recent history

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-android#126]
Feature request: What if Delta Chat showed recent history of conversations such as the 10 last messages of the conversations of the current day? 

I mean when you send a new message, the recent history would be shown as expanded content of the e-mail in this manner:

> **You**: bla-bla-bla!
> **Me**: bla-bla-bla-bla...
> **Me**: bla-bla-bla?
> **You**: bla-bla-bla-bla

That would help the interlocutor who does not use yet Delta Chat to keep track of the conversation.
Just an idea... 
What do you think?

**Comment by luisfsr** [comment]
Or maybe just show the last N messages as normal email history...

**Comment by luisfsr** [comment]
With 0.9.5 changelog (https://delta.chat/en/2017-10-08-delta-chat-0.9.5) maybe the this request lost its object, since the threads won't let non DC users lose track of previous messages.

**Comment by r10s** [comment]
Yes, I think we can close it. I also do not really like the idea of blowing up messages this way...
