### ISSUE TITLE
better support non Google play. fdroid not updating

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#1260]
Fdroid is still 1.12
Latest is 1.20

There needs to be a better way to keep users up to date with the latest version other then Google play.
Maybe rethink hosting your own fdroid repository or maybe have it hosted on issyondroid

**Comment by gerryfrancis** [comment]
Version 1.1.2 is still the latest **official** one. If you like to test the very latest versions and report issues, feel free to attend [here](https://support.delta.chat/t/who-wants-to-help-with-testing-new-releases/697).

**Comment by r10s** [comment]
yip, 1.1.2 are still the official releases. 1.2 is in tested currently and will be pushed to gplay and fdroid as soon as it is regarded as beging "fine" :)
