### ISSUE TITLE
release to production

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1262]
the android version in the app stores is no longer a beta-version and should no longer be flagged as such.

- in the google play store, the button "release to production" should do the job, maybe wait until we've rolled out 1.2.1 to 100%, however. not sure, btw, if this will reset download counters

- on get.delta.chat, remove the "beta" from the icon

**Comment by r10s** [comment]
did so :)

**Comment by webratte** [comment]
And the download counter is still not reset 👍

**Comment by r10s** [comment]
i think, it is not moved to "production yet", this may take a week or more currently ...

**Comment by webratte** [comment]
I don't think so.
I can switch between stable version and Beta.
So I'm relatively sure moving is finished.

**Comment by r10s** [comment]
ahh, one have to switch, didn't know that. you switch in the play store? where is the option?

**Comment by webratte** [comment]
Yes, in play store.

You just have to scroll down and choose "leave beta program".
