### ISSUE TITLE
Feature Request: Allow using multiple E-mail accounts

### ISSUE THREAD

**Issue by shoukolate** [deltachat/deltachat-android#1263]
Feature Request: Allow using multiple E-mail accounts to send and receive messages.

**Comment by r10s** [comment]
thank you for your suggestion.

however, this issue tracker is about bugs and things some developer has currently subscribed to - feature proposals should go to https://forum.delta.chat, in case of this topic, there is even already a proposal at https://support.delta.chat/t/multi-accounts-profiles-support/179

@shoukolate of course, if you're a developer and in case you want to work on this feature, we are very happy to re-open it.
