### ISSUE TITLE
diversify emojis

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1264]
Currently DC android supports only standard yellowish emojis whereas DC Desktop and iOS support emojis with different skin colors. 
We should adapt that on Android as well, in order to avoid the loss of content while messaging between the different platforms.
 I'm pretty sure, we can borrow some code from signal for an fast and easy solution.

**Comment by r10s** [comment]
wondering if this already works with the system-emojis enabled. i so, we could think about using them as default.

**Comment by link2xt** [comment]
At least the keyboard can be copied from signal. They have added interface to choose skin color for some emojis since we forked it.

**Comment by missytake** [comment]
Which emoji set do we ship currently?

Twitter has an open source emoji set. They have skin colors, nonbinary emojis, and even the black flag ;) https://emojipedia.org/twitter/

**Comment by cyBerta** [comment]
wow those are really cool, +1

**Comment by TrickTrackNO** [comment]
Unicode Emojies seems like a good plan.  Is the purpose of OP alternative rendering to OS?

**Comment by r10s** [comment]
what do you mean by "Unicode Emojies"? aren't all emojis unicode?
