### ISSUE TITLE
Messages not delivered

### ISSUE THREAD

**Issue by kuba-orlik** [deltachat/deltachat-android#1269]
- Android version: 8.1.0 
- Device: Nexus 5X
- Delta Chat version: 1.2.1
- Expected behavior: 
   Messages should be received by the other person
- Actual behavior:
   Messages are not received
- Screenshots:

![photo_2020-03-13_22-06-01](https://user-images.githubusercontent.com/2697916/76743269-47fa4600-676a-11ea-8ed7-8744e52709dd.jpg)
![photo_2020-03-16_10-38-39](https://user-images.githubusercontent.com/2697916/76743278-49c40980-676a-11ea-85c8-bd98102c6da2.jpg)

**Comment by r10s** [comment]
so the messages marked as being sent (the green ones on the right) did not find the way to the recipient?

is this only true for the given email address?

**Comment by gerryfrancis** [comment]
@kuba-orlik Have you switched off Autocrypt? See the "three-dot" issue https://github.com/deltachat/deltachat-android/issues/1082 .

**Comment by kuba-orlik** [comment]
It turned out the issue was not on DeltaChat side. My emails were bounced from the recipient's server.

**Comment by r10s** [comment]
@kuba-orlik you're welcome, thanks for coming back and clearing.
