### ISSUE TITLE
ndk-build failed

### ISSUE THREAD

**Issue by vitalyster** [deltachat/deltachat-android#127]
```
MessengerProj/jni/./mrwrapper.c:427: error: undefined reference to 'mrmailbox_set_chat_image'
```

**Comment by r10s** [comment]
should work again now (the reason was that an old deltachat-core was used, sometimes we forget to update them (but we never forget it on releases as otherwise F-Droid-build will fail as well :))

**Comment by vitalyster** [comment]
Thanks!
