### ISSUE TITLE
webview (used in help) may crash on android5 without google services

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1283]
see https://stackoverflow.com/questions/59572065/error-inflating-class-android-webkit-webview-on-android-5

this is fixed in `androidx.appcompat:appcompat:1.2.0-beta01`, however, we should probably wait until there is a stable `1.2.0` release to avoid maybe larger problems.

**Comment by r10s** [comment]
just had a look 1.2.0 is not yet out, but already a release-candidate, https://mvnrepository.com/artifact/androidx.appcompat/appcompat?repo=google

**Comment by cyBerta** [comment]
https://mvnrepository.com/artifact/androidx.appcompat/appcompat/1.2.0 
1.2.0 stable has been released
