### ISSUE TITLE
audio seekbar may show wrong position

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1288]
when an audio is played and scrolled up, other audios have the progress bar moving like if it is playing. maybe because of android list recycling elements.

reported on "Testing Delta Chat" group.

**Comment by cyBerta** [comment]
I'm able to reproduce that bug.

**Comment by AndreaEnzoLattmann** [comment]
The problem is also present in 1.36.2

https://user-images.githubusercontent.com/130047141/230353063-a0bad34b-6e69-48b2-abf6-caba365e7fd5.mp4
