### ISSUE TITLE
leaving groups not possible in nightly

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1289]
when pressing the leave group option, a toast "done" is shown, but no system message "group leaved by me" is shown/sent. therefore, probably also other are not aware that one has left the group.

maybe this is true only for groups having no group-image; there is another report that says "deleting group images in the blobs folder causes the bot to fail to send the "user added" message"

both reported in the "Testing Delta Chat" group - thanks a lot for getting such feedback in time!
 
in the official release, this bug is not present.

**Comment by Hocuri** [comment]
That's already fixed.

**Comment by r10s** [comment]
thanks for checking!
