### ISSUE TITLE
bad/no notification in case of new message

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1295]
There are different situations where we have bad or even no notification for new messages. Even with current v1.3.0 version.

1. no notification
a) When DC is in background and possibly is stopped by OS (issue exists, reopen requested)
b) When another mail client (most of time from provider) installed at same device for same account than DC (sometimes additionally a web client).

2. bad notification
Android version 4, 5, 6, 7, 8: only a small delta is shown at top status bar. No badge counter, no dots at start screen icon. This small delta gets lost in the shuffle of other apps badges for common users.

Some examples will follow.

**Comment by csb0730** [comment]
New message at tablet with Android 7

![tablet-notification](https://user-images.githubusercontent.com/30560716/79082723-fe7d2680-7d28-11ea-89d2-340d614864f4.png)


Comment for notification behaviour at Android 10 device (10.00.190)

![immer schlechter notification](https://user-images.githubusercontent.com/30560716/79082629-cde8bd00-7d27-11ea-8ea5-cf5b7b93cd46.png)

Comment from another colleague with Android 10 device:
Q: How did you detect the new message in DC?
A: I only got a notification from my other email app. Then I saw it in DC!


==> All this makes DC to be unreliable for end user (!)

**Comment by webratte** [comment]
> Comment from another colleague with Android 10 device:
> Q: How did you detect the new message in DC?
> A: I only got a notification from my other email app. Then I saw it in DC!
> 
> ==> All this makes DC to be unreliable for end user (!)

That's exactly what I here from friends of me. 
Therefore I vote for working Badge counter again and again.

**Comment by gerryfrancis** [comment]
FYI: https://support.google.com/pixelphone/thread/8745516?hl=en

**Comment by webratte** [comment]
Sorry, my english is really bad.
Do I understand correctly, you suggest to install a additional luncher?

Please correct me if I understand it wrong.

I think it's not the way to install third party software to make a App work.

E.g. Threema show the badge counter on my phone.
So it seems there exist a way to make the badge counter work without to install additional software.

**Comment by r10s** [comment]
please avoid mixing two things in on issue already in the initial post, this makes things hard to discuss and to figure out actionable items

- the badge counter is a feature requests and it was already discussed here several times, with the outcome that notification needs basic refactoring, see eg. https://github.com/deltachat/deltachat-android/pull/1010 and that it might be better to just depend on what the systems offer.  but anyway, feature requests should be discussed in the forum at https://support.delta.chat

- the missing or delayed background thing can be filed and discussed in a new issue, of course, or we can reopen https://github.com/deltachat/deltachat-android/issues/1168 if this matches the the things you observed.

so, i suggest to close _this_ issue.

**Comment by gerryfrancis** [comment]
> feature requests should be discussed in the forum

@r10s Hard to understand for those who had this feature in the past: https://github.com/deltachat/deltachat-android/issues/1189#issuecomment-568309923

For some apps, this feature was "stolen" from Android. The average user does not care whether the badge comes from Android or Delta Chat. It was there before for some users. From the view of an app developer, of course, it is a "new" feature now.

From "We Care A Lot" (Faith No More): _"Oh, it's a dirty job but someone's gotta do it"_

**Comment by r10s** [comment]
let's discuss this part in the forum.

**Comment by csb0730** [comment]
@r10s and all other developers
I filed this issue because I see the situation around notification really serious meanwhile!

Again, we discuss about that for quite a year now in dedicated issues, but there's no solution. The planned solution to use Android system's possibilities seems not to be a general solution. This proves up to now all experiences at different devices and different Android versions (!).
It feels to me, that I'm the only one which has a badge counter! But not because my Android system provides it - no - because my delta chat fork provides it.

What is the history?
There has been some code cleaning (I think @cyBerta did it) around notifications. Ok, so far.
But then v0.304 missed the formerly existing badge counter.
After some hints cyBerta did a PR to bring the badge counter again.
PR was closed but never introduced.
Meanwhile I integrated the PR, have tested it at my own device (Android 4) and using it (works fine).
The necessary library is existing up to now in current version of build.gradle (!).
Only operational source code is missing (PR).

What is the result/situation?
All Android versions from 4-8 (in any case) doesn't show any badge counter. Many complaints!
Situation at Android 9 is not reliable.
Situation at Android 10 is not reliable too, in any case no badge, but there may be additionally a background issue.

Maybe this issue here mixes the details a little - Ok - but it should summarize too!
Further it should focus our mind to the fact: We have a problem.

I think the focus on that notification subject has been lost because of spreading that subject over some individual technical problems.

I want to remark explicitly that I want to prevent common users throwing DC away because they can't rely on it (!)

Notification is one of the main features of a messenger.

**Comment by csb0730** [comment]
One word to android 8 api usage: This doesn't help for all lower androids! Do You want to keep them all out of the door?!

**Comment by r10s** [comment]
i agree, this is a long standing issue - as many others.

**Comment by adbenitez** [comment]
I agree notification is important, but a badge counter will solves nothing, the same thing can be archived without it, a real issue is delta chat been killed in the background, apks like Conversations and Telegram(from fdroid) offer an option to show a permanent notification, why we don't offer that option in DC? that will solve a lots of issues, your badge counter can't count anything if the app isn't even checking for new messages

**Comment by adbenitez** [comment]
(note: I am not against a badge counter, that will be fine to have, but my point is that there are bigger issues, people can't relay in DC because it gets killed and they miss new messages)

**Comment by r10s** [comment]
@adbenitez for permanent notification i've summarized the situation at https://support.delta.chat/t/show-a-permanent-notification/943

**Comment by csb0730** [comment]
@adbenitez 
One last word: Yes the badge counter alone doesn't solve any problem if DC isn't able to receive new msgs, but receiving a message alone without giving the user an reasonable notification doesn't help too.

Both is a must.

A message is intended from user to receiving user (!), not only from user to receiving DC ;-)


Ok, let's go to the support forum.

**Comment by csb0730** [comment]
@r10s 
Why do we discuss all this at forum? I mean we are speaking about real issues, isn't it?

**Comment by r10s** [comment]
well, it is getting a meta discussion :)

let's continue that in the forum :)

(feature request should go to the forum to keep this tracker focused on bugs and on things people are currently working on. otherwise, we easily have some thousands of open issues, and this is not how we want to work, this was discussed at some time with broad consent (maybe it is not well communicated, however) (and, i regard a badge-counter for some launchers for android<=7 as a feature request, pros and cons are already discussed)

to the other initial bug: if we have concrete information about that, that should go to another ticket here in the issue tracker.

**Comment by solidboredom** [comment]
i completely second that, it takes a lot of effort to talk my friends off whatsup and into using deltachat, and then,only two out of seven people, get notifications, deltachat  is essentially unusable for the rest of them. and it  will almost impossible to talk them into using it again now....after trying it. so sad.. i think deltachat is such a great idea, but now even i start thinking about alternatives. I need something to really get my friends off Whatsup and co, but something they can use....

**Comment by hpk42** [comment]
On Sun, Apr 19, 2020 at 01:20 -0700, solidboredom wrote:
> i completely second that, it takes a lot of effort to talk my friends off whatsup and into using deltachat, and then,only two out of seven people, get notifications, deltachat  is essentially unusable for the rest of them. and it  will almost impossible to talk them into using it again now....after trying it. so sad.. i think deltachat is such a great idea, but now even i start thinking about alternatives. I need something to really get my friends off Whatsup and co, but something they can use....  

We are aware of the pain -- it's just a lot of effort (and growing) to circumvent/neutralize 
the google policies (on ios it's even harder) of them wanting to route notifications
through their centralized clouds. Have you btw seen https://dontkillmyapp.com/ ? 
Would be interesting if you can at least find some of your friend's phones there
and maybe find a remedy for the time being.  Hopefully we find better ways --
we are also talking with other projects who face the problem from time to time.
But so far no one has a golden bullet.

**Comment by gerryfrancis** [comment]
Thanks @r10s and @hpk42 for your detailed explanations about the current situation, and thank you very much for your commitment to cope with it. You and the whole Delta Chat team are working very hard to compete against all the other well-established messengers, and therefore I am convinced, for the success of Delta Chat, you will keep an eye on this. Keep up the great work! :+1:

**Comment by solidboredom** [comment]
@hpk42
 thanks for your efforts from me too, yes i have seen dontkillmyapp, but why there is no permanent notification option? everybody else does it.

**Comment by r10s** [comment]
as said, the permanent notification is added when the screen is turned off, see https://support.delta.chat/t/show-a-permanent-notification/943/9

**Comment by EchedeyLR** [comment]
Giving my point to the issue with the permanent notification, just to add that I consider it critical in order to be able to work (no-one is going to be checking manually the app for notifications and less in the common environment in Spain and have examples to all classmates, family and friends).

In LineageOS 14.1 (Android 7.1.2) in  BQ Aquaris U Plus, background service seems not working anymore from some versions ago (using Disroot provider from a little and Riseup before) even when battery optimizations are enabled. I am not sure when it failed to work but I even tried a clean installation and disabling battery optimizations again.

Another recently case was a classmate who I invited in order to be able to communicate with me. I don't remember it's phone nor Android version (is newer than mine in stock rom at least) and I helped to disable background optimizations of the app. That person (using GMail provider) notifies me to have to open the app in order to receive the notifications or he will receive them as mail notifications (disabled because no-one here cares about that) but confirmed when I told him to check.

In both cases the app is killed at the same time you close the app window.

**Comment by gerryfrancis** [comment]
@EchedeyLR Not sure if you are referring to battery optimizations or background optimizations, or is it basically the same?

**Comment by hpk42** [comment]
some people who only rarely use DC get reminded to open it when their
"normal" email program notifies them about an incoming mail.  Not really
a solution but just wanted to point out that it reduces the risk of
not seeing a message.

let me note also that there are some discussions within dev-space to 
establish cloud-integration after all -- it's not imminent 
but if the background-killing proves to be a growing problem 
we might have to think about giving users the option. 
It would mean that there needs to be a server registered with 
icloud/google-cloud and there are questions how we arrange this. 
Just wanted to note this here to indicate that we are considering
options even if they go a bit against the grain of what we want to 
achieve, decentralization etc.  Most people use their android
(and iPhone) anyway pretty much tied up already with the two 
centralized vendors.

**Comment by EchedeyLR** [comment]
> some people who only rarely use DC get reminded to open it when their "normal" email program notifies them about an incoming mail. Not really a solution but just wanted to point out that it reduces the risk of not seeing a message.

replied here:
" he will receive them as mail notifications (disabled because no-one here cares about that) but confirmed when I told him to check."

**Comment by EchedeyLR** [comment]
> @EchedeyLR Not sure if you are referring to battery optimizations or background optimizations, or is it basically the same?

I tried to reply you by mail but it seems that was sent and not processed or something. In summary I was trying to help you that in its (classmate) phone there are no "battery optimizations" as that. It's called "background optimizations" instead. Making a reference as suggestion to the dontkillmyapp webpage.

**Comment by EchedeyLR** [comment]
I am interested in the permanent notification solution as its the most reliable for this case.

**Comment by EchedeyLR** [comment]
> let me note also that there are some discussions within dev-space to establish cloud-integration after all -- it's not imminent but if the background-killing proves to be a growing problem we might have to think about giving users the option. It would mean that there needs to be a server registered with icloud/google-cloud and there are questions how we arrange this. Just wanted to note this here to indicate that we are considering options even if they go a bit against the grain of what we want to achieve, decentralization etc. Most people use their android (and iPhone) anyway pretty much tied up already with the two centralized vendors.

In reference to this part: before thinking on that, check what was with Tutanota (https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html) or OpenPush (https://bubu1.eu/openpush/) already discussed a bit in https://github.com/wireapp/wire-android/issues/233. But that would make DeltaChat itself internet dependent.

**Comment by solidboredom** [comment]
@hpk42 

> Most people use their android
(and iPhone) anyway pretty much tied up already with the two
centralized vendors.

well, most people use whatsup anyway, so why even bother with deltachat then?
i am pretty sure we are THE bunch of people here whose phone is not completely tied to google, or at least we try to acheive this, by switching to Deltachat. well.. tell me if i am wrong.
so how difficult would it be, to disable the notification hiding and just giving it a try?
anybody here can do a fork?

**Comment by hpk42** [comment]
FYI we'll take all the suggestions here under consideration:

- optional permanent notification is probably a good thing to try
  in the shorter term. 

- better docs/guidance, and maybe a message in the device chat after 
  we detect that the app is killed often in background, pointing
  to dontkillmyapp and potential remedies. 

- optional cloud integration maybe in the longer term -- Delta Chat 
  is not meant only for privacy or decentralization nerds. There
  are in fact a lot of users who dislike facebook/whatsapp yet
  are not able or ready to root/modify their phone fundamentally. 

Note that the next releases have in any case a different focus 
as we are struggling with ECC-key move, ephemeral messaging
and a multitude of other minor yet important things.  

cheers holger (suggesting to put this issue here to rest for now)

**Comment by EchedeyLR** [comment]
> optional cloud integration maybe in the longer term -- Delta Chat is not meant only for privacy or decentralization nerds. There are in fact a lot of users who dislike facebook/whatsapp yet are not able or ready to root/modify their phone fundamentally.

Could be taken in account the services I pointed too like OpenPush or SSE in Tutanota if it is the case in a future?

**Comment by hpk42** [comment]
sure, i edited my post. thanks for the links

**Comment by r10s** [comment]
unconditional permanent notification: https://github.com/deltachat/deltachat-android/pull/1302

**Comment by csb0730** [comment]
> @hpk42
> 
> > Most people use their android
> > (and iPhone) anyway pretty much tied up already with the two
> > centralized vendors.
> 
> well, most people use whatsup anyway, so why even bother with deltachat then?
> i am pretty sure we are THE bunch of people here whose phone is not completely tied to google, or at least we try to acheive this, by switching to Deltachat. well.. tell me if i am wrong.
> so how difficult would it be, to disable the notification hiding and just giving it a try?
> anybody here can do a fork?

IMHO I think when an approach or a feature needs to be tested on a wide user base then it would be a good idea to
- make the interesting approach/feature switchable by user setting and
- give every user the possibility to check if it's working or not (clear indicator; existing log extract is not usable for common users)

**Comment by r10s** [comment]
wrt the tutanota link: at a first glance, basically, this is the same Delta Chat is doing, https://support.delta.chat/t/show-a-permanent-notification/943/18

**Comment by EchedeyLR** [comment]
> wrt the tutanota link: at a first glance, basically, this is the same Delta Chat is doing, https://support.delta.chat/t/show-a-permanent-notification/943/18 - also the openpush probably has similar issues, https://gitlab.com/Bubu/pushclient/-/issues/4 , so, all in all i did not find new approaches or so.

The this work as examples of use cases at least and as channels that should be maintained in order to see how they solve the situation.

**Comment by r10s** [comment]
> Then these work

sure, maybe we've done sth. wrong, but at least _i_ cannot see what. also, also tutanota and openpush seems to have issues, just a random link https://www.reddit.com/r/tutanota/comments/aqpm8g/android_app_gets_closed_in_the_background_and_i/ - for openpush above - i mean, this is the reason https://dontkillmyapp.com exist. however, two apps might be hard to compare, even on the same device, as the reasons for killing might be quite different. and it is not the case that Delta Chat just killed always and everywhere :)

but anyway, we'll try the permanent notification in the next release, and also the suggesion of an uptime counter from @csb0730 looks like a good idea to me.

**Comment by EchedeyLR** [comment]
The thing I don't understand yet and that I must recognize is why stopped working in a non-updated LineageOS release with battery-optimizations disabled for the app in the last versions...

Taking in account AOSP v7.1.2 and references in https://dontkillmyapp.com/ doesn't make any sense that working in releases before, stopped working suddenly in the last ones, doesn't fit also with the own logic...
