### ISSUE TITLE
Reply with non member address to group deletes all group members

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1299]
- Android version: 4.1.2
- Device: S3
- Delta Chat version: v0.500.0

- Expected behavior:
New mail address should be added to group (and one-to-one message should be marked as
one-to-one in group)

- Actual behavior:
All members of existing group are purged from group
New mail address is added to group
"me" is still existing and is not purged
==> group has only the two members "me" and new address (replied the mail).
group name stays

- Steps to reproduce the problem:
Create a group with members A, B, C, D and ME (myself)
Write a message in group and send it
Receiver C (for example) replies with standard MUA, but
  * with a different mail address F (C=>F)
  * and only to me (one-to-one) !
  * Mailheaders "In-Reply-to" and "References" match exactly first mail sent from group

Maybe this issue is existing in actual version too?

**Comment by r10s** [comment]
there were several changes in the group handling the last month, latest eg. https://github.com/deltachat/deltachat-core-rust/pull/1342, so i think, this has to be checked in 1.3 or 1.5

**Comment by adbenitez** [comment]
IIRC, this issue was reported, and already solved. It happened to me and some friends in the past (pretty old past, new versions work like a dream :)

**Comment by r10s** [comment]
thanks for cleariying, @adbenitez

**Comment by csb0730** [comment]
Did a retry with DC v1.2.1 (my own fork)

Expected behavior is working as described in first post.
In chat there appears a message with following text:
"[Unknown Sender for this chat. See 'info' for more details.]"
With Info you can see message text.

I can confirm: **Issue solved** :+1: :-)

Old version was the reason for the issue.

**Comment by csb0730** [comment]
@r10s you can take the tag away

**Comment by r10s** [comment]
thanks for trying over!
