### ISSUE TITLE
An object (image), "shared" to Delta Chat once, appears again forever in Chat editors until app is closed

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-android#1305]
- Android version: Lineage 14.1 and Android 6.0
- Device: Google Nexus 7 and Motorola moto E3 
- Delta Chat version: 1.3.0
- Expected behavior: After having sent the shared image object once, at next time entering the chat, the message editor prompt line should be empty. 
- Actual behavior: When going into any chat later, the image object appears again. Cancelling it via "(x)" in corner enables writing message, but does not stop it from re-appearing next time again. Only closing the app and reopening makes stops it from re-appearing. Does not happen with other "share target" (other messengers) on mentioned platforms.
- Steps to reproduce the problem: pick a picture, select share, select delta chat.
- Screenshots: -
- Logs: -

**Comment by r10s** [comment]
thanks for filing the issue.

i could reproduce this only when i decided _not_ to send the image on sharing, however.
