### ISSUE TITLE
Error message is hard to understand

### ISSUE THREAD

**Issue by rrthomas** [deltachat/deltachat-android#1313]
I got the an error message, part of which reads:

"Some providers place additional information in your inbox; you can check them it eg. in the web frontend."

This is hard to understand. I am a native English speaker; if someone can tell me what the message is supposed to mean, I would be very happy to write a better version so that users can more easily understand it.

I can't understand the first half of the sentence. Does it mean that there might be an explanation of what just went wrong as an email in my inbox?

The second half of the sentence is just written a bit obscurely. I would suggest instead:

"you should be able to check your inbox in your regular email app or web site."

Thank you very much for DeltaChat; I wish I'd had it many years ago!

**Comment by r10s** [comment]
>  Does it mean that there might be an explanation of what just went wrong as an email in my inbox?

yip, some providers do that, however, we actually do not know.

**Comment by rrthomas** [comment]
Great, so here's a complete suggestion for a better message:

"Some providers may email you additional information about this problem; you should be able to check your inbox using your regular email app or web site."
