### ISSUE TITLE
Using OAuth2 with G Suite

### ISSUE THREAD

**Issue by rrthomas** [deltachat/deltachat-android#1314]
- Android version: 9
- Device: Sony Xperia XZ1 Compact
- Delta Chat version: 1.3.0

I'm trying to use a Google G Suite email address with DeltaChat. I have successfully set up a regular GMail address, where the OAuth2 flow is automatically entered. With my G Suite address, obviously the OAuth2 flow is not detected. I have put in all the details as normal for ingoing and outgoing server, and selected OAuth2 as authentication method, but login just times out every time. When I use the same settings in Thunderbird, it works fine.

I looked in the FAQ and found nothing about this. I found this recent thread in the forums: https://support.delta.chat/t/oauth-with-google-g-suite/845 but with no solution, and it didn't seem to have been replied to by any devs.

Sorry if I've overlooked something, and thanks for DeltaChat!

**Comment by r10s** [comment]
currently, this is not possible, you have to use an `@gmail.com` address for oauth2 _or_ enable an app-password _or_ less-secure-apps.

**Comment by r10s** [comment]
i've also commented at https://support.delta.chat/t/oauth-with-google-g-suite/845 with some more detail, let's continue the discussion there.

**Comment by hpk42** [comment]
Reuben -- if you can, it would be great if you could find out if
there is are reliable network queries to detect G-suite domains/mail addresses. 
We could potentially do this query at account-setup time. 
If so, please open an issue describing/linking it as precisely as possible. 

For your background: we can do all internet queries, i.e. DNS or http-requests
from our core library https://github.com/deltachat/deltachat-core-rust
which is used on all platforms.

**Comment by rrthomas** [comment]
Thanks, @hpk42, see issue #1318.

The other obvious possibility would be to allow OAuth2 to be selected (as for example in Thunderbird) manually. Indeed, it is already possible to select OAuth2 in the Advanced options, but nothing seems to happen as a result; is this a bug?

**Comment by r10s** [comment]
> is this a bug?

no, it is just not supported for random domains. unfortunately, oauth2 is not that open and requires lots of adaptions to support each and every provider.

**Comment by rrthomas** [comment]
Thanks for explaining, @r10s. In that case, perhaps OAuth2 could appear in the list of authentication methods only for supported domains? Otherwise it's a little confusing (as I found!).

**Comment by hpk42** [comment]
On Sat, Apr 25, 2020 at 06:28 -0700, bjoern wrote:
> > is this a bug?
> 
> no, it is just not supported for random domains. unfortunately, oauth2 is not that open and requires lots of adaptions to support each and every provider.

oh, forgot about htis. Does Gmail policy-wise prohibit to use oauth2 with custom G-suite domains? 
Wait a second -- do custom google domains support imap/smtp?

**Comment by rrthomas** [comment]
@hpk42: yes to both questions: I use my G Suite account quite happily with OAuth2/IMAP in Thunderbird (and I've previously used it with IMAP and old-fashioned authentication in DeltaChat).

**Comment by r10s** [comment]
@rrthomas opened a corresponding and more focused issue at https://github.com/deltachat/deltachat-core-rust/issues/1425
