### ISSUE TITLE
Question about NDK r21 support

### ISSUE THREAD

**Issue by EchedeyLR** [deltachat/deltachat-android#1316]
I wanted to be sure if NDK r21 is also allowed to build Delta Chat for Android as "ndk-make.sh" had r20 as the minimum requirement.

**Comment by r10s** [comment]
i do not have any hints that it is not working, however, after all experiences in the past, i would also not be astonished if it results in problems. in general, we are a bit careful in changing ndk, sdk etc. and do it not without good reasons :)

**Comment by EchedeyLR** [comment]
Then, I think that, in the make-ndk.sh file, "minimum" should be changed to just "required" in raw and publish a note about that higher versions were not tested.

**Comment by r10s** [comment]
i think, the hint is fine, it is the minimal version that is needed
- older versions are known not to work
- newer versions will likely work, however, can cause problems (as virtually everywhere)

but a pr that clarifies that, of course, is welcome.

**Comment by EchedeyLR** [comment]
Seems that anyone submited a pull request yet...

Well, just to wait as I only have this account to make reports with only 2 exceptions.

**Comment by r10s** [comment]
i fear, i did not understand what you are meaning :)

which pull request are you referring to?  
or do you want to add a  pull request? or are you wating for one?

**Comment by EchedeyLR** [comment]
Waiting to see if any other person submit one.

**Comment by r10s** [comment]
it is about clarifying things in the README? not sure if someone is on that, i do not think so :)

however, i suggest to close this issue, i think the initial question is answered :)

**Comment by r10s** [comment]
sth. like that: https://github.com/deltachat/deltachat-android/pull/1351

**Comment by EchedeyLR** [comment]
> sth. like that: https://github.com/deltachat/deltachat-android/pull/1351/files

I already replied there as a review.
