### ISSUE TITLE
back button in chat window does not go back to start page (contacts) but ends app

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-android#1317]
- Android version: Lineage 14.1
- Device: Nexus 7 (2012)
- Delta Chat version: 1.3.0
- Expected behavior: When hitting the Android "back" icon in a chat view, I expect the app to return to the start screen with the contacts list.
- Actual behavior: Delta Chat closes.
- Steps to reproduce the problem: does not happen everytime, just sometimes. I suspect this corelates with entering the app via a "share to" function from another app.
- Screenshots: -
- Logs: -

**Comment by r10s** [comment]
thanks for filing the issue, would be great if you can find out a way to reproduce that reliably :)

**Comment by Hocuri** [comment]
Steps to reproduce: 
- Hit share in another app
- Select Delta Chat
- Select a chat and send
- Hit back.

**Comment by Hocuri** [comment]
Just tested, this is fixed by #1311
