### ISSUE TITLE
Contact requests are never emptied

### ISSUE THREAD

**Issue by thenktor** [deltachat/deltachat-android#132]
Hi,

all messages stay in contact requests section, even if they are already deleted in another mail client.

**Comment by r10s** [comment]
Yes, this is an area I also want to seen reworked ... also the name "Contact requests" is not perfect IMHO

**Comment by thenktor** [comment]
Yes, the name also is ambigous. Actually it shows just "other e-mails" or "non delta chat e-mails".

**Comment by Ampli-fier** [comment]
If those messages shall be seen as "contact requests" it would be enough to keep the last mail that was received per (sender) address.

**Comment by thenktor** [comment]
That's also a good idea. But still I think that deleted mails also should be removed from that page.

**Comment by r10s** [comment]
> That's also a good idea. But still I think that deleted mails also should be removed from that page.

I've just implemented this yesterday for messages deleted on the device, see
https://github.com/deltachat/deltachat-core/commit/baca7ee53e2e6d153a0d00b40cfd7e97a80294e0

**Comment by r10s** [comment]
included in #22
