### ISSUE TITLE
Messages sent from plain clients to "group" are not displayed in chat

### ISSUE THREAD

**Issue by vitalyster** [deltachat/deltachat-android#133]
Guess we should check for new "send" messages? Is it possible in IMAP? :) Or GMail issue?

**Comment by vitalyster** [comment]
After app freeze and force close I see my messages :)

**Comment by r10s** [comment]
There are some Gmail issues, eg. the Chats-folders does not work as expected, however, the "send" messages should appear in Delta. Or did you mean this by the second comment? If so we can close this issue :)
