### ISSUE TITLE
Contact import mix mail addresses

### ISSUE THREAD

**Issue by matclab** [deltachat/deltachat-android#1334]
I just tried deltachat 1.3.0 on android 10, and when importing contacts I get the following contact list: 
1. Name : first contact address
    Address : second contact address
2. Name : third contact address
    Address : fourth contact address
3. ...

Thus when selecting a contact it sends the mail to the wrong address...

**Comment by r10s** [comment]
interesting, have not seen that. can you reproduce the issue?

looking at the code, one thing i can imagine is that this happens for names or emails containing a linebreak (`\n` is used as a field separator in the stream of name - mail - name - mail - name - mail ....) - can you confirm that somewhow? does the order break at some special name? 

ftr, the belonging code https://github.com/deltachat/deltachat-android/blob/91be337fb68cb75712c64a3d01b94409329af675/src/org/thoughtcrime/securesms/contacts/ContactAccessor.java#L81

**Comment by r10s** [comment]
i prepared a fix @matclab  once that is merged, it would be great if you can checkout with a [nightly](https://delta.chat/en/download#preview-builds) if this actually works for you.

**Comment by matclab** [comment]
I have some contacts that have two mail addresses, and indeed perhaps that `systemContactsCursor.getString(CONTACT_CURSOR_MAIL)` return a string with mail addresses separated by `\n`. I'll try the nightly once merged.

One thing that is strange is that I didnt,' find one contact whose name is not an email address (x@y.tld).

**Comment by r10s** [comment]
@matclab i built a version with this pr, so no need to wait for the nightly: https://send.firefox.com/download/fbb2e8c54341ebca/#YE8KKgLsxZCzz3FLs4gyEA 

you can install the version together with your "normal" Delta Chat, the test-version has a "Dev" on the log.

would be great if you can check, if this fixes the issue :)

**Comment by matclab** [comment]
@r10s yes, it works like a charm. All contacts are present with the good name and the good mail address.
Thanks a lot ! It was a fast bug chase !

**Comment by r10s** [comment]
@matclab thanks a log for the detailed report and for testing and quick responses!
