### ISSUE TITLE
Can not read "encrypted" messages from plain client

### ISSUE THREAD

**Issue by vitalyster** [deltachat/deltachat-android#134]
I see "encrypted message" in my gmail webinterface, what can I do to read it? :)

**Comment by vitalyster** [comment]
And also sometimes I see "encrypted message" in web, but no any new message in delta chat
And also sometimes people with delta chat see "encrypted message" from me in delta chat itself!

**Comment by rizzopablo** [comment]
You have to export DeltaChat encryption keys and configure them in your mail client to read this messages. I use Thunderbird + Enigmail which decrypts and allows me to read this messages.
27 de julio del 2017 15:30, "vitalyster"  escribió:
	And also sometimes I see "encrypted message" in web, but no any new message in delta chat
And also sometimes people with delta chat see "encrypted message" from me in delta chat itself!

**Comment by vitalyster** [comment]
Not much user friendly for casual people :/ and not possible for public web clients

**Comment by rizzopablo** [comment]
Private key can not be transferred so easily to autoconfigure other
email clients, security depends on private key being secret. Also most
mail clients, specially popular webmails like gmail, don't support
autocrypt.
Do you know any way to autoconfigure criptography in gmail and the other
popular mail clients?
