### ISSUE TITLE
Delta loses connection, with mail bag (Cuba) on Xiaomi devices

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1343]
- Android version: 9
- Device: xiaomi mi A3
- Delta Chat version: 1.6.*
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:

In Cuba there are two ways to connect to email by mobile data,
1 internet packages
2 mail bag

The "mail bag" only allows connection "to nauta mail, and to a few other national sites.

I have noticed that the use of Nauta mail is quite stable and fast when using internet packages, but when I am using delta "mail bag" it loses connection easily, mainly after a short period of inactivity.
This is fundamentally so on xiaomi devices,

reestablishing the connection solves the problem.

Note
In these conditions, I can only check the mail, through the web with Chrome. Indicating that there is a connection.

I did the log capture, after resetting the data.
- Screenshots:
- Logs:
[deltachat-log-20200504-064711.txt](https://github.com/deltachat/deltachat-android/files/4595574/deltachat-log-20200504-064711.txt)

**Comment by gerryfrancis** [comment]
@agutierrez25249 The latest version of Delta Chat for Android is 1.6.2, could you give it a try and report back, please? Thanks in advance.

**Comment by agutierrez25249** [comment]
I can say that this problem is related to
https://github.com/deltachat/deltachat-android/issues/1218

**Comment by agutierrez25249** [comment]
@gerryfrancis 
yes, it happens to me in v1.6.2 too

**Comment by gerryfrancis** [comment]
@agutierrez25249 Thank you for the logs.

I have recognized that the connection to `smtp.nauta.cu` was cut on `05-03 07:31:46.380` while `imap.nauta.cu` was still working. The next day, imap.nauta.cu could not be reached anymore on `05-04 06:43:00.073`.

Do you think it is possible that nauta.cu kills the threads for SMTP and IMAP after e.g. 24 hours, and denies further login attempts for some time?

**Comment by agutierrez25249** [comment]
I don't think it will, but I have no way of proving it

**Comment by gerryfrancis** [comment]
> I have no way of proving it

@agutierrez25249 I think you can find out. Note the time, restart your device, and open Delta Chat, then leave everything as is for at least 24 hours. Afterwards take a look at the log, especially at the time when the app has been started, and the time when messages cannot be sent/received anymore. If this occurs approximately 24 hours after Delta Chat has been started, you can assume that `nauta.cu` cuts the threads.

**Comment by agutierrez25249** [comment]
Of course, I can do it, as soon as I get another mobile,
 In my house there is no cell coverage and I must necessarily change from network to Wi-Fi.

**Comment by r10s** [comment]
i am not totally sure what the current state of this issue is, however, we fixes  lots of things since then, esp. for nauta; please open a fresh issue if the problem persists with new logs.
