### ISSUE TITLE
TrackerControl reports one tracker for delta chat

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#1344]
I have noticed, that the App "TrackerControl" reports one tracker for the most recent version of delta chat (1.6.2). The tracker is called "United Internet Media". Blocking it seems to be OK. delta chat still works. Since I cannot find this tracker mentioned in the documentation, I was wondering what this is.

**Comment by gerryfrancis** [comment]
@kollokollo Which mail provider do you have? Can you send and receive messages with Delta Chat?

**Comment by kollokollo** [comment]
It is web.de. Seems I can send messages. But reception is blocked now. OK, that would be it. Thanks for the hint.

**Comment by kollokollo** [comment]
Seems like web.de belongs to that company united media. Indeed, the email provider is itself a tracker. So everything is correct here. I just did not know.

**Comment by gerryfrancis** [comment]
@kollokollo Yeah, that is the price of freemail: You pay with your data. ;) Anyway, thanks for coming back. Please close here if you think that the issue is solved. Thank you.

**Comment by kollokollo** [comment]
I raised this issue in the TrackerControl community. https://github.com/OxfordHCC/tracker-control-android/issues/23 Maybe this should be addressed with a different default setting there. So I can close this Issue here....
