### ISSUE TITLE
Draft file name "Unknown"

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1347]
- Android version: 9
- Device: Fairphone 3
When sharing a file to Delta Chat and then selecting a chat, "Unknown" is shown instead of the file name. What I found out so far: The filename is still there at the beginning of `AttatchmentManager.setMedia()` (in the "uri" variable) but vanishes somewhere before `documentView.setDocument((DocumentSlide) slide);` is called. Reported at https://github.com/deltachat/deltachat-android/pull/1342.

**Comment by mailgate** [comment]
if sharing from another app with SEND Intent, the problem persists and the filename is not restored after "Unknown" draft stage. Can be reproduced with the following code (formatting done by github):

                try {
                    Intent emailIntent = new Intent(Intent.ACTION_SEND);
                    // prepare a file for sharing...
                    File f = new File(getFilesDir() + "/somebinaryfile.bin");
                    f.createNewFile();
                    byte[] b = new byte[1024];
                    new Random().nextBytes(b);

                    // write random data
                    FileOutputStream fOut = new FileOutputStream(f);
                    DataOutputStream dataStream = new DataOutputStream(fOut);
                    dataStream.write(b);
                    dataStream.close();

                    Uri sharedURI = FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".provider", f);
                    emailIntent.putExtra(Intent.EXTRA_EMAIL, new String[]{"someone@example.com"});
                    emailIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                    emailIntent.putExtra(Intent.EXTRA_STREAM, sharedURI);

                    // it will try to start BETA package, so only for development purposes!
                    emailIntent.setComponent(new ComponentName("com.b44t.messenger.beta", "org.thoughtcrime.securesms.ShareActivity"));

                    // at this stage, sharedURI has the format: content://{my sending package name}.provider/files/somebinaryfile.bin
                    Log.d(tag, sharedURI.toString());
                    startActivity(emailIntent);
                } catch (IOException e) {
                    e.printStackTrace();
                }catch (ActivityNotFoundException e) {
                }
![sharing_by_intent](https://user-images.githubusercontent.com/64929236/81500666-66993b00-92dc-11ea-9917-31039de42621.png)

and below is step-by-step sharing from my stock file manager. Avdroid version 9, AndroidOne, Xiaomi A2:

![sharing_from_stock_file_manager](https://user-images.githubusercontent.com/64929236/81500971-49656c00-92de-11ea-9195-460f7b1fdd21.png)

**Comment by Hocuri** [comment]
@mailgate Now I see what you meant with "the filename is not restored after "Unknown" draft stage". I always looked for "Unknown" but it's the current date.

Yes, #1350 also fixes this, I just tested it.

**Comment by mailgate** [comment]
Awesome! As I initially expected, the issue fixed by couple lines.
Sorry I didn't dig further to find the easiest solution. )

**Comment by Hocuri** [comment]
No problem, the issue was fixed easily but rather difficult to find
because the file name is passed around a long way before it is shown to
the user and set in the mail.
