### ISSUE TITLE
Battery drain with chello.at account (a domain of Magenta Austria)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1348]
- Android version: 10.

- Device: Google Pixel 3a.

- Delta Chat version: 1.6.2/1.8.0.

- Expected behavior: No issues.

- Actual behavior: Battery drain, probably due to an issue with a chello.at account.

- Steps to reproduce the problem: Clean install (no update) of Delta Chat (version 1.6.2) and initial configuration of chello.at account.

- Logs: [Delta_Chat.txt](https://github.com/deltachat/deltachat-android/files/4604138/Delta_Chat.txt)
The app seems to be stuck in a loop, draining the battery.

- Remarks:
-- I deleted the fingerprint value from the attached log.
-- App data and cache were cleared before configuring the account.
-- This issue occurs with the chello.at account of my wife. However, messages can be sent and received. When I set up my posteo.de account on her smartphone device, there is no such issue.
-- This issue did not occur with version 1.1.2.

**Comment by r10s** [comment]
hi @gerryfrancis, thank you for your report

can you please try if disabling "settings / notification / reliable background service" makes a difference for you? that should be the behavior or versions older that 1.6 then.

we are thinking about the defaults current, in fact, you can have either reliable notification _or_ the system claiming huge battery usage.

**Comment by gerryfrancis** [comment]
Hi @r10s, thanks for your fast response.

I have disabled reliable background service, my wife will tell if this works out right, we shall know the result by tomorrow. But what I do not quite understand are the multiple messages (three times in just one second) about a "WatchFolder" that is not found. (It happens with disabled reliable background services, too.) To me it looks like there are endless attempts (try -> fail, try again -> fail, try again ...) running in the background that probably are the real cause of the battery drain.

**Comment by gerryfrancis** [comment]
It seems that Delta Chat cannot retrieve information about the Sent folder when using a chello.at account. Messages can be sent, but they are not stored. When "Watch Sent folder" is disabled, the battery drain seems to be over.

This might be indicating a problem in conjunction with chello.at.

**Comment by r10s** [comment]
> This might indicate a problem in conjunction with chello.at. 

yip, this seems to be unrelated to the initial issue wrt battery

**Comment by mst23** [comment]
I have a problem, that seems to be related:
Since 1.6.2, battery usage is much higher. I use a private mail server, and checked the mail.log. There are way to much entries like the following - about 5-7 every second!:

May  9 12:03:07 hostxxx dovecot: imap(userxxx)<123456789><xxx>: Connection closed (CLOSE finished 0.066 secs ago) in=31 out=857 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0

Disabling "Watch Sent folder" helps - the many connections (close) disappear.

One thing is strange: I created a folder "Sent" and enabled "Watch Sent folder", but this did not help - there are still many connections every second. Only disabling "Watch Sent folder" helps.

**Comment by gerryfrancis** [comment]
> yip, this seems to be unrelated to the initial issue wrt battery

@10s I would not say so, the battery drain is the result of it. Of course, the root cause of the issue is Delta Chat not being able to identify the sent folder over and over again. Therefore, sent messages cannot be stored in there.

@mst23 Interesting. Could you post a log, please, so I could compare yours to mine? Thanks in advance.

**Comment by mst23** [comment]
Attached my log from Delta-chat. The warnings are the same as in your log. Delta-chat is checking for the Sent folder multiple times every second. 

[deltachat-log-20200510-090851-mst.txt](https://github.com/deltachat/deltachat-android/files/4605320/deltachat-log-20200510-090851-mst.txt)

**Comment by gerryfrancis** [comment]
@mst23 Thanks a lot, yes, it is the same issue!

**Comment by gerryfrancis** [comment]
Related to https://github.com/deltachat/deltachat-core-rust/issues/1443 .

**Comment by gerryfrancis** [comment]
I have no idea if this is relevant, but regarding the IMAP Sent folder, there is a difference between chello.at (not working) and posteo.de (working):

- The Sent folder in chello.at is named "SentMail".
- The Sent folder in posteo.de is named "Sent".

**Comment by gerryfrancis** [comment]
Same behaviour in version 1.8.0.

**Comment by hpk42** [comment]
is "watch sent-folder" enabled?  If so, could you turn it off and see if it helps?

**Comment by gerryfrancis** [comment]
@hpk42 Please read https://github.com/deltachat/deltachat-android/issues/1348#issuecomment-626225985 and https://github.com/deltachat/deltachat-android/issues/1348#issuecomment-626245002 .

**Comment by gerryfrancis** [comment]
Did a new attempt to set up the mail account, and I guess the issue is this (second line):

```
05-11 22:39:38.941 17346 17375 I DeltaChat: ThreadId(5) src/imap/mod.rs:1056: Configuring IMAP-folders.
05-11 22:39:39.070 17346 17375 I DeltaChat: ThreadId(5) src/imap/mod.rs:1073: sentbox folder is None
05-11 22:39:39.070 17346 17375 I DeltaChat: ThreadId(5) src/imap/mod.rs:1083: Using "/" as folder-delimiter.
05-11 22:39:39.086 17346 17375 I DeltaChat: ThreadId(5) src/imap/mod.rs:1153: FINISHED configuring IMAP-folders.
```

**Comment by gerryfrancis** [comment]
The battery drain does not occur anymore with version 1.8.1, thanks for the fix. @mst23 Please test the latest version and report back if it works or not.

Unfortunately https://github.com/deltachat/deltachat-android/issues/1348#issuecomment-626962423 is still valid, the sent folder for the chello.at account is not recognized. @r10s Shall I file a new issue for that?

**Comment by r10s** [comment]
> shall I file a new issue for that?

yip, that would be great, maybe directly in the core as this is unrelated to android.

i close this one as the battery drain is fixed. thanks for reporting back!
