### ISSUE TITLE
Messages send to only me displayed in group

### ISSUE THREAD

**Issue by vitalyster** [deltachat/deltachat-android#136]
I have sent message to group, group member hit "reply" in plain client instead of "reply all", and send message to me, but delta shows it still in origin group, while it definitely received only by me

**Comment by r10s** [comment]
Thank you, I will check this.

**Comment by Hocceruser** [comment]
I can confirm this behaviour.

IMHO DC should behave in one of the following ways when an answer to a group message is sent only to the current device:
1: redirect it to all group members (Problem: maybe the sender did not want other people to read it)
2: show it in private chat (Problem: Maybe the message was an answer to something in the group chat)
3: keep current behaviour but make clear that the message has not been sent to all group members, for example by all little sign (Problem: Users might get confused)
4: ask the user what to do (Problem: Users might get confused)

**Comment by bokf** [comment]
I had the opposite:
- I have sent a message in a group chat
- The answer of a group member was sent by external email client to all group members (reply to all)
- In Deltachat I recieved the message in the personal chat of the sender and not in group chat

**Comment by luisfsr** [comment]
I also noticed this behavior.

**Comment by r10s** [comment]
this should be fixed with https://github.com/deltachat/deltachat-core/pull/118 , the change will be released with 0.16.0 then
