### ISSUE TITLE
Latest release pointing to a different one

### ISSUE THREAD

**Issue by EchedeyLR** [deltachat/deltachat-android#1363]
Check https://github.com/deltachat/deltachat-android/releases/latest

**Comment by r10s** [comment]
from where is the link accessible?

however, we do not use the github-releases-page any longer, we're just adding tags, releases are at https://get.delta.chat - maybe we should delete all old released from github to avoid confusion.

**Comment by EchedeyLR** [comment]
Yes, @adbenitez told me about it but its confusing when you enter from mobile and see that the last release in green is pointing to that version. 

If you are going to point to the last release here should be at least in the last even with source-only. If not, I consider your idea a better solution.

**Comment by r10s** [comment]
@EchedeyLR thanks a lot for coming back to that and for detailed report. i would have completely overseen that!

i see, indeed, it is very confusing when the mobile page says the latest release is 0.3 or so when opening the page from 1.8 :)

i deleted all old releases therefore, the tags, however, are still there. if someone is interested in history, we have the changelog :)

the github-mobile-page says now: **v1.8.1 published about 22 hours ago** - :)

<img src=https://user-images.githubusercontent.com/9800740/81990087-beb6a100-963e-11ea-9c1e-e0b17577823b.png width=300>

btw, we had a similar issue for the github-desktop view - and i thought we fixed that, see https://support.delta.chat/t/delta-chat-for-android-1-1-2-labelled-latest-release-on-github/973 - but github-mobile seems to be different :)

**Comment by EchedeyLR** [comment]
Thank you for solving it. It's a bit hard having to take in account the changes for the webpage version + the partial responsive design for desktop (I think they have responsive design for desktop and a specific webpage for mobile and both are similar in some sense).
