### ISSUE TITLE
backup contains chats+messages, not system-configuration

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1364]
- Android version: **10**
- Device: **Huawei Mate 20**
- Delta Chat version: **1.8.1**
- Expected behavior: **I expect that when I backup I will preserve all the settings that I have saved.**
- Actual behavior:
**Importing the Backup, I set the following menus with the default values and not as I set them before the Backup:**

_**Chats and media section:**_

**1. Enter key sends**

_**Notifications Section:**_

**1. Reliable background connection**
**2. Sound**
**3. LED color**
**4. LED blink pattern**

_**Apperance section:**_

**1. Theme**
**2. Background**
**3. Message font size**
**4. Use system emoji**
**5. Language**

_**App access section:**_

**1. Screen security**
**2. Incognito keyboard**
**3. Screen lock**
**4. Inactivity timeout lock**

_**Advanced Section:**_

**1. On-demand location streaming**

- Steps to reproduce the problem: 

**1. Configure Delta Chat**
**2. Make a backup**
**3. Uninstall Delta Chat**
**4. Reinstall Delta Chat and import the backup.**

- Screenshots:
- Logs:

**Comment by r10s** [comment]
yip, all this is expected and by design. the backup contains data+chats, not system configurations. at least for now.

we may change this at some point, but it is not even possible in all cases, eg. a several options are pretty system-specifific, eg., a notification-sound may not be available when migrating to a new android phone. or even ios. 
however, maybe it should also be better communicated.

**Comment by gerryfrancis** [comment]
And it is a matter of security, too.

**Comment by hpk42** [comment]
On Thu, May 14, 2020 at 22:25 -0700, gerryfrancis wrote:
> And it is a matter of security, too.

Not a security issue, really.  The android-system settings are only about
notification-settings, appearance and such. This is not about system-secrets ;)

**Comment by gerryfrancis** [comment]
@hpk42 I have had the login credentials for the respective mail account in mind... *cough-cough* ;)

**Comment by r10s** [comment]
yes, they are in the backup - but how would that change if we add the system configuration additionally?

also, the backup-export-warning message is pretty explicit on that:

![Screen Shot 2020-05-15 at 14 07 48](https://user-images.githubusercontent.com/9800740/82048796-8ef6b000-96b5-11ea-912b-824b36ce69d1.png)

the message also states _what_ it is exported, so i think, it is not that bad, not saying it cannot be improved.

but to the initial issue, exporting the whole system setup is easy - but importing is tricky, and we cannot guarantee that import works eg.  on screen-lock - the target system may have that disabled etc. same for some sounds.

nb: we move things to the database, where possible and when we come over it, eg. just mute https://github.com/deltachat/deltachat-android/pull/1356 and media-quality before https://github.com/deltachat/deltachat-core-rust/pull/1449 - so, in general, we have the situation in mind, but just putting all options to the database might be tricky in detail.

**Comment by AndreazLattmann** [comment]
Ok 😄

**Comment by r10s** [comment]
closing, no actionable item. please reopen, if i've overseen sth.
