### ISSUE TITLE
Verbunden mit ...

### ISSUE THREAD

**Issue by igittihub** [deltachat/deltachat-android#138]
Moin DeltaChat-Team,
bei meinem Fairphone 2 mit Android 6.0.1 erscheint permanent die Benachrichtigung "Verbunden mit E-Mail-Adresse" Warte auf Nachrichten ...
Kann man das irgendwo deaktivieren?
Kann man Deltachat generell irgendwo wieder "ausschalten"? Einmal installiert und eingerichtet scheint es immer aktiv zu sein.
Gruß

**Comment by Hocceruser** [comment]
No you can't, see this issue: #82 

Currently, the only way to get rid of this is to go to System Settings -> Apps -> Delta Chat -> FORCE STOP ("Beenden erzwingen" in German), but like this you won't get any push notifications any more, either.
