### ISSUE TITLE
Contact requests stalled.

### ISSUE THREAD

**Issue by skaunov** [deltachat/deltachat-android#1385]
- Android version: 10
- Device: OnePlus 6
- Delta Chat version: 1.8.1
- Expected behavior:
To see all my email in the view.
- Actual behavior:
Only one strange message. See the screenshot.
- Steps to reproduce the problem:
Unknown. I just wanted to add a new thread from inbox to chats.
- Screenshots: 
![Screenshot_20200526-214243__01](https://user-images.githubusercontent.com/65976143/82938712-e7be2680-9f9a-11ea-9b3b-00c92bf8bd60.jpg)

- Logs:

**Comment by r10s** [comment]
if you want to see all emails, in the contact requests, you have to enable "Show E-Mails: All" at "Settings / Chats". maybe that already helps.

**Comment by searoso** [comment]
It helped indeed, thanks! Though a bit counter intuitive.

What I really wanted is to be able to easily pick any mail conversation to main (chat?) Delta screen.

**Comment by skaunov** [comment]
It helped indeed, thanks! Though a bit counter intuitive.

What I really wanted is to be able to easily pick any mail conversation to main (chat?) Delta screen.

**Comment by r10s** [comment]
thanks for rechecking and coming back to the issue!

in theory, there is a message shown to exactly this setting, but this message disappears if there is one message, indeed that can be improved, but that is another issue.
