### ISSUE TITLE
feature request: dark theme

### ISSUE THREAD

**Issue by igittihub** [deltachat/deltachat-android#139]
Wird es in Zukunft ein dunkles Design geben?

**Comment by kollokollo** [comment]
ist delta chat irgenwie verwandt mit der app silence? Dann könnte man gleiche Designs verwenden...

**Comment by r10s** [comment]
No, Delta Chat is not related with the app "Silence" (what is it?)

A dark design is not planned at the moment.

**Comment by kollokollo** [comment]
silence has a very similar user interface (I suspected it was the same), but the message transfer is via SMS instead of mail. silence was formerly known as sms-secure. It has a dark theme.

**Comment by r10s** [comment]
Ah, okay. Thanks for clarification.

**Comment by kollokollo** [comment]
Here is the homepage: https://github.com/SilenceIM/Silence

reading the pages I see that it is forked from following Projects: 

TextSecure --> SMSSecure --> Silence
TextSecure --> Signal

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .

**Comment by r10s** [comment]
see also #275
