### ISSUE TITLE
Forwarding a draft leads to error

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#1396]
When one makes a photo but does not send it, one can still view it in media preview.
But if from there one selects to forward the message, selects a contact and confirms the forward then an error is shown and the forward does not succeed.

Either we disable the "forward" icon if `msg_id == 0` or we fix the forwarding.

Discovered during working on #1228 so a fix should test the large avatar as well.

**Comment by r10s** [comment]
i think, this is fixed by https://github.com/deltachat/deltachat-android/pull/1392/commits/774d6de738cd61a237ec5d039d1731f4f31a453b
