### ISSUE TITLE
Err [Name not found]

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1397]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10
- Delta Chat Version: 1.9.3
- Expected behavior: I expect there is no Err [Name not found] in archived chats.  
If I see the profile of this chat there is no email.
- Actual behavior: Among the archived chats there is Err [Name not found] without any email. I don't know what chat it is
- Steps to reproduce the problem: I don't know how to reproduce the problem, I just know that looking among the archived chats there was Err [Name not found]
- Screenshots:
![Screenshot_20200605_211427_chat delta beta](https://user-images.githubusercontent.com/63752768/83915948-90773d80-a774-11ea-955e-0a75b7d91e83.jpg)
- Logs: 
[deltachat-log-20200605-213628.txt](https://github.com/deltachat/deltachat-android/files/4738122/deltachat-log-20200605-213628.txt)

**Comment by r10s** [comment]
this view can happen when the chat-activity is opened with a chat-id that does not exist in the database or cannot be read from the database. might also be related to some corrupted database.

however, wondering, where this comes from, of course, normally, this should not happen. a guidance with steps how to reproduce that would be great :)

**Comment by AndreazLattmann** [comment]
Yes, I'm trying to understand how it happened.  If I can find out how the DB got corrupt, I will post the way to reproduce the bug. 🤔

**Comment by r10s** [comment]
please open a new issue in this case, closing this one as there is no actionable item.
