### ISSUE TITLE
avatar-enlarge crash

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1399]
tapping on an avatar crashes - however, only on from android versions.

from the log:

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

the issue is that the acticvity is started with getBaseActivity() which is just not needed and micht also shuffle the activity stack.

**Comment by r10s** [comment]
(reported by @webratte in testing group)

**Comment by AndreazLattmann** [comment]
I wanted to report it but webratte arrived first. I add that both on Android 10 and Android 5 crashes.

**Comment by r10s** [comment]
@AndreazLattmann thanks for reporting! would be great if you can try over with the next nightly :)

**Comment by AndreazLattmann** [comment]
Absolutely! Every morning I install the new nightly on two devices, so as to check DC on two versions of Android. 😊

**Comment by AndreazLattmann** [comment]
Works well! both on Huawei Mate 20 (Android 10) and on Samsung J3 (Android 5.1.1) 🎉🎊

**Comment by webratte** [comment]
Also on Galaxy S8 with Android 9 👍

**Comment by r10s** [comment]
thanks for retesting!
