### ISSUE TITLE
Do not truncate copy-pasted text

### ISSUE THREAD

**Issue by Friptick** [deltachat/deltachat-android#1404]
To reproduce:

1. Write a message of Shakespearian length and send it
2. Oops! Message bounced back undelivered. Must have got the address slightly wrong! Oh well, let's try again. Click the "copy" icon in the message, begin a new message, paste the text
3. **BOOM. The text has been truncated arbitrarily with a "[...]". There is literally no way to get back the second half of the message without resorting to screen-capture and OCR**

This is unexpected and seems unnecessary. If copying the text of one's own message is allowed, then that should include copying **all** of it.

Please fix. Thanks.

Version: 1.8.1

**Comment by adbenitez** [comment]
I face this issue quite often, it is really annoying indeed, forwarding the message is the only workaround, but in my case I don't want to re-send the message but to copy the text to send it somewhere else in other app or to save it to a note, etc. and it is impossible currently without using tricks like forwarding to another address you own and check it with a classic MUA.

**Comment by gerryfrancis** [comment]
A possible workaround would be to limit the amount of characters per message.

**Comment by adbenitez** [comment]
actually the messages I have seen truncated were not so long to be considered Shakespearian ;)

**Comment by adbenitez** [comment]
right now there aren't a way to reply to a message, so people copy the message, paste it and reply below, so it is useful to have the name on top, but once a way to reply is implemented I very much would like this name to be removed from the top, causes accidents frequently for me ;)
