### ISSUE TITLE
Good Russian translate without bugs in date, time for Android OS

### ISSUE THREAD

**Issue by westsibe** [deltachat/deltachat-android#141]
I have good Russian translate in resource.arsc file (withhout a bugs in date, time, etc). If need this file, please write to westsibe1{at}yandex.ru . I can not download it to Transifex, sorry.

**Comment by westsibe** [comment]
Or you may download the APK file from Dropbox directly: https://dl.dropbox.com/s/z3rwm7styhwkv8j/Delta_Chat_0.9.3_RU_EN_only.apk?dl=0 (10.5 MB, RU/EN only, signature is "testkey") and extract resources.arsc file..

**Comment by r10s** [comment]
If you cannot use Transifex for any reasons, can you contact on the the russian project maintainers directly, see https://www.transifex.com/delta-chat/teams/76181/ru/ ?

Alternatively, you can post the modified strings.xml here and I will forward the link.

**Comment by westsibe** [comment]
Hello,

I have no strings.xml file, resources.arsc only.

Regards,
Andrey

West Siberia, Russia.

**Comment by r10s** [comment]
Ahh, okay, so you have modified the resources, not the source (you've written it in the first post, I should read more carefully).

**Comment by westsibe** [comment]
Hello,
Yes.
If you can insert the Russian translation from the resources.arsc file, 
then it will be very good. (I have no PC.)

**Comment by guland2000** [comment]
westsibe youre nick **anm** in transifex ?!

**Comment by westsibe** [comment]
Hello,

No. I'm not registered in Transifex and this nickname I'm not know.
