### ISSUE TITLE
Expand notifications to show full content

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1415]
With 1.8.1 it was and with other messengers it is possible to expand the notifications and see the full message content (unless it is very long).

@r10s

**Comment by r10s** [comment]
i just had a look at what whatsapp so doing here (that uses notification styles that are quite similar meanwhile, also one-channel-per-chat), i think, all what they're doing is to provide a longer text.

we've cutting the text at 100 characters (again :), however, we can easily expand this to 5000 or so.

this still fits nicely to the inbox-style we're using, i'll do a pr.

**Comment by r10s** [comment]
pushed a commit to #1414, i think, this is useful in general, however, at least on my testphone, this has no effect. 

we're using InboxStyle, which seems to make some sense, https://developer.android.com/training/notify-user/expanded - maybe whatsapp is using plain text, not sure.

so, not sure what we can do about that.

**Comment by r10s** [comment]
as @cyBerta pointed out at https://github.com/deltachat/deltachat-android/pull/1414#pullrequestreview-430785019, in general, `BigTexStyle` might do the trick.

however, this is seems to be mutual exclusive to the [`InboxStyle`](https://itnext.io/android-inboxstyle-notification-as-deep-as-possible-4d74c0c725f1) we're using (and which seems to be the "correct" thing for us).

but maybe we can use the InboxStyle only when there is more than one message notified - and for one message use the BigTexStyle. note sure, how smooth this looks, however.

**Comment by r10s** [comment]
closing this for now, it would maybe be nice to have (as so many things :), but if i shall choose between big-text for inbox, i think, inbox is the nicer thing.
