### ISSUE TITLE
provide default drawables

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1421]
In order to show a correct layout on low density devices we need to provide the drawables in the default drawable folder if we're not specifying images specially for ldpi and mdpi. 

The vast majority of devices support hdpi or higher densities which is why this is not a huge issue.

**Comment by r10s** [comment]
i think, this is not needed. from https://developer.android.com/guide/topics/resources/providing-resources.html#Compatibility

> If your app's minSdkVersion is 4 or greater, you don't need default drawable resources when you provide alternative drawable resources with the screen density qualifier. Even without default drawable resources, Android can find the best match among the alternative screen densities and scale the bitmaps as necessary. However, for the best experience on all types of devices, you should provide alternative drawables for all three types of density.

so, the "raw" drawable folder should only be used for images where one does not care about dpi (as things are eg. scaled by the app on runtime).

also, just moving things to the drawable folder may result in different sizes of the images displayed - as the dpi information is lost.
