### ISSUE TITLE
v1.10 not receive on occasions

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1427]
- Operating System (Android):
- Delta Chat Version: 1.10
- Expected behavior:
whenever there is a connection, that you receive the messages.
- Actual behavior:
sometimes it does not receive messages, having a good connection, I can send without problems. This started with the new core. resetting the application solved the problem.
- Steps to reproduce the problem:
- Screenshots:
- Logs:
[deltachat-log-20200618-084258.txt](https://github.com/deltachat/deltachat-android/files/4798746/deltachat-log-20200618-084258.txt)

**Comment by r10s** [comment]
this is similar to https://github.com/deltachat/deltachat-android/issues/1343, or?

also here: the log shows receiving acticity in general, it would be great if we can reproduce that on a fresh installation, to get closer to the real issue.

**Comment by agutierrez25249** [comment]
Yes, I'll try

**Comment by agutierrez25249** [comment]
on the other hand, it is happening to me quite often, I don't think it has anything to do with #1343 
The connection I use is with the internet, and delta never gave me problems like that.

**Comment by gerryfrancis** [comment]
Interesting:

```
06-18 08:42:40.611 24448 24480 I DeltaChat: src/job.rs:959: Inbox begin immediate try 0 of job #33, action MarkseenMsgOnImap
06-18 08:42:40.611 24448 24480 I DeltaChat: src/imap/mod.rs:1033: Marking message INBOX/28112 as seen...
06-18 08:42:40.611 24448 24480 I DeltaChat: src/job.rs:983: Inbox finished immediate try 0 of job #33, action MarkseenMsgOnImap
06-18 08:42:40.611 24448 24480 I DeltaChat: src/job.rs:940: Inbox removes job #33, action MarkseenMsgOnImap as it succeeded
```

```
06-18 08:42:41.413 24448 24480 I DeltaChat: src/dc_receive_imf.rs:46: Receiving message INBOX/28112...
06-18 08:42:41.424 24448 24480 W DeltaChat: src/dc_receive_imf.rs:344: Message already in DB
06-18 08:42:41.424 24448 24480 I DeltaChat: src/dc_receive_imf.rs:246: received message 28112 has Message-Id: Mr.AC1YuGDZwl8.vxKcl_ruJPn@nauta.cu
```

Question: Why does that message already exist in the database?

**Comment by agutierrez25249** [comment]
a new installation seems to have no problems, I just cleaned my server to test the previous installation. I will report later.

**Comment by agutierrez25249** [comment]
after deleting all messages from the server, the problem disappeared.

**Comment by agutierrez25249** [comment]
I forgot to mention, Every time I reset the data or the application, I noticed an excellent data traffic, caused by delta.

**Comment by gerryfrancis** [comment]
@agutierrez25249 Thanks for letting us know. Could you provide another log file so we compare it to the prior one?

**Comment by agutierrez25249** [comment]
delta is working as before, if you see any problem here it is related to https://github.com/deltachat/deltachat-android/issues/1343
[deltachat-log-20200619-151259.txt](https://github.com/deltachat/deltachat-android/files/4806401/deltachat-log-20200619-151259.txt)

**Comment by r10s** [comment]
> delta is working as before

not sure if this is good or bad :)

however, i am not totally sure what the current state of this issue is, however, we fixes  lots of things since then; please open a fresh issue if the problem persists with new logs.

**Comment by gerryfrancis** [comment]
@r10s We already have another related issue, it is still open: https://github.com/deltachat/deltachat-core-rust/issues/1821 .

**Comment by r10s** [comment]
great, thanks for the link, @gerryfrancis
