### ISSUE TITLE
Multiple Android Clients - Message marked not read.

### ISSUE THREAD

**Issue by gitkald** [deltachat/deltachat-android#143]
I don't knwo if it is a feature or a bug.

If you're using DC on multiple Android clients, and read a message on 1st client, than it wasn't marked read on the other clients.

**Comment by gitkald** [comment]
I think, there's a general problem in multi device environment. If you delete a message on 1st device, it will be deleted and deleted from server. But on 2nd device, it still exists.

There's no correct syncronisation between DC and Imap Server.

**Comment by r10s** [comment]
Yes, synchronisation is very elementary up to now and basically only affects receiving messages and not sending MDNs twice.

**Comment by r10s** [comment]
we've created an issue for collecting all the multi-device problems, see https://github.com/deltachat/deltachat-core/issues/52
