### ISSUE TITLE
Misleading notifications behavior.

### ISSUE THREAD

**Issue by searoso** [deltachat/deltachat-android#1431]
- Operating System (Android): 10
- Delta Chat Version: 1.8.1
- Expected behavior: click notification and open main DC window; notification without detalization.
- Actual behavior: it opens a chat instead list of chats. It's expected only when *unfolded* notification clicked.
- Steps to reproduce the problem: receive notifications from different chats and click it to see the list and preserve unread count.
- Screenshots:
- Logs:

**Comment by r10s** [comment]
the notifications are reworked in 1.10 and follow common standard now, i think, things are fine there.

you can already test that at:

- 🍉 https://testrun.org/deltachat-fat-debug-1.10.0.apk - can be used in addition to gplay
- 🍊 https://download.delta.chat/android/deltachat-gplay-release-1.10.0.apk  - will replace gplay and normally keeps data <- this version may go to the stores then
if in doubt, make a backup beforehand! or wait a few days, then 1.10 should be in the stores.

**Comment by searoso** [comment]
It's good to hear, thanks! Btw, I use F-droid for updates, of course.

**Comment by r10s** [comment]
> Btw, I use F-droid for updates, of course.

that's great!

**Comment by r10s** [comment]
closing this for now, no actionable item left.
