### ISSUE TITLE
Navigation with too many lag through the emoji panel

### ISSUE THREAD

**Issue by gilbertolazaro92** [deltachat/deltachat-android#1445]
- Operating System Android 6.0.1
- Delta Chat Version: 1.10.3
- Expected behavior: Smooth navigation through the panel of emojis
- Actual behavior: Navigation with too many lag

- Steps to reproduce the problem:  When I enter the section of diversified emojis the app gets very slow, and the general performance of my phone too
- Screenshots:
- Logs:
[deltachat-log-20200624-093820.txt](https://github.com/deltachat/deltachat-android/files/4825696/deltachat-log-20200624-093820.txt)

**Comment by r10s** [comment]
maybe, this is related to the 256MB memory, can confirm that things are not-so-good with few ram (256MB ram seems to be low-end nowadays).

and yes, compared to the old one, the new emoji panel seems to consume more ram, maybe we can tweak that, however, also not sure if there are significant changes compared to the signal upstream, cc @cyBerta

**Comment by gilbertolazaro92** [comment]
256mb is that amount of memory that android assign to delta?

**Comment by r10s** [comment]
i had a look at the source code to get the exact meaning of:

> memory=53M (0.58% free, 256M max)

- 53 mb: "total amount of memory in the Java virtual machine"
- 0.58% of these 53 mb are currently free, garbage collection is done to get more free memory
- 256 mb: "the maximum amount of memory that the virtual machine will use" - however, in practise, this amount seems to be shared with other apps, so this is not really reachable

**Comment by gilbertolazaro92** [comment]
Have 1.5 gb with at least 400 or 350 mb free when I use that versions, also both device storage and sd card have 1.4 and 2 gb free but when navigate through that specific section of the emoji panel(diversified emojis) the general performance of the phone decrease considerably

**Comment by r10s** [comment]
had a closer look on the issue with @cyBerta today, we did not  found a "simple" solution, it's just _many_  views, that need to be handled. they are created on the fly and recreated as needed to save memory, all this seems fine at a first glance, however, this may led to some lag when there is too few memory available (for whatever reason).

so, concrete ideas/pr welcome :)

maybe related https://github.com/signalapp/Signal-Android/issues/8453

**Comment by csb0730** [comment]
Cannot see any constraint at my device (S3 mini, Android 4.1.2).
I use DC 1.2.1 with some tweaks. But things around emoji panel is not changed related to original 1.2.1.

**Comment by r10s** [comment]
> I use DC 1.2.1 with some tweaks. But things around emoji panel is not changed related to original 1.2.1.

this is not true. the emoji-panel was completely revamped in 1.10.3 , see https://github.com/deltachat/deltachat-android/pull/1410 and also [subsequent fixes targeting android4](https://github.com/deltachat/deltachat-android/pulls?q=is%3Apr+is%3Aclosed+emoji+).

to check, if you are actually using the new emoji-selector, long-tap etc. on the pointing hand ☝️:

<img width=400 src=https://user-images.githubusercontent.com/9800740/92108330-7dadec80-ede7-11ea-8f31-844fa24f5add.jpg>

**Comment by csb0730** [comment]
I think I have the old code. Long-tap to any icon doesn't show any action as described here.

**Comment by r10s** [comment]
the old code does not have this issue. however, tbh, i am also failing to reproduce that on my slower devices currently.

**Comment by adbenitez** [comment]
@gilbertolazaro92 told me in Delta Chat that this issue vanished for him since the change of webp to png in emoji format

**Comment by r10s** [comment]
great! thanks for taking care, @adbenitez
