### ISSUE TITLE
use an explicit foreground-service for long-ongoing processes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1447]
there are some few actions in Delta Chat that take some time; there is some risk, that this action is interrupted by the system and Delta Chat is killed before the process is finished. 

to avoid that, a so called "foreground service" is needed, these services always come with a notification that is shown as long the process takes place (in fact, our "reliable background notification" thing is such a "foreground service", see [`KeepAliveService`](https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/connect/KeepAliveService.java)).

actions:

- create a generic foreground-service that can be easily used with a simple call and closed when work is done by another call
- only one foreground-service is needed at the same time
- the existing `KeepAliveService` should not be touched, if it is active, there might be _two_ permanent notifications, which is fine
- i think we can use signal's [`GenericForegroundService`](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/service/GenericForegroundService.java) - maybe some tweaking here and there :)
- the needed notifiation-id needs to be added to NotificationCenter as eg. ID_GENERIC_FOREGROUND_SERVICE=3
- call `GenericForegroundService.startForegroundTask()` before the long-ongoing process and `GenericForegroundService.stopForegroundTask()` or so afterwards - the  long-ongoing process as such should not be modified, the changes there should be small.

long-ongoing processes are currently import and export. maybe later we can also add recoding videos, however, this should be done in another step.

**Comment by cyBerta** [comment]
What GenericForegroundService really does is it prevents from the app being killed and handles the foreground notification nicely. It doesn't processes any tasks within the service. As long as the keep alive service runs, we don't really need this service in order to keep the app running. However we can use it also in these situations to show ongoing jobs in the notification bar.
