### ISSUE TITLE
problems with device messages

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1449]
- Operating System (Linux/Mac/Windows/iOS/Android):Andriod
- Delta Chat Version: 1.10.3
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
after installing v.1.10.3 and loading a backup, every time i open delta, it appears many times, and permanently, the little sign that you see in the image.
does not interfere with operation, but is visually annoying.
- Screenshots:
![deltachat-2020-06-24-220035](https://user-images.githubusercontent.com/52469394/85645793-bce1f380-b668-11ea-83a5-0f30f6c34ace.jpg)

- Logs:
[deltachat-log-20200624-215323.txt](https://github.com/deltachat/deltachat-android/files/4828785/deltachat-log-20200624-215323.txt)

**Comment by agutierrez25249** [comment]
apparently the problem is with the backup, because a new installation does not show this problem

**Comment by gerryfrancis** [comment]
@agutierrez25249 Do you mean the small avatar letters? They seem to appear for contacts with SMTP address only.

**Comment by agutierrez25249** [comment]
I mean this

![deltachat-2020-06-27-111921](https://user-images.githubusercontent.com/52469394/85925700-309e1f00-b868-11ea-9ed8-7a8e974a92bd.jpg)

**Comment by gerryfrancis** [comment]
> the little sign that you see in the image

@agutierrez25249 Lol, I did not expect this toast to be a little sign. ;) What happens when you reenter your login credentials, is the message still present afterwards?

**Comment by RubenDavidPerezJimenez** [comment]
@gerryfrancis @agutierrez25249 Hey I have made some changes in a self backup with a SQLite editor I have deleted all rows from the job table and it have stopped to spam me the toast it appears again for time to time but 1 time, I think it have something in common with it

**Comment by RubenDavidPerezJimenez** [comment]
@gerryfrancis yes it still says the same, if you change the auth it change the message but it is still the same annoying toast

**Comment by RubenDavidPerezJimenez** [comment]
It is only not logic offline, else it are totally functional and doesn't have the annoying repeatedly toast

**Comment by RubenDavidPerezJimenez** [comment]
this issue was resolved in the 1.10.5

**Comment by hpk42** [comment]
thanks for reporting back!

**Comment by RubenDavidPerezJimenez** [comment]
sorry I see it again but you need the automatic delete, a bad connection 256 kbps and 60 or more emails at same time, and it not stop again until you have connection again
