### ISSUE TITLE
App crashed on startup on LG G6 

### ISSUE THREAD

**Issue by JobbeDeluxe** [deltachat/deltachat-android#145]
Starting the app will take long and than you get the massage that the app force closed by Android. After that the start work. But after a while the massage won't appear, so you need to force close again and restart.

**Comment by kollokollo** [comment]
Yes, I do observe the same problem. It looks like there is a communication error or something not goint to timeout when talking to the IMAP Server. My provider is web.de. Sometimes it works fluently, sometimes it hangs very often. In rare cases I have got a message claiming Error #6 or so.

**Comment by kollokollo** [comment]
I find following strange issues with Delta Chat and web.de:

At home (via WLAN) everything works. But When I use a public WLAN or when I use G3 Data connection I get following errors: 
`
07-31 16:44:14.338: I/DeltaChat(1231): T2: Connecting to SMTP-server "smtp.web.de:587"...
07-31 16:44:14.348: E/DeltaChat(1231): Fehler: SMTP-STARTTLS connection to smtp.web.de:587 failed (Connection refused)
`
With the App K9 everything works fine, also in the other networks.

Can it be, that the TLS/SSL certificate needs to be changed whenever the IP-Address changes?

**Comment by JobbeDeluxe** [comment]
That's another error. On my mobile phone it just crashes on start after running in a background a while.

**Comment by kollokollo** [comment]
OK you are right, that may be different. My phone does not crash, but it hangs (or at least waits too long), so that the force-close message appears. Especially after rebooting the device, when deltachat is immediately selected. Maybe the phone is too busy at that time. But the bigger problem for me is that deltachat cannot connect to the server, while k9 can, assuming the same settings.

**Comment by JobbeDeluxe** [comment]
That is what happend to me after start. If i stop that app and restat all fine.
![screenshot_2017-08-02-13-06-01](https://user-images.githubusercontent.com/20384365/28935311-6e5d5dd2-7884-11e7-9a61-63580d5d2667.jpg)

**Comment by JobbeDeluxe** [comment]
Also the battery drain was about 15 up to 20 percent on one day. 
But it looks like the energy saver has closed the program in the background and it was keep trying to restart. I have disabled the safe energy for this app, and now it seams to be working as usal. 
But energy consume is now higher that on my old g3. About 7 up to 10 percent. With over 5 hours of keeping the device aktiv. 

It seams that there is a little more behind the problem, what is different on each device.

**Comment by JobbeDeluxe** [comment]
since the last updates i haven't the issue. So it seams to be solved.
