### ISSUE TITLE
Really problematic toast

### ISSUE THREAD

**Issue by RubenDavidPerezJimenez** [deltachat/deltachat-android#1455]
When the app is offline it sends ton of toast with a error but it not stopping after you have connection or close forcibly the app in the 1.10.4 not like it are online and do a error

**Comment by agutierrez25249** [comment]
This is what I wanted to say in: https://github.com/deltachat/deltachat-android/issues/1449

**Comment by RubenDavidPerezJimenez** [comment]
Ok, sorry, I use nauta too and don't have see the issue
