### ISSUE TITLE
feature req: monospace font

### ISSUE THREAD

**Issue by rulnick** [deltachat/deltachat-android#1456]
Feature request: monospace font family option for message text (presently, sans-serif appears to be hard-coded in res/values/text_styles.xml). Without it, plain text messages using character alignment and/or tabs are rendered poorly.

**Comment by adbenitez** [comment]
I would also love some way to have monospace font, I have a bot that allows to play chess in delta chat, the board use unicode chess icons but looks pretty bad/unaligned
you may want to move this feature request to the forum where most delta chat users and devs discuss about new things, issues are used mostly for bug reports or to track a feature request that will be added soon.

Best regards,
adb

**Comment by r10s** [comment]
closing this here for reasons @adbenitez explained above.
