### ISSUE TITLE
Fix f-droid build issue

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1459]
F-Droid is not able to build delta chat at the moment. 

see https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_587

**Comment by r10s** [comment]
fdroid seems to pick up 1.10.5 (588), metadata are updated at https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.b44t.messenger.yml

however fails to build https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_588

**Comment by r10s** [comment]
so, 1.10 is now available in f-droid: https://f-droid.org/en/packages/com.b44t.messenger/ - thanks a lot for helping, everyone :)
