### ISSUE TITLE
Suggestion: Add emoticons to messages

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#146]
Like we can add Thump-up or -down here on github to the comments. Not high priority, but I think that would be nice.

**Comment by csb0730** [comment]
May You explain it a little bit more?

**Comment by Hocceruser** [comment]
This is a great idea but I'm afraid that it is not possible to implement this:

Technically, DC is an email client. Since it is not possible to add emoticons to other people's emails, it would be very difficult to add emoticons to Delta Chat messages. 

It is probably easier if you just write an answer which contains your emoticon. 😉

**Comment by kollokollo** [comment]
Well, yes, for now, that works. But I am sure, that with time one will find a tecnical soutionfor this.

**Comment by luisfsr** [comment]
Hi @kollokollo ! I also miss emoticons on DC. Having in mind that the recipient of my DC messages don't use an android client, I know that the emojis could just show up there as an unrecognized character.
Ideas:
a) install symbola font on the computer side of your recipients: https://github.com/ChALkeR/Symbola-Emoji 
b) use asscii emoticons instead: http://upli.st/l/list-of-all-ascii-emoticons 
c) in the future, to maintain e-mail compatibility, if DC developers find this a good idea, they could: I) implement asscii emoticons as default on DC; or II) make DC convert android emoji fonts into asscii emoticons and vice-versa; or, instead, III) exceptionally send html messages when the DC user makes use of emojis, converting the emojis into image files.
Just a humble opinion ( ^◡^)

**Comment by Hocceruser** [comment]
@luisfsr: I agree with you about the problem of the non-android-client emoticons but I think that kollokollo meant something different (he wanted to add emoticons to other people's messages, just like I just added a thumbs-up to your message).

Maybe you should copy-and-paste your idea to a newly opened issue?

**Comment by luisfsr** [comment]
Oh! You're right @Hocceruser.

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
