### ISSUE TITLE
Manual upgrade to 1.10.x does not work

### ISSUE THREAD

**Issue by kromonos** [deltachat/deltachat-android#1462]
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: 1.8.1 Play Store Version
- Expected behavior: Upgrade to 1.10.x works without problems
- Actual behavior: After upgrading, Delta.Chat crashes directly after start
- Steps to reproduce the problem:
  - Installed and setuped Version 1.8.1 Play Store Version
  - Download 1.10.x gplay from get.delta.chat
  - Update manually from 1.8.1 to 1.10.x
- Phone: Galaxy A3 2017 (SM-A320FL)
- Operating Systen: LineageOS 16.0 (Android 9)

I didn't try a clean install yet and 1.10.x isn't available for me from the gplay yet.

**Comment by hpk42** [comment]
can you add your phone model and android sytem info?

**Comment by kromonos** [comment]
> can you add your phone model and android sytem info?

oops, sorry. Added :)

**Comment by gerryfrancis** [comment]
I have received a log file regarding this issue from forum member "Aviva" in a personal message. I anonymized the log and forwarded it to one of the developers, but I have not received a reply from him, yet. @hpk42 Shall I post the log here?

**Comment by cyBerta** [comment]
@gerryfrancis uf the logs are anonymized, they're fine to be added here.

**Comment by cyBerta** [comment]
@kromonos did you retry with the current play version?

**Comment by kromonos** [comment]
> @kromonos did you retry with the current play version?
Yes, but same Problem. I had to uninstall 1.8 manually and install then 1.10. Then DC worked as expected.

**Comment by gerryfrancis** [comment]
@kromonos So you created a new database, too, right?

**Comment by kromonos** [comment]
Fresh install, yes @gerryfrancis

**Comment by gerryfrancis** [comment]
@kromonos Thanks for confirming, so there might be an update (migration) issue from version 1.8.1 to 1.10.x.

**Comment by gerryfrancis** [comment]
@kromonos Version 1.12.2 has been released, it most likely fixes your issue (https://github.com/deltachat/deltachat-core-rust/pull/1803). I guess it will take some time until it arrives in Google Play Store.

**Comment by r10s** [comment]
yip, 1.12.2 is rolling out currently, it is available for about 50% of users currently, will take a day or so to reach 100% (unfortunately, there seems to be no option in gplay to force an update - i though this is possible, but that seems not to be the case)

**Comment by webratte** [comment]
Why don't you use the Beta channel of Gplay?

You could put a new version first into the beta channel. Users of the Beta channel know this version can be unstable.

After a few days without bad feedback you can move this version to the regular channel and make it available for all users.

**Comment by r10s** [comment]
> Why don't you use the Beta channel of Gplay?

we are using .apk files as betas, they are compatible to the gplay releases and available at https://get.delta.chat 

this way people not using gplay can also try out new versions - and esp. for beta-testers there are _some_ not using glay.  
of course, we could maintain two beta-channels, however, this is some additional effort and comes at costs.

**Comment by r10s** [comment]
back to this issue - is this one still valid? we fixed some things on migration recently, also 1.10.x is outdated.
so i am closing this one, please open a new one as needed.
