### ISSUE TITLE
mailto doesn't work

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1472]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.10.4 (2020-07-01 Nightly)
- Expected behavior: When I click on a "mailto" link, Delta Chat opens with the parameters body ect.
- Actual behavior: It opens Delta Chat and the email to chat with, but the text in the body is not inserted.
- Steps to reproduce the problem: open a link with example: mailto:test@testrun.org?body=Hi

in stable version 1.10.4 it works.  The bug appears to have been introduced with this commit: 
a2dc69e27ea185566e42521c6b0290c0fdae5150
 Merge: b3389ff1 23decbe2
 Author: cyBerta
 Dates: Tue Jun 30 23:03:37 2020 +0200

Merge pull request # 1341 from deltachat / fix-sharing-multiple Relay to multiple contacts, rework message relaying.

This information was given to me by adb and I thank him for finding this bug.

**Comment by adbenitez** [comment]
seems the issue was introduced in: https://github.com/deltachat/deltachat-android/pull/1341

**Comment by cyBerta** [comment]
Thanks for the fast bug report!

**Comment by AndreazLattmann** [comment]
In the new version of Delta Chat 1.12.2 there are some mailto links that don't work. in a link I appeared the toast with written mail not valid. Other links don't work at all, but with K9 they do. I will try to understand why.

**Comment by cyBerta** [comment]
please share the links that don't work. It will help us to understand the issue

**Comment by AndreazLattmann** [comment]
For example this:
https://www.lakecomoadventurepark.com/contatti/

**Comment by cyBerta** [comment]
could be that the emtpy space between `mailto:` and the contact causes the trouble. I think it's worth creating a new ticket.
