### ISSUE TITLE
Delta chat failed to send message

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#1473]
- Operating System (Android):
- Delta Chat Version:1.81
- Expected behavior: message will be sent eventually if not asap
- Actual behavior: message never sent
- Steps to reproduce the problem:
- Screenshots:
- Logs:
While on a drive with service on and off (never more then 20 minutes without service) i sent an important message. It was never sent.

I was driving and unable to check, i never received a notification of the message failed to send, and it did not send the message when service came back.  Even 8 hours later.. when i had service for over 4 hours.

I would expect it to keep trying or at least have a setting to keep trying forever.

**Comment by gerryfrancis** [comment]
@nutpantz Thanks for your report. Could you try to reproduce the issue with current version 1.10.4 and report back, please? Thanks in advance.

**Comment by nutpantz** [comment]
When it is available on fdroid i can give it a try.

**Comment by monperrus** [comment]
I confirm the problem.

Is there a way to manually trigger resending?

**Comment by gerryfrancis** [comment]
> Is there a way to manually trigger resending?

@monperrus AFAIK, no. If possible, please post a log, so we can see what is going on in the background. Thanks!

**Comment by angelo-fuchs** [comment]
@monperrus There is no button for it but of course you can re-initiate DC by force-stopping it through you device or restarting the device. This should also retrigger the sending.
@nutpantz If you retry please do include a logfile as we will need to figure out why it didn't send after having network again.

**Comment by monperrus** [comment]
> or restarting the device. This should also retrigger the sending.

No. According to my tests, restarting the device does trigger sending again failed messages.

**Comment by gerryfrancis** [comment]
@monperrus When you experience this issue, can you connect to other hosts within your browser successfully?

**Comment by monperrus** [comment]
> When you experience this issue, can you connect to other hosts within your browser successfully?

I don't know, but I suspect that indeed there were some connectivity problems. The bug is that DeltaChat does not try again later.

**Comment by angelo-fuchs** [comment]
@monperrus Agreed, DC should reconnect once the connection is back up and that is a bug. Restart is just a workaround in situations where you know you have Network and want something sent urgently.

**Comment by gerryfrancis** [comment]
@monperrus We need some log that probably contains more information on this, otherwise it is just a guess on what really happened. Also, please try to reproduce the issue with the current version 1.10.5, maybe this bug is already solved. Thanks!

**Comment by monperrus** [comment]
> please try to reproduce the issue with the current version 1.10.5

ack, I currently have 1.8.1 from F-Droid. What's the recommended source for installing 1.10.5?

**Comment by gerryfrancis** [comment]
@monperrus For now, please download from here: https://download.delta.chat/android/deltachat-gplay-release-1.10.5.apk

**Comment by monperrus** [comment]
Thanks, just installed 1.10.5, will let you know if the bug hits again.

**Comment by monperrus** [comment]
FYI, with 1.10.5, hit another, related issue (sent indicator not updated, see https://github.com/deltachat/deltachat-android/issues/1218)

**Comment by csb0730** [comment]
I think the whole resend approach is not that fortunate as it could be. As I was faced with similar experiences like described here too, I changed it meanwhile again for me.

I'm using "network status" again and trigger that status not only from devices' status but also from several success or fail conditions while trying to send/fetch/connect.
Additionally I increase resend counter only if "network is there" and changed retry timings to fix but growing steps.
Further I block all jobs and unnecessary fetches in offline situations.

Up to now it looks like that this approach provides a much better reliability under bad network conditions.

**Comment by r10s** [comment]
the issue is stale. reconfirmed, and meanwhile closed, however, was #1218, also lots of things changed in between. 

if needed, please open a new issue with recent informations and logs.

**Comment by monperrus** [comment]
ack, thanks.
