### ISSUE TITLE
The camera is not working.

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1474]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.10.4 (Nightly 03-07-2020)
- Expected behavior: When I click on the camera icon, it must give me the opportunity to take a photograph.
- Actual behavior: When I click on the camera icon a black screen appears.
- Steps to reproduce the problem: Click on the camera icon.
- Screenshots:

![Screenshot_20200705_203618_chat delta beta](https://user-images.githubusercontent.com/63752768/86539762-778eb300-beff-11ea-8ddb-79a5fa5f4d68.jpg)

![Screenshot_20200705_201911_chat delta beta](https://user-images.githubusercontent.com/63752768/86539765-7cebfd80-beff-11ea-9bd7-3aeded23a2bb.jpg)

- Logs:

[deltachat-log-20200705-203851.txt](https://github.com/deltachat/deltachat-android/files/4875377/deltachat-log-20200705-203851.txt)

**Comment by AndreazLattmann** [comment]
I restarted my cell phone and now the camera works.  The strange thing is that while in the nightly it didn't work, in the gplay version 1.10.4 yes.
At this point I think it's not a real DC bug. 🤔

**Comment by AndreazLattmann** [comment]
It never showed up to me again, possibly an Android malfunction.
I close the issue, if it comes up again I will open it again.

**Comment by r10s** [comment]
thanks for re-checking and coming back to the issue 👍
