### ISSUE TITLE
Replace doze-reminder device message with a menu option and ask for it on first start

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1477]
Users don't even open device chat sometimes, let alone click the message to enable battery optimizations. If there is no harm in asking for this permission, maybe ask for it immediately at the start? And if it is not granted, show an option to enable it somewhere in the settings menu.

**Comment by AndreazLattmann** [comment]
I have already noticed that some friends did not go to see in the messages of the device. I agree with @link2xt .

**Comment by Hocuri** [comment]
I'd personally leave the device message as is (maybe show a notification for it, the core has the possibility now, we just need to add the ffi), but thats not so important. 

And I agree that we could just ask on start.

**Comment by r10s** [comment]
> If there is no harm in asking for this permission, maybe ask for it immediately at the start? 

well, thinking it over, there is some risk to lose the ability to do the request at all, i commented at https://github.com/deltachat/deltachat-android/pull/1505#pullrequestreview-479019318

> And if it is not granted, show an option to enable it somewhere in the settings menu.

this is probably no problem, i did a pr for that at https://github.com/deltachat/deltachat-android/pull/1608

**Comment by r10s** [comment]
closed by #1608 and #1505
