### ISSUE TITLE
Inconsistent message display / loss - message to own address

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#148]
This issue describes inconsistent message display or even message loss due to the fact, that DC suppresses all messages where in "From:" header is the same email address as it has in it's own DC
configuration!

Furthermore this suppression is done independently from the fact(s) if
- there is a new message id in chat
- a message comes from a non DC mail client
- a different address is in "To:" header of message to sent

Resulting problems:
- New messages from external mail clients (other devices) to own address never will be displayed.
  These are always new mails and should to be seen in own chat (or in "Kontaktanfragen") !
- Messages to other address of same mail account never will be displayed.
- With the knowledge in mind that DC uses email as transport layer it should be possible to do the
   standard testing case for email to send a message to own address and see it as incoming again for
   testing. This is not possible now.

Proposal:
- do not suppress any messages and show them as incoming where appropriate or
- only suppress messages where there is really the same message id for THE SAME CHAT existing!

Maybe a configuration setting is possible?

In each case a consistent message display is necessary: there should be no situation where a
message neither from DC itself nor from an external mail client is not seen in DC.

DC = delta chat   :-)

**Comment by csb0730** [comment]
No one interested in?

**Comment by r10s** [comment]
Of course, very interested in :)

> [...] due to the fact, that DC suppresses all messages where in "From:" header is the same email address as it has in it's own DC configuration!

DC handles messages with the same `From:` header as the configured address as "outgoing" messages, see https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox.c#L393 . This way, multi-device is support rudimentary. So, in general, they appear, at least with a little delay, _if_ the chat with the sender exist on the device.

They _do not_ appear if a message is send on DeviceA and the chat does not exist on  DeviceB - I think this is what you're talking about.

As this issue belongs to the core, and to keep things together, I have just created a new "core"-issue where multi-device support lacks should go to: https://github.com/deltachat/deltachat-core/issues/new - unfortunately, all this multi-device stuff is complicated and will cost a lot of time/money. I do not think, I can add this soon (but maybe we get help ins some way)

I'll also marked this issue as "duplicate", knowing you was the first to report it :)

**Comment by csb0730** [comment]
New issue is https://github.com/deltachat/deltachat-core/issues/52 - correct?

But, to keep it simple:
- Just let the DC show every message which is new for the local client (not existent in local database)
  If "From:" header contains own configured address show it as outgoing, but show it.
- If chat for incoming message not exists (at the device X) I would vote for: show it in "contact requests". From there user can start chat if desired.
- And my special wish (again ;-) ): If "To:" header contains own configured address: show it a) in chat where it comes from or b) in "contact requests" when own configured address is used in "From:". From there chat can be started if desired. This will violate no convention. Event at mail server You see a new message at inbox in this case!

I think these three points will ease the multi device support.

Further discussions I suppose we continue at https://github.com/deltachat/deltachat-core/issues/52 ...
