### ISSUE TITLE
manual download media 

### ISSUE THREAD

**Issue by RubenDavidPerezJimenez** [deltachat/deltachat-android#1482]
normally the mail clients have a manual download for the attachments, the whatsapp have it Telegram have it but actually, I don know for what Delta chat don't have it

**Comment by r10s** [comment]
hi @RubenDavidPerezJimenez , thanks for your post and for your suggestion.

> I don know for what Delta chat don't have it

well, it is just not implemented :) there are lots of open ends, many things to do that all eat resources.

there is already a corresponding feature requests in the forum at https://support.delta.chat/t/addition-of-automatic-media-download-feature/327 . the forum is the better place for feature requests anyway, this issue tracker is mainly for bugs and things actually under development. you can log in to the forum with your github credentials.
