### ISSUE TITLE
error making backup

### ISSUE THREAD

**Issue by RubenDavidPerezJimenez** [deltachat/deltachat-android#1484]
I have tried to make a backup and have get a error and the file that are saying is ok

here is the error log

07-13 11:42:40.220 29163 29191 I DeltaChat: src/imex.rs:370: Import/export process started.
07-13 11:42:40.437 29163 29191 I DeltaChat: src/sql.rs:459: Start housekeeping...
07-13 11:42:40.437 29163 29191 I DeltaChat: src/sql.rs:507: 2287 files in use.
07-13 11:42:41.007 29163 29191 I DeltaChat: src/sql.rs:586: Housekeeping done.
07-13 11:42:41.007 29163 29191 I DeltaChat: src/imex.rs:524: Backup '/data/user/0/chat.delta/files/messenger-1.db' to '/storage/emulated/0/Download/delta-chat-2020-07-13-0.bak'.
07-13 11:42:49.825 29163 29191 I DeltaChat: src/sql.rs:1319: Opened "/data/user/0/chat.delta/files/messenger-1.db".
07-13 11:42:49.849 29163 29191 I DeltaChat: src/sql.rs:1319: Opened "/storage/emulated/0/Download/delta-chat-2020-07-13-0.bak".
07-13 11:42:50.561 29163 29191 I DeltaChat: src/imex.rs:584: EXPORT: total_files_cnt=2287
07-13 11:42:50.562 29163 29191 I DeltaChat: src/imex.rs:605: EXPORT: copying filename=Salsa rosa-2.doc
07-13 11:42:50.565 29163 29191 E DeltaChat: backup failed: Sqlite Error: SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 11 }, Some("database disk image is malformed"))
07-13 11:42:50.637 29163 29191 W DeltaChat: deltachat-ffi/src/lib.rs:3158: IMEX failed: IMEX FAILED to complete: Sqlite Error: SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 11 }, Some("database disk image is malformed"))
07-13 11:42:58.058 29163 29168 I art     : Do partial code cache collection, code=106KB, data=124KB
07-13 11:42:58.059 29163 29168 I art     : After code cache collection, code=106KB, data=124KB
07-13 11:42:58.059 29163 29168 I art     : Increasing code cache capacity to 512KB
07-13 11:43:00.840 29163 29163 W PassphraseRequiredActionBarActivity: onPause()

**Comment by r10s** [comment]
is that reproducible in some way?

however, in general, it seems that "just" writing has failed - maybe due to some bad sd-disk for whatever - this error is reported in the log and probably also shown (as you are saying you got an error). so, from that point of view, i see no actionable item what we can do about this issue.

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez If possible, could you try again with another SD card and report back, please? Thanks in advance.

**Comment by RubenDavidPerezJimenez** [comment]
sorry I didn't have get tested in another phone and yesterday I had it, and today I wasn't have I am not sure of what are but I think that file name have something in it, but I have send the file to another phone and not have the problem I don't mind what happened in it before

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez Sorry, I believe I do not understand what you are saying. Have you been able to reproduce the issue with another SD card? (I do not mean a SIM card, it has nothing to do with the issue.)

**Comment by RubenDavidPerezJimenez** [comment]
no, I mean the internal storage of the phone it doesn't not have sdcard only the phone storage

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez Thanks for clarifying. Does the internal storage of your phone have enough space left?

**Comment by RubenDavidPerezJimenez** [comment]
yes, it have yesterday, but I don't know what happened yesterday that have do that, and today don't do

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez OK, never mind. For now, I will close your issue. Should you experience the same issue again, please comment, and it will be reopened. Thanks!
