### ISSUE TITLE
peer state missing cannot encrypt on manual update

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#1487]
Tried to update from 1.81 fdroid version to apk download 1.10.5 from GitHub.

Trying to message a contact i get peerstate for 'contact address' missing cannot encrypt..

I tried restoring a back up which has worked in past version, (messages and contacts all came back) and i tried importing keys..
Tried to install github apk 1.81 and everything works fine but if i install the update to 1.10.5 github apk EVEN that fails with the same error after the update 
(Which might mean a lot of fdroid users can't update because of how long it's been since you had fdroid working)
Still get the error..

Btw i hate that github forces 2 factor verification every time i want to report am issue.. It's a pain in the ass.(i know you don't care but it makes me not want to report issues and just not make the effort to improve or support the software. I'm just going to unsubscription this topic and check back in s week or so i don't need github tracking cookies)

**Comment by Ampli-fier** [comment]
Thanks for reporting, I opened the issue already in DC-Core https://github.com/deltachat/deltachat-core-rust/issues/1596

**Comment by gerryfrancis** [comment]
Thanks @nutpantz and @Ampli-fier for your valuable input on this issue. I suggest to close here and continue in https://github.com/deltachat/deltachat-core-rust/issues/1596 . See you there!
