### ISSUE TITLE
clicking on apk attachment sometimes doesn't work

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#1492]
current gplay version 1.10.5 android 

on my phone, when i click an attached ".apk" the install screen opens, everything is fine. 
With a fairphone 3.0 and another (samsung?) android phone from friends this would not work. 
Isntead we had to "save", then find a file manager, and then click there on the file which did open the installer. 
So shouldn't it then be possible for Delta Chat to also open the file if the "dateien" file manager can do it?

**Comment by gerryfrancis** [comment]
It could depend on whether the Android device is rooted or not.

**Comment by hpk42** [comment]
but why would the file manager allow to click and open the install?

**Comment by gerryfrancis** [comment]
@hpk42 There is a third-party app called "File Manager", do you mean this one, or the common file app in Android?

**Comment by hpk42** [comment]
I think it was the Android file app in both cases.

**Comment by r10s** [comment]
i agree, Delta Chat should be able to launch the apk-installer if a random file-manager from f-droid or so is able to do so.

i just tried over on the devices i have here, and it works as expected - you can send an apk to a chat and launch the installer from there. there is not much special we do there - the apk is handled as an pdf - if there is some app that can handle that, we do it. so, unfortunately, i cannot reproduce this issue.

if a _random_ file manager, from f-droid or so is able to install the app while Delta Chat is not - that should be fixable. might be that some systems require a special intent to install things and that just passing an apk is not sufficient - and that this special intent is fired by the file mangager. but these are only guesses, that would need some research.

but if only the _Android file app_ that is shipped together with the operating-system is able to do so, that may not be fixable, system apps may have special rights etc.

**Comment by cyBerta** [comment]
I can reproduce the bug. I'll try to fix it.

**Comment by r10s** [comment]
should be in the next nightly :)
