### ISSUE TITLE
share more than one picture from galery not working (Huawei only?)

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1495]
- Operating System: Android 8 (Huawei Y7 and Huawei P10)
 
- Delta Chat Version: 1.8.1 gplay

- Expected behavior:
1. select more than one picture from galery
2. press share
3. select deltachat
4. select desired contact
5. deltachat should ask to send more than one picture, send them and show them it in chosen chat.

- Actual behavior:
Steps 1. - 4. are working as expected
Step 5. isn't working. DC shows the chat but sends nothing and doesn't show any picture

- Logs:
[deltachat-log-20200722-194525-y7.txt](https://github.com/deltachat/deltachat-android/files/4961803/deltachat-log-20200722-194525-y7.txt)

Time of test around 19:44 (log)

Remark: doing the same procedure but selecting *only one picture* from galery is working as expected !!

**Comment by csb0730** [comment]
At my S3 mini (Android 4.1.2) with DC 1.2.1 fork it works as expected when selecting several pictures.

**Comment by gerryfrancis** [comment]
@csb0730 Could you update to version 1.10.5 and try again, please? Thanks in advance.

**Comment by csb0730** [comment]
Is that version available on gplay? Unfortunately the error came up not on my device.

**Comment by Hocuri** [comment]
I can confirm this bug in 1.10.5, but it seems to have been fixed in the current master.

**Comment by AndreazLattmann** [comment]
I tried to select 5 images, share the images with delta chat (Version 1.10.5), select a user and send the photos. I have a huawei mate 20 and it works.

Android version: 10

https://download.delta.chat/android/deltachat-gplay-release-1.10.5.apk

**Comment by csb0730** [comment]
just did an update to delta 1.10.4 (current gplay)

still doesn't work, the same than described in issue (Android 8)

**Comment by cyBerta** [comment]
I think this ticket can be closed. The bugfix was confirmed for 1.10.5
