### ISSUE TITLE
"Re: " added to group reply provokos new contact requests and additional chat

### ISSUE THREAD

**Issue by Norbert80** [deltachat/deltachat-android#1496]
Hi,

- I (Delta Chat user) have created a group with three participants (all *not* Delta Chat users)

- After I have received the first reply (to all participants) Delta Chat generated a new contact request

- I confirmed this new contact request

- Now I have an additional group but with "Re: " added to the beginning of the subject/group name.

Is this issue known? Is there a way to avoid this behavior?

Bug found in Delta Chat Android 1.8.1.

**Comment by RubenDavidPerezJimenez** [comment]
maybe it are because the mail app are responding only to one contact, it will need to respond your email and add the another address I believe

**Comment by Norbert80** [comment]
Thanks but please read carefully:

"After I have received the first reply (to all participants)..."

**Comment by AndreazLattmann** [comment]
In mail clients there are usually two options: reply and reply to all.  
If it has been done answer everyone, then it's a bug.  
If you can, I recommend upgrading Delta Chat.  We got to version 1.10.5 which fixes many bugs.

**Comment by gerryfrancis** [comment]
@Norbert80 A lot of work was done in this PR https://github.com/deltachat/deltachat-core-rust/pull/1395 to make Delta Chat comply well with the "Re: " mark, the PR was merged to later versions than 1.8.1. If possible, please update to 1.10.5 - download here https://download.delta.chat/android/deltachat-gplay-release-1.10.5.apk - and report back your results. Thanks in advance!

**Comment by Norbert80** [comment]
@gerryfrancis Thanks for the info!

1.10.5 has been released in F-Droid today. I have upgraded a few hours ago. I don't know why releases from Delta Chat are lagging there so much.

I think we can close this issue. In case I experience this bug again we can re-open this issue.

**Comment by gerryfrancis** [comment]
@Norbert80 Thanks for reporting back! :+1:

**Comment by Norbert80** [comment]
I still experience this issue with Delta Chat 1.12.5.

=> Re-open.

**Comment by Hocuri** [comment]
Did I understand correctly?
- You created a group with A, B, C and D who are all not using DC.
- You sent the first message
- A replied to all
  - this resulted in a contact request? This should not happen.

Can you post the headers of your outgoing message and A's reply? (you should anonymize it first, i.e. remove email addresses and ip addresses)

**Comment by Norbert80** [comment]
That right. In fact each replay generates a new contact request not only the first one. I have multiple "groups" now containing only one response mail.

How can I reveal the headers with Delta Chat?

**Comment by Hocuri** [comment]
You can't you have to get them e.g. in your email account (as you normally check your emails) or Thunderbird.

**Comment by Norbert80** [comment]
@Hocuri Sorry, I do not use that mail.de account on conventional desktop clients. But I expect that this bug should be not too difficult to reproduce since there are no rare providers involved. I use mail.de (I am initiater of the group). Particpants use gmx.net and freenet.de accounts.

![grafik](https://user-images.githubusercontent.com/6921696/95960453-0adf5a80-0e04-11eb-8ce5-5e62dbff3984.png)

**Comment by Hocuri** [comment]
It should not make a difference which provider you use, but which provider does A (from the example above) use?

**Comment by gerryfrancis** [comment]
@Norbert80 Thanks for providing the screenshot, it seems that Delta Chat falsely interprets the subject name as a (new) contact name, and the subject is changed from classic MUAs by prepending terms like "Re: ", "Aw: ", and/or "Fw: ".

**Comment by Norbert80** [comment]
> It should not make a difference which provider you use, but which provider does A (from the example above) use?

Who do you mean with "A"?

**Comment by Hocuri** [comment]
@Norbert80 https://github.com/deltachat/deltachat-android/issues/1496#issuecomment-700516571 the one who answered using reply-all

**Comment by Norbert80** [comment]
@Hocuri I'm sorry. I have deleted all these "groups" in the meantime, because communication was no longer manageable this way. Therefore I can not reconstruct this anymore.

**Comment by Hocuri** [comment]
in this case I unfortunately have no idea what to do about this issue.

**Comment by Norbert80** [comment]
I suggest core devs to reproduce it.

**Comment by monperrus** [comment]
I confirm that it happens that new conversations are created although it's the same set of recipients.

How is defined a group conversation today? 

Recipients? Subject? Thread-Id? Recipients+subject? Another mix?

Thanks!

**Comment by gerryfrancis** [comment]
@monperrus Which version of Delta Chat do you use currently?

**Comment by monperrus** [comment]
@gerryfrancis version 1.14.5

**Comment by r10s** [comment]
> How is defined a group conversation today?

if the group was created by delta-chat, there is a group-id that is used to sort things.

if the group was created by another mua, things are a bit mixed currently - therefore your problems. the plan is to sort things in the same thread together (identified by `In-Reply-To` and `References`, this is sort of a thread-id, yes)

however, i think, this issue is covered by the project https://github.com/orgs/deltachat/projects/31 we are currently working on and, more concrete, by the the core-issue https://github.com/deltachat/deltachat-core-rust/issues/2073 - at least now, there is a reference to this thread :)

closing this issue here, there is nothing android can do about that.
