### ISSUE TITLE
Feature Request - display more information for messages

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#150]
Especially for diagnosis while beta phase of DC now and to examine problems with imap server it would be very welcome to have following features available:
- displaying sending mail client type/name in footer line of each message.
  Information could be taken from "User-agent:" or "X-Mailer:" header.
  (small text in line where hooks are shown).
- displaying timestamp of mail really fetched by DC (local delivery, second timestamp in msg footer).
- displaying msg source for each msg (see K9 "Kopfzeilen anzeigen").
- timestamp of last active status of connection to imap server (in menu settings->status (new)) ?

**Comment by r10s** [comment]
party this is targeted by #256, regarding different timestamps, etc. - well currently, we do not actually have these information in the database (the receiving timestamp, however, can be read from the log).

**Comment by csb0730** [comment]
So far ok by #256 but one very important issue is still open:

- How DC decides to map messages to a certain chat or group or ... ?

For that the headers "References:", "In-Reply-To:", "Group-ID", "Thread-ID" or even "User-agent:" or "X-Mailer:" (only an excerpt) may be used.

I think to understand some decisions of DC it would be usefull to store and show some of these essential headers too in database and show it in info section. Subsequently I would recommend to leave this issue open or open a new one.

**Comment by r10s** [comment]
well, it's just that these information are not available in the Delta Chat database - and I do not think it's worth saving the just for the case to understand some decisions. Esp. as you can get the information with a normal MUA as Thunderbird as well (in fact, this is what I am doing all the time :)

Also note, that the "Message Information" dialog is meant for the user, displaying all these information would require more a "View source" dialog. I do not think this is needed at the moment, however, feel free to open a more concrete issue for this, however, implementing this would required additional volunteers; of course I would be happy to support/review suggestions and efforts.

Regarding the decisions: at least some of then are logged, eg.
```
Receiving message Folder/UID...
Message belongs to a mailing list and is ignored.
Message is a reply to a known message, mark sender as known.
Message sent by another messenger (will be moved to Chats-folder).
Message is a reply to a messenger message (will be moved to Chats-folder).
Message has %i parts and is moved to chat #%i.
```
Of course, this can be optimized, however, at least for me, the current information are sufficient for developing :)
