### ISSUE TITLE
Remove sensitive information from the logs in the application

### ISSUE THREAD

**Issue by vatonbero** [deltachat/deltachat-android#1501]
- Operating System Android: **Lineage OS 17.1 (Android 10)**

- Delta Chat Version: **1.10.5 (F-Droid version)**

- Expected behavior: When you select "View Logs" in the application, there should be a way to remove personal email addresses from the report. More over, personal name (`display_name`) and similar values are expected to be removed since application mentinons nowhere that this information is provided in the logs in raw format.

- Actual behavior: If you export logs right now and put them onto github as a part of bug report, it will show raw email addresses and thus expose personal information to who knows who here.

- Steps to reproduce the problem:
-- Open Delta Chat
-- Export logs
-- Check logs contents

- Logs: Just export any logs, you will see personal identifiable information

**Comment by gerryfrancis** [comment]
> If you export logs right now and put them onto github as a part of bug report, it will show raw email addresses and thus expose personal information to who knows who here.

These logs are ASCII text files anyone can edit before posting them (on Github).

**Comment by vatonbero** [comment]
> > If you export logs right now and put them onto github as a part of bug report, it will show raw email addresses and thus expose personal information to who knows who here.
> 
> These logs are ASCII text files anyone can edit before posting them (on Github).

Makes sense of course. Still, this is not really addressing the issue here if you need to share 2000 lines of logs because you have to be very informed what the program will do and what should be expected at certain points.

Do not get the wrong idea here: logs should be used to review what is happening at certain points but putting everything in plain text and allow sharing without even a prompt or any warning in this age? Nobody wants to filter the logs and do any chore of that sort if you wanna appeal to the regular user who can just "tap here an then there".

There should be a way to share logs without sensitive details. Idea: data strings could be replaced in the logs (`Gmail` keywords Replaced with `SampleProvider`).

**Comment by gerryfrancis** [comment]
Maybe something like a switch (on/off) could be implemented, e.g. "Do not write personal data in log file", before writing the log file.

**Comment by r10s** [comment]
it might be a bit tricky, to define what personal data really are. also, many times when sending a log, it is not clear beforehand, which data are needed to solve a given issue. moreover, parts of the logs come from android - these may also contain personal data, and we do not really have control about these log lines.

also, logs are not only meant to be sent via the internet - they are also useful when helping a person standing next to you -  or you can send them to a person you trust.

so, in general, whatever we are doing here, it comes at costs. and these costs may be larger than the costs saved when going through a log before sending it to unsafe channels. 

but we should prefix the log by a sentence as

```
This log contains personal data.
If you want to post it publicly you may examine and edit it beforehand.
```

i would add this hint as a warning to the exported log (before the log starts), so users are reminded to this fact also later.

**Comment by vatonbero** [comment]
> it might be a bit tricky, to define what personal data really are. also, many times when sending a log, it is not clear beforehand, which data are needed to solve a given issue. moreover, parts of the logs come from android - these may also contain personal data, and we do not really have control about these log lines.
> 
It is not difficult at all to determine this: Email in readable form is personal data. It would be better if application stated upfront that sending logs will include list of all emails and messages exchanged between 2 or more persons.


> but we should prefix the log by a sentence as
> 
> ```
> This log contains personal data.
> If you want to post it publicly you may examine and edit it beforehand.
> ```
> 
> i would add this hint as a warning to the exported log (before the log starts), so users are reminded to this fact also later.
>
If goal of this project is to appeal to people who are used to sending logs than this is fine. Somehow i get the feeling that project would like to share the idea of IM via email so it needs to be as neutral as possible.

Dont get this the wrong way: i do not think that this should be shoved down our throats and create some social justice warrior thingy by bothering everyone on how this is important. In reality, it is important and there should be a big banner stating what will be shared if you send raw logs. This is just my 2c on the matter of course!
