### ISSUE TITLE
proper troubleshooting info in case of SMTP authentication failure

### ISSUE THREAD

**Issue by monperrus** [deltachat/deltachat-android#1508]
# Steps to reproduce the problem

Send an email with incorrect SMTP info, eg an incorrect SMTP user or an outdated SMTP password.

# Expected behavior:

The explicit troubleshooting information is given to the user, such as a device message (suggested by @r10s in https://github.com/deltachat/deltachat-android/issues/1218#issuecomment-660669821).  

# Actual behavior

The message is not sent, it is stuck with the "circle" icon (see https://github.com/deltachat/deltachat-android/issues/1218 and below)
 
<img src="https://user-images.githubusercontent.com/52469394/72749923-62101180-3b89-11ea-93dc-e51877f2bfd5.jpg">

**Comment by Hocuri** [comment]
Actually I already added an issue here: https://github.com/deltachat/deltachat-core-rust/issues/1768 but I got the link wrong so that it was not shown in the original issue.

This is a core issue because it affects all uis and it would be nicer if we do not have to change the ui code.
