### ISSUE TITLE
Request: Refresh new message

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-android#151]
Sometimes messages sent to my DC show up first on my email client and it takes a looong time to show up on DC. For now, the solution is to kill and restart DC to refresh and get new messages. Would it be possible to add a refresh button somewhere in the application?

**Comment by stefan-niedermann** [comment]
Or pull to refresh as in the default email client? it's a well known paatern on android, does not clutter the UI and is helpful for people with problems?

**Comment by csb0730** [comment]
Maybe related to/with #149 ?

**Comment by Hocceruser** [comment]
IMHO the user should not have to refresh manually; if the push notifications do not work there should be a fix for it...

@luisfsr: Can you find out when this happens?

Concerning pull to refresh: I do not think that this is a good idea as it is kind of a psychological trick:
> When we pull to refresh our email, we’re playing a slot machine to see what new email we got.
(https://journal.thriveglobal.com/how-technology-hijacks-peoples-minds-from-a-magician-and-google-s-design-ethicist-56d62ef5edf3)

(it has something of a one-armed bandit😉)

**Comment by luisfsr** [comment]
I can't isolate whats causing the problem. But its occasional, seldom. About the slot machine problem, I don't think that's the case of DC, once it's intended to real time chat. If you're chatting with someone you're already engaged in a conversation, a big delay could cause problems, misunderstands... So the idea of pulling to refresh messages could be, at least meanwhile there's not a better alternative, an acceptable circumvention, IMHO.

**Comment by r10s** [comment]
with the last version, new messages appear much more reliable, so probably, this issue can be close.
