### ISSUE TITLE
Use my own GPG key

### ISSUE THREAD

**Issue by Almtesh** [deltachat/deltachat-android#152]
Hi,
I allready have a GPG key for my e-mail address, is there a way to use it instead of the autogenerated key by Delta Chat?

**Comment by csb0730** [comment]
Yes it is. See documentation (Help section). There is a description to do that.

**Comment by Almtesh** [comment]
Actually, it tells how to import your own key, not how to use it by default.

**Comment by csb0730** [comment]
if you import your own key DC will use it. thats what I understand from doc.
but maybe have a look in faq or github issues. somewhere there are additional descriptions.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Almtesh** [comment]
OK, I imported my key, but Delta Chat is not using it. I can't find how to select the new or delete the old key.

**Comment by r10s** [comment]
- Currently, simply the last imported key is the key spread when sending messages.
- For decryption, all keys are used (currently, "Settings / Info" shows the number of available keys.

Of course, this could be improved.

**Comment by Almtesh** [comment]
It sees 3 private keys, two public keys, and the shown fingerprint is the one autogenerated by Delta Chat when it started E2E encryption.

**Comment by genofire** [comment]
A would like to use it with openkeychain (my GPGmanager), could you use: https://github.com/open-keychain/openpgp-api ?

**Comment by r10s** [comment]
see https://github.com/deltachat/deltachat-android/issues/161

**Comment by r10s** [comment]
i think this can be closed, in general, own pgp keys can be used by an import (not recommended) or by an autocrypt setup message (recommended)
