### ISSUE TITLE
image preview in chat is often 180x180px

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1523]
sending an image from ios to android results in preview of 180x180px, the enlarged image is fine, however, and the preview also keeps the correct aspect ratio. seems as if the correct dimensions are not reported and the fallback-calculation was removed on android recently, maybe together with the new recoding-in-core.

**Comment by r10s** [comment]
it seems to be correct in v1.10.4, i continue investigating ...

**Comment by link2xt** [comment]
Could be caused by https://github.com/deltachat/deltachat-core-rust/pull/1742?

**Comment by r10s** [comment]
yip, i also suspect that change :)
