### ISSUE TITLE
Old Android not getting notified

### ISSUE THREAD

**Issue by RubenDavidPerezJimenez** [deltachat/deltachat-android#1525]
Os: Android
Delta Chat version :1.11.0
Android version: 4.2.2 or 4.4.2 maybe more
Expected Behavior: on get message from server, the user receive a notification
Actual Behavior: the notification does not appear, with or without the reliable background connection setting

In the 1.8.1 it works ok but later version it are not working fine

**Comment by angelo-fuchs** [comment]
@RubenDavidPerezJimenez Can you create a log with the following setup:
- Restart Deltachat (eg. by restarting the phone)
- Ensure that you have network connection
- Send a message to the Deltachat from the outside
- Wait 20 Minutes (15 minutes is the largest of our timeouts and I want to be sure it triggered)
- Open Deltachat
- Go to Settings -> Advanced -> Logfile
- Then save it.
- If you are fine with the email address, etc. being posted here just upload it. If not, you can send it to contact@sommerfuchs.info and I will strip away the personal information before uploading. (Of course you can remove the information yourself if you prefer. The log is just a text file.)

Also, please let us know your mobile plan for data transfer, we had some Cuban users report issues on Mail Bag that are not associated with older Android versions.

**Comment by RubenDavidPerezJimenez** [comment]
The problem is not that the message does not arrive, is the message is not 
notified in the status bar, I will send the log when I have in my hands


En 4 de agosto de 2020 6:05:21 p. m. Angelo Fuchs

**Comment by angelo-fuchs** [comment]
[Log sans user address](https://github.com/deltachat/deltachat-android/files/5026970/log_oldandroid_notification_fail.txt)

Interesting things from the log:

> app=DeltaLab 1.10.6-gplay-debug
> ... nauta.cu ...

A lot of things not loading.
No DC Messages in the log besides the header part.
Unfortunately not much to be learned from it.

**Comment by RubenDavidPerezJimenez** [comment]
Sorry I don't have much know of debug in delta chat

**Comment by angelo-fuchs** [comment]
@RubenDavidPerezJimenez No worries, I have a very old Android (4.0.4) laying around and will try to reproduce the issue there.

**Comment by angelo-fuchs** [comment]
I could reproduce this in Android 4.1 emulator (but on Android 4.0.4 it works...)

**Comment by RubenDavidPerezJimenez** [comment]
thanks @CompuRoot  for reporting back
