### ISSUE TITLE
Add "go to last seen"

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1528]
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: Some versions or years ago (I don't know) until current master
- Expected behavior: When I open a chat with unread messages, I get to the position of the first unread message and a "3 unread messages" is shown
- Actual behavior: it is not shown
- Steps to reproduce the problem: Receive many messages (that do not fit on the screen) and open the chat

**Comment by r10s** [comment]
well, it is just a missing feature, i would not consider that as a bug ;)

nevertheless, it is an important thing that we should add.

there is the rough idea to get that in on all platforms by the MARKER thing, https://github.com/deltachat/deltachat-core-rust/issues/1674

**Comment by Hocuri** [comment]
Ah ok, the code looked as if this should be working to me. Do you know what "moveToLastSeen()" does?

(it is important for me because if this is a feature that is currently working, then I might break it with #1529)

**Comment by r10s** [comment]
yip, there is some code, eg. when being inside a chat, switching display off+on and message arrive in between, the message marker is shown.
