### ISSUE TITLE
Behavior for mail server with filter rules

### ISSUE THREAD

**Issue by Almtesh** [deltachat/deltachat-android#153]
I have sieve rule on my mail server that put on "Chats" folder every e-mail that my be managed by Delta Chat. DeltaChat allready manage to receive e-mails directly in the "Chats" folder.
Would that be possible to add a option for that Delta Chat only manage the "Chat" folder and does not automaticly add e-mail that autodetected as chats in the INBOX?

**Comment by Hocceruser** [comment]
In my experience it is easier to simply use another email account for DC 😉

**Comment by Almtesh** [comment]
Of course, but another e-mail account means another GPG key, another e-mail address to communicate.
Or you meant redirecting Delta Chat e-mail to another address.

**Comment by testbird** [comment]
Oh, apparently I had overlooked this issue and opened one on -core:
https://github.com/deltachat/deltachat-core/issues/60

**Comment by r10s** [comment]
As this request fits better to the core, I think we close the issue here and continue the discussion at https://github.com/deltachat/deltachat-core/issues/60
