### ISSUE TITLE
AAC voice messages don't play for some recipients

### ISSUE THREAD

**Issue by rrthomas** [deltachat/deltachat-android#1531]
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: 1.10.5
- Expected behavior: Audio message should play for just about any recipeient
- Actual behavior: Some email clients/OSes can't handle AAC, or at least the flavor of AAC sent from my Android device.

Suggestion: use a more common format, such as MP3, or at least allow this to be configured for users communicating with non-DeltaChat users.

**Comment by r10s** [comment]
for the same file-size, mp3 have a much worse quality than aac-files, therefore, switching to mp3 is not a good solution. 
aac was not the format of our dream, but has encoders on all systems and was easy to implement. ogg may be better, but is some additional work to get that running everywhere, )maybe we will switch to that some day, however)

adding a switch will solve the problem only partly - and may make things even worse ux-wise (you can play _some_ voice messages then)

so, i'd say it is up to the clients to add support for aac in a way - same as for video-codecs - afaik, this is possible even for most linux systems today.

**Comment by rrthomas** [comment]
@r10s, I believe in this case we're talking about a web mail client, but yes, in general I'm talking about other mail clients.

Currently the UX is this: I send a message, and my correspondent tells me they can't play it. DeltaChat is supposed to be an email client as well as a chat app (I appreciate this is tough!). I shouldn't' have to care what my correspondent is using. Have I misunderstood this? If I have to ensure my correspondent is using a "compatible" system, then most of the time it will be easier to arrange for the two of us to use the same proprietary IM app.

I'm trying to send voice clips etc., not make an audiophile happy. The question is not "what's the best quality per bit" but "can we get adequate quality and data usage"? Users of email systems have vastly differing data costs, so there's unlikely to be an answer that pleases everyone in any case. I'm not sure how "ability to play some messages" is worse UX-wise than "ability to play no messages". If DC insists on a default that is not universally playable, then at least a switch allows the user to overcome this problem.

FWIW, I'm a Linux user, and I had no problem playing the AAC file, though I did have to try a couple of programs before I could find one that would transcode it to MP3 (e.g. faac couldn't read DeltaChat's voicenote).

**Comment by r10s** [comment]
> I shouldn't' have to care what my correspondent is using. Have I misunderstood this?

i agree. this is also why i do not like switches on the senders side very much.

but if the recipient is using a system that cannot display some things - what can you really do about that?
and what if there is a fix - but that comes at costs, eg. having much larger file formats, higher mobile costs, longer download times etc. - i think, this is bad ux as well.

the web is full of things that need migration at some point.

in general, of course, we try to use formats that are widely spreaded and try to not use "the latest hot things", but i think this is not true for AAC. and, as said, ogg might be better, which however, is not supported on older androids and would require decoding on ourselves (doable, of course, but uses work resources that are missing somewhere else then)

also: what are the systems that do not support aac we're talking here about? it might be a difference  if we're having problems with 50% outlook users or 0.1% web.de users.

finally, i think this is more sth. for the forum as this does not affect android alone.

**Comment by rrthomas** [comment]
Thanks for the reply, @r10s. Which section of the forum do you suggest (sorry if it should be obvious!).

As you suggest, if the recipient is using a text terminal, they will not be able to display images. But I don't think this is that sort of situation: most users will have audio capabilities, and almost all of those will support MP3. What I haven't seen here is, what is the cost? How large is reasonable quality MP3 compared to reasonable quality AAC? And how much worse is MP3 if you make it the same size as AAC currently? (After all, we still use JPEG for compatibility even though there are better options for image compression.) Yes, there are many things it would be nice to migrate at some point, but consider that where I live in the UK we still measure distances in miles, and it's not the end of the world. Sometimes, the cost of migration outweighs the benefits.

In this case, the problem is with Outlook.com (mobile and web versions). And of course I understand that DC does not work with Outlook.com; indeed, that's precisely the point here: my correspondent cannot simply use DC instead!

**Comment by r10s** [comment]
> Which section of the forum do you suggest (sorry if it should be obvious!).

it is not too obvious, i'd go for "Feature request" or just "Uncategorized".

> How large is reasonable quality MP3 compared to reasonable quality AAC? 

for lower bitrates [as we are using](https://github.com/deltachat/deltachat-android/issues/481), using AAC instead of MP3 easily halves the size needed (at comparable quality).

also, we are using bitrates down to 24kbit - these low really, really bad for MP3 :)

here is a random link with some examples
http://tonerack.com/analysis-of-mp3-vs-aac-which-is-better-quality/
(using audacity, you can easily create your own examples using some voice )

**Comment by rrthomas** [comment]
Thanks for the guidance, @r10s; I've made a forum post.

**Comment by r10s** [comment]
thanks a lot, ftr, https://support.delta.chat/t/some-email-clients-e-g-outlook-web-mobile-cannot-handle-aac-voice-messages/1151 - if the outcome are concrete actionable items for one android/ios/desktop or core, we can open more concrete issues here again.
