### ISSUE TITLE
Message info box not translated

### ISSUE THREAD

**Issue by Norbert80** [deltachat/deltachat-android#1533]
Hi,

If I select any message and press the i-button to display message info I get English strings like "Sent:", "by", "State: Delivered", "Message-ID" and "Last seen as:"

I assume that all languages are affected but I can confirm it for my German system environment.

Found with Delta Chat 1.12.1.

**Comment by gerryfrancis** [comment]
I can confirm this behavior in Desktop version 1.12.0, too.

**Comment by r10s** [comment]
yip, this dialog is not translatable yet, it is just a string generated by the core.

at some point, we will rework the whole dialog and also make it translatable, however, for now it is easier the current way as we can easily add information to all systems.

**Comment by r10s** [comment]
closing this for now, this is no concrete actionable item and if we come over reworking the info-dialog, of course, it will be translatable then.
