### ISSUE TITLE
dialog pops up too early when setting up a new account

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1536]
- Operating System (Linux/Mac/Windows/iOS/Android): android
- Delta Chat Version: latest master 1.12.2
- Expected behavior: dialog "checking xxx@xxx.xx" appears after password was entered
- Actual behavior: dialog "checking xxx@xxx.xx" appears directly after email text field looses the focus
- Steps to reproduce the problem:
1. setup a new account
2. enter an email address
3. tab into the password field

The dialog blocks the user from entering the password. Moreover the alert appears for about 45 seconds, without any feedback afterwards.

- Logs:

**Comment by cyBerta** [comment]
I had a look into the code and it seems like this behavior is intended. Not sure if I should close this ticket though, since its the work flow interruption related to the alert is surprising and a little bit annoying imo.

**Comment by r10s** [comment]
the lookup is needed after the email is entered - if oauth2 is supported, a password is not required. so, the flow is correct.

> Moreover the alert appears for about 45 seconds, without any feedback afterwards.

that should be much quicker in most cases, eg. for well-known domains from the provider-db, no network is required at all. what was the entered domain?

however, closing the issue, we can open a more specific one wrt the long delay, if needed.
