### ISSUE TITLE
single login for bug tracking and other contributions

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#1539]
There is nothing worse then 500 separate and individually unique logins just to contribute to one project..
It makes people not want to be involved,. 
Logins for bugs, logins for forums else where logins for everything and they all have to be unique and special....

**Comment by hpk42** [comment]
I understand you'd like to have some single-login scheme.  You can sign up with the support forum using your github account. So you can virtually access all bug trackers and the support forum from the same login. 
In any case, this is not a bug on Android and not even a bug with Delta Chat.  Please don't open such issues here. thanks!
