### ISSUE TITLE
where is Bjorn?

### ISSUE THREAD

**Issue by rizzopablo** [deltachat/deltachat-android#154]
Anybody knows? More than 20 days without notices from him.

**Comment by Ampli-fier** [comment]
I think you can close this issue :-)
He posted a new [blog entry](http://delta.chat/de/blog) before he left for a break.

**Comment by csb0730** [comment]
And we didn't reach end of August  ;-)

**Comment by rizzopablo** [comment]
thanks! I didn't read the blog :D

**Comment by r10s** [comment]
I'm back :)
