### ISSUE TITLE
image rotation not working sometimes

### ISSUE THREAD

**Issue by RubenDavidPerezJimenez** [deltachat/deltachat-android#1544]
[deltachat-log-20200812-091030.txt](https://github.com/deltachat/deltachat-android/files/5062858/deltachat-log-20200812-091030.txt)
[deltachat-log-20200812-091030.txt]

Seen in Android 9 phone with the Google keyboard and Delta Chat 1.12.1 on redmi note 8 in MIUI 11 on the last patch, maybe it are the Android 9  

**How do the bug:** 
- open Delta Chat on landscape mode
- go to chat with a Image(in my case .png)
- put the keyboard in fullscreen likewise you are trying to do a message
- rotate to portrait again

**Comment by gerryfrancis** [comment]
I cannot reproduce that in version 1.12.2, neither with a JPEG nor a PNG image. Please update to the latest version, try again, and report back. Thanks!

**Comment by RubenDavidPerezJimenez** [comment]
I have updated and got the same error maybe be MIUI

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez I have tried again, but I still cannot reproduce your issue. Please post a screenshot, maybe I do not understand you correctly. Thanks!

**Comment by r10s** [comment]
@RubenDavidPerezJimenez does it happen to all images for you? or only for specific images? there is the error `java.lang.IllegalArgumentException: y + height must be <= bitmap.height()` in the log, so it might be specific to a concrete image, it that is related at all.

and yes, some screenshots would be helpful, i also have no good imagination what to do on trying to reproduce the issue :)

**Comment by gerryfrancis** [comment]
@r10s Have you tried with a PNG image as well?

**Comment by RubenDavidPerezJimenez** [comment]
I thought at first that they were the pictures but it seems to me that is the background
 to do it you must open a chat in this way
![2020-08-13-08-01](https://user-images.githubusercontent.com/47091244/90132280-8442ca00-dd3b-11ea-86a8-face1fd001e8.jpg)
 Later go to click on the message writing view and let the keyboard open in fullscreen like these
![2020-08-13-08-02-1](https://user-images.githubusercontent.com/47091244/90132423-d1bf3700-dd3b-11ea-84f9-ca65c95e7ef6.jpg)
And now rotate the Chat and will close the app

**Comment by angelo-fuchs** [comment]
@Hocuri Could you reproduce the issue? Try as I might, I cannot.

**Comment by angelo-fuchs** [comment]
@RubenDavidPerezJimenez When did you last set the image?
If you set it to default and then to your pictune in 1.12.1 does the error still appear?

**Comment by RubenDavidPerezJimenez** [comment]
I have reset the image, i have changed it and i put the default image back, and it persist, the only shape that it doesn't crashed is when i put the keyboard in floating mode

**Comment by Hocuri** [comment]
@angelo-fuchs yes. DC crashed when I followed these instructions. It has nothing to do with your selected background image (it happened with the default DC background on my phone).

java.lang.IllegalArgumentException: y + height must be <= bitmap.height() was also in my log.

**Comment by RubenDavidPerezJimenez** [comment]
i believe the problem is in the measureViewSize method, my phone have notch and i think it changes 2 times the size and that is the thing that malfunctioning

**Comment by angelo-fuchs** [comment]
@RubenDavidPerezJimenez You are correct.

I could reproduce the issue on a Android 9 emulator.
measureViewSize gets called twice for portrait in this scenario and the first one has a smaller size than the second one.
So when we tell the app to crop the smaller size to the larger it fails.
