### ISSUE TITLE
Camera (live view) turned off (black screen) after rotating device

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1549]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200705.002 from 2020-08-07).

- Delta Chat Version:
1.12.2.

- Expected behavior:
When live view of the camera is turned on (to take a photo), rotating the device adapts the view (from portrait to landscape or vice-versa).

- Actual behavior:
When live view of the camera is turned on (to take a photo), rotating the device turns the camera off and the screen is black. (However, the navigation bar on the right is visible works.)

- Steps to reproduce the problem:
-- Start a chat.
-- Tap the camera icon to activate the camera.
-- Rotate the device. (Result: The camera turns black.)

- Screenshots:
N/A.

- Logs:
[deltachat.txt](https://github.com/deltachat/deltachat-android/files/5068659/deltachat.txt)

- Remarks:
-- Rotation of screen is configured and works.
-- Changing the camera (from front to back or vice-versa) brings the view back. For now, a possible workaround is to change the camera twice.

**Comment by Hocuri** [comment]
I can reproduce this.

**Comment by r10s** [comment]
i have the effect every 2nd try or so - and i have the same bug also when rotating back to portrait (also not always, but often)

**Comment by gerryfrancis** [comment]
Great, many thanks to you, @Hocuri, @cyBerta, and @r10s, I will test it in the next release! :+1:

**Comment by gerryfrancis** [comment]
Superb, it works! :+1:
