### ISSUE TITLE
Suggestion: Convert emojis into asscii emoticons to non-DC-clients

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-android#155]
Having in mind that some of the recipients of DC messages don't use DC or even an android client, emojis could just show up there as unrecognized characters.
Ideas: I) implement asscii emoticons as default on DC ( e.g. https://github.com/dysfunc/ascii-emoji ); or II) make DC convert android emoji fonts into asscii emoticons and vice-versa when it reaches a DC client; or, instead, III) exceptionally send html messages when the DC user makes use of emojis, converting the emojis into image files.
Just a humble opinion! (^^)

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
