### ISSUE TITLE
Different (stock) camera app launched when chosen as message attachment

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1550]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200705.002 from 2020-08-07).

- Delta Chat Version:
1.12.2.

- Expected behavior:
The same camera app is launched for taking a photo when tapping the camera icon from the keyboard and selecting "Camera" to add an attachment.

- Actual behavior:
The camera app launched to add an attachment is different, it seems to be the stock app.

- Steps to reproduce the problem:
-- Start a chat.
-- Tap the camera icon to activate the camera.
-- Tap the back icon on the bottom to dismiss the camera frame.
-- Tap the attachment (clip) icon and choose "Camera" to activate the camera. (Result: The app to take a picture is different.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by Hocuri** [comment]
I'd say that this is by design. If you want to open your external camera app, you choose "Camera" from the attatchments.

**Comment by gerryfrancis** [comment]
@Hocuri OK, but wouldn't it make sense to use only one camera app in Delta Chat?

**Comment by r10s** [comment]
the camera from the keyboard is for a "quick photo", you can take a photo from there without leaving delta chat or the chat context. however, you cannot take videos there and you cannot replace this camera, therefore, there is the system-camera launchable from the "attach menu".

**Comment by gerryfrancis** [comment]
@r10s Thanks for the information. To take better photos, I guess I will use the stock camera app.

**Comment by r10s** [comment]
at some point, we may discuss if the two different cameras make sense, however, iirc, this "quick view" was also a request in the past, and, i personally, also find it pretty nice :)
