### ISSUE TITLE
mail.ru server.  Does not receive messages.

### ISSUE THREAD

**Issue by devtula** [deltachat/deltachat-android#1552]
- Operating System : Linux, Android
- Delta Chat Version: 1.12.2 (Android), 

- Expected behavior:
receive messages from **mail.ru** server
- Actual behavior:
Receives messages only after the app is restarted.
- Steps to reproduce the problem:
Anytime.
- Logs:

`
08-13 15:36:09.903 13788 13830 I DeltaChat: src/imap/mod.rs:728: fetch_new_messages: ignoring uid 202, last seen was 202
08-13 15:36:09.903 13788 13830 I DeltaChat: src/imap/mod.rs:678: 0 mails read from "&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-".
08-13 15:36:09.903 13788 13830 I DeltaChat: src/imap/idle.rs:185: fetch_new_messages returned false
`

**Comment by Hocuri** [comment]
@devtula thanks for the report!

The one line of logs you shared just means that DC does not download known messages again. Can you please share some more logs?

**Comment by devtula** [comment]
The lines are repeated, only the time changes. After restarting the app all messages are received.

**Comment by gerryfrancis** [comment]
@devtula Does it occur after waking up the device from sleep mode?

**Comment by link2xt** [comment]
Related problem, mail.ru seems not to support `IDLE`: https://github.com/deltachat/deltachat-core-rust/issues/1868
Maybe a problem with fake-IDLE code.

**Comment by devtula** [comment]
> Related problem, mail.ru seems not to support `IDLE`: 
sure
https://github.com/deltachat/deltachat-core-rust/issues/1868#issuecomment-687088808

**Comment by r10s** [comment]
closing this one, there is no actionable item left for android and the core-issue is already marked as "needs retry", it is better to discuss this there.
