### ISSUE TITLE
Pictures saved in folder "Pictures", a subfolder of Android "Pictures" folder sometimes

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1554]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200705.002 from 2020-08-07).

- Delta Chat Version:
1.12.2.

- Expected behavior:
Saved pictures can be found in the dedicated Android picture folder.

- Actual behavior:
Pictures are saved in "Pictures/Pictures". In other words: When "Pictures" is opened, you find another "Pictures" folder that contains the saved files in there.

- Steps to reproduce the problem:
-- Save any picture either from the chat view or the media gallery.

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
might be manufactor specific, i just tried on a moto-g with manufactor-andorid, there pictures go to the correct folder (more concrete /storage/emulated/0/Pictures) 

i tried both, long-click on a photo -> save and gallery -> save.

**Comment by gerryfrancis** [comment]
@r10s Does it matter to Delta Chat which language is set to the OS? Because in my German configuration, the subfolder "Pictures" is located in "Bilder".

**Comment by gerryfrancis** [comment]
**Aaaaaaaahhhhh,** I am a damn Windows guy who does not have a clue about Android!! That is no subfolder which I believed I was in, it is more a general Android view leading to two areas, "Camera" and "Pictures". SORRY!! I am closing this...

**Comment by r10s** [comment]
np, thanks for coming back :)
