### ISSUE TITLE
Use slightly different keyboard layout for URL input field(s)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1556]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200705.002 from 2020-08-07).

- Delta Chat Version:
1.12.2 & 1.12.3.

- Expected behavior:
When an URL is to be entered in an input field, e.g. the one to enter a WebRTC server, the same keyboard layout provided in URL input fields in web browsers should be offered (with the slash in first place).

- Actual behavior:
The keyboard layout differs, it is not the one used in URL input fields in web browsers. To type the slash character in "https://", the user must switch the layout.

- Steps to reproduce the problem:
-- Focus an URL input field, e.g. the one an URL to a video chat (WebRTC) server is to be entered.
-- Focus an URL input field of a web browser and compare both keyboard layouts with each other.

- Screenshots:

-- Keyboard layout used in web browsers for URL input field(s):
![grafik](https://user-images.githubusercontent.com/51095533/90179449-c3116800-ddad-11ea-9927-94f06791fcd5.png)

-- Keyboard layout used in Delta Chat for URL input field(s):
![grafik](https://user-images.githubusercontent.com/51095533/90179542-e0463680-ddad-11ea-9e05-573acd511194.png)

- Logs:
N/A.

**Comment by Hocuri** [comment]
Are there any other url input fields than WebRTC in DC?

**Comment by gerryfrancis** [comment]
@Hocuri I do not think so, but I cannot say for sure.
Another thing I have just recognized is that in username fields of the account configuration, e.g. IMAP and SMTP login names, the keyboard layout must be toggled to access the `@` character. Shall I file a separate issue for that?

**Comment by cyBerta** [comment]
@gerryfrancis no, it's not necessary. I will fix both within this ticket

**Comment by gerryfrancis** [comment]
Thanks a lot, @cyBerta, it will lead to a better user experience when starting with Delta Chat.

**Comment by gerryfrancis** [comment]
Great, thank you very much, I will test the fix in the next release! :+1:

**Comment by gerryfrancis** [comment]
Looks good in version 1.12.4, thanks a lot! :+1:
