### ISSUE TITLE
Lost encryption key. What to do?

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#156]
All data on the phone was destroyed and the whole system needed to be reset. Now, after a fresh installation of Delta-chat, it cannot read the old messages al though they still exist on the server. I guess, they are lost for ever. 
But: What can I do to reactivate the communications to the existing groups and contacts? Do they receive the new key and will they use them automatically to encrypt messages for me?

**Comment by r10s** [comment]
Old messages are lost if you do not have a backup if the key (see advanced/export).
For new messages: Just send your messages to your contacts - they will use your new key automatically in subsequent messages. Revocation or sth. like that is not requied :)

**Comment by kollokollo** [comment]
OK, fine. Thanks.
