### ISSUE TITLE
Scoped Storage Support

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1561]
Beginning with Android P scoped storage is recommended and it will be obligatory when the target API will be updated to Android Q. 

At the moment we use a flag https://github.com/deltachat/deltachat-android/pull/1551/files#diff-a48d6def78e18cbabab3c95ae3c9fc49R48 to gain some time to introduce scoped storage correctly (see infos here: https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage). 

more info about scoped storage:
https://developer.android.com/training/data-storage#scoped-storage
https://www.youtube.com/watch?v=UnJ3amzJM94

**Comment by r10s** [comment]
i think, this is targeted by https://github.com/deltachat/deltachat-android/pull/2087 - at least, we are in gplay with api30, so there is no more pressure  from that side for now :)
