### ISSUE TITLE
Problem in the group name

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1564]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.12.2
- Expected behavior: When I paste a multiline phrase into the group name, it allows me to set a profile picture and receive any name changes via system messages and not normal messages.
- Actual behavior: You cannot set the group image and receive system messages as normal messages.
- Steps to reproduce the problem: Copy any multi-line message and paste it into the group name.
- Screenshots:
![Screenshot_20200814_204116_chat delta beta](https://user-images.githubusercontent.com/63752768/90282381-c49a6900-de5d-11ea-9f7b-808efb88a07e.jpg)

- Logs:

**Comment by gerryfrancis** [comment]
@AndreazLattmann Thank you for your report. It took a while for me to understand what you have meant, but I can confirm your finding, that is a tricky one! Actually the problem does occurs when the following steps are performed:

-- Create a group with at least two members (you and another contact). The group must be named with a multi-line phrase, e.g. by copy a short paragraph into the group name field.
-- Send the introduction message to the group member(s).
-- Rename the group.

It is not necessary to apply a picture to the group at all.

**Comment by AndreazLattmann** [comment]
@gerryfrancis it was a bit difficult to explain this error.😅

**Comment by gerryfrancis** [comment]
@AndreazLattmann Never mind, it is a great catch anyway! :+1:

**Comment by Hocuri** [comment]
Actually, I would expect that multiline group names are just rejected or all newlines are removed.

**Comment by gerryfrancis** [comment]
@Hocuri You are right, nevertheless it would be good to know why renaming the group is causing that behavior (sending a normal message instead of a system message). (I would like to, but unfortunately I have no coding skills.)

**Comment by cyBerta** [comment]
> Actually, I would expect that multiline group names are just rejected or all newlines are removed.

It would make sense to sanitize the strings in the core.
