### ISSUE TITLE
Terms "CANCEL" and "DONE" in group picture selection view not localized

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1566]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-08-14).

- Delta Chat Version:
1.12.2.

- Expected behavior:
The terms "CANCEL" and "DONE" in the group picture selection view are localized when a different language than English is used.

- Actual behavior:
The terms "CANCEL" and "DONE" in the group picture selection view are not localized when a different language than English is used.

- Steps to reproduce the problem:
-- Create a new group and tap on the group avatar space to select a picture.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/90341092-fd247900-dffc-11ea-8f0b-1fde8386ef17.png)

- Logs:
N/A.

**Comment by Hocuri** [comment]
I can confirm this. The problem is that we are using https://github.com/jdamcd/android-crop (`com.soundcloud.android:android-crop`) for this activity, which is not maintained anymore and will definitely not get any new translations. Maybe we can have a look at what Signal is doing now, maybe they fixed this in the meantime.

**Comment by Gh0stz0x** [comment]
![Screenshot_20230205_203320](https://user-images.githubusercontent.com/74795149/216840701-7268f4c8-b347-4bfc-935e-3fc08491a96b.jpg)

The problem is still present in 1.34.12

**Comment by AndreaEnzoLattmann** [comment]
The problem is still present in 1.36.2

**Comment by gerryfrancis** [comment]
@adbenitez Thanks, I did not have this one on my "radar" anymore! ;)
