### ISSUE TITLE
DC hangs on startup (on a slow and old phone)

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#157]
I have observed, that when DC is started on the phone, it opens, but does not take any user input, so it hangs, and finally gets force-closed. When started again, the same happens all over.

I have observed with catlog, that after starting of DC there are T2, T3 and T4 threads working th the background, processing all existing mails in the chat-folder (messages marked as read, thread deleted etc...). This takes quite a while, since there are already lots of messages. This can take up to 5 Minutes or even more. If you wait until this process is complete and then open the DC UI, Everything is fine and DC will not hang. But if you open it too early, it hangs and gets force-closed.

When does this happen: 
1. After rebooting the device
2. After WLAN network has changed (connection to the email server was lost and need to be reestablished). 
3. connection to the email server was lost and need to be reestablished for any reason.
4. after force-close or crash of DC.

Especially 2. is a quite frequend cause when you travel around. ALways having to wait 5min+ is annoying and also sometimes the phone goes into standby mode before and then the processing in the background is stopped or even reset.

**Comment by csb0730** [comment]
Sometimes I get the message from System that the app DC is not responding. "close or wait" is then asked by a Dialog. some time later DC works again.
Maybe this confirms this issue.

**Comment by kollokollo** [comment]
I have the feeling (no good analyzis so far) that this has improved (DC running much faster) with the August update of DC in F-Droid.

**Comment by kollokollo** [comment]
Since I have been using the new (August) Version of Delta Chat this problem has not occured anymore. It looks like, this was fixed.

**Comment by kollokollo** [comment]
No problems anymore. This topic can be closed.

**Comment by r10s** [comment]
Perfect :)
