### ISSUE TITLE
Time values for chats not refreshed when staying on chat list

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1571]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-08-14).

- Delta Chat Version:
1.12.2.

- Expected behavior:
After a message is sent/received, the elapsed time shown should refresh when staying on the chat list.

- Actual behavior:
After a message is sent/received, the elapsed time shown does not refresh when staying on the chat list.

- Steps to reproduce the problem:
-- Open the chat list and watch the time values. (Result: They do not change.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by angelo-fuchs** [comment]
I can reproduce this.

**Comment by gerryfrancis** [comment]
Thanks a lot, @angelo-fuchs, @cyBerta, and @r10s, I will test the fix in the next release. :+1:

**Comment by gerryfrancis** [comment]
Sorry, I have to reopen this one, because it does not update the time values.

**Comment by r10s** [comment]
i think, #1582 updates the values in the chat itself, not in the chat _list_, which however, was also an issue :)

**Comment by gerryfrancis** [comment]
@r10s Ah, I see, thanks for the info. I will leave this one here open. :)
