### ISSUE TITLE
Location label on map still visible after deleted

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1577]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-08-14).

- Delta Chat Version:
1.12.2.

- Expected behavior:
The location label is no longer visible after it has been deleted.

- Actual behavior:
The location label is still visible after it has been deleted. When the map is closed (by tapping on back) and reopened, the label is gone.

- Steps to reproduce the problem:
-- Enable location services.
-- Set a location label anywhere on the map.
-- Delete the location label which you set on the map.

- Screenshots:
N/A.

- Logs:
N/A.

- Remarks:
I believe that it takes a refresh of the map view to solve this.

**Comment by gerryfrancis** [comment]
Thanks, I will test the fix in the upcoming release! :+1:

**Comment by gerryfrancis** [comment]
Works fine in version 1.12.4, thanks! :+1:

**Comment by r10s** [comment]
thanks a lot for reporting back, here and in the other issues, this is very nice and helpful.

**Comment by gerryfrancis** [comment]
You are welcome, thanks for all the work! :heart:
