### ISSUE TITLE
Aborting Backup Import makes future imports fail

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#1579]
On current master
 (Android Nougat 7.1.2, SDK 25)

When I install DC fresh (via Android Studio) and start an import, select the file and hit ok (so that import starts) then wait a little and hit abort
Then I am unable to perform any imports after this until I deinstall and reinstall DC.

The specific behaviors are different, sometimes it will no longer detect any backups or it will display the "importing" dialog with the percentage locked at 1%.

Log of the latest attempt (after this percentage is locked to 1%)
```
23:09:16.929 W/DeltaChat: deltachat-ffi/src/lib.rs:3269: IMEX failed: canceled
23:09:16.952 I/DeltaChat: src/context.rs:259: No ongoing process to stop.
23:09:18.321 I/DeltaChat: src/sql.rs:1323: Opened "/storage/emulated/0/Download/delta-chat-2020-07-29-0.bak".
23:09:18.321 I/DeltaChat: src/imex.rs:108: backup_time of delta-chat-2020-07-29-0.bak is 1596022283
23:09:20.313 I/DeltaChat: src/imex.rs:371: Import/export process started.
23:09:20.313 I/DeltaChat: src/imex.rs:408: Import "/storage/emulated/0/Download/delta-chat-2020-07-29-0.bak" to "/data/user/0/com.b44t.messenger.beta/files/messenger.db".
23:09:20.313 W/DeltaChat: deltachat-ffi/src/lib.rs:3269: IMEX failed: IMEX FAILED to complete: Cannot import backups to accounts in use.
```

We should either remove the abort button or make sure it works properly.

**Comment by Hocuri** [comment]
As the core has an api that allows cancelling the process, I'd say it's a core issue. I'll do a fix.

**Comment by Hocuri** [comment]
> sometimes it will no longer detect any backups

I never experienced this (it was always stuck at 1%). Can you send a log of when it did no longer detect any backups?
