### ISSUE TITLE
Support starred messages

### ISSUE THREAD

**Issue by rajeevn1** [deltachat/deltachat-android#158]
This will let users mark messages for follow-up.  Imap supports starring messages.  Thanks.

**Comment by r10s** [comment]
Yes, this would be a great improvement. 
+1

**Comment by r10s** [comment]
Yeah, the core already has the required functionality, however, the GUI is still missing.

**Comment by r10s** [comment]
i'm closing this for now here; the new forum at https://support.delta.chat is the better place for feature requests and discussions.
