### ISSUE TITLE
improve aspect ratio for quick photo attachments

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1588]
- Android version: all supported
- Device: all android devices
- Delta Chat version: 1.12.3
- Expected behavior: photos taken with from the bottom sheet are not distorted
- Actual behavior: depending on the aspect ratio of the screen and the supported camera aspect ratios of a device images are distorted
- Steps to reproduce the problem:
1. tap on the input field's camera icon
2. a bottom sheet appears, take a photo
3. repeat, but pull bottum sheet up to full screen
4. take a photo by tapping on the attachment icon -> camera icon (the camera app appears) as reference
5. repeat the procedure in landscape and compare shortcut photo 

- Screenshots:

bottom sheet portrait half:
![portrait_bottom_sheet_half](https://user-images.githubusercontent.com/2614900/90651393-406d2a80-e23d-11ea-97f2-d04d5a31c5c1.jpg)

bottom sheet portrait full screen
![portrait_bottom_sheet_full](https://user-images.githubusercontent.com/2614900/90651398-4105c100-e23d-11ea-886d-66e665def89f.jpg)

camera app portrait full screen
![photo_app_portrait_reference](https://user-images.githubusercontent.com/2614900/90651401-419e5780-e23d-11ea-8df0-d85695bffe41.jpg)

bottom sheet landscape
![bottom_sheet_landscape](https://user-images.githubusercontent.com/2614900/90651403-4236ee00-e23d-11ea-9ae3-6c7c5726f9b5.jpg)

camera app landscape
![photoapp_landscape_reference](https://user-images.githubusercontent.com/2614900/90651407-42cf8480-e23d-11ea-8a86-a4363dcb18b5.jpg)

**Comment by r10s** [comment]
yeah, that would be great to fix! iirc, @angelo-fuchs also has this issue.

**Comment by angelo-fuchs** [comment]
[photo_distortion.zip](https://github.com/deltachat/deltachat-android/files/5104039/photo_distortion.zip)
I've made pictures with my two devices here. An Amazon Fire and a Fairphone 2.

All pictures were undistorted.
I took the pictures from a fixed size (putting the device on top of a bottle, pointing down.), device parallel to the number printout.

**Comment by gerryfrancis** [comment]
I can see a difference on my Fairphone FP2.

Taken with the "Delta Chat cam" (reduced to 50%):
![image](https://user-images.githubusercontent.com/51095533/90804720-e5116a00-e31a-11ea-8b92-a830aa3db905.jpg)


Taken with the Lineage OS cam (as attachment, reduced to 50%):
![image(1)](https://user-images.githubusercontent.com/51095533/90804738-ea6eb480-e31a-11ea-9469-df9159194431.jpg)


It seems that even the live picture with the "Delta Chat cam" does not record the whole area, it is a reduced area of what is possible. This makes the photo blurred, BTW.

**Comment by cyBerta** [comment]
> All pictures were undistorted, so this error seems to be device specific.

yes, the distortion depends on the screen height/width and the supported aspect ratios of the camera.

**Comment by gerryfrancis** [comment]
I believe the "quick cam" cuts the outer area and zooms in just a little bit:

Quick cam (reduced to 50%):
![image_quick](https://user-images.githubusercontent.com/51095533/91442426-1d143200-e872-11ea-9a4d-6469cf866ec4.jpg)

"Full" cam (attachment reduced to 50%):
![image_full](https://user-images.githubusercontent.com/51095533/91442444-230a1300-e872-11ea-8e95-e23f4e85b6ee.jpg)

Regarding quick cam, could it be that zoom is not 1.0, but slightly higher?

**Comment by cyBerta** [comment]
yes scaling is used to fulfill adapt the aspect ratio of the screen to the aspect ratios of the supported camera options

**Comment by AndreaLattmann** [comment]
I confirm that this is the case in 1.36.2 as well

**Comment by adbenitez** [comment]
I can not reproduce this, we should probably just launch the system camera instead of our own limited camera, the system cameras have filters, flash and a lot more features, and this internal custom camera app is meanwhile more limited

**Comment by r10s** [comment]
> we should probably just launch the system camera instead of our own limited camera, the system cameras have filters, flash and a lot more features, and this internal custom camera app is meanwhile more limited

pr that switches default to "system camera": https://github.com/deltachat/deltachat-android/pull/2674
