### ISSUE TITLE
How to speed up compile (for 32bit only)

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#1594]
Building all libs (_ndk-make.sh_) with my environment takes around 40 min !
I see that there are four different libs where each of them needs about 10 min to build.
==> For testing I need only the arm 32 bit version.

Is it possible to simply comment out the unneeded one's from _ndk-make.sh_?

Are there any further dependencies in other project files? I mean, I found all libs in apk file.

   Any help is very welcome as this would save many time while testing :-)

(maybe this issue here belongs to rust core? but _ndk-make.sh_ is in main dir!)

**Comment by r10s** [comment]
did you tried ndk-make-fast.sh?
however, i cannot tell much more that that it exist. i also have compile times > 40 minutes, so you're not doing things wrong :)

**Comment by csb0730** [comment]
No didn't try it and didn't know about it.
But many thanks for your hint. Will try ... and I think it works. Looks good :-)

It seems that @Hocuri had the same idea than me now :-)

(in my good old 1.2.1 that build script doesn't exists)

**Comment by csb0730** [comment]
It runs as expected: build time now 10 min :-)

@r10s Thanks a lot.

**Comment by csb0730** [comment]
After full build apk still has 51MB. Suspect that the non used lib's still existing?
Will check and come back.

**Comment by csb0730** [comment]
Remark:
Build settings without --release in _ndk-make-fast.sh_ produces .a files of a size around 320MB!
With --release option .a files have a size of 25MB!

=> as a first step I added --release

**Comment by csb0730** [comment]
This is the summary:

1. _abiFilders_ needs to be adapted in _build.gradle_ to have only the necessary lib's in apk (for my 32bit architecture):
```
ndk {
    //abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"      <== original
    abiFilters "armeabi-v7a"
}

```
2. _ndk-make-fast.sh_ has to be used for building the core with only the desired architecture.
3. `--release` needs to be added to _ndk-make-fast.sh_ build command to keep resulting lib small for apk

See this updated file for changes:
[ndk-make-fast.sh.txt](https://github.com/deltachat/deltachat-android/files/5120595/ndk-make-fast.sh.txt)

=> The resulting apk has a size around 25MB
