### ISSUE TITLE
"mailto:" links seem insecure

### ISSUE THREAD

**Issue by dumblob** [deltachat/deltachat-android#1595]
I'm concerned with potential issues with `mailto:` links as mentioned on https://www.zdnet.com/article/some-email-clients-are-vulnerable-to-attacks-via-mailto-links/ . Any thoughts?

Partially related to https://github.com/deltachat/deltachat-android/pull/1568 .

**Comment by r10s** [comment]
thanks for the link, very interesting.

however, as far as i can see, Delta Chat does not use the `?attach=` parameter at all, only plain text from the `?subject=` and from the `?body=` parameters [are used as a draft for the text field](https://github.com/deltachat/deltachat-android/blob/a29c9498cff5c44ae990b9480ff5d3a9909e7974/src/org/thoughtcrime/securesms/NewConversationActivity.java#L107).

do you have any concrete concern or attack vector in mind? if so, you can also post that to delta@merlinux.eu

**Comment by dumblob** [comment]
>do you have any concrete concern or attack vector in mind?

No, I don't. I just wanted to point out `mailto:` links are potentially dangerous, so we should keep it in mind.

I'll close this because of lack of actionable items.

**Comment by r10s** [comment]
thanks for coming back to the issue and for taking care!
