### ISSUE TITLE
Too big emojis

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-android#1596]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10

- Delta Chat Version: 1.12.3

- Expected behavior: When I select an emoji I would like it not to be cropped because it is too big

- Actual behavior: Round emojis are cut off on all four corners

- Steps to reproduce the problem: Select a round emoji as per the screenshot. The smileys are correct, but the other round symbols are not.
- Screenshots:

![Screenshot_20200825_102231](https://user-images.githubusercontent.com/63752768/91150709-47b48e00-e6ac-11ea-9f5b-3d57c21ddb3b.jpg)

- Logs:

**Comment by gerryfrancis** [comment]
Confirmed, thanks for reporting.

**Comment by r10s** [comment]
it is also visible for square emojis on the second-last-page: the border is a bit truncated.

**Comment by r10s** [comment]
just had a look at the signal upstream in fact, they have the same bug.

**Comment by Gh0stz0x** [comment]
We can close this bug, now the emojis are better seen and the slightest errors are imperceptible?

**Comment by gerryfrancis** [comment]
@Gh0stz0x The bug is still present.

![deltachat-2023-02-06-001548](https://user-images.githubusercontent.com/51095533/216851538-e6a03a05-755e-4499-9169-762499dadcbe.jpg)

**Comment by AndreaLattmann** [comment]
@gerryfrancis I confirm that this is the case in 1.36.2 as well

**Comment by adbenitez** [comment]
I can not reproduce this in my device, I think it is related to device screen size / resolution / pixel density

closing here until some other dev can reproduce or we get a device where it happens so we can try to fix it

**Comment by r10s** [comment]
also, it is probably only a very minor issue - most emojis are no full circle or rectangle (the yellow faces in the screenshot eg. are fine)
