### ISSUE TITLE
smtp-login failed error

### ISSUE THREAD

**Issue by PaintedEdges** [deltachat/deltachat-android#160]
I'm getting an "smtp-login failed" error when attempting to login Outlook accounts and "invalid credentials" with Google accounts. Oddly enough my Outlook account activity marks every login attempt as successful, Google doesn't list the login attempts in logs. 
Sometimes the "one moment" prompt, after entering credentials, will get stuck at 80% and stay there for minutes before failing, or the app will crash once it gets to 80%.

I can reproduce this on two devices, but they are (almost) identical, excluding user installed apps.
(Android 7.1.2 with Snapdragon 650)

**Comment by WorldCodeCentral** [comment]
Hello, this is probably because your server is/ uses an hserver. This is a known issue: #67 
I tried to see what I can do but I already failed at getting the emulator of Android Studio to run, because of some library ".so" errors iirc. Hit me up if you want to work on that too.

**Comment by r10s** [comment]
the google "invalid credentials" may come from non-activated IMAP or less-secure-apps and for the hMailServer there is issue #67, so i think we can close this one.
