### ISSUE TITLE
Integrated Photo Editor fails to fit some screens

### ISSUE THREAD

**Issue by Atreyu-94** [deltachat/deltachat-android#1604]
- Operating System: Android
- Delta Chat Version: 1.12.4
- Expected behavior: The photo editor should be displayed correctly on the screen
- Actual behavior: It doesn't
- Steps to reproduce the problem: I think this is best explained in the screenshots.
- Screenshots:
We add an image and select attach:
![photo_2020-08-26_13-44-40](https://user-images.githubusercontent.com/39834909/91337955-2a61eb80-e7a2-11ea-8723-3c5ebbaf45ed.jpg)

At first, all buttons are shown correctly, we select the "blur" tool:
![photo_2020-08-26_13-44-44](https://user-images.githubusercontent.com/39834909/91338376-d4da0e80-e7a2-11ea-9177-ce7c110d41cb.jpg)

Then we apply the tool and we get the previous screen:
![photo_2020-08-26_13-44-47](https://user-images.githubusercontent.com/39834909/91339053-e8d24000-e7a3-11ea-904d-c061a63920cc.jpg)

As you can see, the last button was lost, the one that accepts the changes to send the photo:
![photo_2020-08-26_13-44-50](https://user-images.githubusercontent.com/39834909/91339383-6433f180-e7a4-11ea-8727-832581a93277.jpg)

However, when rotating the screen, the missing button is observed again:
![photo_2020-08-26_13-44-54](https://user-images.githubusercontent.com/39834909/91339606-b9700300-e7a4-11ea-8a76-f221d745a60d.jpg)

- Logs: N/A

**Comment by Atreyu-94** [comment]
I think this can be fixed in one of the following ways:
1. Allowing to move the buttons from right to left to select them
2. Placing the button bar in the right side corner, as implemented in the last DeltaLab, greetings!

**Comment by RubenDavidPerezJimenez** [comment]
in some cases it doesn't appear in the screen at any time only when it was rotated
