### ISSUE TITLE
crash when opening a chat with voice messages on a Neptune Pine watch

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#1605]
- Operating System (Linux/Mac/Windows/iOS/Android):Android 4.1.2
- Delta Chat Version:1.12.3 (also nightly 2020-08-26)
- Expected behavior: Selector Chat opens
- Actual behavior: Delta Chat crashes shortly after opening the chat
- Steps to reproduce the problem: Opening a chat with a received voice message as the last message
- Video: https://videobin.org/+1bid/1hwk.html

**Comment by gerryfrancis** [comment]
@icke68746 Thanks for reporting, unfortunately I cannot reproduce this with version 1.12.5, but I am using Android 10.

**Comment by r10s** [comment]
i also tried (on android7), without success, might be releated to android4 and/or some special device @icke68746  maybe you can post a log, so that one can get an idea what is going wrong.

**Comment by icke68746** [comment]
A great program, it is not a big effort to report a bug. It's also nice that you still support old Android versions! Thanks!
It is a mobile phone watch (neptune Pine) from a Canadian manufacturer.
Unfortunately `logcat -v time -s DeltaChat >> /sdcard/filename.log` does not work.
Now that further communication via the desktop program has been established, I can use DeltaChat on my mobile phone again. First he left the chat when I scrolled up to the voice messages, now this does not happen anymore, I can even play both voice messages. From my point of view we can close the case. 

Many greetings from Germany, Mike
                                                        Automatically translated with Deepl.com
--Original--
Ein tolles Programm, da ist es kein großer Aufwand, ein Fehler zu melden. Es ist auch schön, dass ihr noch so alte Androidversionen unterstützt! Danke!
Es handelt sich um eine Handyuhr (neptune Pine) eines kanadischen Herstellers.
Leider funktioniert `logcat -v time -s DeltaChat >> /sdcard/Dateiname.log` nicht.
Nachdem jetzt die weitere Kommunikation über das Desktopprogramm stattfand, kann ich DeltaChat auf dem Handy wieder benutzen. Zuerst verließ er noch den Chat, als ich zu den Sprachnachrichten hochscrollte, jetzt passiert dies nicht mehr, ich kann sogar beide Sprachnachrichten abspielen. Aus meiner Sicht können wir den Fall zu den Akten legen. 
Viele Grüße aus Deutschland, Mike

**Comment by r10s** [comment]
to be honest, i have never tested Delta Chat on a watch :) however, with some chance the crash is also visible on next app start at "settings / advanced / view log".

and thanks for the praise :)

**Comment by icke68746** [comment]
All right. I'll do that.

**Comment by icke68746** [comment]
Hello everybody!
It has appeared again. But I use the nightly version 1.13.0-gplay-debug. I received a voice message, one of them was played, all others not anymore. When trying to play it - I was already in the chat - the screen turned white and Delta Chat crashed. After restarting Delta Chat, it crashed when you visited the chat with the voice messages. This time I saved the log file.
Greeting Mike
[deltachat-log-20200903-160853.txt](https://github.com/deltachat/deltachat-android/files/5171006/deltachat-log-20200903-160853.txt)

**Comment by r10s** [comment]
unfortunately, at a first glance, there is no crash reported in the logfile, for whatever reason.

**Comment by icke68746** [comment]
What else can I do to make the error visible?

**Comment by r10s** [comment]
not sure, normally it should be visible in the log :/

**Comment by gerryfrancis** [comment]
I guess this is the part where things get out of control:

```
09-03 16:07:25.120  4950  5034 E ACodec  : huiy: width = 4096, height = 1455812116
09-03 16:07:25.120  4950  5035 E ACodec  : huiy: width = 4096, height = 1456860692
09-03 16:07:25.150  4950  5035 E ACodec  : Unable to instantiate decoder 'OMX.qcom.audio.decoder.aac'.
09-03 16:07:25.150  4950  5035 E MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
09-03 16:07:25.170  4950  5024 F libc    : Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 5024 (ExoPlayerImplIn)
09-03 16:07:25.170  4950  5042 E ACodec  : huiy: width = 4096, height = 1469586964
09-03 16:07:25.180  4950  5043 E ACodec  : huiy: width = 4096, height = 1470635540
09-03 16:07:25.180  4950  5042 E ACodec  : Unable to instantiate decoder 'OMX.qcom.audio.decoder.aac'.
09-03 16:07:25.180  4950  5042 E MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
09-03 16:07:25.180  4950  5022 F libc    : Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 5022 (ExoPlayerImplIn)
09-03 16:07:25.180  4950  5043 E ACodec  : Unable to instantiate decoder 'OMX.qcom.audio.decoder.aac'.
09-03 16:07:25.180  4950  5043 E MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)
09-03 16:07:25.180  4950  5018 F libc    : Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 5018 (ExoPlayerImplIn)
```

**Comment by gerryfrancis** [comment]
There seems to be a problem with calculating height(s):

```
09-03 16:07:25.120  4950  5034 E ACodec  : huiy: width = 4096, height = 1455812116
09-03 16:07:25.120  4950  5035 E ACodec  : huiy: width = 4096, height = 1456860692
```

1456860692 - 1455812116 = 1048576

```
09-03 16:07:25.170  4950  5042 E ACodec  : huiy: width = 4096, height = 1469586964
09-03 16:07:25.180  4950  5043 E ACodec  : huiy: width = 4096, height = 1470635540
```

1470635540 - 1469586964 = 1048576

@icke68746 Could you tell anything about the resolution(s) of these videos?

**Comment by r10s** [comment]
good catch, @gerryfrancis , i've overseen that (was seeking for a stack trace)

**Comment by gerryfrancis** [comment]
@icke68746 I allowed myself to cut a frame out of your video:

![grafik](https://user-images.githubusercontent.com/51095533/92236007-eadb8380-eeb4-11ea-8d14-0bf89e21844f.png)

The received files have 0:00 length each, so I think their contents were not loaded at all. Does your contact use Delta Chat, too?

**Comment by icke68746** [comment]
Yes, my contact also uses Delta Chat. But I have already received voice messages from the same contact that were playable.

**Comment by gerryfrancis** [comment]
@icke68746 That is a good hint. Could you check if the (non-playable) received voice messages (which are AAC ADTS files) can be played well with another app (e.g. VLC Player) on a different system? Maybe the files have been falsely created.

**Comment by icke68746** [comment]
Yes, they can be played on another system. (Tested with deltachat-desktop under Linux)

**Comment by gerryfrancis** [comment]
@icke68746 Thanks for clarifying. I wonder why playback sometimes works fine and sometimes not on your device. I have read somewhere that if the hardware decoder cannot be initialized for whatever reason, a software decoder should take over. Could you post a log made during a successful playback, please? Maybe we can see some enlightening differences in there.

**Comment by icke68746** [comment]
@gerryfrancis I got a voice message and could play it. It was sent at 20:08 and arrived at 21:10. 
[deltachat-log-20200907-211101.txt](https://github.com/deltachat/deltachat-android/files/5184748/deltachat-log-20200907-211101.txt)

**Comment by gerryfrancis** [comment]
@icke68746 Thanks for coming back so quickly. :+1: I think I have nailed it down to this:

`09-07 21:08:50.760  1908  6134 E MediaCodec: Codec reported an error. (omx error 0x80001003, internalError -2147483648)`

Googling for `omx error 0x80001003` got me here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1307864#c17

It seems that we have to avoid instantiating the decoder multiple times, because some devices do not support it. (Maybe the Neptune Pine is one of them.)
