### ISSUE TITLE
Keyboard not disappearing after contact name edit

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1606]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-08-14).

- Delta Chat Version:
1.12.5.

- Expected behavior:
The keyboard that is used to enter a name of/rename a contact disappears after "OK" is tapped.

- Actual behavior:
The keyboard that is used to enter a name of/rename a contact does not disappear after "OK" is tapped.

- Steps to reproduce the problem:
-- While in a chat, tap on the name of the contact.
-- Tap on the three-dot menu and select "Edit name".
-- Enter/Change the name and tap on "OK". (Result: The keyboard does not disappear, it must be minimized manually.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
also the padding and the initial cursor position is not really nice:

<img width=300 src=https://user-images.githubusercontent.com/9800740/92927104-6309f200-f43d-11ea-9621-a4a3ae4fb0fc.png>
