### ISSUE TITLE
External crypto engine

### ISSUE THREAD

**Issue by Almtesh** [deltachat/deltachat-android#161]
I suggest the idea like that, but I see that K9 uses a external application (OpenKeyChain or AGP) to manage crypto. Wouldn't it be a better idea that internal crypto engine?

**Comment by zoff99** [comment]
OpenKeyChain +1

**Comment by r10s** [comment]
We did not use OpenKeyChain as we wanted the core library to be portable (Android, Windows, Linux, Mac, iOS) - and using different crypto libs on different OS would not be the easiest way to archive this. 

However, Delta Chat does not do the crypto itself but it relies on the external crypto engine OpenSSL (which is wrapped by netpgp). 

Finally, all this is the state of today and subject to change ... esp. OpenPGP.js may become interesting ...

**Comment by genofire** [comment]
It's not possible to overright the core crypto in the Android Version with the external Engine?

**Comment by r10s** [comment]
> It's not possible to overright the core crypto in the Android and Linux Version with the external Engine?

Currently: Not. Delta Chat Core uses C and eg. OpenKeyChain uses Java. To allow overriding we had to add an abstract API layer between, which, of course is generally possible.

The disadvantages of this approach may be harder error finding and harder code reviews. Also porting Delta Chat to a new system may be more complicated.
