### ISSUE TITLE
Classic emails set to 'All' but some messages dropped

### ISSUE THREAD

**Issue by lkblkb** [deltachat/deltachat-android#1636]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 9
- Delta Chat Version: 1.12.5 (f-droid)
- Expected behavior: All mail is shown as messages when Show classic emails is set to All 
- Actual behavior: Some messages are shown, some are dropped
- Steps to reproduce the problem: 
So far I am using gmail and mailbox.org and many emails are not shown in DC. I suspect this is related to #1250 -- it seems some mail is dropped automatically, ex. mail from lists, automated systems ...

This behavior seems misaligned with the DC help docs, which state for example:
>Some people use Delta Chat as a regular email client, and want to use the Inbox folder for their mail, instead of the DeltaChat folder.

I am one of these weirdos looking to replace my email client, and I'd love to have emails from newsletters, lists, etc., be threaded by sender -- effectively what DC does. 

Is it possible to have a 4th setting which truly shows All mail, 100%? If not, I would also be happy to have current functionality be described in the FAQ, so users can know what to expect when they set classic email handling to 'All'. Also happy to volunteer to write said FAQ entry :D

**Comment by Hocuri** [comment]
Mailing lists / newsletters are dropped currently, which is not nice, I agree. As we are going to change this, I do not think it is worth it to write an FAQ entry now. But of course we will need one as soon as mailing lists are shown.

I will close this issue as we already have another tracking issue for this in the core repo.
