### ISSUE TITLE
add ImgBot

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1638]
maybe it makes sense to subscribe to https://imgbot.net for automatic image optimizations; it is free for open source projects.

the bot does a pr with the optimized images iiuc.

@TPS ran the bot once at https://github.com/deltachat/deltachat-android/pull/1632 , saving 100k apk size.

we are currently not adding images that often, so, savings will be not that huge. but, otoh, if it is easy to set up and does not need much maintanance, maybe give it a try.

**Comment by r10s** [comment]
i added the bot, let's see what will happen.

i was a bit irritated by the permission "Read and write access to code and pull requests" (the "write" here), however, gone through some comparable bots we are already using, this seems to be usual,  eg. "Dependabot Preview" in core request the same permissions.

**Comment by TPS** [comment]
I agree with you, @r10s : the GitHub permissions for code & PRs should be handled independently.  OTOH, Dependebot _can_ merge certain PRs _automatically **if so configured**_.

**Comment by TPS** [comment]
Also, if you wish to be more set-&-forget re: ImgBot, perhaps think of creating `.imgbotconfig` in the root of the repos here.  [I use](https://www.github.com/TPS/SortExceptions/tree/master/.imgbotconfig)
```
{
    "compressWiki": "true"
    "minKBReduced": null
}
```

**Comment by r10s** [comment]
thanks for the link, @TPS, however, in our case, defaults seem to be fine (we do not have a wiki and open a pr with at least 10kb shrinking looks also as a good idea to me)
