### ISSUE TITLE
status-bar Notifications do not disappear when read on another device

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#1646]
this is happening for a long time: when i read messages on desktop, and enter Android Delta Chat list screen later, messages are correctly "not fresh", i.e. read.  However, the android-status-notification are not (all?) removed automatically.  I have to go to them and swipe them away or re-enter the chat.   The android-statusbar-notification even remain if i enter the respective chat manually --- so it seems that in general statusbar-notifications are, once there, not updated-removed other than going to them.

**Comment by r10s** [comment]
> I have to go to them and swipe them away or re-enter the chat. The android-statusbar-notification even remain if i enter the respective chat manually

not totally clear what you mean here - does re-entering the chat manually work for you or not?

the notifications for a single chat should go away when this chat is entered.

in general, notifications should be removed when the corresponding chat is entered (only notifications from that chat, however), if this is not the case, this is a bug.

for the rest - yip, notifications are not removed when the corresponding message is read on another device. this is missing. probably hard to get that in "real time", there is no event for that and afaik, core does not really know this.

however, what android could do probably easily is to check the notifications whenever it updates/removes the unread-badge for a chat (typically, this is done when the chatlist is entered).

**Comment by hpk42** [comment]
On Thu, Oct 08, 2020 at 03:16 -0700, bjoern wrote:
> > I have to go to them and swipe them away or re-enter the chat. The android-statusbar-notification even remain if i enter the respective chat manually
> 
> not totally clear what you mean here - does re-entering the chat manually work for you or not?
> the notifications for a single chat should go away when this chat is entered.

re-entering the chat does remove the status-bar notification. 

> for the rest - yip, notifications are not removed when the corresponding message is read on another device. this is missing. probably hard to get that in "real time", there is no event for that and afaik, core does not really know this.

it doesn't need to be "realtime" IMHO. 
 
> however, what android could do probably easily is to check the notifications whenever it updates/removes the unread-badge for a chat (typically, this is done when the chatlist is entered).

If it's not too much effort and not much runtime-overhead that sounds great!

**Comment by r10s** [comment]
okay, i got it now. the missing "badge" was more a lucky bug at [setStatusIcons](https://github.com/deltachat/deltachat-android/blob/1fb45147819d62783243cb682106418aca4d5656/src/org/thoughtcrime/securesms/ConversationListItem.java#L268) - if the last message of a chat is seen, the chatlist treats it as an _outgoing_ message - hiding badge counter.

i was also wondering, why sometimes the message-summary was shown in bold where there is no badge counter - this was meant to be for unread messages only.

this situation can only happen when there was an _answer_ to a chat from another device - in that case, the badge disappears by accident.

however, this makes some sense - if the state of the last message in a chat is an outgoing one (maybe from another device), one should treat the other messages as being noticed. however, that should be done in the core, just not showing the badge results in other issues (eg. unread-mark on app-icon does not match chatlist view), i would fix that on android.

but removing the notifications should be safe, we can just do that.

i will do a thing.
