### ISSUE TITLE
add "shield" icons

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1648]
- create the icons ... 🛡️

- show big shield-icon above protect-info-message

- show big unshield-icon above unprotect-info-message

- moreover, the small chat-verified-checkmark should be replaced by a small shield of roughy the same color & design as the big one.

this all should be done after the core with the protection-function is already shipped so that this aligns with an protect/unprotect switch.

once this is done on android, corresponding reminder-issues should be created or the other uis.

**Comment by r10s** [comment]
#1669 did some steps, we can revive parts of this pr.

for the icon: https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f6e1.svg might be a good start, the idea is to show it in blue/white color, however.

**Comment by hpk42** [comment]
On Sun, Oct 18, 2020 at 08:33 -0700, bjoern wrote:
> #1669 did some steps, we can revive parts of this pr.
> 
> for the icon: https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f6e1.svg might be a good start, the idea is to show it in blue/white color, however.

nice :)

**Comment by r10s** [comment]
closing this as this is not finally decided in detail an no directly actionable item currently.
