### ISSUE TITLE
add some padding around the remove-reply button

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1653]
the remove-reply-button (the "x") is hard to tap, there should be some padding around it (the visible size is okay)

**Comment by r10s** [comment]
even better is the suggestion of @Hocuri in "Testing Delta Chat" group, just move the "x" right:

- easier to see
- make clear, the whole quote gets deleted, not only the attachment
- the "x" can have more padding and will be easier to tap

<img width=400 src=https://user-images.githubusercontent.com/9800740/95844364-246f9c00-0d49-11eb-8faa-2afd301e1ff9.jpg>

<img width=400 src=https://user-images.githubusercontent.com/9800740/95844370-25a0c900-0d49-11eb-9051-f8a77827e7e8.jpg>

**Comment by Hocuri** [comment]
<img width=400 src=https://user-images.githubusercontent.com/9800740/95844364-246f9c00-0d49-11eb-8faa-2afd301e1ff9.jpg>
The two circles seem to interfere a little IMHO (before they were above each other).

**Comment by r10s** [comment]
> The two circles seem to interfere a little IMHO (before they were above each other).

nah, i think that's fine. at least much better than before :)

maybe we can move the file-icon closer to the quote - also later, it is typically shown closer together:

![alt](https://user-images.githubusercontent.com/9800740/95875134-f94d7280-0d71-11eb-8552-3b0661fd6524.png)

maybe we can even remove it completely (for voice-messages we do not have them)

but as said, it is already an improvement with your fix, no need to target that directly.
