### ISSUE TITLE
System warning: "Diese App verlangsamt Ihr Gerät, 100 Fehler pro Woche"

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#166]
DC was used and no issue was detected, but after a week, I got this error-message. It is just irritating, because DC seemed to be running fine. DC August version, Android 5

(The screenshot upload failed: Something went really wrong, and we cant process that file).

**Comment by r10s** [comment]
Hm, I've seen these messages before for another app on some device (don't remember which app/device) - however, this seemed to be an error in the system ...

**Comment by kollokollo** [comment]
The most recent version of Delta-Chat has not produced this anymore. It seems to fixed now. Issue might be closed.

**Comment by r10s** [comment]
Okay - I really like to click on the "close" button :)
