### ISSUE TITLE
"Saved messages" displayed above pinned chats after forwarding

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1661]
When you forward a message, "saved messages" chat is sorted above other chats. After forwarding, if you go back, you are still presented with a chatlist where "saved messages" is at the top. However, when a new message arrives, it is resorted correctly.

**Comment by r10s** [comment]
there was a recent change wrt forwarding, https://github.com/deltachat/deltachat-android/pull/1651, so i am not astonished about bugs here, however, i tried some combinations for forwarding and abort-forwarding - but i am failing to reproduce that.

can you please file some more details?

**Comment by link2xt** [comment]
It works after rebuilding the latest master.

**Comment by r10s** [comment]
thanks for re-checking :)
