### ISSUE TITLE
Protecting backups/imports + custom target option

### ISSUE THREAD

**Issue by LeeteqXV** [deltachat/deltachat-android#1685]
- Operating System: Android
- Delta Chat Version: 1.12.5
- Expected behavior: Ask for password on import (and first choose backup folder)
- Actual behavior: Importing any backup without security, worse: from Downloads
- Steps to reproduce the problem: Normal backup/import

1. Backups really need to be protected by a backup-specific password. (Manually set by the user at the time of the backup, and not the account login password. It is important to ask for the login password also, but that is only to authenticate doing the backup, not to protect the resulting backup file...)

2a. On Android, the Downloads folder is the worst location for an unprotected backup; DC should let the user choose target folder and thus also the source folder for imports.

2b. On Android, there is a difference between "save as/to" and "send to" or "share to". Various Encryption software that offers encrypted containers on Android, use the "Send to/Share to" feature, which is technically different from "save", and different software options appear in those alternatives.

It would be great if we could optionally use "share backup to", in order to trigger those encryption features (and even others, such as save directly to a cloud service instead of on the device) which will let us store the backup directly into an encrypted location without touching any "open" folders that are available to other software. (The Downloads folder is the absolutely worst location I can imagine on Android.)

**Comment by hpk42** [comment]
We are not using issue trackers for improvement discussions unless there is someone involved who is committing of doing it. 
Could you repost to https://support.delta.chat ? Thanks!
