### ISSUE TITLE
Autocrypt only available on the same device?

### ISSUE THREAD

**Issue by LeeteqXV** [deltachat/deltachat-android#1686]
- Operating System: Android
- Delta Chat Version: 1.12.5
- Expected behavior: Other device(s) using the same account/login should get to open the Autocrypt message in "Saved messages"
- Actual behavior: Only the device that generates the Autocrypt message can subsequently see it.
- Steps to reproduce the problem: Normal autocrypt trigger.

Is there a technical reason behind this, or is it a bug?
When logging into the same account without doing an import, should it not be possible to use Autocrypt to synch those two installations between two devices?

If doing an import, will even the Autocrypt situation/need occur?
Logically (to me) this seems that it is more related to not having done an import in the first place, and will not be needed if doing export/import.
So, since there is a Autocrypt feature; I expect to be able to fix such a situation when import has not been used.

**Comment by Hocuri** [comment]
I don't know if that's the case, but maybe you have to enable "Send copy to self" in the advanced settings before an autocrypt message can arrive. If yes, maybe we should change this.

But at some point we will have to implement a better way to setup a second device anyway; for now, the best way to setup a second device is importing a backup.

**Comment by hpk42** [comment]
I don't understand -- are you saying that when you send an autocrypt setup message, that the other device doesn't react at all?  Or that it reacts/offers to import but does not show it in saved messages? 

@hocuri I doubt it has to do with bcc-self setting as ASM is expressly a self-sent messages independent of this setting.

**Comment by AndreazLattmann** [comment]
I can tell you my experience: for the first time last week my e-mail provider blocked all autocrypt messages.
Try to see if your provider blocks them.
However the best method is the back-up (That's the way I got around the problem with my provider)

**Comment by hpk42** [comment]
On Fri, Oct 23, 2020 at 12:00 -0700, Andreas Lattmann wrote:
> I can tell you my experience: for the first time last week my e-mail provider blocked all autocrypt messages.

just to be sure, you mean Autocrypt Setup Messages (the syncing message), right? 
Were they blocked or just moved to Spam?

**Comment by AndreazLattmann** [comment]
Yes I mean just that. The Autocrypt Setup Messages were blocked and after 10 attempts they blocked my account.

**Comment by LeeteqXV** [comment]
Send-copy-to-self has been enabled all along. Not sure that that means or if it is relevant here.

Here is my experience, just from the point of logic, in "workflow" order:

1. Added a new account to a tablet in addition to adding it to the main Android phone. The NEW account is on another domain which I am about to switch TO. I want to add the new account to the existing groups, and then kick out the original account, so that I keep the groups, memberships and messages.

2. Receiving "[This message cannot be decrypted - It might already help to simply reply to this message and..." ... "In case you re-installed Delta Chat or another email program on this or another device you may want to send an Autocrypt Setup Message from THERE."]" in various groups and 1-on-1 chats.

3. Opening the new account on both the tablet and phone, going to Advanced settings on the TABLET and trigging the Autocrypt function from there, receiving the numbers visibly.

4. Expecting that there will turn up a clickable message about Autocrypt on the PHONE, so I can fill in the numbers. But no. After waiting in vain, I close both Deltachats, re-enter into the same account on both, and only on the SOURCE (TABLET) there is an Autocrypt message ("to myself"), but not on the phone, where I need it... (this is the same account/email/password).

Leaving me confused and puzzled; is this actually a bug, or am I missing some logic here?

5. Visiting all the existing groups with 3 member accounts on both the tablet, phone and from one of the other members' phone; adding my new account, and removing the old account from all groups. Then many similar messages happen meanwhile, same "cannot decrypt" issue, but now it helps to just reply once from both sides in each group, and then that part is resolved for that group.

6. But: Why is the users stuck on EACH (all) groups when one of the members is clearly a) kicking it out, and b) A system message informing/confirming about who has been kicked out is sent to all members, yet on all member's accounts that same "kicked-out" user account needs to be manually kicked out from that same group on all members devices? It does not synch at all...

7. Sometimes it is not enough to reply to solve the problem, but then another trick works: to to the main DC screen, use the plus sign to "add a contact", add that contact "again" from the EXISTING LIST that is displayed there, send a chat message, receive a reply, and then test in each group; and voila!, now it decrypts correctly...

Another confusion: There is not any "contacts" list in DC, as far as I can tell/see, but that list of available users (all members of existing groups, I assume(?)), certainly gives the impression of being some kind of "contacts list". Add to that confusion that I cannot tell the difference AFTERWARDS; who is "already a contact", and who is only in the available list behind the plus sign...

I am still trying to get past all the messages in all the groups from all the accounts on all the devices (.....), so I am unsure if I have solved it all, or if some problem persist. It may be that I need to kick out 1 user and export/import it again on 1 device to resolve the last bit, but not sure yet. Completely bewildered and overwhelmed.

However, once the GUI and logic has been smoothened somewhat more, DC seems like the clear choice of such an app, if only we can get password protected backups. I like DC a lot for its basic functionality, and understand that we might have to expect temporary glitches such as this after enabling/getting into multi-account territory (which is what maked DC the preferred messanger; without that I would not use DC at all).

**Comment by LeeteqXV** [comment]
[Summary: the main trick is in #5: kick out the old account from each group on each device on each member account..., and then the messages start to decrypt: That old account was meanwhile on a domain that was cancelled, so DC was not able to send message to that accont, and then not to communicate at all with that group before that account was removed. Then that person/device could send messages, but potentially only with the same problem of not decrypting, until the receiver also kicked out that account on his/her device before replying. In this context, the error is not explaining or giving any hint of what might be the underlying problem)

**Comment by LeeteqXV** [comment]
(in this case, there were roughly 20-30 groups with 3-8 member accounts in each, with some members using the same account on more than one device.., so it became a daunting task to tidy it all up...)

**Comment by LeeteqXV** [comment]
Follow-up: Not completely verified this yet, but it SEEMS that when all groups display all messages ok for all members, then if I send a new message from one of the same accounts on another device, then the same decryption error occurs again for that account, trigging the whole round again if I want to see all groups for that user on that device  (This is maybe entirely logical, if indeed what I initially did was to add the initial second account just with the password instead of exporting/importing it, which I honestly dont remember for that particular account..). If this then plays out to cancelling all efforts on the other device for the same account everytime I send from it on another device, and if it cannot be fixed using the Autocrypt feature (which does not send it to the same account on the other device, which I need), then I guess I have to delete that lastly added account and to export/import. This part was daunting before, as I had so many groups etc, and was unclear of some other issues/effects here, but now that I have tidied all on one side for all groups, then perhaps this is the only thing to do.

Awaiting feedback from here in particular on the Autocrypt problem first.

**Comment by LeeteqXV** [comment]
I also want to understand the exact cause/effect(s) of the message "Changed setup for [user@...]"; Does that occur when the SECOND device for a given user is sending a new message in a group, while not having being imported, but added through login? Is that what triggers decryption errors on subsequent group messages FROM that user on other devices? And (have not had time to check yet); is that then happening across the board for all users receiving those messages, or only for "oneself" on a device using the same account?

There are several variables here which mudders the waters a bit.

**Comment by LeeteqXV** [comment]
OH, and a missing feature that would make all this trouble-shooting far easier:

If only the Avatar of the current user was shown beside the DeltaChat title in the main screen, so that I instantly can see which user I am active with on each device, without having to go to the settings page to check (or the switch user page) a million times during all this tidying. Sigh.

**Comment by adbenitez** [comment]
I think the title of this issue is misleading, this is actually a feature request: **account migration** user wants to switch from `a1@example.com` to `a2@example.org` migrating all groups from the first account to the second address and migrating the autocrypt key to the second account.

So this seems not to be a bug related to Autocrypt Setup Message, but a feature request to migrate autocrypt key to a different account? in that case you can migrate the key using the "export keys" option in advanced settings, on the other hand, @LeeteqXV if you want to request a feature to migrate a full account with chats, etc. to another address, please close this issue and open a feature request in the forum: https://support.delta.chat, the issue tracker is used only for bug reports, feature requests are discussed with the community in the Delta Chat forum

**Comment by Hocuri** [comment]
> if you want to request a feature to migrate a full account with chats, etc. to another address

This is actually being worked on in the AEAP (Automatic email address porting) project https://github.com/orgs/deltachat/projects/38

So I suggest to close this issue as it's already being worked on.
