### ISSUE TITLE
Delete from server not performed if not all parts are deleted

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-android#169]
**Version:** Delta Chat 0.9.4

When receiving (mail) messages from other MUA (not DC), which e.g. contains several attachments, the mail gets split into several "short messages" in the database (see mrmailbox.c in deltachat-core).

In the GUI I selected one of the attachments and clicked the _Delete_ button.
A message appeared:
`Delete 1 message? The message will also be deleted from the server.`

The attachment was deleted locally, but not the mail message on the server.

A logcat entry was written by deltachat-core:
`T2: The message is deleted from the server when all message are deleted.`

This response is not forwarded to the GUI.
Can this be added?
Would it be possible to mark those mails messages by e.g. drawing a frame around all "short messages" that compound one mail?

**Comment by r10s** [comment]
Well, this is a weird problem. I do not believe the user understands a message "The message is deleted from the server when all message are deleted." just after the message is deleted. 

Technically, for now, I do not want to make things too complicated which also makes the inital porting to different operating systems more difficult.

Maybe the best way would be to change the message, maybe sth. like " Delete 1 message? Messages are deleted from the server when all parts are deleted."

@Ampli-fier can you please contact be at r10s@b44t.com - I have a private question :)

**Comment by testbird** [comment]
Pressing delete could automatically mark all message parts of the email, and let confirmation dialog say massage consists of x parts all contained a single email that can only deleted at once.

**Comment by r10s** [comment]
i'm closing this for now here; the new forum at https://support.delta.chat is the better place for feature requests and discussions.

not sure if there is a better solution than the existing one, which, obviously has its drawbacks. but all other solutions that come into my mind have even more drawbacks - coming in sort of complexity, maintainability, ux.
