### ISSUE TITLE
Malformed "From" line in DeltaChat messages

### ISSUE THREAD

**Issue by floe** [deltachat/deltachat-android#1698]
- Operating System: Android
- Delta Chat Version: 1.12.5
- Expected behavior: Create properly formatted mail messages
- Actual behavior: "From" line is malformatted

While writing a `maildrop` filter for my mail server to sort DeltaChat messages into their own folder, I noticed that the headers seem to be not RFC compliant, especially the "From" header on the very first line:

```
From floe-deltachat@butterbrot.org  Fri Oct 30 11:05:30 2020
Return-Path: <floe-deltachat@butterbrot.org>
X-Original-To: floe-deltachat@butterbrot.org
Delivered-To: floe-deltachat@butterbrot.org
Received: from localhost (...)
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by butterbrot.org (Postfix) with ESMTPSA id 4CE594AE016B;
	Fri, 30 Oct 2020 11:05:30 +0100 (CET)
Content-Type: text/plain; charset=utf-8
Chat-Disposition-Notification-To: floe-deltachat@butterbrot.org
Subject: =?utf-8?q?Re=3A_Message_from_floe-deltachat=40butterbrot=2Eorg?=
MIME-Version: 1.0
References: <Mr.6qrSKrGNRSa.AYt4Q2LxYRN@butterbrot.org>
	<Mr.IfxUtm3Ck3r.hCYkcZoVSmI@butterbrot.org>
In-Reply-To: <Mr.IfxUtm3Ck3r.hCYkcZoVSmI@butterbrot.org>
Date: Fri, 30 Oct 2020 10:05:28 +0000
Chat-Version: 1.0
Message-ID: <Mr.FUnlY_nihBy.tqHoOwcNtiI@butterbrot.org>
To: Florian Echtler <floech@cs.aau.dk>
From:  <floe-deltachat@butterbrot.org>

[...]
```

There is a correctly-formatted From: line right before the message body, but the one at the very top of the message seems broken (and does confuse `maildrop`).

**Comment by r10s** [comment]
that's weird. are you sure, the line is really added by Delta Chat?

**Comment by floe** [comment]
I wouldn't know where else to look... "regular" mail messages don't have that weird header, I just checked again.

**Comment by r10s** [comment]
can you try over with another provider? just to make sure, that the provider is not the cause of the issue.

**Comment by link2xt** [comment]
This `From` line is not generated by Delta Chat, it is above `Return-Path`, `Received` and other headers added by the mail server.

DC generates correct envelope From at https://github.com/async-email/async-smtp/blob/22b49409c49d32c4d1056c0ebf3a3cb92fafd83b/src/smtp/commands.rs#L65

I think it is generated by Postfix. See http://www.postfix.org/pipe.8.html: `flags=F` does this:
> Prepend a "**From** sender time_stamp" envelope header to the message  content.  This is expected by, for example, **UUCP** software.

Refer to [Postfix + Maildrop Howto](http://www.postfix.org/MAILDROP_README.html), it says you should use `flags=ODRhu` (no `F` flag).
