### ISSUE TITLE
forward might end activity

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1704]
forward to saved-messages sometimes removes all activities and closes app.

the app is not crashing or so, just the activity is ended.

i could reproduce that currently only on my android 4.4 testphone.

**Comment by csb0730** [comment]
Can confirm this.

just after forwarding the target chat is shown (not only at saved-messages). when I then press the _back button_ then all activities are closed. DC is not returning to main activity or last chat selected.

**Comment by r10s** [comment]
thanks for confirming! we will fix that before 1.14 is released to the stores.

**Comment by r10s** [comment]
this issue seems to be older, eg. it is also in the 1.12.

it can be reproduced even simpler: 

- tap forward-message
- then the "back" key (either in the action bar or the system key) 
- app will close

also, when really forwarding, the chatlist is not updated.

maybe related to `launchMode="singleTask"` we're using, might be the behavior changed at some point.

as this is a pretty old issue and no regression, i remove the blocker tag, however, it should be fixed anyway soon.

**Comment by csb0730** [comment]
I'm using code base of 1.2.x ... much older than 1.12 ;-)

**Comment by r10s** [comment]
> I'm using code base of 1.2.x ... much older than 1.12 ;-)

and 1.2.x also already has this issue?

**Comment by r10s** [comment]
that `A.chatlist -> B.chat -> A.forward -> back` exists the app with launchMode=singleTask seems to be logical to me, as `A.forward` just reuses `A.chatlist`- and removes things on top of that (`B.chat` in this case)

what i do not understand: why does this work on newer androids?

**Comment by r10s** [comment]
> what i do not understand: why does this work on newer androids?

it works because startActivityForResult() behaves differently on newer androids, cmp. https://github.com/deltachat/deltachat-android/pull/1412 

so, we have several solutions to solve that:

- give up singleTask thing, that would require us to track that no more than one Chatlist is present in the activity stack, also may have other side effects. does not sound tempting to me.

- start the following activity manually for android4 - that may be some code / some situations to think of, however, the advantage that we would not run into danger making things worse for non-android4

- maybe also a separate FowardActivity is a solution, similar to ShareActivity, that would not alter the stack. FowardActivity can maybe be an aliased activity, that has to be checked out.

however, i just tried delta chat 1.0 (from beginning of this year - setup has becom 30x faster on that device, btw), that also has the bug in, so it is no regression and this issue should not block upcoming 1.14 release.

**Comment by Hocuri** [comment]
> setup has becom 30x faster on that device, btw

:tada::tada::tada::tada:

>     * start the following activity manually for android4 - that may be some code / some situations to think of, however, the advantage that we would not run into danger making things worse for non-android4

My guess would also be that that's the easiest solution with fewest possible problems (although it would not be the first time I am totally surprised how easy or hard a solution is to do)

**Comment by adbenitez** [comment]
this is happening 100% of the time after I upgraded to Android 11, IMHO opinion this is a blocker, and should be targeted before we release an app or mention in blog posts about our "target api level 30" efforts because the app feels quite buggy on Android 11 "the app closes after forwarding"

**Comment by Hocuri** [comment]
AFAIK usually we only flag issues as "blocker" if things worked in the last version (regressions). But I agree that this should have high priority. I can't do anything about it though because so far I failed to reproduce this problem (I don't have a physical Android 11 device and in the emulator things work fine). And also I'm currently still busy with Api30 itself.

I'd be happy to help you when you are poking on this issue though - be it just reading what you found/tried so far and give my perspective.

**Comment by adbenitez** [comment]
other devs having similar issues:

https://stackoverflow.com/questions/66504667/activity-launch-mode-singleinstance-works-unnormal-in-android-11

**Comment by r10s** [comment]
nb: in addition to the launchMode in the xml, there is also the flag FLAG_ACTIVITY_CLEAR_TOP that is set programatically.

**Comment by Hocuri** [comment]
Probably try removing the `android:launchMode="singleTask"` in the manifest and make sure that `FLAG_ACTIVITY_CLEAR_TOP` is set whenever we want only a single activity to be on the stack

**Comment by cyBerta** [comment]
> Probably try removing the `android:launchMode="singleTask"` in the manifest and make sure that `FLAG_ACTIVITY_CLEAR_TOP` is set whenever we want only a single activity to be on the stack

IIRC, the flag `FLAG_ACTIVITY_CLEAR_TOP` is related to a task, it assures that only that one instance of that Activity lives within that task, and is reused while removing all other activites on top of it's latest position. However, for example, when starting activities from services and probably also from static class broadcast receivers you need to add the `ACTIVITY_NEW_TASK` flag to an intent in order to show the intended activity. In that case, two instances of the same Activity would exist in two tasks.
The behavior is thus not the same and we would have to check thoroughly if the chat list is always started from another activity within the same task.

**Comment by r10s** [comment]
well, that seems to be a bit more complicated, including the chance to break things.

also,  the issue is no regression and only affects very new (and very old :) devices

all in all, it may be wise to target that directly after 1.24.

**Comment by adbenitez** [comment]
should this be added to stabilization project? it is quite annoying in Android 10+
