### ISSUE TITLE
maybe switch to debug symbols as recommended by gplay

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1715]
not sure, if this is useful/doable, just want to mention that the play store issues a hint saying:

_"This APK contains native code, and you've not uploaded debug symbols. We recommend you upload a symbol file to make your crashes and ANRs easier to analyze and debug. [Learn More](https://developer.android.com/studio/build/shrink-code#native-crash-support)"_

**Comment by Hocuri** [comment]
Duplicate of #1716 :joy:

**Comment by r10s** [comment]
no idea why this was created two times. thanks for closing.
