### ISSUE TITLE
check gplay-recommendation wrt debug-symbols

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1716]
not sure, if this is useful/doable, just want to mention that the play store issues a hint saying:

_"This APK contains native code, and you've not uploaded debug symbols. We recommend you upload a symbol file to make your crashes and ANRs easier to analyze and debug. [Learn More](https://developer.android.com/studio/build/shrink-code#native-crash-support)"_

**Comment by Hocuri** [comment]
Are there even any native stack traces (i.e. Rust panics/segmentation faults/...) shown in Android Vitals?

**Comment by r10s** [comment]
there was sth. in the past, we'll see how the new version performs.

however, we are currently saving the symbols together, so we should be able to get these information anyway, see https://github.com/deltachat/deltachat-android/issues/1437, however it was just not really used in the last months, so not sure how practical this really is.

i am closing this for now, there is no directly actionable item. i filed it mainly to have that filed somewhere :)
