### ISSUE TITLE
Message hidden by the bar

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1717]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.14.1
- Expected behavior: When I send a message, I would like it to be visible
- Actual behavior: Sometimes when I send a message, the message stays hidden in the lower compose bar.
- Steps to reproduce the problem: Send a short message like "Hello"
- Screenshots:
- Logs:

**Comment by r10s** [comment]
> Steps to reproduce the problem: Send a short message like "Hello"

i just tried that (on android5 and android10, both in emulator), i did could not reproduce the issue, so there are probably some more preconditions to fulfill to reproduce the bug. or it happens on some devices only.

**Comment by AndreazLattmann** [comment]
@r10s It is actually a difficult bug to reproduce and it only happens to me on my Huawei. On other devices like, Samsung and Xiaomi it doesn't happen to me. I need to figure out if it's a DC bug or a problem with my device. 🤔

**Comment by AndreazLattmann** [comment]
Could it be a problem with the db? 🤔
I have now reinstalled Delta Chat, if I get the bug again I reopen the issue. 
For now I close it.
Thanks for everything r10s! 😄

**Comment by r10s** [comment]
would be interesting if it happens on "all" Huawei devices, though.

**Comment by webratte** [comment]
For me (Huawei nova) it works fine.
See also my screenshots

**Comment by r10s** [comment]
@webratte thanks for re-checking!
