### ISSUE TITLE
The chat does not always open on the first unread message

### ISSUE THREAD

**Issue by AndreazLattmann** [deltachat/deltachat-android#1718]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.14.0
- Expected behavior: When I open a chat I would like to see the first unread message with the message "x new message"
- Actual behavior: When I open a chat, it often opens in the center of the unread message list and there is no "x new message" message.
- Steps to reproduce the problem:
- Screenshots:
- Logs:

[deltachat-log-20201107-194652.txt](https://github.com/deltachat/deltachat-android/files/5505285/deltachat-log-20201107-194652.txt)

I couldn't catch the bug, I hope you see something in the log.
In the meantime I try to recreate it.

**Comment by gerryfrancis** [comment]
@AndreazLattmann There might be a problem either with the query or the database:

```
11-07 19:46:30.316 13721 23381 I DeltaChat: src/job.rs:1190: loading job for Imap-thread
11-07 19:46:30.316 13721 23381 I DeltaChat: src/job.rs:1007: Inbox-job #497931, action MoveMsg started...
11-07 19:46:30.316 13721 23381 I DeltaChat: src/job.rs:1076: Inbox begin immediate try 0 of job #497931, action MoveMsg
11-07 19:46:30.317 13721 23381 I DeltaChat: src/job.rs:1100: Finished immediate try 0 of job #497931, action MoveMsg
11-07 19:46:30.317 13721 23381 W DeltaChat: src/job.rs:1052: Inbox removes job #497931, action MoveMsg as it failed with error Sqlite Error: QueryReturnedNoRows
11-07 19:46:30.317 13721 23381 W DeltaChat: 
11-07 19:46:30.317 13721 23381 W DeltaChat: Caused by:
11-07 19:46:30.317 13721 23381 W DeltaChat:     Query returned no rows
11-07 19:46:30.317 13721 23381 I DeltaChat: src/job.rs:1190: loading job for Imap-thread
```

**Comment by AndreazLattmann** [comment]
I try to uninstall DC and reinstall it.
Let's see if I can reproduce the bug or is it a corrupt db problem.  
Thanks @gerryfrancis always very kind! 😄

**Comment by AndreazLattmann** [comment]
For now, I close the issue. I think it is a question of corrupted db. In the meantime, I try to reproduce the 3 bugs I am hunting (if they are such). 😄

**Comment by gerryfrancis** [comment]
> always very kind!

You are welcome, always! :+1:
