### ISSUE TITLE
PDF in attachment cannot be opened

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#172]
If there is a PDF file in attachment it is shown in a separate message in DC. But if I press on the link in this separate message PDF file is not opened. Instead a failure message appears that file is not found.

See example:
![screenshot_2017-10-01_dc_pdf_not_opened](https://user-images.githubusercontent.com/30560716/31059675-8c9e4a26-a706-11e7-82ef-d01af1302262.png)

**Comment by Ampli-fier** [comment]
Can you try with a shorter filename?

**Comment by r10s** [comment]
A problem with the spaces in the name?
Does a PDF with a short name as "test.pdf" work on your device?

**Comment by csb0730** [comment]
Yes, unfortunately You cannot see in example, but in fact the filename has a space in name!
Test shows that short and simple filename works fine.
So it can be fixed now?

**Comment by r10s** [comment]
And a simple space messes up things? Can you re-check this? (I'm quite sure I've seen PDFs with spaces in their names here...)

**Comment by csb0730** [comment]
Hi Björn,
I cannot reproduce it when i'm sending a mail to myself even with original filename! There seems to be a relation with original sending MUA. I requested a new reply from it.

But here an extract from original email source which produced the issue (original filename replaced).
Maybe this gives a hint what happens?

------------------ start excerpt -------------------------
------=_Part_3142_927388164.1506843730486
Content-Type: application/pdf; name="SZ_Xxxxxx Xxxxxxxxxxxxxx_ Xxxxxxxxxäxxx xx Xxx_27.09.2017.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="SZ_Xxxxxx Xxxxxxxxxxxxxx_ Xxxxxxxxxäxxx xx Xxx_27.09.2017.pdf"

JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9DcmVhdG9yIChNb3ppbGxhLzUuMCBcKFdpbmRvd3Mg
TlQgMTAuMDsgV2
...
---------------- end excerpt ---------------

**Comment by csb0730** [comment]
Even german umlaut ä has no effect!

**Comment by r10s** [comment]
Maybe you can reproduce the error with a mail and a PDF which you can send me as a raw mail? (eg. .eml - "save source as" in Thunderbird)
This would make it much easier for me to find out what is going wrong. Maybe it has nothing to do with PDF at all - but only with some weird header ...

**Comment by csb0730** [comment]
I'll send You some raw mails by separate mail.
What I found by comparing source of original mails is simply the difference in filename!
All headers and mail parts are identical, but ...
  a test with same non working filename from Thunderbird works! Encoding of original mails and Thunderbird mail is different.

**Comment by r10s** [comment]
Thank you very much, I got the mail and I will check this ASAP :)

**Comment by r10s** [comment]
Okay, I figured out the problem; it is a badly encoded filename, ISO-something where it should be UTF-8. While Delta Chat seems to have no big problem with these names, the operating system does and cannot find the file to display.
We will fix the names to fix the issue.

With correctly encocded filenames, neither Delta nor the OS has problems - even when using Umlaute or spaces.

**Comment by r10s** [comment]
Fixed, see https://github.com/deltachat/deltachat-core/commit/4462e31297082b09fe6396338e413fff8fd24e17

The fix will be available in v0.9.6 and later.
