### ISSUE TITLE
When returning to delta chat once visited an external link is shown a blank page

### ISSUE THREAD

**Issue by darhma** [deltachat/deltachat-android#1722]
How to reproduce: open a chat and visit an external link, once you close the browser and go back to delta chat is shown a blank page if you go back you'll be shown the home page of delta chat

Expected behaviour: once the browser is closed  you should go back to the message from where you had open the link

**Comment by r10s** [comment]
> Expected behaviour: once the browser is closed you should go back to the message from where you had open the link

i cannot reproduce that on any of my devices; in general, this is what happens. so there might be some more preconditions to be met. can you retry/file more details? can you test that on some other device? maybe you can figure out the difference.

**Comment by darhma** [comment]
@r10s Ok after a further check I found that the problem seems to occur when the block with the fingerprint is active

**Comment by darhma** [comment]
I've just updated delta chat from f-droid from version 1.12.5 to 1.14.1 and I saw a message from delta chat that the screen lock feature will be discontinued in future versions so I think that this issue can be closed

**Comment by r10s** [comment]
thanks for coming back - ahh, right, the screen lock. indeed, i can easily imagine that caused the issue.
