### ISSUE TITLE
if  names of attached pdf files   contain spaces or ä,ü,ö they can't be opened directly

### ISSUE THREAD

**Issue by gitgerardo** [deltachat/deltachat-android#1725]
- Operating System (Linux/Mac/Windows/iOS/Android):Android
- Delta Chat Version:1.14
- Expected behavior: opening pdf attachments always directly in  DeltaChat
- Actual behavior:if  names of attached pdf files   contain spaces or ä,ü,ö they can't be opened directly in DC. I have to download these pdf- attachments in order to open them.

**Comment by r10s** [comment]
thanks for filing this issue, i can confirm, this does not work, neither in 1.12 nor in 1.14.

it is a good timing, we are currently improving compatibility with classic clients/mail, i think, this falls roughly into this area :)

some screenshots:

display in dc already looks weird:

<img width=300 src=https://user-images.githubusercontent.com/9800740/98747810-9a9f0700-23b8-11eb-8f1b-a9740f71667c.png>

started intent cannot open the file:

<img width=300 src=https://user-images.githubusercontent.com/9800740/98747806-996dda00-23b8-11eb-8fd3-0b4fad2256d6.png>

export works, however, somehow the extension is lost and the pdf cannot be opened from a filemanger unless the extension is added correctly (then, at least, the content is correct):

<img width=500 src=https://user-images.githubusercontent.com/9800740/98747819-9c68ca80-23b8-11eb-9f82-b928d8caafa5.png>

**Comment by r10s** [comment]
there is also https://github.com/deltachat/deltachat-core-rust/issues/1854, however, we also leave this issue open to make sure, no android bits are left unfixed :)

**Comment by gitgerardo** [comment]
![20201111_150001_063](https://user-images.githubusercontent.com/33866993/98821058-4f740b00-242f-11eb-8f68-e1422e3316d2.jpg)
same here...

**Comment by gerryfrancis** [comment]
Enhancement of https://github.com/deltachat/deltachat-core-rust/issues/1854 .

**Comment by gerryfrancis** [comment]
BTW, the name must not begin with "UTF-8" or "utf-8". This seems to be a misinterpretation in Delta Chat, as the name is assigned correctly in Posteo Webmail.
