### ISSUE TITLE
http links are not shown correctly

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#173]
Depending on the complexity (length?) of http links they are not shown correctly.
If you press on one of these links then only a part of them is used as link adress.

In this example the full link should cover all text in the red box, but it breaks after position "...e-a":

![screenshot_2017-09-30_dc_link not shown correctly](https://user-images.githubusercontent.com/30560716/31059754-4d235c22-a708-11e7-8697-bfc163569d61.png)

**Comment by csb0730** [comment]
Hello @r10s,

this issue is still existing (v0.9.9 f-droid). If necessary I can send an example mail (source) offline.

**Comment by r10s** [comment]
Can you post an example .eml (or so) file here or add it to gist?

Internally, currently, we just use  (android.text.util.Linkify)[https://developer.android.com/reference/android/text/util/Linkify.html] with WEB_URLS - so different Android versions may produce different results...

**Comment by csb0730** [comment]
Here an example .eml file which produces a link representation as described.

[link_nicht_korrekt_dargestelt_#173_anonymous.eml.txt](https://github.com/deltachat/deltachat-android/files/1545190/link_nicht_korrekt_dargestelt_.173_anonymous.eml.txt)

... but what I found now is that in ascii part of the mail the link structure is broken while in html part the link is ok! If MUA shows html as standard (Thunderbird) links are looking ok while DC (I suppose it only shows ascii part) presents the broken links!

So root cause of this situation is broken ascii part of mail, not a bug in DC.

But maybe in future DC could show html part in mail if available? Feature Request?

**Comment by Ampli-fier** [comment]
There is a [linkify repository](https://github.com/markdown-it/linkify-it) on Github, and the test/demo page is [here](https://markdown-it.github.io/linkify-it/).

**Comment by csb0730** [comment]
Issue is reproducable and root cause is a broken link in "text only" part of a message.
The MUA sending the message breaks the links by automatically wrapping lines at a certain length. By disabling this feature or making lines long enough at sending MUA this problem can be prevented completely.

Issue is not at DC side!

So this issue can be closed now :-)

**Comment by r10s** [comment]
:)
Thanks for investigate :)
