### ISSUE TITLE
Screen rotation while doing a Voice recording

### ISSUE THREAD

**Issue by cwerner1** [deltachat/deltachat-android#1735]
- Operating System (Linux/Mac/Windows/iOS/Android): Android - 10.1.0.243
- Delta Chat Version: 1.14.1
- Expected behavior: 
DeltaChat should not rotate the screen, while a voice Memo is recorded.

- Actual behavior: 
the screen gets rotated and the voice recording gets aborted.

- Steps to reproduce the problem:
autorotation of the screen is turned on.
In deltachat start a voice recording, rotate the Phone about 90° to the side - the screen gets rotated and the voice recording get aborted.

**Comment by gerryfrancis** [comment]
I thought, I had replied to this one, yet. Unfortunately I cannot reproduce the issue. @cwerner1 Could you please try again with the latest version 1.14.5, please? You can download/update either from Google Play or here: https://download.delta.chat/android/deltachat-gplay-release-1.14.5.apk

**Comment by cwerner1** [comment]
@gerryfrancis 
I tested with the delta chat version you provided, an captured a screen recording, while preforming an voice recording.

![SVID-20201123-154500-1](https://user-images.githubusercontent.com/1199614/99977273-b638e300-2da4-11eb-860a-9c6541af18fe.gif)

**Comment by gerryfrancis** [comment]
@cwerner1 Thanks a lot, unfortunately I still cannot reproduce the issue. Could you anonymize and upload a log file that is saved right after you performed the test? That would be extremely helpful, thank you in advance!

**Comment by cwerner1** [comment]
I solved the Issue with teh App "Auto Auto-Rotate".
I've disable the auto-rotation for deltachat with this app.

**Comment by gerryfrancis** [comment]
@cwerner1 Thanks for the information. I have tried to reproduce your issue in version 1.15.0-beta, it works just fine. I suggest to test one of the nightly builds available [here](https://download.delta.chat/android/nightly/) or wait for the next official release.
