### ISSUE TITLE
Stockstring definition uses plain numbers instead of constants

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1739]
https://github.com/deltachat/deltachat-android/blob/aa180e1c3a3a1364efa50b4a16cc8a84d37a333d/src/org/thoughtcrime/securesms/connect/ApplicationDcContext.java#L118-L122

Yeah might be that an enum is not overkill, but constants or simple comments that contain the constant name would already be a big plus in code readability.

#### Why am I opening this issue now:
Upon working on https://github.com/deltachat/deltachat-desktop/issues/1941 I thought I could save some time copying and adjusting code from android (at-least to see what strings are still missing).

https://github.com/deltachat/deltachat-desktop/blob/e953f3fb37c99cbaca82793f15075063d2aabbb4/src/main/deltachat/login.ts#L215

I can still use android code but it requires now a bit more work.

**Comment by r10s** [comment]
yip, copy+paste does not work here.

however, from the view of android, using named constants here would require defining them somewhere else, so that would just shift the work around and increase effort on android-side - unless we generate the constants from deltachat.h via a script or so. i am no sure if this is worth the effort currently, esp. as there are only a handful of new strings every few months.

**Comment by r10s** [comment]
@Simon-Laux ahh, we just updated the strings for ios - maybe that is a better template for copy+paste:

https://github.com/deltachat/deltachat-ios/blob/master/deltachat-ios/AppDelegate.swift#L166

**Comment by Simon-Laux** [comment]
> unless we generate the constants from deltachat.h via a script or so

That's exactly what we do in the nodebindings: https://github.com/deltachat/deltachat-node/blob/master/scripts/generate-constants.js

**Comment by Simon-Laux** [comment]
yeah iOS is a better template in this case, already did it with android (looking more at the translation keys and replacing the numbers by their constants one by one), but still thanks for the link :+1:

**Comment by r10s** [comment]
k, then close this for now, i just had a look, a script would be quote some effort as the java-constants are distributed over several files. also testing and so on. it seems not to be worth the effort.
