### ISSUE TITLE
quoting forwarded message  no longer look as beeing forwarded

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1743]
when quoting a forwarded message, the information that the message is not from the sender, is lost.

this can easily lead to confusing situations, i just came over that in testing group, here is a more constructed case:

<img width="373" alt="Screen Shot 2020-11-25 at 11 42 58" src="https://user-images.githubusercontent.com/9800740/100217436-bd323380-2f13-11eb-97e6-09365ae057cb.png">

things would be even worse, if there are other messages between the first two shown in the example above.

solution:

if forwarded messages are quoted, this should be shown in the quote as usual by replacing the name by the string "Forwarded message" and show the title and the bar in "forward grey color".

no additional api is needed for that, just check [`dc_msg_is_forwarded()`](url) for the quoted message. if the quoted-message is unknown, things are fine as the author is not shown at all in this case. however, i suggest to use the "forwarded" bar also in this case (instread of the current purple fallback) - this is fine whether the message was forwarded or not.

**Comment by r10s** [comment]
i think, this is what it should look like:

<img width="372" alt="Screen Shot 2020-11-25 at 13 05 11" src="https://user-images.githubusercontent.com/9800740/100225763-05a31e80-2f1f-11eb-92ef-d7d996ebb96f.png">

**Comment by webratte** [comment]
Maybe still in top of the message the senders name.
I mean the name of the sender who forwarded the message (as in every other quoted message.)



Am 25. November 2020 13:07:06 MEZ schrieb bjoern <notifications@github.com>:

**Comment by r10s** [comment]
i think, this produced unnecessary noise. 

and also looks a bit unbalanced as we add more titles/info to the quote as to the original message.

regard the real sender a "Forwarded message" as sort of unknown, quoting such a messages quotes an unknown sender. this "Forwarded message" hint is type of the sender name.

finally, if it is really important who did the quote, this is just a tap away.

**Comment by webratte** [comment]
I thought it's interesting who forwarded this message. Especially in a group. Similar who has written a message which was quoted.

On the other hand, it's possible to jump to the replied message by tapping on the quote.

So probably your right.

**Comment by r10s** [comment]
well, quoting hides information. i think this is similar to quoting a message that already contains a quote: the previous quote and sender information are also hidden then. we are basically doing the same, hiding the previous information. 

in both cases, you can tap on the quote to get more information by jumping to the original message.

ah, and one thing: the sender will also see the preview quote in the "Forwarded message" way - so, it is also pretty clear to what he refers.
