### ISSUE TITLE
List of lately used emojis not accurately updated

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1745]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-11-27).

- Delta Chat Version:
1.14.5, latest master build.

- Expected behavior:
After using one or more emojis, the list of lately used emojis (clock icon on the bottom) should offer this/these to be quickly selected.

- Actual behavior:
After using one or more emojis, the list of lately used emojis does not offer this/these. The current chat must be closed (<-) and opened again to be able to choose this/these.

- Steps to reproduce the problem:
-- While in a chat, switch to the emoji keyboard, and choose one or more emojis that you did not use before.
-- Send this message.
-- Check the list of recently used emojis (clock icon). (Result: The list is not updated.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
> The current chat must be closed (<-) and opened again to be able to choose this/these.

this is a feature :)
emoji-recents-order is not changed unexpectedly.

however, this is a known issue. all attempts to fix that resulted in more worse issues iirc. so, tbh, not sure if that is worth targeting again.

**Comment by r10s** [comment]
moving stale discussion to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).

**Comment by gerryfrancis** [comment]
@r10s Thanks for caring! For what it's worth, I think this fix from Signal could help here when adapted for Delta Chat: https://github.com/signalapp/Signal-Android/commit/e709cdc9d5a800d9dd1ac152464386123097c346

**Comment by Hocuri** [comment]
Let's reopen then as it's a lot more actionable now (we can just try to pull this commit)

**Comment by Hocuri** [comment]
Actually, no, https://github.com/signalapp/Signal-Android/commit/e709cdc9d5a800d9dd1ac152464386123097c346 does something unrelated. And Signal still shows the same behavior as DC wrt updating the list of lately used emojis, so pulling code from Signal won't help.

**Comment by r10s** [comment]
thanks for checking!
