### ISSUE TITLE
Photo of unsent message cannot be viewed in fullscreen size

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1749]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-12-04).

- Delta Chat Version:
1.14.5.

- Expected behavior:
When a message that contains a photo cannot be sent for whatever reason, the photo of that message can be viewed fullscreen sized afterwards by tapping the photo.

- Actual behavior:
When a message that contains a photo cannot be sent for whatever reason, the photo of that message cannot be viewed fullscreen sized afterwards.

- Steps to reproduce the problem:
-- Add a new contact with a mail address that does not exist.
-- Enter a chat with this fake contact.
-- Try to send a message that includes a photo. (Tap on the camera icon.) (Result: A system message pops up to inform you that the message could not be sent.)
-- Tap on the photo of the unsent message. (Result: It does not appear in fullscreen size.)

- Screenshots:
N/A.

- Logs:
N/A.

- Credits:
Reported by user "adb" from Delta Chat group "Testing Delta Chat".

**Comment by Hocuri** [comment]
Fixing this would be a one-line change, but: Signal shows the error of a failed message when you click it (that's the reason the image is not enlarged, only that showing the error message doesn't work, either).

So, we can decide: Do we want to show the error message when the user clicks a failed message? Or do we want to enlarge the image to full-screen?

**Comment by Hocuri** [comment]
btw it's in org/thoughtcrime/securesms/ConversationItem.java:636 `messageRecord.isFailed()`

**Comment by r10s** [comment]
the error message is also visible in "info", or?

i'd keep it simple, do enlarge/whatever as usual and long-tap -> info will show the error. maybe a tap in the error icon could be used as a shortcut, howerver, that is probably too small and not worth doing as a fix.

**Comment by adbenitez** [comment]
I was the one proposing to enlarge at first, but now that you point that out, it will be better UX to show the error on tap,
@r10s enlarging and ahowing error with long-tap + info button might be simple for the developer but not for the user, currently most users don't know what is going on when they see the X, don't know how the long-tap + info "hack"

**Comment by gerryfrancis** [comment]
Although a system message already informs the user about the failure, sometimes it is not clear to which message that system message belongs. (E.g. one relay reports back 24 hours later that the mail could not be forwarded in time.) It is just my assumption, because I cannot simulate such a scenario, so please correct me if I am wrong.

**Comment by adbenitez** [comment]
system message will appear only if it is an SMTP error, in that case is directly shown under the message, but when you send a message to an user in another server, after some while you get the X in the message because dc got a "mail delivery daemon" message, so in this case you don't get any info, just the X, so you have to tap the info button, would be nice to show error on tap

**Comment by Hocuri** [comment]
I just asked my little brother, and he said that the error message should be shown when tapping the image "as you already know the image" (i.e. you sent it yourself)

**Comment by adbenitez** [comment]
+100
