### ISSUE TITLE
email chat explaining and naming

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#175]
Hi, maybe others have made a similar experience?

I found it is becoming increasingly harder to convince others to install yet another "XYZ-chat" app. And this includes delta.chat. But what worked wonders was to mention it as an email chat client, refering to it as "chat mail".

See, this awsome "chat.mail" app allows me seamless quick and secure email communication when on the mobile device.

```
--
Sent with my chat.mail app. 
```

**Comment by r10s** [comment]
:)

but the good point about Delta Chat is that it is not a strong requirement that your chat partners use Delta Chat too (although may will make things easier)

**Comment by testbird** [comment]
Right, I wasnt't too sucessful to make one person realize that the app really is a regular but specialized email client, though. A ChatMail**er** that can reach the world.
```
--
Sent with chat.mail - notifying email client for speedy mobile conversations.
```

**Comment by netzoom** [comment]
What's about this version? :)
```
--
Sent with Delta Chat - notifying email client for speedy mobile conversations.
```

**Comment by r10s** [comment]
Sounds good to me - but I am no specialist in such things ...

**Comment by testbird** [comment]
In any case mentioning the actual domain name provides precise pointer.
I kind of like the current version, with a the technical background added:
```
--
Sent with my <domain name> messenger - the notifying email client with touchscreen support.
```

**Comment by testbird** [comment]
Further streamlined:
```
--
Sent with my <domain name> messenger -
open source notifying email client for mobile chats.
```
PS: There is no FAQ item anymore that explains the naming of this awesome email chat program.

**Comment by r10s** [comment]
> PS: There is no FAQ item anymore that explains the naming of this awesome email chat program.

Was there any?

**Comment by testbird** [comment]
IIRC I saw something in the search result summary for some librechat.org result (which points to delta.chat now).
```
--
Sent with my email.chat messenger - open source paging email client.
```

**Comment by netzoom** [comment]
Now I understand that you did talking about domain name, not just signature about! Few variants, which will redirect to main, it's good idea. But you should register domain name quickly if you want it, because it published here and anyone can overtake you. Also when I tried to check few names, I did find the competitor unexpectedly. Their website is without first letter "e" in previous message.
