### ISSUE TITLE
General (system) notification sound played when selected "None"

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1753]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2020-12-04).

- Delta Chat Version:
1.14.5, latest master build.

- Expected behavior:
When no notification sound ("None") is set, Delta Chat does not play a sound after a new message is received.

- Actual behavior:
When no notification sound ("None") is set, Delta Chat plays the general notification sound configured in Android.

- Steps to reproduce the problem:
-- In "Settings" -> "Notifications" -> "Sound" choose "None".
-- Wait for an incoming message. (Result: The general notification sound is played.)

- Screenshots:
N/A.

- Logs:
N/A.

- Credits:
Reported by user "Gh0stz" from Delta Chat group "Testing Delta Chat".

**Comment by adbenitez** [comment]
I am looking at this issue, 

good news: I think I can fix it, at least for new channels.

**bad news:**
* we are not supposed to keep this configuration at all in the app, on clicking the notification menu the app should redirect to system notification settings (see https://developer.android.com/training/notify-user/channels.html#UpdateChannel)
* if user go to system notification settings, to the channel for the chat "my group" that was silenced inside the app, and change it to some sound, actually the channel for "my group (no sound)" will be overwritten, in the app still "no sound" will be selected, and from now on "no sound" will actually play the sound that the user selected,
* this also applies to any sound, if you have selected "Luna" ringtone and then change the chat sound to "one beep" from system settings that point on, "Luna" in Delta Chat will actually be "one beep"

(it is broken, Google made it so you can't handle this in your app)

I just tested Signal and it is pretty broken, have this same issues and selecting "no sound" doesn't works

**Comment by Hocuri** [comment]
> we are not supposed to keep this configuration at all in the app, on clicking the notification menu the app should redirect to system notification settings (see https://developer.android.com/training/notify-user/channels.html#UpdateChannel)

OTOH, neither Telegram nor WhatsApp does this. No idea how they circumvented Google's restrictions. Maybe it involves creating a new channel with a random name everytime the user changes a setting.

**Comment by r10s** [comment]
> Maybe it involves creating a new channel with a random name everytime the user changes a setting.

yip - and this is also what we are doing. however, our name is not random, but is build from the settings, so that we do not spam the channel-names too much. it is documented at https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/notifications/NotificationCenter.java#L159
