### ISSUE TITLE
Fail to play builtin voice message

### ISSUE THREAD

**Issue by EchedeyLR** [deltachat/deltachat-android#1755]
- Operating System (Linux/Mac/Windows/iOS/Android): LineageOS for microG 14.1 ~ Android 7.1.2 
- Delta Chat Version: 1.14.5
- Expected behavior: Built-in audio player plays my own recorded voice messages made by Delta Chat.
- Actual behavior: Built-in audio player doesn't play my own recorded voice messages made by Delta Chat and external Android default player is showed.
- Steps to reproduce the problem: Happened suddenly but I remember I sent a 5 minutes voice message and, when I saw that duration time was not showed in the audio preview I tried to play it from Delta Chat to check if was recorded wrong, it froze a moment (only the playing) and the external audio player was showed. 
This has happened to me in other times with big voice messages too involved but as always, like now, was solved by just closing and open Delta Chat from Android settings. Now I could catch the log.
- Screenshots: 
![image_2020-12-13_23-12-41](https://user-images.githubusercontent.com/56733813/102082258-8ca23300-3e09-11eb-9f5d-b2a783f5c7c3.jpg)

- Logs: 
[player-log.zip](https://github.com/deltachat/deltachat-android/files/5688769/player-log.zip)

```
12-13 23:35:05.124 13312 13312 W AudioView: playbutton onClick
12-13 23:35:05.127 13312 13312 I ExoPlayerImpl: Init 71dd597 [ExoPlayerLib/2.9.6] [tenshi, Aquaris U Plus, bq, 25]
12-13 23:35:05.228 13312 14129 I OMXClient: MuxOMX ctor
12-13 23:35:05.235 13312 14129 I ACodec  : codec does not support config priority (err -2147483648)
12-13 23:35:05.284 13312 13312 D AudioSlidePlayer: onPlayerStateChanged(true, 3)
12-13 23:35:05.284 13312 13312 I AudioSlidePlayer: onPrepared() 100% buffered
12-13 23:35:05.284 13312 13312 D AudioSlidePlayer: DURATION: 1630
12-13 23:35:05.291 13312 14127 E AudioTrack: AudioFlinger could not create track, status: -12
12-13 23:35:05.291 13312 14127 E AudioTrack-JNI: Error -12 initializing AudioTrack
12-13 23:35:05.291 13312 14127 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal: Playback error.
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack  init failed: 0, Config(44100, 4, 28288)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:646)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:154)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 4, 28288)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1128)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:532)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:593)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(M ediaCodecAudioRenderer.java:640)
12-13 23:35:05.304 13312 14127 E ExoPlayerImplInternal:     ... 7 more
12-13 23:35:05.357 13312 13312 W AudioSlidePlayer: MediaPlayer Error: com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 4, 28288)
12-13 23:35:05.396 13312 13312 D AudioSlidePlayer: onPlayerStateChanged(true, 1)
12-13 23:35:05.427 13312 13312 I PassphraseRequiredActionBarActivity: onPause()
12-13 23:35:05.427 13312 13312 I AudioSlidePlayer: Stop called!
```

**Comment by gerryfrancis** [comment]
@EchedeyLR Thanks for your report. I tried to reproduce the error according to your description, but I am not able to do that. However, my device is different (running current Lineage OS 17.1), and recording > 5 minutes did not froze. The "Playback error" probably occured because the audio resource was not released properly due to the freeze before...

**Comment by EchedeyLR** [comment]
I think the same. This doesnt happen always but only a few times. There are times with 5 minutes messages where I don't have the issue but when happen, it happens always with a big voice message by me (as I dont receive similar messages from other people).

**Comment by gerryfrancis** [comment]
@EchedeyLR Do you remember if any playback (e.g. a notification tone) occured while you were recording your voice message?

**Comment by Hocuri** [comment]
- When this failed, did you play multiple other audio files right before?

>   * This has happened to me in other times with big voice messages too involved but as always, like now, was solved by just closing and open Delta Chat from Android settings. Now I could catch the log.

- But it was not solved by closing just hitting the "play" button again? Was it solved by swiping away Delta Chat and trying again? Or by just going to the chatlist view and entering the chat again? (in case you tried it out)

Some quotes from the internet possibly concerning this bug:

["-12 is ENOMEM Not enough space"](https://stackoverflow.com/a/12472446)
["I'll use this as an opportunity to remind media developers: please remember to call release() for media objects when your app is paused."](https://stackoverflow.com/a/12024769) ([example](https://stackoverflow.com/a/19815461))
[You must reduce the size of your mp3 file. You should keep the size under 100kb per file.](https://stackoverflow.com/a/16453936) (sb. else said [1mb](https://stackoverflow.com/a/19237073))
[It was due to creating the SimpleVideoPlayer twice not intentionally and releasing it only once](https://github.com/google/ExoPlayer/issues/954#issuecomment-260198880)

**Comment by Hocuri** [comment]
Just saw that in `org/thoughtcrime/securesms/audio/AudioSlidePlayer.java:162` we set `mediaPlayer = null;` without releasing it, maybe that's the case.

**Comment by EchedeyLR** [comment]
Sorry for being late.

> Do you remember if any playback (e.g. a notification tone) occured while you were recording your voice message?

No, I am sure in the last case this didn't happen.

> When this failed, did you play multiple other audio files right before?

Yes, I was in an audio-first conversation mostly.

> But it was not solved by closing just hitting the "play" button again? Was it solved by swiping away Delta Chat and trying again? Or by just going to the chatlist view and entering the chat again? (in case you tried it out)

Closing the Delta Chat window and opening it again, getting out of the chat to the chat view and entering inside the chat again and closing and hitting "play" button again didn't worked.

The issue was, even, maintained in every audio file I recorded and played later or when I tried again the first ones I sent before the issue. To solve it, I had to force Delta Chat closing in Android settings (Settings > Applications > Delta Chat > "Force closing") and then open Delta Chat normally and try to play any of them.

**Comment by Hocuri** [comment]
This may have been fixed by https://github.com/deltachat/deltachat-android/pull/1756.

**Comment by EchedeyLR** [comment]
I will wait to the stable release to see if it happens again.

**Comment by Hocuri** [comment]
Stable release is there, is this bug gone in 1.20.5?

**Comment by EchedeyLR** [comment]
Oof, sorry for my delay. I didnt experience this anymore after upgrade.

**Comment by r10s** [comment]
\o/ yeah! thanks for re-checking, @EchedeyLR !
