### ISSUE TITLE
Unable to exit "Unlock Delta Chat" screen by clicking "Cancel"

### ISSUE THREAD

**Issue by aykarpov** [deltachat/deltachat-android#1757]
If the screen lock is enabled, when you start the application, the "Unlock Delta Chat" window will first open, where you can only enter the unlock code. Clicking the Cancel or Back button always reopens the Unlock window and pops up the message "Authentication failed."

**Comment by r10s** [comment]
thank you for your report.

> Clicking the Cancel or Back button always reopens the Unlock window and pops up the message "Authentication failed."

what would you expect to happen? closing the app, maybe.

anyway, we it is very unlikely, that we will fix or change that, the internal "Settings / App access / Screen lock" options will be removed completely in one of the next versions, 1.14 already adds a corresponding warning, see https://github.com/deltachat/deltachat-android/pull/1627 for reasoning.

**Comment by EchedeyLR** [comment]
@r10s is there any plan to add custom app lock settings?

**Comment by r10s** [comment]
several rough ideas, but no concrete plans :)

**Comment by r10s** [comment]
closing this, no actionable item left.
