### ISSUE TITLE
Make setting advanced settings easier with OAuth2 flow

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1759]
OAuth2 offer gets in the way currently when you type in the login. A notification is shown, which should be dismissed if you want to set some advanced settings first:
https://github.com/deltachat/deltachat-core-rust/issues/1759#issuecomment-750920572
When focused on the password for the second time, an option to use OAuth2 is not offered anymore until you click to proceed.

What I suggest:
1. After typing in the login, add a hint below the password, something like: "This provider offers simplified setup (OAuth 2.0). Leave the password empty to use it."
2. If users clicks continue with empty password when the hint is shown, open the browser with OAuth2 setup. If password is entered, try normal configuration.
3. Remove "Authorization method" from advanced settings. Set it to OAuth2 if password is a token from the browser and "automatic" otherwise.

Also this way user will not see password field filled with the token. Normally you can see token length during login, it's a glitch IMO.

**Comment by r10s** [comment]
closing stale feature request; if still needed, please reopen in the [forum](https://support.delta.chat)
