### ISSUE TITLE
Designer wanted!

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#176]
While optimising the "onboarding" process and implementing an export/import backup function, I was stumbled upon the graphics in the welcome screen (which are the same as from https://delta.chat :

- the graphics are partly still from the Telegram original source code, which is no licence problem (GPL'd) but it would be finer to have something own
- other graphics are created by my in less-than-a-minute just to have _anything_ - these are at least the two checkboxes IIRC

So, I am wondering if there is a designer out here (or maybe someone knows) who can try to do it better :) (I'm sure _everyone_ can do it better :)

- the graphics should be vector or "large" pixel graphics
- more or less serious
- should harmonize with the logo in some way
- should reflect the statements and sentences written below them in some context

Here is what I'm talking about:

![screenshot_20171005-230438](https://user-images.githubusercontent.com/9800740/31252597-f8445b3a-aa21-11e7-90c7-93c47ac5db23.png)
![screenshot_20171005-230444](https://user-images.githubusercontent.com/9800740/31252599-f846ce9c-aa21-11e7-822a-7220de7361cc.png)
![screenshot_20171005-230452](https://user-images.githubusercontent.com/9800740/31252601-f85327d2-aa21-11e7-987e-e165fb9dc8ae.png)
![screenshot_20171005-230504](https://user-images.githubusercontent.com/9800740/31252598-f845e482-aa21-11e7-8ac6-93655bdc0197.png)
![screenshot_20171005-230509](https://user-images.githubusercontent.com/9800740/31252602-f855ba88-aa21-11e7-8180-fee561355604.png)
![screenshot_20171005-230513](https://user-images.githubusercontent.com/9800740/31252600-f850fa0c-aa21-11e7-9757-463b2b9c534e.png)

**Comment by stefan-niedermann** [comment]
Maybe someone from @opensourcedesign/people is willing to contribute to this great project (short description: it's a decentralized, encrypted whatsapp-like email client)? :)

**Comment by jancborchardt** [comment]
I suggest submitting a job on our Open Source Design job board: http://opensourcedesign.net/jobs :)

**Comment by testbird** [comment]
Maybe refocus the page from "Free" (as in beer) onto "Free Sources".

**Comment by r10s** [comment]
@stefan-niedermann @jancborchardt Can someone add a job to opensourcedesign,net pleae - I do just know nothing about the page currently and I fear I do not have the time to go into deep reading at the moment.

**Comment by jancborchardt** [comment]
@r10s there’s a very simple form you can fill out at http://opensourcedesign.net/jobs/job-form/ :) and the person filling it out should really be one of the maintainers like you.

**Comment by r10s** [comment]
Ah, okay, thank you for pointing me to the right direction.

**Comment by r10s** [comment]
As you see - I've just asked for adding a new job :)

**Comment by r10s** [comment]
The job is live - http://opensourcedesign.net/jobs/jobs/2017-10-12-create-or-choose-images-for-a-feature-eyecatcher - let's see what will happen :)

**Comment by r10s** [comment]
we have a first iteration for the graphics, see https://github.com/deltachat/deltachat-android/commit/c8a0d268f90ed6795e1cd16551b9791ee4e5a2d2 , thank you very much, ilya :)

the first checkmark is replaced by a bird and the icons do more match the delta chat logo itself. I like it :)

however, of course, if there are further improvements, they're welcome :)

**Comment by r10s** [comment]
another iteration by ilya: sharper and a _castle_ as a replacement for the second _checkmark_ :) https://github.com/deltachat/deltachat-android/commit/ca23b6e2c54e0ae23ef20befc66e713b7e4cae88

**Comment by jancborchardt** [comment]
@r10s good to hear someone got involved! :) May I ask if the person came through our job board?

Also, it would be good to mark the job from "searching" to "resolved" if you are not looking anymore. :) cc @simonv3 @evalica

**Comment by r10s** [comment]
Hi @jancborchardt @simonv3 @evalica

first of all, thank you for your job board. 

> May I ask if the person came through our job board?

No, He came from the Delta Chat community.

> Also, it would be good to mark the job from "searching" to "resolved"

Yes, it can be closed. However, we would be glad if we can add a job there again, if needed.

**Comment by jancborchardt** [comment]
@r10s ok, thanks for the info! Of course you are welcome to submit a job again at any time! :) It would be great if you can submit a pull request to the job about this, and change the status from searching to resolved: https://github.com/opensourcedesign/jobs – thank you!

**Comment by r10s** [comment]
@jancborchardt i've created a PR, see https://github.com/opensourcedesign/jobs/pull/275 - thanks for the hint.
