### ISSUE TITLE
A toast is shown many times when I lose connection

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1760]
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: 1.14.5
- Expected behavior:
what I hope is that when I lose connection the toast is shown only once
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- 
![deltachat-2020-12-26-101118](https://user-images.githubusercontent.com/52469394/103154007-c4db3700-4762-11eb-95ac-d9ab573cd0c9.jpg)

- Logs:
[deltachat-log-20201215-064306.txt](https://github.com/deltachat/deltachat-android/files/5743258/deltachat-log-20201215-064306.txt)

- A video capture
https://user-images.githubusercontent.com/52469394/103154260-323b9780-4764-11eb-922b-7b6c3bac4daf.mp4

**Comment by adbenitez** [comment]
I think #1860  will close this, right?

**Comment by adbenitez** [comment]
btw, this toasts are a real pain in Desktop

**Comment by Hocuri** [comment]
> I think #1860 will close this, right?

Yup :tada: :tada: Specificially, this line:

https://github.com/deltachat/deltachat-core-rust/pull/2319/files#diff-51d143b69b6ca8b0c0417b328de29bbb8ad98f691bc78019803808b22578e016L134

**Comment by agutierrez25249** [comment]
I think this problem is solved in v.1.20.5, anyway I will wait a little longer before closing it
