### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [deltachat/deltachat-android#1765]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by r10s** [comment]
thanks for filing the issue, and sorry for not answering :)

you may have noticed that many devs are busy with various things ... but maybe you are up to help with the issue? iirc, anyone can do a pr on f-droid (in fact, also we have to do just prs there)

**Comment by gerryfrancis** [comment]
@r10s Can you provide test accounts to build (group) chats with "Bob" and "Alice"? I would like to help out. Thanks in advance!

**Comment by r10s** [comment]
@gerryfrancis sure, i will send them to you via DC.

would be great if you can help here. we could also use the same images as we use for google, however, they are also a year or so old meanwhile ...

**Comment by Hocuri** [comment]
Actually, for the case that we want to change the images later, it is probably better to just remove the description from the F-Droid repo (https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.b44t.messenger.yml) after putting into our repo. More on this here: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-applications-source-repository.

For an example, see SuperFreezz: https://gitlab.com/SuperFreezZ/SuperFreezZ/-/tree/master/fastlane/metadata/android/, esp. the `en-US` folder there

**Comment by r10s** [comment]
> For an example, see SuperFreezz: https://gitlab.com/SuperFreezZ/SuperFreezZ/-/tree/master/fastlane/metadata/android/, esp. the en-US folder there

wow, you did super-nice things there!

**Comment by r10s** [comment]
moving stale issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).

**Comment by r10s** [comment]
ftr: there are sceenshots now on f-droid :)
