### ISSUE TITLE
Backup import/export fails with file access error on Android 11

### ISSUE THREAD

**Issue by uhrfra** [deltachat/deltachat-android#1768]
I updated to Android 11 (Lineage), installed DC and I am not able to import a backup from the previous Android 10 or desktop installation.

- Operating System: Android 11 (Lineage)
- Delta Chat Version: 1.14.5
- Expected behavior: Selecting "Import backup" after new installation restores state from a previous Android or a Desktop installation.
- Actual behavior: When selecting "Import backup" an error dialog appears saying that there is no backup file found at /storage/emulated/0/Download. However, the file is present at this location. Restarting DC or the device does not resolve the problem. When I sign up in DC and want to export a backup I also get an error message ("Could not open exported database [...] Sqlite error [...] disk I/O error: Error code 5386 ", see screenshot)

It seems that there's a problem accessing the internal storage of the Android file system. Has anyone experiences with backup import/export on Android 11?

![Screenshot_dc](https://user-images.githubusercontent.com/75865476/104591832-8eac1b80-566d-11eb-88a4-1e293d8bf2ec.png)

**Comment by Hocuri** [comment]
Android 11 apparently breaks things, as every new Android Version, [this time it's storage access](https://developer.android.com/about/versions/11/privacy/storage). For the time being we might be able to circumvent this by adding [requestLegacyExternalStorage](https://developer.android.com/reference/android/R.attr#requestLegacyExternalStorage) to the manifest, but only if we don't set targetSdkVersion=30.

Anyway, we probably need a device running Android 11, any dev who has one?

@uhrfra Does exporting a backup work on Android 11?

**Comment by uhrfra** [comment]
Neither import nor export works. Import says "no backup file found". Export gives the error message in the screenshot above.

I can test on my device if you provide the apk.

**Comment by uhrfra** [comment]
Just for your information: **Key import** from file and **key export** to file works, so in this case there is no problem with internal storage access unter Android 11!

**Comment by r10s** [comment]
> Just for your information: Key import from file and key export to file works, so in this case there is no problem with internal storage access unter Android 11!

that's interesting - as from the view of the filesystem, this is quite the same - a backup just has larger files.

**Comment by Hocuri** [comment]
I don't have an android11 phone, but I tried it in an emulator and, plot twist: Export and import worked totally fine, both for .bak and for .tar files. Maybe this has nothing to do with Android 11 at all?

@uhrfra we recently switched backup formats from `.bak`-files to `.tar`-files. The version of DC you have installed can import both formats but exports `.bak` files. Can you download the nightly APK from https://download.delta.chat/android/nightly/2021-01-16/ (which exports `.tar` files) and try out if importing and exporting `.tar` files works?

**Comment by uhrfra** [comment]
Thank you for your help! I tried the nightly build from above:

- Export works! A tar file is created in the folder /storage/emulated/0/Download
- Importing this tar file after a fresh installation also works!
- I cleared the folder /storage/emulated/0/Download and then copied my actual .bak file there. After re-installation of DC I chose import and got the "No backup found" message.
- I renamed the bak file /storage/emulated/0/Download/delat-chat-2021-01-13.0.bak to /storage/emulated/0/Download/delat-chat-2021-01-13.0.tar and tried an import again. Now DC detects the file and asks if the tar file should be imported! Of course the import with the wrong file format fails.

So maybe actually no problem with Android 11 file access but rather the .bak file detection does not work?

**Comment by Hocuri** [comment]
Before importing a .bak file, DC tries to open it and get the export time and date from the file. This probably fails and therefore DC thinks it's not a backup. That's the reason for the "No backup found" message.

It's great news that everything works fine with tar files, because in the next version at least exporting will magically work! As for importing .bak files, I made a PR to fix this.

**Comment by uhrfra** [comment]
Ok, good to know that backup export / import will work in the upcoming release. However, I am wondering why opening my bak files does not work (I tried bakups from the previous Android 10 installation and desktop installations) and why even exporting as a bak file fails. 

Furthermore, do I have any possibility to sync my desktop installation with the Android 11 device if loading the bak file fails (e.g. copying sqlite database manually)?

**Comment by Hocuri** [comment]
> Furthermore, do I have any possibility to sync my desktop installation with the Android 11 device if loading the bak file fails (e.g. copying sqlite database manually)?

Well, you could:
- Export .bak file from desktop
- on an Android 10 or lower device, install the nightly APK and import the .bak file there
  - then export again, now you will get a .tar file
- import this tar file on Android 11

that's the easiest way to do this that comes to my mind.

**Comment by uhrfra** [comment]
@Hocuri Thank you for your help! As I have no Android 10 device any more I built the deltachat-core-rust and exported a tar backup of my desktop installation via the core command line. I can confirm that tar import works without problems on Android 11 even with DC version 1.14.5!

**Comment by Hocuri** [comment]
Ok, I finally merged https://github.com/deltachat/deltachat-core-rust/pull/2148, I had somehow lost track of this :)

@uhrfra .bak import should work now, as soon as the nightly is there (https://download.delta.chat/android/nightly/), you can try it out if you want.

Thank you for the great report!
