### ISSUE TITLE
thunderbird with enigmail plugin: missing autocrypt setup message?

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#177]
Try this: Install thunderbird and then the latest enigmail plugin, then send a chat messag.
The enigmail plugin is said to handle incoming autocrypt setup messages.
https://sourceforge.net/p/enigmail/source/ci/0bc79b85e266beadddb976f21ad4c2e5aa5ae8aa/

However, no key seems to get imported. Is delta chat sending such a setup message at all?
And should the thunderbird user send a message with the public key as attatchment?

**Comment by r10s** [comment]
We are in contact with the Thunderbird/Enigmail authors as well as with K-9. So, sooner or later, Autocrypt between these apps will work. Currently, there are some known issues.
The setup message itself is not yet fully implemented in Delta Chat, but we're working on this point, see https://github.com/deltachat/deltachat-core/issues/35

**Comment by testbird** [comment]
Ok, great, thanks. Then I can close this.
