### ISSUE TITLE
gmail not work

### ISSUE THREAD

**Issue by Suburbanno** [deltachat/deltachat-android#178]

**Comment by r10s** [comment]
Gmail works if you enable "Less secure apps".

**Comment by danito** [comment]
And if you have 2fa enabled, you need to create an app id for DC see #20 
For me it works, but sometimes it takes several minutes before it synchronizes. And I don't know if this is a bug or a feature, but I get also replies for "non-chat" emails in DC.

**Comment by r10s** [comment]
as mentioned, please refer to #20
