### ISSUE TITLE
Autocrypt setup message ui looks weird

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#1784]
![image_2021-02-01_13-09-06](https://user-images.githubusercontent.com/34889164/106463168-5b53f400-6497-11eb-9602-4c6bad1c776d.png)

I would expect the inputs to be centered?

**Comment by r10s** [comment]
i think, it is okay. it's a bit a matter of taste. 

having the text _left_-aligned, the input _centered_ and the buttons _right_-aligned, might also look weird - no real edge the eyes could align to.

**Comment by Jikstra** [comment]
![Screenshot_20210201_143557](https://user-images.githubusercontent.com/34889164/106465658-8e4bb700-649a-11eb-8a42-475b407701c3.png)

This is how it looks on desktop. Expanding it to the full width with a little bit of padding?

**Comment by r10s** [comment]
also nice - however, tbh, i would prefer the input field smaller, there are only 4 characters to be entered. and i do not think that too many room between the input fields is helpful (it is still okayish in your example, however)

on android we do not really know about the full width of the dialog (at least not without additional effort) - so just stretching to the whole width, may result in the input fields getting lost a bit on the screen.

but i'd say, all that is bikeshedding :)

**Comment by r10s** [comment]
more important: a "cancel" button is missing in the desktop screenshot :)

**Comment by Jikstra** [comment]
> more important ux/ui-wise: a "cancel" button is missing in the desktop screenshot (no, the "x" upper right is no replacement :)

Haha :D But yes :)

**Comment by r10s** [comment]
closing this, there is not really an actionable and urgent item, esp. as we recommend export/import for multi-device setup.

idea for general ux improvement of multi-device-setup goes towards qr-codes anyway.
