### ISSUE TITLE
Do not send locations older than the time of location streaming start

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1787]
When I enable location streaming, my GPS is usually enabled at the same time. Looks like Android caches the last location, so Delta Chat usually immediately sends some older location, even before new GPS data is available. If I enable "show traces", I see a huge jump from some old location (e.g. home) and the location where I enabled location streaming and DC started getting new data. This can easily leak some location the user did not want to share. All locations sent should be obtained strictly within the period when location streaming was enabled.

One way to fix this is to modify `isBetterLocation` at
https://github.com/deltachat/deltachat-android/blob/370335bf6e4f28a79a3f0a654035f4dafecb85ad/src/org/thoughtcrime/securesms/geolocation/LocationBackgroundService.java#L143
to only accept locations that are strictly newer than the time when location streaming was enabled last time: `location.getTime()` should be compared to the time when streaming is enabled.

I have not found how to access the time when streaming was enabled, so opening an issue.

**Comment by cyBerta** [comment]
I would like to propose that the last fix has an timeout of 2 minutes, this will reveal . The idea is to get a first location fast, disallowing the inital 

> When I enable location streaming, my GPS is usually enabled at the same time. Looks like Android caches the last location, so Delta Chat usually immediately sends some older location, even before new GPS data is available.

This is intended behaviour to get an early 'fix'. What I would like to propose it to implement a check that this inital location should not be older than 2 minutes.

**Comment by link2xt** [comment]
Yes, 2 minutes old is ok. The problem is when this location is 1 day old and is totally not a location the user wanted to share.
