### ISSUE TITLE
Answer Google's request for Location-streaming policy update

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#1790]
![Screenshot from 2021-02-03 11-52-21](https://user-images.githubusercontent.com/73579/106737000-6f722f80-6616-11eb-84e4-cfc57998c6f6.png)

**Comment by r10s** [comment]
the policy:

https://support.google.com/googleplay/android-developer/answer/9799150?hl=en#zippy=%2Cstep-review-best-practices-for-accessing-location

i just provided app access by adding a testrun-account:

<img width="640" alt="Screen Shot 2021-03-27 at 18 19 49" src="https://user-images.githubusercontent.com/9800740/112729013-5016c500-8f2a-11eb-8966-c8e4a947e544.png">

unfortunately, they want a youtube-video in the further process ...

**Comment by r10s** [comment]
k, i submitted, we'll see how this works out.

![Screen Shot 2021-03-27 at 23 45 30](https://user-images.githubusercontent.com/9800740/112736900-9550ec00-8f56-11eb-9645-51aade690471.png)

**Comment by r10s** [comment]
closing this one here in favor to the more concrete issues that were filed.
