### ISSUE TITLE
JCenter is closing on August 15th

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1791]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Something should be done about this line in `build.gradle`:
https://github.com/deltachat/deltachat-android/blob/f03c8a5062e23ac980e7cfb5e508ab551215a1a5/build.gradle#L9

**Comment by Hocuri** [comment]
According to the link from above:


> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.


And at least ExoPlayer still recommends to use JCenter: https://exoplayer.dev/hello-world.html, didn't check the other dependencies, but seems like for now we should just leave things as they are.

**Comment by r10s** [comment]
yip, then let's leave things as is for now.

**Comment by adbenitez** [comment]
> For these dependencies we should remove `jcenter()` and vendor dependencies by uploading `.jar` files and dropping them into `vendor/` folder, then referencing it via `flatDir`: https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver

I am trying at https://github.com/deltachat/deltachat-android/pull/3215 but it is not as simple as that, projects have dependencies and then you also have to try&error and figure out the dependencies and include them, and then we even had a dependency (https://github.com/cketti/SafeContentResolver) that is not in jcenter but that also had dependencies in jcenter so I had to include them as well

**Comment by adbenitez** [comment]
https://github.com/deltachat/deltachat-android/pull/3215#issuecomment-2275476206

> So, this means that, since we're including the binary blob now, we just can't publish any more F-Droid versions until either:
> 
>   * We manage to get the source code of the old dependency versions, include it in the repo, and get gradle to compile them together with our own source code
> 
>   * Or we switch to newer versions that are available via Maven Central, dropping support for some older Android versions?
