### ISSUE TITLE
Provide a fallback for unknown value "4 weeks"

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#1796]
I had "Delete messages from device" set to 4 weeks. After update #1786 it shows "Unknown".
![screen](https://user-images.githubusercontent.com/18373967/107193835-55629380-6a00-11eb-9087-bb51f6ca6e16.jpg)

**Comment by r10s** [comment]
yip, we kept the "4 weeks" string, as it was a selectable option, we should use that.

what shall happen to the unknown value in the selection dialog? is it mapped to the next one? or just nothing is selected?

and, as more and other "unknown" values may happen in the future, in addition to the "4 weeks", i would write just "On" instead of "Unknown"

**Comment by link2xt** [comment]
> what shall happen to the unknown value in the selection dialog? is it mapped to the next one? or just nothing is selected?

With disappearing messages I tried to map to some other value close to the one selected. Here nothing is selected now.

**Comment by adbenitez** [comment]
there could be other Delta Chat clients with custom timers, so I would rather just show "X seconds" in that case

**Comment by Hocuri** [comment]
4 weeks are going to be lots of seconds, though

**Comment by adbenitez** [comment]
seconds can be converted to minutes, hours (and maybe weeks),  there are string templates for X seconds, and X hours that are displayed in the message bubbles

**Comment by Hocuri** [comment]
Not sure if that's worth the effort, though, unknown values won't be that frequent as this is only about the deltachat-android app, which we have full control over

**Comment by adbenitez** [comment]
the advantage is that it needs to be translated only once, no need to drop translations and add new ones if then we decide that it is better to change X with Y or add a new category with X months

**Comment by adbenitez** [comment]
is this still an issue?

**Comment by r10s** [comment]
i do not think, there were changes in this area. however, i would be fine with closing the issue. lots of time have passed since we changed from 4 to 5 weeks, so most of ppl will have already dealt with the string "Unknown" and improvements are maybe a bit too late and not worth the effort.
