### ISSUE TITLE
Three-dot menu items not translated when lists displayed in landscape view

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1799]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-02-05).

- Delta Chat Version:
1.15.0-beta.

- Expected behavior:
Items of the three-dot menu (on right top) are translated to the selected language.

- Actual behavior:
Items of the three-dot menu (on right top) are not translated.

- Steps to reproduce the problem:
-- Change the language from "Default" to a different one (e.g. "German") while in portrait view.
-- Rotate the view from portrait to landscape.
-- Tap on the three dots (on right top in the main view) to open the menu. (Result: The menu items are not translated to the selected language.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
there seems to be sth. wrong with landscape and rotation ... thanks for figuring things out and thanks for the great and detailed reports!

**Comment by gerryfrancis** [comment]
@r10s You are welcome. :)

I can add that after rotating from landscape back to portrait view, the menu items keep non-translated. Fun fact: I had not encountered this landscape issue if I was not reporting another one before. (I had to switch from German ("Default") to English, to be able to name the English expression of a menu item in my report.) ;)

**Comment by Gh0stz0x** [comment]
Wow, many times you don't think about changing the language for testing.
Yet it is a bug that is also present in version 1.14.5 - 1.15.1
Nice discovery!

**Comment by adbenitez** [comment]
I have seen menu items translated to the wrong language even in portrait mode

**Comment by gerryfrancis** [comment]
There is another case how this can be triggered:
- Make sure Delta Chat runs in a different language than English.
- Close Delta Chat and launch it again.
- Change the language from e.g. German ("Deutsch") to English, then go back to the main view.
- Select "Help" from the three-dot menu. (Result: The German term "Hilfe" (for "Help") is displayed. From this moment on, the three-dot menu is displayed in German again, so I believe this has something to do with refreshing the header bar.)

**Comment by Gh0stz0x** [comment]
Unfortunately the bug also persists in the new version 1.34.12

**Comment by AndreaLattmann** [comment]
I confirm this bug in version 1.36.2
