### ISSUE TITLE
Feature Request: Forward with edit possibilities

### ISSUE THREAD

**Issue by kollokollo** [deltachat/deltachat-android#180]
I'd like to see a freature similar to forwarding a message, but with the possibility to edit the content, before it gets sent. Not essential, but a nice-to-have.

**Comment by r10s** [comment]
Editing other's message content before forwarding it may be regarded as a falsification by the receiver. Of course, this is always possible in some way, however, I do not believe it is a good idea to push users to this direction.

Currently, you have already the following possibilities:
- Copy the message text via the clipboard to a new message and edit it there
- Forward the original message and add another message with some additional notes

For me, these possibilities are just fine :)

(all apart from the additional complexity such a feature would produce :)

**Comment by r10s** [comment]
Just cleaning up the issue tracker, I think, for now, this is out of scope of Delta Chat unless there are some additional volunteers to implement the feature. However, the request stay available eg. via https://github.com/deltachat/deltachat-android/wiki

**Comment by rilian-la-te** [comment]
@r10s, sorry for write in closed request, but I think my request is similar, and I want to know if it is case, or I can submit another request with my proposal.

I want to allow forwarding with comment attached, and forwarding several messages at one message (with message splitting marks).

This can serve as quoting in chat rooms and as sign of reply in ordinary chats, for example:

1. I send 2 questions
2. Partner choosing one, them forwarding it to me with added answer
3. I see one message with my cited question (selected someone by chat) and with his answer.

Second use case:
1. I choose 2 messages from one chat
2. Then I forward it to another chat with my comment
3. Another chat's peer see it as one message, but can determine quotes' original poster and messages.

Feature example (similar feature from VK messenger):
![screenshot at 2019-01-31 04-07-19](https://user-images.githubusercontent.com/1329638/52023390-00850c00-250e-11e9-8cf1-5dd5a530f2f3.png)
On the screenshot you can see than Konstantin forwarded Anastasia's message, then added a comment (question), and then sent it back to her.

Is this feature possible or desired?

**Comment by r10s** [comment]
well, most things are possible in a way, however, it's often about resources :)

however, feel free to create a new feature proposal in the forum at https://support.delta.chat/ - this issue tracker is mainly about bug reports.
