### ISSUE TITLE
GPG key import according to the standard of GPG

### ISSUE THREAD

**Issue by webermike** [deltachat/deltachat-android#1806]
Hello
I have GPG keys and want to import these into DC.
Does not work. 
Can you make it standardized plz, 
so that DC works for GPG Keys and the key import and export is compatible with the GPG Standard?
Thanks

**Comment by r10s** [comment]
> Can you make it standardized plz,

we are supporting keys compatible to the [Autocrypt standard](https://autocrypt.org/level1.html), this is Ed25519 public keys for signatures, as well as Cv25519 for encryption. moreover, most kinds of RSA keys are supported.  

might be, that in the future, some more key formats are supported, esp. if they are widely used (i am no expert here, not sure what is missing), but the goal is not to support any key format that existed at some point in the past and maybe even has security flaws from a today point of view.

nb: we are also _not_ using GPG internally. instead, we are using [rPGP](https://github.com/rpgp/rpgp) which is completely written in the Rust programming language.

**Comment by r10s** [comment]
nb: in general, this issue tracker is only for bugs and for things some dev is actually working on, i suggest to close this issue here and continue discussion/fr at https://support.delta.chat

**Comment by link2xt** [comment]
There is already a similar issue by the way: https://github.com/deltachat/deltachat-core-rust/issues/2180

**Comment by r10s** [comment]
k, one more reason to close this one :)
