### ISSUE TITLE
Feature Request: Log failure diagnosis informations in special chat or file

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#181]
Quite every time between I detect a strange situation regarding showing messages and getting the chance in doing logcat at home interesting information is no more existent because of limited size of logcat file. Other apps are filling logcat file too!

It would be very usefull to have a function available (like K9) in activating an extra log which is accessable easily by user without using ADB.
(K9 Version 5.207, Function  "Fehlersuchvorgang->Fehlersuchprotokollierung")

**Comment by testbird** [comment]
Better yet, as long as this is not stable, allways keep say 5KB of log in memory, to allow saving the current log to file when an error occurs.

**Comment by csb0730** [comment]
I think this feature request is already done.
See some comments in #189 about that. Only some tweaks are still necessary to complete it :-)

"_Settings_ menu, scroll down to **Info** - _About_, click on it and then click on the text "_v0.9.6 |Info_" at the bottom."

**Comment by r10s** [comment]
Yes, and the upcoming version will also have an option to copy it together with the other information to the clipboard. I think we can close this issue for now.
