### ISSUE TITLE
no notification 

### ISSUE THREAD

**Issue by mohamedhagag** [deltachat/deltachat-android#1810]
- Operating System (Linux/Mac/Windows/iOS/Android): xiaomi note lite8 miui 12
- Delta Chat Version: 1.14.5
- Expected behavior: receive notification
- Actual behavior: not working
- Steps to reproduce the problem:
- Screenshots:
- Logs:

Using multi account

I enabled notification, disabled app killing, enabled permanent connect but still not working.

**Comment by r10s** [comment]
hi @mohamedhagag, thanks for filing the issue.

one question: is the permanent notification visible in the system-area at the time where you expect the notification to be shown?

if so, can you attach a log here? might be the receiving thread is stuck somehow, that might be visible in the log.

**Comment by Gh0stz0x** [comment]
@mohamedhagag I too sometimes have problems with DC on the Xiaomi.
They use very aggressive battery optimization. 
Have you tried following this guide?  https://dontkillmyapp.com/xiaomi

**Comment by r10s** [comment]
closing stale issue with unanswered questions and without actionable item.

please open a new issue with more details if needed.
