### ISSUE TITLE
Feature request: Compress image and other attachments as much as possible

### ISSUE THREAD

**Issue by miguel3014** [deltachat/deltachat-android#182]
If you could add a functionality that allows you to automatically compress images, audio and other attachments as much as possible that are sent.
Some mobile operators have very high rates for data consumption, eg "Cubacel" 1USD / MB

**Comment by r10s** [comment]
Images and videos are already recoded and highly compressed before sending.
I do not think that more will help more here (the problem with #185 is not related to sending images but has other causes that under some circumstances, old messages are trying to being downloaded over and over, same for sending)

**Comment by r10s** [comment]
i'm closing this for now here; the new forum at https://support.delta.chat is the better place for feature requests and discussions.

btw. the upcoming single-folder approach will use only _one third_ of the currently used bandwidth, see https://github.com/deltachat/deltachat-core/issues/408 :)
