### ISSUE TITLE
Icons and labels not shown when capturing image for avatar or deleting it

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1836]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: nightly/master
When changing the profile image, then instead of "Capture image" and "Remove" it says "Android S...". Also, the icons just show a gear in a green circle.
- Screenshots:
![Screenshot_20210313-130536](https://user-images.githubusercontent.com/18012815/111029471-093eb080-83fd-11eb-8aa1-437a818b7dbe.png)

**Possible fixes:**
- Pull code from Signal. They implemented  this in quite a complex way, but OK.
- Just show an AlertDialog with 3 options "Take photo", "Choose from gallery" and "Remove photo". The easier solution, but won't look as nice.
- Imitate Telegram and re-use the attachment-chooser dialog. This will have the nice effect that users already know it and they are already offered some options.
- _Probably doesn't work:_ "Directly" fix this, just set the correct label and icon: I tried to use `LabeledIntent`s , but it didn't work. I tried some other things, but they didn't work, either.

**Comment by Gh0stz0x** [comment]
@Hocuri Sorry, I didn't see you opened an issue.
I opened one too https://github.com/deltachat/deltachat-android/issues/1838 Please close it if you want and use my screenshots if they are useful.  
Sorry again! 😅
