### ISSUE TITLE
Too many garbage cans.

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-android#1838]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: 1.15.0 - beta
- Expected behavior: When I click on my profile picture I would like to see only 3 entries: Camera, Gallery and Delete image
- Actual behavior: When I click on my profile picture, 4 items appear: Android, Camera, Gallery, Photo. The item delete image is missing. If I click on Android, 5 Delete image appears.
- Steps to reproduce the problem: I click on Settings, on my profile, on the image.
- Screenshots: 
![Screenshot_20210313_183639_com huawei android internal app](https://user-images.githubusercontent.com/74795149/111039182-a95c0000-8424-11eb-8d17-28a28e1392c7.jpg)
![Screenshot_20210313_183646_com huawei android internal app](https://user-images.githubusercontent.com/74795149/111039192-afea7780-8424-11eb-8c0a-9708cb7bfe79.jpg)
- Logs:

**Comment by r10s** [comment]
@Hocuri this is probably what you've just fixed with https://github.com/deltachat/deltachat-android/pull/1837 ?

**Comment by Hocuri** [comment]
Ah, yes, I didn't see there already was an issue for it.

**Comment by Hocuri** [comment]
Ah, no, lol, that's a new issue! This issue has been around for months and we opened an issue on the same day :joy::joy::joy:

**Comment by Gh0stz0x** [comment]
Probably yes, sorry, I hadn't seen that you had already opened an issue. 😅 
I deserve to be whipped 😔

**Comment by Hocuri** [comment]
Let's close one

**Comment by Hocuri** [comment]
>  I deserve to be whipped 

Sure not, thanks for being on the lookout for bugs! Closing issues is done easily, but if not found, they can annoy lots of users
