### ISSUE TITLE
Search results not updated after deleting chat

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1843]
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: master
- Expected behavior: deleted chat is removed from search results
- Actual behavior: weird "ghost" chat is shown as placeholder when you delete it
- Steps to reproduce the problem: 
  - create some test chat,
  - use the search button and search part of the test chat's name to find it,
  - open the test chat in the results list, 
  - tap on the menu and select to delete the chat
  - you are redirected to the search results, but now in the place where the test chat was there is a "ghost" chat with a black avatar with `#` symbol
- Screenshots:
![deltachat-2021-03-24-154506](https://user-images.githubusercontent.com/24558636/112374702-cc09d680-8cb8-11eb-8b30-b5d34c306289.jpg)

**Comment by r10s** [comment]
nb: on ios, that was even worse and crashes :) but that was fixed with https://github.com/deltachat/deltachat-ios/issues/1348
