### ISSUE TITLE
Error running `./ndk-make.sh` inside Docker container

### ISSUE THREAD

**Issue by trollkotze** [deltachat/deltachat-android#1847]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: current git master
- Expected behavior: Following instruction in README.md, running `./ndk-make.sh` after `scripts/install-toolchains.sh` inside the Docker container should compile successfully.
- Actual behavior: It unexpectedly ends with a SIGKILL by itself.
- Steps to reproduce the problem: Follow the instructions in the README.md, using Docker.
- Screenshots:
- Logs:
```
root@011e5eb44dff:/home/app# ./ndk-make.sh
starting time: Sat Mar 27 15:46:13 UTC 2021
Setting CARGO_TARGET environment variables.
Full build
-- cross compiling to armv7-linux-androideabi (arm) --
    Updating crates.io index
    Updating git repository `https://github.com/async-email/async-smtp`
    Updating git repository `https://github.com/deltachat/rust-email`
    Updating git repository `https://github.com/async-email/encoded-words`
    Updating git repository `https://github.com/deltachat/lettre`
  Downloaded aes v0.6.0
  Downloaded derive_builder_core v0.9.0
  Downloaded encoding-index-singlebyte v1.20141219.5

  // ... cut for readability

  Downloaded deflate v0.8.6
  Downloaded encoding_index_tests v0.1.4
  Downloaded base64 v0.11.0
  Downloaded 297 crates (25.0 MB) in 2.36s (largest was `openssl-src` at 5.1 MB)
   Compiling version_check v0.9.2
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1

   // ... cut for readability

   Compiling http-client v6.2.0
   Compiling surf v2.1.0
   Compiling deltachat v1.51.0-alpha.0 (/home/app/jni/deltachat-core-rust)
error: could not compile `deltachat_ffi`

Caused by:
  process didn't exit successfully: `rustc --crate-name deltachat --edition=2018 deltachat-ffi/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --crate-type staticlib --emit=dep-info,link -C opt-level=3 -C lto=on --cfg 'feature="default"' --cfg 'feature="vendored"' -C metadata=a153403a3e6bffd6 --out-dir /home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps --target armv7-linux-androideabi -C linker=/home/deltachat/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang -L dependency=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps -L dependency=/home/app/jni/deltachat-core-rust/target/release/deps --extern anyhow=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libanyhow-ca93e06175431a25.rlib --extern async_std=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libasync_std-315d09598486f3e9.rlib --extern deltachat=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libdeltachat-8288340891dd91cc.rlib --extern human_panic=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libhuman_panic-0ba929a03bc53d69.rlib --extern libc=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/liblibc-3b2f969de4b89c89.rlib --extern num_traits=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libnum_traits-e9f62564d6e96e88.rlib --extern rand=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/librand-7c5c694dc010d585.rlib --extern serde_json=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libserde_json-24d30fcece173eb8.rlib --extern thiserror=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/deps/libthiserror-59a542b905837350.rlib -L native=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/build/openssl-sys-7492a150f15363f8/out/openssl-build/install/lib -L native=/home/app/jni/deltachat-core-rust/target/armv7-linux-androideabi/release/build/libsqlite3-sys-7d1f361533a91999/out` (signal: 9, SIGKILL: kill)
root@011e5eb44dff:/home/app#
```

**Comment by link2xt** [comment]
This looks like an out-of-memory error. How much memory does your machine have?

You can try to add `--jobs 1` to `cargo build` call in `ndk-make.sh` to ensure there will be at most one `rustc` running in parallel, but it may still fail during linking which uses a lot of memory.

**Comment by trollkotze** [comment]
Thanks for the hints. I tried both, still with the same result.
The machine is a small mail server with more than half of its available 4 GB in use by its usual processes.
I first tried it on my laptop, which has 8GB, and should be roughly the same Ubuntu 18.04 based setup. But there I get some strange errors when trying to run any shell scripts inside Docker:

```
trollkotze@schrotthaufen-mobil:~/deltachat-android$ docker run -it --name deltachat -v $(pwd):/home/app -w /home/app deltachat-android
deltachat@a0f33981a948:/home/app$ scripts/install-toolchains.sh
bash: scripts/install-toolchains.sh: /bin/sh^M: bad interpreter: No such file or directory
```

I guess it makes sense to open an issue for that here, since it has probably nothing to do with anything in the repo here. Seems to be some strange Docker setup error on my laptop that `bin/sh` does not work for some reason, although it should all be set up the quite same as on the mail server where it works until here, apart from the apparent memory issue. But any hints if having ideas would be very welcome.

Thanks for all the help. I guess this ticket then can probably be closed, if it is determined that this is just an out-of-memory error (which seems to make much sense).

**Comment by link2xt** [comment]
8Gb should be enough as I compiled it on 8Gb raspberry pi before.

`^M` is the `CR` character, looks like line endings were converted to windows-style (`CRLF`) for some reason. This is a problem with your copy of source code, this could be a result of `core.eol` setting in your `git` config.

**Comment by trollkotze** [comment]
Oh, thank you very much. I would have never thought of that. Indeed, this resolved the problem and I could finally compile successfully on my laptop. Had to reclone with autocrlf off.
Peak memorty usage of rustc was a bit over 3GB. So it seems pretty clear that this was the issue. So I'm closing with this.
