### ISSUE TITLE
Excessive data consumption in the background

### ISSUE THREAD

**Issue by miguel3014** [deltachat/deltachat-android#185]
I was testing the app and it's great but it should improve data consumption in the background.
This app would help many people in countries with low penetration of internet, example: Cuba where I live. But the excessive consumption of data limits its use.
To understand: 5MB of data to Cubans cost us 1.5USD. In about 24 hours I spent 5 USD.
If the developers could work in this aspect would be appreciated.

**Comment by r10s** [comment]
Thank you very much for your report. Yes, this is not 100% optimal and we will work on this issue sooner or later :)
As there is also a similar issue at https://github.com/deltachat/deltachat-core/issues/46 , I mark this one as a duplicate and close it.
