### ISSUE TITLE
location streaming permission issues

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#1851]
as a result of https://github.com/deltachat/deltachat-android/issues/1790

- [x] Add link to privacy policy in FAQ
- [x] add alert before location permission is not yet granted and needs to be requested

**Comment by r10s** [comment]
this is a blocker as without we cannot go to gplay.

**Comment by r10s** [comment]
> Add link to privacy policy in FAQ

@cyBerta not totally sure what this link/FAQ means here, what is missing is a statement in the policy imu

**Comment by r10s** [comment]
fixes are in https://github.com/deltachat/deltachat-android/pull/1919 and https://github.com/deltachat/deltachat-pages/pull/441
