### ISSUE TITLE
Only first image of MUA-sent message displayed in chat when all images embedded in message body

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1854]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-03-26).

- Delta Chat Version:
1.15.0-beta.

- Expected behavior:
When a message sent from a MUA contains images which are embedded in the body, all of them are displayed in the chat window.

- Actual behavior:
Only the first image is displayed in the chat window. (All images appear in a separate view after "Show full message..." is tapped.)

- Steps to reproduce the problem:
-- Wait for a message that has been sent from a MUA (e.g. Microsoft Outlook) and contains at least two images embedded in the message body.

- Screenshots:
-- Message displayed in Delta Chat for Android:
![image_2021-04-04_17-35-52_2](https://user-images.githubusercontent.com/51095533/113517914-35c09500-9583-11eb-9473-29121b18bbcf.jpg)
-- Message displayed in Delta Chat for Desktop (in comparison):
![Delta_Chat art jpg](https://user-images.githubusercontent.com/51095533/113517904-1cb7e400-9583-11eb-9497-1b7b1438cb89.jpg)

- Logs:
N/A.

- Message:
[mail.txt](https://github.com/deltachat/deltachat-android/files/6255117/mail.txt)

**Comment by r10s** [comment]
this affects only html-mails, or?

- for html-mails, this is by design. unfortunately, we cannot easily and reliably differ between user-generated mails with images and computer-generated mails with images - and the latter may contain tons of images flooding the chat, eg. rounded corners, facebook icons and so on. eg. sending an amazon-link via apple mail generates mails with j>80  images, same for newsletter etc.

- for non-html-mails, however, all images should be shown - if not, that is a bug :)

**Comment by gerryfrancis** [comment]
@r10s I just did some tests:

- Thunderbird simply ignores embedded images when a message is sent as text only, so it must be HTML.
- Outlook wants to send my corporate mails in text with HTML, although I changed the setting before.

**Comment by gerryfrancis** [comment]
I consider this to be a bug, since the message shows alright in the Desktop version.

**Comment by r10s** [comment]
> nobody knows whether it is the important one or not.

that's true, but in practice, it is not so seldomly the first one.

the alternative would be to show _no_ images, not sure if that is nicer. other alternatives that come into my mind are "too smart" or too complicated.

this all was discussed recently at https://github.com/deltachat/deltachat-core-rust/pull/2272 and https://github.com/deltachat/deltachat-core-rust/issues/1977 and linked issues.

so, things are better now as before, maybe just give it a try for some time and see where things can be improved (of course they can :)

**Comment by r10s** [comment]
nb: the artworks are both great! ❤️❤️❤️

**Comment by gerryfrancis** [comment]
@r10s OK, I should have known that Desktop is behind Android and about the discussions as well. My mistake. Thanks for the explanations, closing here...

Regarding the artworks: Thanks, but the flowers belong to my aunt who is a paintress, I just took a snippet of a picture from her and applied a caleidoscope effect in GIMP on it, and changed the colors. Her picture looks completely different. ;-)
