### ISSUE TITLE
I am making a fork

### ISSUE THREAD

**Issue by rreynaldo** [deltachat/deltachat-android#186]
Hello, I am making a Fork  DC for Android, to use it in Cuba, I have added some options such as reducing the size of the images, as well as erasing the message on the server, because if there will be another application to delete it would consume the balance. I'm adding other options, if your can suggest me some, that optimize data consumption. The code I downloaded it as indicated in the documentation, I soon make a fork to see the changes I've made. I would like to be told if there is any way to optimize the use of the data, and just collaborate with DC. Fork I've put chat53 I'm not sure if that can be done in terms of license and other terms. Sorry i was translate this text with google.

**Comment by r10s** [comment]
Hi rreynaldo,

great to hear that you want to do something with Delta Chat. For testing etc. a fork may be a good idea, maybe even later, however, of course, we would also be glad to get pull request that we can add to the core. Maybe with a switch or sth. like that, but this is the future.

For the end-user, there are good news: Different forks would be compatible to each other and can chat together - I think this is the most important thing :)

Best Regards
Björn

**Comment by testbird** [comment]
Hello, where is your fork? It seems you have not made it with button on the right side of the second row of github controls above. (It is not in the lists.)

**Comment by Ampli-fier** [comment]
Maybe it's a private fork named chat53 ... or he wants to name the app **chat53**.

**Comment by csb0730** [comment]
Hi @rreynaldo,
to save data consumptions and maybe battery consumption some ideas:
- only query "Inbox" folder for new messages, not all main folders or let user specify folders to be checked for new messages (option list). I think in my use case this could work. But pay attention to multi device usage. 
- don't do active query for new messages and wait for push notification from mail server (not shure if this works stable in every use case).
- enlarge (user configurable) interval to renew push connection and check for new messages actively after connection is established.
