### ISSUE TITLE
Full name of contact no longer displayed after selected in "New chat" contact list

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1861]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 10 on Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-03-26).

- Delta Chat Version:
1.15.0-beta.

- Expected behavior:
The contact name remains after the entry is selected to begin a new chat.

- Actual behavior:
The contact name is vanished after the entry is selected to begin a new chat. (Further analysis show that only some contacts seem to be affected.)

- Steps to reproduce the problem:
-- Select "New chat" from the three-dot menu.
-- Choose a contact from the list to begin a chat with. (Further analysis show that it should be one to whom you have not received a mail from, but already sent a mail to with a MUA.) (Result: The name vanishes as soon as the contact has been chosen.)
-- Go back to the chat overview.
-- Mark that (empty) chat with this contact and delete it.
-- Perform the first step again. (Result: The name is not displayed anymore and seems to be gone forever.)

- Screenshots:
N/A.

- Logs:
`04-09 11:36:47.347  6007  6066 W DeltaChat: deltachat-ffi/src/lib.rs:644: Failed to get chat for contact_id: Sqlite Error: QueryReturnedNoRows: Query returned no rows`

**Comment by gerryfrancis** [comment]
Aaahh!! I have just found out that it does not happen to every contact, only to those who have an email address like this: `alan.smith@example.com`. I have updated the steps to reproduce the issue...

**Comment by AndreaLattmann** [comment]
I can't reproduce the bug

**Comment by gerryfrancis** [comment]
> I can't reproduce the bug

@AndreaLattmann Neither can I, so I am closing here, thank you very much for confirming! :)

**Comment by r10s** [comment]
thanks for double checking this and all the other issues! 👌
