### ISSUE TITLE
Gallery and Documents tabs lacks more menu options

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1865]
In the chat's Documents tab you have only two options: clicking/opening the document or deleting it, you can't export the document or open in context, so you have to manually search for the document in chat.

In the Gallery tab you can open an element to then have access to more options but would be nice to have some of them directly in the Gallery menu

**Comment by r10s** [comment]
i think, we should add the option "show in chat" also the long-tap-menu for both, gallery and documents.

that way, you can proceed to the original message and do what you want to do from there. of course, having other options directly, would be an even larger improvement (but do not add "forward" there as that would also forward the attached text, that is not displayed, which may be unexpected :)
