### ISSUE TITLE
App crashes due to switching profile tabs while items selected

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1869]
- Operating System (Linux/Mac/Windows/iOS/Android): Android 10
- Delta Chat Version: master
- Steps to reproduce the problem:
  * open a group's profile
  * select some member as if you wish to delete the contact
  *  press the Documents  tab, menu is still active
  * press the top bar's back row
  * app crashes
  * the same can be done in the opposite direction, selecting a document and then switching to the settings/group tab, but it doesn't happens if you switch to the Gallery tab, **the issue is exactly between Settings and Document tabs** 
- Logs:

```
04-13 21:05:49.983  4069  4069 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window androidx.fragment.app.FragmentActivity.getWindow()' on a null object reference
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at org.thoughtcrime.securesms.ProfileDocumentsFragment$ActionModeCallback.onDestroyActionMode(ProfileDocumentsFragment.java:253)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onDestroyActionMode(AppCompatDelegateImpl.java:2694)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at androidx.appcompat.view.StandaloneActionMode.finish(StandaloneActionMode.java:112)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at androidx.appcompat.widget.ActionBarContextView$1.onClick(ActionBarContextView.java:174)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.view.View.performClick(View.java:7870)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7839)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.view.View.access$3600(View.java:886)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:29363)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7948)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-13 21:05:49.983  4069  4069 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by gerryfrancis** [comment]
Confirmed, nice catch! :+1:

**Comment by adbenitez** [comment]
if someone has any hint why this crashes? I could try to deactivate the menu when tab is changed but it bugs me it crashes exactly with Settings-Documents combination

**Comment by Hocuri** [comment]
You have a stack trace, which tells us what went wrong. If I filter out all unimportant information it says:
```
[...] NullPointerException: Attempt [to call] getWindow() on a null object reference
at [...] ProfileDocumentsFragment.java:253
[...]
```
The problem is that getActivity() in ProfileDocumentsFragment.java:253 returns `null`, which is not too surprising as the current fragment is not shown anymore. 

BTW if you press "Delete" instead of "Back" in the top bar, a similar crash occurs, this time at `org/thoughtcrime/securesms/ProfileSettingsFragment.java:276`.



> I could try to deactivate the menu when tab is changed

Sounds like a good solution. If we to be on the very safe side, we can additionally check for `null` everywhere `getContext()` or `getActivity()` is called in `ProfileSettingsFragment`.
