### ISSUE TITLE
ISSUE_TEMPLATE.md is ignored

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1878]
instead templates from https://github.com/deltachat/.github/blob/master/.github/ISSUE_TEMPLATE/ are used

if this is intended then the local template should be deleted?

would be nice to have a dedicated template for android, I tried to move the template to a ISSUE_TEMPLATE folder and see if it overwrites the global template, but it also hides the other links to community etc so also config.yml needs to be copied so it defeats the point of having the templates at the organization level. Still would be good to have the android-specific template, 

opinions?

**Comment by r10s** [comment]
having a dedicated android template maybe makes sense, we could ask for android version, device etc. however, we also had no problems before. all in all i do not have a strong opinion on that currently and would be fine with both :)

desktop seems to use the global template, so we should not delete it or so.

and: we should not try to assign tags as "bug" along with the template, there were bugs with that "bug" tag that took hours to finally fix :) https://github.com/deltachat/.github/pull/1 :)

**Comment by adbenitez** [comment]
see also https://github.com/deltachat/deltachat-ios/issues/1161 with a better description of the same problem over there
