### ISSUE TITLE
get no email

### ISSUE THREAD

**Issue by horald** [deltachat/deltachat-android#189]
Hello,
a nice programm. But I get no EMail-Answer. Delta.Chat send the email, but don't receive the answer. The answer I can only read in my Email-Client. How can I limit the error? Thanks.
kind regards,
Horst Meyer

**Comment by Ampli-fier** [comment]
Hi, can you provide more information, please?

What version of DC are you using?
Which e-mail client is used to read e-mail and how is it configured (IMAP/POP)?
What is the e-mail provider name (e.g. Google, Strato, ...)?
Do you have any e-mail filter configured?
In which folder do you find the reply message?

Thanks!

**Comment by horald** [comment]
>Hi, can you provide more information, please?
Hi! I will try.

>What version of DC are you using?
the latest. (Version 0.9.6)

>Which e-mail client is used to read e-mail and how is it configured (IMAP/POP)?
several. On my pc thunderbird, on my android mobile phone I do not know, I have a wiko sunny.
It is all IMAP configured.

>What is the e-mail provider name (e.g. Google, Strato, ...)?
For DC I use a 1und1-Email.

>Do you have any e-mail filter configured?
No.

>In which folder do you find the reply message?
What do you mean with folder? I get the EMail in the inbox.

kind regards,
Horst Meyer

**Comment by Ampli-fier** [comment]
Can you check two things please?

1. Have a look at the contact request: Click the three dots at the top, then on contact requests (Kontaktanfragen).
2. If you don't find the message in there, you can watch logs from Delta Chat by opening the Settings menu, scroll down to Info - About, click on it and then click on the text "v0.9.6 |Info" at the bottom.

**Comment by csb0730** [comment]
Is it possible to copy/paste the log? I can't do it.

**Comment by Ampli-fier** [comment]
Not in the current version from F-Droid (0.9.6), but it will be included in the next release.

**Comment by csb0730** [comment]
Another question: how to identify a dedicated email in the log? I can't find no message id or something similar into that?

Regarding _copy/paste_: A _save as_ to a file would be ok too (or additionally)?

**Comment by r10s** [comment]
Well, I think for now, a copy/paste ist just fine. Not too complicated to implement but handy to add to a chat or a mail. It may be, the whole stuff get reworked some time, I would not add to much effort into it at the moment.

**Comment by Ampli-fier** [comment]
The intention to check this log is not to 'find' the lost message, but to look for potential problems or error messages from Core.

**Comment by r10s** [comment]
should be fixed by https://github.com/deltachat/deltachat-core/commit/15a8ac7f44c34a9161f9f7357158cc0c769bbe9b and in Delta Chat 0.14.0 then. If the problem still exists, please re-open the issue.
