### ISSUE TITLE
allow viewing eg. pdf from contact request

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1890]
this is about the contact request chat that is available at "menu / contact requests":

when a contact request message contains eg. a pdf attachment, it may be useful to view/handle this attachment as usual - esp. if we push using the app more as an email-client, this becomes more important, as there will usually be many contact requests, parts of them with attachments - and you may want to see them before finally starting a chat. maybe just reading them from the contact requests is sufficient.

also, as links and "show full messages" work in contacts requests as usual, we should not make a difference here. maybe also images could be enlargeable, but that is even less important.

but: we should take care not to lose the option to finally _accept_ a contact request - if the file/image/whatever covers the whole bubble and there is no tap possible to accept the contact request (currently, taps outside the bubbles work as well, maybe that is sufficient - most messages are not only file/image/whatever)

i just rested 1.14.5 - also there, this does not work, so, this is no new issue and no degradation and not super-important.

**Comment by adbenitez** [comment]
not sure about  this, because would be hard to accept contact requests with images/files, and clicking in empty spaces to accept it is kinda of a hack (not easy to discover)

I would like at some point this contact requests could be reworked to be just another chat list, where you can see all contact requests as a single entry in the list, open the chat, see all messages from that contact and interact with documents and images like in a normal chat and have buttons at the end of the chat to accept, block etc. just like Signal and other apps do

**Comment by adbenitez** [comment]
something like this: 

![deltachat-2021-04-21-171630](https://user-images.githubusercontent.com/24558636/115622221-8e9f6580-a2c5-11eb-8cb6-3118c3965587.jpg)

**Comment by r10s** [comment]
yes, maybe. thanks for the image.

or maybe a button a "start chat" to the bubbles.

but, as this such changes should be done on all uis and as there is already some backlog, maybe do not add too much new ui for now.

not sure. but as said, i do not think that this is important just now, it just came into my mind when i noticed that [links do not work in ios contact requests at all](https://github.com/deltachat/deltachat-ios/issues/1169) :) 

however, as said, that is not super-important now, there are lower-hanging fruits and also more general issues for contact requests, https://github.com/deltachat/deltachat-core-rust/issues/2371 , trying to solve these "little things" first may also harm the broader view, so, i think we should close this issue for now and put it to [resurrection project](https://github.com/orgs/deltachat/projects/19)

**Comment by r10s** [comment]
reopening, i think, that can be targeted pretty easily after https://github.com/deltachat/deltachat-android/issues/1896 is done.

**Comment by link2xt** [comment]
Cross-referencing proposal by @Hocuri: https://github.com/deltachat/deltachat-android/issues/1896#issuecomment-827494316

The idea is to eventually replace "contact requests" chat with a chatlist similar to "archived chats" and allow to accept/reject at the top of the chat when it is opened. If this is done, anything done here will only be a temporary solution.
