### ISSUE TITLE
read receipts are sent when chat is opened while screen turns off

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1900]
read receipt should only be sent when messages are really displayed to the user.

if the chat is open but the screen is turned off, no read receipt should be sent.

if later the screen is turned on again, and the user sees the messages, the read receipts should be sent.

ios has the same issue, btw: https://github.com/deltachat/deltachat-ios/issues/1178

**Comment by adbenitez** [comment]
duplicate of #1850 ???

**Comment by r10s** [comment]
ah, thanks, yes, this is a duplicate - i even filed the original myself ... :)
