### ISSUE TITLE
Poor screenreader support

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1901]
there are buttons unlabeled, for example:
- send button
- global search button
- go back to chat list button inside chat
- when you press add attachment, the button to go back keeps the label of "add attachment" button

Also would be nice to add labels to the message status button (sending, sent, read, error)

Voice message recording button also lacks hints to tell the user to swipe up to lock and swipe left to cancel

**Comment by adbenitez** [comment]
there is even a crash when you do the "swipe with one finger" gesture to make the assistant read the selected element in the chat list:

```
04-29 03:27:37.643 29474 29474 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                 04-29 03:27:37.643 29474 29474 E AndroidRuntime: Process: chat.delta, PID: 29474                                                                                       04-29 03:27:37.643 29474 29474 E AndroidRuntime: java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable                     
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.widget.TextView.setAccessibilitySelection(TextView.java:14526)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.view.View.traverseAtGranularity(View.java:13988)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.view.View.performAccessibilityActionInternal(View.java:13903)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.widget.TextView.performAccessibilityActionInternal(TextView.java:13157)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.view.View.performAccessibilityAction(View.java:13807)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:691)                                                                                                                                                    
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:75)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1399)                                                                                                                                                         
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)                                                        04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)                          
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7948)        
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                   
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-29 03:27:37.643 29474 29474 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by adbenitez** [comment]
send button actually has a label but for some reason it doesn't work :/

**Comment by r10s** [comment]
which screen reader are you using? visually impaired reported that the overall state of accessibility is not that bad.

may, of course, have become worse over time, so - great you have a closer look at that.

**Comment by adbenitez** [comment]
@r10s I opened a PR, take a look at that, in general several buttons without description, emojis without descriptions, etc.

**Comment by r10s** [comment]
i see, thanks for taking care!

**Comment by adbenitez** [comment]
also I am using this apk recommended by Google to test accesibility: https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor

**Comment by r10s** [comment]
one question if you're on that: can you say if the chat-profile accessible without the chat-menu? (so by a "tap" on the title)

we were thinking several times to clean the menu up, it gets pretty filled over time ...

**Comment by adbenitez** [comment]
it is actually easier to tap in the tittle or avatar it says "tap twice to activate", with the menu you have two type twice to open menu and then search throw the so many options and tap twice to open profile

**Comment by adbenitez** [comment]
just to have something to compare with, in telegram there is no menu option to open profile

**Comment by r10s** [comment]
> it is actually easier to tap in the title or avatar 

great, that's good to know.

**Comment by adbenitez** [comment]
tapping the title in telegram says "tap twice to open profile", I have to investigate how to do this instead of the default "tap twice to activate"
