### ISSUE TITLE
Cannot share any message that includes file attachment

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1906]
- Android version:
Android 10.

- Device:
Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-04-30).

- Delta Chat version:
1.19.1 (nightly).

- Expected behavior:
A message that includes a file attachment can be shared with Delta Chat.

- Actual behavior:
A message that includes a file attachment cannot be shared with Delta Chat.

- Step(s) to reproduce the problem:
-- Mark any message that includes a file attachment and share it with any chat in Delta Chat.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/116739536-138c2c80-a9f4-11eb-92e1-f977099389d2.png)

- Logs:
N/A.

- Credits:
Reported by users "adb" and "Gh0stz" from verified Delta Chat group "Testing Delta Chat".

**Comment by r10s** [comment]
> Mark any message that includes a file attachment and share it with any chat in Delta Chat.

so this is from sharing from another app to Delta Chat? Or inside Delta Chat?

**Comment by gerryfrancis** [comment]
> so this is from sharing from another app to Delta Chat? Or inside Delta Chat?

@r10s No, it is sharing with Delta Chat from Delta Chat. ;)

> do you know if that worked before?

@r10s Sorry, no idea.

**Comment by Gh0stz0x** [comment]
I honestly hadn't tried it before.  
I have two versions of DC one stable and one dev.  
From the building I shared a file to the dev and the file was Null - 1

**Comment by Gh0stz0x** [comment]
The only way to "see" the file is to export it and rename it with the correct extension.
Only you have to know it first. 🤔

**Comment by gerryfrancis** [comment]
> From the building I shared a file to the dev and the file was Null - 1

@Gh0stz0x This can be reproduced with one Delta Chat client only, I did so with a nightly build.

**Comment by agutierrez25249** [comment]
I have been having this problem since the feature is implemented
