### ISSUE TITLE
OK and Cancel button invisible in "delete messages

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#1907]
OK and Cancel button invisible in "delete messages from server" message (see screenshot)

It's a screenshot of a friend. I have no idea what Android version or device is used.
Probably she uses a bigger font size set in sytstemsetting of her device.
Maybe a easy way to fix it could be to make the window scrollable?

- Platform (android/blackberry/anbox): Android ?
- Device: ?
- Delta Chat Version: 1.14.5
- Expected behavior: show all buttons
- Actual behavior: ok and cancel button invisible (see screenshot)
- Screenshots:
![deltachat-2021-05-01-163816](https://user-images.githubusercontent.com/6864851/116785877-29552c80-aa9c-11eb-8919-782752910c60.jpg)

**Comment by Hocuri** [comment]
Can you retry with a current nightly from https://download.delta.chat/android/nightly/? AFAIK I fixed this some months ago.

**Comment by webratte** [comment]
I'm sorry. My friend will never ever use a nightly ;-) And I cannot reproduce this problem.

So I think I have to wait for the next official Gplay release.

Thank you for your reply.

**Comment by webratte** [comment]
I just played around and could reproduce this problem with my own phone.
And I also run a earlier nightly.

In this nightly it's already fixed.
So you can close this issue.

Thank you again.

**Comment by r10s** [comment]
@webratte thanks for taking care!
