### ISSUE TITLE
check storage access

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1918]
another app-store issue, might be an issue even if not yet targeting sdk30, cmp. https://github.com/deltachat/deltachat-android/issues/1768, did not dived into details yet, however.

> Starting May 5th, you must let us know why your app requires broad storage access
> 
> We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.
>
> Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:
>
> Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
> Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.
> 
> Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.
>
> [Learn more](https://support.google.com/googleplay/android-developer/answer/10467955)

**Comment by Hocuri** [comment]
As we don't target API 30 (Android 11), this should be fine for right now. Sooner or later, Google will force us to target API 30, but it doesn't delay this release.

**Comment by r10s** [comment]
also here, i think, this is targeted by https://github.com/deltachat/deltachat-android/pull/2087 - at least, we are in gplay with api30, so there is no more pressure  from that side for now :)
