### ISSUE TITLE
Highlight "Subject" in "Message info"

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#193]
Hi @r10s,
only a small issue:

Would it be possible to show "Subject" text in different colour, font or style when mail is shown complete (for example in Contact Requests or Info)?

This would give a better overview :-)

**Comment by r10s** [comment]
Well, I think the whole "message info" can be reworked some day - but not now (unless there is another volunteer doing it), it is still _subject_ to change.

**Comment by csb0730** [comment]
Yes, change only the _subject_ text will be enough now
:-)

**Comment by csb0730** [comment]
Hello @r10s,
I often have the problem to identify clearly the subject text in the Info window. I would appreceate it very much to make at least a small tweak in showing the subject text between two simple text markers?

`*s* subject text *s*`
`--`
`message's body text`

This would be quite no effort in doing that and would help very much :-)

Next version?  ;-)

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .

**Comment by Ampli-fier** [comment]
I started working on this. This is what I currently have for the normal chat view:

![bold_subject](https://user-images.githubusercontent.com/22896574/37565502-729a75f8-2aa2-11e8-8d34-96425e1d78e3.jpg)

What do you think?

**Comment by r10s** [comment]
looks good (although i am not really convinced that this is necessary at all and leads to a more noisy view).
how did you detect the subject? just the text before the first hyphen?

**Comment by r10s** [comment]
however, thinking this over, i have some concerns: showing the subject in bold text would introduce an imbalance between mails and delta-messages - mails can have bold text, delta-messages not. This may result in additional desires for _more_ formatting options which, imho are not a good idea for a messenger. I would prefer a clean text-lasting layout.

otoh - maybe I am too pessimistic and have seen too many ugly html mails ...

Alternative ideas:
- show the subject in a lighter color - eg. a dark gray - this would also make the subject appear differently and make it recognizable but would not start the "formatting race" 
- maybe we can mitigate the noise by adding a special character - maybe ✉ (the unicode envelope) - in front of _all_ non-delta messages? this would not hilite the subject but all non-delta messages (just brainstorming, i am not sure if _this_ is a good idea, this would require more thinking)

In any case: I would not put too much effort into the layout currently.

**Comment by r10s** [comment]
okay, i have changed the window to the following:

![subject](https://user-images.githubusercontent.com/9800740/37571210-ec950d8a-2af9-11e8-98c4-3bddc6d23d16.png)

I think sooner or later, this dialog should be a complete rewrite and more a table-like layout, however, today this would more hinder further improvements - it is not 100% clear what to show there and so every additional information may result in a ui update which slows down development. So, for now, I would prefer a plain text that is very easy extensible.

**Comment by r10s** [comment]
this is the corresponding commit: https://github.com/deltachat/deltachat-core/commit/85fbab32910a6689af58c512aa57b179546ea314

**Comment by csb0730** [comment]
Hi @r10s, that's it.

Ok to close this issue :-)

**Comment by r10s** [comment]
great :)
