### ISSUE TITLE
Optinally keep logs for a longer time

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#1930]
We often had the problem that logs were not kept long enough. So, it would be nice to have an option to keep logs longer, i.e. not just log them using Android's `Log` functions, but keep them ourselves.

- We should still _also_ log them using Android's `Log` functions, as that's useful for debugging via adb.
- This should be an advanced option, we shouldn't just always keep tons of logs, for devices with low storage.

To decide:
- Should the core or DC-Android implement this? The core would have the advantage that DC-iOS can use it too, @r10s would this be useful?

**Comment by r10s** [comment]
there were several discussions about that, among others, issues are that that may drain the ssd much more than using android logcat (we discussed that with @VP-, however, more focused on prepare-message - log would be even more wasteful).

also, there are reasons, that logcat is limited and an "own" log would miss the system information.

so, all in all i would not go for that, i do not expect it to be very helpful compared to the effort.

however, the log as such can be improved, there is still a lot of waste in there, also eg. source file names and linenumbers are not helpful. as logcat limits by size and not time, that would also help on getting older information.
