### ISSUE TITLE
Can't share file with % in the file name

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#1939]
- Android version: 10
- Delta Chat version: 1.20.2
- Steps to reproduce the problem: try to share a file with a name like `test%20file.txt` the message text is shared but the file isn't

**Comment by devSJR** [comment]
I can confirm that.
Android 9
DC 1.20.2

When I sent the file via share then the file name gets changed to test%20file-1.txt 
An empty message is received on the recurved side.
