### ISSUE TITLE
Cant transfer Autocrypt key (Enigmail -> Deltachat)  (#279 again?)

### ISSUE THREAD

**Issue by gessel** [deltachat/deltachat-android#1941]
- Android version: 9 4.4.11-21276405
- Device: Note 8
- Delta Chat version: 1.20.2
- Expected behavior: Successfully open Autocrypt Setup Message
- Actual behavior: Bad setup code. Please Try again.
- Steps to reproduce the problem:
* Send autocrypt Setup message from Thunderbird -> Enigmail -> Preferences -> Transfer Settings -> Intiate Autocrypt Setup
* Get message in Delta Chat
* Select message -> Delta Chat initiates Autocrypt Setup Message PIN entry and pre-fills with first 2 digits.
* Enter the rest of the code.
*  -> 
Autocrypt Setup Message
Bad setup code. Please Try again.

- Screenshots:
- Logs:

I'm having the (same?) problem with Enigmail 2.1.9 (20201220-1657) --> Delta Chat 1.20.2 as Bug #279 . I successfully imported the Enigmail generated Autocrypt Setup Message into K9 and FairEmail (via OpenKeyChain 5.6 and 5.7 respectively... gotta update one phone).

The Delta Chat interface correctly shows the two "Passphrase-Begin" pin numbers, but won't accept the rest of the passphrase.

I've tried both the Delta Chat desktop client (Ubuntu 64 bit Version 1.15.5 (git: v1.15.4-1-g77948e7b)) and the f-Droid supplied client (1.20.2) and both give identical results:

Autocrypt Setup Message
Bad setup code. Please Try again.

Message Source (munged a bit)

```
Message-Id: EVfZKHVKvzzeUUEyJX8i3TJIriI-enigmail
Date: Thu, 27 May 2021 15:21:28 GMT
To: me@domain.com
From: me@domain.com
Autocrypt-Setup-Message: v1
Subject: Autocrypt Setup Message
Content-type: multipart/mixed; boundary="i3KoBpwcZuST3PgsIqwj6TEdYTPAySWVV"

--i3KoBpwcZuST3PgsIqwj6TEdYTPAySWVV
Content-Type: text/plain

This message contains all information to transfer your Autocrypt settings along with your secret key securely from your original device.

To set up your new device for Autocrypt, please follow the instuctions that should be presented by your new device.

You can keep this message and use it as a backup for your secret key. If you want to do this, you should write down the password and store it securely.
--i3KoBpwcZuST3PgsIqwj6TEdYTPAySWVV
Content-Type: application/autocrypt-setup
Content-Disposition: attachment; filename="autocrypt-setup-message.html"

<html><body>
<p>This is the Autocrypt setup file used to transfer settings and keys between clients. You can decrypt it using the setup code displayed on your old device, then import the key to your keyring.</p>
<pre>
-----BEGIN PGP MESSAGE-----
Passphrase-Format: numeric9x4
Passphrase-Begin: 62

wy4E2QMIydowH0Rq2t3g7Jsx62SiSImkvfSbyYFmmv1Rd/KvtNNj/Hnk2xx2
gejf0sYExWxNB4WNtFKdfMrl4FuMMTtMhD7W0024duqxNtMHdfhlDE5fLkX5
xxxXEYOjyOt28mo5vyFTw5hR2ReiXy2ix8R1kEqRflqv3+i8h2lLxuWIxfxv
Qfxx6/62sgiELh324Xq8Tl2wgkf6fWjfMu2iF8t5fjBLxf2ROx6SU57S2FEK
E22dx730uFxxJ4lxxk7IGBb2bGVj7KMh6sgb22YVr5F/Qqevw6+KeXvN2xmM
svKvFxfiFKSdiTIBW8KQdUqdir6GoWmotk2slEL6u/4lBxGhfJM2lNWBnFLi
sXx7v1bkjdEnd163i2Q4txIf2uT5DxiHJk7Kv2r1UJvlx7UEtX02bKWBrEfk
K02In5nfE2882mRsS6v4Y3443geX5dWx/qb722nDsxTKn+q24y5Jhb27WxbW
u2mKeUej11x1542bquRFBfxNWrs6sxX214N3O2egmqf6KxYm2j8BlF1vVRof
H0qS0R83dhjNxEKsROj2iXeBouXE2xrS+1D20NfH/MejKf7Kto20IfTNWo7E
UuUSmGkEfxoGf126HmJKfj738OYUOemfBd2VqY4x0wlxUeWnQUt5Dky0kGSf
mu2Bf2uYxlbxGxThQMNl85Yf22/XFYhqnD24Llikk82Ejo2Q+Vr8D6JKt+ig
if8qyxQ8KdD872WV5wL22ihEqsEk5MqKUGiwKhb22VwUj2B2FrYwLv4vfijQ
8On1rlfF2/rojE2R8b6KOHwttfEeENwEH/HNQNGjf47ILwO522w8frQ112lf
T2OD7rf0GgXDOwxghKBi4wbg0eoqtjSOLJ56/XdB2T+T6ViDxSnI2UBlm3Dt
LxW4H0Yowh/J6f5F8IHFlVfhTfWW3vb8723hvBYx4fx/wniy2r2fYdQSy8Sf
bVwN77r2S6r0x6qBkquxif62YiuxxxBMo2kseK2e7fSnNW2274qLBfO+b2Js
wiDLxHwW4odf3h4odeQymv2fDEOKJxHWfFGKrK2Nsx6ww52Fgv2n8fQ2/L2o
b7EoEtgw6tIMxOJtDS5WdB8gd/fJh6fKoJiK+YX67xhx+SjME2E+LdIHfDfT
Oy335xIjwvFFextKh+J/IOV7dJFT2tyVxounjnxYVKV2Mqfx+Gel56XHjw4X
fX2JVwX2RtQ/xVoxQ2dlYJjuofX7wINlDdksSbFSln0ku1UDDwln0+gIosWY
trbb1RT6hYoI2R2xQJfrY01M02fmg0w7oDMhf3uybJEf1rF27dN72/420DDj
8OLYKRtxDjwvh6Hf/7WSBkMN7Yd2wg/vVJGKu8fibXK5Ifx2v24WW04HJ//f
WfsHfOgK2XnxweFu7X8XM2BTuutkRI82x2/eddNW1f4Gm1RRj2xLS1g0n0r5
jf0SkbLKGsjwSQvWMI5r2OxBY5Jf76dxutwfOBJwu4KjFftmx07x+gQ+wt4L
xr+nug2VdHRGkHKxrD+k2fgnv3W65G6H72J55FwUY+wOjs60ykIqBYn/dV1w
n2xO2fxBLGnWxi3ktuExGsvfw/TxQDfK2BUoVowrIxMo222yjS1F6VLvoYF4
xy42v7ghbutxDvI0wYyN7lyDOk2O8RQBwI5Fx2fihGxgn/xFfyhU3rlxurfw
EVOTn22fSEh5s2u5m1Oobq7seBtnO22M7DB/y62yQeOxwRISfKlFGRrLH3Kw
vwRy8jXMYnNMDIod1f/Q2YMGy2BSHx2yRGFtwuL42meT/kBT2mxxWxxVEJxy
m4sksvk0+x4jL7+LDGwvMFeD/vKq76nM422fYfLXequGMn4fVLIuXnTu8hWh
Mvyt3fdf2xWvn0dUV01hjQuro2HXWVqeYNIYj+JMw+Rt8KEQ2gixrWlGguWr
SwxeI3WxdFJK2TXfjXX4OwX3QbHMHqgxuBeML2j12HyRU62/UBX4VIIsoHN7
L+wgN4gY7HK2M1fVDivxUk0SJ+kQd72wtBVLtT55VGxVIbI2Q704w2lxO0xw
ewoffGoUX2KS8q2q58/tx2OyyfF6wnsT3eETj23w7dOTtyXwTQwsQugGv4Dj
J24mxfjY1NWog2xkFhxxFd7/SihThkxek0o7H2jRgxn2H5gyshmx+8fgv6NF
2xV0YN3sx2roU8VudWKfgT6v1q4/q22k3R2DLbetGw+J12fs2q7r0yg/5eDJ
t2bf8D0SmfdTfILVFGL/2uoBh8LqNHwxExMfw2kJLfhV+VD4gKex5xTuUd2n
sg7hD1+2q2tSFwoSWXxkQx/6DTTmw20r7fBs+hgwf3xDn20R7ukeuGgBb/2T
Y1xs1w2xfOWuBHNH7vJ6FSmS2kXw25Dx8BfiUg==
=dk0U
-----END PGP MESSAGE-----
</pre></body></html>
```

**Comment by gerryfrancis** [comment]
@gessel Thank you for your report. Please check if the MIME part ends with this line:
`--i3KoBpwcZuST3PgsIqwj6TEdYTPAySWVV--`
(Note the double dash at the end.) Thanks in advance.

**Comment by gessel** [comment]
It does not.  (that section copied verbatim, the only munging was to the encoded GPG key block).    I just generated another with Enigmail and the following comes right from the outbox message source:
```
Message-Id: ZwIkl8bIiZ663VkcEk9DNi7WMnC-enigmail
Date: Fri, 28 May 2021 14:54:47 GMT
To: me@domain.com
From: me@domain.com
Autocrypt-Setup-Message: v1
Subject: Autocrypt Setup Message
Content-type: multipart/mixed; boundary="RvIZfZUhnnTdrdN5mevzmiZrQ2m1JTb2u"

--RvIZfZUhnnTdrdN5mevzmiZrQ2m1JTb2u
Content-Type: text/plain
```

**Comment by gessel** [comment]
Oops, sorry - my bad.  Here's a complete message with the attachment end boundary, which does end in "--" as it should - and is not recognized by deltachat as a valid setup message as above:

```
Message-Id: nf3RVPYJGUU8fpjy8d5Hb1ynvUV-enigmail
Date: Sat, 29 May 2021 17:40:54 GMT
To: me@domain.com
From: me@domain.com
Autocrypt-Setup-Message: v1
Subject: Autocrypt Setup Message
Content-type: multipart/mixed; boundary="d9AaflnR24ZNIcGanjIOPQDmCW20252Km"

--d9AaflnR24ZNIcGanjIOPQDmCW20252Km
Content-Type: text/plain

This message contains all information to transfer your Autocrypt settings along with your secret key securely from your original device.

To set up your new device for Autocrypt, please follow the instuctions that should be presented by your new device.

You can keep this message and use it as a backup for your secret key. If you want to do this, you should write down the password and store it securely.
--d9AaflnR24ZNIcGanjIOPQDmCW20252Km
Content-Type: application/autocrypt-setup
Content-Disposition: attachment; filename="autocrypt-setup-message.html"

<html><body>
<p>This is the Autocrypt setup file used to transfer settings and keys between clients. You can decrypt it using the setup code displayed on your old device, then import the key to your keyring.</p>
<pre>
-----BEGIN PGP MESSAGE-----
Passphrase-Format: numeric9x4
Passphrase-Begin: 75

wy4ECQMIu66i202YC8/gqMx2U0Xd3e8qRQE0uc/8teg3VYIlx2dEC1c8JwCc
R+ui0sYExTcWDj4elm8olx81OIj3jMJ5o8yw81OuhmOwG8xsSttWxCc1I26O
63cx133M/XX1tVWwitQlExMCTuscy2lY8E8xelx7R2mqOgXtUgUhSrQvU21E
leq2T4xClXeJSM/HehLjIwx+W7326OUS2R2dOR42YjvQEd8tC5WtV67Dg5yc
dsE03U/rixH531r358v2CeOm+h+SiL7HcgyLc86Gx0tx33Xvq5C4l32xc8oc
LOx8Yxuxg13mtxxlQQMlcJTuTM+c7CxDgLmXq0icG4I6cec8RQcxl3scuh16
1RsqWycxrlHuR32012u6TL/icVcxt45yOq8rds3Towx28ecgtQxMtW3g5051
3M12GV8iHGW6V8WJ22ir222c2mrS+M23Wq1dRIIOIxlUj1YhEU315tSWxtwY
1xw/33xecJ81tso80/wGcIHE05G1SJyI62j1EIl6EIxYRWlXc2Vdx81lcC3m
d288hXYi2D2O3lIylCJ2lc22xxx207dCcrLrYIex3c3X2TceM/l3ccW21182
2O5x2VS38DrHcEicxco3MW3Hs8LR/ciH4mD6ilewltjC7SY14rD2HLYRdgtC
6x+HjTt+YSIQxCe8vdLSW+7XRsldx11S3G1ciimoY1u2j73HQ2l88qlXXTqi
TSG2310E2S7YtJQUM7Qv+yxjl3dISG12q1t2vvcuWisccox7D3dcGxv4d7yl
JUcttGmyqRcLxj0EJml7RlQhR21qG3+wOR181ULCOcxs11/GxlYyhIw1locg
sJ7E2y8lHHSoc5MWV6W36d283hDtGi+te2yOGTQTos81JTxr8c2tGMi8E2t+
1i3802rxwt8SlTtvi1IlqjuxC1U2J1H2Tc5XcS2CWHR1D3tc3I/27mxH22eH
610uJG3olT3q1hyuliX2OxiOLeu0GM1dMx1/c1Q8o11JE2V3Jc33WuQ3xc18
c81c82lwt01li21DTXcc67MQegJ8CDDXM8XG16+cw+1LJE2oxXMY3mgQwVjm
jllEJ/+mcs5dlMv38lx2Xx1GR232y2yS3U0l84smrsUeLlc38jc2MgiDgv7l
x2L26tO+7wMlRExsrDVg87C6qWHL68dT8Ll2T0D14w8h8m3JLlx7E1Exr8LL
xOd51+8LIdcecvGJ6oRE/E86+SlYcs2280Olw+ooxdcJQ8+2c4T13uT6xxTl
eOO1e/7x0+8r0e3S3Jr10D33ehUrJ7xVq8MMm5m+8ycc3h2Eli6uYmW3xtxD
5oYQuSChwiQ3u5R1r33m5xTL18dSVSqLs33RCuRcrt2xtlsMoYTU8/Y2deG3
Hly58IVI3wlERYEJecCuvxjEO8r0887o73l3s2ehqlgYYl7WotLJi3VujGoD
oRl33TrcMJR883GD4DEumOs2GlolrW5cLjw2GicH01meHUR5mclcE25Ouey0
82t2Llc32XsGjmWHXX2lrhRCliMocc4r2cIx3h/y8L1/2R8toh2h1c1w62l/
yx8RL2Yxx5Qg5j1rU18mU5udcl201i1JeYXdR+5S01TQce13Wgm/y8t4dx8c
EC13lvcw18Wu1RsdR7cyCsxUcLR4U1Q2Yw31212s0Ymql2TH78DTh35ScWeV
wtRlTDJ7QD23u2Q/+QlM282SC81w7L2VcW0WxymqDE+HL2sWxmtv6i3tWjC+
3yg2+6V/YVs/mlXgO611xt3cHsgsV4Q613QE3HJcr5/x3TQvMCCg+cYr+25G
SX12GOh/1J2YULhgEyUDS2w87QIsqJcomH1mlm5d14WevCIsjJmS8C27dyc/
Ss54C3TEvuvsd66lQ8Xji3c6e0iyxT+q2l/g8yMUH3ESMWMvlU0HL52JcU8l
lIiulr+Wt6tXr82/l7STsLCiIm1hCT6r7D6S02lh86gmc4llLu3Xxcdw3xiT
3tEcYUvGmlY+mR8xul21T32c3WLY5q38cQR2UcRYTDlHtI1SI1OxOgrx/Y8Y
J3i32iYlj1ySOtqh0dR5/L2qj3u4+w02h71wRIcJJv1u233Gur5YUDgt3Tjs
lcWxri82uoRoqxJ3q8QE7I2xv32q7hojvicl63OSloTJ1oyWd2dlJJdDIhH3
848CI18uGGOqxulR0vxG5xcrWX1GvYIVUr2u6ov2cu/8Sq5cltu0lj34hlD7
uc+lily3O8Qjcl2Rcc33u8+1Oy83T1CGc325sGCWti8t1t+oWGycV1JxmDsh
3TwVto3+IeoccyvclSjh18Eo6djoD5GjGU0gTh+lOjtE+mRhst12O8/jRjiH
Djct78cc3ccyEGjy56cxC33G12qgm38MuEciiQ==
=+B1a
-----END PGP MESSAGE-----
</pre></body></html>
--d9AaflnR24ZNIcGanjIOPQDmCW20252Km--
```
Messing around with Muacrpyt now to verify the message.

**Comment by gerryfrancis** [comment]
@gessel Thanks for the update. Do you have your private key protected with a passphrase? If yes, please remove it and do the Autocrypt setup again. Delta Chat does not support passphrases for private keys.

**Comment by gessel** [comment]
Is there a summary somewhere as to why this isn't as horrifically insecure as it seems?  I'd think storing or even transferring an unprotected private key on, especially, a mobile device would be inadvisable, no?

**Comment by gerryfrancis** [comment]
@gessel Please have a look here: https://delta.chat/en/help#i-cant-import-my-existing-pgp-key-into-delta-chat . I believe that the main reason behind that decision has been expected user experience. It would be odd to enter the passphrase every time you send/receive a message. Please confirm if it works for you without a passphrase, thanks in advance!

**Comment by gessel** [comment]
Thanks for the ref, it will take a minute to digest the implications.  

What I'd expect to happen from  UX perspective is something similar to enigmail/PGP/etc. is that a passphrase is required per some user definable session parameters (every message, every hour, every day, every launch, etc.) and the unencrypted key is never written to media (on a portable device, flash, which may be a bit of a challenge).  The obvious risk is that there's no forward security - lose your device or have it taken at a border and your entire "secure" message history encrypted with that key is easily unencrypted.  To some extent the risk is mitigated by using device encryption, but only superficially  and obviously not in all cases (stolen/lost while in unlocked state, etc).

I'll take some time to understand the in-transit encryption for the setup message, but I assume that the key is sufficiently protected in-transit and only decrypted and stored in plain text on the device after the pin.  

My advice based on my current and clearly very limited understanding so far is that it is extremely dangerous to advise people to try removing their passphrases - that's advice that really could get people killed.  I'd strongly suggest that users be advised to either use a key that they already consider only suitable for in-transit protection and not protected at-rest or to generate a new key specifically for Delta-Chat, keeping in mind that at-rest protection is only as good as the weakest device file protection the user is running Delta Chat on.

That's fine - no different than most E2E chat programs.  The only risk is if a person who's threat profile requires considering the consequences of a lost/stolen/compromised device problematic were to actually follow the advice and remove their passphrase protection and then expose their crypto keys.

I really appreciate the support - it is clear now why the autocrypt setup message didn't work as expected.  Not a bug.  A feature.  I generated a new key on a device and exported it - the setup message imported into Enigmail and I simply added a note with GPG that it is insecure and for chat only and to remind myself not to export the public key to a keyserver.

**Comment by gerryfrancis** [comment]
@gessel Thanks for reporting back, herewith I am closing the issue. For general discussions I would like to recommend our [Delta Chat forum](https://support.delta.chat/), especially [this thread](https://support.delta.chat/t/a-usable-idea-for-pgp-keys-with-a-passphrase/151/13) regarding your case, the developers are listening. Thanks!

**Comment by gessel** [comment]
Thanks for the link - perfect!
