### ISSUE TITLE
wrong error message on inserting things from "Image keyboards"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1948]
when inserting eg. stickers from an "Image keyboard" (eg. gboard which is shipped with at least some systems), _after_ the sticker is inserted successfully, the image keyboard shows a toast with the error "Delta Chat doesn't support image insertion here":

<img width=300 src=https://user-images.githubusercontent.com/9800740/121092848-7ab7b080-c7ec-11eb-9627-2eb3bf3e4e2a.png>

the issue is true with or without https://github.com/deltachat/deltachat-android/pull/1947.

not sure, what we are doing wrong here, searching a bit, for [doesn't support image insertion here](https://www.google.com/search?hl=en&q=doesn%27t%20support%20image%20insertion%20here) , other apps seems to have similar problems. might be, it is related to some versions of gboard only.

https://stackoverflow.com/questions/49782842/google-keyboard-insert-image-send-intent-weirdness advice is to ignore SEND intents, however, i could not make much sense of that at a first glance.

Telegram, however, does not have the problem, i did not tested Signal/Whatsapp (cannot install currently - no spare SIM card :)

**Comment by r10s** [comment]
@adbenitez reported at https://github.com/deltachat/deltachat-android/pull/1947#issuecomment-857190174 that stock Samsung keyboard and with AnySoftKeyboard do not have that toast. so, it seems to be an issue only with some keyboards in some versions, maybe that is not fixable by us.

**Comment by Gh0stz0x** [comment]
@r10s I tried with Microsoft keyboard, Google keyboard, OpenBoard, AnySoftKeyboard, EweSticker and the problem does not occur (DC Android 1.34.12)

**Comment by r10s** [comment]
thanks for checking, then this is maybe only very few keyboards and affected devices. let's close this anyway stale issue, it seems not to be worth investigating further.
