### ISSUE TITLE
Add a function to star messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#195]
- messages can be marked with a star
- all starred messages can be shown in a "virtual" chat named "starred messages"

**Comment by Ampli-fier** [comment]
Do you think about adding?

- mark message as unread

**Comment by r10s** [comment]
Not yet, however, I do not think marking a message as being unread should increase the counter for the chat, all in all it would only be useful for multi-device? but I think this should be another feature request :)

**Comment by kollokollo** [comment]
Should the sender (or other group members) be notified, when one of his messages gets marked?

**Comment by r10s** [comment]
This is at least not my plan. My idea is only a method for quick finding messages and preventing them from possible automatic pruning (if this may be implemented some time)

**Comment by r10s** [comment]
duplicate of #158
