### ISSUE TITLE
unify appearance of user-generated links

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1950]
in bubbles, user-generated links are shown in text-color and underlined, i suggest to use the same appearance for the status/signature field (where they are currently more outstanding and shown in blue, similar to buttons otherwhere in the app):

<img width=300 src=https://user-images.githubusercontent.com/9800740/121396692-e9fbe480-c953-11eb-8700-385e92e68e0c.png> &nbsp; &nbsp; &nbsp; <img width=300 src=https://user-images.githubusercontent.com/9800740/121396715-eff1c580-c953-11eb-8621-77af73f8e1ce.png>

left: android, right: ios

elsewhere in android, links are shown as on ios, so i consider to adapt the appearance to just text-color+underline,

**Comment by Hocuri** [comment]
Not sure if that's the right time to start this discussion, but actually I like the blue links better, also WA and Telegram do it this way :innocent: (WA: Blue, not underlined, Telgram: Blue & underlined)

**Comment by adbenitez** [comment]
I don't have an strong opinion other than it should be the same everywhere,

with color it is clear that it is a link, with the same color than text it looks just like underlined text but anyway no one complained so far

**Comment by r10s** [comment]
i do not want to start a color discussion here :) the things is that we should use the same user-generated link appearance throughout the app.

so, i am not suggesting to do the same as on ios - i am suggesting to do the same as elsewhere on android.
