### ISSUE TITLE
Notification for new chat requests

### ISSUE THREAD

**Issue by karnotcycle** [deltachat/deltachat-android#1954]
I have set my setting to show all mails (classical mails). The notifications for ongoing chat is great but new chat requests don't come as poppy as the ongoing chat ones do.
This is the only bug that stops me from using delta on full fleged capacity.
Thank you for making such an amazing app.

**Comment by Hocuri** [comment]
Yip, it's on the wishlist (as lots of things regarding contact requests), see https://support.delta.chat/t/notify-contact-requests-lets-discuss-about-this/190/22

**Comment by Hocuri** [comment]
I'll close this issue here though, as the discussion already happens at the link I posted above :)
