### ISSUE TITLE
Possible null-pointer-exception.

### ISSUE THREAD

**Issue by textbrowser** [deltachat/deltachat-android#1967]
- Android version:
- Device:
- Delta Chat version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

deltachat-android/src/com/b44t/messenger/DcMsg.java 

 public static int[] msgSetToIds(final Set<DcMsg> dcMsgs) {
        int   cnt = dcMsgs==null? 0 : dcMsgs.size(); // If dcMsgs is null, cnt is set to zero. See below.
        int[] ids = new int[cnt];
        int   i = 0;
        for (DcMsg dcMsg : dcMsgs) { // dcMsgs == null?
            ids[i++] = dcMsg.getId();
        }
        return ids;
    }

**Comment by adbenitez** [comment]
in practice it is never null, but yes that method will fail if it receives null

**Comment by textbrowser** [comment]
Sure, however, the original logic suggested that it could occur. :)
Thanks for the correction.
