### ISSUE TITLE
Waveform for voice message no longer shown

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#197]
Don't know why, but since a while the waveform for voice messages is no longer shown.

**Comment by r10s** [comment]
maybe this is related to https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/191#issuecomment-352206550 [via #220 ]

**Comment by csb0730** [comment]
I think this issue is the same than #220

**Comment by Ampli-fier** [comment]
Closed after README update [3ecb5a4](https://github.com/deltachat/deltachat-android/commit/3ecb5a43308703b134d1f3241aa6e6507732bfcb): "dependecy on NDK 14b".

**Comment by r10s** [comment]
merge request for F-Droid:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2942
