### ISSUE TITLE
UI for Quota Report 

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#1973]
- [ ] A toggle switch in the settings to turn off the automatic(daily) check: config key is `disable_quota_check`
- [ ] (Optional) a button to request a quota report `dc_request_quota_report(context)`

see desktop pr: https://github.com/deltachat/deltachat-desktop/pull/2294

## References
- core pr: https://github.com/deltachat/deltachat-core-rust/pull/2462
- iOS issue: https://github.com/deltachat/deltachat-ios/issues/1296

**Comment by r10s** [comment]
i would postpone that until it is settled which ui is really wanted/needed and until core is merged. might be that at the end, there is no ui needed at all (info goes to connectivity, and maybe quota reports are "good enough" or we can detect wrong ones)

there is a pending desktop-implementation, it makes sense to wait until things are prototypes there.

**Comment by r10s** [comment]
closing this for the same reasons as of https://github.com/deltachat/deltachat-ios/issues/1296#issuecomment-883294529

prototyping may be done on android, however, this is another issue.
