### ISSUE TITLE
Retract posts

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-android#198]
Hi,
Sometimes a post (especially when written with auto correction) is sent, but you are not happy with the contents (due to automatically replaced words which changes the meaning or the blackout you had a moment before ;-) ).
If I can select the send post in the chat view and simply sent it again with an additional payload (like a command) that will trigger a delta chat core service on the target side to delete the original post and the resend message from chat and target mail box, I might be happier (or less ashamed).
That does not work if the post is already read or sent to a contact which does not use delta chat.

Beside the described use case, that feature is announced as new killer feature of whatsApp and will be so part of comparisons with delta chat in future.

I don't think that is a essential feature, but something nice and I think I would use sometimes.
Nevertheless, I would like to start a discussion here whether it is worth to implement, because it cannot be ensured that is is deleted before it is read. How to implement it (with a time limit or not) and whether we should copy features from other messengers or not.

**Comment by rizzopablo** [comment]
While I think it's goldplate functionallity in this moment, I think it
worth taking note and put it in a wishlist.

DC could even show a sign meaning 'retracted' message, and offer the
possibility to show the original post on demand by target user.

**Comment by r10s** [comment]
Technically, it would be possible in some way.

However, IMHO, the "edit posts" feature is more an anti-feature of WhatsApp or Telegram - you get and read a message and it may change in future. Seems to be okay for typo, but not for changing the context or the meaning. A little "edited" remark won't solve this issue. 

It also results in a false sense of security/privacy: You _cannot_ retract what is already delivered, eg. the user may have made a screenshot in between. 

Sending a second message for clarification seems to be much better to me solve all of the problem.

So, unless there are some additional volunteers working on this issue, for now, this is out of scope of Delta Chat. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .

**Comment by r10s** [comment]
see also https://github.com/deltachat/deltachat-android/issues/99 - Self-destructing messages

**Comment by r10s** [comment]
i'm closing this for now here; new new forum at https://support.delta.chat is the better place for feature requests and discussions.
