### ISSUE TITLE
titlebar with two lines looks weird

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1983]
with the new connectivity view, it may happen that some of the strings "Connected", "Not connected", "Connecting..." and "Getting new messages..." are too long and span two lines.

imho, this looks a bit wrong in the title bar, esp. as it changes fast to only one line.

i suggest to truncate the text right instead - and maybe add a translator hint to make the "Getting new messages..." as short as possible.

<img width=320 src=https://user-images.githubusercontent.com/9800740/126635448-2fb01f7e-8fe3-4788-a2bd-f3a742397cd6.png>

maybe "Getting new messages..." could also be reworded shorter, esp. as the _new_ is not necessarily correct. ~~maybe "Working..." or "Checking..." is better here.~~ i just checked the code, imu, it is actually about getting messages, so workin/checking seems to be a bit too broad.

**Comment by Hocuri** [comment]
If we go for a shorter word, maybe "Updating…"?

**Comment by r10s** [comment]
> If we go for a shorter word, maybe "Updating…"?

yip, nice idea! that would also fit for read-receipts, setup-contact and for sync-messages (future plans ... :)

if possible, however, i'd still ensure that the title does not break into two lines.
