### ISSUE TITLE
Marked single emoji not exchanged by pasted clipboard text in message input field

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1993]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2021-07-23).

- Delta Chat version:
1.20.5 (nightly build).

- Expected behavior:
When marked, a single emoji character in the message input field shall be overwritten when text from the clipboard is pasted.

- Actual behavior:
The marked emoji in the message input field is not overwritten by text from the clipboard when pasted. When the user taps the send icon afterwards to send the message, text from the clipboard is sent instead of the emoji character.

- Steps to reproduce the problem:
-- Open the chat "Saved Messages".
-- Enter "Test" in the text input field and tap the send icon to send the message.
-- Mark the message that has been sent and tap the "Copy to clipboard" icon from the top bar to copy the text to the clipboard.
-- Enter any emoji character in the text input field and long tap the emoji character to mark it.
-- Select "Paste" to exchange the emoji character with the text from the clipboard. (You will see that nothing has changed.)
-- Tap the send icon to send the message. (Result: The text from the clipboard has been sent instead of the emoji character.)

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/127489468-13fdaafe-1330-4f05-80f3-af21d15ecdc2.png)

- Logs:
N/A.

**Comment by Gh0stz0x** [comment]
I confirm this bug.
I also had this problem, but I never had the time to report it 😅

**Comment by Gh0stz0x** [comment]
The bug is still present in 1.34.12

**Comment by r10s** [comment]
@Gh0stz0x thanks a lot for going systematically through older issues, this is very much appreciated, +1

**Comment by AndreaLattmann** [comment]
I confirm this bug also in version 1.36.2

**Comment by AndreaLattmann** [comment]
This bug also in version 1.36.4

**Comment by adbenitez** [comment]
this issue is stale for years now and it is not a big issue, ex. it only happens if you try to paste selecting exactly one emoji, since it doesn't have big repercussions, ex. is easy to avoid, just delete the emoji first, in fact it is harder to select a single emoji to paste than just deleting the emoji and replace, and it is a rare situation, lets close this,

we are considering switching to system emojis as default for new delta chat installations this will make this issue even more rare

**Comment by adbenitez** [comment]
this issue is fixed by #3411 :tada:
