### ISSUE TITLE
new requests: chatlist updates lead to anr

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1994]
on recent master, i am getting anr (app not responding, ui frozen) when many messages are downloaded (eg. after getting online). i am pretty sure that this does not happen that often/badly before.

i assume, that this is because by #1975, `getChatlist()` is always called in the main thread and `DcChatlistLoader` was dropped.

there is a hint to the removed loader at https://github.com/deltachat/deltachat-android/pull/1975#issuecomment-886103166 - and i think, it makes sense to not use it on opening activity - but for lots of events received (as on updates), a background thread still seems to be advantageous.

when targeting that: i am not totally sure if `DcChatlistLoader` did actually _debounce_ things, but when fixing that issue, we can maybe do this, similar to https://github.com/deltachat/deltachat-android/pull/1884

not sure if that is a blocker, by using dc_accounts_t, this will be mitigated sometimes, however, i think, we should target that with some priority.

**Comment by r10s** [comment]
> not sure if that is a blocker

@adbenitez reports the same issue, so i think, this is a blocker and should be fixed before a release to avoid worsening.

**Comment by Hocuri** [comment]
> but for lots of events received (as on updates), a background thread still seems to be advantageous.

That should be very easy, just putting it on a background thread.

> i am not totally sure if `DcChatlistLoader` did actually _debounce_ things

Debouncing is a bit harder, but should be no problem, either.
