### ISSUE TITLE
new requests: flashing input bar after blocking

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1999]
after hitting "block" (not: "delete"), the input bar appears for a little moment, for a fraction of a second.

reason is probably, that, by calling block(), the chat is no longer a contact request and, by some event, initializeContactRequest() is called and the input bar is shown - as isContactRequest() is false.

it becomes more visible by fixing #1994, as the app is less blocked in main thread - but the bug is unrelated and also on current master.

**Comment by adbenitez** [comment]
I was able to reproduce and did an small fix
