### ISSUE TITLE
Problem with two-factor sign-in verification

### ISSUE THREAD

**Issue by YoungNFoolish** [deltachat/deltachat-android#20]
Hi,
first off, such a great idea man! surely it would be useful for everyone!
The two step sign-in verification is my problem to use Delta Chat! Actually when i tried to sign-in via my Gmail account, it ended with an error. Could you plz fix it?
Sorry for my bad english!

**Comment by r10s** [comment]
We know about this issue, however, currently it is not clear to me how this can be fixed. Any help on this point would be welcome.

In between, you can enable support for "less secure apps"
https://support.google.com/accounts/answer/6010255 (the name is a little bit misleading, of course, Delta Chat uses all secure standards, however, there seems to be some proprietary google stuff)

I've also seen some Googlemail accounts where a simple "UnlockCaptcha" is sufficient, see https://gmailhelp.com/unlocking-googles-gmail-captcha/

Again, if anyone can help on these points, this would be very welcome.

PS: Your english seems to be perfect, sorry for mine.

**Comment by petmos** [comment]
To my mind k9mail uses OAuth2 for IMAP, too.
https://github.com/k9mail/k-9/tree/master/k9mail-library/src/main/java/com/fsck/k9/mail/oauth
and
https://github.com/k9mail/k-9/commit/7774ebc788c8e33ac7994b6cea6614cbd4f68d81

Perhaps this helps you.

**Comment by LordTyrius** [comment]
I am also using google 2fa. I have enabled "less secure apps", but to use mail clients like kmail or delta I need to generate and use a special "!app password" for just that application. (More information: https://security.google.com/settings/security/apppasswords)

**Comment by danito** [comment]
I confirm that creating an application password works for Delta when you have 2fa enabled. (without enabling less secure apps). Thanks for the tip.

**Comment by SaintDI** [comment]
App password works well, but I strongly suggest to write a little tip message when new account is configured, because it isn't clear for average users.

> e.g. "Please, generate an app password on your mail account if you're use 2FA autentication method."

**Comment by ravilov** [comment]
Any chance of implementing OAuth2 in DeltaChat? I assume that's why we need to enable less secure apps in Gmail. I really hate having to enable that, plus it doesn't look well for an app that's trying to appeal to business users. Honestly having to enable that setting is right now the only reason I'm not using DC more seriously.

**Comment by rizzopablo** [comment]
+1

**Comment by r10s** [comment]
+1 :)
in fact, we just need someone who can do this resp. has the time to do so :)

**Comment by testbird** [comment]
> App password works well, but I strongly suggest to write a little tip message when new account is configured, because it isn't clear for average users.

> I really hate having to enable that [less secure apps] , plus it doesn't look well for an app that's trying to appeal to business users. 

Inform and warn users of providers working to collect data against their users AND their users' contacts interests.

**Comment by testbird** [comment]
Applies to configuring, sending and receiving.

**Comment by r10s** [comment]
i think this is targeted well enough by #336, at least for now, closing.
