### ISSUE TITLE
FR: Play voice messages through the ear speaker

### ISSUE THREAD

**Issue by luisfsr** [deltachat/deltachat-android#201]
When you didn't bring your earphones the only option to hear voice messages is through the speaker of your phone (the louder one, which play the rings and so). What if you could play those messages through the ear speaker (that one you use in normal calls)? That would be more discrete...

**Comment by r10s** [comment]
Maybe this would also be possible automatically when the user raises the phone to the ear (as it already works for recording when "Settings / Advanced / Raise to speak" is enabled."

**Comment by r10s** [comment]
> That would be more discrete...

didn't really get this issue. if you move the phone to your ear, the ear speaker is used and this is discrete imo.
otherwise you can of course decrease the volume.
