### ISSUE TITLE
0.9.8 F-Droid build failing

### ISSUE THREAD

**Issue by nebulon42** [deltachat/deltachat-android#204]
@r10s just to notify you that the build of 0.9.8 on F-Droid is apparently failing as in this log: https://f-droid.org/wiki/page/com.b44t.messenger/lastbuild_473

I don't know if you are involved with the build recipe on F-Droid, but if you are you might be able to fix this. :)

**Comment by r10s** [comment]
Thank you very much, I will have a look at it.

**Comment by r10s** [comment]
Okay, [0.9.9 is on the way to F-Droid](https://github.com/deltachat/deltachat-android/releases). As usual, this will take some day and I am not sure if this fixes the problem - locally, there was no problem with the build at all. But I am very optimistic :)

However, for now, I close this issue, but I would be glad if you add a new one if there are problems again.
