### ISSUE TITLE
share screenshot-from-external-app or text-from-external-apps easily continues to be displayed as draft

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#2040]
- Android version:7.1.1
- Device: LEMT DM100 (Uhrenhandy)
- Delta Chat version: deltachat-gplay-debug-1.22.0.apk | 59199980 | 2021-Aug-23 00:34
- Expected behavior: Image is sent, and does not appear again and again unsent in chat (_Bild wird versendet, und erscheint nicht  immer wieder unversandt im Chat_)
- Actual behavior:Image is sent, but keeps appearing unsent in chat (_Bild wird versendet, erscheint aber immer wieder unversandt im Chat_)
- Steps to reproduce the problem: - an image (01.jpg)
![image](https://user-images.githubusercontent.com/36864290/130384147-a84a27b5-7a55-4a33-a05b-b1e7f0cb8141.png)
 should be sent from screenshot easily
- Send -> DeltaChat
-> change program to DeltaChat
- enter text (to the picture)
- click send
- Keyboard can not be closed
- In the same chat the picture is available again unsent (02.jpg)
![image](https://user-images.githubusercontent.com/36864290/130384214-81239433-b7da-4d85-b9a5-54a85a8c525b.png)

- unsent picture can be closed (04.jpg)
![image](https://user-images.githubusercontent.com/36864290/130384249-d582fcc5-0ded-4d03-aa30-a2ceee746df8.png)

- the chat can not be left
-> Android menu last used programs
- DeltaChat is open twice (03.jpg)
![image](https://user-images.githubusercontent.com/36864290/130384288-4d832409-a4ba-4e76-9482-c192a59ab923.png)

- closed both DeltaChat programs manually
- DeltaChat started again
- operation is normal again
- problem does not occur when sending from gallery

Translated with www.DeepL.com/Translator (free version)
- Screenshots:01.jpg - 04.jpg
- Logs:deltachat-log-20210823-030851.txt
[deltachat-log-20210823-030851.txt](https://github.com/deltachat/deltachat-android/files/7028881/deltachat-log-20210823-030851.txt)

**Comment by gerryfrancis** [comment]
@icke68746 Many thanks for your detailed report, I just wanted to report this, what a coincidence! ;)

**Comment by icke68746** [comment]
The problem also exists when sending text from external applications via DeltaChat.
Or should we create a new bug report for this?

**Comment by r10s** [comment]
i adapted the title, this is really sth. we should target soon.

**Comment by icke68746** [comment]
Unfortunately no. I have had many versions, the previous one (1.20.5) already had the problem.
My wife now has the same version, but on a Samsung Galaxy S10 (Android 11) there it is also so.

**Comment by r10s** [comment]
> the previous one (1.20.5) already had the problem.

this is already pretty helpful information - so we know, the issue was not introduced by very recent changes.

**Comment by r10s** [comment]
there is a similar issue with some additional explanations at #2054
