### ISSUE TITLE
Sluggish performance after opening connectivity view while no network available

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2043]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2021-08-20).

- Delta Chat version:
1.22.0 (nightly build from 2021-08-24).

- Expected behavior:
No lags occur after opening connectivity view while no network available.

- Actual behavior:
Lags occur after opening connectivity view while no network available. Response time makes the user believe that the app hangs/has crashed.

- Steps to reproduce the problem:
-- Disable WLAN and mobile data.
-- Open connectivity view in Delta Chat.
-- Try to go back. (Result: Delta Chat barely responds.)

- Screenshots:
N/A.

- Logs:
N/A.

- Remark:
-- Quota info displays "One moment...".

**Comment by icke68746** [comment]
**DeltaChat responds quickly for me** (_Android version:7.1.1; Device: LEMT DM100 (Uhrenhandy); Delta Chat version: deltachat-gplay-debug-1.22.0.apk | 59199980 | 2021-Aug-23 00:34_)**. "One moment" is not displayed. Same on Android 11, Device: Samsung Galaxy S10** (_deltachat-gplay-debug-1.22.0.apk | 59199980 | 2021-Aug-23 00:34_)

**Comment by gerryfrancis** [comment]
@icke68746 Did you test with WLAN and mobile data disabled, so that your device cannot connect to the Internet? The issue might be related to quota information. If your mail provider does not support quota info, your Delta Chat app probably will not lock up.

**Comment by icke68746** [comment]
Yes, I did it according to the "Steps to reproduce the problem". I don't know if my provider (GMX) supports it.

**Comment by Hocuri** [comment]
Might have been fixed by https://github.com/deltachat/deltachat-core-rust/pull/2726

**Comment by Hocuri** [comment]
> -- Try to go back. (Result: Delta Chat barely responds.)

I had this in my mind differently, but this is exactly what I fixed in deltachat/deltachat-core-rust#2726, which means we can close this issue as fixed.

**Comment by gerryfrancis** [comment]
@Hocuri Confirmed, the performance is as expected now, thank you very much! :)
