### ISSUE TITLE
Constantly flashing error window

### ISSUE THREAD

**Issue by alexzh2** [deltachat/deltachat-android#2046]
After some time of using program, I have error that constantly flashing (appeared and disappeared) and I can't do anything in program. The flashing stop after ~5 min.

message: "smtp.gmail.com 465: failed to connect: transient 4.7.0: too many login attempts ..."

After flashing is stopped, the program not work - messages is not arrived to me. If I restart program the flashing begin again.

**Comment by alexzh2** [comment]
After some investigation I found that I have disabled IMAP on my server. I enable IMAP and reinstall program. Now it work fine. Maybe problem was with that. Anyway I think flashing window is not OK.

**Comment by Hocuri** [comment]
This could have been fixed in the connectivity view, which is in https://download.delta.chat/android/deltachat-gplay-release-1.22.1.apk. Could you re-try with this version if the problem is still fixed?

**Comment by Hocuri** [comment]
Nice, let's close this then!
