### ISSUE TITLE
Cannot loggin to Office 365 email

### ISSUE THREAD

**Issue by gochev** [deltachat/deltachat-android#2049]
- Android version: Android 10
- Device: OnePlus 
- Delta Chat version: updated August 26, 2021
- Expected behavior: To login 
- Actual behavior: doesnt login :) 
- Steps to reproduce the problem: Try to login with a company office 365 email

Automatic picking of IMAP and SMTP doesnt worked.
manually with this settings also doesnt worked

<html>
<body>

Setting | IMAP (incoming) | SMTP (outgoing)
-- | -- | --
Server Name | outlook.office365.com | smtp.office365.com
Port Number | 993 | 465 or 587
Encryption Method | SSL/TLS | SSL/TLS

</body>
</html>

**Comment by r10s** [comment]
@missytake do we have a test account for office 365? if so - does it work there?

**Comment by magic-ian** [comment]
Does your organization have IMAP switched on for their Office365? Do they restrict which specific apps can connect to their instance (e.g uses OAuth)? Do you only have this issue on Android?

**Comment by Micraow** [comment]
> * Android version: Android 10
> 
>     * Device: OnePlus
> 
>     * Delta Chat version: updated August 26, 2021
> 
>     * Expected behavior: To login
> 
>     * Actual behavior: doesnt login :)
> 
>     * Steps to reproduce the problem: Try to login with a company office 365 email
> 
> 
> Automatic picking of IMAP and SMTP doesnt worked. manually with this settings also doesnt worked
> Setting 	IMAP (incoming) 	SMTP (outgoing)
> Server Name 	outlook.office365.com 	smtp.office365.com
> Port Number 	993 	465 or 587
> Encryption Method 	SSL/TLS 	SSL/TLS

Please have a look at this:
https://github.com/deltachat/deltachat-core-rust/issues/3196

I met the same problem as you and solved it temporarily. However，It may go wrong some days later,  as microsoft will end the IMAP support forever. 😭

So we must use oauth2, but Microsoft accounts are not supported by Delta Chat,  either. 😢

It can only be used and cherished.

**Comment by Micraow** [comment]
> @missytake do we have a test account for office 365? if so - does it work there?

If you need it,  I can offer one for test.  Just email me at peng@pengs.top.

**Comment by buster** [comment]
> I met the same problem as you and solved it temporarily. However，It may go wrong some days later, as microsoft will end the IMAP support forever. sob
> 
> So we must use oauth2, but Microsoft accounts are not supported by Delta Chat, either. cry
> 
> It can only be used and cherished.

Is it true, that MS will end IMAP for everyone? Is there a source for this?

**Comment by r10s** [comment]
> Is it true, that MS will end IMAP for everyone? Is there a source for this?

i just checked my testing address, wXXX.XXX@outlook.com - i could login there even though i was not using it for a year, IMAP and SMTP works.

i am not sure, to which _exact_ addresses or services the "office 365" from above refers to - it seems, microsoft also changes this over time :)

so, if there is an issue with another microsoft services and that is not covered by https://github.com/deltachat/deltachat-core-rust/issues/3196 , please open a new, dedicated issue in core - there is probably not much, android can do about these things.

closing otherwise stale issue with no obvious actionable item left.
