### ISSUE TITLE
show landscape stickers/gif larger

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2056]
stickers are currently put into a sqaure, so landscape stickers are pretty small which is esp. bad as GIF may be send as stickers as well (we cannot really differ between them).

i suggest to leave the max. height for stickers as is, but instead of trying to put them into an imagined square, allowing them to be as wide as the other bubbles.

this sizing things are tricky, there might be some points i missed and that were discussed in the past.

this is how a gif sent from a samsing keyboard currently looks like, as said, a bit small:

<img width="322" alt="Screen Shot 2021-09-21 at 21 28 59" src="https://user-images.githubusercontent.com/9800740/134238238-77444832-90e5-4976-af4a-92d8cc7bc286.png">

**Comment by Tury23** [comment]
Cómo le puedo hacer para enviar la imagen

**Comment by Gh0stz0x** [comment]
@Tury23 It is not yet available, you have to wait for them to publish the new version.
You must have a bit of patience. 🙂
---
Aún no está disponible, hay que esperar a que publiquen la nueva versión.
Debes tener un poco de paciencia. 🙂

**Comment by r10s** [comment]
closing stale issue due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48); also, it seems okayish, looking at that again :) 

nb: stickers cannot be enlarged, that seems to be a larger issue in general, as the distiction between sticker and image is not always 100% correct on the sending device ...

however, just now, there is no actionable item of some importance.
