### ISSUE TITLE
Question to confirm deletion of device messages "on the server"

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2058]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2021-09-17).

- Delta Chat version:
1.23.0 (latest nightly build).

- Expected behavior:
When a user is about to delete a device message, the question should be `Delete 1 message?` only.

- Actual behavior:
Instead, the question is `Delete 1 message here and on the server?`.

- Steps to reproduce the problem:
-- Open the "Device Messages" chat.
-- Long-tap any message so it is marked/selected.
-- Tap on the rubbish bin icon.

- Screenshots:
N/A. (It is obvious.)

- Logs:
N/A.

- Remark:
This does not occur on Delta Chat for Desktop.

**Comment by r10s** [comment]
same for the deletion-dialog in the gallery.
