### ISSUE TITLE
Incoming messages from blocked senders are counted in the message counter

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#2062]
Android version:7.1.1

Device: LEMT DM100 (Uhrenhandy)

Delta Chat version: deltachat-gplay-debug-1.23.0.apk | 59319677 | 2021-Sep-27 00:34

Expected behavior: Incoming messages from blocked senders are not counted in the message counter.

Actual behavior: I get a lot of mails via mailing lists. In the previous version of DeltaChat (deltachat-gplay-debug-1.22.0.apk | 59199980 | 2021-Aug-23 00:34) these were not shown, although I set to show all mails. I have set it back to that in the current version, however now new messages are shown to me in the message counter, but when I open DeltaChat they are not because I have blocked them.
Translated with www.DeepL.com/Translator (free version)

Steps to reproduce the problem: -
- Screenshots: -
![2021_09_28_20 59 49_edit](https://user-images.githubusercontent.com/36864290/135149306-7ec4cb3f-620e-4ed6-8769-09889b22af00.jpg) (but all messages were read)
- Logs: [2021.09.28-DC.txt](https://github.com/deltachat/deltachat-android/files/7246636/2021.09.28-DC.txt)

**Comment by Hocuri** [comment]
> We have a new message counter? Either I completely missed this or your launcher is just counting the number of notficantions DC has sent. Which launcher are you using?
> 
> > but when I open DeltaChat they are not because I have blocked them.
> 
> Hm, does this mean that there are no notifications about them, either?

I'll go ahead and close this issue as @icke68746 didn't answer.

@icke68746 I'll be happy to re-open when you answer the questions I posted above; without them I have no idea how I could try to fix this issue.

In case the language is a problem, we can also write in German for once (obviously this has the disadvantage that others can't read our convernation then).

Falls die Sprache das Problem ist, können wir auch ausnahmsweise auf Deutsch schreiben (das hat natürlich den Nachteil, dass andere unsere Unterhaltung dann nicht lesen können).

**Comment by icke68746** [comment]
Oh, sorry I didn't realize there was a reply. English is ok, there is DeepL. 
I use the NovaLauncher, but the problem does not occur now. I use DeltaChat 1.28.3 in the development version from March 4, 2022.
----ORIGINAL----
Oh, Entschuldigung ich habe nicht mitbekommen, dass geantwortet wurde. English ist ok, es gibt ja DeepL. 
Ich verwende den NovaLauncher, das Problem tritt jetzt aber nicht mehr auf. Ich verwende DeltaChat 1.28.3 in der Entwicklerversion vom 4.März 2022.

**Comment by Hocuri** [comment]
Ok, nice!
