### ISSUE TITLE
Delta Chat notification always visible

### ISSUE THREAD

**Issue by francwalter** [deltachat/deltachat-android#207]
**Delta Chat v0.9.9**

After install of Delta Chat there is a notification which never disappears: 

Delta Chat
connected to me@example.org
Waiting for messages ...

Indeed it is german ("Verbunden mit me@example.org Warte auf Nachrichten ..." I hope my translation fits exatly.

I would prefer not to have always this notification, it is irritating. No other Messenger has it.

On a Cubot Note Plus with Android 7.0 (with root)

Thanks
frank

**Comment by r10s** [comment]
Hi frank,

regarding the reference: nice that you have found Delta Chat :) we're still beta but, with a growing community, things start working :)

Regarding the topic of this issue:
I would also prefer not to to have this notification, however, unfortunately, it is needed in some way, see #82

Best -
Björn

**Comment by francwalter** [comment]
OK. I understand. Thank.
I didnt know that Delta Chat doesn't use GCM.
Good.
