### ISSUE TITLE
Backup hangs and renders instance unuseable

### ISSUE THREAD

**Issue by thomas374b** [deltachat/deltachat-android#2074]
- Android version: 4.3
- Device: Galaxy S gti9003
- Delta Chat version: 1.20.5

- Expected behavior: saving backup to storage finishes

- Actual behavior: 
   The backup continues quickly to about 92..93% then it hangs forever. In folder /storage/sdcard0/Download
  a file delta-chat-****.tar.part is created. Despite the wrong extension  (probably unfinished tar process) the tar archive can be read to some extent but ends with some checksum error. Obviously the tar process has not cleanly finished.  After aborting the backup via the dialog box, the DC-instance becomes unuseble. All chatroom icons are black containing s single hash (#) mark. All texts and settings are gone. On closing and reopening the instance is requests entering the email-acount data as after a fresh install.

Screenshots are not possible to take in that situation. This action renders the phone unuseable in some way. Some data storage seems to get unmounted and remounted and some processes (taking screenshots, DC) refuse to work.

For DC one can solve the situation by tapping on  
    - Menu -> Manage Apps -> Active Apps -> Select DC -> Kill App 
    - Menu -> Manage Apps -> Active Apps -> Cached Apps -> Select DC -> Kill App 
    - restart DC
and all chatrooms / data / account settings are visible again and seem to work properly again.
      
But the problem of not beeing able to take screenshots remains until reboot. 

- Steps to reproduce the problem:
  I don't know which activity triggered the fault. Maybe it was the attempt to update to a newer version (see issue #2072). I recall that backups have been possible already with this instance and I have
  an older backup on that phone that was finished properly. I checked already, there should be enough space on storage to finish the backup
   - start DC
   - open your profile
   - tap on chatroom settings
   - scroll down and start "backup to external server"
   - wait for long time untill it hangs at around 92% (one hour should e realy enough)
   - press "abort" on the backup dialog

- Screenshots:
   - not possible

**Comment by thomas374b** [comment]
OK, I've got the new version 1.22.1 (APK checksum 0f9788eb1e52644318a3edaf84dd20d8) installed.  Installation
went OK. It took over my account data, chats and settings. There is only one DC icon in application Menu, but ...

 .. the backup problem persists, hanging at 93%. No screenshot possible while it is hanging on 93%.  

Better with this new version:
 - Screenshots are again possible after aborting the backup.
 - no blacked chatroom icons
 - no (virtual) loss off account data
 - no killing/restart needed 

This time I have a "adb logcat" and a "protocol" saved.
( ... still working on attachment ...)

**Comment by gerryfrancis** [comment]
Seems like the main thread is not aware that a backup is processed and repeatedly tries to connect to the SQL database which is exclusively locked to the backup process. The stop at ~92/93% could have been caused by this:

`I/DeltaChat( 7888): src/context.rs:267: Signaling the ongoing process to stop ASAP.`

**Comment by adbenitez** [comment]
@thomas374b  could you retry with the new version 1.28?
open this issue again if it keeps happening and provide logs, thanks in advance
