### ISSUE TITLE
Message sent despite Access Error for folder

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-android#209]
**Delta Chat version**: 0.9.9

**Expected behavior**

No message is sent, when a folder cannot be accessed.

**Actual behavior**

Message with this attachment is sent:
![screenshot_2017-11-30-15-33-57](https://user-images.githubusercontent.com/22896574/33483520-8060ab2e-d69e-11e7-9919-508f1ad6f6aa.png)
(the snapshot shows two, but this is due to two trials)

**Steps to reproduce the problem**

Start a new chat and click on the paper clip to select attachments.
Select a folder that cannot be opened due to permission problems, in my case:

![screenshot_2017-11-30-15-34-29](https://user-images.githubusercontent.com/22896574/33483587-d0c9dfcc-d69e-11e7-8286-e7483c28aa09.png)

A toast message is shown: Access error.
Then a message is sent as shown above.

**Debug logs**

Folder access prohibited:

`shell@GT-I9100:/ $ cd /mnt`
`shell@GT-I9100:/mnt $ ls -l media_rw/`
`opendir failed, Permission denied`
`1|shell@GT-I9100:/mnt $`

logcat when message is sent:

`29:28.327 D lights  : set_light_buttons: 1`
`29:28.516 V WindowManager: not Base app: Adding window Window{14991018 u0 com.b44t.messenger/com.b44t.messenger.LaunchActivity} at 12 of 16`
`29:31.458 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@141b15c4 attribute=null, token = android.os.BinderProxy@9ec33f0`
`29:36.032 D lights  : set_light_buttons: 2`
`29:40.492 D lights  : set_light_buttons: 1`
`29:40.784 I DeltaChat: T1: Attaching "/mnt/sdcard" for message type #60.`
`29:40.787 I DeltaChat: T1: Signal job thread to wake up...`
`29:40.788 I DeltaChat: T2: Job thread checks for pending jobs...`
`29:40.893 I DeltaChat: T2: Executing job #1, action 800...`
`29:40.902 D Yamaha-Audio: yamaha_mc1n2_audio_output_start()`
`29:40.902 D Yamaha-Audio: yamaha_mc1n2_audio_route_start()`
`29:40.902 D Yamaha-Audio: (yamaha_mc1n2_audio_params_route_find): device = 2, direction = 0`
`29:41.662 W DeltaChat: T2: mailsmtp_mail: delta1@xxxxx.xxx, Stream error (3)`
`29:41.736 I DeltaChat: T2: Job #1 delayed for 0 seconds`
`29:41.738 I DeltaChat: T2: Executing job #1, action 800...`

Values in database:

`INSERT INTO "msgs" VALUES(260,'Mr.WiAV1xxxxx4.delta1@xxxxx.xxx','Chats',337,14,1,278,1512052180,60,26,1,0,'sdcard','','m=application/octet-stream`
`f=/mnt/sdcard`
`c=1',0);`

**Code reference**
https://github.com/deltachat/deltachat-android/blob/b37a91cdd9447b6443abca06b987c9216bda1c66/MessengerProj/src/main/java/com/b44t/messenger/DocumentSelectActivity.java#L302

**Comment by r10s** [comment]
@Ampli-fier can you please check if the problem is fixed?

**Comment by Ampli-fier** [comment]
Done, the problem is fixed! 👍

**Comment by r10s** [comment]
Perfect :)
