### ISSUE TITLE
Pause background music when playing voice message

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#2091]
**Expected**: When another app plays music (like spotify or vlc) the music should be paused when starting to play a voice message.

**Actual**: Voice message is played without pausing the other music, which means that the voice message's content is not clearly understandable most of the time.

There is also the question whether to resume the music after the voice message has finished, but we don't need to tackle it in this issue:
Sometimes you may want to keep the pause, for example when you're listening to a chat full of voice messages, other times you might want the music to continue afterwards again so you don't have to manually press the resume button it.

**Comment by adbenitez** [comment]
related: https://stackoverflow.com/questions/15390126/how-to-stop-other-apps-playing-music-from-my-current-activity
