### ISSUE TITLE
Wrong wording on 'Help' (doc)?

### ISSUE THREAD

**Issue by riveravaldez** [deltachat/deltachat-android#2097]
Hi, in this section:

> **Can I reuse my existing private key?**

I think the word in bold is incorrect?

> Alternatively, you can **import** the key manually in “Settings” or “Advanced settings” and then “Import secret keys”.

Just that. Best regards and thanks a lot!

**Comment by Hocuri** [comment]
With "the word in bold is incorrect" do you mean "import"? What should it be instead?

**Comment by riveravaldez** [comment]
Hi, yes, I thought it should be "export", but now I'm re-reading and thinking that maybe it's correct (if the instructions are just to import the key from another client, and not to first export one from DC and then import it somewhere else).
I'm closing this because seems to me right now that it was just a misreading from my part. If not, please tell me what to do.
Thanks a lot and sorry for the misunderstanding.
Kind regards!
