### ISSUE TITLE
Option to limit history download

### ISSUE THREAD

**Issue by ghost** [deltachat/deltachat-android#21]
I would like an option to limit the amount of email history downloaded from the server. Perhaps options such as: 

- Past Day
- Past Month
- Past Year
- All
- None

**Comment by reallyBasic** [comment]
To clarify, I mean when the account is added.

**Comment by aHVzY2g** [comment]
Probably your issue should be moved to the "messenger-backend".

**Comment by reallyBasic** [comment]
@aHVzY2g Perhaps a second issue there. The front end still needs supporting UI.

**Comment by r10s** [comment]
As currently, Delta Chat does not download _anything_ on new installs, there is no need for a _limit_ on startup.

However, for an option to download the history optionally, see - #123
