### ISSUE TITLE
New contact request prompting =>? no import of current Chats and Groups

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#210]
Uninstalled 0.9.6, installed 0.9.9 and imported key, but none of the messeges on the server  got imported/visible.

**Comment by r10s** [comment]
This is by design of the current scope of the app.

Delta Chat does not restore messages from the server (BTW:  it has never done so, not sure, if it will do in the future. maybe if some else starts working on this point).

If you need to uninstall/reinstall the app, you can have to make a backup before.

**Comment by testbird** [comment]
Ok, I would have thought though that delta chat would have to sync with the INBOX and Chats folder, also to allow Chats send on DeviceA do appear on DeviceB.
https://github.com/deltachat/deltachat-core/issues/52

> If you need to uninstall/reinstall the app, you can have to make a backup before.

Well, but the backup would include the database, while I needed to start over cleanly because I suspected the db got out of sync with the server (pop/imap actions with other clients).

**Comment by Ampli-fier** [comment]
It worked for me to re-sync all messages from the "Chats" folder. I did this in _DC Core_ with an empty database, but I do not see any reason why it should not work on a phone.
It involves some hacking ... Do you have a rooted phone? Are you familiar with sqlite?

Basically, I updated the **lastuid** value of the "Chats" folder and DC fetched all messages with a higher UID value from the server after re-connecting.

`sqlite> update config set value=1 where keyname='imap.lastuid.1506603186.Chats';`

1506603186 is the **uidvalidity** value and specific for my mailbox. Yours will look different.

I did not test (yet) what happens, when some messages are already fetched.
**No warranty** that there are no side effects :)

**Comment by testbird** [comment]
Thank you for reporting your success. :) I tried to look up some of your words, but I don't think I will be able to try this. For an imap internals novice it sounds promising that sync details seem part of the protocol. https://stackoverflow.com/questions/9956324/imap-synchronization Is that "Mr email libraray" part of the DC implementation or a dependency that can already handle the imap sync?

**Comment by Ampli-fier** [comment]
From the referenced article:
> You should use the UID to detect which mails have been added or removed. Note that the content of an email can not be changed without also changing the UID

This fact is used by DC.

Imagine you have 5 mails in your INBOX with UIDs: 1, 2, 3, 4, 5.

You install DC and it does an initial connection to the mailbox/server. DC will look for the last mail, then write a "5" as a marker to it's local database. The mails with UID <= 5 are not fetched (they are not chats when DC was never used before). With every "IMAP fetch" action DC will check if there is a message with a UID > 5 and then fetch the message.
Imagine it is a chat message from another DC user. The mail will be moved to the "Chats" folder.

Now, for you the scenario is, that you **have** chats, and they are collected in the "Chats" folder. You started with a fresh installation (as you did not have a backup).

DC will read the latest UID value from all folder, also from the "Chats" folder. Imagine you have 20 chat (mail messages in "Chats") and the highest UID value is 25 (you deleted 5 for example). DC will use the same mechanism as for the INBOX. The marker for the "Chats" folder in DC database will be "25". Only the next message with UID 26 and higher will be downloaded.

Now you start hacking: Stop DC, enter the database and exchange the "25" with "1". On the next connection to the server, DC will download 20 message from "Chats" as the UIDs are all higher than the marker "1" ...

If you do not have a rooted phone, you can probably use the Backup function and copy the .bak file to a system with sqlite3 command. Open the database (the .bak file) with sqlite3 "_externally_" and hack the UID (with the sqlite command above). Then copy the .bak file back to the phone and restore it.

The remaining question would be if you can use **_any_** DC backup (e.g. one where you already have chat messages in local DC database), or if it would be better to use a fresh/empty installation. I think the empty one is better, you just would need to re-install your key to be able to decrypt the messages from the server.

These are the commands that you would need:

`% sqlite3 /path/delta-chat-2018-mm-dd.bak`
`sqlite> select * from config where keyname like "%lastuid%Chats%";`
`5|imap.lastuid.1506603186.Chats|576`
`sqlite> update config set value=1 where keyname='imap.lastuid.1506603186.Chats';`
`sqlite> .quit`

Only adapt the **uidvalidity** in the update command with the one that is printed in the line above (starts with "5|...").

**Comment by testbird** [comment]
So on fresh installs, DC currently always assumes that all emails on the server are regular emails, and no chat messages. And you're suggessting if DC would by default start with lastuid=1 even for newly discovered folder/lastuid combinations, it could fetch the current state from the server? Sounds like a perfect default to make good use of sending a setup message to another device.

**Comment by Ampli-fier** [comment]
> So on fresh installs, DC currently always assumes that all emails on the server are regular emails, and no chat messages

It's my own interpretation when I look at how DC works and from reading the code (+ the comments inside :)) and the database content. There is only r10s who can tell about the intentions.
Setting lastuid to 1 for **all** folder cannot be a good idea. That would result in far too many messages getting downloaded. Probably for the "Chats" folder it makes sense.

> Sounds like a perfect default to make good use of sending a setup message to another device.

I don't understand what you mean. No messages are sent between devices ...

**Comment by testbird** [comment]
> Setting lastuid to 1 for all folder cannot be a good idea. That would result in far too many messages getting downloaded.

Existing (regular) emails outside the INBOX or the Chats folder (or "E-chat" if the new name may be an abbreviation of the [Email-chat specification](https://delta.chat/en/spec)?) would not need to get downloaded to the database completely, only the contacts need to get saved to keep track when they qualifiy as *known*. 

Your comment also made me realize why I naively expected, and would still expect DC to show at least the subjects from (chat) messages on the server. I think with every MUA I know one sees what is on the server, and most implemented some local caching for performance. The reason probably is that showing/listing is a requirement for deleting messages. After realizing that, I looked into the Chats folder and after a couple of installations it really looks there are more message on the server than I can see (and delete) in the current DC install.

I think for fresh installs first fetching the chat folder with lastuid=1, then the INBOX and all others would make sense. Thanks for your howto, I will try your hack.

> I don't understand what you mean. No messages are sent between devices ...

I was referring to the future setup messages that allow to easily transfer your key, shown [here](https://delta.chat/en/2017-12-21-34c3-and-other-news) is a transfer to thunderbird.  Let's say one installs DC on a new tablet, and one transfers the key by sending a setup message to oneself, one would most probably expect the new install to pick up the chat messages from the server (allowing to continue open chats). The imap design and your tests already suggest it may work.

**Comment by Ampli-fier** [comment]
Before you try "the hack" ... make sure you configured the account and imported your key pair **first**. Otherwise messages won't get decrypted on (down)loading.

I think the order of the messages in the database will become unsorted, but when DC displays them it will use the date and time information for sorting.

I still did not test on Android. In Core it looks like the "read receipts" are handled correctly. So the information that own messages were read by the recipient(s) are preserved.
Question would be, how it looks when the user deleted chats but not the read receipts and vice versa (e.g. with K9). There might be an unpredictable/unwanted behaviour that falls back to DC but is caused by "actions outside" of DC ...

**Comment by testbird** [comment]
> Before you try "the hack" ... make sure you configured the account and imported your key pair first. Otherwise messages won't get decrypted on (down)loading.

Ok.
The setup message with the key might only be downloaded after older messages, however, in many cases as the last message.

**Comment by Ampli-fier** [comment]
Just to let you know that the sqlite commands from my posts above do not work any more from versions 0.14.0 onwards.
