### ISSUE TITLE
Older backup might be automatically suggested to restore account data

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2111]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2021-10-29).

- Delta Chat version:
1.23.0 (latest nightly build).

- Expected behavior:
Delta Chat always suggests the latest backup available to restore account data.

- Actual behavior:
Delta Chat not always suggests the latest backup available to restore account data.

- Steps to reproduce the problem:
-- Perform two backups on the same day (e.g. today), one after another ("Settings" -> "Chats and Media" -> "Back Up Chats to External Storage" -> "Start Backup"), and wait until the processes have finished. (The file names could be like these: `delta-chat-backup-2021-11-03-00.tar` (1st backup), and `delta-chat-backup-2021-11-03-01.tar` (2nd backup).)
-- Open the "Files" (or another equivalent) app, and locate the backup files in the `Download` folder.
-- Delete the file `delta-chat-backup-2021-11-03-00.tar`, or rename its file name.
-- Perform another backup on the same day. (Result: The name of the first file - its name ending with `00.tar` - will be applied to the backup file.)
When account data must be restored later on, Delta Chat generally interprets `*01.tar` to be a younger backup file than `*00.tar`, but that can be wrong obviously...

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by adbenitez** [comment]
that is something expected if you rename backups, at some point would be better to let manually select backup file I guess

**Comment by r10s** [comment]
closing stale issue, i also think, the behaviour is okayish.

also, with #2493 backups will become less important, so that this situation will be even more rare.

**Comment by gerryfrancis** [comment]
@r10s @adbenitez  Sorry, I totally forgot about this one! Now that we are able to select any backup file, this issue is no longer valid anyway. Thank you for closing! :)
