### ISSUE TITLE
Further improve QR activities

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#2114]
Follow-up for #2103, see https://github.com/deltachat/deltachat-android/pull/2103/files#r742725602: Extract a method from `DcHelper.openForViewOrShare()` that doesn't take a msg_id but directly a file.

**Comment by r10s** [comment]
closing stale issue, not totally sure what this was about, please reopen and refine if needed.

maybe related: as an enhacenment for sharing QR codes, there is also there is [i.delta.chat](https://github.com/deltachat/invite) upcoming
