### ISSUE TITLE
needs a visual way to tell is encryption is active

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#212]
From what I can tell
They're is no simple visual way to tell if the conversation is encrypted, if the message you are sending is encrypted (or expected to be encrypted)or if the message you received was encrypted or not.
Somewhere Something like a little red openlock or red eye to say no encryption was used would be nice.
Or a green indicator to say encryption is in use and all is encrypted.

**Comment by testbird** [comment]
I see lock symbols for sent messages. If the last message you received has a lock, that might imply your answer will also get one. (Can someone confirm?)

**Comment by rickcrash** [comment]
Yes. The lock marks encrypted messeges sent and received ones. Once kne message is encrypted, the next messages should be encrypted too.
After install it takes some time to start encryption.

**Comment by nutpantz** [comment]
To be honest even though im using a note 3 i could not tell what that little icon was.
I never even noticed if it was there or not on messages.
Maybe it should be a little bigger and color coated like red for not encrypted and green for encrypted. Either way definitely a little bigger as I know if I missed it's significance my encryption novice friends will never see it.

**Comment by testbird** [comment]
Showing a lock symbol on the send button would be nice, and rather direct than implied.

**Comment by r10s** [comment]
+1 for a rethinking of the lock and the state shown in the ui

**Comment by testbird** [comment]
It seems the new features, that may have been inspired in part by this wiki page, also introduced a different type of trust state for contacts that is not equal to a contact with a verified key but visualized in the same way as verified contacts.

See disussion at: 12a765e

I'm not sure but IIUC these contacts use keys that have only been passed around, and in the course have been passed on as (automated) gossip by a verified contact.

**Comment by testbird** [comment]
A distinction might be possible like this:
 "✓" meaning "verified" by oneself
and  "o" or  "(✓)"  meaning claimed to be verified by verified? other

**Comment by webratte** [comment]
I just opend a new issue https://github.com/deltachat/deltachat-android/issues/312 but found this.
I think it's better to extend this issue.

The user should be warned if a message will sendet unencrypted.
E.G. show a popup window "This message will be sendet in clear text." Maybe with te option "Don't show again" or "Don't show again for this receiver".

So the user have the choice to change the content if it's very confidential and should be encrypted (after And user should be warned if a message will sendet unencrypted.
E.G. show a popup window "This message will be sendet in clear text." Maybe with te option "Don't show again" or "Don't show again for this receiver".

So the user have the choice to change the content if it's very confidential and should be encrypted (after keys are exchanged via autocrypt) or it's a trivial content and can be sendet unencrypted. are exchanged via autocrypt) or it's a trivial content and can be sendet unencrypted.

**Comment by r10s** [comment]
i think the initial issues, the missing locks, are now available in general.

meanwhile, there are also experimental groups that enforce encryption.

for an indication about the state of the sending message there is a more concrete issue at #249

**Comment by monperrus** [comment]
In the UI, I don't see any encryption icon to know whether a message was encrypted or not.

Has it been removed or is there some configuration to activate?

**Comment by r10s** [comment]
there is a little lock beside each message that shows if a message is encrypted+signed or not.

**Comment by monperrus** [comment]
On my DeltaChat Android version 1.12.5 I don't see a single lock 
(neither locked or unlocked). Any idea why?

**Comment by r10s** [comment]
> On my DeltaChat Android version 1.12.5 I don't see a single lock

not even when you send a message to the "Saved messages" chat?

this is what it should look like:

<img width=400 src=https://user-images.githubusercontent.com/9800740/92098483-96170a80-edd9-11ea-9b99-b2f8353202df.jpg>

with long tap on a message you can get some more info.

of course, the locks appear only when a chat is and can be encrypted - this requires autocrypt-capable clients on both/all ends and the clients to have "prefer encryption" enabled (see settings/advanced)

**Comment by monperrus** [comment]
> not even when you send a message to the "Saved messages" chat?

I don't have a "Saved messages" chat

> this is what it should look like:

Thanks, I confirm it does not look like this, even on a conversation with somebody who has Autocrypt encryption (the messages are indeed encrypted, I cannot read them via regular IMAP), there is no locker icon.

**Comment by monperrus** [comment]
>  you can recreate it by creating a chat with yourself or by reinstalling the app.

I confirm that I can recreate "Saved messages" by sending a message to myself and the message there has a locker icon

**Comment by monperrus** [comment]
> how does it look like? what does message-info tell? 

Sent date, received date, but nothing related to encryption

**Comment by r10s** [comment]
> I confirm that I can recreate "Saved messages" by sending a message to myself and the message there has a locker icon

k, so the locker icon as such exists and the initial issue is confirmed to be fixed.

for the other chats:

i would assume that one of the recipients in some chat is not using Delta Chat or an Autocrypt capable client or has disabled encryption and therefore encryption is not activated.

by adding a send device with Delta Chat or by a second account (main menu / switch account) you can find out if you can create an encrypted chat.

**Comment by monperrus** [comment]
Thanks a lot @r10s, I'm making progress. I do send messages to another Delta Chat device, I'm debugging.,

**Comment by monperrus** [comment]
OK, it works with proper autocrypt.

FYI: some encrypted messages with PGP without autocrypt headers don't have a locker icon while indeed encrypted, but that's a corner case.

**Comment by r10s** [comment]
thanks for figuring that out and reporting back!

**Comment by monperrus** [comment]
FTR,  in Delta Chat version 1.36.5, encrypted messages with PGP without autocrypt headers do not have a locker icon (happens for both Thunderbird and Evolution encrypted messages)
