### ISSUE TITLE
Notification links not localized after different language selected

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2128]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2021-11-05).

- Delta Chat version:
1.24.2 (latest nightly build).

- Expected behavior:
Links in Android notifications (e.g. "Reply" and "Dismiss") are displayed in the priorily selected language.

- Actual behavior:
Links in Android notifications are not displayed in the priorily selected language. Delta Chat must be stopped and launched again to achieve this.

- Steps to reproduce the problem:
-- Change the language ("Settings" -> "Appearance" -> "Language").
-- Wait for a message notification for an incoming message. (Result: The links are displayed in the former language.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by Hocuri** [comment]
I think it's OK to leave things as they are, our efforts are probably better spent elsewhere and every change we make usually increases code complexity.

And if the user just switched languages, then chances are good that they know both languages and it's no problem at all

**Comment by r10s** [comment]
for new notifications, the links are probably okay then?

i agree, it is not worth, amending already fired notifications and messages.

**Comment by r10s** [comment]
for newly added notifications, the string is reloaded, see https://github.com/deltachat/deltachat-android/blob/eb75aaae1aa91ccffcc2c8b06feecec17f67b8b1/src/org/thoughtcrime/securesms/notifications/NotificationCenter.java#L430 - but sometimes, there is some localisation hickup, after some more redraws things are usually fine. i also noticed that sometimes in the menu and on rotating the device, not sure where that comes from, maybe some caching somewhere.

> And if the user just switched languages, then chances are good that they know both languages and it's no problem at all

i agree, it seems not worthable throwing time at that. for the "normal" users, this is not really an issue - more for devs and testers, switching languages often.

**Comment by gerryfrancis** [comment]
Maybe related: The whole quota page does not refresh after the language has changed. (E.g. the default system language has changed from English to German. Only the title bar says "Verbindungsstatus" (German), the rest is held in English.) Going back and reloading the page does not help, only a shutdown and relaunch of Delta Chat does.

**Comment by r10s** [comment]
i think the comment from https://github.com/deltachat/deltachat-android/issues/2128#issuecomment-968090888 is still valid. i would not spend time in chasing such rare shenanigans as long as there are larger bugs ::)

**Comment by Hocuri** [comment]
I'm just going to go ahead and close this, if someone things this is important we can re-open :)
