### ISSUE TITLE
get it on app store

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#214]
How does the roadmap, timeline, and the remaining blockers look like to make it into the unfree app store?

**Comment by r10s** [comment]
well, we won't go to google play & co. before we're stable and the remaining "show stopper" issues have been fixed.
currently, i cannot tell how long this will take as it also depends on how many help we will get.

**Comment by testbird** [comment]
Ok, thanks I know how it takes iterations to reach something stable. Maybe adding a Milestone or just an "app store requirement" label to issues could give people an idea what you want.

**Comment by r10s** [comment]
Yeah - this was also my idea, to to create a milestone 1.0 here on github where all issues that have to be fixed are collected. just didn't found the time to do so yet  ...

**Comment by r10s** [comment]
i've just create a milestone: https://github.com/deltachat/deltachat-android/milestone/1 :)

**Comment by testbird** [comment]
Hey, thanks nice things are developing lately!

**Comment by r10s** [comment]
:)
