### ISSUE TITLE
Add "Last seen: ..." line to profile

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2142]
Use the new `dc_contact_get_last_seen` API added in https://github.com/deltachat/deltachat-core-rust/pull/2823

There is currently no `DC_EVENT_CONTACTS_CHANGED` event emitted when last seen time is updated, but it's ok to only update when the contact profile is opened.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/2144
