### ISSUE TITLE
Disable the debug command execution option

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#215]
currently, the user can execute some special commands using "Settings / Name and status / My name". To do so, he has to prepend the command by a dot.

Eg. try to enter `.help` there.

For the 1.0 release we should get rid of this (historical) option or move it to a separate function at "advanced settings"

![image](https://user-images.githubusercontent.com/9800740/34003208-ff13c09a-e0f4-11e7-843d-bcf38aa4e273.png)

**Comment by csb0730** [comment]
My recommendation: move it to "advanced settings".

**Comment by testbird** [comment]
I think this feature should remain available, it's still required to solve other problems like #294.
Or does it expose critical things that warrant a need to remove it?

**Comment by r10s** [comment]
we will leave the feature in _this_ app.

however, for security reasons and also because it is very easy to damage things this way, we won't add a command line option in the new apps. also when it comes to security reviews such an option may result in a  lot of unneeded questions.

things as "cleanup contacts" might be added as a core feature then.

of course, i am speaking about the end-user-app only, as Delta Chat is full open source, of course, there can be "power user" apps at any time :)
