### ISSUE TITLE
Login with Google Workspace on a .net domain results in invalid email

### ISSUE THREAD

**Issue by rafaelwv** [deltachat/deltachat-android#2151]
Hi,

I'm using Delta Chat with Google Workspace, former G Suite, former Apps for Business with and .net TLD. This worked until the last update like a charm. Now I've been logged out and can't retrieve any oauth token, the sign-in wizard shows a toast: invalid email address.

Workaround: Use app-specific password. However this is not nice, the Oauth token was renewed (at least in the past) when needed and was easy to re-auth (browser based). 

I also tried to add the account again but was greeted with the toast "invalid email"

**Comment by rafaelwv** [comment]
For testing purposes I can provide a test user on my domain.

**Comment by rafaelwv** [comment]
![Screenshot_2021-11-26-16-25-16-615_chat delta](https://user-images.githubusercontent.com/46530865/143602627-2eb615cb-1777-4401-8061-46a75424733f.jpg)

**Comment by r10s** [comment]
it would be great if you can provide a test account, you can send that to the address shown at https://delta.chat/en/imprint (delta at merlinux dot eu)

**Comment by rafaelwv** [comment]
@r10s testaccount created and active, credentials shared. The account has 2SV enforced like my own so you will need to setup a time based OTP or something similar.
