### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by xunil89** [deltachat/deltachat-android#2154]
I report a rather strange bug. I have a multi account one email and gmail the other is disroot. I changed the password of the disroot account, of course I had to change the password inside delta. I changed it but it gave a timeout error. I deleted the account and recreated and it still gave error. I only solved it by clearing the cache.

- Android version: 11
- Device: Redmi note 9 pro / joyeuse
- Delta Chat version: 1.22.1

**Comment by Hocuri** [comment]
How did the "timeout error" look? Can you send screenshots and logs? Can you reproduce the issue by changing the password again?
