### ISSUE TITLE
Remove the icon of change account by the side of the Delta Chat name

### ISSUE THREAD

**Issue by DarkSoul-12** [deltachat/deltachat-android#2161]
The new account change icon on the main page is redundantby side of Delta Chat app name on upper left side, clicking on the 3 dots we have the same functionality, so why not to remove it and left the Delta Chat name alone, looks more cohesive and nice, like other apps like Telegram or Whatsapp.

Thanks for your time, and I just want to say that this is a wonderful app :yellow_heart:

**Comment by Hocuri** [comment]
Because it's quicker to click on the icon in the upper left corner (1 tap instead of 2).

I suggest to close this issue, we can think about removing the entry in the 3-dots-menu at some later point.

**Comment by r10s** [comment]
> Because it's quicker to click on the icon in the upper left corner (1 tap instead of 2).

also, you see which account is selected immediately - and it will fit better with what we can do on ios (where you do not have a three-dot-menu)

> I suggest to close this issue, we can think about removing the entry in the 3-dots-menu at some later point.

yip, the plan is to remove the entry in the 3-dots-menu. the icon has 

@DarkSoul-12 thanks for your point of view anyway!

**Comment by r10s** [comment]
closing  issue without actionable item due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).

of course, discussion can continue :)
