### ISSUE TITLE
Account selector shows unread badge but no chat does

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#2163]
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: Current master

I think Holger once reported this too:

None of my chats show an unread badge, but the account in the account switcher dialog does show an unread badge, and there is no hint where this alledged one unread message comes from.

**Cause**

For whatever reason, one of the older messages in a chat with Björn stayed at DC_STATE_IN_FRESH, so both `get_fresh_msg_cnt(chat_id)` and `dc_get_fresh_msgs()` returned "1"/a message.

However, Android later does:

```
    int unreadCount = ((state==DcMsg.DC_STATE_IN_FRESH || state==DcMsg.DC_STATE_IN_NOTICED) && !thread.isContactRequest())?
                        thread.getUnreadCount() : 0;
```

(org/thoughtcrime/securesms/ConversationListItem.java:140; also see https://github.com/deltachat/deltachat-android/commit/618af02bf54cb7fd66f9843e491bbf3206e7b26a)

`state` here is from `dcSummary`, and means the state of the last message in the chat.

**Proposed solution**

- On Androd, show the unread badge when unread!=0 again (see https://github.com/deltachat/deltachat-android/commit/618af02bf54cb7fd66f9843e491bbf3206e7b26a). Then the user can see that there is a chat with an unread message and click it to get rid of it.
  - Another option would be to fix this during migration in the Core
- Then, Core should take care that if the last message in a chat is not fresh|noticed, no messages in the chat can be fresh.
  - One way to do this would be in dc_receive_imf()
  - Another way would be to do this in a function that's called at the end of `fetch_new_messages()`. Then `dc_receive_imf()` wouldn't get slower by this and we could re-use the same function for migration.

**Comment by link2xt** [comment]
This really fixed the bug for me, I quickly found the chat that had unnoticed message.
