### ISSUE TITLE
f-droid 1.26 not building

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2166]
this issue is just to to nor forget about https://gitlab.com/fdroid/fdroiddata/-/issues/2555 ;)

the Java upgrade was needed because of https://github.com/deltachat/deltachat-android/pull/2087

@Hocuri can you have a look what f-droid needs and how we can achieve that in the simplest way?

**Comment by link2xt** [comment]
Proposed fix: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10186

**Comment by link2xt** [comment]
1.26.2 has been built by F-Droid successfully.

**Comment by r10s** [comment]
great! thanks a lot for taking care!
