### ISSUE TITLE
Fix versionCode bug for newer gradle versions

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#217]
Currently F-Droid has an error and prints out a weired version code `33` - although the last versionCode was already `483` see https://f-droid.org/wiki/page/com.b44t.messenger#Versions.

I try to explain:

Up to now the versionCode is calculated as follows (just copied from Telegram sources) ...

```
    defaultConfig.versionCode = 50

    productFlavors {
        ...
        fat {
            versionCode = 3
        }
    }

    applicationVariants.all { variant ->
        def abiVersion = variant.productFlavors.get(0).versionCode
        variant.mergedFlavor.versionCode = defaultConfig.versionCode * 10 + abiVersion;
    }
```

... which results in a versionCode of 503 in _older_ gradle versions (2.3 or so). But the _new_ gradle version (since 4.1 or so) does no longer allow a versionCode definition outside productFlavors - and then  defaultConfig.versionCode seems to be just productFlavors.versionCode and the resulting version code is _33_. _I_ would expect it being only `3` however ...  

maybe the version printed in the F-Droid log has also to do with the [f-droid-vercode-operation](https://f-droid.org/en/docs/Build_Metadata_Reference/#Vercode-Operation), which is [%c*10 + 3](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.b44t.messenger.txt) - but if I understand the things correctly, this  affects the resulting version, for the 483 of the last successfull build, this would be 4833 then ...

**Comment by jlelse** [comment]
With Android Plugin version 3.0 there is also another change in productFlavors needed: dimensions. I tried to fix this, but didn't want to commit yet, because the ndk-build failed for me. Didn't find out why (yet).

**Comment by r10s** [comment]
yes, I saw this error. can you tell me what the line should read?
I will test it then ...

**Comment by jlelse** [comment]
You can read about changes to productFlavors here: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html
