### ISSUE TITLE
notification for new message only shown when corresponding email account is selected for display in the UI

### ISSUE THREAD

**Issue by chrfre** [deltachat/deltachat-android#2183]
- Android version: 12 (GrapheneOS, build: SQ1A.211205.008.2021122018)
- Device: Pixel 3a
- Delta Chat version: 1.26.2 (F-Droid)
- Expected behavior: I am notified for incoming messages from any of the registered email accounts, no matter if one is currently selected for display in the UI or not.
- Actual behavior: I am notified for incoming messages only from the email account which is currently selected for display in the UI.
- Steps to reproduce the problem: In the settings of the email account which will receive a message choose “All” under “Show Classic E-Mails”. Select another email account than the one which will receive a message for display in the account selection dialog. Send a message to the receiving email account via a normal email client of another account. For comparison select the the email account which received the first email without notification for display in the UI. Then send another message to that account the same way as before.
- Screenshots:
- Logs:

**Comment by Gh0stz0x** [comment]
This is not a bug, because for now it is a feature not yet implemented.
To check if this request has already been made, try going to the forum:

https://support.delta.chat/c/features/6

If not done yet, open a request thread.

**Comment by Gh0stz0x** [comment]
As you can see it is a request already made that has yet to be implemented:

https://support.delta.chat/t/support-for-multiple-accounts-profiles-requirements/1012

**Comment by chrfre** [comment]
Thank you for pointing that out. I was not aware of this feature request.
