### ISSUE TITLE
QRCode Display Error

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-android#2187]
- Android version: 10
- Device: Huawei Mate 20
- Delta Chat version: 1.26.2 Nightly 2022-01-16
- Expected behavior: When I see an invitation QRCode of a group it should not show quot;  before and after the group name
- Actual behavior: Quot;  before and after the group name
- Steps to reproduce the problem: View the invitation QRCode
- Screenshots: 
![Screenshot_20220116_105805](https://user-images.githubusercontent.com/74795149/149655444-13e9a209-38d7-4993-8df4-ff096ba96eac.jpg)

- Logs:

**Comment by Hocuri** [comment]
Can reproduce, also in other languages. Something with QR code generation is going wrong there. The source string is `Scansionalo per entrare nel gruppo \"%1$s\".`, which actually looks fine.

In 1.26.2, there simply were no quotes, maybe we should simply remove them again.

**Comment by Gh0stz0x** [comment]
> `Scansionalo per entrare nel gruppo \"%1$s\".`

From this string I have eliminated the dot, which was not there in the sentence to be translated.  For the rest I noticed this bug only in the nightly.  In the stable version it does not show up 🤔

**Comment by Gh0stz0x** [comment]
> `Scansionalo per entrare nel gruppo \"%1$s\".`

From this string I have eliminated the dot, which was not there in the sentence to be translated.  For the rest I noticed this bug only in the nightly.  In the stable version it does not show up 🤔

>In 1.26.2, there simply were no quotes, maybe we should simply remove them again.

I really think so

**Comment by gerryfrancis** [comment]
The text shown below the QR code is `Scansional per entrare nel gruppo quot;QRCode_Testquot;.` while it should be `Scansional per entrare nel gruppo &quot;QRCode_Test&quot;.` instead, according to https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling . (Note the `&` character!)
