### ISSUE TITLE
sharing pdf not possible

### ISSUE THREAD

**Issue by Yettte** [deltachat/deltachat-android#2189]
- Android version: 10
- Device: Honor 10
- Delta Chat version: 1.26.2
- Expected behavior: I sent a pdf to myself from another email account and want it to share with someone on signal
- Actual behavior: the share option was there, but when I tapped on it, it said: " Es tut uns sehr leid! Unser Entwicklungsteam wird dieses Problem so schnell wie möglich lösen."
- Steps to reproduce the problem:
- Screenshots:
- Logs: file:///tmp/c6948c3483aca3e2aa942710966a8968.html 
![imageedit_1_8241602593](https://user-images.githubusercontent.com/82230211/149765851-dd80939c-4096-4b08-8145-2ac812e9cc3b.jpg)

**Comment by r10s** [comment]
i think, the screenshot and the message is from the pdf-viewer in use, not from Delta Chat, so there is no actionable item.
