### ISSUE TITLE
Not possible to install v0.11.x (Beta)

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-android#219]
**Delta Chat version**: > v0.10.0

**Actual behavior**

Any attempt to install (either upgrade or install initial) v0.11.0 or v0.11.2 fails.

**Debug logs**

Saved to [Gist](https://gist.github.com/Ampli-fier/7cbfdd11782d55d81f7a83d1b3397324).

**Comment by r10s** [comment]
Unfortunately, I cannot reproduce the crash on my devices. I tried ... 
- a fresh installation from the downloadable APK on a Moto G4 Play with Android 6.0.1 
- an update installation directly from Android Studio on Nexus 4 with Android Lineage 7.1.2
- various virtual machines
... without problems :-|

When looking at the logs, to me it seems that the problem is the launcher, at least on the first glance:
```
--------- beginning of crash
12-15 22:38:30.230  4823  4823 F libc    : invalid address or address of corrupt block 0x31 passed to dlfree
12-15 22:38:30.231  4823  4823 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 4823 (themes.provider)
```
and the rest of the log is more about the launcher.

**Comment by Ampli-fier** [comment]
I tried several times to install the latest version, I even created a smaller apk (by omitting x86 target architecture) to make sure it is not the size. I stopped other apps and cleaned my phone (deleted apps), but still ... all attempts to install end in crashing. Version 0.10.0 installs fine, **always** :)

I found this [question on Stackoverflow](https://stackoverflow.com/questions/25069186/invalid-address-passed-to-dlfree). With a reference to [Memory Profiling](https://developer.android.com/studio/profile/memory-profiler.html) in Android Studio.

**Comment by Ampli-fier** [comment]
My Android Version is: 5.1.1 (CyanogenMod 12.1).

I **can** install and run Delta Chat v0.11.2 when I revert
`classpath 'com.android.tools.build:gradle:3.0.1'`
back to
`classpath 'com.android.tools.build:gradle:2.3.3'`.

**Comment by r10s** [comment]
interesting, to be honest, I do not know much about the gradle stuff up to now.
if you install delta - do you still get the crashed?

**Comment by Ampli-fier** [comment]
No crash any more when I compile with the above mentioned change.
_Delta_ runs fine :)

I see some differences inside the apk files (Größe=Size):

![apk_comparison](https://user-images.githubusercontent.com/22896574/34149426-4da4bf26-e4a5-11e7-97dc-35687d983b39.jpg)

The diff in AndroidManifest.xml is that this info is missing in the "not ok" version:
`platformBuildVersionCode="25" platformBuildVersionName="7.1.1"`

Probably not relevant. 

I do not come further at the moment, the decompiler is crashing ... :(

**Comment by r10s** [comment]
okay, i think i will revert the changes from https://github.com/deltachat/deltachat-android/commit/a55edf0ba0fea3ff821a93cb6add9816a105ae12 and https://github.com/deltachat/deltachat-android/commit/11bca87a4705c4c3ec06dc8e365c4071ad6db233.

if in doubt, we should keep buildtoolsVersion and compileSdkVersion in sync - and we should not just update gradle stuff by a single click; there seems to be tons of things that can go wrong.
