### ISSUE TITLE
Chat layout in landscape broken on small screens with shown keyboard

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#2195]
I'm using a Samsung galaxy s4 mini, which has a small display screen. Between the release 1.22 and 1.26 the landscape layout in  chats has been modified. When the keyboard is shown, now the send button is cut off. The first line is barely shown completely, if I try to write 2 lines, I cannot see anymore what I'm writing, having three lines of text, the quoted view is overlapped.

IMO, at least for small screens, the text editing only field should be shown in landscape if the keyboard is visible, maybe with the reduced size up to the action bar.

one line: emojibutton and send button are already cut off
![image_2022-01-20_11-34-34](https://user-images.githubusercontent.com/2614900/150332956-d6a6ed6d-f9a7-4270-baa7-e1c963569380.jpg)

two lines: while writing on the 2. line I cannot completely see what I write:

![image_2022-01-20_11-34-01](https://user-images.githubusercontent.com/2614900/150332665-9877f966-c899-4753-8ab8-3c93481bb633.jpg)

three lines: the quote is overlapped

![image_2022-01-20_11-32-30](https://user-images.githubusercontent.com/2614900/150332343-ae73631d-bade-40ae-b651-da2de54beec3.jpg)

**Comment by adbenitez** [comment]
this issue was caused by https://github.com/deltachat/deltachat-android/pull/2081, as predicted by @r10s,  it broke someone's workflow :)

**Comment by r10s** [comment]
> as predicted by @r10s, it broke someone's workflow :)

i wish i was wrong :)
