### ISSUE TITLE
Lost photo when get mail from ios gmail and send photos

### ISSUE THREAD

**Issue by Bluezz99** [deltachat/deltachat-android#2198]
- Android version:
- Device:
- Delta Chat version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

I try to send some photos from gmail use iphone to android delta chat , but in delta chat, only show 1 photo, and if sender have text and photos, on delta chat show full message, have some time it show nothing, can’t download photos, I haved try use other imap client like blue mail, the photos show fine, thanks!

**Comment by gerryfrancis** [comment]
@Bluezz99 Thank you for your report. Please edit your request and fill in the template. Are you using the latest version 1.26.2 of Delta Chat?

**Comment by Bluezz99** [comment]
Hi,
1.26.2
Thanks!

gerryfrancis ***@***.***> 於 2022年1月24日 週一 下午4:18寫道：

**Comment by r10s** [comment]
hm, i usually see all photos sent by other clients. there must be sth. special, we need further information to make this issue actionable.

**Comment by adbenitez** [comment]
@Bluezz99 please test with 1.28 and if it keep happening open this issue again, and provide more information, an example email etc.

**Comment by Bluezz99** [comment]
Thanks!
