### ISSUE TITLE
webxdc's `window.innerWidth` not always set early enough

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2201]
in dev chat, with the "fairx.xdc", it makes a difference if the WebView is quit and reopened again or if the app is restarted before reopening.

this should not happen, however, it is not confirmed yet that the WebView as such is the issue - there is also the issue that "triska.xdc" is sometimes rendered too wide, maybe this is related somehow. or, getAllUpdates() does not return the same things. 

whatever, that needs some investigations.

**Comment by r10s** [comment]
the issue seems to be that `window.innerWidth` is not always set when onLoad is called, so it is either `0` or the correct width.

@adbenitez wrote a little test.xdc:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <script src="webxdc.js"></script>
    </head>
    <body>
        <button onclick="sendMsg('manually'); return false;">Test</button>
        <p id="output"></p>
        <script>
         function sendMsg(tag) {
             const msg = tag + ": window.innerWidth == " + window.innerWidth;
             window.webxdc.sendUpdate({payload: {name: window.webxdc.selfName(), msg: msg}}, msg);
         }

         function receiveUpdate(update) {
             document.getElementById('output').innerHTML += "<strong>&lt;" + update.payload.name + "&gt;</strong> " + update.payload.msg + "<br>";
         }

         window.webxdc.setUpdateListener(receiveUpdate);
         window.webxdc.getAllUpdates().forEach(receiveUpdate);

         window.addEventListener("load", () => sendMsg("onLoad"));
        </script>
    </body>
</html>
```

the output of this xdc is mixed:

<img width=320 src=https://user-images.githubusercontent.com/9800740/151356446-9d5724d3-729d-4d67-a357-7ca9df7d0aa5.png>

at least, the issue seems to be not unknown in other contextes: https://stackoverflow.com/questions/28402100/wrong-value-for-window-innerwidth-during-onload-event-in-firefox-for-android

**Comment by adbenitez** [comment]
this seems to be fixed by the switch to `https://` scheme

**Comment by r10s** [comment]
> this seems to be fixed by the switch to https:// scheme

wow! that's great - and pretty much unexpected.

**Comment by r10s** [comment]
then let's close this :)
