### ISSUE TITLE
First unencrypted message empty

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#2213]
Could also be an issue in core.

- Android version: P
- Delta Chat version: 1.26.2 (Account A) and nightly (Account B)
- Expected behavior: message with `.` is shown
- Actual behavior: shown message is empty - looks bugged
- Steps to reproduce the problem:
1. send message with single `.` character to a new contact
2. recieve it
- Screenshot:

![androidbug](https://user-images.githubusercontent.com/18725968/151705203-6bd7d7b4-0070-4e31-b1b6-17ba7dc21a89.jpg)

**Comment by Hocuri** [comment]
There already is an issue in core for this: https://github.com/deltachat/deltachat-core-rust/issues/2635
