### ISSUE TITLE
Grey unread badge numbers for muted chats

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#2217]
would be great if android also showed the number of unread messages in grey like on desktop. 
![Screenshot from 2022-02-02 14-47-50](https://user-images.githubusercontent.com/73579/152166210-62f9b7a9-7eae-48e1-afee-ddd205027b5e.png)

**Comment by r10s** [comment]
hm, i thought that is the case, but yes, somehow not :)

**Comment by r10s** [comment]
i am currently targeting that.
