### ISSUE TITLE
Use ".txt" for exported/imported keys?

### ISSUE THREAD

**Issue by rrthomas** [deltachat/deltachat-android#2219]
- Android version: 9
- Device: Sony Xperia XZ1
- Delta Chat version: 1.26.0
- Expected behavior: Keys exported from desktop should be recognized
- Actual behavior: Keys are not found
- Steps to reproduce the problem: Export keys from desktop, share files to Android, try to import on Android
- Screenshots: Not attached
- Logs: Not attached

The bug is not in DeltaChat, but it certainly confused me: when I shared the `.asc` files to Android from my Desktop, using KDEConnect, they were named `.txt` once imported.

Perhaps DeltaChat could also look for keys ending `.txt`?

Thanks for DeltaChat!

**Comment by r10s** [comment]
> Perhaps DeltaChat could also look for keys ending .txt?

hm, i think it makes more sense to check why the files are renamed at the first place.

treating .txt as possbile keys may introduce other issues.

**Comment by rrthomas** [comment]
> hm, i think it makes more sense to check why the files are renamed at the first place.

As I said, the renaming seemed to be done by the file sharing with KDEConnect.

**Comment by rrthomas** [comment]
https://bugs.launchpad.net/ubuntu/+source/kdeconnect/+bug/1964469

**Comment by r10s** [comment]
great! thanks for taking care!
