### ISSUE TITLE
Wait for Delta/Core reaching Milestone 1.0.0

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#222]
This issue can be closed if Delta/Core reaches the Milestone "Version 1.0.0", see https://github.com/deltachat/deltachat-core/milestone/1

**Comment by testbird** [comment]
Closing as https://github.com/orgs/deltachat/projects/2 holds all issues from -core and -android.

**Comment by r10s** [comment]
reopened, see https://github.com/deltachat/deltachat-core/issues/119
