### ISSUE TITLE
Unable to Send Messages

### ISSUE THREAD

**Issue by moriel5** [deltachat/deltachat-android#2226]
Device: Razer Phone 2
OS: Android 9, Stock

Currently I'm testing out different encrypted messaging solutions (such as Delta Chat and Briar) to see what for the bill for my family, and I do especially like Delta Chat's premise (to say the truth, I have been intrigued by it for quite a few years).

Since I didn't have time to set app passwords for my Yahoo and Microsoft accounts (I cannot do so for ProtonMail), I have decided to use my Vivaldi account.

One problem, which may have to do with the fact that my Vivaldi email address is the same as my Yahoo address (it literally ends with @yahoo.com), and that is while I can recieve messages (at least, I can recieve them via AquaMail), I cannot send any messages.

For reference, this is the error message:
```
Error: Send error: permanent: 5.7.1 forged sender address
```

**Comment by gerryfrancis** [comment]
@moriel5 Thank you for your report. The domain part of your email address must be the one administered by your email provider. Many providers do not allow to state a sender (`From:`) address that incorporates a foreign domain, e.g. you cannot send a message as `userID@vivaldi.com` by using the Yahoo SMTP server. Maybe you added a new Delta Chat account, and then simply changed the input of the address and the password field from Yahoo's to Vivaldi's login credentials, but not the fields for email servers configured in the advanced settings. Please check (and appropriately modify if necessary), and report back here, thanks in advance!

**Comment by moriel5** [comment]
I guess that must be the issue, however I did not add the account and then change it, but directly via the advanced settings, since I didn't have another way to add it.

And yeah, that should be basic, separate accounts for different providers.

**Comment by moriel5** [comment]
I would not call it solved, but rather invalid, but at the end of the day, the result is the same, so I agree.

**Comment by moriel5** [comment]
I found my Vivaldi address (which turns out to be in the format "userID@vivaldi.net"), and changed everything necessary, and now everything functions as expected.

Thus, I can finally call this issue resolved (with the cause being used error), in addition to being invalid.

**Comment by gerryfrancis** [comment]
@moriel5 Thanks for reporting, and enjoy Delta Chat! :)
