### ISSUE TITLE
Remove the "key" language from the Autocrypt Setup Message dialog

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#223]
Autocrypt does not want to see "key" anywhere ... however, I'm not sure if this is possible everywhere.

**Comment by r10s** [comment]
Current state:

Menu entry: `Initiate Autocrypt Key Transfer`
Dialog title: `Autocrypt Key Transfer`
Dialog texts: see [here](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/res/values/strings.xml#L420)

Not really sure what to use here, maybe just `Initiate Autocrypt Setup Transfer` as the menu entry and `Autocrypt Setup Transfer` as the dialog title? This would be in sync with the wording `Autocrypt Setup Message` then.

@dkg , @pbrunschwig this issue comes from an IRC comment some time ago - maybe we should make this an Autocrypt-issue, in fact I copied the wording "Autocrypt Key Transfer" from Enigmail IIRC.

**Comment by pbrunschwig** [comment]
@r10s @dkg Yes, "Autocrypt Key Transfer" comes from Enigmail. I agree, we should better call it "Initiate Autocrypt Setup Transfer"

**Comment by dkg** [comment]
see also https://sourceforge.net/p/enigmail/bugs/749/

**Comment by r10s** [comment]
> see also https://sourceforge.net/p/enigmail/bugs/749/

Thank your for the link. I am completely lost in all these wordings currently, on IRC #autocrypt there is actually a discussion with @Valodim and other about how to name and explain the prefer-encrypt=mutual thingie in the UI. However, whatever the names will be, at least Valodim and me agree in that the names for the most important Autocrypt functions should be identical on different MUAs :)

**Comment by Valodim** [comment]
I don't think the word "key" is that bad actually, as long as it is not used with the terms "public", "secret", or "private". Personally I like to use "end-to-end key" as a slightly longer form that gives more context, and that isn't so short it's easy to write three times in a sentence.

**Comment by r10s** [comment]
Hm. However, I would also prefer "Initiate Autocrypt Setup Transfer" because it does not introduce an additional term - "Initiate _Autocrypt Setup_ Transfer" results in an "_Autocrypt Setup_ Message" which sounds quite logic to me.
In the longer explanations about what is happening, the word "key" may be useful, esp. for Enigmail users it might be confusing _not_ to use that term :)

**Comment by pbrunschwig** [comment]
I decided for "Initiate Autocrypt Setup".

**Comment by dkg** [comment]
fwiw, "initiate" is kind of a nerd-word.  in "simple english" (which i
think is usually advisable for UI/UX) there is almost no semantic
difference between "initiate" and "start".  Why not "Start Autocrypt
Setup" ?

       --dkg

**Comment by r10s** [comment]
_Start_ instead of _Initiate_  - yes, this seems to be much easier to understand, esp. for me as non-native-english-speaker, no idea why i did not found this out myself :)

However, a "Start Autocrypt Setup" imho does not imply that the setup is actually done on another device, if i read this, i probably would assume, the setup happens on the same device. Doesn't a "Start Autocrypt Setup _Transfer_" (or a "_Transfer_ Autocrypt Setup"?) make this clearer.

@comradekingu maybe you have also an idea here?

**Comment by r10s** [comment]
@dkg Yes, I've seen this. Thank you for the hint. The "transfer" aspect is implied in "another" then? Don't know why, I feel it might be better to have the term "Autocrypt Setup" also in the button, so that it is closer to the "Autocrypt Setup Message". But maybe "Set up ... Autocrypt" is already close enough :)

But, hey, I am not _that_ nailed to a special wording :) I think the most important part is to find basic terms that are used in the MUAs equally. So - I would be fine with "Set up another Autocrypt e-mail app" as well as with @Valodim 's "Autocrypt mutual mode" ...

![delta-wording](https://user-images.githubusercontent.com/9800740/36514090-2073cf0a-1773-11e8-9aac-9eee915501c2.png)

**Comment by dkg** [comment]
I like the looks of this!  is there any way in a preferences setting to have a "what's this?" link to more explanatory text?

**Comment by r10s** [comment]
@dkg my idea is to add some descriptive text and a link just below the "Autocrypt" section, maybe also the logo.

**Comment by r10s** [comment]
this what it looks like now:

![screenshot_1524000216](https://user-images.githubusercontent.com/9800740/38898874-8df92d88-4296-11e8-8812-1a3d473a0f9f.png)
