### ISSUE TITLE
Delta Chat App remove iWatch monitoring service messages

### ISSUE THREAD

**Issue by joaquinferrero** [deltachat/deltachat-android#2231]
- Android version: 7.1.2
- Device: Aquaris M5.5
- Delta Chat version: 1.28.3
- Expected behavior: iWatch messages remain in the inbox
- Actual behavior: iWatch messages disappear
- Steps to reproduce the problem:
Configure Delta Chat with an email account that receives messages from the iWatch monitoring system (Linux). Make sure that the IMAP mailbox is only being accessed by the Delta Chat App (close access to other IMAP clients). Wait or force an event for the system to send a message to the mailbox. Within a few seconds, Delta Chat deletes the mail. There is no copy left in any other folder, not even in the Delta Chat IMAP folder.
- Logs: 
03-11 15:17:13.127 22298 22352 I DeltaChat: src/imap/idle.rs:73: Idle has NewData ResponseData { raw: 4096, response: MailboxData(Exists(1835)) }
03-11 15:17:13.320 22298 22352 I DeltaChat: src/job.rs:753: loading job for Imap-thread
03-11 15:17:13.416 22298 22352 W DeltaChat: src/message.rs:1684: Empty rfc724_mid passed to rfc724_mid_exists
03-11 15:17:13.422 22298 22352 W DeltaChat: src/message.rs:1684: Empty rfc724_mid passed to rfc724_mid_exists
03-11 15:17:13.427 22298 22352 I DeltaChat: src/imap.rs:825: 2 mails read from "INBOX".
03-11 15:17:13.650 22298 22352 I DeltaChat: src/imap/select_folder.rs:35: Expunge messages in "INBOX".
03-11 15:17:13.986 22298 22352 I DeltaChat: src/imap/select_folder.rs:40: close/expunge succeeded
03-11 15:17:13.987 22298 22352 I DeltaChat: src/imap/scan_folders.rs:27: Starting full folder scan
03-11 15:17:14.106 22298 22352 I DeltaChat: src/imap.rs:1580: Need to fetch again, got unsolicited EXISTS Exists(1836)
03-11 15:17:14.227 22298 22352 I DeltaChat: src/imap.rs:672: No new emails in folder xxx
... (many forlders later)
03-11 15:17:18.412 22298 22298 I PassphraseRequiredActionBarActivity: onResume()
03-11 15:17:18.514 22298 22352 I DeltaChat: src/imap.rs:672: No new emails in folder yyy
... (many forlders later)
03-11 15:17:19.246 22298 22298 I PassphraseRequiredActionBarActivity: onPause()
03-11 15:17:19.309 22298 22298 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a9200cf
03-11 15:17:19.309 22298 22298 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b839a5c
03-11 15:17:19.334 22298 22298 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b229060
03-11 15:17:19.335 22298 22298 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ff4e919

The iWatch messages folder have this subject line, and body:
Subject:  [iWatch] server.ip.com: IN_MODIFY /var/domain.com/www/readme.html
											
[11/mar/2022 14:53:05]
IN_MODIFY /var/domain/ww/readme.html=

**Comment by Hocuri** [comment]
Should have been fixed by https://github.com/deltachat/deltachat-core-rust/pull/3095, please retry with the latest nightly from https://download.delta.chat/android/nightly/

**Comment by adbenitez** [comment]
@joaquinferrero please retry with 1.28, and re-open this issue if it keeps happening
