### ISSUE TITLE
Lacking check if connection is dead or too high timeout

### ISSUE THREAD

**Issue by tomekdev** [deltachat/deltachat-android#2238]
Device: bq Aquaris X
OS: LineageOS 16.0 (Android 9)
Mail account host: GMail

Delta Chat seems to have too high timeout value to check if connection with mail server is dead or not. Quite often I have to wait until Delta Chat reconnects to server (few minutes) before my message was sent. It happens when phone is not used for several minutes. Will it be possible to add setting in order to set connection timeout in seconds ?

Best regards,
tomekdev17

**Comment by Hocuri** [comment]
Thanks for the feedback! This already has an issue at https://github.com/deltachat/deltachat-core-rust/issues/3092 and we are planning to fix it before the next release.
