### ISSUE TITLE
Bad UX for adding a user that is not in the address book to a group

### ISSUE THREAD

**Issue by allo-** [deltachat/deltachat-android#2241]
- Delta Chat version: 1.28.3

When I try to add a new E-Mail address to a group, I get an input field with a checkmark next to it. After typing in an E-Mail address it looks like I now need to click the checkmark icon to add it. Clicking it closes the dialog without adding the new person to the group.

Current flow:

The actual workflow is to click the entry that is suggested in the list below after one typed in a correct e-mail address, which then gets a checkbox icon next to it and then clicking the checkmark icon at top. This workflow is not intuitive, as there is no obvious hint that the checkmark icon belongs to the whole dialog and not to the textbox.

Suggested flow:

Have a "plus" symbol next to the textbox, which then adds the address to the list (of possibly multiple new addresses) below. Have a "finish" or "close" button at the bottom instead of the top of the dialog, which is clearly meant for the whole dialog and not related to the textbox at top.  
Possibly add a warning when the user tries to close the dialog when he entered an e-mail address at top, but did not add it to the list.

**Comment by Hocuri** [comment]
Yes, I agree that this is unintuitive.

> Have a "plus" symbol next to the textbox, which then adds the address to the list (of possibly multiple new addresses) below.

There already is a "plus" symbol below the textbox which does this. Although I don't understand what you mean with "possibly multiple new addresses"?

> Have a "finish" or "close" button at the bottom instead of the top of the dialog, which is clearly meant for the whole dialog and not related to the textbox at top.

Not sure, all our "confirm" buttons are at the upper right corner.

> Possibly add a warning when the user tries to close the dialog when he entered an e-mail address at top, but did not add it to the list.

+1. Maybe even directly ask "Do you want to add <email address> to the group?".

**Comment by Hocuri** [comment]
Let's keep this open as a "good first issue" (i.e. not fix it by an experienced dev) for a short while, because we don't have lots of "good first issues".

**Comment by allo-** [comment]
> There already is a "plus" symbol below the textbox which does this.

The function is okay, but the UX is confusing. The "Add Contact" Entry looks like a contact you can select from your address book before you typed in an e-mail address. I think especially with the filtering effect it looks like "One contact in the list is remaining" but not like a call to action.

- Simple fix: Remove the checkmark next to the textbox so the user looks for the add button in other places, hopefully finding the "New Contact" Entry
- Possibly better fix: separate "add to list" (e.g. textbox with plus symbol to the right) from the list of existing/already added contacts

The usual pattern in other programs is to have a list that is just a list that allows to select entries (possibly not even having a context menu) and add/remove buttons next to it. A text field for adding a new entry may be next to the add button, or the add button opens an "add address ..." dialog.

```
- some
- entries
- already
- there
[__________] [add new]
[remove selected]
```

> Although I don't understand what you mean with "possibly multiple new addresses"?

The screen allows to add existing contacts and add more than one new contact to the list. For this one would type the next address right after choosing "New Contact".

> Not sure, all our "confirm" buttons are at the upper right corner.

I am not sure if this isn't a general anti-pattern (people read from top to bottom and often the flow for dealing with settings and similar is like this) but it could still work if there would be a better separation for adding to the list and closing the dialog.

When I use the dialog I have the following flow:

- Goal: Add an address
- First Item: Text field. Great, I enter the address
- Second Item: Checkmark button. Great, I click it and it's finished?! MISTAKE! Now the screen is closed without the address being added
- Third Item: List (I've only seen that there are some members in the group / some address book entries that could be added if I wouldn't want a new address. The "New Contact" Entry looked very similar to the entries for address book contacts / existing list members)

Now let's place the button at bottom, making sure it is the last element and not the one right after entering the address:

- Goal: Add an address
- First Item: Text field. Great, I enter the address
- Second Item: The list
- Third Item (in the list): A similar e-mail address filtered from the list. I skip this, it's not what I want
- Fourth Item (in the list): A list entry "Add new@address". Great, I click that one! There is a smaller chance that I don't look close enough and mistake it for a user that I could select, but probably I've seen it from the corner of my eye even when I didn't read it closely.
- Fifth Item: A save button. I click that one and I am finished

Or making it explicit:

- Goal: Add an address
- First Item: Text field. Great, I enter the address
- Second Item: Add Button. I click that one. The address now appears in the list below and is selected.
- Third Item: The list. I ignore it or check that the address is now in the list
- Fourth Item: A save button. I click that one and I am finished

- Goal: Add a user from the address book
- First Item: Text field. Great, I may filter the list (or I skip it)
- Second Item: Add Button. I ignore it, I don't want to add a new user.
- Third Item: The list. I choose the user
- Fourth Item: A save button. I click that one and I am finished

**Comment by allo-** [comment]
Testing the screen more thorough, I am also not sure if the (x) in the top left could be confused with a "clear textfield" button. But maybe it's just me an it isn't such a big deal as re-opening the dialog to clear the text isn't as annoying as having an address not added after clicking a button that looks like it would add it.

**Comment by monperrus** [comment]
> Clicking it closes the dialog without adding the new person to the group.

this happens to me. I'm not able to add a single member. how to do this?

**Comment by adbenitez** [comment]
this issue is more than 1 year old already, moving to the forum so it gets more feedback from other users:
https://support.delta.chat/t/bad-ux-for-adding-a-user-that-is-not-in-the-address-book-to-a-group/2746
