### ISSUE TITLE
Account no longer loaded after restore of backup

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2242]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2022-03-18).

- Delta Chat version:
1.28.3 (latest nightly build).

- Expected behavior:
After a backup has been restored, Delta Chat loads the respective account.

- Actual behavior:
After a backup has been restored, Delta Chat does not load the respective account. (The app does not crash or hang, but it stays at the welcome screen and does not continue by itself.)

- Steps to reproduce the problem:
-- Install the latest Delta Chat nightly build.
-- Open Delta Chat and restore a backup.

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
so, that should work with the next nightly again (not sure if the one from today, depends on when it is build :)

@gerryfrancis thanks a lot for testing so that we got aware of this bug soon!

**Comment by gerryfrancis** [comment]
@r10s Ah, don't mention it, thanks for the fast fix! :)

**Comment by gerryfrancis** [comment]
I'm sorry, this issue just reoccured with the latest nightly. :( Reopening here...

**Comment by r10s** [comment]
i think, this is a different issue, the initial one was clearly bound to the nightly and to the related core change. please open a new issue to not mix up things,
