### ISSUE TITLE
Can't share images with "invalid" characters in name

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#2248]
- Delta Chat version: Current master
- Steps to reproduce the problem:
  - Create an image with an "invalid" character in the file name like `/` or `\`. (For some reason, my built-in camera app sometimes creates names like `IMG_3874\.jpg`.)
  - Click "share", select DC, and select a chat. Expected: The image is set as a draft. Actual: It's not.

Ping @r10s can you check whether there is a similar issue in iOS, and if not how you avoid it?

**Reason**
There's just never any code that would remove the invalid character. The Android code directly creates a file in the blob dir (`handleSharing()` -> `createMessage()` -> `getRealPathFromUri()` -> `getBlobdirFile()`) and sets it on the message with `set_file()`, which is a simple setter. Then when it calls `set_draft()`, the core errors `failed to set draft: Blob has a badname /data/.../IMG_394\.jpg`.

**Proposed solution**

Expose `BlobObject::create()` via the FFI and let Android use it instead of `getBlobdirFile()`. Ping @link2xt @flub as this would be a Core change.

**Alternative solutions**

- In DC-Android: Directly fix `getBlobdirFile()`, implementing a logic similar to what `BlobObject::create()` does.
- In DC-Core: Let `set_draft()` or `set_file()` repair the filename, copying the file (or moving if we are sure it's not needed under the old name)

**Comment by flub** [comment]
I kind of like the suggestion of `dc_msg_set_file()` fixing up the filename and moving it.  However the current docs say it won't do anything and instead `dc_send_msg()` (or `dc_set_draft()` I guess) will do this.  So maybe those are better places.

Main reason I prefer this is that there's no new FFI API.  Downside of it is that a `Message` could have an "invalid" `Param::File` value, but only while it does not yet exist in the database so maybe that's ok.

**Comment by Hocuri** [comment]
Let's write down some advantages & disadvantages of dc_msg_set_file()/dc_msg_set_draft() fixing up the filename comparet do my proposed solution:
Pro:
- No new FFI
- The UI can't do it "wrong", the core just fixes whatever the UI gives it

Con:
- At least on Android, dc_msg_set_file()/dc_msg_set_draft() is called from the UI thread while loading the chat for sharing. So, if we move or even copy a file in these functions, loading the chat for sharing will take a little longer.
- If we move the file, it's possible that it was needed under the old name, e.g. because multiple Messages referred to the same Param::File. This problem is less bad if we move it earlier (i.e. in `dc_msg_set_file()` not `dc_set_draft()`) since it's less likely that another Message "already" also uses the file, but we might still introduce bugs (and have to be careful to hopefully not introduce bugs).
- If we copy the file, that's usually unnecessary work being done.

**Comment by flub** [comment]
Worth also noting that sometime in the future the file will have to be moved because it will need to be moved into the database.  Maybe we need to think about how `dc_msg_set_file()` `dc_send_msg()` and `dc_set_draft()` should interact in that case.
- When should it move to the database?
- Who owns and cleans up the file?

**Comment by AndreaLattmann** [comment]
Is this bug still present?

**Comment by adbenitez** [comment]
so in the end it is more about fixing it in core, not really fixing it in the Android side? then I think we should move this issue to core

**Comment by adbenitez** [comment]
> So Android side needs to stop creating files in the blobdir and instead use set_file directly, followed by set_draft.

the thing is that set_file() requires a path, no data, and in android it often happens that what you have is a data stream, that is exactly why files are created in the blob dir, to first save them to a local file and pass that path to core, one option would be to create a temp file elsewhere but then that creates duplicate storage usage just to pass the file to core

**Comment by adbenitez** [comment]
to be honest I am not sure, creating files in the blob dir without using core feels wrong, but whatever fixes this issue is better than current situation

**Comment by adbenitez** [comment]
created a quick fix, to sanitize the filename before creating it in the blobs dir  this will solve this issue, in the long run would be better to move away from creating files directly in the blobs dir, but for now it is as it is 

https://github.com/deltachat/deltachat-android/pull/2692
