### ISSUE TITLE
Make messages appear in chat if contact is known

### ISSUE THREAD

**Issue by cnsgithub** [deltachat/deltachat-android#225]
Hi,

I decided to take a look at Delta Chat because of its WhatsApp look and feel and out-of-the-box end-to-end-encryption with Autocrypt support. That's pretty cool.

There is just one thing I stumbled upon: if a chat (email) is initiated by a non-deltachat MUA like Thunderbird or a webmailer the message appears in 'contact requests'. That's absolutely fine for the very first time. 

However, for subsequent emails initiated by non-deltachat contacts the messages should appear directly in the chat signalling that there are new messages without having to look within 'contact requests'. Otherwise, non-deltachat contacts will always have to pick up and answer to old mail threads if they want the messages to pop up instantly. That's somewhat uncomfortable.

Thanks

**Comment by cnsgithub** [comment]
Delta Chat version: latest from F-Droid, 0.9.9.

**Comment by testbird** [comment]
That's how it used to work. Seems like some error might have been introduced with the new prompting for not-chat inbox items.

**Comment by csb0730** [comment]
You should get alerted some way that a new contact message arriving in Contact Requests.
- By switching to that message and tapping to the arrow right top of the message You can start a chat immediately (old way).
- At the top of the chat list You should get a highlighted (some more greyed) new chat request. From there You can decide what to do (new way).

Maybe both possibilities are working. I'm not completely clear with that in the moment!

Further informations You can find here #49 and here #149.

**Comment by testbird** [comment]
Do you have a filter rules in other clients or on the server that move messages out of the INBOX, or maybe are you also using another client that uses POP to fetch messages, or do the messages get read in some other way?

**Comment by cnsgithub** [comment]
I don't have specified any filters explicitly. 

Though, I am not sure if there is any bad interaction with other MUAs on the phone like Samsung's email app or Google's Gmail app. But I think I deactivated the Samsung client. 

However, after disabling synchronization in Gmail client I didn't receive any mails in DeltaChat. So I enabled synchronization again. But I think Gmail uses IMAP instead of POP per default. I dind't change any default settings. Is DeltaChat dependant on the Gmail app anyhow?

**Comment by testbird** [comment]
Could you try with a non-gmail account, it defeats your privacy and your contacts privacy anyway, and is known to create configuration problems when using other clients.

**Comment by r10s** [comment]
i think, this issue is covered more detailed in #228

**Comment by testbird** [comment]
As I understood it, this issue #225 is about messages from **known** contacts not showing up, which if I am not mistaken can happen due to a couple issues already known for a while. Therefore my questions above to find out if this might be case of a known bug.

Issue #228 however is about the now missing option for a visual indication of new messeges from **unknow** contacts in the chats list (email log showing number of unread messages count).

**Comment by testbird** [comment]
In particular, the flaky reception, and not receiving at all without parallel gmail client, might hint to gmail auth whitelisting the device ip for imap.

**Comment by testbird** [comment]
To make sure this is not just flaky whitelisting of your IP, have you enabled IMAP and less secure apps at gmail? https://github.com/deltachat/deltachat-core/wiki/Provider-overview

**Comment by cnsgithub** [comment]
Yes, IMAP and insecure apps were configured as proposed. The good news is that it seems to work after the last update. Sorry for not giving you feedback, as the issue was closed as a duplicate I thought it would be no longer of interest here. Thanks.

**Comment by testbird** [comment]
All right, so we can leave this issue closed without qualms, good that it works for you as well now.
