### ISSUE TITLE
Account no longer loaded after restore of backup (#2)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2263]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2022-04-01).

- Delta Chat version:
1.29.0 (nightly built 2022-04-04).

- Expected behavior:
After a backup has been restored, Delta Chat loads the respective account.

- Actual behavior:
After a backup has been restored, Delta Chat does not load the respective account. (The app does not crash or hang, but it stays at the welcome screen and does not continue by itself.)

- Steps to reproduce the problem:
-- Install Delta Chat.
-- Open Delta Chat and restore a backup. While the backup is restored, let your device enter sleep mode for a few seconds, but wake it up shortly afterwards.

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by Hocuri** [comment]
Hmmm, I can't reproduce this. Are there any details I have to take account of? And did you choose to encrypt the account?

**Comment by gerryfrancis** [comment]
@Hocuri My device (Fairphone FP2) is not encrypted, I think this is not supported in general, hence I cannot encrypt the database. All I know is that it happened to me just once, and the phone went to sleep for a few seconds while database restore was in progress.

**Comment by gerryfrancis** [comment]
I am able to reproduce the issue by letting the device enter sleep mode (after 1 minute for <5 seconds), and waking it up immediately once.

**Comment by gerryfrancis** [comment]
I have retested this one: It still happens to me, but I have recognized that after the backup had been restored, a new welcome screen is layed over the existing one. (I saw a fullscreen window animation unfolding right after restore process had been finished.) I have no concrete idea what is going here, maybe the main process (welcome screen) was terminated shortly after the device entered sleep mode (switched-off display).

**Comment by Hocuri** [comment]
I could reproduce this now

**Comment by gerryfrancis** [comment]
Works fine now, thank you! :)
