### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yoha-Codet** [deltachat/deltachat-android#2268]
In android the app crashes at the start of launching the app

**Comment by r10s** [comment]
can you provide some more information as android versions, logs, screenshots, what you were doing and if you can reproduce the crash?

for fixing, it is required that some developer is able to reproduce the bug - otherwise, there is not much one can do about the issue.

**Comment by adbenitez** [comment]
closing stale issue, until more info is provided then can be opened again, otherwise we can't do anything about it
