### ISSUE TITLE
POP protocol implementation

### ISSUE THREAD

**Issue by decripter37** [deltachat/deltachat-android#227]
As title says, I'd like a **POP** implementation.
I have a limited storage capabilities on the server, so, I'd like to **pop** the messages out.
This will keep the email clean, without the struggle of a manual management.

**Comment by testbird** [comment]
POP does not not support the required notification (IMAP push / notify) what you probably want from it is a max. age, max. used space setting for the messages on the server.

**Comment by decripter37** [comment]
This max is a server thing or a deltachat one? 
Maybe a fictional POP will do too, if I read an email/message, remove it from the server automatically and keep a copy only on my phone. 
I just want to use my mail as a middle ground for the messages.

**Comment by decripter37** [comment]
How does the POP protocol break the notification?

**Comment by textbrowser** [comment]
Spot-On supports both IMAP and POP3 and has done so for years. That is, communicating through e-mail servers. So, yes, POP3 interaction is quite possible. POP3 requires less logic. Notifications are something a developer must implement in the world of POP3. A polling solution suffices for such an old protocol.

**Comment by testbird** [comment]
AFAIK limiting max. message age or storage space on the server would be a client feature. And does have importance on its own. Not only locally: https://github.com/deltachat/deltachat-android/issues/244

Otherwise it's just that POP would require battery consuming polling, and is used less and less I think, or is there some advantage?

**Comment by textbrowser** [comment]
Let's say you receive 500 messages in 1 hour. 500 pulls, right? How many notification messages? Are there versions of IMAP which notify by including actual e-mail data or do they simply notify and expect you to retrieve?

If you poll once every 30 seconds, that's 120 polls in 1 hour. Or, let's say every 15 seconds. 240 polls. These are at most polls as a single poll may result in popping all messages from the server.

What if you don't receive messages? Polling would appear at a disadvantage.

Which method is gentler on the battery? I don't know.

Offering both methods would let users experiment.

**Comment by testbird** [comment]
> Let's say you receive 500 messages in 1 hour.
Good point, haven't though of high amounts of incomming messages. But then the user is probably also reading all the time with CPU and display on, and the difference in batch polling/repetitive polling doesn't make much of a difference for battery usage anymore.

IIRC IMAP push allows the client to just stay in a low power mode all the time with the CPU only waking up by an interrupt from the modem when a push notification package arrives. And this deep sleep state is the usually the desired state most of the time for mobile clients. As the current effort is to get out a stable usable version, if one really needs POP one would most likely have to contribute a pull request.

**Comment by textbrowser** [comment]
POP3 doesn't require a persistent connection. I imagine an IMAP persistent connection is not free.

**Comment by textbrowser** [comment]
http://helpblog.blackberry.com/2013/03/blackberry-z10-battery-tips/

Recommends IMAP.

**Comment by decripter37** [comment]
I'm actually OK with a max system.
I just thought of POP first, thinking that maybe it will be easier on the code side just switch the protocol, but of this is not the case, I'm OK with IMAP.
My problem is just that I have low storage and would like to use my actual mail to chat. (#244 asked essentially for the same feature I want, didn't meant to bring back POP from the reign of the dead)

**Comment by testbird** [comment]
Just found this: #22

**Comment by decripter37** [comment]
Contrary to #22, I want it to delete the messages on the server

**Comment by textbrowser** [comment]
POP-goes-the-weasel!

**Comment by testbird** [comment]
Sorry, I first wrongly interpreted the hint given in #22 as server related.
As a workaround for now, maybe your server allows to have some filter definitions to automatically delete older messages.

**Comment by r10s** [comment]
i'm closing this for now here; the new forum at https://support.delta.chat is the better place for feature requests and discussions.
