### ISSUE TITLE
I get "INBOX: Error: Connection refused (os error 111)"

### ISSUE THREAD

**Issue by FlugHundSN2** [deltachat/deltachat-android#2272]
- Android version: 11
- Device: 
- SM-A526B
- Delta Chat version: 1.28.3
- Expected behavior: to work
- Actual behavior: doesn't work
- Steps to reproduce the problem: ---
- Screenshots:
- Logs:

**Comment by FlugHundSN2** [comment]
Problem caused by an adblocker. Exception configured, problem solved.

**Comment by r10s** [comment]
thanks for coming back and giving details and a solution!
