### ISSUE TITLE
"live.com" is Not Autodetected as an Outlook.com Alias

### ISSUE THREAD

**Issue by moriel5** [deltachat/deltachat-android#2295]
Just as Hotmail addresses are grandfathered Microsoft addresses nowadays, Microsoft Live addresses are also in the same boat.

However it appears that Live addresses are not automatically detected with Outlook.com settings.

**Comment by r10s** [comment]
> However it always that Live addresses are not automatically detected with Outlook.com settings.

at least looking at the code of the outloook-provider-db entry, it live.com should pick up the same settings as outlook :

https://github.com/deltachat/provider-db/blob/master/_providers/outlook.com.md?plain=1#L9

so, can  please someone double-check? of course, might be there is some other weird bug :)

**Comment by Hocuri** [comment]
Closing since this seems not to have been the problem.
