### ISSUE TITLE
No way to open sent image in full screen after receiving an NDN or getting another error

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2299]
I sent an image to some group, then received an NDN from one of the members. After that, clicking anywhere in the message bubble opens an error message with NDN.

I think clicking the image should still open it in fullscreen, while clicking the message bubble or red "!" in the bottom of the message should open the error message.

**Comment by link2xt** [comment]
It's still possible to access the image via "gallery" view, but it's definitely not straightforward enough.

**Comment by Hocuri** [comment]
I'd say it's a missing feature, not a bug - the reasoning back then was that the user isn't interested that much in outgoing images anyway IIRC (they already know them, incoming images are more interesting). BTW in Signal it's not possible to directly enlarge a sent image either.

> I think clicking the image should still open it in fullscreen, while clicking the message bubble or red "!" in the bottom of the message should open the error message.

I agree that this would be the perfect behavior; no idea how much work this would be (I guess between 1-30 hours) (didn't look at the code yet, and stuff like this is hard to estimate on Android).

See #1751.

**Comment by adbenitez** [comment]
notice that you can still see the image from the chat's gallery or saving/exporting it, also such kind of errors for incoming messages are not common

**Comment by adbenitez** [comment]
closing stale feature request for now until we have more concrete idea how to proceed, because showing the error is more important than displaying the image (ex. there is always ways to save the image, share it, or see it in the chat gallery
