### ISSUE TITLE
Improve authentication fault message text

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#230]
**DC v0.9.9**

*Background:*
I created a new email account (gmx) especially for a new device.
At the device I installed DC for the first time.
Then I entered and checked several times the account credentials without success!

*Concern:*
While setup of the account following error message appears: "authentication fault for account xxx, Error  code 28". I stumbled several times over that message without finding the root cause! No concrete hint about real cause of the problem, even with knowledge in mind that maybe IMAP has to be activated!

The way I could see the problem finally was a security message into gmx web interface which explained that someone tried to contact that new account and that IMAP and POP3 is disabled for security reasons by default.

With that information is was an easy thing to solve the problem: Activating "External Mail Programs" (IMAP and POP3) and installation was possible immediately.

But I think for unexperienced users this problem is hard to find or even impossible to solve and finalize the installation!

*My proposal*
is to extend the error message with additional text information, for example:

"authentication fault for account xxxxx, Error code 28, _(please check if IMAP access really is activated if name and password is given correctly!)_"

**Comment by r10s** [comment]
+1

**Comment by csb0730** [comment]
Can be closed with https://github.com/deltachat/deltachat-android/issues/346
