### ISSUE TITLE
Horizontal padding values of transparent footer too low

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2319]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.211001.001 from 2022-06-10).

- Delta Chat version:
1.30.3 (current nightly build).

- Expected behavior:
The horizontal alignment of the transparent footer is like for other footers which are not transparent.

- Actual behavior:
The horizontal alignment of the transparent footer is not like for other footers which are not transparent.

- Steps to reproduce the problem:
-- Receive a message that includes a transparent footer and compare it to the other ones which are non-transparent.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/173359061-36d365a4-1631-4d1d-b4c5-14da0ef9f733.png)
(The vertical line shall visualize the alignment.)

- Logs:
N/A.

**Comment by gerryfrancis** [comment]
I suggest to delete the following lines to fix the issue:

https://github.com/deltachat/deltachat-android/blob/9e70aa7cadccd90b71945ea3ab0f174050dfd86c/res/layout/conversation_item_received.xml#L212-L213
https://github.com/deltachat/deltachat-android/blob/9e70aa7cadccd90b71945ea3ab0f174050dfd86c/res/layout/conversation_item_sent.xml#L189-L190

**Comment by r10s** [comment]
> I suggest to delete the following lines to fix the issue:

at a first glance, that would _remove_ the padding for the standard footer, which would look bad wrt typography.

we should _add_ padding to the video-instance footer instead.
