### ISSUE TITLE
separate thematic folders (as in telegram)

### ISSUE THREAD

**Issue by andsofine** [deltachat/deltachat-android#2327]
I think adding the ability to sort chats into folders would be a great improvement.
(with the ability to name, reorder, maybe send a message to everyone from the folder at once)
![50371b2ab1a4d7e024.jpeg](https://user-images.githubusercontent.com/99369164/177011202-8fc00e9e-a346-4d67-807d-12d8755818b5.jpeg)

**Comment by r10s** [comment]
yip, that's probably nice, we also thought about sth. like that several times.

however, this issue tracker is about bugs and things some dev is concretely working on the next time.

feature requests should go to the forum at https://support.delta.chat/c/features/6
