### ISSUE TITLE
add a message box when starting AEAP

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2328]
when the user changes their email address, add a message box and show some information about what will happen.

**Comment by Hocuri** [comment]
Draft for the text:

> You changed your email address.

> Contacts using Delta Chat will automatically replace you in all groups as soon as they get a message from you.

> If possible, set up your old email provider to forward all emails to your new email address.

> Read more about what happens when you change your email address at TODO INSERT AEAP HELP/BLOG POST HERE.

**Comment by r10s** [comment]
below would be  Continue / Cancel buttons right?

maybe better do not add the link to the flowtext, this is not so easy on the different platforms and also tricky wrt translations. i suggest to add a button "More Info" that then opens the webpage or whatever. also this would not block things as currently we do not know where to link to.

**Comment by Hocuri** [comment]
Makes sense; the disadvantage is that the device chat may need another text that contains a link (if this is important to us).

I just noticed that we have to slightly change the text: ~in all groups as soon as they get a message from you.~[in the groups you send a message to.](https://github.com/deltachat/deltachat-core-rust/pull/3491) (or sth. like this)

**Comment by r10s** [comment]
we can still use the same text and add "More Info: URL" to the end.

but if we have two texts at the end, that's also okay and probably makes wording easier.

**Comment by rosano** [comment]
> > You changed your email address.
> > Contacts using Delta Chat will automatically replace you in all groups as soon as they get a message from you.
> > If possible, set up your old email provider to forward all emails to your new email address.
> > [More Info]       [Cancel] [Continue]

I might not fully understand the context here, but the first phrase gives me the impression that the address was already changed—if so, what's the different between Cancel and Continue?

I would try to inform about all of this in a way that is always visible/accessible (like in a settings pane), as opposed to only in a dialog box which disappears and must be triggered somehow to access the information.

**Comment by adbenitez** [comment]
> I would try to inform about all of this in a way that is always visible/accessible (like in a settings pane), as opposed to only in a dialog box which disappears and must be triggered somehow to access the information.

that is why I recommended using a device message that is always accessible instead of an ephemeral dialog

**Comment by Hocuri** [comment]
I think that @r10s' idea was to show both a dialog and a device message.

> I might not fully understand the context here, but the first phrase gives me the impression that the address was already changed—if so, what's the different between Cancel and Continue?

- User edits their address in "Password and Account"
- Clicks on OK (or the checkmark)
- Then, this dialog is shown
- Cancel gets them back to the "Password and Account" screen, where they can edit the address back or cancel changing stuff altogether
- Continue actually applies the address change

But we can also call it "You are about to change your email address."

**Comment by r10s** [comment]
> I think that @r10s' idea was to show both a dialog and a device message.

yip - but if we find out that a ephemeral confirmation dialog is not needed at all, that would be even better as less work in all UIs :)

**Comment by Simon-Laux** [comment]
> as less work in all UIs :)

Note: dialogs are easy to add in desktop, if there are just confirmation dialogs then they are trivially easy.
on iOS confirmation dialogs are also not hard, it's standard ui.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/2342
