### ISSUE TITLE
Context-free string

### ISSUE THREAD

**Issue by rosano** [deltachat/deltachat-android#2335]
@link2xt [explained to me](https://github.com/deltachat/deltachat-android/pull/2331#issuecomment-1176487680) that the following localized string is designed to be replaced in another context:

https://github.com/deltachat/deltachat-android/blob/e14dbd5c3be67db0e29a5a7c2d09e1ecd82f1875/res/values/strings.xml#L714

> > When does this appear? It reads to me as 'The group left' but maybe it means 'You left the group'?
> 
> It's one of those weird strings mentioned in [deltachat/deltachat-core-rust#3429](https://github.com/deltachat/deltachat-core-rust/issues/3429)
> 
> Full sentence is formed by removing the period and attaching the translation of "by %s", e.g. "Group left by you".
> 
> Proper fix is to remove this string and translate the sentence "You left the group" as a whole.

I would recommend to follow his fix by using an entire sentence as a localized string. This makes translation less opaque (people don't need to figure out how the string will be used because it contains all the context), and also avoids encoding English specific grammar into the programming (removing punctuation and replacing placeholders is an example of this).

**Comment by r10s** [comment]
ftr: this will probably be targeted by https://github.com/deltachat/deltachat-core-rust/pull/3518
