### ISSUE TITLE
option to remove notification in notification drawer

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#234]
Personally I don't need to see 
Connected to (email address)
Waiting for messages
In my notification area all the time
Maybe an option for when there are errors only or when it is disabled. (Can it be disabled even?)

I would love some options I this area.

**Comment by omid3098** [comment]
I second this request.

**Comment by ijurisic** [comment]
Please add option for hide this message in notificatio area.

**Comment by Ampli-fier** [comment]
Hi folks, thanks for your contributions.

This was discussed earlier with the conclusion that the notification is needed when not using GCM (Google Cloud Messaging). For details see issue #82.
