### ISSUE TITLE
The screen turns off while the voice message is playing

### ISSUE THREAD

**Issue by bmivzkrp** [deltachat/deltachat-android#2345]
Android version: 6.0
Device: Impression ImSmart C551
Delta Chat version: 1.30.3 (F-Droid)
- Steps to reproduce the problem:
Just start playing any voice message.
Actual behavior: About ten seconds after playback starts, the screen turns off and playback stops.
Expected behavior: The screen turns off according to the Android system settings. In addition, I would like to be able to listen to the voice message even when the screen is turned off (blind users often find this convenient).

Many thanks for fixing this issue.

**Comment by gerryfrancis** [comment]
Thank you for your report, however, this issue has been on the radar for quite a long time: https://github.com/deltachat/deltachat-android/issues/1022

Closing here...
