### ISSUE TITLE
Exodus tracker finds GMS classes

### ISSUE THREAD

**Issue by licaon-kter** [deltachat/deltachat-android#2349]
Last time we did this we were looking at apktool and decompiled classes, fixed in https://github.com/deltachat/deltachat-android/pull/2303

F-Droid now integrates _(but not yet enforces)_ Exodus trackers scanning capabilities, and we scanned the current repo and we're in the middle of a clean up.

See long thread here: https://gitlab.com/fdroid/fdroidserver/-/issues/1004

In this scan DeltaChat popped up again but Element did not (!!)
```
$fdroid scanner --verbose --exodus com.b44t.messenger_632.apk
DEBUG: Starting new HTTPS connection (1): reports.exodus-privacy.eu.org:443
DEBUG: https://reports.exodus-privacy.eu.org:443 "GET /api/trackers HTTP/1.1" 200 None
DEBUG: 428 trackers signatures loaded
INFO: Scanning APK with dexdump for known non-free classes.
DEBUG: > /usr/bin/dexdump /tmp/tmpw_8kem8z/classes.dex
DEBUG: > /usr/bin/dexdump /tmp/tmpw_8kem8z/classes2.dex
DEBUG: Found class 'com/google/android/gms/tasks/OnFailureListener'
DEBUG: Found class 'com/google/android/gms/location/LocationResult'
DEBUG: Found class 'com/google/android/gms/location/FusedLocationProviderClient'
DEBUG: Found class 'com/google/android/gms/location/LocationRequest'
DEBUG: Found class 'com/google/android/gms/location/LocationCallback'
DEBUG: Found class 'com/google/android/gms/tasks/OnSuccessListener'
CRITICAL: Found problems in /home/fdroid/scanner/com.b44t.messenger_632.apk
WARNING: Scanner found 6 problems in /home/fdroid/scanner/com.b44t.messenger_632.apk:
```

Looking at deps
```
$gradle dependencies --configuration fatReleaseCompileClasspath
...
+--- org.maplibre.gl:android-sdk:9.4.0
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
|    \--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0
...
```

First thing `com.mapbox.mapboxsdk:mapbox-android-accounts` is not-FOSS see [maven](https://mvnrepository.com/artifact/com.mapbox.mapboxsdk/mapbox-android-accounts/0.7.0) and [this issue](https://github.com/mapbox/mapbox-gl-native-android/issues/316)

Also not sure why maplibre still depends on com.mapbox, but that's another issue I guess.

apktool > com.b44t.messenger_632/smali_classes2/
```
$ grep gms -rin 
/com/mapbox/mapboxsdk/location/engine/GoogleLocation...smali
8<-----moar of this
...
```
...coming from here I guess https://github.com/maplibre/maplibre-gl-native/blob/android-v9.4.0/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl.java#L13

/LE: disabled 631&632 https://gitlab.com/fdroid/fdroiddata/-/commit/bbe1be46dffe071335d24296133b9815edfe198d

**Comment by r10s** [comment]
hm, in my understanding, the classes are actually not part of the apk.

eg, if you do `apktool d deltachat-fat-debug-1.31.1.apk` and then `grep -ril FusedLocationProviderClient .` you find code that would call FusedLocationProviderClient - but that code would fails if actually executed. and it is not executed. the removal is done at https://github.com/deltachat/deltachat-android/pull/2303

**Comment by adbenitez** [comment]
> also, i am pretty unhappy about the fast removal; this makes checking carefully and discussions very hard.

yes, now I can't download the apk and analize it :-/

**Comment by licaon-kter** [comment]
I've attached the APK to the GItlab issue.

F-Droid gets flack if it's too slow, now was fast, or if it did not find a non-FOSS issue, or now if it does. :roll_eyes:

**Comment by adbenitez** [comment]
> I've attached the APK to the GItlab issue.

yes, found already, sorry, read here before there ;P

**Comment by adbenitez** [comment]
@licaon-kter analyzing the apk the `gms` warnings are false positives from exodus

**Comment by hpk42** [comment]
We uploaded the F-droid APK in question here https://download.delta.chat/android/beta/com.b44t.messenger_632.apk as a full file, so that more people can look into it.  Note that F-droid has already removed all versions of Delta Chat since September 2021 which means everyone who now tries to install Delta Chat gets a very old version.

**Comment by r10s** [comment]
> @licaon-kter analyzing the apk the gms warnings are false positives from exodus

yip, i can confirm that. false positives.

**Comment by adbenitez** [comment]
pasting here comment from gitlab:

I analyzed the Delta Chat apk and it doesn't have any gms blobs, that are false positives from exodus, so the real issue is about mapbox-android-accounts as [@tad](https://github.com/tad) said?
to test:

```
wget https://download.delta.chat/android/beta/com.b44t.messenger_632.apk
apktool decode -o com.b44t.messenger_632  com.b44t.messenger_632.apk

# this fails, no gms is in the apk, false positive from exodus:
du -sh com.b44t.messenger_632/smali*/com/google/android/gms/

# this is present:
du -sh com.b44t.messenger_632/smali*/com/mapbox/android/accounts
```

besides mapbox-android-accounts, anything else that would be needed to be fixed for the app to be 100% free software?

**Comment by licaon-kter** [comment]
@adbenitez 
> anything else that would be needed to be fixed for the app to be 100% free software?

Isn't this on a checklist when adding a new dependency to begin with?

**Comment by adbenitez** [comment]
> Isn't this on a checklist when adding a new dependency to begin with?

this is nothing super new, it was used since a lot of time without it even being noticed by f-droid folks :walking_man:

**Comment by hpk42** [comment]
@licaon-kter of course we take care to only include foss dependencies -- which is why we moved to maplibre -- but we can not always check the dependencies of dependencies but rather trust the "top" level declaration.

**Comment by licaon-kter** [comment]
We've been having the "maps in DeltaChat are problematic" discussion [for >3 years already](https://gitlab.com/fdroid/fdroiddata/-/issues/1611).

**Comment by adbenitez** [comment]
@hpk42 who would have expected something called map**Libre** to be not libre XD

**Comment by adbenitez** [comment]
@licaon-kter I am struggling to load gitlab page (via proxy because gitlab.com blocks access to my country) to reply your comment :hourglass_flowing_sand:

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/admin/-/issues/159 :shrug:

**Comment by r10s** [comment]
@licaon-kter to sum up:

- the mapbox-android-accounts issue should be solved by #2351
- the GMS issue was a false positive of the Exodus scanner

can you please re-enable auto-update that was disabled at https://gitlab.com/fdroid/fdroiddata/-/commit/bbe1be46dffe071335d24296133b9815edfe198d ? we likely tag a new version soon and like to avoid more delays. thanks!

also, while it would have been more fun if it was timing wise differently - please let me note that i appreciate the check of non-FOSS code, thanks a lot for that.

**Comment by licaon-kter** [comment]
So this will fix both issues like Element did, no references in smali too?/

**Comment by adbenitez** [comment]
@licaon-kter no idea if the false positive will still pop up, in theory if it is not popping up for element it shouldn't for DC, I don't have the fdroid scanner and can't download it at the moment, maybe other dev could test, but still it would be only false positives, I checked the decompiled apk and there is no gms blobs

**Comment by licaon-kter** [comment]
Build testing now...

**Comment by licaon-kter** [comment]
no joy :(
```
...
INFO: Scanning APK with dexdump for known non-free classes.
DEBUG: > /opt/android-sdk/build-tools/30.0.2/dexdump /tmp/tmpcj_x8tmj/classes.dex
DEBUG: > /opt/android-sdk/build-tools/30.0.2/dexdump /tmp/tmpcj_x8tmj/classes2.dex
DEBUG: Found class 'com/google/android/gms/location/LocationResult'
DEBUG: Found class 'com/google/android/gms/location/LocationRequest'
DEBUG: Found class 'com/google/android/gms/location/FusedLocationProviderClient'
DEBUG: Found class 'com/google/android/gms/tasks/OnFailureListener'
DEBUG: Found class 'com/google/android/gms/tasks/OnSuccessListener'
DEBUG: Found class 'com/google/android/gms/location/LocationCallback'
CRITICAL: Found problems in build/com.b44t.messenger/build/outputs/apk/fat/release/com.b44t.messenger-fat-release-unsigned-1.32.0.apk
ERROR: Could not build app com.b44t.messenger: Found blocklisted packages in final apk!
```
Deps
```
+--- org.maplibre.gl:android-sdk:9.5.2
|    +--- org.maplibre.gl:android-sdk-geojson:5.9.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    \--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
```

```
.../smali_classes2/com $ grep \/gms -rin .|cut -d ":" -f1|sort|uniq
./mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.smali
./mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl$GoogleLocationEngineCallbackTransport.smali
./mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl.smali
./mapbox/mapboxsdk/location/engine/LocationEngineProvider.smali
./mapbox/mapboxsdk/location/engine/LocationEngineResult.smali
```
...as expected since that lib is build using GMS libs.

**Comment by r10s** [comment]
thanks for checking. exodus and `grep` seem to find references to non-existent code; this seems expected by the current state of the tools.

so, to be precise, is there anything that stands in the way of 1.32.0 being added to f-droid again and solve annoying and maybe even harmful  issues for new users?

**Comment by licaon-kter** [comment]
Element deps tree
```
+--- org.maplibre.gl:android-sdk:9.5.2
|    +--- org.maplibre.gl:android-sdk-geojson:5.9.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    \--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0  
+--- org.maplibre.gl:android-plugin-annotation-v9:1.0.0
```
apktool diassemble the APK but `grep \/gms -rin smali*` yields no results.

Not sure what Element does differently.

**Comment by Hocuri** [comment]
@licaon-kter is there anything left we have to do so that DeltaChat can get back into F-Droid?

- Element deps are same as for Delta Chat
- The script finds a false positive, because https://github.com/maplibre/maplibre-gl-native/blob/main/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl.java references classes that would be non-free if they were compiled in, but they are not compiled in.
- Element doesn't trigger the false-positive, probably because they are using Proguard.
- I just played around a bit with ProGuard and build.grade, trying to exclude this file, but didn't find way after a few hours.
