### ISSUE TITLE
vpn bypass?

### ISSUE THREAD

**Issue by proItheus** [deltachat/deltachat-android#2357]
- Android version:12
- Device:poco f3
- Delta Chat version:1.22.1
- Expected behavior: follow android vpn service
- Actual behavior: I have an email account which requires a vpn to login.But even though I have enabled vpn on the device, deltachat will throw 'connect timeout' and I can't find connection attempts from deltachat in the vpn's log. I changed several vpn clients and the problem persists.
- Steps to reproduce the problem: enable vpn on android device, then try to login to any email account. Deltachat appears not to use the vpn.

sorry for my bad English :)

**Comment by gerryfrancis** [comment]
@proitheus Thank you for your report. Which VPN app/service do you use? AFAIK some of these must be configured to give third party apps like Delta Chat access to the VPN gateway. Please check your firewall rules, too.

**Comment by r10s** [comment]
closing stale issue, requested additional information missing
