### ISSUE TITLE
remove requirement for contacts permission.

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#236]
The contacts database on android is less secure than a postcard.
While I can deny access to the permission delta chat complains it needs it to access your friends across all devices insistently.
A internal secure contract database would be far more secure than goggle and any unscrupulous developers information mine.
Or at least let me deny access just once understanding I have a reason to deny the permission 

I think this has been causing delta chat to freeze up requiring me to force closer it often.

**Comment by r10s** [comment]
> Or at least let me deny access just once understanding I have a reason to deny the permission

Thank you for your post. At least since Mashmallow (Android 6/SDK 23), if you have denied the access to the contacts database once, Delta Chat should no longer ask for permissions. So, I am not sure, if this is still an issue. Which Android version are you using?

Regarding the access to the contacts database at all: We use it because it is used by many Android users and we want to allow the users to access their contacts in a convenient way. If users regard the contacts database as insecure and do not add their contacts to it, I think there is no additional security risk in reading an empty database.

**Comment by nutpantz** [comment]
Yes using Samsung marsh mellow.
It asks me for contacts permission regularly
And since I started blocking it  I have had errors that delta chat is not responding and had to force close it almost as regularly. So there is definitely a issue there.

I understand most people use the built in contacts but then I know most people don't realize just what a security risk they are.
Promoting good security practices is essential

(Btw is deltacrypt compatible with k9mails new autocrypt support(not that I can figure out how to turn it on in k9mail))

**Comment by r10s** [comment]
> Yes using Samsung marsh mellow.

Okay, don't know about the Samsung Android, but at least in stock Android, the permission should requested only once (however, the whole progress can be improved some time ...) 

> It asks me for contacts permission regularly

How often? Every time you open the contacts?

> And since I started blocking it I have had errors that delta chat is not responding and had to force close it almost as regularly. So there is definitely a issue there.

Okay, but _this_ issue may also come from the blocking (which, of course, could be prevented if Delta Chat would be more graceful)

> I understand most people use the built in contacts but then I know most people don't realize just what a security risk they are. [...]

I can imagine several risks, but which security risks are you talking about concretely?  Do you use the contact database at all? If not, you can easily give Delta Chat permissions to it (of course, you can also do so if you use it - Delta Chat, in contrast to most other messengers, does not send the contacts, or hashes from them, anywhere)

> (Btw is deltacrypt compatible with k9mails new autocrypt support(not that I can figure out how to turn it on in k9mail))

Yes. K-9 and Delta use the same Autocrypt :) In fact, we're in close contact to the K-9 authors to solve remaining issues.

**Comment by nutpantz** [comment]
It asks me randomly for contacts.usually after it force closes but sometimes when I have not used it in a few hours.
I get the freeze and force close randomly. However it is usually with a new mail arriving
(So in my view it gets the mail tries to lookup the contract and can't so it freezes )

I use contacts for a few things that I just can't find another way to do.
(To black list and white list calls and text)
As for security risks for contacts.
Other than every free game and app wanting the permission (not to mention Facebook, snap chat, Twitter and just about every fitness tracking app) so they can advertise to your friends.(yes I get spam mail from fitbit, petstores and Amazon thanks to my sister)
Samsung will not let you use the camera gallery without reading your contacts and gallery transfers data to both Samsung and Google (and I pray my fire wall or host file is blocking that)

I wish I could find a open source no internet sync secure encrypted contract database and phone dialer.
(The best I have found so far is essential pim but it's not open-source)

(Please ask the k9mail developers to publish some instructions on using auto crypt,I would but I have to sign up to Google accounts to use k9mail forums)

**Comment by r10s** [comment]
Okay, after a force close, the _do-no-longer-ask-for-contact-permissions-state_ is resetted (it's only saved in memory), this is okay and would not be a problem if there won't be a crash...

Regarding the contact to K-9 developers: you can contact them yourself here: https://github.com/k9mail/k-9

**Comment by r10s** [comment]
> Or at least let me deny access just once understanding I have a reason to deny the permission

This is added by https://github.com/deltachat/deltachat-android/pull/251 - I close this issue now as we won't give up reading the system contact database for reasons explained above.
