### ISSUE TITLE
Contact name in message "Member xy added" is unreadable 

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#237]
When adding members to a group, the name or e-mail address of the added contact is displayed in an unreadable color, see image.

![image](https://user-images.githubusercontent.com/9800740/34532009-c066b828-f0b4-11e7-9d24-11db4fd077ea.png)

I think this has something to do with the orange color set used to identify system messages.

**Comment by csb0730** [comment]
Hi Björn

I see a similar/same behaviour. see attachment.

Am 3. Januar 2018 18:35:53 MEZ schrieb "Björn Petersen" <notifications@github.com>:
>When adding members to a group, the name or e-mail address of the added
>contact is displayed in an unreadable color, see image.
>
>![image](https://user-images.githubusercontent.com/9800740/34532009-c066b828-f0b4-11e7-9d24-11db4fd077ea.png)
>
>I think this has something to do with the orange color set used to
>identify system messages.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-android/issues/237

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by r10s** [comment]
@csb0730 Thank you for your post. However, I didn't got the attachment. Maybe you should add it directly in the webinterface and not attach it it an email reply.

**Comment by csb0730** [comment]
ok, I'll add it by tomorrow :)
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by csb0730** [comment]
ok, nevertheless the picture from my side:
![screenshot_2017-12-29-10-15-38-1](https://user-images.githubusercontent.com/30560716/34578686-3e91d5ee-f186-11e7-90bc-327675766522.png)

**Comment by r10s** [comment]
Thank you! The fix will be in the next release then.
