### ISSUE TITLE
For mobile phone version with Outlook account,msg is never got provided you keep Delta Chat foregrounded or backgrounded from before msg is sent from other client account.

### ISSUE THREAD

**Issue by GitKKg** [deltachat/deltachat-android#2370]
- Android version:Android 11
- Device:Sony J9110
- Delta Chat version:1.32.0
- Expected behavior:Msg could be got when Delta Chat is at foreground or background
- Actual behavior:Not got always so long as I keep Delta Chat foregrounded or backgrounded 
- Steps to reproduce the problem:for email **outlook** account A, keep Delta Chat foregrounded(in chater list UI) or backgrounded ,then sent a Msg from another Delta Chat client account to email account A, provided keeps Delta Chat foregrounded or backgrounded, the msg is never got. But if you make a switch from foreground to background then foregound, the msg will be got.
- Screenshots:
- Logs:
I made some analysis on log, seems this section matters:
08-22 **18:56:50**.777 31993 32033 I DeltaChat: src/imap/idle.rs:57: **INBOX: Idle entering wait-on-remote state**
**(here just take 20 seconds as example, actually I ever waited for more than 20mins ,still not get msg if I don't first minimize then foreground Delta Chat again)**
08-22 **18:57:09**.559 31993 31993 I **PassphraseRequiredActionBarActivity: onPause()**
08-22 18:57:10.336 31993 31993 I DeltaChat: ++++++++++++++++++ last ForegroundDetector.onActivityStopped() ++++++++++++++++++
08-22 18:57:10.339 31993 31993 I PassphraseRequiredActionBarActivity: onDestroy()
08-22 18:59:49.589 31993 32477 I DeltaChat: ++++++++++++++++++ FetchWorker.doWork() started ++++++++++++++++++
08-22 18:59:49.589 31993 32033 I DeltaChat: src/context.rs:218: starting IO
08-22 18:59:50.204 31993 31993 W PassphraseRequiredActionBarActivity: onCreate(null)
08-22 18:59:50.229 31993 31993 I DeltaChat: ++++++++++++++++++ first ForegroundDetector.onActivityStarted() ++++++++++++++++++
08-22 18:59:50.229 31993 32033 I DeltaChat: src/context.rs:218: starting IO
08-22 18:59:50.229 31993 32486 I DeltaChat: calling maybeNetwork()
08-22 18:59:50.229 31993 32486 I DeltaChat: maybeNetwork() returned
08-22 18:59:50.230 31993 32033 I DeltaChat: **src/imap/idle.rs:83: Idle wait was interrupted**
08-22 18:59:50.230 31993 32033 I DeltaChat: src/imap/idle.rs:83: Idle wait was interrupted

seems Idle is never interrupted when you keep DeltaChat foregrounded from before Msg is actually sent from another client side.
same to keep DeltaChat backgrounded or minimized from before Msg is actually sent from another client side, but this correpongding log is tricky to be got for me.

**Same conditions for PC version 1.32.0, get same issue too**

**Same conditions for Gmail account, just works normal,msg is got in 1min,no matter foreground or background**  (**CONDSTORE relevant?**)

**Comment by GitKKg** [comment]
Same conditions for Zoho account, just works normal, so this issue is definitely related with CONDSTORE !

Outlook just don't support CONDSTORE!

**Comment by gerryfrancis** [comment]
@GitKKg Thank you for your report. I do not think that the lack of CONDSTORE support can be blamed here. I have tested with yesterdays Delta Chat nightly build (version 1.33) in conjunction with a GMX Freemail account that has no CONDSTORE support either, and I cannot reproduce your issue. If you want to repeat your tests with one of the latest nightly builds available, please download from here https://download.delta.chat/android/nightly/ and report back. Thank you!

**Comment by gerryfrancis** [comment]
@GitKKg When you experience the issue described, does it happen with a WLAN or mobile network (e.g. LTE) data connection, or both?

**Comment by GitKKg** [comment]
> @GitKKg When you experience the issue described, does it happen with a WLAN or mobile network (e.g. LTE) data connection, or both?

both  WLAN and mobile get this issue, but only in outlook email now, zoho and gmail is ok, and zoho response very quick, the client will wake up from suspend in 12s after meesage sent from other account, so as you said, maybe outlook email now itself get some issue

**Comment by gerryfrancis** [comment]
@GitKKg Please update to the latest version of Delta Chat, as numerous communication improvements have been implemented in the meantime. Should the problem persist, please enable "Reliable Background Connection" in the notification section of the Delta Chat settings before coming back here to report. Thanks!

**Comment by GitKKg** [comment]
@gerryfrancis ,I made test,android and PC are all OK now, no that notification problem anymore for outlook email,this is really a big good news!Thank you very much!

**Comment by gerryfrancis** [comment]
@GitKKg Glad to know that the issue is solved, thank you for confirming! :)
