### ISSUE TITLE
RTL: Green dot indicator is stretched 

### ISSUE THREAD

**Issue by maemunman** [deltachat/deltachat-android#2397]
- Android version: 12
- Device:Samsung GS20
- Delta Chat version: 1.34.1
- Expected behavior: The green dot next to a thread would be a small circle as it is in a left-to-right language.
- Actual behavior: If the device is using a right-to-left language, such as persian, it is stretched. 
- Steps to reproduce the problem: Just put the device into persian or arabic or something, then look at the inbox. There needs to be a thread with a green dot next to it in order for you to see it.
- Screenshots:
![Screenshot_۲۰۲۲۱۰۱۷-۱۰۵۱۵۵_DeltaLab](https://user-images.githubusercontent.com/32847759/196249249-402b8eb6-e438-4e29-824b-b8c00c05f64e.jpg)
- Logs: none

**Comment by r10s** [comment]
thanks for filing the issue, looks interesting :)

(maybe left/right is used instead of start/end)

**Comment by maemunman** [comment]
![Screenshot_۲۰۲۲۱۰۱۷-۱۲۲۵۱۵_DeltaLab](https://user-images.githubusercontent.com/32847759/196265958-6484a65d-c547-4b99-a6f2-0ff22660a85e.jpg)
