### ISSUE TITLE
Messages not coming in anymore (probably due to dead idle tasks caused by network change)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2400]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 11.

- Delta Chat Version:
1.33.0-1.34.5.

- Expected behavior:
Messages are coming in when the app is not focused and WLAN is the active network gateway.

- Actual behavior:
Messages are not coming in when the app is not focused and WLAN is the active network gateway.

- Steps to reproduce the problem:
-- Wait for the issue to occur, but use some other apps in the meantime. (WLAN and mobile data must be enabled on the device.)

- Screenshots:
N/A.

- Logs:
[deltachat-log-20220921-131932_2.txt](https://github.com/deltachat/deltachat-core-rust/files/9675549/deltachat-log-20220921-131932_2.txt)

- Remarks:
I doubt that the change from async-std to tokio has something to do with it. I think the culprit lies in how Delta Chat core recognizes old and new network tasks after a different network gateway is activated by the OS.
![2022-09-26-19-51_2](https://user-images.githubusercontent.com/51095533/193065254-62b9c59d-2f1e-4983-888d-5b2c5f202fac.png)
This switch in Android developer options seems to drive two networks, e.g. LTE and WLAN, in parallel to improve delays for switching between the two networks. When enabled (default setting), the tasks bound to the LTE connection might remain in the back when WLAN is active. Delta Chat might try to hold on to the LTE connection tasks at some time, probably the app cannot distinguish between the "old" and "new" idle tasks properly, and various requests might run into a timeout. I cannot reproduce the issue after I disabled this developer function.
An [Android technote](https://developer.android.com/training/basics/network-ops/reading-network-state) says this:
`All Android apps have a default network. The system decides which should be the default network. The system typically prefers unmetered networks to metered ones and faster networks to slower ones. When an app issues a network request, such as with [HttpsURLConnection](https://developer.android.com/reference/javax/net/ssl/HttpsURLConnection), the system satisfies this request using the default network. Apps can send traffic on other networks, too.`
And further:
`When a new network becomes the default, any new connection the app opens uses this network. At some point later, all remaining connections on the previous default network are forcefully terminated.`
So, the old connections seem to exist for a while, but they do not carry any data as soon as a different network has been set as default. The core might see the old tasks in memory, and therefore does not create any new ones. At a later time, the old tasks are getting killed by the OS, and new network tasks are never created when the app is never focused. This is just speculation, of course, but I guess that is what occurs in the connectivity background.
Folks, this is a serious issue that has been torturing a few Delta Chat users (including myself), and messages can be delayed for hours. Some users are losing their temper, and things are derailing a little bit. These users have no idea about Android developer options, some cannot even get to them (and I am quite glad about it, otherwise they might mess up their device). Please have a look at this stuff as soon as possible, thank you very much! :)

**Comment by gerryfrancis** [comment]
> we use targetSdkVersion 30

From https://developer.android.com/google/play/requirements/target-sdk :

> Starting in November 2022, app updates must target API level 31 or above and adjust for behavioral changes in Android 12; except for Wear OS apps, which must target API level 30 or higher.

@link2xt @r10s Does the app have to comply with API level/SDK version 31 until the end of October?

**Comment by gerryfrancis** [comment]
> If you can reproduce the situation where you bring the app to foreground, maybeNetwork is called, but messages are not downloaded over IMAP and collect the log, this will be useful for core debugging.

@link2xt In fact, new messages are received (downloaded) after maybeNetwork is triggered by focusing Delta Chat. The problem appears when that developer function switch is on - remember, that is a default value since Android >10 in some ROMs, probably introduced with a certain API level - , Delta Chat is not focused, and the network has changed from mobile data to WiFi before. I cannot get a log out of Delta Chat and see what has happened so far unless I focus the app to do so. Is there any other information I could submit to you to support you?

**Comment by gerryfrancis** [comment]
I think Google wants Android app developers to cope with the newer requirements the recent API levels come along with. So much for their compatibility dedication... ;)

**Comment by Gh0stz0x** [comment]
I also confirm this bug.

**Comment by r10s** [comment]
> [...] so there are two tasks:
>
> - check that dc_maybe_network() is called by Android app on any network state change (doesn't matter if default network changed, wi-fi enabled, whatever)

i tried a fix at https://github.com/deltachat/deltachat-android/pull/2403, but i am a bit sceptical, see comment in the pr.

> - ensure that we actively probe that IMAP connection is still working when dc_maybe_network() is called and create a new connection if we cannot get a reply from the server within timeout

does core actually take care of that? this is not clear to me by the following comments.

**Comment by r10s** [comment]
beside #2403 there is now also #2407, updating appcompat dependencies, that may help on this issue.

**Comment by gerryfrancis** [comment]
I have got news from my mate currently using version 1.34.3 from F-Droid, she still has been experiencing no new messages coming in unless the app gets into foreground. Here is the log from her device, a Google Pixel 3a running Android 12:

[deltachat-log-20221112-172039_052816_2.txt](https://github.com/deltachat/deltachat-android/files/9996025/deltachat-log-20221112-172039_052816_2.txt)

Especially this line has caught my eye:

`11-12 15:41:55.343 23384 23417 W DeltaChat: src/imap/idle.rs:86: Idle wait errored: Io(Os { code: 103, kind: ConnectionAborted, message: "Software caused connection abort" })`

This is plain Google factory ROM, no antivirus, no firewall. no proxy, not even a Google account.

`Mobile data always active` is enabled.
`WiFi` is enabled.
`Bluetooth` is enabled.
`Mobile data` is enabled.

**Comment by gerryfrancis** [comment]
I am afraid to report that the bug has striked again:

[deltachat-log-20221120-210635_2.txt](https://github.com/deltachat/deltachat-android/files/10050882/deltachat-log-20221120-210635_2.txt)

Maybe this time the log includes more information on why this fails. I wished I could read the code, so I suspect the Worker threads to be unable to hold/maintain IMAP idle after they have been rebuilt. They just seem to be silent and do nothing.

**Comment by gerryfrancis** [comment]
[deltachat-log-20221122-013039_2.txt](https://github.com/deltachat/deltachat-android/files/10061764/deltachat-log-20221122-013039_2.txt)

Any idea why `getChatMsgs(39)` behaves like it is out of control?

**Comment by gerryfrancis** [comment]
A current log from a Google Pixel 3a device running stock Android 12 with `reliableService=true`:

[deltachat-log-20221128-201006_2.txt](https://github.com/deltachat/deltachat-android/files/10108064/deltachat-log-20221128-201006_2.txt)

`IMAP IDLE failed: io: Connection reset by peer (os error 104)`, I got this on my own device (Fairphone FP2), too. My email provider is different (Posteo, for this case it is Magenta/T-Mobile Austria). In fact, so are the device, the Internet access, the Android version (mine is 11), eventually everything is different.

`ignoreBatteryOptimizations` is `true` for both cases.

It seems that the `reliableService` obviously is not reliable. The email was delivered to the recipients Inbox just five seconds after it had been sent off, so the supply chain of email hosts is not to blame.

Do you need any further information to troubleshoot and pinpoint? I am willing to perform and deliver anything I can to get this under control, my contact has lost faith in the reliability of message delivery.

`reliableService` has been set back to `false` because it did not help to cure the problem.

Many thanks in advance, guys! :heart: :heart: :heart:

**Comment by gerryfrancis** [comment]
@hpk42 I think it _is_ related, but I did not know that it affects the Desktop client, too. So is this a core issue?

**Comment by gerryfrancis** [comment]
@link2xt Thank you very much for the new test build and the detailed explanation. I am running the nightly build from 2022-12-10 (core version 1.103.0), but unfortunately the issue has reappeared. Please view the (anonymized) current log file from my device:

[deltachat-log-20221212-200050_2.txt](https://github.com/deltachat/deltachat-android/files/10212338/deltachat-log-20221212-200050_2.txt)

An "unsolicited response" ("Still here") from the IMAP server was ignored, though I have no idea whether this is relevant or not:

`12-12 19:08:16.846 11260 11299 I DeltaChat: src/imap.rs:1685: ignoring unsolicited response Other(ResponseData { raw: 4096, response: Data { status: Ok, code: None, information: Some("Still here") } })`

**Comment by gerryfrancis** [comment]
Using "reliable background connection" `reliableService=true` seems to bring no joy, too:

[deltachat-log-20221214-223823_2.txt](https://github.com/deltachat/deltachat-android/files/10231975/deltachat-log-20221214-223823_2.txt)

The app received new messages just after it had been foregrounded, while Desktop received them instantly about an hour ago. (The phone did not leave the home WiFi frequency area.) What I still do not understand are the `starting IO` lines without calling `maybeNetwork()`. How can `IO` be started when `maybeNetwork()` is not called afterwards?

**Comment by gerryfrancis** [comment]
Another log:

[deltachat-log-20221216-202658_2.txt](https://github.com/deltachat/deltachat-android/files/10254570/deltachat-log-20221216-202658_2.txt)

**Comment by gerryfrancis** [comment]
Maybe I have found the culprit, at least I hope so:

Delta Chat seems to struggle with a sudden IP address change of the device, especially when the DHCP lease time has expired. The Android client itself welcomes the new IP address successfully, and can be pinged from my notebook immediately, but the running app no longer receives any messages.

My access point features a DHCP server, and its IP address lease times for network clients are set to 86400 seconds (24 hours) equally. (They cannot be adjusted unfortunately, that SOHO router is provided by A1 Austria, they do not seem to allow that.) Sometimes my phone ("Fairphone FP2", running the latest build of "Lineage OS" based on Android 11) connects to the gateway earlier (when in range), sometimes later, which could explain why connectivity in Delta Chat is lost on one day and on the other one it is not.

However, the app recovers and receives new messages when WiFi connectivity is lost, but found (by switching the access point WLAN signal off and on) again after some time, or - more likely - due to a poor WiFi signal that has caused a dis- of and a reconnecting to a WiFi network.

In order to not only cover an IP address change caused either by DHCP lease timeout that has been reached, or by a manual static IP address modificiation, we could listen to a dedicated Android network event that informs about available IP addresses of the currently active network (e.g. use `onLinkPropertiesChanged()` and `getLinkAddresses()` of `LinkProperties()`), and compare them to the one that has been used to connect so far:

https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onLinkPropertiesChanged(android.net.Network,%20android.net.LinkProperties)

The document also says:

`Starting with [Build.VERSION_CODES.O](https://developer.android.com/reference/android/os/Build.VERSION_CODES#O) this method is guaranteed to be called immediately after [onAvailable(Network)](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onAvailable(android.net.Network)).`

That makes sense, as the phone might connect to another WiFi network than the one used before, allocating a completely different client IP address.

In any case, should the IP address differ, we may intend to kill the respective idle tasks in memory, and initiate new ones afterwards, to reestablish these connections.

I think that approach might be successful and solves the issue for good (hopefully), what do you think, @r10s and @link2xt?

**Comment by gerryfrancis** [comment]
@link2xt

> So if the address changed due to DHCP lease timeout, onLinkPropertiesChanged is called without onAvailable?

I guess so. It seems logical to me, as the network itself has not changed in this case.

> Normally the phone should keep renewing the lease even if it stays on the same network forever, so 24h timeout is not a problem.

@link2xt Yes, that is what the phone does, but the open app tasks cannot hold their connections anymore after the IP address change.

**Comment by gerryfrancis** [comment]
Also wondering if and which consequences would follow when the IP address changes from IPv4 to IPv6 and back (or vice versa).

**Comment by gerryfrancis** [comment]
@link2xt The integrated DHCP server of that ADSL modem can assign the same IP address when a permanent entry for a certain MAC address of a device is configured, of course, but I did not care for it. Also there are times when the phone is connected to at least one other WiFi network.

**Comment by gerryfrancis** [comment]
I am closing this one, as I believe that this issue has been resolved "as good as possible". Thank you very much to everybody involved for the hard work, the app seems to be much more stable and reliable to date! :)
