### ISSUE TITLE
send reactions

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2402]
sending reactions should be similar to what is discusssed on https://github.com/deltachat/deltachat-ios/issues/1728, however, as we by default use the multi-select-paradigm of android, we should keep the main title bar menu as is and show an additional reaction "area".

this is also what whatsapp is doing:

<img width=300 src=https://user-images.githubusercontent.com/9800740/197558189-0241bdeb-0b75-4b37-8264-f005b714483e.png>

- the real set of reactions needs to be discussed, assume a handful of default reactions plus the option to pick any emoji.
- if the user already reacted, their reaction should be hilited

cmp. https://github.com/deltachat/deltachat-core-rust/pull/3644, https://github.com/deltachat/deltachat-desktop/pull/2964

## timing

there is no urgency, first we'll need release that uses a core that processes reactions (core >= 98), also #2401 should be implemented first

**Comment by r10s** [comment]
>  a handful of default reactions

these are the default reactions used by some other messengers:

```
👍 whatsapp  signal  telegram   github**
👎           signal  telegram   github
❤️ whatsapp  signal  telegram   github
😂 whatsapp  signal  telegram*  github*
😢 whatsapp  signal             github*
😮 whatsapp  signal
🙏 whatsapp
🔥                   telegram
🥰                   telegram
👏                   telegram
🎉                              github
🚀                              github
👀                              github

*slightly different icon
**matrix uses the same set as github
```

*slightly different icon
**matrix uses the same set as github

**Comment by adbenitez** [comment]
since we plan to only have that set of reactions (no extra any-emoji button) I think the matrix/forgejo is the best

**Comment by r10s** [comment]
to get a grip on this issue easily, idea is to use the "move to bottom floating button" as a template

**Comment by hpk42** [comment]
On Fri, Sep 29, 2023 at 03:49 -0700, Asiel Díaz Benítez wrote:
> since we plan to only have that set of reactions (no extra any-emoji button) I think the matrix/forgejo is the best

hum, it's something that concerns more people than just android devs ;) 
would it be difficult to have a custom poll where there are all emojis (from all sources) 
and then everyone can select 6 they want? 
and then we look at the top-6? 
we could post this to the community and xyiv channels or so for the fun of it.

**Comment by r10s** [comment]
> hum, it's something that concerns more people than just android devs ;)

regarding that only 5~6 emoji fit into the "direct picker", the mentioned forgejo-set cannot be used in complete anyways.

and picking an  intersection from the table above will not only cover android devs but also people used to whatsapp/signal/telegram/imessage

additionally, for sure, some votes could be fun - and may help at least to decided for less-used emojis, where also the other messengers do not have a clear intersection. 

plan is to have an emoji picker sooner or later anyways. but, surely even then the default set is a thing :)
