### ISSUE TITLE
Can't turn off socks5 proxy after importing backup

### ISSUE THREAD

**Issue by missytake** [deltachat/deltachat-android#2405]
- Android version: 10 QP1A.190711.020
- Device: Redmi 9A / M2006C3LG
- Delta Chat version: 1.32.0
- Expected behavior: After importing a backup from desktop client, where I have configured Tor via socks5 proxy, it either works or I can disable the socks5 proxy
- Actual behavior: I can't connect to the socks5 proxy, so I can't connect to the server. Also I can't disable the socks5 proxy, because the deltachat-android configure screen doesn't have the socks5 option.
- Steps to reproduce the problem:
  - Login on the desktop client
  - configure a socks5 proxy (e.g. localhost:9050 for most tor setups on linux)
  - export a backup
  - open the Android app
  - import the backup
  - see connection errors

**Comment by missytake** [comment]
Proposal:
- either support socks5 proxys on Android, or another way to connect to tor
- or if that doesn't make sense: in the connection view, if a socks5 proxy is configured, show an option to turn it off. Could also be a device message? Maybe we should warn that tor isn't supported on Android?

**Comment by hpk42** [comment]
Android and iOS should clear this socks5 proxy flag automatically on import, maybe?

**Comment by adbenitez** [comment]
> Android and iOS should clear this socks5 proxy flag automatically on import, maybe?

not good, because then the only way/hack to configure the proxy on android is gone, this issue will be solved when the options to configure the proxy are added to android, meanwhile remove the configuration before exporting if you don't want to use it

**Comment by r10s** [comment]
> either support socks5 proxys on Android, or another way to connect to tor or if that doesn't make sense [...]

i am not too deep in this topic, but there was some recent discussion that either on ios and/or android, these socks5 settings are not needed and are supported more nicely by os or some app.

unfortunately, i cannot remember any details about the discussion nor can find any notes on that :) cc @cyBerta maybe you was involved?

(technically, it would not be very hard to add the socks5 settings - but it is quite some mess and not really user friendly, esp. if an additional app is needed anyway).

workaround for now would be to turn of socks5 proxy before export, btw. socks5 is declared as experimental anyway.

**Comment by missytake** [comment]
I would not turn off the socks5 proxy on export on Desktop - that way, after importing a backup on the same machine, connectivity would stop working.

Turning off the socks5 proxy on import on Android (and probably also iOS, don't know) makes sense, if it doesn't work anyway. But we should at least warn users: "Warning: the socks5 proxy/tor connection you used on Delta Chat desktop doesn't work on this device. Connecting to the server directly now. Proceed?" At-risk users can press cancel and research for a solution themselves (we might even put something in the FAQ, don't know). Pressing "cancel" will abort the backup import, pressing "ok" will turn off socks5 and continue with the import.

Then it's just one warning dialog during setup, which will *only* appear to those few users who configured. Not much more hassle during onboarding, not so much to implement (I hope? I can't really estimate the effort)
