### ISSUE TITLE
Voicemail stops when focus lost

### ISSUE THREAD

**Issue by maemunman** [deltachat/deltachat-android#2409]
- Android version: 12
- Device: Samsung GS20
- Delta Chat version: 1.34.2
- Expected behavior: Audio message continues to play — ideally in a background player with a notification and a queue feature so you can play multiple back to back, but that's just luxury at that point.

  Basically, the user should be able to play a voicemail with the screen off, or while looking at a different app or a different email thread.
- Actual behavior: If your screen went dark or DC lost focus, your voicemail also stopped playing.
- Steps to reproduce the problem:
    1) Start playing a voicemail
    2) Switch to a different email thread
        - Or switch to a different app
        - Or lock the screen
        - Or let the screen turn off by itself by not touching it for a few seconds
    3) Voicemail has stopped playing 
- Screenshots: n/a
- Logs: n/a

**Comment by r10s** [comment]
thanks for filing an issue!

this is probably a duplicate of an old,  long standing issue, https://github.com/deltachat/deltachat-android/issues/1022

**Comment by maemunman** [comment]
> thanks for filing the issue!
> 
> maybe this is a duplicate of an old, long standing issue, #1022

Looks like it. I apologize.

**Comment by r10s** [comment]
> Looks like it. I apologize.

nothing to apologize for, thanks for the reminder, i'd really like to see that fixed at some point, at best as a "mini media player" as a "permanent notification", that would also be great for music files ...
