### ISSUE TITLE
Include intuitive button for preview pictures in chatbox and additional actions (export)

### ISSUE THREAD

**Issue by EchedeyLR** [deltachat/deltachat-android#2414]
- Android version: Does not matter
- Device: Does not matter
- Delta Chat version: Does not matter
- Expected behavior: An icon is showed after choosing a picture and editing it in the chatbox to show more details and export it if needed.
- Actual behavior: The image in the chatbox must be pressed, which is not intuitive by default in order to access the preview and additional actions such as with the Pencil for edition.
- Steps to reproduce the problem: Choose a picture from the gallery and wait until it is showed in the chatbox. A new user could be incapable of detecting that by pressing the image a preview is showed with action to export it. Additionally, a pencil button appears for edition which may confuse some users when it is not also showed in a similar way for this case.
- Screenshots: Not needed
- Logs: Not needed

**Comment by r10s** [comment]
i see what you mean.

but not sure if that is really needed and worth cluttering the user interface.

- Delta Chat (as well as other messengers) does not have a special button for "enlarge image & options" for normally shown images in the chat as well.  
it is not unusual to tap a picture to enlarge it and get further options from there.  

- so, currently, things are consistent - if we now add an extra button for "enlarge image & options" at some places, ppl may wonder why they are not used elsewhere :)

- the actions available from the preview are not primarily needed for most users, so, it seems fine if they are a bit harder to discover. also, as the "export" would not be obvious even if we would have an "preview" icon.

so, all in all, i think, the current approach already has a good set of tradeoffs.

**Comment by EchedeyLR** [comment]
I agree with the latest point, I don't know what to say about the middle (seems a bit pointless to me when it is something related to usability and accesibility) and I have mixed ideas of the first one.

About the first one:
> it is not unusual to tap a picture to enlarge it and get further options from there.

This is what I was trying to discuss this in the first post. It is not "usual" to the point that I was not aware of that until other user told me in a conversation about it and I have been using the app for more than 3 years.

The same have happened to other people in my environment who were not aware.

In the latest point, seems like a contradiction: you say that it is not unusual yet you recognize being a bit harder to discover (?). I am a bit confused.

**Comment by r10s** [comment]
> In the latest point, seems like a contradiction: you say that it is not unusual yet you recognize being a bit harder to discover (?). I am a bit confused.

sorry to be unclear here. i meant the "export function" with a "a bit harder to discover", not the enlargement of an image.

**Comment by EchedeyLR** [comment]
What is about removing the functionality if it is not worthy to be made accessible because of its niche and also because it is not a focus itself of the Delta Chat capabilities?

**Comment by Hocuri** [comment]
Why should we put effort into removing a functionality, though? If we would want to reduce code complexity / improve maintainability in DC Android, there would be easier things to do.

**Comment by EchedeyLR** [comment]
The functionality is said to not serving higher purpose, so that is supposed to be a valid point to not making it usable/accesible.

I made an extra proposal to remove it, given that. But I now don't understand your point.

If you consider that the feature should be kept, why not making it accesible?

---

I don't see how my points are invalid about accesibility as it was recognised that the preview was not easy to catch, plus the internal options inside it.

**Comment by EchedeyLR** [comment]
In Spain, currently, there is a law that enforces accesibility and usability over software and websites developed using public funding, but there is an exception: if the effort to make that thing accesible or usable is very high in the sense of money, it can be justified.

This, however, it is used as gray area from some companies hired by the government to avoid implementing accesibility or usability properly in public infraestructure, yet when the average web developer knows that is possible easily (I think I don't need to point W3C content for it nor current websites lacking that).

Current question doesn't seem very far from that and I am a bit worried.

**Comment by r10s** [comment]
sorry if things get mixded, UX is a complicated thing :)

maybe a more general answer can shine some light on this:

_not all options need to be discoverable equal._

_many times, that would even lead to bad UX._

(1) often used options are maybe available directly, eg. by a "button"
(2) other options may follow general conventions,  eg. a "double click" does known things. 
(3) less often used options may be hidden behind some menu or require further steps - it is okay, if a user does not see it directly, UX distinguishes between _findability_ and _discoverability_ here. in classic apps, this is eg. the "main menu".

the more opetions are like (1), make the most used options less visible.

so, of course, one could argue and discuss that an extra button to "preview" does not make things much worse. and of course, one can do things differently. but still, i do not see the need, even more this is true for "export". but that does not mean that the options are superfluous and can be removed.

one could do user tests for things like that, however, i there are far more important areas that would require attention :)

for now, i suggest to close this issue as there is no actionable item. however, of course, if we get more reports about that there is a button missing, we can think this over.

**Comment by EchedeyLR** [comment]
I don't understand the relation with the point, and maybe I was not understood properly.

I understand that my proposal of an icon could not be valid but I don't understand the obscurity of the functionality.

That makes it not equally accessible for different types of people and that was a part of my point all the time. The icon was my proposal to solve that gap between different users with different perceptions.

---

Aside this, your second point seems to be a mention to "it is not unusual"-type of actions, which I still find without a proper reply for this case.

Even if I understand the discoverability of different options, this should not harm different type of users. Having to perceive it because a third party user in a spin off conversation mentioned it does not seem the best way to discover features. 

Of course, I may tell this to other people and, maybe, create a network effect, but this is not automatic, that the perception over the chatbox is not public known information as it is for the chat timeline to consider this *not unusual*.

Could, at minimum, documentation be provided towards these things? Maybe I could even participate of that in a tips section or similar of the FAQ included with the app.

**Comment by r10s** [comment]
> Could, at minimum, documentation be provided towards these things? Maybe I could even participate of that in a tips section or similar of the FAQ included with the app.

this is a good idea, we are about to update the FAQ these days anyway, so filing an issue at https://github.com/deltachat/deltachat-pages - or even do a pr there - makes a lot of sense.

**Comment by EchedeyLR** [comment]
I think this can be closed already. If anything wants to be added, can be reopened again.
