### ISSUE TITLE
Does not restore previous chats when switching account and then back

### ISSUE THREAD

**Issue by Svetlana-T** [deltachat/deltachat-android#2415]
- Android version: 12
- Device: Samsung Galaxy A12
- Delta Chat version: 1.32.0
- Expected behavior: After starting a chat in Delta Chat and switching to another email account, and then back, previous chats are still visible.
- Actual behavior: No prior existing chats are visible in this scenario.
- Steps to reproduce the problem: Log in, start a chat, click switch account, it will offer you to log in again. Log in with the same email. The chat will not be visible.
- Screenshots:
- Logs:

**Comment by Hocuri** [comment]
Logging in twice with the same email on the same device (i.e. what you did) means that you will have the same account twice on your phone, which is the same as if you use the same account on multiple devices. In this case, it would be nice to directly show created chats on all devices, but difficult to implement.

By the way, logging in twice with the same email on the same device is possible & sometimes useful for experienced users, but in most cases, you should just use the "Back" button if you changed your mind and want to go back to the first account.

I'm wondering if we should show a warning when a user tries to log in wit the same email twice.

**Comment by Hocuri** [comment]
Also, thanks for

**Comment by r10s** [comment]
the misunderstanding seem to be explained, no actionable item left, closing stale issue
