### ISSUE TITLE
App stops (crashes) on Jolla phone running Sailfish OS 3.4.0.24

### ISSUE THREAD

**Issue by M-Stenzel** [deltachat/deltachat-android#2420]
Hi team,
the latest version of DeltaChat (1.34.3) stops working on my Jolla phone (Sailfish OS version 3.4.0.24, Android 4.1 support) when choosing a communication partner, or when sending photos, etc.
The previous versions (e. g. 1.32) did not show this problem.
Sailfish OS uses the Alien Dalvik layer for Android app support. 

Attached is the log:

device=unknown Jolla (alien_jolla_bionic)
android=4.1.2 (eng.erin.20151105.144423, JZO54K)
sdk=16
memory=32M (2.42% free, 256M max)
memoryClass=128
host=erin-ubuntu
applicationId=com.b44t.messenger
app=Delta Chat 1.34.3-fat
installer=org.fdroid.fdroid
notifications=true
reliableService=false
lang=en_GB

arch=32
bcc_self=1
blobdir=/data/data/com.b44t.messenger/files/accounts/[blackened out]/dc.db-blobs
bot=0
configured_mvbox_folder=DeltaChat
configured_sentbox_folder=Sent
database_dir=/data/data/com.b44t.messenger/files/accounts/[blackened out]/dc.db
database_encrypted=false
database_version=92
delete_device_after=0
delete_server_after=0
deltachat_core_version=v1.98.0
display_name=[blackened out]
download_limit=0
e2ee_enabled=1
entered_account_settings=[blackened out] imap:unset:***:unset:0:cert_automatic:AUTH_NORMAL smtp:unset:0:unset:0:cert_automatic:AUTH_NORMAL
fetch_existing_msgs=1
fetched_existing_msgs=true
fingerprint=[blackened out]
folders_configured=3
imap_server_id=Some({})
is_configured=1
journal_mode=wal
key_gen_type=0
last_housekeeping=1668103888
level=awesome
mdns_enabled=1
media_quality=0
messages_in_contact_requests=35
mvbox_move=1
num_cpus=2
number_of_chat_messages=16981
number_of_chats=5
number_of_contacts=1235
only_fetch_mvbox=0
private_key_count=1
public_key_count=9
quota_exceeding=0
scan_all_folders_debounce_secs=60
secondary_addrs=
selfavatar=<unset>
send_sync_msgs=0
sentbox_watch=0
show_emails=0
socks5_enabled=0
sqlite_version=3.37.2
uptime=0h 0m 20s
used_account_settings=[blackened out]
webrtc_instance=basicwebrtc:https:[blackened out]

--------- beginning of /dev/log/main
11-11 15:50:47.161  4289  4289 E dalvikvm: Could not find class 'org.thoughtcrime.securesms.ApplicationContext$1', referenced from method org.thoughtcrime.securesms.ApplicationContext.onCreate
11-11 15:50:47.228  4289  4289 E dalvikvm: Could not find class 'androidx.work.impl.background.systemjob.SystemJobService', referenced from method androidx.work.impl.Schedulers.createBestAvailableBackgroundScheduler
11-11 15:50:47.234  4289  4289 E dalvikvm: Could not find class 'androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateCallback', referenced from method androidx.work.impl.constraints.trackers.NetworkStateTracker.<init>
11-11 15:50:47.347  4289  4289 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.notifications.NotificationCenter.getNotificationChannel
11-11 15:50:47.350  4289  4289 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.notifications.NotificationCenter.getNotificationChannel
11-11 15:50:47.351  4289  4289 E dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method org.thoughtcrime.securesms.notifications.NotificationCenter.getNotificationChannelGroup
11-11 15:50:47.403  4289  4289 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.connect.KeepAliveService.createFgNotificationChannel
11-11 15:50:47.476  4289  4289 E dalvikvm: Could not find class 'android.os.LocaleList', referenced from method androidx.core.os.LocaleListCompat.wrap
11-11 15:50:55.287  4289  4289 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.service.GenericForegroundService.createFgNotificationChannel
11-11 15:50:55.393  4289  4289 E dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method androidx.appcompat.widget.AppCompatImageHelper.hasOverlappingRendering
11-11 15:50:55.982  4289  4289 E dalvikvm: Could not find class 'android.content.pm.ShortcutManager', referenced from method org.thoughtcrime.securesms.connect.DirectShareUtil.lambda$triggerRefreshDirectShare$2
11-11 15:50:59.788  4289  4289 E dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method androidx.core.view.WindowInsetsCompat.toWindowInsetsCompat
11-11 15:51:00.271  4289  4385 E dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method androidx.core.app.NotificationManagerCompat.areNotificationsEnabled
11-11 15:51:00.281  4289  4385 E dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method androidx.core.app.NotificationManagerCompat.getNotificationChannelGroup
11-11 15:51:00.284  4289  4385 E dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method androidx.core.app.NotificationManagerCompat.getNotificationChannelGroupsCompat
11-11 15:51:00.286  4289  4385 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method androidx.core.app.NotificationManagerCompat.getNotificationChannelsCompat
11-11 15:51:20.451  4289  4390 E dalvikvm: Could not find class 'androidx.exifinterface.media.ExifInterface$1', referenced from method androidx.exifinterface.media.ExifInterface.getHeifAttributes
--------- beginning of /dev/log/system
11-11 15:51:24.373  4289  4289 E AndroidRuntime: FATAL EXCEPTION: main
11-11 15:51:24.373  4289  4289 E AndroidRuntime: java.lang.NoSuchMethodError: android.content.res.Configuration.getLayoutDirection
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ViewUtil.isLtr(ViewUtil.java:211)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.ViewUtil.isLtr(ViewUtil.java:207)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationItem.setThumbnailOutlineCorners(ConversationItem.java:572)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationItem.setMediaAttributes(ConversationItem.java:510)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationItem.bind(ConversationItem.java:181)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationAdapter.onBindViewHolder(ConversationAdapter.java:247)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at org.thoughtcrime.securesms.SetStartingPositionLinearLayoutManager.onLayoutChildren(SetStartingPositionLinearLayoutManager.java:37)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1867)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5260)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:524)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:615)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:92)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:137)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:4781)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:511)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
11-11 15:51:24.373  4289  4289 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
11-11 15:51:45.162  4506  4506 E dalvikvm: Could not find class 'org.thoughtcrime.securesms.ApplicationContext$1', referenced from method org.thoughtcrime.securesms.ApplicationContext.onCreate
11-11 15:51:45.221  4506  4506 E dalvikvm: Could not find class 'androidx.work.impl.background.systemjob.SystemJobService', referenced from method androidx.work.impl.Schedulers.createBestAvailableBackgroundScheduler
11-11 15:51:45.225  4506  4506 E dalvikvm: Could not find class 'androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateCallback', referenced from method androidx.work.impl.constraints.trackers.NetworkStateTracker.<init>
11-11 15:51:45.375  4506  4506 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.notifications.NotificationCenter.getNotificationChannel
11-11 15:51:45.377  4506  4506 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.notifications.NotificationCenter.getNotificationChannel
11-11 15:51:45.378  4506  4506 E dalvikvm: Could not find class 'android.app.NotificationChannelGroup', referenced from method org.thoughtcrime.securesms.notifications.NotificationCenter.getNotificationChannelGroup
11-11 15:51:45.438  4506  4506 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.connect.KeepAliveService.createFgNotificationChannel
11-11 15:51:45.517  4506  4506 E dalvikvm: Could not find class 'android.os.LocaleList', referenced from method androidx.core.os.LocaleListCompat.wrap
11-11 15:51:45.593  4506  4506 E dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method org.thoughtcrime.securesms.service.GenericForegroundService.createFgNotificationChannel
11-11 15:51:45.692  4506  4506 E dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method androidx.appcompat.widget.AppCompatImageHelper.hasOverlappingRendering
11-11 15:51:46.258  4506  4506 E dalvikvm: Could not find class 'android.content.pm.ShortcutManager', referenced from method org.thoughtcrime.securesms.connect.DirectShareUtil.lambda$triggerRefreshDirectShare$2
11-11 15:51:54.558  4506  4506 E dalvikvm: Could not find class 'android.transition.Transition', referenced from method androidx.appcompat.widget.MenuPopupWindow.setEnterTransition
11-11 15:51:54.560  4506  4506 E dalvikvm: Could not find class 'android.transition.Transition', referenced from method androidx.appcompat.widget.MenuPopupWindow.setExitTransition
11-11 15:51:59.021  4506  4506 E dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method androidx.core.view.WindowInsetsCompat.toWindowInsetsCompat

I know, the OS version is the last supported one on the device, so the Sailfish developers will not be of much help, but maybe the DC team may help in this case!?

Is there sth. in the cache that might disturb? Is there sth. in the config file that might break things? I did not change ANYTHING in the app configs directly before or after the upgrade. 

Is there someone who can confirm this problem?

Many thanks in advance, 

Martin.

**Comment by r10s** [comment]
thanks a lot for filing the issue.

the issue seems to be `11-11 15:51:24.373 4289 4289 E AndroidRuntime: java.lang.NoSuchMethodError: android.content.res.Configuration.getLayoutDirection` - and indeed, [`Configuration.getLayoutDirection()` is not available in android4.1/api16](https://developer.android.com/reference/android/content/res/Configuration)

wondering why this was no issue before, maybe a slight change or so. _if_ this is the only issue,  a fix should be easy and we can continue to support android4 :)

**Comment by M-Stenzel** [comment]
Wow, thank you indeed!

**Comment by r10s** [comment]
@M-Stenzel there is a new release candidate that, with chance, fixes the android 4.1 issue - it would be great if you can download and test one of the following APK:

here is Delta Chat 1.34.4 - choose your flavour and mind your backups:
- 🍋 https://download.delta.chat/android/beta/deltachat-gplay-release-1.34.4.apk (android, overwrites existing gplay installs, should keep data)
- 🍉 https://download.delta.chat/android/beta/deltachat-fat-debug-1.34.4.apk (android, can be installed beside gplay)

(if in doubt, you can use first APK, install it beside your existing Delta Chat and use another account for testing)

**Comment by M-Stenzel** [comment]
> @M-Stenzel there is a new release candidate that, with chance, fixes the android 4.1 issue - it would be great if you can download and test one of the following APK:
> 
> here is Delta Chat 1.34.4 - choose your flavour and mind your backups:
> 
>     * lemon https://download.delta.chat/android/beta/deltachat-gplay-release-1.34.4.apk (android, overwrites existing gplay installs, should keep data)
> 
>     * watermelon https://download.delta.chat/android/beta/deltachat-fat-debug-1.34.4.apk (android, can be installed beside gplay)
> 
> 
> (if in doubt, you can use first APK, install it beside your existing Delta Chat and use another account for testing)
> 
> if the problem persists, please post another log, reopen the issue and we will see :)

Marvellous, I installed the "gplay" version 1.34.4, and the error reading  "AndroidRuntime: FATAL EXCEPTION..." went away. I tested posting text, taking pictures, recording voice - everything works as expected! From my side I can confirm that version 1.34.4 works on my Jolla phone without any problems - thank you very much - indeed!

Martin.

**Comment by r10s** [comment]
thanks for coming back and retesting, @M-Stenzel 

i just pushed 1.34.4 for f-droid, gplay etc. will follow as well.
