### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [deltachat/deltachat-android#2426]
https://monitor.f-droid.org/builds/log/com.b44t.messenger/641#site-footer

```
+ ./ndk-make.sh
starting time: Mon Nov 14 23:18:58 UTC 2022
Setting CARGO_TARGET environment variables.
Full build
-- cross compiling to armv7-linux-androideabi (arm) --
    Updating git repository `https://github.com/async-email/async-imap`
    Updating crates.io index
    Updating git repository `https://github.com/dignifiedquire/rs-async-zip`
    Updating git repository `https://github.com/deltachat/rust-email`
    Updating git repository `https://github.com/async-email/encoded-words`
    Updating git repository `https://github.com/deltachat/lettre`
    Updating git repository `https://github.com/Majored/rs-async-io-utilities`
error: failed to get `async_io_utilities` as a dependency of package `async_zip v0.0.8 (https://github.com/dignifiedquire/rs-async-zip?branch=main#5556c5ac)`
    ... which satisfies git dependency `async_zip` (locked to 0.0.8) of package `deltachat v1.98.0 (/home/vagrant/build/com.b44t.messenger/jni/deltachat-core-rust)`
    ... which satisfies path dependency `deltachat` (locked to 1.98.0) of package `deltachat_ffi v1.98.0 (/home/vagrant/build/com.b44t.messenger/jni/deltachat-core-rust/deltachat-ffi)`

Caused by:
  failed to load source for dependency `async_io_utilities`

Caused by:
  Unable to update https://github.com/Majored/rs-async-io-utilities#6661a0fb

Caused by:
  failed to clone into: /home/vagrant/.cargo/git/db/rs-async-io-utilities-5b754873e3909201

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration
```

Could you please take a look? Thanks!

**Comment by r10s** [comment]
we probably need a new android version with a new core101 that includes this fix: https://github.com/deltachat/deltachat-core-rust/pull/3747 (some repo that we were using was just deleted)

**Comment by linsui** [comment]
By the way, I'd like to split the abi in F-Droid buil to reduce the apk size. What version code scheme should we use?

**Comment by r10s** [comment]
> What version code scheme should we use?

is there a standard or so? what are others using? cc @Hocuri @link2xt @adbenitez

**Comment by Hocuri** [comment]
> By the way, I'd like to split the abi in F-Droid buil to reduce the apk size.

Like, distribute separate APKs for arm-32bit, arm-64bit, x86-32bit, x86-64bit? Version code scheme for what? I don't understand.

**Comment by linsui** [comment]
As Google recommands and F-Droid requires, different apks should use different version codes. So we need different version codes for different abis. We can use 6411, 6412, 6413, 6414 for 4 abis.

**Comment by Hocuri** [comment]
Ah, I understand. Yes, 6411, 6412, 6413, 6414 (just adding a 1/2/3/4 to the end of the number) sounds good to me, without knowing much about this.

**Comment by linsui** [comment]
I thought I can simply patch the version code. Is that OK?

**Comment by Hocuri** [comment]
What do you mean with "simply patch"?

**Comment by linsui** [comment]
I can simply replace the version code with sed.

**Comment by Hocuri** [comment]
Sounds sensible

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12107 Updated with splitted apks.
