### ISSUE TITLE
Improve backup import

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#243]
1) It would be good to have possibility to import a backup from installed DC. In the moment it's necessary to uninstall DC first to have this function available.

2) If more than one backup file is existing in download directory it's not possible choose the right one!
Please give user a possibility to choose the desired file.

**Comment by r10s** [comment]
1. there are many corner-cases when replacing the existing configuration by an import. also UX: we have to make sure, the user understands, everything will be deleted. We do not have this problem if we let the user uninstall the app.

2. Delta chooses the newest from the Downloads-dir. You can delete or rename older ones to force importing a different one. At least for experienced users, this is fine, and I am not sure what the usecase for this would be for normal users.

While both points may make sense in some way, IMHO, unless there are some volunteers working on this issue, for now, this is out of scope.

**Comment by csb0730** [comment]
Yes I agree Björn, but regarding "chooses the newest" I saw the following behaviour:

1) I exported the current db to file named "delta-chat-2018-01-14.bak"
2) then I transfered this file to my pc, modified this file, transfered it back to "Downloads" under name "delta-chat-2018-01-14b.bak" (newer timestamp now).
3) then I deleted DC, reinstall as described and
4) DC shows always "delta-chat-2018-01-14.bak" (the original exported one) to import.

While the two files were at "Downloads", the newer one "delta-chat-2018-01-14b.bak" not has been displayed for import.

Q: What filename is DC searching for import? Is the timestamp relevant?
Maybe this can be documented here and then it's ok for the moment. 

It's not a big issue to delete all unwanted files so that DC only has one to import.
IMHO I would see this issue only for FFE (For Future Expand), not for high priority!

Please defer to future, real bugs are more important  ;-)

**Comment by r10s** [comment]
> Q: What filename is DC searching for import? Is the timestamp relevant?

Delta Chat regards files starting with `delta-chat` and ending with `.bak` as potential backups and tries to open them with the normal open routines. On success, the timestamp from inside the configuration table is read. The newest backup is used then. From the view of the program, The timetamp in the file name is decorative only.

See https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox_imex.c#L1237 for the corresponding source code.

So, if you want to skip a backup, copy it away from the "Downloads" directory or rename it eg. to `delta-chat-...bak.skip`.

**Comment by csb0730** [comment]
Ok so far :-)

This issue really can be attacked later and labeled with "less important or defered" or even closed for now!
