### ISSUE TITLE
"Reply Privately" available in mailing lists

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2430]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.211001.001 from 2022-11-21).

- Delta Chat version:
1.34.5 (latest nightly build).

- Expected behavior:
"Reply Privately" is not available in mailing lists.

- Actual behavior:
"Reply Privately" is available in mailing lists.

- Steps to reproduce the problem:
-- Open a mailing list.
-- Long-tap a received message, then tap the three-dot menu in the header bar. (Result: "Reply Privately" is offered.)

- Screenshots:
N/A.

- Logs:
N/A.

- Credits to:
User "orbifx" from the Delta Chat Community (EN), thanks for reporting! :)

**Comment by Hocuri** [comment]
Quoting @adbenitez (and I agree with him):
> this should not be disabled IMHO, most mailing list I have seen in the wild are not anonymous, and being able to reply in private is useful, currently used in some non-anonymous ML channels to allow a way to have "post comments"

**Comment by gerryfrancis** [comment]
Quoting @r10s:
> there may be mailing lists where you cannot really reply privately. if that is true, it might be better to hide the option.

I don't mind whether it is one way or the other, but I guess we should follow a consistent approach for _all_ DC clients.

**Comment by adbenitez** [comment]
closing this as there is no actionable item, and removing "reply privately" for mailing lists will only further limit the app usage as an email client replacement
