### ISSUE TITLE
Introduce a limit for number of messages in a chat

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#244]
When using DC regularly any user will be faced sooner or later with the problem that some chats gets too big. Manual deletion is very unhandy in some way. Automatic or manual launch of such a function is thinkable.

Introducing
  a) an option for maximal number of messages in a chat would help (FIFO) or
  b) a maximal time range could help too.

Usually a) is the better choice in case of chats with few traffic.
b) has the disadvantage that even with no traffic sooner or later messages are deleted. IMHO this is not good ;)

**Comment by nutpantz** [comment]
Personally I would like to see a clean and clear option for the email account in question.
A sort of delete everything 
if not a emergency delete everything then clear data and cache of the app automatically

**Comment by csb0730** [comment]
Hi nutpantz,
I do not understand your proposals clearly but my intention wasn't a function to delete all messages of a chat. I will explain a litle bit clearer:

A max number of messages in a chat (for example 100 pcs) would mean that when the 101th message for that chat arrives message (1) would be deleted (or archived) automatically. This is a simple FIFO principle.

Another possibility could be to have a function in chat's menu which would allow for example "delete oldest 10 messages". Maybe this is easier to implement in a quick hack ;-)

In reality I'm now facing with this problem because I have one very busy chat which receives many long emails. To delete the oldest mail I need to move to the first message in chat manually (which needs really some time; approx 200 messages in chat!) and delete that. After that DC moves automatically to last message and that game begins from start again! :-(
Extremely unhandy!

That's it.

**Comment by Hocceruser** [comment]
> After that DC moves automatically to newest message at the end and that game begins from the beginning again! :-(

It doesn't happen on my DC installation (v0.9.9), which version of DC do you  use?

Also it is possible to mark and delete multiple messages at once, although you still have to tap on each message which is not very handy, either.

**Comment by csb0730** [comment]
Ok, I have to correct my description:
 After deleting some messages (mark several for one batch, then pressing onto the recycle bin) really the chat stays near deleting position :-)
I think my observations came from a kind of misuse from my side :-/

I didn't realize that it is possible to mark more messages for deleting because in other apps a checkbox for doing that is shown!

I'm using v013.0 now. But I think this behaviour doesn't change?

But in spite of that, deleting message by message is not very handy. Especially for long text messages from which each of them goes over several screens! You have to swap and swap and swap ... , then next .... and so on...

**Comment by testbird** [comment]
This probably is beyond the V1.0 "robust usefullnes" target, but an important "smooth experience" feature.

Still, an idea to add to the automatic archiving proposed in the original post above: Also allow manual deletion in with the same code, by providing an option to "archive all messages up to this one", and an option to delete archived messages, manually, and automatically to limit storage usage https://github.com/deltachat/deltachat-android/issues/227.

**Comment by testbird** [comment]
Just found this: #22

**Comment by csb0730** [comment]
Hi testbird,
 #22 seems to describe the same issue, but why You referenced #227 to this issue?

My intention is only for local device. At server side I do not have a problem because there I can define some rules to delete older messages easily.

But meanwhile to ease message deleting manually @r10s could implement a button in chat to jump to first message? A similar button to jump to last message still exists!

Similar to this:
![screenshot_2018-01-24-mod](https://user-images.githubusercontent.com/30560716/35360828-53981a82-015f-11e8-9b8f-6c5c6de83bc1.png)

**Comment by testbird** [comment]
> why You referenced #227 to this issue?

By mistake when I wheeled through the issues, but it should be straightened out in the priority list I compiled: https://github.com/deltachat/deltachat-android/wiki/Bug-Priorities

**Comment by csb0730** [comment]
Ok ;-)

**Comment by csb0730** [comment]
Overlapping with #22 except of the button I described above.

**Comment by r10s** [comment]
as the button is another issue, i close this in favour to #22 

regarding the button: well, this would more be a workaround to make things easier until there is a automatic delete function. i think we should use our resources for an automatic delete.

and: to go to the first messag you can:
- select "search" from the menu
- do not enter a search term
- click on the up arrow beside the search field
