### ISSUE TITLE
A widget to open talk screen directly

### ISSUE THREAD

**Issue by foxtrotchat** [deltachat/deltachat-android#2448]
- Google phone already have a widget to dial person directly,
- Conversations.im already have one to open chat screen directly
so why not add one??

Widget
- Talk to xyz
  -  (icon should be xyz's icon)

**Comment by gerryfrancis** [comment]
@foxtrotchat Welcome, and thank you for your suggestions on how to improve Delta Chat. This place is all about coding. Feel free to discuss feature proposals in the Delta Chat Community Forum, https://support.delta.chat/c/features/6

Thank you for your understanding, I am closing here.
