### ISSUE TITLE
bug priority groups

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#245]
I devised a method to determine priority groups for issues, based on three sets of lables.
Issues are ranked higher the larger the impact of an issue is on the general user experience (user-impact). 

https://github.com/deltachat/deltachat-android/wiki/Bug-Priorities

If you like the idea, you may already direct your work on the bugs using the manual listings I had compiled before, to try out the priorization.

In the future, the listings could be generated automatically by adding the label combinations of the groups to the general github issue filtering `https://github.com/issues?q=is%3Aissue+is%3Aopen+org%3Adeltachat`:

The "testbird" criteria :

tag | filter
-----|-------
`affects users: in general` |  +label%3A%22affects+users%3A+in+general%22
`affects users: specific config` |  +label%3A%22affects+users%3A+specific+config%22
`affects users: specific provider/hard-/software` | +label%3A%22affects+users%3A+specific+provider/hard-/software%22
--- | ---
`severity 4: not usable` | +label%3A%22severity+4%3A+not+usable%22
`severity 3: deterring disturbance` | +label%3A%22severity+3%3A+deterring+disturbance%22
`severity 2: expected function` | +label%3A%22severity+2%3A+expected+function%22
`severity 1: nuisance` | +label%3A%22severity+1%3A+nuisance%22
`severity 0: feature request` | +label%3A%22severity+0%3A+feature+request%22
--- | ---
`impairs: overall app usage` | +label%3A%22impairs%3A+overall+app+usage%22
`impairs: specific feature` | +label%3A%22impairs%3A+specific+feature%22

Excludes:

tag | filter
-----|-------
`duplicate` | +-label%3Aduplicate
`part of overlapping issue` | +-label%3A%22part+of+overlapping+issue%22

**Comment by testbird** [comment]
It should help to give testers and users the overall positive experience (even within a limited feature set), that is so important for a positive reception, and to avoid unecessarily driving testers and early adopters away.

**Comment by r10s** [comment]
so your suggestion would be to add the corresponding tags to the issues? makes sense, do you like to do this? do you have sufficient rights to do so? otherwise, I would be glad to grant you the missing rights :)

**Comment by testbird** [comment]
If you really agree with the resulting priorities, and if you think it helps you to stay on top of the bugs, I could add them to the existing bugs.

I updated the list of tags above.

If you enable those, I would still need the permissions to add/remove. Maybe it could even work to allow all users to add/remove those basic tags.

**Comment by r10s** [comment]
okay, I think, we can try it this way, however, I would like to have a second opinion on this point, maybe from @Ampli-fier (i'm a little sick these days, caught a cold or sth. like that ... so I feel as if I cannot think as usual ..) (Ampli-fier can also grant you the required rights then)

**Comment by testbird** [comment]
No hurry, as I already compiled the list manually at https://github.com/deltachat/deltachat-android/wiki/Bug-Priorities, let's see how it works out. Hopefully, it allows coders to avoid some of the scrabbling through the bugs. All the best to get well!

**Comment by Ampli-fier** [comment]
Good to have priorities. I have to admit I don't understand the concept yet.

Do you think about establishing "Prority"-Tags? Where the prio is derived from the three criterias above (affect, severity, relevance)?

**Comment by testbird** [comment]
> Do you think about establishing "Prority"-Tags?

To arrive at something like a plan about how to possibly deal with the pile of issues, in an order that tries to reduce the impact bugs have on users, I started to create an outline in the wiki with summarized lists of issues.

At some point I noticed the group Iistings could be automated based tag combinations assigned to the issues, and the summaries may also be created as issues.

The issues in the top priority group (1.1.1) affected users in general, with highest severity (something is considered unusable), and are present in the overall app usage.

Have a look at the header ordering in the wiki (link above). There I experiemented with manually sorting the issues into the outline there (1.1.1 etc.).

**Comment by testbird** [comment]
Sorry, to answer you question: The idea is not to apply priority tags to the issues, but let users select tags from the three categories (affects, severity, relevance), and to use these tags to compile a number of lists (while implying some order between the lists).

**Comment by testbird** [comment]
Wording? Maybe `impairs` is more specific, and better to select by reporters than `relevance`?

**Comment by Ampli-fier** [comment]
That's a cool idea.

I also prefer `impairs` over `relevance`.

Can you check [this test issue](https://github.com/Ampli-fier/deltachat-android/issues), please? Did you have this in mind?

**Comment by testbird** [comment]
Just though of one more label that would be needed: `gets fixed with another issue`
This label could be applied when a summarizing issue is created (e.g. like "refactoring the imap folder/flag handling") that is able to solve a number or reported issues, and would serve to filter out those (redundant) issues from the priority listings.

**Comment by Ampli-fier** [comment]
That sounds like `duplicate` ...

**Comment by testbird** [comment]
`duplicate` sounds, because it usually is, dismissive (already know that..., didn't you search).
What I mean is maybe more `this will be dealt with as part of a summarized in Todolist/Task that allows to tackle a set of issues in a more organized/coherent way than jumping from issue to issue from different reporters`

For example, there a different issues about some messages disappearing, other users getting mailbox cluttered, etc. and they might all be tackled by reworking the IMAP strategy, having the issues in mind but not as the focus point.

**Comment by testbird** [comment]
Idea for the issue tag: `part of overlapping issue` (like reworking the IMAP strategy)

**Comment by testbird** [comment]
I am trying out the "project management board" feature to generate bug listings. You can see it at https://github.com/orgs/deltachat/projects/1

One thing I already noticed is that you added the label `being worked on` to some issues. The project board seems to make marking "issues as being worked on" easier, just by dragging them into the column. (And automatically moving the issues into the "Done" column when the issue gets closed. If you agree I would remove the `being worked on` label, is that ok?

**Comment by r10s** [comment]
yes, you can remove the "being worked on" label, it was rarely used, anyway.

> I am trying out the "project management board" feature to generate bug listings. You can see it at https://github.com/orgs/deltachat/projects/1

Thank for pushing this forward, looks great. I didn't know that this thingie even exist :)

**Comment by testbird** [comment]
Unfortunately, the github project automation does not allow for a custom issue list based on sorted label combinations. It doesn't even support automatically adding newly opened bugs to a project column. That "To do automation" setting only determines the project column to which an issue is added when manually "adding the project to the project list in the right-side menu of an issue". So, the github project workflow seems seriously flawed. It's not at all like I saw it working on gitlab.

So, it is not possible to render a list of the issues sorted by label combinations within github, to have a look at the resulting user-impact ranking of the issues. :(

If someone is fluent in javascript, maybe sorting of lists retrieved through github api queries would be possible, but hacky.

**Comment by r10s** [comment]
i am wondering, if it is possible to get shorter names for the tag, the issue lists looks very noisy to me :) - but i like the color scheme 

Eg. 

    affects users: in general                       -> affects all users
    affects users: specific config                  -> affects some config
    affects users: specific provider/hard-/software -> affects some config
    severity 0: feature request                     -> feature request

And so on. What do you think?

**Comment by r10s** [comment]
regarding shorter labels: there are now label descriptions available that are shown when selecting labels but not directly in the issue list: https://developer.github.com/changes/2018-02-22-label-description-search-preview/ - this would make the decision for shorter labels easier, imho

**Comment by r10s** [comment]
the descriptions are also shown in the issue list in the tooltips:
![bildschirmfoto vom 2018-03-07 11-42-15](https://user-images.githubusercontent.com/9800740/37088196-dc893782-21fc-11e8-9dec-27cf4f709504.png)

**Comment by testbird** [comment]
Yea, the descriptions makes shortening easier. Renaming will requires adjusting the "filter query URLs", so lets find a good complete list before applying changes. What I had in mind is the (alphabetical) sorting of the lables to be reflect the importance given, and to give a hint that the labels are weighted members of their labal groups. Thats why I added the colons like in `group: value`.

**Comment by testbird** [comment]
Overall, I find the labels don't look that good in the issue list, but they look much better on the issue's page as well as on the project cards. Unfortunately the labels in the issue list are not on a new line, or in a separate right column.

**Comment by testbird** [comment]
> Maybe the "affects some config" is also sufficient for some " provider/hard-/software".

My thoughts were that then the provider/hard/software group would be weighted just as much as the deltachat config dependency group. The difference I see is that a config dependency has potentially an impact on more (all DC) users, and can only be solved withing DC. If the issue depends on a specific provider/hard/software, it is a sub-group of DC users, it may be caused by the provider/hard/software, and (temporarily) changing it is a possible workaround.

**Comment by testbird** [comment]
> affects users: in general                       ->  affects all users

There is a subtle difference. For example, not yet having housekeeping auto-archive/delete feature doesn't  really affect all users (each and every), but in general yes. As long as the local and server limits are not reached, I am not affected (but witnessed DC how DC stopped working at chat partner). The idea of the "in general" was to make it easier to give such cases the proper weight.

**Comment by testbird** [comment]
If the grouping is clear from the label text, it may also be an alternative to have a color scheme that shows the importance withing the group, instead of between the groups. (It was just not so easy to get to that with the available color picker.)

**Comment by testbird** [comment]
Applied the other color assignment to test, and I kinda like it...

**Comment by r10s** [comment]
> Overall, I find the labels don't look that good in the issue list, but they look much better on the issue's page

Agree - but the more important place seems to be the issue list.

> If the grouping is clear from the label text, it may also be an alternative to have a color scheme that shows the importance withing the group, instead of between the groups

This is a nice idea. Eg. the current "bug red" for a "bug" (that should stay existent, btw. one should not remove labels added by others) and "severity 4..." fading to very lite red for "severity 0" aka "feature request"

**Comment by testbird** [comment]
> "bug red" for a "bug" (that should stay existent, btw. one should not remove labels added by others) and "severity 4..."

Did I remove a labels? I adapted the `feature request` one into the serverity 0, because I thought it would be redundant.

I didn't use the "bug red" because I considered a bug means something in the current code is wrong and responsible. So it has a specific meaning different from the user-impact.
The user-impact labels I kept of lighter colors, because individually they serve only the the purpose of a rough priority ranking, but three times orange is hopefully still likely to be quite an important issue.

**Comment by r10s** [comment]
No, afaik you have not removed labels :)

Regarding the "bug red": the color was only meant as an example. We can use any other colors, but I would leave red for the bug.

> I considered a bug means something in the current code is wrong and responsible.

Yes, and adding the "bug" label should be done by someone knowing about the code details; just in difference to a label telling that just sth. does not work. 

However, I fear a little bit that we should not add too many knowledge into the labels; or at least, _reading_ them should work without reading manuals :)

**Comment by testbird** [comment]
The orange / yellow "user-impact" labels should usually not need to be read in full.

The intention was to just have a sorted list rendered that ranks the issues for which fixing would have the largest user-impact.

It's only unfortunate that github does not support sorting by label combinations, but the "darkness count" seems to work already.

**Comment by r10s** [comment]
@testbird Okay, after working some days with the new labels, I unfortunately have to say that they do not work for me. 

- My first place to work on Delta Chat is the normal issue list, and this is far too noisy now. Same for the issues themselves, I think the issues are mainly a conversation and not database records that should be tagged properly.
- Also it is hard to say, which severity or impact a special issue has. Some issues tagged the last days, would have been tagged in another way by me. But I do not want to discuss about which tag is appropriate but more on the issue itself.
- For the author of an issue, _his_ issue my be the more important than from the developers view who has to handle with limited resources. A discussion about tags again uses some of these limited resources.
- I also fear that this complex system in the issue list discourages users from contributing. I would prefer to keep things _far_ more simple for the issue lists. I am a little sensible on this point; on a previous project the meta data stuff gets so complex that it gets close unusable. I do not want this for Delta Chat.

So I would really like to switch to the old, more _organic_ scheme, where tags are added and created as needed. And are much shorter. 

This is also the way most other repositories seem to work, i think it is a good idea to do thinks here users are familiar with.

I am sorry, that I could not foresee all this earlier. _And please do not understand me wrong, I appreciate your work on the issues, your comments are really helpful and push things toward to the right direction._ 

Suggestion: If I have understood _projects_ correctly - isn't this a perfect place for such lists and overviews? Eg. having a project "Most disturbing issues" and file all issues there may work better. 

This way, we can give the issue tags and the milestones back to the developers :)

**Comment by r10s** [comment]
@testbird regarding your "owner" membership - I do not have an email address from you, can you please mail me at r10s at b44t dot com

**Comment by testbird** [comment]
I'll have to get back later, just want to say that the reason for github issues fading into conversations is the lack of an alternative (traditionally a mailing list). And please note that the issues are not necessarily *my* issues. 

Reading the issues I noticed too much duplicate reports and too many reporters that left deltachat behind again. So I thought about a way to make that less likely to happen. I know that when oneself is developing something, one naturally gets the coder point of view on things, and the impact an issue has on coding differs of course from the impact on the users. I thought about how to assess the user-impact in a operationalized way. I am sure I have tagged some issues not with the  appropriate user-impact labels, as I could only do it as a third person and as best as I could understand the issue. We don't have established practices yet. Personally, I'd prefer to choose issues to work on based on an issue list that is categorized and consolidated, over working with a raw issue submission log.

(got longer than intended) Let's see if we find a way that doesn't disturb the issue log.

**Comment by r10s** [comment]
> And please note that the issues are not necessarily my issues.

of course :)

> Personally, I'd prefer to choose issues to work on based on an issue list that is categorized and consolidated, over working with a raw issue submission log.

Okay, that is the opposite from what I prefer. So you will go mainly over the [wiki links](https://github.com/deltachat/deltachat-android/wiki/Bug-Priorities)?  I prefer the [raw list, possibly sorted by date](https://github.com/deltachat/deltachat-core/issues?utf8=%E2%9C%93&q=is%3Aissue%20sort%3Aupdated-desc).

> (got longer than intended)

:)

> Let's see if we find a way that doesn't disturb the issue log.

Looking forward this, I could imaging eg. a project with cards reflecting eg. the priorities and another one relecting different impacts an so on. IIUC one can drag the issues from hand (instead of adding the tags to the issues, so this shouldn't be more work).

We can link to these lists from a prominent place then, no problem. I think this is better than a list of links with filters in the wiki.

**Comment by testbird** [comment]
@r10s: You may look for a ping in your contact requests.

**Comment by testbird** [comment]
> So you will go mainly over the wiki links? 
Not really, no, that's a kludge.  I'd like a nicely sorted list, and as it is already sorted the user-impact tags don't need to be shown either in the resulting bug ranking list. But I expect having some (sub) headings in between the list items could provide good orientation when navigating this list.


>> Let's see if we find a way that doesn't disturb the issue log.

> Looking forward this

A clean looking but local hacky way I found is to have the browser apply the following css (tested with firefox webdeveloper tool).
```
a[title^="affects"] { display: none; }
a[title^="severity"] { display: none; }
a[title^="impairs"] { display: none; }
```
But I would first try other or even stealth colors and descriptions for possibly almost "empty" labels.

> I could imaging eg. a project with cards reflecting eg. the priorities and another one relecting different impacts an so on. IIUC one can drag the issues from hand (instead of adding the tags to the issues, so this shouldn't be more work).

The nice thing about the tree tag groups is that they only require to select answers to three questions (affects, severity, impact) which is easier than having to sort the issues manually.

**Comment by r10s** [comment]
> IMHO this project doesn't benefit from issue automation. The amount of issues written isn't big enough yet.

This is exactly my feeling :)
