### ISSUE TITLE
Let user to change contact's name manually

### ISSUE THREAD

**Issue by foxtrotchat** [deltachat/deltachat-android#2450]
because deltachat always revert to email address when the recepient does not use deltachat.

**Comment by gerryfrancis** [comment]
@foxtrotchat Thank you for your report! I just did as you described, but the (manually applied) contact name in my Delta Chat client does not change when I receive an email composed with a different email app from that contact.

Please fill in our template and name the version of Delta Chat you are currently using, as well as the steps on how to reproduce the issue. Thank you!

**Comment by r10s** [comment]
we would need more information if there is a bug, in general, it is possible to change the contact's name.

please reopen with additional information.
