### ISSUE TITLE
Stop sending avatar icon every single time when the both side already shared each other's icon

### ISSUE THREAD

**Issue by foxtrotchat** [deltachat/deltachat-android#2451]
to save internet data usage.

**Comment by gerryfrancis** [comment]
@foxtrotchat Thank you for your report! Avatar images are not sent with every single message, I have just tested that: I sent a message immediately after I changed my avatar image. The recipient did not receive my recently changed avatar image.

Please fill in our template and name the version of Delta Chat you are currently using, as well as the steps on how to reproduce the issue. Thank you!

**Comment by gerryfrancis** [comment]
> This sounds like a real bug, I would expect that the timer is reset when avatar is changed :)

@link2xt I did the test with my two email accounts using the very same Delta Chat client, does that matter?

**Comment by gerryfrancis** [comment]
@link2xt I have tested the latest nightly build, now the new avatar is received and displayed in the recipient's Delta Chat client immediately, thank you very much! :)

@foxtrotchat We still need further information from you about your originally reported issue. Please submit, thank you!

**Comment by adbenitez** [comment]
@foxtrotchat the avatar is not sent in every single message, please provide more info and logs or some prove that for you avatar is being sent in every single message, so we have some more concrete issue to fix, closing the issue until you come back with more feedback that allows us to take action
