### ISSUE TITLE
"force(-once) (un)encrypted" to directly reach a classic MUA, after having had a chat

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#246]
A known chat contact uninstalled deltachat because the "empty" chat messages and return receipts in his MUA inbox annoyed him (his email provider only supports folders below the inbox). (EDIT: That issue causing this has been fixed in the meantime.)

Now I can not reach this contact anymore, because the last message received was encrypted from his former deltachat installation.

Some ways to control the encryption are needed. For example, it is also needed to allow reaching a known contact, and him to answer with a normal MUA, for example, once he gets into the office, after he left the phone with deltachat at home.

* Force-once-unencrypted in Chat menu  (when autocrypt is on, as if an unencrypted message had been received)
* Force-once-encrypted in Chat menu (when autocrypt is off, as if an encrypted message has been received)
* always-encrypt in contact properties
* never-encrypt in contact properties

**Comment by csb0730** [comment]
You're right. This is comparable to the opposite (send encrypted if You want to and key exists).

There should be a manual choice what to do if desired. This could be implemented as an option in a chat's setting:

- force encrpyted send
- automatic (standard)
- force unencrypted send

**Comment by testbird** [comment]
Good idea, force and force-once sounds better.

**Comment by testbird** [comment]
But how to implement this in the UI? Long press on the send button may be "dangerous". Maybe, long press on the lock symbol in the message to write?

**Comment by testbird** [comment]
Drop-down menu for the lock symbol?

**Comment by csb0730** [comment]
As this should be an exceptional use case there could be a (some) option(s) in a chat's menu?

**Comment by r10s** [comment]
i think a "long click" on the send button would be fine. unfortunately, there is not only _one_ send button in Delta Chat currently, so there is much more cleaning up and ui rewriting required. I do not think we will get there _fast_.

**Comment by csb0730** [comment]
I know only the send button beside the text input field. Are there more?

**Comment by r10s** [comment]
> I know only the send button beside the text input field in chat view. Are there more?

yes. sending is also done eg. by
- when selecting several images the "close" in the lower right corner turns into a send button
- when clicking on a single image, there is a button names "send"
- same for videos
- voice messages are send when the record button is released

the behavior comes from telegram. the best would be to rewrite all this to let the user select what to send first and having a single send-button then. this can be long clicked to force encrypted/unencrypted then.

**Comment by angelo-fuchs** [comment]
This proposal has been moved to https://support.delta.chat/t/force-once-un-encrypted-to-directly-reach-a-classic-mua-after-having-had-a-chat/227 as we strife to have all feature proposals in one place.
@testbird @csb0730 Please do put your contributions to the forum.
