### ISSUE TITLE
Delta Chat + Email client

### ISSUE THREAD

**Issue by kskarthik** [deltachat/deltachat-android#247]
Delta chat clearly is an exciting idea of IM with email. But, Android lacks a decent open source mail app with built-in encryption , user friendly encrypted email app. 

The default aosp mail app seems to be silently (intentionally?) abandoned by google. K9 is great but, not so beginner user friendly. PEP is also based on K9.

So, My request to delta chat is serve both as email client along with IM functionality. 

Curious to hear your thoughts on this guys! 

poke @r10s

**Comment by r10s** [comment]
Thank you for your post.

Currently, there are no ideas in the direction of making Delta Chat a "normal" email client. I think, K-9 is way to go for pgp-encrypted mails on Android and I think it is easier to solve the usability issues in K-9 than starting from scratch with Delta.
