### ISSUE TITLE
Voice message player UX issues with screen readers

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#2470]
from https://support.delta.chat/t/compact-media-view/2433

Dear developers
Could you implement an alternative, i.e. more compact, media view like Telegram s?
The fact is that, for example, the appearance of the voice message interface that we have in Delta Chat is not very convenient for blind users.
Below is a small comparison:

1.    Telegram. A voice message only has one line on the screen (of course, this is from the point of view of TalkBack and Jieshuo screen readers). When I focus on a voice message, the screen reader tells me it s a voice message. Also announces its duration, tells when it was sent or received, and says the word Slider.
    If I double tap on a voice message it starts playing. I can also control the playback time slider using the appropriate screen reader gestures (just like in the Delta Chat interface).
2.    Delta Chat, Signal, and if I m not mistaken, Element.
    Each voice message takes up a lot of screen space. Separately - playback button, separately - playback time slider, separately - message information.
    I understand that my comparison can be confusing, but if you try to interact with Telegram and with Delta Chat using the screen reader TalkBack or Jiesuo, you will understand everything.
    I will be very grateful for your attention to my request. Let me know if testing is needed.

**Comment by gerryfrancis** [comment]
> Delta Chat, Signal, and if I m not mistaken, Element.
> Each voice message takes up a lot of screen space. Separately - playback button, separately - playback time slider, separately - message information.

![grafik](https://user-images.githubusercontent.com/51095533/217553192-4b7ddeca-bd64-44b4-9685-0b8e24d755ed.png)

This is how the audio player looks in Delta Chat for Android.

**Comment by bmivzkrp** [comment]
@gerryfrancis I thought about uploading screenshots, but then gave up on that idea. I am completely blind, so I rely entirely on screen readers. So I describe the user experience as it is presented to me by the screen reader.

**Comment by gerryfrancis** [comment]
@bmivzkrp I understand, therefore I will try to describe the image as good as possible, but I am no English native speaker, so please forgive me if I do it wrong: Inside the bubble there is one button that combines play and pause, the symbol on it depends on whether playback is in action or paused. Next to the right of that button within the bubble, there is a slider that you can move within a horizontal line, and below that line is the audio position counter that tells you a) the duration of the audio (mm:ss), and the time position when paused.

I hope that description represents the audio function in Delta Chat. Feel free to ask questions if you would like to know more, we are always glad to help! :)

**Comment by bmivzkrp** [comment]
@gerryfrancis
I am also not a native English speaker, my native language is Ukrainian.
I have no questions regarding the use of voice messages. The problem is 
that it is inconvenient for a blind user to navigate between voice 
messages because each voice message takes up a lot of screen space. That 
is, the transition from one voice message to another takes some time. 
For example - a few seconds. According to conventional standards of the 
user experience of a blind person - it s pretty slow.
You can do it faster in Telegram.
The current state of things isn t bad enough to abandon Delta Chat, but 
I wish the developers would adopt the Telegram experience.

**Comment by adbenitez** [comment]
while testing this I also had a crash in the chatlist using talkback:

```
10-01 22:54:34.453 17743 17743 E AndroidRuntime: java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable                                                                                                                            
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.widget.TextView.setAccessibilitySelection(TextView.java:10171)                                                                                                                                             
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.view.View.traverseAtGranularity(View.java:9054)                                                                                                                                                            
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.view.View.performAccessibilityActionInternal(View.java:8984)                                                                                                                                               
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.widget.TextView.performAccessibilityActionInternal(TextView.java:9340)                                                                                                                                     
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.view.View.performAccessibilityAction(View.java:8895)                                                                                                                                                       
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:668)                                                                                    
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:54)                                                                                                             
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1194)                                                                                         
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                                                                                               
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)                                                                                                                                                                            
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5551)                                                                                                                                                          
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                                                     
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)                                             
10-01 22:54:34.453 17743 17743 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624) 
```
