### ISSUE TITLE
Need SplashScreen

### ISSUE THREAD

**Issue by MadTooth** [deltachat/deltachat-android#2492]
`Can you add SplashScreen ?`

_For example with the DeltaChat logo with a dark background, or change the "SplashScreen" color to dark if the user is using a dark theme_

**Every launch of "this" app is a disgusting white light in my eyes.**

**Comment by r10s** [comment]
> Every launch of "this" app is a disgusting white light in my eyes.

so, the issue is, that, you are using dark mode - and when starting delta chat, for a short moment, a full white screen flashes up?

if so, we should fix that, but i do not see the reason for a splash screen still (in general, "splash screens with a logo" are mostly discouraged nowadays)

**Comment by gerryfrancis** [comment]
A splashscreen with a logo might be useful for old Android devices running newer ROMs, e.g. Lineage OS, due to their bigger overhead that delays almost every I/O operation, while newer and more powerful devices would not need a splashscreen. Just my two cents.

**Comment by r10s** [comment]
splash screens _with logos_ are mostly ugly, adding unneeded noise and flickering in the vast majority of cases - we have that currently on ios, and it is not nice.

this chances, if one thinks of a splash screen that has some basic view that closely resemble the first screen of the app.  launching the app just feel much faster with that, and there won't be flickering and noise - this is also what is recommended for ios: https://developer.apple.com/design/human-interface-guidelines/patterns/launching/#launch-screens

however, on ios, this only works as there splash screen is loaded _before_ the app's code is even loaded - similar to an icon - not sure if that is doable on android. maybe one can at least use a different color as white, however.

just adding a splash screen at the moment where we have the first chance programmatically would not help - as we could also do render the chatlist title and other elements already.

but i also just checked out my old Nexus S - starting takes some seconds, sure, but that is honestly also true for all other apps - and all show the white backround there.

if we can make that nicer with few effort, i would be up for that, but all in all, i consider this a very minor issue or feature request.

**Comment by MadTooth** [comment]
@r10s

**Just change the "splashscreen" color to be dark by default, or just for dark mode, or is it that hard to do ?

Do it for the people, it's important**

**Comment by r10s** [comment]
> Just change the "splashscreen" color to be dark by default, or just for dark mode, or is it that hard to do ?

i don't know :)

checking apps on older phones, i regularly see a white screen on startup, btw. the places where colors are defined, come in to play much too late, after the app is actually loaded and start execution.

there is https://developer.android.com/develop/ui/views/launch/splash-screen - that seems to be similar to what is mentioned above for ios, however, is a relatively new api.

but there may also be an entry in the manifest or so that works for older phones.

which android version are you using on which device? do you have examples of open source apps that behave differently - maybe we can peek at the code there.

**Comment by MadTooth** [comment]
@r10s

> «which android version are you using on which device? do you have examples of open source apps that behave differently - maybe we can peek at the code there.»

![CPU-Z v1 42  My Device Info](https://user-images.githubusercontent.com/30464341/223430961-f1ee8a55-a46b-45a2-873c-1a1f3fde20c5.png)

https://github.com/wrmndfzzy/Atomize
https://github.com/crackededed/Xtra

**Comment by MadTooth** [comment]
@r10s

Addition: for Dark theme

In "Show_Full_Message..." display, invert colors

> [Dark Theme = Dark Color's]

![Show_Full_Message](https://user-images.githubusercontent.com/30464341/224021941-cd51185d-ff1e-43c9-9f7f-925aed0794b1.png)
![Show_Full_Message](https://user-images.githubusercontent.com/30464341/224021846-4fe91c47-d006-4015-9d98-1ea2f494228f.png)

**Comment by gerryfrancis** [comment]
> Addition: for Dark theme
> 
> In "Show_Full_Message..." display, invert colors

@MadTooth Please open a new issue for dark theme troubles in full message view, so we can keep focused on the splashscreen here, thank you.
