### ISSUE TITLE
wrong hints in "All Media" activity

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2498]
the hints for empty tabs in the "All Media" activity added at #2489 do not for the new case:

<img width="320" alt="Screenshot 2023-03-14 at 11 39 01" src="https://user-images.githubusercontent.com/9800740/224976793-4875ce9a-5972-421a-90fc-41610fb117a8.png">

using a neutral wording would make things less user friendly, i'd say, so i think we should either 
(1) add new strings for all cases or 
(2) only one string fitting all of the new cases as "Media shared in any chat will appear here." - this also picks up the wording of the title, so maybe good enough

cc @adbenitez

**Comment by adbenitez** [comment]
mmh somehow this issue didn't close automatically, but it was fixed in #2499 IIRC, right? closing, reopen if I missed something

**Comment by r10s** [comment]
there was a `closes #1234` missing the pr - thanks for gardening 👩‍🌾
