### ISSUE TITLE
IOS gmail app mails with images do not get decoded properly

### ISSUE THREAD

**Issue by wenzler** [deltachat/deltachat-android#252]
_Please read the guidelines linked above, especially when you are a first time contributor. Remove this text and provide some basic informations below, if applicable. Remove template content that is not applicable._

**Delta Chat version**
0.99

See settings dialog …

**Expected behavior**
Display inline images in multipart messages

What is the expected output?

**Actual behavior**
Does only show the image just the text

What do you see instead?

**Steps to reproduce the problem**

1. Send email with text and image from IOS gmail app to delta chat account…
2. Email contains multipart content:
--f403045fc07c70e38005657b2111
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

--f403045fc07c70e38005657b2111--
--f403045fc07c70e38305657b2112
Content-Type: image/jpeg; name="image_123923953.JPG"
Content-Disposition: inline; filename="image_123923953.JPG"
Content-Transfer-Encoding: base64
Content-ID: <161a8b84fa9c7597e591>
X-Attachment-Id: 161a8b84fa9c7597e591
…
This is omitted

Also quotes often get displayed from gmail app
This should be improved overall as being a common email client.

**Screen snapshots**

If applicable …

**Debug logs**

If applicable, debug logs can be copied from within the Delta Chat app: 

Open the _Settings_ menu -> _About_ -> _version number|Info_.

Alternatively from the Android system log:

` adb logcat -v time -s DeltaChat `

This log contains private data (e.g. mail address, provider information) which shall be removed or anonymised prior to posting.

Thanks!

**Comment by wenzler** [comment]
Also tried with no additional text - image does not show up either - so its probably about that html mails sent with inline image attachments...

**Comment by csb0730** [comment]
This issue described here should be the same or very similar to https://github.com/deltachat/deltachat-core/issues/91.

Even https://github.com/deltachat/deltachat-core/issues/90 is similar to that.

In general: There are some leaks in decoding interleaced or nested mail components or attachments.

**Comment by r10s** [comment]
@wenzler thank you very much for the detailed information, this will be very helpful in finding out the problem

@csb0730 thank you for the issue overview, this issue is closed then; the information, however, are referenced by the other issues and stay helpful
