### ISSUE TITLE
Push notifications does not work under some conditions

### ISSUE THREAD

**Issue by anedroid** [deltachat/deltachat-android#2527]
I personally don't experience this issue, but my friend I'm chatting with do. I disabled battery optimization, allowed work in background, made sure notifications are enabled, none of these helped. When I send her a messege, she don't get a notification until she open the app, which is not very useful. This applies to the iOS version as well. I have a little knowledge about how email push notifications works, may it be that some servers support this feature and some don't? I use disroot.org (where everything works fine) and my friend use wp.pl, but we also have different phone manufacturers. Details below.

**My setup (working)**:
- Android version: 12 (custom ROM LineageOS)
- Device: Moto g7 Power
- Delta Chat version: 1.34.13 F-Droid
- Email server: disroot.org

**My friend's setup**:
- Android version: probably 10
- Device: Realme, iPhone
- Delta Chat version: 1.34.13 F-Droid, latest from App Store
- Email server: wp.pl

**Comment by Hocuri** [comment]
Does this help? https://dontkillmyapp.com/realme

**Comment by AndreaLattmann** [comment]
I also advise you to see on https://dontkillmyapp.com/realme there are smartphones that require a few more steps then you have DC which works perfectly

**Comment by Hocuri** [comment]
Since @anedroid didn't answer anymore, I'm going to close this issue for now.

**Comment by Hocuri** [comment]
To be clear, devices that kill Delta Chat while it's trying to receive notifications in the background is a constantly re-appearing problem, but it seems there is nothing we can do to improve this.
