### ISSUE TITLE
Swipe down on notification to expand it

### ISSUE THREAD

**Issue by new-on-github** [deltachat/deltachat-android#2529]
If this is intended and therefore no bug, I am sorry to post there and not in the forum.

- Android version: 13
- Delta Chat version: 1.34.13
- Expected behavior: If there is a new message, it is shown as notification. Now swipe down from the notification and it should expand to see a lot more of the message (this seems to bee normal in other messengers, for example "element")
- Actual behavior: Now nothing happens. There are the sender and the first few words only.
- Steps to reproduce the problem: Get a new message in the background and than swipe down the notification
- Screenshots:

![2023-04-01_12-43 resized](https://user-images.githubusercontent.com/30312140/229284561-9f949a52-0c01-407f-8f3c-cb7e0425ec2d.png) ![2023-04-01_12-45 resized](https://user-images.githubusercontent.com/30312140/229284563-7795634d-19a1-4ee9-a599-241642c6570f.png)

btw: Thanks for this amazing messenger!

**Comment by Hocuri** [comment]
Yes, would be nice to implement this, probably by looking at how Signal is doing it.

**Comment by adbenitez** [comment]
moved to forum: https://support.delta.chat/t/swipe-down-on-notification-to-expand-it/2742
