### ISSUE TITLE
BackupProviderFragment may unref backup provider while it is still used

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2531]
Here, in `onDestroyView`, dcBackupProvider is destroyed:
https://github.com/deltachat/deltachat-android/blob/dfd8f92068db389529164010fbfea26027a8e674/src/org/thoughtcrime/securesms/qr/BackupProviderFragment.java#L107

However, it may still be used in a thread spawned above at https://github.com/deltachat/deltachat-android/blob/dfd8f92068db389529164010fbfea26027a8e674/src/org/thoughtcrime/securesms/qr/BackupProviderFragment.java#L66-L96

All started threads should be joined before calling `unref()`.

This bug leads to crash reported in https://github.com/deltachat/deltachat-core-rust/issues/4179#issuecomment-1485138810

This bugreport is a follow-up to the discussion in https://github.com/deltachat/deltachat-core-rust/pull/4244

**Comment by r10s** [comment]
hm, `DcBackupProvider.unref()` sets the internal c-pointer to `null` and leaves the outer java object valid. i would expect subsequent calls then only lead to "ignoring careless call" messages. the moment between `unrefBackupProviderCPtr` and `backupProviderCPtr = 0;` is critical, but probably not the reason for the crash.

maybe i have overseen sth :)

and yes, i agree that a proper `join()` on the thread is nicer.
