### ISSUE TITLE
Delta Chat crashes / Delta Chat stürzt ab

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#254]
0.15.0
Translated with deepl.com:
I want Delta Chat on standby.

Delta chat is crashing. This has occurred several times today (28.02.2018). Also a restart of the mobile phone did not bring success.
![delta_chat-absturz_img-20180228-wa0002](https://user-images.githubusercontent.com/36864290/36802227-aefa1cca-1cb4-11e8-888b-408be30a6052.jpg)
Message:"Delta Chat does not respond. Would you like to close the app?"

It occurs by itself.
--------------------------------------------
Originaltext:
Delta Chat soll in Bereitschaft sein.

Delta Chat stürzt ab. Dies ist heute (28.02.2018) mehrmals aufgetreten. Auch ein Neustart des Handys brachte keinen Erfolg.

Meldung: "Delta Chat reagiert nicht. Möchten Sie die App schließen?"

Es tritt von selbst auf.

© 2017, 2018 Delta Chat contributors

Chats: 3
Chat messages: 107
Messages in mailbox: 33
Contacts: 86
Database=/data/data/com.b44t.messenger.beta/files/messenger.db, dbversion=18, Blobdir=/data/data/com.b44t.messenger.beta/files/messenger.db-blobs

displayname=NePi
configured=1
config0=***@gmx.net 0:***:0:0 0:0:0:0 0
config1=***@gmx.net ***@gmx.net:***:imap.gmx.net:993 ***@gmx.net:***:mail.gmx.net:465 AUTH_NORMAL IMAP_SSL SMTP_SSL
mdns_enabled=1
e2ee_enabled=1
E2EE_DEFAULT_ENABLED=1
Private keys=1, public keys=2, fingerprint=
 

Using Delta Chat Core v0.15.0, SQLite 3.19.3-ts1, libEtPan 1.7, OpenSSL 1.0.1t. Compiled Feb 27 2018, 12:09:05 for 32 bit usage.

Log excerpt:

16:36:14 T2: Attaching C-thread to Java VM...
16:36:14 T2: Attaching ok.
16:36:14 T2: Job thread entered.
16:36:14 T2: Job thread waiting for signal...
16:36:14 T1: Opened "/data/data/com.b44t.messenger.beta/files/messenger.db" successfully.
16:36:14 T1: Signal job thread to wake up...
16:36:14 T2: Job thread checks for pending jobs...
16:36:14 T2: Executing job #3, action 900...
16:36:14 T2: Connecting to IMAP-server "imap.gmx.net:993" via SSL...
16:36:15 T2: Connection to IMAP-server ok.
16:36:15 T2: Login to IMAP-server as "***@gmx.net"...
16:36:15 T2: IMAP-Login ok.
16:36:15 T2: IMAP-Capabilities: IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN
16:36:15 T2: Starting IMAP-watch-thread...
16:36:15 T3: Attaching C-thread to Java VM...
16:36:15 T3: Attaching ok.
16:36:15 T3: IMAP-heartbeat-thread started.
16:36:15 T4: Attaching C-thread to Java VM...
16:36:15 T4: Attaching ok.
16:36:15 T4: IMAP-watch-thread started.
16:36:15 T4: Fetching from all folders.
16:36:15 T2: Job #3 done and deleted from database
16:36:15 T2: Executing job #2, action 700...
16:36:15 T4: Receive message #158 from Chats.
16:36:17 T4: Message already in DB.
16:36:18 T4: Receive message #159 from Chats.
16:36:19 T2: Appending message to IMAP-server...
16:36:22 T4: Message already in DB.
16:36:22 T4: 2 mails read from "Chats" with 0 errors.
16:36:22 T4: Folder "Entwürfe" ignored.
16:36:31 T2: Message appended to "Chats".
16:36:31 T2: Job #2 done and deleted from database
16:36:31 T2: Job thread waiting for signal...
16:36:31 T4: 0 mails read from "Erdgas" with 0 errors.
16:36:31 T4: Folder "Gelöscht" ignored.
16:36:31 T4: 0 mails read from "Gel&APY-scht/interessante Forenthemen" with 0 errors.
16:36:31 T4: 0 mails read from "Gesendet" with 0 errors.
16:36:31 T4: 0 mails read from "Gmx-rechnungen" with 0 errors.
16:36:31 T4: Receive message #18301 from INBOX.
16:36:31 T4: Signal job thread to wake up...
16:36:31 T2: Job thread checks for pending jobs...
16:36:32 T2: Executing job #1, action 102...
16:36:32 T2: Marking message INBOX/18301 as seen...
16:36:32 T2: Message marked as seen.
16:36:32 T2: Moving message INBOX/18301 to Chats...
16:36:32 T2: Message moved.
16:36:32 T4: 1 mails read from "INBOX" with 0 errors.
16:36:32 T2: Job #1 done and deleted from database
16:36:32 T2: Job thread waiting for signal...
16:36:32 T4: 0 mails read from "INBOX/Aktien" with 0 errors.
16:36:32 T4: Init lastseenuid and attach it to UIDVALIDITY for folder "INBOX/Reklamationen".
16:36:32 T4: Folder "INBOX/Reklamationen" is empty.
16:36:32 T4: 0 mails read from "INBOX/Reklamationen" with 0 errors.
16:36:32 T4: 0 mails read from "INBOX/Versicherung" with 0 errors.
16:36:32 T4: 0 mails read from "K&AOQ-ufe" with 0 errors.
16:36:32 T4: 0 mails read from "K&AOQ-ufe/Ebay" with 0 errors.
16:36:32 T4: 0 mails read from "K&AOQ-ufe/Ebay/2011" with 0 errors.
16:36:32 T4: 0 mails read from "K&AOQ-ufe/Ebay/2012" with 0 errors.
16:36:32 T4: 0 mails read from "K&AOQ-ufe/Ebay/2013" with 0 errors.
16:36:32 T4: 0 mails read from "K&AOQ-ufe/Vertr&AOQ-ge" with 0 errors.
16:36:32 T4: 0 mails read from "Lustiges" with 0 errors.
16:36:32 T4: 0 mails read from "Maillisten" with 0 errors.
16:36:32 T4: 0 mails read from "Maillisten/btrfs-Mailingliste" with 0 errors.
16:36:32 T4: 0 mails read from "Maillisten/networkmanager" with 0 errors.
16:36:32 T4: 0 mails read from "Newsletter" with 0 errors.
16:36:32 T4: Init lastseenuid and attach it to UIDVALIDITY for folder "OUTBOX".
16:36:32 T4: Folder "OUTBOX" is empty.
16:36:32 T4: 0 mails read from "OUTBOX" with 0 errors.
16:36:32 T4: 0 mails read from "Software" with 0 errors.
16:36:32 T4: Folder "Spamverdacht" ignored.
16:36:33 T4: 0 mails read from "TLZ" with 0 errors.
16:36:33 T4: 0 mails read from "Uhrenhandy" with 0 errors.
16:36:33 T4: IDLE start...
16:43:12 T4: IDLE has data.
16:43:12 T4: Receive message #18302 from INBOX.
16:43:14 T4: Message sent by another messenger (will be moved to Chats-folder).
16:43:14 T4: Message has 1 parts and is moved to chat #10.
16:43:14 T4: 1 mails read from "INBOX" with 0 errors.
16:43:14 T4: IDLE start...
16:43:21 T1: Seen message #244.
16:43:21 T1: Signal job thread to wake up...
16:43:21 T2: Job thread checks for pending jobs...
16:43:21 T2: Executing job #1, action 110...
16:43:21 T2: Interrupting IDLE...
16:43:21 T4: IDLE interrupted.
16:43:21 T2: Marking message INBOX/18302 as seen...
16:43:21 T2: Message marked as seen.
16:43:21 T2: $MDNSent just set and MDN will be sent.
16:43:21 T2: Moving message INBOX/18302 to Chats...
16:43:21 T2: Message moved.
16:43:23 T2: Signal job thread to wake up...
16:43:23 T2: Job #1 done and deleted from database
16:43:23 T2: Executing job #2, action 105...
16:43:23 T2: Connecting to SMTP-server "mail.gmx.net:465" via SSL...
16:43:23 T4: IDLE start...
16:43:23 T2: Connection to SMTP-server ok.
16:43:23 T2: Login to SMTP-server as "***@gmx.net"...
16:43:24 T2: SMTP-Login ok.
16:43:24 T2: Job #2 done and deleted from database
16:43:24 T2: Job thread waiting for signal...
16:43:24 T2: Job thread checks for pending jobs...
16:43:24 T2: Job thread waiting for signal...
17:06:27 T4: IDLE has data.
17:06:27 T4: IMAP stream lost; we'll reconnect soon.
17:06:27 T4: Disconnecting...
17:06:27 T4: Disconnect done.
17:06:27 T4: Connecting to IMAP-server "imap.gmx.net:993" via SSL...
17:06:27 T4: Connection to IMAP-server ok.
17:06:27 T4: Login to IMAP-server as "***@gmx.net"...
17:06:27 T4: IMAP-Login ok.
17:06:27 T4: Fetching from all folders.
17:06:29 T4: Receive message #160 from Chats.
17:07:32 T4: Message already in DB.
17:07:33 T4: Receive message #161 from Chats.
17:07:33 T4: Signal job thread to wake up...
17:07:33 T2: Job thread checks for pending jobs...
17:07:33 T2: Executing job #1, action 102...
17:07:33 T2: Marking message Chats/161 as seen...
17:07:33 T4: Receive message #162 from Chats.
17:07:33 T2: Message marked as seen.
17:07:33 T2: Message Chats/161 is already in Chats...
17:07:33 T2: Job #1 done and deleted from database
17:07:33 T2: Job thread waiting for signal...
17:07:34 T4: Message already in DB.
17:07:34 T4: 3 mails read from "Chats" with 0 errors.
17:07:34 T4: Folder "Entwürfe" ignored.
17:07:35 T4: 0 mails read from "Erdgas" with 0 errors.
17:07:35 T4: Folder "Gelöscht" ignored.
17:07:35 T4: 0 mails read from "Gel&APY-scht/interessante Forenthemen" with 0 errors.
17:07:35 T4: 0 mails read from "Gesendet" with 0 errors.
17:07:35 T4: 0 mails read from "Gmx-rechnungen" with 0 errors.
17:07:35 T4: Receive message #18298 from INBOX.
17:07:35 T4: Message belongs to a mailing list and is ignored.
17:07:35 T4: Message already in DB.
17:07:35 T4: 1 mails read from "INBOX" with 0 errors.
17:07:35 T4: 0 mails read from "INBOX/Aktien" with 0 errors.
17:07:35 T4: Init lastseenuid and attach it to UIDVALIDITY for folder "INBOX/Reklamationen".
17:07:35 T4: Folder "INBOX/Reklamationen" is empty.
17:07:35 T4: 0 mails read from "INBOX/Reklamationen" with 0 errors.
17:07:35 T4: 0 mails read from "INBOX/Versicherung" with 0 errors.
17:07:35 T4: 0 mails read from "K&AOQ-ufe" with 0 errors.
17:07:35 T4: 0 mails read from "K&AOQ-ufe/Ebay" with 0 errors.
17:07:35 T4: 0 mails read from "K&AOQ-ufe/Ebay/2011" with 0 errors.
17:07:35 T4: 0 mails read from "K&AOQ-ufe/Ebay/2012" with 0 errors.
17:07:35 T4: 0 mails read from "K&AOQ-ufe/Ebay/2013" with 0 errors.
17:07:35 T4: 0 mails read from "K&AOQ-ufe/Vertr&AOQ-ge" with 0 errors.
17:07:35 T4: 0 mails read from "Lustiges" with 0 errors.
17:07:36 T4: 0 mails read from "Maillisten" with 0 errors.
17:07:36 T4: Receive message #28549 from Maillisten/btrfs-Mailingliste.
17:07:36 T4: Message belongs to a mailing list and is ignored.
17:07:36 T4: Message has 1 parts and is moved to chat #3.
17:07:36 T4: Receive message #28550 from Maillisten/btrfs-Mailingliste.
17:07:36 T4: Message belongs to a mailing list and is ignored.
17:07:36 T4: Message has 1 parts and is moved to chat #3.
17:07:36 T4: Receive message #28551 from Maillisten/btrfs-Mailingliste.
17:07:36 T4: Message belongs to a mailing list and is ignored.
17:07:36 T4: Message has 1 parts and is moved to chat #3.
17:07:36 T4: Receive message #28552 from Maillisten/btrfs-Mailingliste.
17:07:36 T4: Message belongs to a mailing list and is ignored.
17:07:36 T4: Message has 1 parts and is moved to chat #3.
17:07:37 T4: 4 mails read from "Maillisten/btrfs-Mailingliste" with 0 errors.
17:07:37 T4: 0 mails read from "Maillisten/networkmanager" with 0 errors.
17:07:37 T4: 0 mails read from "Newsletter" with 0 errors.
17:07:37 T4: Init lastseenuid and attach it to UIDVALIDITY for folder "OUTBOX".
17:07:37 T4: Folder "OUTBOX" is empty.
17:07:37 T4: 0 mails read from "OUTBOX" with 0 errors.
17:07:37 T4: 0 mails read from "Software" with 0 errors.
17:07:37 T4: Folder "Spamverdacht" ignored.
17:07:37 T4: Receive message #4664 from TLZ.
17:07:37 T4: Message has 1 parts and is moved to chat #1.
17:07:38 T4: 1 mails read from "TLZ" with 0 errors.
17:07:39 T4: 0 mails read from "Uhrenhandy" with 0 errors.
17:07:39 T4: IDLE start...

SDK_INT=16
MANUFACTURER=Neptune
MODEL=Neptune Pine
APPLICATION_ID=com.b44t.messenger.beta
BUILD_TYPE=debug
ABI=universal
ignoreBatteryOptimizations=-1
versionCode=513

**Comment by r10s** [comment]
can the app be used normally before the crash? / konnte die app vor dem Absturz normal verwendet werden?

**Comment by r10s** [comment]
might be that this is fixed by https://github.com/deltachat/deltachat-core/commit/efb77369e42ed8be6c3a4c6d639b37c0b060584f , please check again in Delta Chat 0.16.0 or later.

**Comment by r10s** [comment]
might also be fixed by https://github.com/deltachat/deltachat-android/commit/d5c2a8b9fab78176fc946ede6c935a98cb87bcba
