### ISSUE TITLE
show notifications settings per account

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#2543]
Currently,  the show notifications setting applies to all accounts. 
There are situations where you want to change this setting per account instead, especially after the multi-account notifications feature was introduced. 

@r10s mentioned this enhancement was already planned, but no ticket existed yet. So it is :)

**Comment by r10s** [comment]
feature proposal now tracked at https://support.delta.chat/t/show-notifications-settings-per-account/2747
