### ISSUE TITLE
Improving the quality of the voice message

### ISSUE THREAD

**Issue by MadTooth** [deltachat/deltachat-android#2550]
VOICE MESSAGE AUDIO QUALITY - TERRIBLE

_Can you improve the sound quality of a voice message, or add the ability to customize the sound quality of a voice message?_

**Comment by hpk42** [comment]
that's the first complaint of its kind (i am aware of). 
could you provide an audio file maybe that exhibits the "terrible" sound quality?

**Comment by MadTooth** [comment]
I was wrong, the problem is in fork DeltaLab.
