### ISSUE TITLE
[Inconvenient] Very small move down button

### ISSUE THREAD

**Issue by MadTooth** [deltachat/deltachat-android#2559]
Can you make? the "move down" button larger ! (for example, the size of the "[PaperClip](https://dojki.rf.gd/SmallButton.webp)" button)

**Comment by gerryfrancis** [comment]
@MadTooth Hi, and thank you for your report. I consider this an issue, as the size of the button to scroll a chat to its end always stays the same, even after different font and/or display sizes in the respective Android settings have been configured.
