### ISSUE TITLE
Create a relation between IMAP log message ID and real messages seen in chat

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#256]
In IMAP log which can be selected by Settings->Info->Info messages are reflected by an ID #12345. I suppose this is the UID as described in other issues.
I think it would be a good idea to establish a relation to real messages seen in chats for detecting DC's behaviour because sometimes I see strange behaviour of delivering of certain messages.
This can be caused by mail server or problem in DC?!

To detect this ...

my recommendation is to show/store
 a) UID (#12345) and
 b) "Message-ID" from email header
in Info section of each message.

@r10s maybe this helps for clearing some strange behaviours of some messages!

**Comment by r10s** [comment]
> In IMAP log which can be selected by Settings->Info->Info messages are reflected by an ID #12345. I suppose this is the UID as described in other issues.

Not always. There are (at least) three type of IDs:

- `ID #123456` - used to identify a message in the database. This identifier is only valid for the local instance.
`UID #123456` - used to identify a message on a given folder on the sever. Useful only together with the folder name and as long as UIDVALIDITY does not change. Normally, this is shown by `FOLDER/UID`
`Message-ID` - used to identify a message worldwide.

Not all function writing things to the log have the knowledge of all IDs, so it would be an extra effort to log uniquely. But I think we should keep your suggestion in mind when generating new log messages to log really everything we know in a given moment.
I also did a quick review of how the IDs are logged and found an ambiguous log entry that i have [changed](https://github.com/deltachat/deltachat-core/commit/5a79eff312d58dfcf741a480e85909ea65c325fa) - there may be more log entries that could be improved, any PR on this are welcome.

> my recommendation is to show/store
> a) UID (#12345) and
> b) "Message-ID" from email header
> in Info section of each message.

Good idea. With https://github.com/deltachat/deltachat-core/commit/c099c5fdf900620ce1ccebe10a9bc14089288b57 I have added the Message-ID, the server folder and the server UID; I think these numbers are also of interest for the user. I do not output the internal database id; this id may be more confusing than helpful to the user and if for the developer only useful if you have access to the sqlite database - and in this case you can get the database ID easily from the table "msgs".

**Comment by csb0730** [comment]
Great!
You make it more clear what ID's are used and with Your improvement as You describe it above, every user is able to see the relation between the log (info section), it's handling by IMAP and the real message at mail server or other MUA where the same message is handled.
:+1:
