### ISSUE TITLE
 <input type=file> should work in webxdc apps

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#2572]
it is supported by iOS and Desktop already, only Android is missing support, with this webxdc apps already have a way to import files in a classic well-known way used by web developers in existing web apps

**Comment by r10s** [comment]
once this is implemented, the docs should be updated, see https://github.com/webxdc/webxdc_docs/pull/46 for a suggestion

**Comment by adbenitez** [comment]
close #2575
