### ISSUE TITLE
Select group profile image "from camera" does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#259]
Select _group_ profile image "by camery" does not work, no crash or sth. like that, simply nothing happens when tapping on the button. Tested on Nexus 4 and Moto G, user schneider17, however, reported that it works for him. 

Selecting groups profile images "by gallery" or deleting them works for me.

NB: Selecting profile images for _users_ is not available this way, however, Delta Chat uses the profile images from the system address book. And we're thinking about letting users define their own profile image, see #130.

**Comment by testbird** [comment]
Where is this edit option? Could't find it.

**Comment by r10s** [comment]
> Where is this edit option? Could't find it.

@testbird you find it in the group profile when tapping on the group icon - the large "F" in the following image:

![group-image](https://user-images.githubusercontent.com/9800740/36938628-8c1a039c-1f24-11e8-9d07-a06b9bc6202f.png)

**Comment by testbird** [comment]
Ah, ok I would have expected some "select picture" options in the settings.

I can confirm it the "from camara" option does not seem to do anything.

**Comment by r10s** [comment]
just tested it again, it is not fixed by #319
