### ISSUE TITLE
add more context to dialog title shown after `sendToChat()`

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2594]
the title should be set to `send_file_to` or `send_message_to`. in case the RelayHelper is not used from `sendToChat()`, the title should stay as is.

for more context and screenshots, see https://github.com/deltachat/deltachat-ios/pull/1907 and https://github.com/deltachat/deltachat-android/pull/2592

**Comment by adbenitez** [comment]
nice, I was planning to touch that area to disable the "connectivity activity" that is shown if you tap the "share with.." title so with this issue is a good opportunity to do both
