### ISSUE TITLE
Upgrade targetSdkVersion and compileSdkVersion to 33

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2599]
We currently target SDK version 32 since it was upgraded in #2407.

Due to recent incident with deprecated JCenter repository #2595 it would be nice to upgrade at least some affected dependencies to versions that are published outside of JCenter. One such dependency is exoplayer, the version 2.9.6 that we depend on currently is published on JCenter and new version 2.18.7 which is published in Google's Maven repository requires SDK 33: #2598 

SDK upgrade guide is published at https://developer.android.com/google/play/requirements/target-sdk
There is no dedicated list of things to upgrade when migrating from API level 32 to API level 33, but there is a guide for migration from Android 12 (API level 31) to Android 13 (API level 33): https://developer.android.com/about/versions/13/behavior-changes-13

There is a number of changes to make:
- [x] For Wi-Fi use-cases the applications should request `NEARBY_WIFI_DEVICES` instead of `ACCESS_FINE_LOCATION` permission. Quick grep shows that we only request `ACCESS_FINE_LOCATION` in src/org/thoughtcrime/securesms/mms/AttachmentManager.java when attaching the location, but we may need to update this comment and test if backup transfer still works: https://github.com/deltachat/deltachat-android/blob/1343f5399a6d9c6264c772e2f2008919f4490519/src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java#L222-L223 Most likely it is not needed as we are not using Wi-Fi Direct and the documentation says "This change affects your app only if you call a Wi-Fi API.", but we are not using Android Wi-Fi APIs.  
EDIT: should be fine, i adapted the comment and commented at https://github.com/deltachat/deltachat-android/pull/2649/commits/84e8b7ef51851b1d86e31ba3a22852210fd85aa4
- [x] Use `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` instead of `READ_EXTERNAL_STORAGE` when running on Android 13. Another option suggested is to use [photo picker](https://developer.android.com/training/data-storage/shared/photopicker), but it is only supported on Android 4.4 (API level 19) which Delta Chat supports API level 16.
- [x] https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls - no idea if this affects us EDIT: i did not find any hint that this affects us, we're not using playback controls in notifications
- [x] [`setForceDark()`](https://developer.android.com/reference/android/webkit/WebSettings#setForceDark(int)) is deprecated. It is already behind `WebViewFeature.isFeatureSupported(WebViewFeature.FORCE_DARK)`, maybe can be removed completely? EDIT: fixed by https://github.com/deltachat/deltachat-android/pull/2695
- [x] other points from https://github.com/deltachat/deltachat-android/pull/2649

**Comment by r10s** [comment]
added "blocker" as it will block gplay releases from nov1 on (we got an extension, see #2684)

**Comment by adbenitez** [comment]
> * Use `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` instead of `READ_EXTERNAL_STORAGE`

it is not clear to me if this includes any file attachment, or we suddenly will only support images ,video, audio :thinking:

**Comment by r10s** [comment]
setForceDark() is not only deprecated, it is a no-op on API33, so we really have to adapt things :/

**Comment by r10s** [comment]
> > * Use `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` instead of `READ_EXTERNAL_STORAGE`
> 
> it is not clear to me if this includes any file attachment, or we suddenly will only support images ,video, audio 🤔

no. READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE persmissions are just no longer needed as accessing these files is possible over file pickers only. this is already since some time the case, however, in the past, checking for READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE did not hurt our code. for api33, we now explicitly skipped the check manually and call `onAllGranted()` directly
