### ISSUE TITLE
Emojis sind schwarz/Emojis are black

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#260]
Ich verwende Delta Chat 0.15.0 auf einem Neptune Pine unter Android 4.1.2. Auf diesem Gerät sind die Emojis schwarz.
Meine Frau verwendet Delta Chat 0.15.0 auf einem Samsung S8+ unter Android 8.0.0 . Auf ihrem Gerät sind die Emojis farbig (normal) aus.
-------------------
I am using Delta Chat 0.15.0 on a Neptune Pine under Android 4.1.2. on this device the emojis are black.
My wife is using Delta Chat 0.15.0 on a Samsung S8+ running Android 8.0.0.0. On their device the emojis are colored (normal) off.

Neptune Pine:
![nepi_emojis_screenshot_2018-03-02-19-48-05](https://user-images.githubusercontent.com/36864290/36923538-e6de09d6-1e6b-11e8-9a9e-4fc3816c3ae8.png)
S8+:
![s8 _emojis](https://user-images.githubusercontent.com/36864290/36923544-eb172884-1e6b-11e8-8d5e-f7bfcd94e33b.jpg)
Neptune Pine:
![nepi_screenshot_2018-03-02-19-45-48](https://user-images.githubusercontent.com/36864290/36923592-0d9b8d1e-1e6c-11e8-8549-688fb51593b4.png)
S8+:
![s8 _image-12](https://user-images.githubusercontent.com/36864290/36923602-145e596a-1e6c-11e8-8195-14a93cb843da.jpg)

**Comment by csb0730** [comment]
This seems to depend on the devices OS version.
At my known devices it is the same: Android 4.0.x (Samsung S3) Emojis: black, Android 7.1.2: Emojis in colour.

**Comment by r10s** [comment]
Delta Chat currently uses the system font to draw the emoji, so they may [look different on different devices](https://unicode.org/emoji/charts/full-emoji-list.html) - or even may not be rendered at all. For now, there is not much we can do on this topic - maybe it is possible to install a different font for your device. I think we can close this issue.

NB: A different approach might be to draw the emoji ourself, however, this may have some other disadvantages (eg. other emoji in Delta Chat as in other apps, raised complexity) and won't completely solve the problem at all as you can send emoji also to non-Delta-clients which may render them different again (eg. Thunderbird ...) - but this would be a different issue, myself is not up for this right now, but I would be happy to support/review suggestions and efforts.

**Comment by icke68746** [comment]
Hello,
I've got coloured emojis now. Thanks a lot!

Greetings Mike
--Oirginal--
Hallo,
ich habe jetzt farbige Emojis. Danke!

Gruß Mike

**Comment by r10s** [comment]
@icke68746 and how did you finally fix it? this might be interesting also for other users.

**Comment by adbenitez** [comment]
I think @icke68746 say it works because in the new versions of Delta Chat, built-in emojis are used by DC, if the "use system emojis" option is set I guess the black ones will come back ;)

**Comment by r10s** [comment]
okay, i see :) in general, i like the black emoticons, btw. it's a feature!

**Comment by adbenitez** [comment]
hahaha I like the black but I don't like they are too much Android-ish ;)
Also wondering how they look in the dark theme
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by r10s** [comment]
in the dark theme you would proably only see eyes and mouth. uhhhhhhh, straaaaaaaaange :)

**Comment by adbenitez** [comment]
hahahaha

On May 1, 2019 3:48:57 PM GMT-04:00, "björn petersen" <notifications@github.com> wrote:
>in the dark theme you would proably only see eyes and mouth. uhhhhhhh,
>straaaaaaaaange :)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
