### ISSUE TITLE
Add "force refresh" function

### ISSUE THREAD

**Issue by Aydan** [deltachat/deltachat-android#261]
I'd like to have a force refresh function to force a reload of the messages on the mail server and also a last refreshed timestamp so I can see if there really are no new messages or if the refresh hasn't happened lately.
The problem for me is that messages usually get shown with a delay of up to several hours. Especially if the phone has slept for a while. Force-closing the app and reopening will show the messages.
App version 0.14.0 on CM13.0 on LG G2 with a web.de account

**Comment by r10s** [comment]
Thank you for your post. Probably, we will rework some of these points, the idea is to get a fetch at least when the app goes to the foreground, but this is not 100% clear; it also depends on the possibilities on iOS (iOS will need some different approaches; Android can benefit from them, then)

**Comment by r10s** [comment]
I think, in general we should not aim for a "force refresh" but for a more reliable fetching method, this is targeted by #269 and I think we can close this issue now.

**Comment by Aydan** [comment]
I can live with the "app to foregrund" approach.

**Comment by r10s** [comment]
> I can live with the "app to foregrund" approach.

The aim would be that this is not needed at all but the refresh just always works reliable :)
