### ISSUE TITLE
Initial build takes longer then might be needed

### ISSUE THREAD

**Issue by pjvleeuwen** [deltachat/deltachat-android#2613]
The initial build takes longer then might be needed for some (most?) developers.

The `scripts/ndk-make.sh` step described in https://github.com/deltachat/deltachat-android#build-using-nix took me 45 minutes. 
Later I found out that the script itself actually provides good documentation on how to speed things up: https://github.com/deltachat/deltachat-android/blob/3becdf52ecc2623b6d1ad5fd2195a2ee674a2c76/scripts/ndk-make.sh#L3

I propose to reference to this existing documentation in the getting started documentation to allow the next person to spend less time.

**Comment by pjvleeuwen** [comment]
PS: The fact that I (as an absolute n00b) was able to get the APK build, only shows that the current documentation is very good. Just attempting to polish a bit on what is already a job well done 👍✌️

**Comment by adbenitez** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/2614 thanks a lot @pjvleeuwen
