### ISSUE TITLE
end-to-end encryption disabled even if necessary public keys are on device

### ISSUE THREAD

**Issue by monperrus** [deltachat/deltachat-android#2617]
- Android version: 13
- Delta Chat version:  1.38.2

- Expected behavior:
When public keys are on the device, end-to-end encryption is enabled for outgoing messages.

- Actual behavior:
Public keys are on the device (as per menu >> "Encryption",  "end-to-end encryption available",  [DC_STR_E2E_AVAILABLE](https://c.delta.chat/group__DC__STR.html#ga2025629ecb152101fca8347b97ce516d)), yet all outgoing messages are clear text. I don't find a switch to activate it (''end-to-end encryption preferred", [DC_STR_E2E_PREFERRED](https://c.delta.chat/group__DC__STR.html#gaaf68df9f876a78d007461d1dd269560b)).

- Steps to reproduce the problem:
Start a clear text chat between Alice (using an email client) and Bob (using DeltaChat), with a few messages, later Alice sends a message with public key in autocrypt header, then Bob sees "end-to-end encryption available", yet Bob continues to send clear text messages to Alice.

**Comment by Hocuri** [comment]
If the last message you got from Bob was sent using a classical email client, then DC assumes that Bob can't read encrypted message and sends unencrypted. Since years, there is the plan to add a "Force-encrypted/Force-unencrypted" option when sending: https://support.delta.chat/t/force-once-un-encrypted-to-directly-reach-a-classic-mua-after-having-had-a-chat/227, but as so many things, we didn't have the time to implement it yet.

> * Start a clear text chat between Alice (using an email client) and Bob (using DeltaChat), with a few messages, later Alice sends a message with public key in autocrypt header, then Bob sees "end-to-end encryption available", yet Bob continues to send clear text messages to Alice.

Can you retry whether this actually happens even if the last message you got from Bob was sent with DeltaChat?

**Comment by monperrus** [comment]
thanks for the fast answer @Hocuri .

do you mean that Deltachat checks some additional information in addition to the presence of the autocrypt header, such as the user-agent?

**Comment by Hocuri** [comment]
For encryption, DC only checks the Autocrypt header, and inside the Autocrypt header the `prefer_encrypt` field.

**Comment by monperrus** [comment]
OK, that's clear, thanks. It's consistent with the fact that Thunderbird does not set `prefer_encrypt` in the autocrypt header.

So a fix easier than adding a button would be to assume `prefer_encrypt=true` if `prefer_encrypt`is absent.

**Comment by monperrus** [comment]
fix proposal: https://github.com/deltachat/deltachat-core-rust/pull/4553

**Comment by Hocuri** [comment]
As of https://github.com/deltachat/deltachat-core-rust/pull/3774, DC treated all messages from Thunderbird as `prefer_encrypt=mutual`. This was changed again in https://github.com/deltachat/deltachat-core-rust/pull/3832, now all messages that have _the public key attached OR are encrypted & signed themselves_ are considered as `prefer_encrypt=mutual`. This seems like a nice solution to me; Thunderbird users who want to encrypt will attach their public key, and we don't totally need to violate the Autocrypt specification.

**Comment by monperrus** [comment]
I confirm that "public key attached" triggers an encrypted answer from DC. This works even without the autocrypt header, so this is completely independent of autocrypt.

> are encrypted & signed themselves

my test messages are already encrypted and signed. what do you mean exactly? I'd like to give it a try.

**Comment by Hocuri** [comment]
> > are encrypted & signed themselves
> 
> my test messages are already encrypted and signed. what do you mean exactly? I'd like to give it a try.

If DC has a public key of a user, and the last message you got from them is encrypted & signed with the public key, then this is treated as prefer_encrypt=mutual.

I think we can close this issue, then?

**Comment by monperrus** [comment]
> If DC has a public key of a user, and the last message you got from them is encrypted & signed with the public key, then this is treated as prefer_encrypt=mutual.

this is exactly the case I'm describing in this issue. Bob has Alice's key, and the last message from Alice is encrypted and signed.

the current behavior in DC 1.38.2 "If DC has a public key of a user, and the last message you got from them is encrypted & signed with the public key" 
then the reply is in clear text.

that is the bug we're discussing.

**Comment by hpk42** [comment]
if there still is a problem please open a new issue, and verify it against 1.40.X releases.

**Comment by monperrus** [comment]
thanks a lot! Is that already in the nightly build: https://download.delta.chat/android/nightly/?

**Comment by hpk42** [comment]
yes 1.40.X is on nightly, but the regular 1.40.0/1 releases are out in stores.

**Comment by monperrus** [comment]
I tried with Android nightly, the bug is still there:

Actual behavior: I reply to an encrypted message with autocrypt key, the Deltachat message is clear text


Expected behavior: I reply to an encrypted message with autocrypt key, the Deltachat message is encrypted.

@hpk42 shall I open a new issue with the exact same symptom?

**Comment by hpk42** [comment]
On Tue, Sep 12, 2023 at 07:43 -0700, Martin Monperrus wrote:
> I tried with Android nightly, the bug is still there:
> 
> Actual behavior: I reply to an encrypted message with autocrypt key, the Deltachat message is clear text
>
> 
> Expected behavior: I reply to an encrypted message with autocrypt key, the Deltachat message is encrypted.
> 
> @hpk42 shall I open a new issue with the exact same symptom?


yes, please. Also mention the presence/absence of Autocrypt headers. 
It's likely this is a core-rust issue so better open it in the core repo. 
thanks!
