### ISSUE TITLE
Ability to customize the value of "Auto-Download Messages"

### ISSUE THREAD

**Issue by MadTooth** [deltachat/deltachat-android#2622]
Can you add the ability to customize the value of "Auto-Download Messages" (Custom value), I need to set "this" value to 0

**Comment by Hocuri** [comment]
> I need to set "this" value to 0

What's "this", and why do you want to set it to 0? Do you want to not auto-download any messages at all, and only download messages manually?

**Comment by r10s** [comment]
ftr, setting download limit to "0" would break many things. currently, we do not have many meta information for not-downloaded messages and the current minimum is chosen to let read receipts and other system messages as webxdc updates pass

also customised values tend to cause issues, therefore, delta chat (and many other comparable apps) prefer a set of predefined values - however, of course, also in the past, we adapted and improved these sets, so, this is possible :)

**Comment by MadTooth** [comment]
@Hocuri Yes

**Comment by MadTooth** [comment]
@r10s Understood
