### ISSUE TITLE
Ability to accept (all) certificates

### ISSUE THREAD

**Issue by MadTooth** [deltachat/deltachat-android#2638]
Can you add the ability to accept (all) certificates ? (for example, as in the "[ProfiMai Go](https://www.lonelycatgames.com/apps/profimail)" application)

![DeltaLab](https://github.com/deltachat/deltachat-android/assets/30464341/f8e7e731-f7be-4e52-8d90-79830e77468c)
![ProfiMail_Go](https://github.com/deltachat/deltachat-android/assets/30464341/55417994-1c38-433a-b37e-f6785a62d449)

**Comment by MadTooth** [comment]
> You can set "Certificate checks" to "Accept invalid certificates".

How ¿

**Comment by r10s** [comment]
> How ¿

when you enter your credentials, tap "Advanced" and scroll down to "Certificate Checks". there, select "Accept invalid certificates":

<img width="200" alt="Screenshot 2023-08-25 at 22 07 04" src="https://github.com/deltachat/deltachat-android/assets/9800740/b5ac502f-9570-4a14-9b25-e07b7c23a967">
<img width="200" alt="Screenshot 2023-08-25 at 22 07 39" src="https://github.com/deltachat/deltachat-android/assets/9800740/4404e10f-e95a-4cf6-809e-43dad2b0a9dd">

for an already configured account, you find the same options at "Settings / Your Profile / Password and account / Advanced / Certificate Checks"

**Comment by MadTooth** [comment]
Thanks
