### ISSUE TITLE
chat prompt shown for unknown sender

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#267]
I still can't fully understand when deltachat prompts to open a chat and when it doesn't.

I created a new contact, and sent a message. Apparently the message got forwarded to another address, because the reply came with a different local part.

* The replying deltachat did not seem to have picked up the autocrypt keys.
* My deltachat asked if the reply should open a chat.

**Comment by r10s** [comment]
i think your post is about the message you sent to r10s at b44t dot com?

I think the following has happened:
- A (you) sends a message to B (r10s ...)
- B forwards the message to C, adding, for any reasons, A and B as recipient
- C (me) answers to A and B

Up to 0.15.0, the message creates a new single-user chat with C, as the message is a reply to a known message, Delta Chat ask if the chat should be created, see https://github.com/deltachat/deltachat-core/blob/217bd51e14c0b8111f56a28f6ce251bee93c6234/src/mrmailbox.c#L490

In Delta Chat >0.15.0 a new ad-hoc group will be created.

**Comment by testbird** [comment]
> adding, for any reasons, A and B as recipient

Why would you ad A? Or do you mean B (like a CC to self?)

To avoid the group in Delta Chat >0.15.0, would one use a BCC?

**Comment by testbird** [comment]
If for a second we leave out the additional `To:` added when forwarding,
what's the reason not to automatically open a chat for replies coming from a (forward) address?

Maybe an idea to not create groups when one forwards a secondary address to a deltachat address (a use-case that might be common as long as deltachat only supports a single account) could be an option to configure the forwarded address as an "alias" addresses in deltachat? (So that it replies as if the message was sent to the forward address.)

**Comment by r10s** [comment]
it's because the "forwarding" comes from the "in-reply-to" and you cannot be sure that this is always the same person replying. and, as a general concept, Delta Chat shall only show chats with desired/confirmed persons (to mitigate this, however, the contact request popping up in the chatlist was introduced)
