### ISSUE TITLE
reactions not shown if there are many

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2679]
if there are many reactions, the `+NUMBER` is shown, however, the two "always shown" reaction pills are empty:

![Screenshot 2023-09-29 at 13 53 51](https://github.com/deltachat/deltachat-android/assets/9800740/b118533b-01a1-4e91-96ac-7c52b39fdb53)

(reaction generated with repl command `react MSGID 😎 💋 1 2 3 4 5 6 7`)

**Comment by adbenitez** [comment]
the issue is that they are text and for some reason the pill is not rendering text reactions

**Comment by r10s** [comment]
maybe white on white text?
