### ISSUE TITLE
no backups found

### ISSUE THREAD

**Issue by streaps** [deltachat/deltachat-android#268]
I'm trying to import a backup, but Delta Chat 0.15 complains:

>No backups found:
>
>Copy the backup to /storage/emulated/0/Download and try again. …

I have no idea what is wrong, because the backup file is there. It was written by a previous version on the same device.

```
/storage/emulated/0/Download $ ls -la delta-chat-*                                                                           
-rw-rw---- 1 root sdcard_rw 122880 2018-02-05 06:38 delta-chat-2018-02-05.bak
```

**Comment by Ampli-fier** [comment]
Have you tried to restart your phone? This helped in [this issue](https://github.com/deltachat/deltachat-core/issues/50), reported on Delta Chat Core.

**Comment by r10s** [comment]
would be interesting if there is a workaround for this strange behavoir of android

**Comment by streaps** [comment]
> would be interesting if there is a workaround for this strange behavoir of android

I don't think it's a strange behaviour of android. I'll add a comment to the issue in deltachat-core, maybe you can reopen deltachat/deltachat-core#50.
