### ISSUE TITLE
Background-Poll

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#269]
It might be an good alternative to pull for messages in background instead of using PUSH-IMAP instantly. When the app comes to foreground, we would switch to PUSH-IMAP to allow instant chatting

The advantages would be 
- no permanent notification needed (targets #82)
- probably more reliable than a PUSH-IMAP that runs for days (see #261, a "force refresh" would be every app-to-foreground then)
- no hacks required
- can probably use the same way on iOS
- possibly a better battery life (#104)

Disadvantage is mainly a larger delay for messages appearing when the app is not in foreground. But we could offer the instant-PUSH-IMAP-mode as an option (another option may be not to pull at all in background, see #253, #200)

This issue is not super-urgent, as, in general, the current approach works.

**Comment by Ji-eF** [comment]
I vote :+1: for this after being hit by deltachat/deltachat-core#12 :)

**Comment by testbird** [comment]
This would likely take DC out of the competition of instant messengers.

Polling is slow or likely battery intensive.

To reduce current battery usage, consider reducing the default scanning interval of (potentially GBs of)  imap folders to once a day, instead of every 30 minutes, and implement custom folder ignore lists.

But keep push IMAP by default!

**Comment by testbird** [comment]
@r10s: Apologies for my short bullet point like sentences.

**Comment by testbird** [comment]
What might make more sense to improve the push reliability, and even battery usage, could be to use the android network status changes to make sure stalled IMAP-push connections get closed and re-established properly when the network connection is lost or changes.

**Comment by testbird** [comment]
The network state events are now considered in https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy

**Comment by r10s** [comment]
v0.18.0 will come with two fetch modes, "Save battery" (poll, default) and "Persistent connection" (push).

We made the poll-mode the default mode as it:
- uses less battery (<1% instead of 4% in my tests)
- is more reliable, esp. newer Android versions are very aggressive in shutting down background tasks. it is not always easy to tell users how to get around this - and it may not even work on all systems
- no annoying permanent notification required
- no other hacks required
- when the app comes to foreground, push is enabled automatically

![screenshot_1526985025](https://user-images.githubusercontent.com/9800740/40358740-93234c7c-5dc0-11e8-9f19-a3492be3d865.png)

NB: https://www.fastcodesign.com/90171307/googles-plan-to-make-tech-less-addictive :)

**Comment by testbird** [comment]
> When the device is in doze mode, the delay may be longer.

What are the actual timeouts, are they configurable?

**Comment by r10s** [comment]
i think this depends on the device and the system.

**Comment by testbird** [comment]
Ok, so I understand the menu selection as:
* Periodic **Pull** (Delays during doze save battery.)
* Keep persistent **Push** connection alive (Instant as far as battery saving is disabled in OS.)

Let't see how it works in practice.

**Comment by r10s** [comment]
> Let't see how it works in practice.

yes, this was also my idea. might be that we have to think over the defaults after some time.

of improve things in other ways, eg. there is a relative new API for background jobs that seems worth having a closer look: https://developer.android.com/reference/android/app/job/JobScheduler

**Comment by adbenitez** [comment]
was this option removed? I don't find it in the settings

**Comment by r10s** [comment]
yip, to simplify things, we're supporting only one mode currently and meanwhile we als figured out how to work around some limitations that were present at the time this issue was initially written (iirc :)
