### ISSUE TITLE
rename `stable` to `main` and `master` to `feat/verified-1to1`

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2691]
we tried out stable/unstable on android in practise, and it causes issues and confusion [^1]

so, stable/unstable does not hit the correct set if tradeoff for android in practise. if a a critical bugfix requires a "stable" branch, we can always branch off the corresponding release tag

therefore, in android-dev there was sort of agreement to go back to the model we're using on desktop/ios and as well on android in the past:

- having a "stable/main/master" that uses a stable core, releases are build from there and feature-branches are merged there
- having feature-branches for features
- having some "merge window for dangerous pr" as we did in practise implicitly in the past, we can also flag these "potentially dangerous features" as such

for renaming, idea is to follow the instruction from https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch - there is also some description about how to follow renaming locally

[^1]: some points from android-dev and other discussions (sorry for the mess; many points are for sure solvable by investing more time/brain - but these resources are better spend elsewhere):<br>- PRs are done against the "wrong" base, so, one frequently has to correct things and always has a closer look<br>- core API change in combination with different APIs on stable/master and the need to merge to stable and from there to master is a pain [[eg]](https://github.com/deltachat/deltachat-android/pull/2655#issuecomment-1732538160) [[eg]](https://github.com/deltachat/deltachat-core-rust/pull/4314#issuecomment-1732535864)<br>- we do not check in submodules to fixing PR usually - usually this is unrelated anyways, and also "just so changing" the submodule has its dangers on its own<br>- translations cannot be pushed from master, need to be done from stable now, then merged into master. this again requires additional brain resources<br>- log is polluted with "sth. merged from stable"<br>- it is easily forgotten to merge things from stable to master - otoh, some prefer "`stable` is generally merged into `master` after tagging a release, not after every commit." - a source of confusion<br>- hard to solve merge conflicts - thankfully there was always lots of help to get them solved, but it feels like being out of control<br>- Delta Libre has its own issues (adb can tell)

**Comment by r10s** [comment]
for the "merge window", i created some more labels where waiting PR can be flagged with:

![Screenshot 2023-10-01 at 13 58 54](https://github.com/deltachat/deltachat-android/assets/9800740/5d6853a3-d973-466c-8fa0-dc71d50ed6f0)

this esp. makes the PR overview nicer

**Comment by adbenitez** [comment]
TIP - to manually update your local environments:

```
git branch -m stable main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
