### ISSUE TITLE
Allow passwords ending with whitespace?

### ISSUE THREAD

**Issue by adrian-bl** [deltachat/deltachat-android#270]
DeltaChat can not be used with an account whose password ends in one or multiple whitespaces.

Having deltachat connect to 'netcat' shows that the user supplied password is silently modified: trailing whitespaces are silently removed from the password which is sent to the server.

An example 'captured' via `nc -l -p 143`

Create a new account in deltachat with:
User: `username`
Password: `foo ` #<- note the whitespace at the end. (which isn't visible in githubs rendred text?!)

The login attempt will look like this:
```
> * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED AUTH=CRAM-MD5 AUTH=DIGEST-MD5] fake-imap ready
< 1 LOGIN username foo
```

Note that the sent password (`foo`) had its trailing whitespace removed.
Instead, `1 LOGIN username "foo "` should have been sent to the imap server.

**Delta Chat version**

0.15.0

**Expected behavior**

Should use the specified password to log in

**Actual behavior**

Sends a different password to the imap server: all whitespaces at the end of the password get removed.

**Steps to reproduce the problem**

1. Create a mail-account with a password which ends in one or multiple whitespaces
2. Try to use the account in delta-chat
3. You will be unable to login as delta-chat fails to send the correct password to the IMAP server.

**Comment by r10s** [comment]
Thank you very much for starting a discussion for this.

This is the corresponding line in the code: https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/SettingsAccountFragment.java#L294 - just removing this line would change the behaviour to the behaviour described above. So the behaviour could be easily changed.

However i am not sure, if we should change it this way.

- some users might accidentally put spaces before or after their passwords, or assume that doing so has no effect. So it could also be confusing for some users if spaces are kept.
- spaces may be added when using copy+paste for passwords \[[via](https://security.stackexchange.com/questions/89230/why-will-google-no-longer-allow-me-to-end-or-begin-passwords-with-a-space/89237)], also autocomplete, voice and so on could make problems.
- after duckduckgo'ing around - it seems not to be unusual

Maybe the disadvantages outweigh the benefits of having the possibility to add a space at the end of a password.

**Comment by mogorman** [comment]
i think modifying password on users behalf is never a good idea, but one solution is if you trimmed the login and the login failed try again with the unmodified version of the password.

**Comment by r10s** [comment]
> i think modifying password on users behalf is never a good idea, but one solution is if you trimmed the login and the login failed try again with the unmodified version of the password.

yes - this sounds very reasonable. However, I think, for now, we should just remove the trimming the the frontend and maybe add a comment in the backend that we could probe different passwords if we _really_ get complaints about users expecting spaces to be trimmed.
