### ISSUE TITLE
Delta Chat and SMSBackup

### ISSUE THREAD

**Issue by Ji-eF** [deltachat/deltachat-android#272]
I'm using the latest Delta Chat from F-Droid.

I use SMS Backup to periodically save my SMS on my Mail server.
(If you're not familiar with SMSBackup) The SMS are saved on a auto-created subfolder Inbox.SMS with recipient's phone number AND hir associated mail if applicable.

For every contact with a mail address, I receive backed-up SMS on my Direct Chat discussion with that person, and it kinda... floods my conversations.

Also, SMS I reply to those contacts --also saved on Inbox.SMS by SMSBackup-- are displayed on a Delta Chat conversation "Messages I send to myself"

Can something be done to avoid it. Would it be possible to only allow Delta Chat to just read Inbox.Chats and nothing else ? (Sorry if this question seems silly ; I probably miss some background informations)

Thanks for reading, and thanks for this simple, yet great program :)

**Comment by r10s** [comment]
Do these mails headers look like `From: email@associated-with-phone-number.com, To: your@address.com` and  `From: your@address.com, To: your@address.com`? If so, the behaviour described above is the behaviour I would expect - though if is not your desired behaviour. 

To force delta chat not to show these messages, it seems to be sufficient just to ignore the folder. Currently, there is no explicit option for this in Delta Chat, however, there is already a feature request in #239

**Comment by Ji-eF** [comment]
Thanks r10s for this reply.
Yes indeed, `From:` and `To:` headers show correct mail addresses.
I'll wait for this option to get implemented then.
Thanks again :)

**Comment by r10s** [comment]
okay, thank you for your answer. so we know at least that the deltachat-messages-to-chat-logic is working as expected. And I think, sooner or later there will be an ignore folder feature :)

**Comment by Hocceruser** [comment]
Until then, you could just use another  email account for SMSBackup 😉

**Comment by rizzopablo** [comment]
I use smsbackup too, and actually I like to see the sms and call-missed warnings from SMSBackup in the same conversation within Delta Chat. I would also like to choose Delta to ignore some other folders, but not in this case. Just my 2cents. Long live to Delta and the email! Best regards!

**Comment by testbird** [comment]
> SMS I [send and] reply to those contacts --also saved [in] `INBOX.SMS` by SMSBackup-- are displayed [in the] Delta Chat conversation "Messages I send to myself"

Is that the correct behavior?
* If SMSBackup can identify the recipients email address, shouldn't deltachat list them *in the chat with the contact*, or ask to open a new chat. Is that not the case?
