### ISSUE TITLE
is `application/pgp-keys` really supported for the android file selector?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2733]
in `AdvancedPreferenceFragment.java` we're using the mime type `application/pgp-keys` for the file selector. i doubt, this is really supported by android, maybe it preserves the mime type if exported by delta chat, however, probably not when copied otherwise.

we're passing `text/plain` as an alternative selection. although starting already on 4.4, this extra field is not supported on all android versions

and even if the extra field is supported, it still may be that .asc is not identified as `text/plain` - but as sth. else.

all in all, i think, the mime types are too fragile here.

maybe better just say `*/*` for the mimetype, s trike the extra-mimetype and call it a day. it is advanced anyways, the last part of selection will not scare the user that goes all that way ...

or is it known that android just always allows the user to selecte "*.*" manually, also on old androids?

**Comment by adbenitez** [comment]
good point, better safe than sorry, I will create a pull request

**Comment by adbenitez** [comment]
btw, the manual selection is only done for android SDK >= 30, so the android 4.4 etc. part doesn't applies

**Comment by r10s** [comment]
> btw, the manual selection is only done for android SDK >= 30, so the android 4.4 etc. part doesn't applies

i am wondering if we can get rid of some of these conditions, and use `selectMediaType()` more unconditionally. but that is another discussion and another issue :)
