### ISSUE TITLE
RegistrationActivity: run `getProviderFromEmailWithDns` off the main thread

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2747]
When the password field is selected on registration activity, `getProviderFromEmailWithDns` is called and queries MX record. It is a blacking call doing a network request, so it should not be executed on the main thread.

Normally the call is fast, but it can be slow if the DNS server is not accessible and "the app is not responding" error appears.

To reproduce:
1. Install [Rethink](https://f-droid.org/packages/com.celzero.bravedns/) from F-Droid.
2. Enable Rethink "VPN" by clicking "Start"
3. Open Delta Chat registration activity, type in "foobar@abc.tesrun.org" email.
4. Focus the password field.

"Checking foobar@abc.testrun.org" dialog appears. Clicking "Cancel" does not stop it, and even when it disappears, registration activity is unresponsive.

**Comment by adbenitez** [comment]
to test with Rethink: in the apps section (firewall) block wifi/mobile-data for delta chat
