### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by HammyHavoc** [deltachat/deltachat-android#275]
Dark mode would be great. Similar to TypeApp with choosing colors if possible.

**Comment by r10s** [comment]
A dark theme would be great, however, we would need someone to do it. Are you free for implementing this? Anyway, before I would suggest to rework some parts of the android frontend in a way that more standard classes and controls are used (and less self-painting stuff that came from the telegram codebase); this would probably make adding a dark theme much easier then.
