### ISSUE TITLE
new delta.chat mailing list and IRC channel

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#277]
hi all, just a redundant reminder here that we now have a mailing lits where you can subscribe here:

https://lists.codespeak.net/postorius/lists/delta.codespeak.net/

Also several are now on the IRC channel #deltachat on irc.freenode.net 

this issue can be closed soon again, it mainly serves as a reminder/notification :)

**Comment by Ji-eF** [comment]
Pardon my ignorance, but ...
I subscribed to delta@codespeak.net from https://lists.codespeak.net/postorius/lists/delta.codespeak.net/ , but how do I consult -older- messages from the ML ?

**Comment by r10s** [comment]
> but how do I consult -older- messages from the ML ?

currently, the archive is not configured, so, for now this is possible. but @hpk42 knows about this issue :)
