### ISSUE TITLE
Cannot send a photo

### ISSUE THREAD

**Issue by kuba-orlik** [deltachat/deltachat-android#278]
**Delta Chat version**

0.15.0

**Expected behavior**

When sending an image, it should be attached to the message

**Actual behavior**

The attachment is an empty (0B) file

**Steps to reproduce the problem**

1. Send an image
2. See that in the messages list it appears as empty

**Screen snapshots**

![photo_2018-03-21_12-21-46](https://user-images.githubusercontent.com/2697916/37707192-95c4f3c0-2d02-11e8-9544-ad8e6ffd49a2.jpg)

**Debug logs**

https://hub.sealcode.org/P6

**Comment by r10s** [comment]
could anyone reproduce  this?

**Comment by angelo-fuchs** [comment]
Having looked in your log, it seems like the app could not read the image:

--
12:13:34 T1: Cannot read "/storage/3DB7-CD11/Pictures/Screenshots/Screenshot_20180302-084904.png" or file is empty.
12:13:34 T1: Attaching "/storage/3DB7-CD11/Pictures/Screenshots/Screenshot_20180302-084904.png" for message type #20.
--

I'll try to reproduce this, it should prompt the user that there is a problem instead of silently doing nothing.

**Comment by angelo-fuchs** [comment]
This is not a FileNotFound (that looks like this)

> 06-27 10:59:39.952 4333-5456/com.b44t.messenger.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/sdcard1/der_schäääähhhhfer.jpeg: open failed: ENOENT (No such file or directory)
06-27 10:59:39.952 4333-5456/com.b44t.messenger.beta E/JHEAD: can't open '/storage/sdcard1/der_schäääähhhhfer.jpeg'
06-27 10:59:39.953 4333-5456/com.b44t.messenger.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/sdcard1/der_schäääähhhhfer.jpeg: open failed: ENOENT (No such file or directory)
    Unable to decode stream: java.io.FileNotFoundException: /storage/sdcard1/der_schäääähhhhfer.jpeg: open failed: ENOENT (No such file or directory)
06-27 10:59:39.953 4333-5456/com.b44t.messenger.beta E/JHEAD: can't open '/storage/sdcard1/der_schäääähhhhfer.jpeg'
06-27 10:59:39.954 4333-5456/com.b44t.messenger.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/sdcard1/der_schäääähhhhfer.jpeg: open failed: ENOENT (No such file or directory)

**Comment by angelo-fuchs** [comment]
Its also not a 0 byte file (that cannot be attached at all)

**Comment by angelo-fuchs** [comment]
@kuba-orlik Could you see if this still happens to you? If so, please do have a look at the file you are trying to attach. Does it exist? Can you read it (with e.G. Gallery)? How large is it? How much free space do you have left (at the place where the file is stored AND at the place where delta stores its files)?

**Comment by r10s** [comment]
nothing we can do on this issue currently.
if this is still an issue with the current version, please post more details and feel free to repopen this issue.
