### ISSUE TITLE
disable “QR Invite Code” until a first message is sent

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2783]
showing the “QR Invite Code” needs to "promote" the group, which may be unexpected, if you want to prepare an initial message at ease. one does not want to get "what is this group about?" feedback while writing the first message (this is what happens on WhatsApp, btw)

having a group only promoted after the first message is sent, would make this aspect clearer, however, has the disadvantage that the user has to learn that a message needs to be sent before “QR Invite Code” can be shown. this may be annoying if the main thing is to set up a group with ppl nearby, but not so much in drafting a first message; but it is unclear if ppl are really using group setup this way.

as we’re revamping things wrt verified-groups UI anyways currently, i would tend to give it a try - we’ll get feedback if ppl are really missing sth and have more clarity then (we could then as the user when showing QR code for unpromoted groups)

deferring group creation may also have the disadvantage that we could defer the verified/unverified decision to when the first message gets send (we cannot change the verified-state after the group is propagaged)

**Comment by r10s** [comment]
@adbenitez in dc:

> IMHO forcing a first message to see the QR button is bad UI

> if you click that button is expected that someone will be joining from that moment on so you dont want to send a first message (you are meeting irl and explanation is not necessary)
for the user is not obvious they need to send a first message to see the button, it looks completely arbitrary for them since that is a technical limitation of DC

**Comment by hpk42** [comment]
On Tue, Oct 31, 2023 at 06:27 -0700, bjoern wrote:

> @adbenitez in dc:
> > IMHO forcing a first message to see the QR button is bad UI
> 
> > if you click that button is expected that someone will be joining from that moment on so you dont want to send a first message (you are meeting irl and explanation is not necessary)
> for the user is not obvious they need to send a first message to see the button, it looks completely arbitrary for them since that is a technical limitation of DC

It's not exactly a technical limitation. We could send out a group-creation notice 
after the inital group-setup. I consider it a feature that the group only comes
to existence once you send an initial message. 

The question is if someone is actually using QR-invite codes 
while the group is in preparation, i.e. if people expect the QR-invite to be there 
when the group is still fresh and currently says 

    Others will only see this group after you sent a first message.

as the only message in the empty chat.  Using the Qr-invite code when the group is in this state
actually proves this statement as wrong which should rather more truthfully read: 

    Others will only see this group after you sent a first message
    or if you let them scan the QR-invite code from the member list. 

My stance is: Don't change the current message, fix the UX options to make it true :) 
Also, if we don't offer the qr-invite code while the group is in preparation
and we get feedback from users that they expect/miss it, we could add it back,
even in a minor bug fix release.

**Comment by r10s** [comment]
in recent user testing, ppl have issues to find the "QR Invite Code" as it is now. we are considering to add it to the menu in addtion at #2820 

if it would be disabled (or hidden - menu entries are usually not disabled on android), ppl have to understand additionally that they have to send a message before they can use it. this is hard to explain and not obvious when looking for "QR Invite Code".

seems both variation have their drawbacks, but it seems, the current implementation hits the better set.

closing this issue therefore for now, we can reconsider, if it becomes an issue again or if the set of tradeoff changes.
