### ISSUE TITLE
SMTP login will not work.

### ISSUE THREAD

**Issue by JobbeDeluxe** [deltachat/deltachat-android#2784]
- Android version: 12
- Device: Redmi note 9 pro eu
- Delta Chat version: last version, Download.
- Expected behavior: SMTP login should work
- Actual behavior: IMAP ist okay, SMTP login faild, in old Version (I do not know which exactly) was no problem. After Update No Massage could be send.
- Steps to reproduce the problem: removed all data start new Login put mail and password, IMAP is okay, SMTP login faild with SSL error 70. All cert are new.
- Screenshots: 
- Logs:
Konfiguration fehlgeschlagen. Fehler: Trying smtp: jobbe@unlimited8 .de@smtp.unlimited8.de:465 security=Ssl certificate_checks=strict oauth2=false socks5_config=None...

Error: error:1409442E:SSL

routines:ssl3_read_bytes:tlsv1

alert protocol version:ssl/record/ rec_layer_s3.c:1563:SSL alert number 70: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/ rec_layer_s3.c:1563:SSL alert number 70

Trying smtp: jobbe@unlimited8

.de@smtp.unlimited8

.de:587 security=Starttls certificate_checks=strict oauth2=false socks5_config=None...

Error: connection failure: No route to host (os error 113)

----------------

jobbe@unlimited8 .de@smtp.unlimited8.de:465 is correct and work with all other mail clients and with the old delta chat, too.

Please let me know how we can solve this.

**Comment by JobbeDeluxe** [comment]
I am not sure, but it looks like the server config is mixed up? I can't connect with thunderbird, too. only STARTTLS with teh correct Port is working, so may this is my server config issue, not on Deltachat..... Deltachat itself work with STARTTLS. But the strange thing is that every SSL test on smtp has no issue..

So if you think that could be checked, let me know if i can do something.  First of all i will check my Mailserver config.

**Comment by r10s** [comment]
thanks for coming back!

**Comment by JobbeDeluxe** [comment]
Aditional Information:

Tho Problem was: The answer from postfix was TLSV1 what is not supported anymore. I forced to use TLSV1.3 and now delta will find und use the smtp port as it should!

Greatings
