### ISSUE TITLE
title bar disappears sometimes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2798]
the title bar disappears sometimes, currently this is reproducible on the phone of @hpk42 

- send a message (virtual keyboard is still on) EDIT: no need to send just type is enough (or even just an open keyboard)
- turn screen off, wait 5+ seconds, turn screen on again

-> the title bar is gone. it reappears eg. when virtual keyboard is hidden

you may need to try this several times until it happens

**Comment by r10s** [comment]
nor could i, but i have seen it :)

**Comment by adbenitez** [comment]
I guess android version and phone model is relevant for this issue

**Comment by hpk42** [comment]
On Thu, Nov 02, 2023 at 13:13 -0700, Asiel Díaz Benítez wrote:
> I guess android version and phone model is relevant for this issue

Android version 14, Pixel 6a, calyxos.

**Comment by adbenitez** [comment]
I updated my phone to android 14 (xiaomi) but still couldn't reproduce this issue :(

**Comment by r10s** [comment]
android14 log shows two errors that are not there on android7 (which does not have the bug):

both errors do always happen, independently of the issue pops up or not

error before the screen is turned off:

> 2023-11-06 16:29:36.789  6919-6919  ImeBackDispatcher       com.b44t.messenger.beta              E  Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 242366287

error after the screen is turned on again [[full log]](https://gist.github.com/r10s/770055499ce3d1849fc2589b94b9f5b7)

> 2023-11-06 16:29:57.412  1626-14468 ActivityTaskManager     system_server                        E  setVisibility=true while transition is not collecting or finishing ActivityRecord{3021fa6 u0 com.b44t.messenger.beta/org.thoughtcrime.securesms.ConversationActivity t4251} caller=com.android.server.wm.ActivityRecord.setVisibility:5287 com.android.server.wm.TaskFragment.resumeTopActivity:1393 com.android.server.wm.Task.resumeTopActivityInnerLocked:5044 com.android.server.wm.Task.resumeTopActivityUncheckedLocked:4974 com.android.server.wm.Task.resumeTopActivityUncheckedLocked:5025 com.android.server.wm.RootWindowContainer.lambda$applySleepTokens$20:2428 com.android.server.wm.RootWindowContainer.$r8$lambda$9xL80GDJRExKql35hTmQVg_ieD8:0 com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda10.accept:0 
2

**Comment by adbenitez** [comment]
sadly #2825 didn't fix the problem, it is just really hard to reproduce and then not clear if it is fixed or just not happening randomly

**Comment by adbenitez** [comment]
more logs:
```
11-08 18:09:49.615  1466  7157 W ActivityTaskManager: Force removing ActivityRecord{7a87ff0 u0 com.b44t.messenger.beta/org.thoughtcrime.securesms.ConversationActivity t4347 f}}: app died, no saved state
11-08 18:09:49.616  1466  1695 W UsageStatsService: Unexpected activity event reported! (com.b44t.messenger.beta/org.thoughtcrime.securesms.ConversationActivity event : 23 instanceId : 223988073)
```

```
11-08 18:14:01.916  3562  3562 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.                                                                                                                          
11-08 18:14:01.916  3562  3562 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```

**Comment by adbenitez** [comment]
a similar report:
https://stackoverflow.com/questions/13561459/actionbar-is-hiding-when-keyboard-appears#13604665
