### ISSUE TITLE
(Optionally) create and/or use dedicated deltachat folders

### ISSUE THREAD

**Issue by digitalkram** [deltachat/deltachat-android#281]
Hi there
Thanks for this great idea to use email as a messanger base!

This is a feature request. 😄 

In order to eliminate the need to use a seperate email address (which limits "discoverabilty" for peers) to avoid cluttering your mailbox with tons of im-style messages (short one-liners with no context/greeting/salutation) I suggest that there could be a configuration option to specify (or automagically create if not yet existing) two folders to use as delta-inbox and delta-sent. So it is not mixed with the "real" emails.

[That also means there is no direct need to cleanup those folders/messages anymore which would also serve as an implicit backup of messages. Upon a first start of the app it could be offered to re-read them back into the app maybe (in chunks/wifi-only/x-month only)?]

Thanks again for this great idea and the very functional beta!

Cheers,

**Comment by testbird** [comment]
Looks like deltachat is also not working for you as inteded.

[It is already thought to move all messages into a `Chats` folder (name to be changed). But this still only works with some specific providers (imap servers), and thus many users suffer from all those messages showing up in other email programs and having to remove all those messages cluttering the inbox (apparently (counting the duplication of this issue from early on, and the thumbsup that also your report got, and the following silence) even to the degree of leaving deltachat behind again).]

If you are technically interested, maybe see if the IMAP-Strategy referenced at https://github.com/deltachat/deltachat-core/issues/117 would help in your case.

**Comment by testbird** [comment]
More than a feature request, this sounds like another variant issue for making the IMAP-Strategy work for the users in general. It has large user-impact.  ;-)

**Comment by digitalkram** [comment]
@testbird thanks for your super swift response.

Before I posted the issue I'll actually searched the existing issues and found most of those consolidated in #117 however I mist #117 iteslf obviously. So I considered this a feature request assuming this is intended behaviour accepted to deliver a working beta in a short time. 

But obviously it is more a bug or at least a problem with certain IMAP setups as I understand now. Looks like you discovered a downside of the decentralized aspects .. 10 servers with 11 different implementations ;) Probably impossible to cover them all. Still I am convinced that the idea is great. 

It will not scare me away :) but before recommending it to not so tech-savvy friends and family I'll still wait a while until delta chat matured.

My mail server is self-hosted so if you need a hand to troubleshoot the "initialization sequence" (which should have created folders and place sieve rules as far as I understood) end2end (as I have acces to the mailserver logs) I am here to help.
It might be worth doing as it is not a uncommon setup (dovecot).

Regarding IMAP-Strategy. I read it. It's good but when I read the "Re: Chat"-part and the issues related to ignored folders naming due to variations in naming and language-specific implications I started wondering if you have considered using/adding a specific header field to the header section to identify relevant messages instead of dealing with maintance of synonym lists like "RE, Re, Reply, Antwort, Réponse, ..) for folders and subject prefixes. I assume that was considered and overturned already for good reasons..

**Comment by testbird** [comment]
Thanks you for your writeup and offer to help with testing.

Yes, `Chat:` is discussed here https://github.com/deltachat/deltachat-core/issues/136, do mean `Re:` was already overturned?

**Comment by digitalkram** [comment]
I just meant that "Re:" is just one out of multiple possible prefixes that will be used by different clients/languages and was wondering if a identifcation of delta chat relevant messages shouldn't be based on something more reliable like email headers instead of subjects starting with "Chat: " or "Re: Chat: ".

**Comment by Ji-eF** [comment]
As far as I understand, delta chat provides X-Mailer and Chat-Version headers, so you can filter messages with those two

**Comment by digitalkram** [comment]
Sounds like a plan

**Comment by westsibe** [comment]
digitalkram, I think that better idea for Incoming messages in DC it's the Spam folder and use 1 e-mail address for DC and another push mail.

**Comment by Ji-eF** [comment]
@westsibe : personnally, I prefer not DC using the SPAM folder, as I'd like to keep my Chats on my mail box. And again, it's a personal opinion.

To prevent it from "spaming" my Inbox, I created a rule with the above-mentioned headers to move my 
chats over in a dedicated folder upon Seamonkey-Mail startup.

Also, maybe I misunderstood it along the road (someone will correct me I hope ^-^), but I think DC should move chats in its dedicated folder using sieve filters, but it does not seem to run on all IMAP configurations (surely not on my mail provider)...

**Comment by westsibe** [comment]
I doubt that Delta Chat will see incoming messages in the Spam folder because it uses the INBOX>Chats folder...

**Comment by testbird** [comment]
> I think DC should move chats in its dedicated folder using sieve filters

This would allow the server ~~moving~~ delivering messages directly into the email chat folder, and would fix getting the annoying duplicate notifications in classic MUAs that watch the INBOX folder. (It also moves messages when no DC client is online.)

Uploading a Sieve filter setup is not implemented, currently DC tries only to moves messages after it can detect them, but fails on many servers, because its default target location can not be created (the root folder is not an allowed location).

**Comment by testbird** [comment]
> I doubt that Delta Chat will see incoming messages in the Spam folder

Yes, the spam folder has a specific meaning. It is listed as an ignored folder. Spam message addresses should not be counted as known contacts.

**Comment by Ji-eF** [comment]
@testbird : Thanks for the clarifications about sieve filters, much appreciated :)

**Comment by JonasDralle** [comment]
Not working for me either  
I have a `Chats` folder but only ~ 60 % of my messages have been transferred there.

Maybe because I had Thunderbird open at the same time?
Details on my mail server can be found in #304

**Comment by r10s** [comment]
may be targeted by https://github.com/deltachat/deltachat-core/milestone/2

closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
