### ISSUE TITLE
can't use Service workers

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-android#2818]
- Android version:
- Device:
- Delta Chat version: 1.40.1
- Chromium version: 119
- Expected behavior: Service worker gets registered
- Actual behavior: `serviceWorker.register()` causes `Failed to register a ServiceWorker for scope ('https://acc1-msg1234.localhost/') with script ('https://acc1-msg1234.localhost/sw.js'): An unknown error occurred when fetching the script.`
- Steps to reproduce the problem:
  1. Create a webxdc app with `main.js` containing `navigator.serviceWorker.register("/sw.js");` and `sw.js` containing dummy code, e.g. `const a = 1;`.
  2. Launch the app from Delta Chat Android.
- Screenshots:
- Logs:

The same app works as expected on Delta Chat Desktop (since recently, thanks to https://github.com/deltachat/deltachat-desktop/pull/3413). Also the same app works on desktop Chromium with a web server on `localhost`.

`fetch("/sw.js")` succeeds.

Notably the logs don't show a request to `/sw.js` being intercepted (here https://github.com/deltachat/deltachat-android/blob/5c51339ccc14b328864329acfdf59fa89e746a76/src/org/thoughtcrime/securesms/WebxdcActivity.java#L212). It could mean that the browser doesn't make the request itself (due to, say, [some security restrictions](https://w3c.github.io/ServiceWorker/#security-considerations)), or that a service worker file request is supposed to be intercepted in a different way (what is [`ServiceWorkerController`](https://developer.android.com/reference/android/webkit/ServiceWorkerController) ?)

I'll try to rule out the "security restriction" thing and report back.
I can also update the webxdc-test app to test for this.

**Comment by adbenitez** [comment]
it is possible to use workers in fact several of the existing apps in the mini-apps store use them, check SuperBunny's source code for example

**Comment by WofWca** [comment]
The service worker was removed from Super Bunny https://github.com/DeltaZen/super-bunny/commit/2e89748b5738216e8ca2cef73ebaf3c1f23b15b4

I have tried the previous commit, and I see the same behavior, `An unknown error occurred when fetching the script`. Here's the build, with `eruda.js`:

[super-bunny.zip](https://github.com/deltachat/deltachat-android/files/13258991/super-bunny.zip)

**Comment by r10s** [comment]
there is a "song worker" present again, https://github.com/DeltaZen/super-bunny/blob/main/js/game.js .

not sure if that is derived from  a "service worker" or what the differences are and if we aim to support "service workers" at the current stage in general. the solution may also be to document that it is not supported currently.

**Comment by WofWca** [comment]
> not sure if that is derived from a "service worker"

No, this is a regular `Worker`: https://vitejs.dev/guide/features.html#web-workers

**Comment by r10s** [comment]
thanks, no things get clearer.

what is the user visible feature we want to solve with ServiceWorker? i can imagine some usecases when reading through https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API , however, it is not clear to me if that is really an important thing currently that will enable lots of new usecases; maybe there are things with larger impact.

we have quite some API that are not supported by Webxdc, so questions is, if and why we want to support ServiceWorkers currently

**Comment by r10s** [comment]
k, thanks all.

as we're not saying somewhere that we're supporting all possible api in general, nor ServiceWorker in special, i am closing this issue here, there is no actionable item currently.

if needed, a feature proposal can be created at https://support.delta.chat/c/features/6
