### ISSUE TITLE
DC 0.16.0 (514) down with an error after authentication in @yandex.com

### ISSUE THREAD

**Issue by westsibe** [deltachat/deltachat-android#285]
In DC (513) this mail server is OK!

Mail domains there: ya.ru, yandex.ru, yandex.ua, yandex.com, etc.
login(s): login@yandex.com
imap server: imap.yandex.ru
smtp server: smtp.yandex.ru
port and security: automatic.
Error type: unknown (no root / no logcat: logcat is not work.)
App (514 ) down with an error and show(n) Android launcher.
OS: Android 4.4.2 stock, ARMv7a, MTK6582.

**Comment by Hocceruser** [comment]
You can get the logs at 
Settings menu -> About -> version number|Info (in the Delta Chat app).
You do not need root for this. From there you can copy the logs to the clipboard.

**Comment by westsibe** [comment]
Unfortunately it did not happen again on this version of DC. But this problem I seen a 4 times.

**Comment by t-oster** [comment]
@westsibe so this can be closed?

**Comment by r10s** [comment]
closing this, if there are still problems, please reopen.
