### ISSUE TITLE
denying contact's permissions causes freezes

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#286]
Not allowing contacts permission causes delta chat to freeze randomly on incoming messages. 
I've had this bug since at least delta chat .14 I have tested this with and without allowing the contact permission and it appears only when contacts is denied.
But when the freeze happens is random on an incoming message. If I force close the app and restart I get all the messages waiting.

**Comment by r10s** [comment]
see https://github.com/deltachat/deltachat-android/pull/251#issuecomment-377562458

**Comment by nutpantz** [comment]
Now it seems delta chat .16 is freezing on sending mail as well..
I grabbed a log cat. 
There are two messages I sent that did not go though

**Comment by nutpantz** [comment]
---- Apr 4, 2018 8:52:08 PM ----

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:273721878

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

 Launching com.b44t.messenger.beta, updated priority

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

identifyGamePackage. com.b44t.messenger.beta

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

identifyGamePackage. com.b44t.messenger.beta

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560} time:273722591

[background] Process cur broadcast BroadcastRecord{b222973 u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

updateVisibility : ActivityRecord{c721f47 token=android.os.BinderProxy@b58d19b {com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}} show : false

[background] Process cur broadcast BroadcastRecord{345bb5 u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:273819539

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

 Launching com.b44t.messenger.beta, updated priority

identifyGamePackage. com.b44t.messenger.beta

identifyGamePackage. com.b44t.messenger.beta

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560} time:273820331

identifyGamePackage. com.b44t.messenger.beta

[background] Process cur broadcast BroadcastRecord{590cdaa u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

updateVisibility : ActivityRecord{c721f47 token=android.os.BinderProxy@b58d19b {com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}} show : false

---- Apr 4, 2018 8:52:08 PM ----

**Comment by nutpantz** [comment]
Here is the log cat including my force closing it and restarting where it send and received messages that were frozen



---- Apr 4, 2018 8:55:49 PM ----

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:273721878

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

 Launching com.b44t.messenger.beta, updated priority

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

identifyGamePackage. com.b44t.messenger.beta

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

identifyGamePackage. com.b44t.messenger.beta

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560} time:273722591

[background] Process cur broadcast BroadcastRecord{b222973 u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

updateVisibility : ActivityRecord{c721f47 token=android.os.BinderProxy@b58d19b {com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}} show : false

[background] Process cur broadcast BroadcastRecord{345bb5 u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:273819539

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

 Launching com.b44t.messenger.beta, updated priority

identifyGamePackage. com.b44t.messenger.beta

identifyGamePackage. com.b44t.messenger.beta

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560} time:273820331

identifyGamePackage. com.b44t.messenger.beta

[background] Process cur broadcast BroadcastRecord{590cdaa u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

updateVisibility : ActivityRecord{c721f47 token=android.os.BinderProxy@b58d19b {com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}} show : false

[background] Process cur broadcast BroadcastRecord{fc11ba0 u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:273934108

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

 Launching com.b44t.messenger.beta, updated priority

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

identifyGamePackage. com.b44t.messenger.beta

identifyGamePackage. com.b44t.messenger.beta

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560} time:273934864

updateVisibility : ActivityRecord{c721f47 token=android.os.BinderProxy@b58d19b {com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}} show : false

[background] Process cur broadcast BroadcastRecord{319a15f u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

[background] Process cur broadcast BroadcastRecord{ffd4a47 u0 null qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{821eb27 20211:com.b44t.messenger.beta/u0a51}

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:274074271

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

 Launching com.b44t.messenger.beta, updated priority

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

identifyGamePackage. com.b44t.messenger.beta

identifyGamePackage. com.b44t.messenger.beta

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

manageDisableList userId=0 what=0x0 pkg=Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

Finishing drawing window Window{3608476 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

Timeline: Activity_windows_visible id: ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560} time:274075016

[libsuperuser][C][SU+] am force-stop com.b44t.messenger.beta

Force stopping com.b44t.messenger.beta appid=10051 user=0: from pid 21636

Killing 20211:com.b44t.messenger.beta/u0a51 (adj 0): stop com.b44t.messenger.beta cause from pid 21636

isAutoRunBlockedApp:: com.b44t.messenger.beta, Auto Run ON

Scheduling restart of crashed service com.b44t.messenger.beta/com.b44t.messenger.KeepAliveService in 1000ms

Force removing ActivityRecord{fc23054 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11560}: app died, no saved state

  Force stopping service ServiceRecord{56f5052 u0 com.b44t.messenger.beta/com.b44t.messenger.KeepAliveService}

Remove alarm for next reason : android.intent.action.PACKAGE_RESTARTED : package: com.b44t.messenger.beta

Timeline: Activity_launch_request id:com.b44t.messenger.beta time:274082376

identifyGamePackage. com.b44t.messenger.beta

Gamemode - return 0,  when calling  identifyForegroundApp(com.b44t.messenger.beta)

addAppToken: AppWindowToken{6ff1fd0 token=Token{ea32393 ActivityRecord{3b7a082 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11566}}} to stack=1 task=11566 at 0

InputChannelName : a48518a Starting com.b44t.messenger.beta

Finishing drawing window Window{a48518a u0 d0 Starting com.b44t.messenger.beta}: mDrawState=DRAW_PENDING

Start proc 21665:com.b44t.messenger.beta/u0a51 for activity com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity

SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.b44t.messenger.beta 

 Launching com.b44t.messenger.beta, updated priority

NotifyRunnable. pkg: com.b44t.messenger.beta, type: 4, isMinimized: false, isTunableApp: false

manageDisableList userId=0 what=0x0 pkg=Window{a48518a u0 d0 Starting com.b44t.messenger.beta}

identifyGamePackage. com.b44t.messenger.beta

identifyGamePackage. com.b44t.messenger.beta

Hooking package=com.b44t.messenger.beta

T1: Opened "/data/user/0/com.b44t.messenger.beta/files/messenger.db" successfully.

InputChannelName : 741b3f4 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity

isStatusBarNotificationAllowedAsUser: packageName = com.b44t.messenger.beta,userId = 0

manageDisableList userId=0 what=0x0 pkg=Window{741b3f4 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}

DTS_GLAPI : DTS is not allowed for Package : com.b44t.messenger.beta

Finishing drawing window Window{741b3f4 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=DRAW_PENDING

Displayed com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity: +1s38ms (total +2m2s161ms)

Timeline: Activity_windows_visible id: ActivityRecord{3b7a082 u0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity t11566} time:274083573

packageName: com.b44t.messenger.beta, className: com.b44t.messenger.LaunchActivity, count: 0

Finishing drawing window Window{741b3f4 u0 d0 com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}: mDrawState=HAS_DRAWN

onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity} 0

isStatusBarNotificationAllowedAsUser: packageName = com.b44t.messenger.beta,userId = 0

 remove PendingIntent] PendingIntent{dc75cea: PendingIntentRecord{705ca40 com.b44t.messenger.beta startService}}

Turning on edge light for notification (NotificationRecord(0x032e0bdb: pkg=com.b44t.messenger.beta user=UserHandle{0} id=1 tag=null score=0 key=0|com.b44t.messenger.beta|1|null|10051: Notification(pri=0 contentView=null vibrate=default sound=content://settings/system/notification_sound tick defaults=0x2 flags=0x211 color=0xff415e6b category=msg groupKey=messages vis=PRIVATE secFlags=0x0 secPriority=0))) with color=ffffffff

packageName: com.b44t.messenger.beta, className: com.b44t.messenger.LaunchActivity, count: 1

onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity} 1

Received android.intent.action.BADGE_COUNT_UPDATE com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity for wrong type (Notification)

packageName: com.b44t.messenger.beta, className: com.b44t.messenger.LaunchActivity, count: 0

onReceive: android.intent.action.BADGE_COUNT_UPDATE ComponentTag{com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity} 0

updateVisibility : ActivityRecord{5859fb7 token=android.os.BinderProxy@b58d19b {com.b44t.messenger.beta/com.b44t.messenger.LaunchActivity}} show : false

---- Apr 4, 2018 8:55:50 PM ----

**Comment by nutpantz** [comment]
Hope the log cat helps fix the freezing. I think it's getting worse

**Comment by r10s** [comment]
so, in general, it seems it is not related to contacts permissions?

**Comment by nutpantz** [comment]
When I was testing delta chat .14 and before it never froze for me when I had contacts allowed. And freezes were maybe once a week.  I only had .15 installed a few days before I upgraded to   .16   now it freezes everyday and I can't say for sure what is causing it. 
The permissions I have allowed are microphone and storage.

**Comment by nutpantz** [comment]
It's getting a lot worse it's freezing up outgoing and incoming a lot more often now. I have to force close the app regularly to check is mail is stuck incoming and have to watch the icon with every send to make sure it went.

**Comment by testbird** [comment]
Just to make sure, do you have enough free storage space, and are the messages (audio/video?) not exceeding any size limits? Have you tried a clean reinstall (only re-importing the key, not the database)?

**Comment by nutpantz** [comment]
I have gigabytes free, and I have tried reinstall just importing the key. Only

**Comment by nutpantz** [comment]
Not sure is this is important, but delta chat seems to miss a number of read receipts.  And does not mark messages read in the mail box sometimes for a few minutes after it's read.

**Comment by testbird** [comment]
> delta chat seems to miss a number of read receipts

https://github.com/deltachat/deltachat-core/issues/68

**Comment by nutpantz** [comment]
First time I noticed this. Delta chat got a dinged with a new message after it was sitting in my in box for 45 minutes. Bit of a lag there that might be related to the freezing

**Comment by testbird** [comment]
> got a dinged with

wobba da whot tap?

**Comment by testbird** [comment]
@nutpantz The search found BADGE_COUNT_UPDATE in your log, do you have badges working? 
See https://github.com/deltachat/deltachat-android/issues/340.

**Comment by nutpantz** [comment]
Badges ate enabled on nova launcher and they seem to work fine. I'll disable them and see if it makes any difference and report back.

**Comment by nutpantz** [comment]
I updated to 18.2 and disabled badges for delta crypt, it still froze up today.  I'll try disabling badges for all apps in nova launcher and see if that makes and difference.

**Comment by nutpantz** [comment]
@testbird
Ok I disabled badges completely (uninstalled teslaunread for nova launcher) and so far today is the first time I have gone all day without having to force close delta chat. It has not froze today.. Let's see how tomorrow goes. I'll report back again.

**Comment by testbird** [comment]
Nice! If it turns out the freezes are related to the badge support, could you tell your brand?

The freezes I've heard from where on samsung, likely with their default launcher (not sure).

**Comment by nutpantz** [comment]
I should mention I use nova launcher and tesla unread for badges. Or I did.

**Comment by testbird** [comment]
So, to summarize, the random freezes only occur if **both** are true at the same time?:

1) Badge support installed (here, nova laucher with tesla unread), even if the displaying of badges is disabled.
1) Contact's permission for deltachat denied.

If that's the case, you could add this to your bug report above, and change the title to "w/ badge support: denying contact's permission causes freezes".

**Comment by nutpantz** [comment]
Originally(back with delta chat 15) I did not have badge support installed. I had random freezes with just contacts blocked.
I'm testing now to see if delta chat still freezes up with just contacts blocked.  So I'll leave it for now and continue testing. Then I'll report back. Badges defiantly cause freeze ups, but badges might be separate.

**Comment by nutpantz** [comment]
Yep it is still freezing. Had to force close today and restart it to get my messages. No badges installed. Phone and contacts are denied.
