### ISSUE TITLE
feature request: microphone volume

### ISSUE THREAD

**Issue by MellowVoidUser** [deltachat/deltachat-android#287]
For some reason not known the recording volume level on deltachat and on whatsapp is much lower then in a normal phonecall which makes it unusable. A great feature would be to add a mic-volume-level-setting! Maybe even select which mic (front, back, extra1, extra2) should be used.
It would be great!

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
