### ISSUE TITLE
After backup restore, 1:1 chat name overridden manually (by user) before changes to name of corresponding email contact in Android address book when message from respective contact is received

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2871]
- Android version:
Android 12.

- Device:
Google Pixel 3a (sargo).

- Delta Chat version:
1.42.1.

- Expected behavior:
A manually (by the user) applied name for a 1:1 chat does not change after a backup is restored, and after a message from a contact who is assigned to that chat is received.

- Actual behavior:
A manually (by the user) applied name for a 1:1 chat changes after a backup is restored, and after a message from a contact who is assigned to that chat is received.

- Steps to reproduce the problem:
-- Run a previous version (e.g. 1.40.1) of Delta Chat.
-- Ensure that your Android address book includes a contact (e.g. `Alice C.`) with an email address that corresponds to a 1:1 chat in Delta Chat.
-- Rename the corresponding 1:1 chat in Delta Chat (e.g. from `Alice C.` to `Alice Cooper`).
-- Create a complete backup of your account, chats, and media.
-- Go to Android settings and clear the cache and storage that are applied to Delta Chat.
-- Uninstall Delta Chat.
-- Install Delta Chat version 1.42.1.
-- Restore the backup which you created before.
-- Receive a message from the contact whose 1:1 chat name you changed before. (Result: The name of the corresponding 1:1 chat has changed from `Alice Cooper` to `Alice C.`.)

- Screenshots:
N/A.

- Logs:
[deltachat-log-20231117-084832_2.txt](https://github.com/deltachat/deltachat-android/files/13390958/deltachat-log-20231117-084832_2.txt)

**Comment by r10s** [comment]
while trying to reproduce the issue, there is a more general bug even sooner:

- when creating a chat with a user from the system address book (i added "Alice C." with `alicec123@nine.testrun.org` to the system address book as instructed), the name is not taken - instead name and address set to `alicec123@nine.testrun.org` 

interestingly, when then trying to create the same chat again the same way (which will just open the existing chat), the name is set correctly


the following screencast is from 1.40.0:
https://github.com/deltachat/deltachat-android/assets/9800740/905cd455-2fa1-4931-af8e-8c0c40eba179

**Comment by gerryfrancis** [comment]
@r10s Looks like the email address is displayed every time the contact name is not applied, or chat name = NULL for whatever reason.

**Comment by adbenitez** [comment]
I am not sure this is 100% a bug, if you have a name set in phone contacts that should be used and if you want to change it you should change it there, setting the name in delta chat is mainly for the contacts you don't have in your address book :thinking:

**Comment by gerryfrancis** [comment]
@adbenitez Although I agree with your point that contact names should be changed in the Android address book, there might be reasons why someone changes them in the app itself, and that these names should be maintained as overrides, otherwise it would not make much sense to let the user edit names for contacts who have already been read from the address book.

But hey, I think the APK from the PR seems to solve the issue, I need to test it on the device of my mate who experienced the problem. Will keep you updated... :)
