### ISSUE TITLE
Sharing videos from any app to Delta does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#288]
"Sharing" videos from Whatsapp to Delta Chat seems not to work. "Sharing" in this sense does not mean sending a message but sharing through Android Intents.

Sharing from Whatsapp to Conversations seems to work.

I was reported about this issue today via mail; i have not tested this myself. Maybe anyone who has WA can confirm? and probably fix?

**Comment by Two-Finger** [comment]
I can only confirm - once I selected the Delta Chat contact to send the message to, the conversation opened, and a toast with "Unknown error" was briefly displayed.

This is not WhatsApp-specific, I got the same error when sharing a video from my stock file manager too.

**Comment by r10s** [comment]
@Two-Finger intersting, thank you very much. sharing text or images works for you?

**Comment by Ji-eF** [comment]
Selecting a video from my gallery > Share with > Delta Chat also gives me unknown error.

**Comment by Ji-eF** [comment]
If anything, I also did not succeeded sharing a contact from my Contact list, with the error 'Errorneous email address"

**Comment by Two-Finger** [comment]
@r10s Images work fine, yes.

As for text, I'm not sure what that means. At least WhatsApp didn't offer me any Share button when I selected a message.

**Comment by r10s** [comment]
@Two-Finger thanks for figuring things out :)

**Comment by Hocceruser** [comment]
Actually, for me, sending videos did not work at all, neither by sharing it to DC nor by selecting "Video" in the attachment dialog. 

When trying to share a video, it says "Delta Chat has stopped"; when selecting "Video" the attachment dialog disappears and nothing happens.

**Comment by Hocceruser** [comment]
Now I'm completely confused. The video I tried to share to Delta Chat was only less than a second long. With longer videos it seems to work. 
However, when I try to select `attachment -> video` nothing happens still.

**Comment by r10s** [comment]
this issue is not longer valid for 0.100.0 as videos are not yet re-implemeted at all.
