### ISSUE TITLE
location sharing: position of contact is not shown

### ISSUE THREAD

**Issue by IeP4nieF** [deltachat/deltachat-android#2901]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.41.4 (git: v1.33.0-542-g5f802c94)
- Expected behavior: location of contact is show (if the location is shared by the contact)
- Actual behavior: nothing is shown on the chart
- Steps to reproduce the problem: let a contact share the location and look at the chart

best regards

**Comment by Simon-Laux** [comment]
I suspect the location is not send then, I moved the issue to the android repo.

**Comment by IeP4nieF** [comment]
> > How can I remove the POI?
> 
> you can delete it's message

Thank you for the hint. It worked!

But I would say their should be an easy option somewhere to delete the POIs. In my case I had a old one which I didn't remember. It was possible to find the related chat, because I had very few chats and messages. If there is a normal amount of messages you have to search forever... (This is more a feature request, then a bug.)

**Comment by IeP4nieF** [comment]
> I suspect the location is not send then [...]

Any hint on how to debug this?

**Comment by hpk42** [comment]
On Mon, Dec 04, 2023 at 21:54 -0800, IeP4nieF wrote:
> > I suspect the location is not send then [...]
> 
> Any hint on how to debug this?

Did your contact turn on location-streaming?  Could you share a screenshot
after location-streaming was enabled on Android? 

Note that location-streaming is currently not a primary development 
area but nevertheless we can try to resolve your issue at hand.

**Comment by adbenitez** [comment]
I don't understand, can you clarify:

does the location sharing work from Android to Android? is the problem only from Android to Desktop?

**Comment by Simon-Laux** [comment]
> But I would say their should be an easy option somewhere to delete the POIs. In my case I had an old one which I didn't remember. It was possible to find the related chat, because I had very few chats and messages. If there is a normal amount of messages you have to search forever... (This is more a feature request, than a bug.)

@IeP4nieF please make a feature proposal in the forum if you want this (https://support.delta.chat)


> is the problem only from Android to Desktop?

as far as I understand this, no. otherwise I would not have moved the issue here. it's either dc-android or dc-core. but would be useful if the bug reporter could provide more information so we can reproduce and better debug this.

**Comment by r10s** [comment]
closing stale issue. i do not doubt, there are bugs, however there is no actionable item - in general, at bb33, we've just managed to share locations and tracks between devices.

if needed, please file a new issue with more details to reproduce the issue
