### ISSUE TITLE
Changing "+" icon in circle

### ISSUE THREAD

**Issue by westsibe** [deltachat/deltachat-android#291]
![screenshot_24](https://user-images.githubusercontent.com/29564089/38461453-ea545db6-3abf-11e8-9973-38e824fec7d9.png)

May be better in this variant?

![floating_pencil](https://user-images.githubusercontent.com/29564089/38461465-3a695216-3ac0-11e8-87b5-abb3f75a67a0.png)
^ New floating_pencil.png for hdpi/xhdpi.

![floating_pencil](https://user-images.githubusercontent.com/29564089/38549464-959db6ec-3ca3-11e8-90ed-1715c24f8622.png)
^ Old floating_pencil.png

**Comment by testbird** [comment]
The round icons could even have that deltachat buble design.

![](https://delta.chat/assets/home/intro1.png)

**Comment by r10s** [comment]
cmp https://github.com/deltachat/deltachat-android-ii/issues/107
