### ISSUE TITLE
focus on setting up contacts in initial device message

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2914]
the "device messages" chat is one of the few things that are present after "instant onboarding" (eg. via QR code scan on https://nine.testrun.org, maybe later in-app)

currently, the "welcome" messages shows some general hints, idea is to write down the most interesting thing for new users, how to get in contact with others (that are maybe sitting just next to me) - so, eg. 
- an image of two phones scanning each others QR code (needs to be changed in core iirc)
- a describing text about how to scan QR codes (cmp. [desktop/#3623](https://github.com/deltachat/deltachat-desktop/issues/3623) wrt streamlining) (can be changed on android)
- maybe show own QR code in device messages and/or allow opening the corresponding dialog via a tap/link
- to reduce noise in device chat, it is also questionable to show the "Changelog" also on initial installations (on real updates, however, it is cool)

desktop already opens the "device messages" after installations, so that should be mostly fine.
for android/ios, there is the additional idea to use space on the chatlist for additional hints, but i'd say, this is another issue, and it also depends on how good the updated device message already works (would be nice, if eg. already in the chatlist the summary "How to get in contact ... " or so is shown) 

(once this is settled here and in core, we have to check if desktop/ios needs adaptions or if just strings/core is updated)

current, a bit outdated device message:

<img width=320 src=https://github.com/deltachat/deltachat-android/assets/9800740/ddca23ae-abf0-49d7-a72c-bacd09abe69f>

nb: maybe the name "Device Messages" is also a bit cumbersome and buerocratic and sth. as "Hints" or "Notes" or just "Info" is better

**Comment by adbenitez** [comment]
> * to reduce noise in device chat, it is also questionable to show the "Changelog" also on initial installations (on real updates, however, it is cool)

+100 it is rather confusing for first installations to get some message about "what is new" and it clutters the device chat, also a message about enabling disabling background optimizations will appear so the chat so too much is going on for an user that just logged in

**Comment by adbenitez** [comment]
> and sth. as "Hints" or "Notes" or just "Info" is better

If it needs to be changed, from that options Info is my favorite and it fits better with the (i) icon that chat has
