### ISSUE TITLE
offering email-addresses from the system's address book is not helpful for chatmail

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2915]
currently, the app adds all email-addresses from the system's address book to the "New Chat" dialog.

in case of chatmail, that requires encryption for foreign addresses, however, most of these addresses cannot be written to easily.

offering these addresses on case of chatmail even harms UX as it raises false expectations.

we should somehow not add these addresses. question is if we stop adding them in general or only for chatmail (however, currenlty, we do not know if self-address is chatmail or not) and/or offer a way to add them manually. are these addresses are really a thing? eg. desktop never scanned the address book, arguably, there is no common address book on desktop as for android/ios

in any way, once we found a solution here, we should do the same on ios.

**Comment by devSJR** [comment]
Maybe I misunderstood this. A popup asking the user ''Wanna add to address book''? would not do the trick?

**Comment by adbenitez** [comment]
if it is chatmail it will not work

**Comment by adbenitez** [comment]
the simpler solution is to not import from address book, to be honest I never used the phone contacts to manage email addresses, but for phone numbers, I guess removing it affects the "user that use DC to chat unencrypted with non-DC contacts" use case, anyway I don't think that use case is more important than encrypted chatmail usage, and they can always look in the address book and from there start the chat with the contact the first time

**Comment by Simon-Laux** [comment]
Not sure removing it completely is the right way, as you might have synced your contacts with your other email program on all your devices, so while you don't have email addresses in your contact app as a pure phone user, users that sync their contacts with their computer or email provider will more likely have email addresses in there.

Maybe rather change it to an opt in option -> button in settings or at end of contact list: "turn on importing contacts from system address book" or "import contacts from system address book"
