### ISSUE TITLE
Another Delta Chat in Google Play?

### ISSUE THREAD

**Issue by drcicero** [deltachat/deltachat-android#292]
I just wanted to recommend delta chat to someone and noticed, that there is another Delta Chat in the Google Play Store.

According to #214 and #110 you eventually intend to publish to Play, too. However, I do not think [1] is this delta chat, because the screenshots look different. Having such a Delta Chat on Play will at very least confuse people that search for Delta Chat because they got it recommended by someone. In Play you can see that this other app was published 31.03.2018 ...

(If you are looking for this this publishing date, note that I could not find it on the Play website. It seems the publishing date of an app is only visible when you click on the description text in the Play App.)

[1] https://play.google.com/store/apps/details?id=com.sleepingteam.nonstopchat
"Delta chat - Secure code chat (Beta)"

**Comment by r10s** [comment]
hm, thank you for the hint. this app is not related in any way to out Delta Chat.

**Comment by r10s** [comment]
@Hocceruser yes, i have written a friendly mail to them. let's see what happens, might be that they just did not know that there is already an "Delta Chat".

**Comment by webratte** [comment]
The linked app seems to have a new name.
And Delta Chat is now unic again ;-)

**Comment by testbird** [comment]
> wondering if it makes sense to add at least a beta-version to the play store

I'd agree. Just make extra sure to clearly state that the current beta is still only usable for a very small fraction of IMAP-provider/use-case combinations, and even where it is usable still has inconveniences like disturbing messages,  missing warnings and manual clean-up tasks.

**Comment by testbird** [comment]
OTOH don't underestimate the benefits of a truly usable first publication, with the basic things really working.

So, a pre-app could maybe  just mention f-droid.

**Comment by testbird** [comment]
Just got a another message of a frustrated user, uninstalling. Getting unreadable emails and receipts for every message in deltachat to manually delete in your email program is... unbearable. (Standard national telecom email account that does not allow subfolders in root. Deltachat not usable just for chats (account shared with parallel classic email client (MUAs).)

https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy
https://github.com/deltachat/deltachat-core/wiki/Use-Cases

**Comment by r10s** [comment]
well, seems as if our decision not to release a 1.0 is correct :)

**Comment by testbird** [comment]
With the 0.17 lab version out, it would be good if you could find the time to fix the rather basic issues before working or fixing newer/advanced features.
