### ISSUE TITLE
global badge counter in self-avatar

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#2921]
a badge counter in self-avatar in the main screen (chatlist) to know how many unread messages there are in other accounts

one could argue that it is not a vital feature since there is already multi-account notifications, but with the tentative of allowing to disable notifications for background accounts, a badge counter would be a less disruptive way to notice new messages

**Comment by adbenitez** [comment]
currently the event center works in a selected-account-only approach, instead of receiving all events and discarding if the account-ID is for a different account

processing events for all accounts is necessary to be able to react and update the badge counter when an incoming message event is received in another account

**Comment by r10s** [comment]
> currently the event center works in a selected-account-only approach, instead of letting the listener to receive all events and discard if the account-ID is for a different account

looking at the [DcEventCenter code](https://github.com/deltachat/deltachat-android/blob/main/src/org/thoughtcrime/securesms/connect/DcEventCenter.java#L144), `DC_EVENT_INCOMING_MSG` is already passed unconditionally for all accounts to `addNotification()`.

we could either add the badge logic at `addNotification()` - or we could emit a special event as DC_EVENT_INCOMING_MSG_ANY_ACCOUNT that any object can listen to (the latter is what we're doing on iOS)
