### ISSUE TITLE
Reaction bar reappears after image to send is selected/attached _and_ vertically cropped

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2929]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.211001.001 bfa3c18745 from 2024-01-12).

- Delta Chat version:
1.42.6 (nightly built on 2024-01-19).

- Expected behavior:
After a message has been marked, the reaction bar should not reappear when an image to send is selected/attached _and_ vertically cropped.

- Actual behavior:
After a message has been marked, the reaction bar reappears when an image to send is selected/attached _and_ vertically cropped..

- Steps to reproduce the problem:
-- Open a chat.
-- Mark any message.
-- Tap the "attach" (paper clip) button, and choose any image from the gallery.
-- Crop that image vertically to a very small height. (Result: The reaction bar has reappeared for the marked message.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
did not try out, but that may be on purpose - if sth else than a reaction is initiated by the user, the reaction bar gives way.
so: long tap and then reaction - or reaction bar disappears on other taps

**Comment by gerryfrancis** [comment]
@r10s Thank you for explaining. Funny thing is that when I perform the steps described above, then add editing the image to vertically crop it to a very small height, the reaction bar for the marked message reappears all of a sudden while it should not? Hmm...

**Comment by gerryfrancis** [comment]
@r10s Reopening here, please consider my comment before. ;)
