### ISSUE TITLE
cleanup of contacts

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#294]
Due to a incomplete or not customized list of folders to ingnore, the contact list can grow into a very large list of unwanted and unknown addresses (from spam mails etc).

It seems there already is an internal function to clean up the contacts (https://github.com/deltachat/deltachat-core/blob/74ca467da1c638882dd4e3772ad6ffd17b1fddfb/cmdline/cmdline.c#L86) but it ist not accessible from the UI.

Could you please make the "cleanup unused" function available in the menu of the contact list?

**Comment by testbird** [comment]
The github search seems to only return references unclear to me. Can the contact cleanup function be called from the ui with some dot notation?

**Comment by testbird** [comment]
Thank you for the advice! What a relieve to get rid of the junk addresses.

It's an important function to have.

**Comment by r10s** [comment]
in fact, a cleanup will be available in android-dev
