### ISSUE TITLE
Consider setting `hasFragileUserData`

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2941]
I have noticed that some app that I recently removed (IIRC Element) offered to keep the data when I was uninstalling it.
I did it on Android 10.

Seems it is possible to trigger this with a manifest setting https://developer.android.com/reference/android/R.attr#hasFragileUserData

Should we enable it as well? This may prevent some users accidentally removing their data when they just want to switch versions or something like this and assume data is not removed. For example here is a thread from someone trying to downgrade and removing the data: https://support.delta.chat/t/how-to-recover-all-chats-after-dc-reinstallation/2686

**Comment by adbenitez** [comment]
I tried this, on two devices:

Xiaomi with android 13: it didn't offered to keep the data, after reinstall all was gone

CalyxOS with android 14: it offered to keep data, after installing again the app opens directly as it was not uninstalled, the account was preserved
