### ISSUE TITLE
Add info buttons

### ISSUE THREAD

**Issue by jidanni** [deltachat/deltachat-android#2944]
Add info buttons. For instance at the after we install the app there are several choices that show up. Each one should have an info button explaining what the choice is all about.

Okay now we've chosen the first choice. At the top it's asking us for an existing password. An info button would say if this password is an account password for a Delta chat account. For instance if we were supposed to sign up or something. Or if it's for our email account.

Okay at the top you collect our email address and our password. But I don't see how you're going to log into something to use it. So the user assumes it's sort of a club membership to the Delta chat club.

Okay we open up the advanced options and we fill in all our SMTP, and IMAP information, including passwords.

That should be all you need to know to get and send emails. So I don't see why we cannot proceed without going back to the top and filling in our email address and password. Particularly the password. Don't you already have our password in the IMAP and SMTP fields? So what could it possibly be for at the very top of the form also?

Asking for I email address makes sense because that's what we would like to send our emails as so people can reply to us with it. But asking for the password especially after we already filled in the SMTP and IMAP details, just doesn't make sense.

In fact this is quite sensitive piece of information that could be used to hijack bank accounts etc. I don't think you should be that carefree about it.

**Comment by r10s** [comment]
let's move discussion about that to the [forum](https://support.delta.chat), that is better fitting as this is (a) mostly a feature proposal and (b) affects not only android but also desktop/ios/ubuntu-touch

you can log in in the support forum using your github account and just copy+paste the text
