### ISSUE TITLE
Why not get all the messages via IMAP?

### ISSUE THREAD

**Issue by jidanni** [deltachat/deltachat-android#2945]
The user installs the app. User fills in is IMAP details. No error is reported. However the user does not see his 25 emails that are sitting on his IMAP server. Therefore there must be some kind of lack of understanding on my part of what this app is supposed to do.

**Comment by hpk42** [comment]
On Tue, Jan 30, 2024 at 00:35 -0800, 積丹尼 Dan Jacobson wrote:
> The user installs the app. User fills in is IMAP details. No error is reported. However the user does not see his 25 emails that are sitting on his IMAP server. Therefore there must be some kind of lack of understanding on my part of what this app is supposed to do.

only new e-mail will show in Delta Chat. 
There is no fetching of history (or showing the INBOX's folder content).

**Comment by r10s** [comment]
for discussions about  feature requests, please refer to the forum (you can log in via your github account there), eg. https://support.delta.chat/t/have-an-option-to-download-chat-from-server/1952 or create a new topic

closing this issue as it is the expected behaviour, however, maybe we can make things a bit clearer in the UI, esp. below "Show All E-Mails" we could add a hint "This affects only new messages. Legacy messages are not downloaded."

**Comment by jidanni** [comment]
I think I figured it out by myself too. The typical Gmail user has thousands of messages on the server. Therefore the app needs to start fresh only for new messages.

However for  traditional people who keep tidy upstream places, it's very confusing behavior. I guess we're in the minority these days so everybody expects the current behavior is normal though.

**Comment by hpk42** [comment]
On Tue, Jan 30, 2024 at 14:42 -0800, 積丹尼 Dan Jacobson wrote:
> I think I figured it out by myself too. The typical Gmail user has thousands of messages on the server. Therefore the app needs to start fresh only for new messages.

It also has to do with history: delta chat started as "you can use it next to your email app" 
and kept chat messages and regular email separate. 
The support for using Delta chat as a regular email client has been improving,
as mailing lists and many other little things were better supported. 
Today, there are users with dedicated chatmail address 
and also many who co-use delta chat with another email app/webinterface
and either use the now default "all email" setting or the "only chat messages" one. 

Any move towards downloading historic messages during onboarding 
will need to think about these differences in usage/perspectives/wants
and come up with a nice UI/UX around it. 
It's a recurring topic and likely to get addressed one way or another at some point.
