### ISSUE TITLE
App freeze for seconds when doing text search in chat list

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#296]
**v0.16.0**

When using search function the app freezes for several seconds after typing each new character into the search field.
I suspect that this is related to a meanwhile big database (> 500MB) at my device now.
It seems that DC does a new full search immediately after typing every next character.

The result of this approach is, the more the database grows the worse the app responses!

My recommendation is:  to change search approach in that way that searching is started only when search button is pushed, not after each typed character!

**Comment by r10s** [comment]
on my test devices, searching is "fast enough". can you have a look at the log, since some time, we log the number of nanoseconds required to create the view.

**Comment by csb0730** [comment]
Hi r10s,
to make the issue more clear: I speak about the search function in the chatlist (main screen), not the text search into a chat.

The log shows lines like:
"hh:mm:ss T1: Message list for search "xyz" in chat #0 created in **2553.640 ms**."
"hh:mm:ss T1: Chatlist created in 49.225 ms"

These are typical timings.

You have to see that these 2553 ms delay are for **every** key stroke in search field and
makes the app feeling very unresponsive.

Use case for that function is:
If I need to send a message quickly to a contact which is stashed in the chat list between many other chats (current data from log: number of chats: 71, number of messages 2454).

**Comment by r10s** [comment]
okay, these are helpful numbers, thanks.
how many messages do you have in the database (see Settings / About Info), I have about 7000 messages and the message list is always created in ~120 ms on my old Nexus 4, so I never thought this is a problem.

a little summary about what is going on:
- typing characters result in an java call to [ChatlistActivity::doSearch()](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/ChatlistActivity.java#L1181) which calls two search functions in the core: [mrmailbox_get_chatlist()](https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox.c#L841) (logs "Chatlist created") and [mrmailbox_search_msgs()](https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox.c#L1500) (logs "Message list created")
- getting the chatlist seems to be fast enough
- getting the messages is slower (also on my device)

how can we speed up things?
- we can try to optimize the sqlite part in the core (there are some comments about possible optionns in the code around [mrmailbox_search_msgs()](https://github.com/deltachat/deltachat-core/blob/master/src/mrmailbox.c#L1500)), however, this might be tricky - and even if we gain 50% it seems to be still too slow for some machines
- **better:** we could put the core search function to a thread, in fact, we also do this already for the in-chat search function - if we do not wait for both search functions to finish but show the result directly after the chatlist result, the response should be close to instant also on slow machines.

**Comment by r10s** [comment]
the "better" part from above would may work in this way: a new search would not be started until the previous search is done. instead a flag could be set that indicates that there are pending searches.

**Comment by csb0730** [comment]
But I think start 1st search with 2nd char typed would make sense (?).
If You type only first character and search that single one quite every message will give You a match !

**Comment by csb0730** [comment]
@r10s - this is targeted by new version, but not solved.
