### ISSUE TITLE
Option to temporarily go offline

### ISSUE THREAD

**Issue by annando** [deltachat/deltachat-android#297]
it seems as if Delta Chat is draining battery power under certain circumstances like a flaky internet connection (for example when traveling by train).

Since my phone isn't that powerful, I sometimes temporarily deactivate my XMPP accounts in "Conversation" and would like to do so in "Delta Chat" as well.

So I really would like an option in Delta Chat to simply go offline. Especially under circumstances where the internet is very bad (means: Most of the places in Germany with O2 as provider), this would help, since communication wouldn't be possible at all.

**Comment by annando** [comment]
@testbird sorry. Although I searched for related issues, I hadn't found that one since it used all the words, I hadn't used ;-)

**Comment by annando** [comment]
it seems that most applications don't have a problem with bad internet connections, so that would be some very drastic solution. And this automatic reconnect you suggested doesn't help when the connection is there every few minutes and then disappears again.

I do understand your concern, but sometimes manual switches can be a better solution than some automatic.

**Comment by testbird** [comment]
If you only notice a problem with deltachat, then there should be a working solution for it, just as in other apps.

If you are technically inclined, you could try out the "cheat codes" as a workaround, maybe `.auth <password>` `.disconect`. But I don't know, only discovered them lately, see https://github.com/deltachat/deltachat-android/issues/215

**Comment by csb0730** [comment]
Maybe off topic, but:

Is there a summary of all commands which are possible? Wiki?

**Comment by r10s** [comment]
@csb0730 you can type `.help` into the "My name" name field or see the code here: https://github.com/deltachat/deltachat-core/blob/master/cmdline/cmdline.c#L428 - however, I think these cheat codes will be removed sooner or later, see https://github.com/deltachat/deltachat-android/issues/215

**Comment by r10s** [comment]
btw. did not forgot the uuencode stuff, i think i will find some time for it tomorrow or or tuesday.

**Comment by r10s** [comment]
as the core of this issue seems to be saving battery, i think this issue can be closed together with #269 

for an option to exit the app, there is still #253 open
