### ISSUE TITLE
Get rid of `FileUtils.getFileDescriptorOwner`

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2975]
getFileDescriptorOwner is the last piece of native JNI code taken from Signal. Signal itself does not use it anymore as the last call to it was removed in https://github.com/signalapp/Signal-Android/commit/9bac88697b25f0ca4ae1104129bc5f1649579eb0
That commit is under GPLv3+ and not AGPL so we can take whatever changes are needed from there.

This `getFileDescriptorOwner` in `jni/utils` blocks moving JNI code to a separate package. Once it is done we can revive https://github.com/angelo-fuchs/dc-jni-playground and resolve https://github.com/deltachat-bot/echo/issues/9

Moving JNI code to a separate package will make it possible to upload prebuilds to Maven Central so Android developers and F-Droid will only need to run Gradle to build Delta Chat.

**Comment by r10s** [comment]
did some research: the function was introduced in 2016 at https://github.com/signalapp/Signal-Android/commit/f2b81d88ba57b9a76ca1b8976435c92db296761f to fix https://github.com/signalapp/Signal-Android/issues/5381
