### ISSUE TITLE
Pull metadata and changelog translations from weblate

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#2990]
Weblate has a project for metadata translations at https://translate.codeberg.org/projects/delta-chat/android-metadata/

Weblate pulls original text from the git repository already, but translations need to be pulled back to this repository now.

Related forum thread: https://support.delta.chat/t/were-to-translate-android-app-metadata/3008/3

**Comment by r10s** [comment]
imu, weblate now always creates PR with the changes, so, there is no need for pulling metadata anymore.
