### ISSUE TITLE
New "Instant Onboarding" UX flow to create accounts

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#2996]
once https://github.com/deltachat/deltachat-desktop/pull/3773 and https://github.com/deltachat/deltachat-android/issues/2995 are settled, instant onboarding can be done for android as well

in case someone is in idle, before, #2994 can be targeted already

counterpart of https://github.com/deltachat/deltachat-ios/issues/2156

**Comment by r10s** [comment]
more concrete, roughly the following steps are required to get onboarding on default server ready:

1. in `WelcomeActivity`,

    1. move secondary buttons ("Log into your E-Mail Account", "Add as Second Device") and tertiary buttons  ("Restore from Backup") to a new `AlertDialog` (using setItems(), see eg. MuteDialog for an example). this new dialog is started by the new secondary button "I Already Have a Login"  
as we did not add new activities, all these flows should continue to work.
    2. add primary button "Let's get started", that opens the new `InstantOnboardingActivity`
    3. replace logo by the plain Delta Chat logo

2. in `InstantOnboardingActivity`,

    1. create layout similar to the desktop one. no need to mimic footer exactly wrt background etc., but the elements should be the same at the same position
    2. on opening, it should already be fine to create a new empty account, so that avatar and name can already be set using `set_config()`
    3. when the user hits "Accept & Create Profile", call `setConfigFromQr()` using `dcaccount:https://nine.testrun.org/cgi-bin/newemail.py` (can be hardcoded as is, we can get crazy later)

i think, when this is done, we can already review+merge, next PR is to make the other flows working (scanning QR code or tapping "Explore Other Options" from the instant onboarding screen)

**Comment by adbenitez** [comment]
> 2\. on opening, it should already be fine to create a new empty account, so that avatar and name can already be set using ``

not sure it is ok to create account in background when you don't know if user accepts or not the privacy policy

**Comment by r10s** [comment]
> not sure it is ok to create account in background when you don't know if user accepts or not the privacy policy

it is not about calling `configure()` and sending things over the wire.

it is just about already having a `dc_context_t` object, so that one can set name and avatar (which are also not sent over the wire) - and only on hitting "Agree & Create Profile" - set_config_from_qr() is called and then configure().

 that's fine, and also what desktop is doing roughly

**Comment by adbenitez** [comment]
> 3\. replace logo by the plain Delta Chat logo

is there a place where this asset is or should I pick it from desktop PR?

**Comment by r10s** [comment]
it's fine to pick it from desktop. otherwise raw logos, icons, colors etc. are at https://github.com/deltachat/interface/
