### ISSUE TITLE
Option to change account details

### ISSUE THREAD

**Issue by allo-** [deltachat/deltachat-android#300]
_Please read the guidelines linked above, especially when you are a first time contributor. Remove this text and provide some basic informations below, if applicable. Remove template content that is not applicable._

**Delta Chat version**
0.16.0

**Expected behavior**

I should be able to change account details or logout completely

**Actual behavior**

I cannot

**Steps to reproduce the problem**

1. Setup Delta Chat. Enter some wrong details for the mail server
2. Delta Chat does not work as expected
3. You cannot change the details.
4. You cannot logout and login again.

The is an absolute show stopper, as small mistakes can make the app mostly unusable (you need to delete all data from the settings app) and probably users cannot change their mail password without breaking the app (I did not test if you get a password prompt when the login fails).

**Comment by violoncelloch** [comment]
Have you seen "Settings»advanced settings»account settings" ?
Doesn't this contain the settings you mean?

**Comment by allo-** [comment]
Indeed, that's it.

I did not recognize it because as the very first item before items containing checkboxes and numbers it looked like a header instead of a button. Maybe you should make it more prominent visible (i.e. in the main menu), but probably this will come with #25 anyway?
