### ISSUE TITLE
app crashes in "create new contact" screen on android 4

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#3003]
in android 4 (API 16) the app crashes when you click the "new contact" button in my tests in the android emulator

**Comment by r10s** [comment]
for me, on a real android4 testing device, the app also crahes on install - (1.44 from fdroid - 1.36 dev is also installed on the device and working) - but the device crashes often, also in settings on boot etc - so, maybe sth different.

**Comment by adbenitez** [comment]
> for me, on a real android4 testing device, the app also crahes on install

this sounds like: https://support.delta.chat/t/dc-on-older-devices/3046

**Comment by r10s** [comment]
unfortunately, i do not manage to get the device connected to debug-bridge (that stopped working at some point)

**Comment by r10s** [comment]
ftr, @adbenitez figured out it might be related to "android:drawableLeft that for some reason don't support vector drawable in android 4" - and linter suggests  app:drawableLeftCompat
