### ISSUE TITLE
trying to start on android4 crashes immediately

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3027]
from https://support.delta.chat/t/dc-on-older-devices/3046/7 : 

on an android 4.4.2 (kitkat), the app crashes immediately on startup

i have sth. similar on an android device, which, however refuses to connect to debug-bridge - and is also otherwise very buggy meanwhile, independent of deltachat, see https://github.com/deltachat/deltachat-android/issues/3003#issuecomment-2096188265

@link2xt tried to set up an emulator, but without success - https://support.delta.chat/t/dc-on-older-devices/3046/8?u=r10s

so - questions is how to deal with it. seems we do not have any device nor emulator that runs android4 in a way we can take action

as this should not be a blocker, if we do not find sth. actionable for 1.46, we should **increase minSdkVersion to android5** - at least, we would not ship more buggy versions that overwrite existing installations - and if we find a solution later, we can decrease again so that the android4 installations get their updates

**Comment by r10s** [comment]
> If you can reproduce the crash, then first we need to find out if it is the core problem or UI code problem.

my android4 phone crashes on startup of 1.44 installation from fdroid - but unfortunately, i am completely failing to connect it via usb, debug bridge or whatever. so i cannot access logs nor install from androidstudio. the phone is also buggy otherwise, lots of random crashes.

this is not a setup we can take action, unfortunately (alone the 1.44 installation from fdroid took me more than half an hour ...)

**Comment by r10s** [comment]
trying the following - maybe i have more luck with the emulator

![Screenshot 2024-05-06 at 21 57 24](https://github.com/deltachat/deltachat-android/assets/9800740/64a859f3-034c-4b30-a8da-302e42d5db2c)

**Comment by r10s** [comment]
no luck:

![Screenshot 2024-05-06 at 22 01 21](https://github.com/deltachat/deltachat-android/assets/9800740/bd17b320-b92b-4c6e-81b3-64fcbe20ad0e)

**Comment by r10s** [comment]
so, we can sleep over it, but i do not think, it makes much sense to spend more resources currently, during the 1.46 release ongoings.

if we increase minSdkVersion and lower it later, the android4 ppl would just get their update delayed - and if we do not manage to lower minSdkVersion later, at least we would not break more running android4 installations

**Comment by adbenitez** [comment]
question is if this only affects android 4 and not any other 32bit system with ex. android 5

**Comment by adbenitez** [comment]
I tested in a real android 4 device, current stable release in fdroid crashes, but the beta of the next release works fine!

we can close this issue

**Comment by r10s** [comment]
not doomed yet 😈 android4 survived another day, whew
