### ISSUE TITLE
Key-Exchange by file rather than setup message

### ISSUE THREAD

**Issue by ne20002** [deltachat/deltachat-android#303]
I'd prefer to have a way to import my keys by asc-file. I have a pair I use with Enigmal and Mailvelope and I can transfer the keys vice versa. 
Seems as if Delta Chat is importing only keys that has been written by itself. Setup-Message is either not aproriate as I don't want to send keys via email provider and is also not working.
:(

**Comment by r10s** [comment]
what is not working with setup messages?
in general, delta chat allows importing keys not written by itself, however, of course, there can be issues with specific keys.

moreover, you can import and export .asc files at settings / advanced, for importing, keys must not be protected by a password, see https://github.com/deltachat/deltachat-core/issues/144. however, the recommended way is a setup message.

**Comment by t-oster** [comment]
This may be fixed by https://github.com/deltachat/deltachat-core/pull/191. @ne20002 please be more specific, what you were trying to import. Please check if the asc file contains the private key after the public key and is NOT password protected.
