### ISSUE TITLE
App is constantly crashing // maybe improve the log feature

### ISSUE THREAD

**Issue by ChargingBulle** [deltachat/deltachat-android#304]
Been using the app for 2 hours now and in the meantime it crashed ~ 30 times.
I can paste the log here but they don't seem very helpful as they don't list crash analytics.

My phone has no GApps installed. Maybe this contributes to the crashes?
After restarting the app is fine again

Can I somehow switch on verbose logging?

	© 2017, 2018 Delta Chat contributors

	Chats: 9
	Chat messages: 139
	Messages in mailbox: 4
	Contacts: <redacted>
	Database=/data/user/0/com.b44t.messenger/files/messenger.db, dbversion=27, Blobdir=/data/user/0/com.b44t.messenger/files/messenger.db-blobs

	displayname=Jonas Dralle
	configured=1
	config0=<redacted> <redacted>:*:<redacted>:993 0:0:0:0 IMAP_SSL SMTP_STARTTLS
	config1=<redacted> <redacted>:*:<redacted>:993 <redacted>:*:<redacted>:587 AUTH_NORMAL IMAP_SSL SMTP_STARTTLS
	mdns_enabled=0
	e2ee_enabled=1
	E2EE_DEFAULT_ENABLED=1
	Private keys=2, public keys=5, fingerprint=
	<redacted>
	<redacted>

	Using Delta Chat Core v0.16.0, SQLite 3.22.0-ts1, libEtPan 1.7, OpenSSL 1.0.1t. Compiled Mar 22 2018, 20:59:43 for 32 bit usage.

	Log excerpt:

	13:37:47 T2: Attaching C-thread to Java VM...
	13:37:47 T2: Attaching ok.
	13:37:47 T2: Job thread entered.
	13:37:47 T2: Job thread waiting for signal...
	13:37:48 T1: Opened "/data/user/0/com.b44t.messenger/files/messenger.db" successfully.
	13:37:48 T1: Signal job thread to wake up...
	13:37:48 T2: Job thread checks for pending jobs...
	13:37:48 T2: Executing job #1, action 900...
	13:37:48 T2: Connecting to IMAP-server "<redacted>:993" via SSL...
	13:37:48 T1: Chatlist created in 3.567 ms.
	13:37:48 T2: Connection to IMAP-server ok.
	13:37:48 T2: Login to IMAP-server as "<redacted>"...
	13:37:48 T2: IMAP-Login ok.
	13:37:48 T2: IMAP-Capabilities: IMAP4 IMAP4rev1 ACL RIGHTS=tekx QUOTA LITERAL+ NAMESPACE UIDPLUS CHILDREN BINARY UNSELECT SORT CATENATE URLAUTH LANGUAGE ESEARCH ESORT THREAD=ORDEREDSUBJECT THREAD=REFERENCES CONDSTORE ENABLE QRESYNC CONTEXT=SEARCH CONTEXT=SORT WITHIN SASL-IR SEARCHRES METADATA ID XSENDER X-SUN-SORT ANNOTATE-EXPERIMENT-1 X-UNAUTHENTICATE X-SUN-IMAP XUM1 IDLE
	13:37:48 T2: Starting IMAP-watch-thread...
	13:37:48 T3: Attaching C-thread to Java VM...
	13:37:48 T3: Attaching ok.
	13:37:48 T3: IMAP-watch-thread started.
	13:37:48 T3: Fetching from all folders.
	13:37:48 T4: Attaching C-thread to Java VM...
	13:37:48 T4: Attaching ok.
	13:37:48 T4: IMAP-heartbeat-thread started.
	13:37:48 T2: Job #1 done and deleted from database
	13:37:48 T2: Job thread waiting for signal...
	13:37:48 T3: 0 mails read from "INBOX" with 0 errors.
	13:37:48 T3: Init lastseenuid and attach it to UIDVALIDITY for folder "Archive".
	13:37:48 T3: Folder "Archive" is empty.
	13:37:48 T3: 0 mails read from "Archive" with 0 errors.
	13:37:48 T3: Init lastseenuid and attach it to UIDVALIDITY for folder "Archives".
	13:37:48 T3: Folder "Archives" is empty.
	13:37:48 T3: 0 mails read from "Archives" with 0 errors.
	13:37:48 T3: 0 mails read from "Archives/2016" with 0 errors.
	13:37:48 T3: 0 mails read from "Archives/2017" with 0 errors.
	13:37:48 T3: 0 mails read from "Archives/2018" with 0 errors.
	13:37:49 T3: Receiving message Chats/91...
	13:37:50 T3: Message already in DB.
	13:37:50 T3: Receiving message Chats/92...
	13:37:52 T3: Message already in DB.
	13:37:52 T3: Receiving message Chats/93...
	13:37:53 T3: Message already in DB.
	13:37:53 T3: 3 mails read from "Chats" with 0 errors.
	13:37:53 T3: Folder "Drafts" ignored.
	13:37:53 T3: Folder "Junk" ignored.
	13:37:53 T3: Folder "SPAM" ignored.
	13:37:53 T3: 0 mails read from "Sent" with 0 errors.
	13:37:53 T3: Folder "Trash" ignored.
	13:37:53 T3: Init lastseenuid and attach it to UIDVALIDITY for folder "Unwanted".
	13:37:53 T3: Folder "Unwanted" is empty.
	13:37:53 T3: 0 mails read from "Unwanted" with 0 errors.
	13:37:53 T3: IDLE start...

	SDK_INT=25
	MANUFACTURER=samsung
	MODEL=SM-G800F
	APPLICATION_ID=com.b44t.messenger
	BUILD_TYPE=release
	ABI=ErrAbi
	ignoreBatteryOptimizations=0
	versionCode=514
	13:39

**Comment by r10s** [comment]
hi @JonasDralle verbose logging is available via Logcat or Android Studio; this has also the advantage that this log will contain system events etc.

**Comment by r10s** [comment]
regarding the crashes: i cannot reproduce this here, neither on devices with or without Google.
so, a detailed system log via logcat would be very interesting.
