### ISSUE TITLE
Markdown links not being parsed by chat screen

### ISSUE THREAD

**Issue by foxyseta** [deltachat/deltachat-android#3040]
- Android version: LineageOS 20
- Device: Samsung Galaxy S8
- Delta Chat version: 1.44.0
- Expected behavior: HTML links are correctly showed in the chat screen
- Actual behavior: I can see a Markdown-like link syntax, i.e. `(test)[url]`
- Steps to reproduce the problem: receive an HTML mail with a link
- Screenshots: 
![Screenshot_20240509-202910_Delta Chat](https://github.com/deltachat/deltachat-android/assets/12249077/a05b20a0-66a3-4e6d-a446-b30d1a901fc5)

- Logs:

**Comment by adbenitez** [comment]
hello @foxyseta thanks for taking care to report, but this is not a bug, the app just doesn't support markdown in general in message bubbles

the feature proposal to add markdown support is here: https://support.delta.chat/t/markdown-support-for-dc-android-and-dc-ios/2884

you can participate there, give your upvote and comment if you think it is an important feature,

best regards,
adb
