### ISSUE TITLE
Support directly "sharing" a log to some chat

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#3046]
posting a copy-paste is a giant message in DC, and saving, and refinding is bothersome. 
If there were a way to directly share a log it'd be very helpful especially for the push-notification debugging now.

**Comment by r10s** [comment]
maybe a usual "share button", that way, you can share to other apps, notes, save, whatever - as well as to delta chat

(this is what we did for iOS, btw)

**Comment by adbenitez** [comment]
> maybe a usual "share button", that way, you can share to other apps, notes, save, whatever

+1 I will go for that
