### ISSUE TITLE
"three dots" in reaction selector might wrap in small screens

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#3047]
![image](https://github.com/deltachat/deltachat-android/assets/24558636/a8a62c08-d2a9-4924-b3f6-be46f9965b32)

**Comment by r10s** [comment]
looks very mysterious, like a very secret reaction only professionals understand

. .
.

**Comment by adbenitez** [comment]
one easy solution is to delete the sad face from default reactions then everyone is happy!
