### ISSUE TITLE
Check whether to change the package name to chat.delta.android

### ISSUE THREAD

**Issue by JonasDralle** [deltachat/deltachat-android#305]
While the current name is okay it doesn't reflect the relationship to https://delta.chat/

Proposed change:
`com.b44t.messenger` -->  `chat.delta.android`

Community vote via 👍 👎 emoji?

**Comment by r10s** [comment]
yeah, the current package name was chosen before the whole thing got the name "Delta Chat" :)

however, wouldn't changing the package name also required the users to re-install the app? if so, we should consider this, too.

**Comment by JonasDralle** [comment]
This will trouble the update routines. Haven't found any official doc yet in what way this would trouble the android system and the f-droid store but I don't think we can avoid trouble.

All I know is that
1) changing the name would increase the trustworthiness of the app, since it's a name associated with an open source group instead of an individual (which is an opinion tbh ; people who vote for this ticket appear to share this view)
2) Doing this as early as possible would result in the smallest damage possible. Similar to ripping off a band-aid.

It's harsh to disrupt the users but we should do it while we're sill a `0.x` version.

**Comment by johanw666** [comment]
Not everyone uses F-Droid, some way to transfer settings to the new ly named app without involving F-Droid would be preferrable.

**Comment by r10s** [comment]
@JonasDralle i fear there are currently definitely not the resources to create and test such a migration version.

**Comment by testbird** [comment]
The standard Import/Export function should work. Maybe the renamed package can even be installed in parallel. And a last update for the old package, just puts something like an "old" overlay on the logo in the old package, before the next version is released with the new package name.

**Comment by violoncelloch** [comment]
And something like the intro (showing the strength of delta chat) could warn and guide the user to move to the new app.
Maybe even a banner or an entry on top of the chats list which stays there could be added.

**Comment by JonasDralle** [comment]
@r10s then change package name without migration tool.
All the messages reside inside the email server of the user. The user would only need to login again.

**Comment by testbird** [comment]
related: https://github.com/deltachat/deltachat-android/issues/379

**Comment by r10s** [comment]
> @r10s then change package name without migration tool.
> All the messages reside inside the email server of the user. The user would only need to login again.

that's just not true.
there is no option to restore messages. 
also, it's not only about messages but also about settings, created chats, blocked users and so on.

so, the inital poll should not only be about a nicer internal-id but also if that changing the internal-id may result in hard jobs about export/import - which is a challenge esp. on devices with few harddisk-space. 
 
in https://github.com/deltachat/deltachat-android-ii/issues/230 and on irc and in personal discussions we've reconsidered this, however, decided for an easier update-path.

also, the internal name is not always visible, eg. on my moto-g test-device i did not have found it at all. and, for google-play, we can go for another id.

i would suggest to close this issue, it would result in lot of work for both, maintainers and users, for few effect imho.

**Comment by webratte** [comment]
Me, as a non tech but interested user would say:
Minimum 90% of te users are not interested in the package name or even know what it is ;-)

So IMHO it's not needed to change it.

**Comment by r10s** [comment]
in fact, i was really searching to get the appplicationId, but i did not find it o recent test devices. also f-droid does not display it - so, i would suggest to close this issue.
