### ISSUE TITLE
name/avatar settings do not survive leaving/re-entering InstantOnboardingActivity

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3063]
when settings a name + avatar and then selecting another server, the name is lost.

in addition to saving on hitting "create" button, we should set name/avatar unconditionally when leaving InstantOnboardingActivity and restore it on re-entering

**Comment by adbenitez** [comment]
that was actually intentional, otherwise the change is too subtle (just the privacy policy thing) and user might not notice that anything changed at all :thinking:

**Comment by r10s** [comment]
well, but nothing happens but name and avatar the user selected is not discarded. the use can still edit after server changes

it is weird to ask the user for a name, then allow to change server - and let the user set name 
and avatar again

the account is still only configured later, so i do not see how this can be unexpected (maybe when going back to "welcome" - but that can be handeled separately, if we think it is important)
