### ISSUE TITLE
Scanning QR code from message-composing

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android#309]
Hi

it would be nice if there is a direct way to scan QR codes and put them in messages directly. 

thanks

**Comment by r10s** [comment]
Hi @gerroon,

thank you for your post, however, i do not understand it :)
can you be more precise what you're meaning and what you want to achieve?
what is a "direct way to scan QR codes"? what is "them" and why should put into "messages directly"?

**Comment by gerroon** [comment]
@r10s 

Lets say I want to paste the content of the QR code directly into a message. At the moment, I have to leave the message window, open a scan program scan the qr code with it, either copy or share from that scann app to DC to get tthe actual content of a QR code.

Instead, when I press the camera icon in DC message line,. there can be an icon that directly runs the QR scanner and pastes the results back into the curent message directly.

**Comment by r10s** [comment]
@gerroon so you're talking about QR codes containing plain text or URLs?
and you want to scan eg. a URL from a QR code and send it directly to a chat (the URL, not the QR code itself)?

i still do not understand what this has to do with "open a scan program".

however, the main purpose of the QR scanner is to establish contacts and create groups - which is typically not bound to the message input.

**Comment by gerroon** [comment]
I am talking about text, urls, whatever can be encoded in a QR code. Not the QR code itself, the content of the QR code in the message to sent.

"open scan program" is how this qr scanning works on my phone. When an app provides QR scanning, it generally fires another app to scan the QR code then pastes the result back to itself, not sure what else this mechanism called.

**Comment by r10s** [comment]
just to make sure, we're talking about the same things: are you aware of the Labs-Function that adds a QR-scanner into the main screen of Delta Chat? (Settings > Advanced > Labs: Enable QR code options)

The flow in Delta to send a text would be Scan > Copy to clipboard > Select chat > Paste, at least a little easier as using an external program.

However, as mentioned, the "Copy scanned QR content to clipboard" is only a side effect - that, of course, might be improved later. For now, the core QR verification progress is subject to change, so we will focus on this currently.

**Comment by r10s** [comment]
ok, i understand.

might be useful, however, i feel i would first try the QR code content myself before sending it to someone else, eg. open the URL in the browser, if it looks worth sharing, share it from there.

And, at least with the Labs-feature you do not need another app :)

**Comment by gerroon** [comment]
Thanks for considering

**Comment by haeckser** [comment]
I understand the intention, but isn't it  the typical flow, that you see a QR code, scan it and open the URL in browser - and if you enjoy, you will give such information to some friends and can simply share it (the URL) via DC. No need to scan it again inside DC. I don't have the behaviour for text content of QR codes in mind,but I would assume you can share it directly or copy and paste it without any change in DC

From my point of view it is not a necessary or something behind 1.0

**Comment by gerroon** [comment]
@haeckser It is to avoid all those steps like opening thirdparty app scanning copying getting back to dc etc.

**Comment by haeckser** [comment]
If I would like to send a picture, I will be happy that DC is opening the camera app and includes the picture. That is the comfort I like and will never miss. Same with video, files, speech, music, etc.
But in case of QR codes, the order is typically reverse. I cannot read QR codes by myself, so I take my Android and scan it to understand the contents which is typicaly an URL and sometimes simple text. And after I have converted the QR, I might have the idea to share it using DC. But not by starting DC, start internal scan (like the camera app) again and forward its content. No, I would simply share the content that I have in front of me (after scanning and understanding what it is about). 
That is the difference to pictures or music and why I would give QR scanning from DC to sent its contents a low priority

**Comment by testbird** [comment]
There are special apps that show the QR content before doing anything.
Like by the Technische Universität Darmstadt, Germany https://f-droid.org/de/packages/com.secuso.privacyFriendlyCodeScanner/

Getting into the habit of scanning anything without inspecting it isn't a good idea, so if DC gets (another) button to scan QR codes it would be good if the scanning app could be selectable.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
