### ISSUE TITLE
Crash when you activate "Share location with all group members"

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-android#3098]
- Android version: 10
- Device: Huawei Mate 20
- Delta Chat version: 1.46.0
- Expected behavior: When you enable "Share location with all group members" it should not crash
- Actual behavior: Crash
- Steps to reproduce the problem: Just activate "Share location with all group members" in any chat.
- Screenshots:
- Logs:
[deltachat-log-20240525-190545-1.txt](https://github.com/deltachat/deltachat-android/files/15444316/deltachat-log-20240525-190545-1.txt)

**Comment by r10s** [comment]
for reproducing  in the emulator android14

- fresh install
- enable location streaming in "advanced settings"
- go to "saved messages", "attach location"
- system does not show the "direct dialog" (why?) but redirect to the system-permission-settings-dialog
- enable "location" there, back, back
- again, "attach location" -> **crash**

for me, on every restart, app crashes now

log: https://gist.github.com/r10s/7b076550f3bea4a470f9e868c22d217d

**Comment by r10s** [comment]
thanks a lot for testing and reporting! did a fix at #3100

**Comment by Gh0stz0x** [comment]
Thank you for Delta Chat! 😄
