### ISSUE TITLE
add peer to peer channels

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3103]
related desktop PR: https://github.com/deltachat/deltachat-desktop/pull/3741

android PR adding for getting blob from event: https://github.com/deltachat/deltachat-android/pull/3089

**Comment by adbenitez** [comment]
for testing in implementators would have been nice if the webxdc-test app had a simple test that sends and receive data and display it in a section

**Comment by Septias** [comment]
[Ping](https://github.com/Septias/ping-xdc) and [Messaging](https://github.com/Septias/gossip_tests) are both good xdcs to test communication etc.

**Comment by Septias** [comment]
I find the headline very confusing by the way. This is about adding realtime channel API to android, right?
