### ISSUE TITLE
remove DEBUG entries from log

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3106]
with the now [colored debug](https://github.com/deltachat/deltachat-android/pull/3087) log, the _green_ DEBUG entries are easily recognizable - and i do not think, there is any worth in it for out typical debugging of network problems, this level is not even emitted by core/us but only by other libraries.

it is probably just noise in most, if not all cases. and it may result in INFO/WARNING/ERROR being added less for older entries.

i do not think, we need a switch, i would consider a switch only if we really have an issue where that would be helpful.

<img width=320 src=https://github.com/deltachat/deltachat-android/assets/9800740/3698ef42-e1a0-46bc-a7db-0bad6f79f6f9>

**Comment by adbenitez** [comment]
we have a developer mode toogle, makes sense to log debug only if developer mode is enabled

**Comment by r10s** [comment]
yes, that's an option to play it safe. if it turns out we really never need that stuff we can always iterate
