### ISSUE TITLE
Emoji avatar is not displayed in the settings

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-android#3117]
If an emoji is placed in front of the profile name, it is displayed as an avatar in the account switcher, but not in the settings.

DC-Android 1.46.2

**Comment by adbenitez** [comment]
in the settings if no avatar is set, a camera icon is displayed indicating that you can click to set an avatar, it is not that the emoji is not displayed, no avatar is displayed there, so there is no bug, it is the intended behavior,

thanks for your report and taking care
