### ISSUE TITLE
Themed/Monochrome App Icon

### ISSUE THREAD

**Issue by NielSync** [deltachat/deltachat-android#3144]
![Screenshot_20240701-160104.jpg](https://github.com/deltachat/deltachat-android/assets/20804647/106e8a18-575e-4c8e-9379-ba263b2d4439)

**Comment by adbenitez** [comment]
this is not a bug but a feature proposal, I moved it to the forum: https://support.delta.chat/t/themed-monochrome-app-icon/3205

we can keep the discussion there with the rest of the DC users, thanks for your proposal!

**Comment by adbenitez** [comment]
hi @NielSync good news! I implemented your requested feature :tada:
