### ISSUE TITLE
app must target api34 by Aug 31

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3151]
the yearly dance ... did not check out which new requirements are needed this time.

![Screenshot 2024-07-08 at 12 07 08](https://github.com/deltachat/deltachat-android/assets/9800740/f6864c17-2b21-455d-99ed-9ead85af6c37)

**Comment by adbenitez** [comment]
documentation: https://developer.android.com/about/versions/14/behavior-changes-14

**Comment by r10s** [comment]
i checked some points of the link:
- [android core libraries](https://developer.android.com/about/versions/14/behavior-changes-14#core-libraries): we're not using java.util.regex.Matcher, java.util.UUID.fromString(), ProGuard
- [JobScheduler reinforces callback and network behavior](https://developer.android.com/about/versions/14/behavior-changes-14): JobScheduler is not used by us, WorkManager is quit after 1 minute (but we could improve by using
