### ISSUE TITLE
 verification checkmark is unreliable

### ISSUE THREAD

**Issue by dkg** [deltachat/deltachat-android#3155]
- Delta Chat version: 1.46.5

I recently changed the displayname for my delta account to "dkg ✅✓✔☑".

As a result, when a contact using DeltaChat android 1.46.5 looks to see whether i'm verified (i am, on their system), they see this:

![checkmarks-android](https://github.com/user-attachments/assets/50134931-f034-490b-bf12-12addefe05b5)

If i wasn't verified, they would see the same thing, but the last checkmark would be missing.

I don't think we can expect users to distinguish between the different types of checkmarks, which means that a user can't defend themselves against someone putting a checkmark in their username to make the recipient think that they're verified.

(this is the same as https://github.com/deltachat/interface/issues/71 but for android)

**Comment by r10s** [comment]
thanks for bringing that up, discussion takes place in the other issue at https://github.com/deltachat/interface/issues/71 ; closing this issue here as there is no concrete actionable item for android currently
