### ISSUE TITLE
update store descriptions

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3161]
the store descriptions are quite outdated, esp. when it comes to "just write to any email address".

descriptions they are placed at:

https://github.com/deltachat/deltachat-android/blob/main/store/text.md (needs to be copied manually to google play, same can used for amazon/huawei, probably ios)

and 

https://github.com/deltachat/deltachat-android/blob/main/metadata/en-US/short_description.txt / https://github.com/deltachat/deltachat-android/blob/main/metadata/en-US/full_description.txt (f-droid)

and can be modified via a normal PR.

when this issue is closed, we should update ios as well.

**Comment by missytake** [comment]
I wrote this draft:

## Delta Chat

Delta Chat looks and feels like other popular messenger apps, but does not involve centralized tracking and control. It is available on all platforms, and offers reliable and trustworthy communication.

Sign-up is easy - you don’t need a phone number, an e-mail address, or any private data. You can create as many profiles as you like to use different identities in private or professional circles.

Delta Chat has an elegant and simple user interface, as you know from WhatsApp and Telegram. To get in contact with others, you can send each other an invite link, or scan a QR code when you meet in person.

Technically, Delta Chat is an e-mail application but with a modern chat interface - e-mail in a new dress if you will. This means, that if you sign-in with your traditional e-mail account, you can send and receive e-mails to anyone, even if they don’t use Delta Chat. This means, you can select your server and use sovereign infrastructure - choose who you trust. Delta Chat’s trust model makes it perfect for sensitive purposes or business usage.

If everyone in the chat uses Delta Chat, the app offers seamless end-to-end encryption, based on the Autocrypt and Securejoin standards. Self-destructing messages, multi-profile support, and other security features protect your digital life. Delta Chat has been security-audited, is fully Open Source/Free Software, and based on Internet standards like IMAP and SMTP, openPGP/Autocrypt, and Securejoin.

Despite its simple look, Delta Chat offers extended functionality. With “apps shared in a chat” you can play games or take notes collectively, powered by webxdc.org standard. And various chat bots offer stickers, RSS feeds, voice message transcription, and other features.

Chat over e-mail and head back to the future with us!

---

Notes I had:


* decentralized messenger

  * multi-device

* easy sign-up: no phone number, e-mail address, or any private data needed

  * multi-profile: use different identities in professional or private circles

* send each other an invite link, or scan a QR code in person to get in contact

* elegant and simple user interface, as you know from WhatsApp and Telegram

* based on e-mail; if you use a traditional e-mail account, you can send and receive e-mails

  * choose who you trust, sovereign infrastructure

  * fully Open Source and standards-based

* reliable and trustworthy, perfect fit for business use cases, even with traditional e-mail contacts

* interoperable end-to-end encryption, if everyone in the chat uses Delta Chat

  * based on the Autocrypt and Securejoin standards


  * self-destructing messages

* use apps in a chat, send “Hi” to xstore@testrun.org to discover them

* various chat bots for extended functionality

* 

* available on any platform

* no phone needed: doesn’t make sense to mention in the iOS store

**Comment by missytake** [comment]
It is slightly shorter than most of our current store descriptions.

Our competitors use bullet points rather than paragraphs for features, we could consider that. This explanation is focused on early adopters still, instead of mass users, if you will. On the other hand I think Delta Chat deserves an explanation rather than selling points, and mass users don't read more than the first 2 sentences anyway, they will probably ignore bullet points, too.

**Comment by adbenitez** [comment]
> Our competitors use bullet points rather than paragraphs for features, we could consider that.

yes please, it is much easier to read
