### ISSUE TITLE
adapt internal strings to changed "read receipt" behaviour

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3179]
adapt stock strings to changes done at https://github.com/deltachat/deltachat-core-rust/pull/5712 :

- string DC_STR_READRCPT_MAILBODY (32) is deprecated, a warning is logged
- string DC_STR_READRCPT_MAILBODY2 (192) is new

wondering if it isn't even better to leave the string in english, so only remove DC_STR_READRCPT_MAILBODY (32). there is not so much worth in translations, the string is usually not visible, and that way also no language setting is disclosed if the read receipt is sent unencrypted for whatever reason.

once this is settled for android, issues/pr for ios desktop need to be filed.

**Comment by iequidoo** [comment]
> wondering if it isn't even better to leave the string in english, so only remove DC_STR_READRCPT_MAILBODY2 (32). there is not so much worth in translations, the string is usually not visible, and that way also no language setting is disclosed if the read receipt is sent unencrypted for whatever reason.

+1, better in English and maybe even shorten to "This is a receipt notification." Moreover, read receipts are still unencrypted and there's no need to disclose the language setting even to contacts. And we don't know the contact's language setting, so we can't translate it properly.
