### ISSUE TITLE
Some Android-Versions return bad download folder -> importing PGP keys fails

### ISSUE THREAD

**Issue by t-oster** [deltachat/deltachat-android#318]
Delta Chat version: v0.17.3

When trying to import existing PGP Keys, the app uses `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)` to determine the Download folder.

On my device (Oukitel K6000 Plus, Android 7.0) the download folder is `/sdcard/Download`, so it should look there.

However the function returns  `/storage/emulated/0/Download`, which is not readable on my device (I tried with various file-managers and Termux), nor is it linked to the real Download folder.
So there seems to be a Bug in Android, which causes a wrong folder to be returned, which makes importing keys impossible for me.
I am not the only one: https://stackoverflow.com/questions/34041741/environment-directory-downloads-returns-incorrect-directory)

Maybe we should consider using a file-manager dialog or at least let the user manually override the path in order to allow imports on buggy Androids.

**Comment by t-oster** [comment]
The function used is here https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/SettingsAdvFragment.java#L447

**Comment by r10s** [comment]
Wondering if there are approches to fix this in the os.
However, a file selector may be useful in general.

(also, i am not sure if the "Download" directory is the best place to export/import keys to, i just thought, this may be the only directory where most users are able to delete files without additional software later. however, this is a different issue :)

**Comment by t-oster** [comment]
Well now that I have a working debug build, I can confirm that `/storage/emulated/0/Download` in fact works from the app. The problem was that if I export my key with thunderbird, it will also prepend the public key so that the file is ignored.
The detailed description from #98 helped me importing my existing key, so this was false alarm.
I thought about adding a file-open dialog, but since the core-api expects a folder instead of a file, I think we can do this later.
Possible improvements:

- Make the import function list all candidates with errors so the users gets a hint
- Add an intent to pick a folder instead of only the Download folder
- Check for private keys following public keys, so keys exported from thunderbird/enigmail GUI work out of the box

**Comment by t-oster** [comment]
For reference: Android API 27+ has this intent for specifying directories https://github.com/googlesamples/android-DirectorySelection
