### ISSUE TITLE
High battery usage with DC 1.46.x F-Droid

### ISSUE THREAD

**Issue by lkfasnrqrl** [deltachat/deltachat-android#3184]
- Android version: 8.0.0 (OxygenOS 5.0.3) with microG
- Device: OnePlus5T (ONEPLUS A5010)
- Delta Chat version: 1.46.7 F-Droid, 1.46.5 F-Droid
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

I'm using the F-Droid build of DC with my own IMAP server which is working without any problems for versions <= 1.44.0.

With version 1.46.5 or 1.46.7 android is reporting a high battery usage of DC and the app is stopped after some time in background, so that I do not receive notifications about new messages.

**Comment by adbenitez** [comment]
hi @lkfasnrqrl thanks for reporting, we need more information, could you provide a log? (go to settings then advanced)
better after some time of noticing the battery drain while the app is installed

**Comment by adbenitez** [comment]
thanks a lot @lkfasnrqrl !!! this is really useful!

@link2xt could be the battery drain related to the lot of lines per second saying:

```
1722454086.016 10658 19137 23586 I DeltaChat: src/scheduler.rs:674: IMAP session supports IDLE, using it.
1722454086.017 10658 19137 23586 I DeltaChat: src/imap.rs:542: Not fetching from "<REPLACED>".
1722454086.067 10658 19137 23586 I DeltaChat: src/scheduler.rs:674: IMAP session supports IDLE, using it.
1722454086.069 10658 19137 23586 I DeltaChat: src/imap.rs:542: Not fetching from "<REPLACED>".
1722454086.121 10658 19137 23586 I DeltaChat: src/scheduler.rs:674: IMAP session supports IDLE, using it.
1722454086.121 10658 19137 23586 I DeltaChat: src/imap.rs:542: Not fetching from "<REPLACED>".
1722454086.180 10658 19137 23586 I DeltaChat: src/scheduler.rs:674: IMAP session supports IDLE, using it.
1722454086.180 10658 19137 23586 I DeltaChat: src/imap.rs:542: Not fetching from "<REPLACED>".
1722454086.243 10658 19137 23586 I DeltaChat: src/scheduler.rs:674: IMAP session supports IDLE, using it.
1722454086.244 10658 19137 23586 I DeltaChat: src/imap.rs:542: Not fetching from "<REPLACED>".
```

**Comment by adbenitez** [comment]
created an issue for the crash opening the log, since the original issue seems to be already fixed, we can close here, @lkfasnrqrl this should be solved for you in the next release, if the problem persist, comment again here providing a new log, thanks a lot for your help!
