### ISSUE TITLE
move "Video Chat" option to "Attach" menu

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3187]
currently, the "Video Chat" option is in the chat's context menu for whatever reason.

being a message sent, it is more logical to have it in the "Attach Menu", however. this is also consistent with iOS and desktop.

this would also cleanup the chat's menu [further](https://github.com/deltachat/deltachat-android/pull/3182).

**Comment by adbenitez** [comment]
question is what icon to use and how space can be better used there in a way that we can keep adding more stuff (ex. some webxdc stuff like drawing app or the webxdc store) even today with location streaming feature enabled there is no free space left in the attachment panel

**Comment by r10s** [comment]
maybe "Select Audio" is sufficiently covered by "Select Document", that would give us a slot :)

nb: [looking at the corresponding code](https://github.com/deltachat/deltachat-android/blob/main/src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java#L451), no idea why we query for permissions on "Select Audio" but not on "Select Document"
