### ISSUE TITLE
f-droid seems not to pick up the changelogs

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3189]
we maintain special f-droid changelogs as suggested in `RELEASE.md`, however, i do not see f-droid picking that up at some place, neither in the f-droid-app not on the webpage.

this used to work at some point in the past

**Comment by adbenitez** [comment]
FTR, the problem with this was that the changelog that is displayed to the user is the one that has a version number of an arch that is compatible with their phone, see:

https://github.com/deltachat/deltachat-android/issues/3274#issuecomment-2325324455
