### ISSUE TITLE
F-Droid: Long description for German in wrong language

### ISSUE THREAD

**Issue by sushidave** [deltachat/deltachat-android#3193]
### Device a:
- Android version: Latest
- Device: n/a
- Language: German (Germany)
### Device b:
- Android version: 8.0.0
- Device: SHIFT6m
- Language: German (Switzerland)
### Both devices:
- Delta Chat version: 1.46.7
- Expected behavior: Long app description on F-Droid for German appears in German
- Actual behavior: Long app description on F-Droid appears in a) English and b) Italian
- Steps to reproduce the problem: Open F-Droid and check the description on the Delta Chat page

On F-Droid web version, the long description for German appears in English:
https://f-droid.org/de/packages/com.b44t.messenger/index.html

According to Transifex, the translation status for German is 100%:
https://explore.transifex.com/delta-chat/delta-chat-app/

It seems that there are two issues:
1) Translation file from Transifex is not productive.
2) Wrong locale for German (Switzerland).

**Comment by r10s** [comment]
> According to Transifex, the translation status for German is 100%:

for f-droid, we experiment with _Weblate_, therefore,  translations are at https://github.com/deltachat/deltachat-android/tree/main/metadata and are done via https://hosted.weblate.org/projects/deltachat/android-metadata/

these f-droid translations are far away from 100%

sorry for this confusion here :)

> Actual behavior: Long app description on F-Droid appears in a) English and b) Italian

when i open https://f-droid.org/de/packages/com.b44t.messenger/index.html , i see the long description in English - which is expected as a german translation is missing.

for " b) Italian": what do you mean exactly here? can you add a screenshot?

**Comment by r10s** [comment]
closing as there is no actionable item. please comment or reopen if we've overseen something.

thanks a lot for taking care!

**Comment by sushidave** [comment]
@r10s 
Thanks for your reply and clarification that translations for F-Droid come from Weblate.

> for " b) Italian": what do you mean exactly here? can you add a screenshot?

Screenshot for device b set to language German (Switzerland):

![20240802-Screenshot_F-Droid_Delta_Chat](https://github.com/user-attachments/assets/aede9d0e-d9e7-4aad-bcf1-054e44e81c9a)

The long description is in Italian. Shouldn't it be in English since it's the default language?

**Comment by sushidave** [comment]
@r10s 
Same happens if the language is set to French (Switzerland). If set to English the long description is in English.

**Comment by r10s** [comment]
maybe F-Droids fallback for "German (Switzerland)" is Italian if German is missing? that would make some sense as Italian is an official language in Switzerland - but English is not [^1]

anyways, there is no actionable item here, the [metadata](https://github.com/deltachat/deltachat-android/tree/main/metadata) look fine so far, and when just completing the german translation, things would be totally unquestionable :)

[^1]: see "Official Languages" https://en.wikipedia.org/wiki/Switzerland

**Comment by sushidave** [comment]
@r10s 
Thanks. The German translation has been completed.

**Comment by r10s** [comment]
great! and thanks as well for taking care of details! 🙏
