### ISSUE TITLE
Option for "don't delete messages on server if deleted locally"

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#321]
Use case:
If You see a message locally which is corrupted (possible with uuencoded attachments for example) or You have a message which You really don't want to handle by DC it's not possible to delete it locally without deleting it at server. So this prevents You to handle it by other email client in case of You delete it too early.

Other email clients (K9) gives You the choice to "don't delete messages on server".

The most often this occurs even for messages in "Contact Requests" where You don't want to start a chat.

A user option for that is really necessary and should to be implemented very easily.

Eventually this can be done by chats profile or simply globally?

**Comment by testbird** [comment]
Appart from a default, the confirmation modal should provide a choice.
```
                                  Delete 5 messages?


                      Locally          On Server             Both

                                [  ] don't ask again


                                         Cancel
```

**Comment by csb0730** [comment]
Yes, this could be a solution too.

The most important is to have a choice!

 :)


Am 14.06.2018 um 12:17 schrieb testbird:

**Comment by r10s** [comment]
i agree, that something like that might be useful, however, i think we should shift the discussion on that to the [forum](https://support.delta.chat/). also as it affects also desktop and ios,

**Comment by g6094199** [comment]
This feature is missing in the desktop client in version 0.901.0.
