### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [deltachat/deltachat-android#3217]
...as many deps are no longer to be found in [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/-/blob/8cf4503a00f6e0ccb93f5a9089cf660f20b0045b/fdroidserver/scanner.py#L456-L480)

ref: https://monitor.f-droid.org/builds/log/com.b44t.messenger/6911#site-footer

**Comment by adbenitez** [comment]
this is a duplicated of #1791

**Comment by licaon-kter** [comment]
@link2xt it's on autoupdate, just release as usual

do we need to modify the recipe in some way?

**Comment by adbenitez** [comment]
nothing is needed besides tagging new version, as I pointed out to @r10s some days ago

thanks @licaon-kter for confirming

**Comment by r10s** [comment]
i just tagged [v1.46.13](https://github.com/deltachat/deltachat-android/releases/tag/v1.46.13) for f-droid
