### ISSUE TITLE
Show status for mail server connections at main screen

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#322]
Sometimes message delivery defers for some time and it' unclear if connection is there or not. Especially under bad mobile net conditions this is not really clear for the user.

It would help to see the current connection status for imap and last smtp try somewhere on the main screen. Maybe as one/two small red/green LED lights?

**Comment by csb0730** [comment]
I think with the great new version v0.18 this issue is a lower priority.

_Thanks a lot for the connection optimizations to the team: Good job!_ :-)

It would be only nice to have it :-)

**Comment by r10s** [comment]
hm, in general i am against any new ui elements :)

- the _incoming_ state (if Delta Chat can receive messages) is equal to the network state of the device - if the device is not connected, Delta Chat cannot receive message - if the device is connected, maybe only for a few seconds, Delta Chat will use this gap.

- the _outgoing_ state (if Delta Chat has sent a message) is shown directly beside the message in question - i think, a "Delta Chat global" connection state would not help here.
And, same as for incoming, as soon as there is little network, Delta Chat will try to do what's needed at once.

so, in general, i do not see the benefits of a red/green led or sth. like that - and, from my view, i would also not agree that it is "nice to have" - it has to be documented, maintained and may have it's own issues ...

i would vote to close this issue therefore :)

**Comment by csb0730** [comment]
As I wrote: nice to have (but not really needed any more) - I'll close it :-)
