### ISSUE TITLE
Introduce a function to move (not forward) a message to another chat at local device 

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#324]
If a message is routed wrong to a chat or group it is not possible to move it manually at local device to the correct chat.

This use case happens most of times, when message comes from another MUA and DC tries to automatically route it or opens an adhoc group. This fails often because DC doesn't understand the subject and the history of mail content!

**Comment by testbird** [comment]
First, is there really no more room to improve the automatic assignment?

But in any case, it would be nice if the handling of chat assignment errors could be solved with a single "reassign or message" feature, see second point listed under general features at https://github.com/deltachat/deltachat-core/wiki/Use-Cases

**Comment by testbird** [comment]
Question remains: can this made to work for multi-client?

**Comment by r10s** [comment]
> First, is there really no more room to improve the automatic assignment?

there still is room for improvement, i would also prefer puting efforts to improving this first.

in general, i would not like such a feature; i do not think, users should start "sorting" messengers in their messengers.

**Comment by csb0730** [comment]
It is somehow like in a standard MUA. I really need this feature!

I think, as long as other peers are free in their decision to use the functions "New message", "Reply", "Reply all" or even a malfunction of the peer MUA to make a reply for a chat we should offer a manual reassign function.

I've been faced to this situation in group chats only by now. But a general function should be provided.

This problem is normally relative rare but if it happens user should have an option to solve it. Now You only have the option to delete a message or forward it to the correct chat (but this confuses other mail users very much because they see a new message without any reason for them!)

I think from technical point of view this can be implemented very easily (Simply change the chat # in local database!).

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
