### ISSUE TITLE
"Copy to clipboard" while preparing profile to add second device

### ISSUE THREAD

**Issue by dotlambda** [deltachat/deltachat-android#3245]
- Android version: 14
- Device: Pixel 8
- Delta Chat version: 1.46.7

In the "Add Second Device" dialog, the option "Copy to clipboard" exists even while the profile is being prepared but clicking it doesn't actually copy anything to the clipboard before it's ready.

**Comment by r10s** [comment]
6 hours from reporting to fixing - and even the release is in the queue ... this was fast! 🏃‍➡️

thanks for reporting @dotlambda, thanks for fixing, @adbenitez
