### ISSUE TITLE
Delete messages on the device of the chat partner 

### ISSUE THREAD

**Issue by chatonick** [deltachat/deltachat-android#325]
May be you add such chat options as Telegram killer feature: self-destructing after specific time messages and chats and autodeleting messages on other side of the conversation after deleting on one side.

**Comment by chatonick** [comment]
> In general, there is nothing that really prevents one of the users making a copy of the "self-destructing messages" or from messages that are deleted on "both sides of the conversation".

No. It's not for protection from known contact, it's for protection when the contact device gets into the hands of others. In this case I can delete the entire history remotely. You can make a checkbox or option in the chat which will need to enable on both sides.

> we already had an issue for this
Not only messages but also chats if I want to have some chats automatically deleted on my device after some time.

**Comment by r10s** [comment]
okay, things get clearer now :)

so, this issue is about 
(a) self-destructing messages as #99 and
(b) the option to delete messages on the devices of your chat partner (related to #198)

> it's for protection when the contact device gets into the hands of others.
> In this case I can delete the entire history remotely.

sounds reasonable, in a way. however, this won't work if the device is offline; possibly one of the first things an attacker would do. also this would introduces completely new attack vectors and possibly abuse.
  
maybe a device-password or device-encryption would be better here. maybe an additional delta-password.

**Comment by testbird** [comment]
> "Verified chats"

Beware "verfied" may rather mean "someone has captured a QR that can be freely copied and abused" not "keys one-to-one confirmed through another channel" => https://github.com/deltachat/deltachat-core/issues/168

**Comment by r10s** [comment]
> someone has captured your QR that can be freely copied and abused

but this cannot happen without you will notice it.

however, all this is subject to change, it's currently not even beta and we decided to make it static for simplicity.

it's also an open question in the spec, see http://countermitm.readthedocs.io/en/latest/new.html#open-questions , and i think it would be better to discuss this there, see https://github.com/nextleap-project/countermitm/

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
