### ISSUE TITLE
Show dates on messages

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android#326]
Hi

It would be so nice if the messages have dates on them. I am looking at my chat history, and I do nto know when those messages were sent for instance. Some of of them have a portion of the previous meessage where I can see, but most messgaes lack date information.

At least something like, 3 days ago, 1 month ago etc would be nice.

thanks

**Comment by gerroon** [comment]
Ok I totally missed the "date" tags well because my chats are done in long sessions so I had to actaully scroll up a bit to see the a date line. But still it would be nice if the dates are also shown on messgaes "optionally",.

Conversations does it thatw ay and it does not take much of a space.

**Comment by violoncelloch** [comment]
Or date tags could be shown as overlay in the top section (at least if users scroll up the chat history)
