### ISSUE TITLE
Provide video demonstrating FOREGROUND_SERVICE_DATA_SYNC

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3260]
We need to "provide a video demonstrating how your app uses the FOREGROUND_SERVICE_DATA_SYNC permission for the tasks you've selected" to be able to update on Google Play.

Here is the video:

https://github.com/user-attachments/assets/0a8f2d91-910f-4e54-972f-1f7f387347fb

**Comment by adbenitez** [comment]
the app was approved for publishing
