### ISSUE TITLE
Rename fastline to fastlane

### ISSUE THREAD

**Issue by licaon-kter** [deltachat/deltachat-android#3274]

**Comment by adbenitez** [comment]
oops! btw, even before the rename, changelogs were not picked up by F-Droid or displayed in the "what is new" section in the app, that is why we renamed the metadata/ folder to a fastlane structure, but it seems fdroid still supports the old structure but it was not working for some reason for Delta Chat, maybe related to the 4 split apk situation? (the version number of the x86_64 arch was used for the changelog

**Comment by licaon-kter** [comment]
Theory goes like this: highest compatible `versioncode.txt` is read

Hence, after the split, if you want to be perfect, you need to duplicate the changelog, one for each ABI

**Comment by licaon-kter** [comment]
Most users are on arm64? That would be enough imho. As you see fit. :)

**Comment by adbenitez** [comment]
so you have to duplicate the changelog for every arch for every language :skull: :skull: :skull: :skull: :skull: 

a `ChangelogVersionNumber:` field when? :rofl:
