### ISSUE TITLE
Add separate view for proxy settings

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3276]
Proxy (currently SOCKS5 only) settings are independent of configuration and can be changed without rerunning configuration.

Delta Chat can also have an icon leading to this screen when proxy is enabled, similar to what Telegram does:
![telegramproxy](https://github.com/user-attachments/assets/8c4201d4-ee7f-4918-8279-9ea6be251b84)

If proxy screen is separate from Password and Account screen, then it can also be made accessible for unconfigured accounts even during chatmail onboarding so users can configure local proxy before creating a chatmail account.

I thought about adding proxy information to connectivity view as a part of https://github.com/deltachat/deltachat-core-rust/pull/5926 but connectivity view is cluttered already so a separate native screen for proxy settings can solve this already.

Adding an icon is outside of the scope for this issue, first these settings need to be moved outside of "advanced settings" for server configuration.

**Comment by adbenitez** [comment]
one problem is that we already have the search and qr buttons, not sure if adding an extra button there will push the QR button to the menu, or if that is a problem at all (at least in the FAQ there are several pictures of the QR button and using it in explanations)

**Comment by adbenitez** [comment]
yup, I am working in a dedicated screen, that can be added to menus from registration activity to add/enable proxy even before registration in chatmail instances or typing email in classic login and leaking DNS queries
