### ISSUE TITLE
Start data sync foreground service task when FCM notification is received

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3281]
Currently FCM notifications are only used to start the application if it is in background so it can download the messages:
https://github.com/deltachat/deltachat-android/blob/56717d3f445a315e9a1623d1614464e6b8575359/src/gplay/java/org/thoughtcrime/securesms/notifications/FcmReceiveService.java#L95-L101

Notification is shown only once core downloads a new message from IMAP and decides that notification should be shown. It is done this way to prevent showing notifications for read receipts as the server does not know for encrypted messages if the message is read receipt or not.

Users however report that on some Android phones application fails to connect immediately after receiving FCM notification and only downloads the messages when user opens the application. Because of this FCM notifications effectively do nothing, application starts in the background but cannot download messages. This seems to happen at least on some stock Samsung phones. See <https://support.delta.chat/t/push-notifications-not-working-with-chatmail-server/3245/5>. It should also be possible to replicate on vanilla Android by going to App info -> Mobile data & Wi-Fi and switching off "Background data" or configuring non-existing proxy.

In this case it would be nice to be able to show a local notification saying something like "Failed to connect". This can be done by checking connectivity status when FCM notification is received and if it is `DC_CONNECTIVITY_NOT_CONNECTED` show a notification "Failed to connect". Normally this should not happen because if we can connect to FCM, we should at least be in the "connecting" state in Delta Chat unless OS blocks internet connectivity.

As this may be annoying to receive these notifications constantly on OS that don't allow fixing this behavior, it should be possible to disable the option and it should suggest disable this in the notification if it is enabled by default.

**Comment by iequidoo** [comment]
I have WhatsApp on my phone and it seems that it does the same. At least i see this "You may have new messages" when a bus with wi-fi passes  by me. But i don't remember that it shows any failures. A user may have a poor connection quite a long time, so i'm not sure we should scare users with errors.

**Comment by r10s** [comment]
shouldn't we also for  [`dc_accounts_background_fetch()`](https://c.delta.chat/classdc__accounts__t.html#a4b735a1e51222a06aa992773e42d06b0) [as on iOS](https://github.com/deltachat/deltachat-ios/pull/2071), instead of just hoping that starting the app is good enough? cc @link2xt 

iirc, `dc_accounts_background_fetch()` somehow does maybe_network and whatever is needed to perform a fetch - and can be called unconditionally. on iOS, things seem to work fine with that so far.

and yes, before `dc_accounts_background_fetch()` is called, we can add a permanent notification saying "Checking for messages..." that is removed just afterwards (and probably not really visible in the vast majority of cases)

still wondering, if there is a degradation somewhere, iirc, maybe due to the changed API version, android does things differently and kills app faster

**Comment by adbenitez** [comment]
we should probably also ask for disabling battery optimizations for the app even if push notifications are are available, I always felt not doing so could bring potential issues

**Comment by adbenitez** [comment]
> Just calling `maybe_network()` (we don't do it currently and I think should) and showing a notification with connectivity status is a smaller change.

well showing a "Checking for messages…" permanent notifications should be easy the question is how/when to remove it, because there is not clear "sync/fetch messages" blocking call in core api to know when core finished fetching, unless we use `dc_accounts_background_fetch()` as @r10s suggested, I guess

**Comment by r10s** [comment]
thanks a lot for the heads up, @link2xt and @adbenitez 

> the question is how/when to remove it

indeed, this is also unclear to me if we do not use `dc_accounts_background_fetch()`.

before `dc_accounts_background_fetch()`  was introduced, iOS watched  for DC_EVENT_CONNECTIVITY_CHANGED and checked `isAllWorkDone()` - it feels odd to go that way again, however, as we introduced `dc_accounts_background_fetch()` to solve error-prone `DC_EVENT_CONNECTIVITY_CHANGED/isAllWorkDone()`. or is there some other way, cc @link2xt 

> BTW, it sounds really odd to me that the app would need to show a permanent notification to get network access

imu, the  permanent notification is not to get network access, but to stay active - and this makes some sense, iirc, there is just no background activity allowed on newer androids without showing a permanent notification. that signal/whatsapp show one as well points into that direction.

anyway, worth a try. the notification as such is a simple change, we are using it already on various places (with dataSync-flag iirc). if it does not solve the issue, we can iterate :)

**Comment by r10s** [comment]
> But starting a foreground task makes the app considered to be in the foreground, right? Otherwise if the app has background access disabled it cannot download messages when receiving FCM notification at all.

i have to re-dive into that again, but iirc, one needs to add a "visible permanent notification" for work needed to be done in the background - this is eg. also the case when doing an export and leave the app - the export should be continued in background then.

iirc, androids/googles idea is that every bit running is somehow visible to the user. but the wording foreground/background is confusing here, maybe also in our own code :)
