### ISSUE TITLE
Bigger Android font and display sizes cause truncated reaction bar

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#3291]
- Android version:
Android 13 & 14.

- Devices:
Google Pixel 8 & Samsung Galaxy A71.

- Delta Chat version:
1.46.13.

- Expected behavior:
The reaction bar is not truncated when the sizes for font and display in Android are set to high levels.

- Actual behavior:
The reaction bar is truncated when the sizes for font and display in Android are set to high levels.

- Steps to reproduce the problem:
-- Set the sizes for font and display in Android to high levels.
-- Open a chat and long-tap a message you would like to react to. (Result: The reaction bar is truncated, the three-dot icon on the right is invisible and cannot be selected.)

- Screenshot:
![grafik](https://github.com/user-attachments/assets/228497e9-c4ad-4d3b-81d9-841c54eb4fcc)

- Logs:
N/A.

**Comment by r10s** [comment]
cmp https://github.com/deltachat/deltachat-android/issues/3047
