### ISSUE TITLE
Add info about notification permission to the log

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3305]
Here we should have some info about notification permission:
https://github.com/deltachat/deltachat-android/blob/e6f9eda78727a8f06af6df0994910cb6bca44179/src/main/java/org/thoughtcrime/securesms/LogViewFragment.java#L244-L249

We ask for the permission here:
https://github.com/deltachat/deltachat-android/blob/e6f9eda78727a8f06af6df0994910cb6bca44179/src/main/java/org/thoughtcrime/securesms/ConversationListFragment.java#L200-L223

Otherwise when user reports that notification are not working on Android >=13 we don't know if it is just because they denied notification permission on the first start.

**Comment by adbenitez** [comment]
> Otherwise when user reports that notification are not working on Android >=13 we don't know if it is just because they denied notification permission on the first start.

we also have a notifications enabled/disabled per account, but I assume that is logged by core in the `dcContext.getInfo()` call?

**Comment by iequidoo** [comment]
> we also have a notifications enabled/disabled per account, but I assume that is logged by core in the `dcContext.getInfo()` call?

`is_muted` is logged in Core's `get_info()`, but it has no effect in Core, afaiu it's only checked in UIs.
