### ISSUE TITLE
Show self-name in title bar

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#3307]
with instant onboarding and chatmail servers multi-profile usage is more common, users that have multiple profiles often get confused or find it hard to know which profile they are using

in ArcaneChat the user's display name is displayed in the top bar, which fits well since the avatar is displayed there, in official DC the avatar is displayed but then the text "Delta Chat" which looks a bit weird/odd more now that clicking it shows the account switcher

**Comment by r10s** [comment]
if there is only one account, however, i'd stay with the current title "Delta Chat", not everyone wants to read ones name all the time without additional benefits, and this is also what ppl know from most other apps

**Comment by adbenitez** [comment]
one could argue that even then it is fine since clicking in it opens the account switcher and it is besides the avatar, it is good to remember what is your current display, ex. to realize you have set your name to "your honeybee" before sending an important email to your boss etc.

**Comment by r10s** [comment]
yeah, one can argue anything :)
however, i am not aware of real complains in that direction.

the "Delta Chat" in the title after installation also has the task to let ppl know about the app, and to let ppl learn the app name :) i have somehow the feeling, it is better to stay with that for the beginning, it also looks clearer, esp. if names are longer.

so i would fix the issue on-point, and go for showing the name only if there is really a second account

**Comment by adbenitez** [comment]
(I would say it helps to discover you can tap there to discover the account switcher, people asked for this feature before multi-accounts even existed, that is why DeltaLab introduced that feature even before multi-account existed, having the app name there is pretty useless as it is in the launcher etc. it is not like you have to advertise it to the user all the time :sweat_smile: , but yeah doing it for multi-account setup only is an improvement already)

**Comment by r10s** [comment]
> I would say it helps to discover you can tap there to open the account switcher

we agreed in other discussions before, that multi-account is already advanced usage, most ppl have only one account, and it is good if they do not directly start with multi-account usage. therefore, it is okay, if adding multiple accounts is not directly in ones face. and once you add a second account, you know the way to switch
