### ISSUE TITLE
Account deletion confirmation dialog takes a while to appear in big accounts

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#3308]
this is because the computation of the account size takes a few seconds, maybe display "..." or "--" there and make the core API call in a thread to load dynamically? what will happen if user click "delete" button and the API call didn't returned yet?? (cc @link2xt) 

other option would be not to display the account size, but it is nicer to know

**Comment by iequidoo** [comment]
`get_account_file_size()` (if it's what is used) can fail, but nothing else should happen (i.e. it shouldn't deadlock or so). Still, it makes sense to wait when it finishes before closing the dialog window.
