### ISSUE TITLE
Report existence of media cache compressor

### ISSUE THREAD

**Issue by theamericanaccount** [deltachat/deltachat-android#3313]
Hello, I wanted to inform users and developers a silly but handy cached video compressor for Delta Chat has just been published on the [ur](https://github.com/themartiancompany/delta-chat-compressor-ur) Github mirror.

Clearly it requires root, but let's be honest, is really a device without root something more than an expensive intelligence-offending toy?

Anyway, with a tool such as the above is very possible to keep chatting for a long while without having to dump or trim the message cache for a very very long time.

So, have a good day!

**Comment by adbenitez** [comment]
hi, there is nothing we can do with that information, this issue tracker is for issues/bugs, for interaction with the Delta Chat community there is the forum https://support.delta.chat,

by checking that repo it is not clear to me if you are a spammer or what is that about, thanks in any case :)

**Comment by theamericanaccount** [comment]
What do you mean a spammer, what's wrong with the repo?

**Comment by Gh0stz0x** [comment]
@theamericanaccount 
He means that the source code was not found from the link https://github.com/themartiancompany/delta-chat-compressor-ur.
So it was legitimate to think of a form of spam to promote one's own future project.
He thanked you anyway and directed you to the Forum where requests for new features are made or where one promotes one's own bots, codes, etc.

**Comment by theamericanaccount** [comment]
@Gh0stz0x it's okay, I think I look like a spammer because all my activity is within `themartiancompany` namespace so it may be not visible from profile page.

Actually I have written and published it because it's a bug to me that storage fills up, so I was wondering if you were willing to let one tune ffmpeg prameters in delta directly and dynamically to avoid that happening.

I mean, I'm gonna do that in the compressor but it would be nice if delta was to do it directly.

**Comment by theamericanaccount** [comment]
Also it's not like delta doesn't have an issue with the compressor currently as if you try to send a video bigger than around 50mbs the compression is gonna get stuck and the phone locks down.
