### ISSUE TITLE
If Alice is only forward-verified, the green checkmark is shown, but not everywhere

### ISSUE THREAD

**Issue by iequidoo** [deltachat/deltachat-android#3314]
I'm Bob and i scanned Alice's QR code, but haven't yet received `vc-contact-confirm`. I see a chat with Alice with green checkmark, if i enter the chat, i also see green checkmark. If i tap on Alice (above the chat), i see their contact with green checkmark and "Introduced by me". But if i tap on `+` in the main window (to create a new chat), i see Alice w/o green checkmark.

Also i can't add Alice to verified groups. Afaiu the idea is that Alice may not have me verified, so it's not reliable to add Alice to verified groups. At the same time i can send messages to Alice which is also not reliable, but afaiu this is a way to resolve this situation somehow, e.g. by rescanning their QR code. This is just for the record.

The same behaviour i see in DC Desktop. I think that the green checkmark should be shown everywhere for consistency, but when adding such Alice to a verified group, just don't allow to select them, maybe with the same explanation message as currently.

**Comment by adbenitez** [comment]
ftr, there are some ideas to actually remove the verification checkmarks, and signal instead when there are no encryption etc.

**Comment by iequidoo** [comment]
The things are complicated because there are 4 encryption/verification stages:
- No encryption
- Nonverified encryption
- Verified encryption
- Verified encryption + backward verification

At least in the last two cases the contact should be displayed samely i think. Most of the time users don't want to dive into these details.

**Comment by r10s** [comment]
android just renders the icon as core tells using [`dc_chat_is_protected()`](https://c.delta.chat/classdc__chat__t.html#adccb89a809982f91a400fe3a3da83364) and [`dc_contact_is_verified()`](https://c.delta.chat/classdc__contact__t.html#a287ad50725bd26f8a8a7df36ce56b91f).

so, there seems not be an actionable item for android, however. that needs to be changed in core, if ppl agree on that. and yes, maybe the timing for changes is not-so-good - and may raise new cornercases and bugs, maybe even more - as we consider to rethink the "encryption signals" at some point in 2025

**Comment by iequidoo** [comment]
In general this issue is about this:
> But if i tap on `+` in the main window (to create a new chat), i see Alice w/o green checkmark.

It seems that currently `dc_contact_is_verified()` is used for that on Android/Desktop, but this call also checks backward verification. But backward verification only matters when adding the contact to verified groups. Seems it should be renamed to `dc_contact_is_verified_for_groups()` or smth like this, and a new `dc_contact_is_verified()` should only check forward verification because it's sufficient to have a protected 1:1 chat. Then the only place where only forward-verified Alice is shown w/o a green checkmark is the "Add Members" window, but there it's ok and also an explanation message is shown already if i try to add such a contact to a verified group.
