### ISSUE TITLE
make sure, 3-letter-language-codes that are supported by the system are supported by Delta Chat as well

### ISSUE THREAD

**Issue by hosseinabaspanah** [deltachat/deltachat-android#3318]
After using the ability to select the program language separately from the system language; Local languages ​​that are not available in the phone cannot be used in Delta Chat...

If you don't understand what I mean, tell me so I can explain more...

If there is a way to enter local languages ​​in Android and Google has provided a platform for Android translation to solve the said problem. Please let me know...

**Comment by r10s** [comment]
> Local languages ​​that are not available in the phone cannot be used in Delta Chat

which are these languages? and what is the manufactor and android version?

however, it is known and accepted that there are situations where app language is not yet available, see https://github.com/deltachat/deltachat-android/pull/3241 for reasoning why we went for simplifying the code here.

at least on recent android, i am able to select any of the supported languages for Delta Chat - although as "system language" only "English" is available:

<img width="380" alt="Screenshot 2024-09-26 at 16 41 36" src="https://github.com/user-attachments/assets/af023738-58ad-41b6-bb60-10b2663b2f48">
<img width="380" alt="Screenshot 2024-09-26 at 16 42 12" src="https://github.com/user-attachments/assets/0c40dd28-93ed-4a8b-9855-8967df7a0f51">

**Comment by hosseinabaspanah** [comment]
> > Local languages ​​that are not available in the phone cannot be used in Delta Chat
> 
> which are these languages? and what is the manufactor and android version?
> 
> however, it is known and accepted that there are situations where app language is not yet available, see #3241 for reasoning why we went for simplifying the code here.
> 
> at least on recent android, i am able to select any of the supported languages for Delta Chat - although as "system language" only "English" is available:
> 
> <img alt="Screenshot 2024-09-26 at 16 41 36" width="380" src="https://private-user-images.githubusercontent.com/9800740/371219221-af023738-58ad-41b6-bb60-10b2663b2f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODIzNDMsIm5iZiI6MTcyNzM4MjA0MywicGF0aCI6Ii85ODAwNzQwLzM3MTIxOTIyMS1hZjAyMzczOC01OGFkLTQxYjYtYmI2MC0xMGIyNjYzYjJmNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMjAyMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTUzYTFlZmUwOTVhNjIzOTcwYzJjMjc2ZTM0MGZjZjBlYWUzYWJkNGM3ZGMyYTY0MzA2YmZmYTAyY2Y3YWQzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wfdErFlYbqAXvwzGF3ZTZ3-O0yJHgK1AHbTBtUHea0c"> <img alt="Screenshot 2024-09-26 at 16 42 12" width="380" src="https://private-user-images.githubusercontent.com/9800740/371219212-0c40dd28-93ed-4a8b-9855-8967df7a0f51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODIzNDMsIm5iZiI6MTcyNzM4MjA0MywicGF0aCI6Ii85ODAwNzQwLzM3MTIxOTIxMi0wYzQwZGQyOC05M2VkLTRhOGItOTg1NS04OTY3ZGY3YTBmNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMjAyMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q1ZTc4NzA4MTBjYTY1MjkyYjA0MmJhZmMyMzNkMDFmOTAxMDc1ODEyZjU5ZTUzNzg1YTI2OTNiNmY5N2I1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RRQGxfvQbtlXnHgAeGXYQo_7VRyia4qnI5MJ-2eXfDo">

I meant the language of Luri Bakhtiari...

And in the case of Android, I meant clearly; I meant Luri Bakhtiari's language because it is not in the phone's languages list, so with the changes in the new version of the program, this language cannot be used...

**Comment by hosseinabaspanah** [comment]
According to the information of Android, I think you can add this language to the list of languages ​​by adding Luri Bakhtiari's language code...

For example:

<?xml version="1.0" encoding="utf-8"?>
<locale-config xmlns:android="http://schemas.android.com/apk/res/android">
   <locale android:name="en-US"/>
   <locale android:name="en-GB"/>
   <locale android:name="bqi"/>
   <locale android:name="ja"/>
   <locale android:name="zh-Hans-MO"/>
   <locale android:name="zh-Hant-MO"/>
</locale-config>

**Comment by hosseinabaspanah** [comment]
<?xml version="1.0" encoding="utf-8"?>
<locale-config xmlns:android="http://schemas.android.com/apk/res/android">
   <locale android:name="en-US"/>
   <locale android:name="en-GB"/>
   <locale android:name="fr"/>
   <locale android:name="ja"/>
   <locale android:name="zh-Hans-MO"/>
   <locale android:name="zh-Hant-MO"/>
</locale-config>

**Comment by hosseinabaspanah** [comment]
![Uploading Screenshot_۲۰۲۴۰۹۲۷_۰۰۲۳۵۲_Chrome.jpg…]()

**Comment by hosseinabaspanah** [comment]
![Screenshot_۲۰۲۴۰۹۲۷_۰۰۲۳۵۲_Chrome](https://github.com/user-attachments/assets/3c537ee4-765e-4ea4-80e9-8dd7ca13c959)

![Screenshot_۲۰۲۴۰۹۲۷_۰۰۲۴۰۷_Chrome](https://github.com/user-attachments/assets/a9f89b0f-83f8-49f1-9453-709a3894a529)

**Comment by adbenitez** [comment]
> According to the information of Android, I think you can add this language to the list of languages ​​by adding Luri Bakhtiari's language code...

we already do that, the file is automatically generated and it has the "bqi" code there, but for some reason other languages appear but not Bakhtiari, it seems the system is ignoring it or not recognizing it as supported value (the system is the one putting the language name, we just declare the codes) so if the system doesn't know the language name of that code it might be ignoring it completely

**Comment by hosseinabaspanah** [comment]
> > According to the information of Android, I think you can add this language to the list of languages ​​by adding Luri Bakhtiari's language code...
> 
> we already do that, the file is automatically generated and it has the "bqi" code there, but for some reason other languages appear but not Bakhtiari, it seems the system is ignoring it or not recognizing it as supported value (the system is the one putting the language name, we just declare the codes) so if the system doesn't know the language name of that code it might be ignoring it completely

What do you think is the solution now???
How to solve this problem from the Android side???

Is there any hope to solve this problem from the Android side???

**Comment by adbenitez** [comment]
Android system needs to update this, not sure why they don't support the language code at all, the only thing we could do is to revert everything and add the language selector to the app again which adds more bugs and effort in maintenance on our side, that is why we decided to delegate it to the system :(

**Comment by hosseinabaspanah** [comment]
> Android system needs to update this, not sure why they don't support the language code at all, it will be good if we could report this to the AOSP somehow?, the only thing we could do is to revert everything and add the language selector to the app again which adds more bugs and effort in maintenance on our side, that is why we decided to delegate it to the system :(

I'm glad you noticed this problem...

Now that Android doesn't update these codes, and I should say, it doesn't care about the three-letter language codes. Don't you think it's better for developers to report this or not to use this new Android feature until this problem is fixed???

**Comment by adbenitez** [comment]
maybe it is just that we are doing something wrong, ex: https://stackoverflow.com/questions/10330893/android-resources-for-languages-with-only-3-letter-codes

**Comment by hosseinabaspanah** [comment]
> maybe it is just that we are doing something wrong, ex: https://stackoverflow.com/questions/10330893/android-resources-for-languages-with-only-3-letter-codes

What should I do to solve this big problem???

Do I have to follow up to solve this problem???

**Comment by adbenitez** [comment]
we need to investigate more about the 3 letter codes as this seems to be happening to all of them so we are doing something wrong, then we need to change the code names of the /res/values-XXX/ folders to the proper format and check that then android picks it up, you don't have to do anything unless you want to help with it and look into the problem which is very much appreciated

**Comment by hosseinabaspanah** [comment]
> we need to investigate more about the 3 letter codes as this seems to be happening to all of them so we are doing something wrong, then we need to change the code names of the /res/values-XXX/ folders to the proper format and check that then android picks it up, you don't have to do anything unless you want to help with it and look into the problem which is very much appreciated

If this problem is not only related to Lori Bakhtiari's language, there is less reason to worry; But in any case, this issue should be followed up by Android and also developers to solve it...

I only do translation work and don't know much about android programming. But if I can follow up with you to solve this problem, I will be very happy...

Please, if there is new material to solve this problem; Let me know here...

**Comment by r10s** [comment]
in general, these three language codes come from transifex, might totally be, android is using sth different.

looking at the "language editor" in android studio, indeed it looks as if the two languages using three letter codes are undetected (all other have a real name)

![Screenshot 2024-10-04 at 13 34 03](https://github.com/user-attachments/assets/51c87678-5cea-46b7-ab7e-fa1fadc66183)

so, we might need some mapping for them at https://github.com/deltachat/deltachat-android/blob/main/.tx/config

to the other part of this issue, _supporting languages that are not supported by the system:_ that should be advocated in android-sources first. otherwise it surely can become a [feature proposal in the forum](https://support.delta.chat/c/features/6), that then, however, will compete with other feature requests for limited resources, maintainability etc.

however, let's first see where the bug fix will bring us :)

**Comment by hosseinabaspanah** [comment]
I need to mention here that I mistakenly used Luri's Latin font, when I should be using RTL font...

Soon, I will solve this problem by translating Delta Chat with the Rtl line for Luri, and there is nothing to worry about in this regard...

I just wanted to say here so that you are also informed...

**Comment by r10s** [comment]
> maybe it is just that we are doing something wrong, ex: https://stackoverflow.com/questions/10330893/android-resources-for-languages-with-only-3-letter-codes

the mentioned [BCP 47](https://www.rfc-editor.org/info/bcp47) is indeed interesting and also referred to in [official android docs](https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources)

according to that, it seems possible to chose the script for a language [^1]

still, i do not see a reference for android using 3-letter-languages in BCP 47, maybe it works, that needs to be tried out. when renaming the folder accordingly, the "correct" name is still not picked up - but that might be on purpose. at least, things do not get worse it seems, a folder `values-b+bqi` is still shown

signal otoh uses 3-letter-languages without BCP 47 at https://github.com/signalapp/Signal-Android/tree/main/app/src/main/res/values-yue - but might be that never works as well ...

[^1]: script variations are recently a topic at  https://github.com/deltachat/deltachat-desktop/issues/4167#issuecomment-2393922845 and https://github.com/deltachat/deltachat-android/issues/3213

**Comment by adbenitez** [comment]
> signal otoh uses 3-letter-languages without BCP 47

they don't support system's per-app language at all it seems

**Comment by r10s** [comment]
yes, that's true

**Comment by hosseinabaspanah** [comment]
my dear friends
I will check and read your comments very quickly...

In your opinion, shouldn't this problem be solved from the Android side???

**Comment by r10s** [comment]
it is still unclear to me, seems we're still in research phase ;) i am out for today, but maybe @adbenitez has more insights

**Comment by adbenitez** [comment]
@r10s wait a sec! I just realized the android settings are grouping languages! ex. instead of listing Portuguese and Portuguese (Brazil) there is only Portuguese and when you select it then what you see is a list of available regions including Brazil, I clicked in some of the arabic options and there was two options but I don't understand them since they are in weird arabic scripts, so with a high chance the language is already available or after using the other "correct" format it will could be available inside a subsection  

@hosseinabaspanah  how is the language name in the original scripts?

**Comment by hosseinabaspanah** [comment]
> @r10sیک ثانیه صبر کن تازه متوجه شدم تنظیمات اندروید گروه بندی زبان هاست! سابق به جای لیست کردن پرتغالی و پرتغالی (برزیل) فقط پرتغالی وجود دارد و وقتی آن را انتخاب می کنید، لیستی از مناطق موجود از جمله برزیل را می بینید، من روی برخی از گزینه های عربی کلیک کردم و دو گزینه وجود داشت اما متوجه نشدم آنها از آنجایی که آنها با حروف عربی عجیب و غریب هستند، بنابراین با احتمال زیاد زبان از قبل در دسترس است یا پس از استفاده از فرمت "صحیح" دیگر می تواند در یک زیربخش در دسترس باشد.
> 
> @hosseinabaspanah نام زبان در اسکریپت های اصلی چگونه است؟

I don't understand what you mean so I can guide you...

In what script do you mean???

**Comment by hosseinabaspanah** [comment]
> @r10s wait a sec! I just realized the android settings are grouping languages! ex. instead of listing Portuguese and Portuguese (Brazil) there is only Portuguese and when you select it then what you see is a list of available regions including Brazil, I clicked in some of the arabic options and there was two options but I don't understand them since they are in weird arabic scripts, so with a high chance the language is already available or after using the other "correct" format it will could be available inside a subsection
> 
> @hosseinabaspanah how is the language name in the original scripts?

I don't understand what you mean so I can guide you...

In what script do you mean???

**Comment by adbenitez** [comment]
Luri Bakhtiari, how do you write it in the native language/script, same as Spanish appears as "Español" in the native language in the selector, I expect Luri Bakhtiari to also appear in the native script

**Comment by hosseinabaspanah** [comment]
> Luri Bakhtiari, how do you write it in the native language/script, same as Spanish appears as "Español" in the native language in the selector, I expect Luri Bakhtiari to also appear in the native script

Now I understand what you mean...

In the native script, it is usually written like this:::

لۊری بختیاری

**Comment by hosseinabaspanah** [comment]
Was it useful and did you get a result???

Search for this name too, because unfortunately the Luri extension is not available in the selected ISO name...

Bakhtiari or بختیاری

**Comment by adbenitez** [comment]
so it seems the place where it should appear (if at all)  is inside Persian/Farsi, but when I go there there is only the option to select Iran region and that is it, there is no further option to select Bakhtiari, at least using `values-b+bqi`, maybe the problem is that the name is not correct, there is a "Table 2. Configuration qualifier names." at https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources with some examples

another option would be to look into other apps that supports this language and check the codes they use and if they support system language or custom internal selector

**Comment by hosseinabaspanah** [comment]
None of the programs for which I have translated Luri Bakhtiari use this new Android option, and they all use the same internal program selector, which does not cause any problems...

**Comment by adbenitez** [comment]
for Luri this is the only code that seems to be supported according to Android Studio:

![image](https://github.com/user-attachments/assets/d7eee17f-5df2-444e-aa5a-15faee832e37)

I tried using `values-lrc` and `values-b+lrc` but **it didn't work** I am at a lost with this, it doesn't make much sense when the wizard of Android Studio is generating the `values-XXX` folder but then the system doesn't seem to support it, it seems this is some small minority language that Android doesn't give proper support :'(

for ckb (Central Kurdish/Sorani) this is the only code that appears:

![image](https://github.com/user-attachments/assets/28c0f647-f4e1-4b4d-bd4d-17b7c15b7fba)

I tried using `values-ku` and it also **it didn't work** in the per-app language selector :exploding_head:

**Comment by adbenitez** [comment]
it seems the only options we have are:

1. revert the removal of the in-app language selector (which was quite some refactoring across several files)
2. drop support for bqi and ckb languages, delete their values-XXX folder
3.  keep their values-XXX folder and do nothing, just hope eventually Android will update and fix this problem

(FTR: I tried in CalyxOS, don't know if in other systems it works, maybe reporting to CalyxOS is a good first step, they fixed the problem we had with the system camera after I reported it)

**Comment by hosseinabaspanah** [comment]
> it seems the only options we have are:
> 
> 1. revert the removal of the in-app language selector (which was quite some refactoring across several files)
> 2. drop support for bqi and ckb languages, delete their values-XXX folder
> 3. keep their values-XXX folder and do nothing, just hope eventually Android will update and fix this problem
> 
> (FTR: I tried in CalyxOS, don't know if in other systems it works, maybe reporting to CalyxOS is a good first step, they fixed the problem we had with the system camera after I reported it)

In order to report this problem and support two other Luri codes, i.e. bqi and luz, what method should we use to inform Android???

**Comment by adbenitez** [comment]
> In order to report this problem and support two other Luri codes, i.e. bqi and luz, what method should we use to inform Android???

I don't know, I found this post asking them to add Sorani Kurdish:
https://support.google.com/android/thread/32107365/hello-please-add-sorani-kurdish-language-to-the-system?hl=en

**Comment by hosseinabaspanah** [comment]
> > In order to report this problem and support two other Luri codes, i.e. bqi and luz, what method should we use to inform Android???
> 
> I don't know, I found this post asking them to add Sorani Kurdish: https://support.google.com/android/thread/32107365/hello-please-add-sorani-kurdish-language-to-the-system?hl=en

Please ask them to add Luri language codes...

**Comment by hosseinabaspanah** [comment]
I feel that the people of Lurs should apply collectively for the support of the Lori language codes so that they can follow up faster...

Or in other words, a group of developers together asking Google to update the three-letter codes and support them all...

**Comment by r10s** [comment]
k, i did a little test at #3359 to make sure, the way we're adding three-letter-languages are correct.

turns out, as already suspected `cbk` and `bqi` are unsupported by android.

i would still leave the folders here, as they are correct - and it might be there are android OS out that have better language support. and then it would be possible to pick them up.

as we can reasonably only maintain languages that are also supported by the system. also these concrete languages are somehow unmaintainted and/or raise questions wrt script. we cannot really offer support for that, even though we generally take care for small groups, that time is better invested somewhere else. i suggest to advocate in the correct android repo/issue for adding them.

if you point us to some repo/issue i am happy to comment there, saying that Delta Chat would love to support additional languages.
