### ISSUE TITLE
new profile-name in title should get nicer truncation

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#3331]
currently, the title is cut off within a word, which does not look nice and may result in some confutsion as well.

![Screenshot 2024-10-04 at 18 13 42](https://github.com/user-attachments/assets/7d50b7c3-e395-49d8-b70a-7af71ec7097c)

we should cut the title as we're doing for chatnames, sth. as `ellipsize="end"` or so

successor of https://github.com/deltachat/deltachat-android/pull/3329

**Comment by adbenitez** [comment]
this works fine for me:

![image](https://github.com/user-attachments/assets/ce2bc235-dd40-42de-89c2-2796d1aec56c)

**Comment by r10s** [comment]
maybe a bug in some android version. using an email address like word on android5 does not show the ellipsis - i double checked, it is same as in the initial screenshot.

however, using a name or sth. else on android5 truncates as expected.

android14 truncates email adresses as expected as well.

so, yeah, things seem good enough - esp. as we force entering a name now, the case an email address is shown is rare
