### ISSUE TITLE
cannot start camera app when trying to attach a picture

### ISSUE THREAD

**Issue by haeckser** [deltachat/deltachat-android#334]
_Please read the guidelines linked above, especially when you are a first time contributor. Remove this text and provide some basic informations below, if applicable. Remove template content that is not applicable._

**Delta Chat version**

0.17.3, but also observed with 0.17.x 

**Expected behavior**

when pushing attachment symbol, pictures and apps are shown. When selecting camera it raises and after taking the picture it is automatically added as attachment

**Actual behavior**

app is not raising. Nothing happens except that the app and picture preview closes. Same behaviour as if I cancel taking and sending a photo, No message, no action.Can be raised independent of DC and existing pictures can be selected and will be transferred

**Steps to reproduce the problem**
1. select a chat
2. select attachment symbol
3. select camera 

**Screen snapshots**

If applicable …

**Debug logs**

If applicable, debug logs can be copied from within the Delta Chat app: 

no logs from the related time frame -> no logs available
BUT this problem happens on other devices too (Samsung tablet with Cyanomodgen  (Android 6.0.1), Archos Tablet with Android 7.0 and Cygnus phone with Android 6. 
Video is also blocked. 

Alternatively from the Android system log:

` adb logcat -v time -s DeltaChat `

This log contains private data (e.g. mail address, provider information) which shall be removed or anonymised prior to posting.

**Comment by t-oster** [comment]
You can test this by going to settings->apps on your android, go to the DeltaChat app and under permissions add the camera permission. if it works, it will be fixed in the next version.
