### ISSUE TITLE
Account name/address in title bar not changed back to "Delta Chat" after all but current account are deleted

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#3342]
- Android version:
Android 14.

- Device:
Google Pixel 8.

- Delta Chat version:
1.46.15 (nightly built 2024-10-06).

- Expected behavior:
After all but the current Delta Chat account have been deleted, the name/address displayed in the title bar of the only account left is changed back to "Delta Chat".

- Actual behavior:
After all but the current Delta Chat account have been deleted, the name/address displayed in the title bar of the only account left is not changed back to "Delta Chat".

- Steps to reproduce the problem:
-- Create at least two Delta Chat accounts.
-- Remove all but the current account. (Result: The name/address of the only account left is still displayed in the title bar.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by adbenitez** [comment]
it is back to delta chat eventually, ex. when you open a chat and go back again

**Comment by r10s** [comment]
>  Remove all but one account

for reproducing: it is important to delete the _other_ accounts, not the selected account.

**Comment by gerryfrancis** [comment]
> for reproducing: it is important to delete the other accounts, not the selected account.

@r10s Many thanks, I updated the description accordingly.

**Comment by adbenitez** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/3343

**Comment by gerryfrancis** [comment]
Works fine now, many thanks to everyone involved! :)

**Comment by r10s** [comment]
thanks for checking and for coming back!
