### ISSUE TITLE
QR code scanner for "Add as Second Device" should have an option to paste from clipboard

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3369]
Currently 3-dot menu only has "Troubleshooting".

Same for "Scan Invitation Code", it should have a way to paste from clipboard.

See https://support.delta.chat/t/how-do-i-add-a-second-device-that-doesnt-have-a-camera/3289

**Comment by r10s** [comment]
we had a bit hidden fallback by the option to use the scanner available from the chatlist - however, that was forgotten to adapt by the move to DC_QR_BACKUP2, i did a fix at #3370 

but yes, we should probably have a paste option also directly at "add second device scanner"
