### ISSUE TITLE
periodic smtp thread interruptions

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#339]
>  [from #337] @testbird the smtp-idle loop every minute is by design currently. if there are no jobs to do, this should take no time (there is no network involved) and results in a simple guarantee that failed jobs are restarted at most after a minute (if a job fails and there is network available, the restarting time is only 1 second)

(besides filling the logs, pushing out interesting entries)

Won't the frequent interruptions prevent sending longer attachments in slow networks (cellular!)? Instead of unconditional interruption every x minutes, shouldn't only the actual jobs have timeouts, and shouldn't that kind of timeouts already be part of the SMTP protocol itself? 

SMTP or even TCP/IP would look like the right place to detect if the connection has stalled. Possibly with a reduced timeout, if the system default really is too long (desktop?).

**Comment by testbird** [comment]
Principle: pass back error messages, instead of preventive interruptions.

**Comment by r10s** [comment]
> Won't the frequent interruptions prevent sending longer attachments in slow networks (cellular!)?

no. the interruption only takes place when we're really in idle. the SMPT-thread looks like the following:

```
void* smtp_thread_func(void* context)
{
    while( true ) {
        dc_perform_smtp_jobs(context);
        dc_perform_smtp_idle(context);
    }
}
```

calling dc_interrupt_smtp_idle() will only interrupt dc_perform_smtp_idle(), not the jobs function.

> shouldn't only the actual jobs have timeouts,

if everything works well, timeouts are not used at all. If a message is sent, delta-core adds the message to the database and calls dc_interrupt_smtp_idle() immediately which results dc_perform_smtp_jobs() to be called where the message is really sent and the job is deleted.
only if sending fails, it is needed that dc_perform_smtp_jobs() is executed later. of course, the timing can be optimized, however, interrupting smtp-idle every minute is cheap as - other than IMAP-idle - there is absolutely no network involved.
and: for now it seems to be better to have an easy and reliable solution.

> shouldn't that kind of timeouts already be part of the SMTP protocol itself?

AFAIK timeouts have nothing to do with the SMTP protocol.

**Comment by testbird** [comment]
> dc_interrupt_smtp_idle() will only interrupt dc_perform_smtp_idle()

OK thanks, that's good, then. :)
Sorry I misinterpreted the logs here.

What makes me still wonder in the logs is that I see occasional `Interrupting SMTP-idle...` immediately followed by `Interrupting IMAP-IDLE...` maybe related to display on/off?, BUT only on one device (same brand and software).

> AFAIK timeouts have nothing to do with the SMTP protocol.

It's not relevant anymore, but even if not strictly defined in the protocol, I guess every library still needs to have a timeout for when there is no response (at least a prompt or ACK) from the other side upon a login, send or other command.

**Comment by testbird** [comment]
Anyway, an idea to silence the constant noise to only-if-needed would be to let dc_perform_smtp_jobs() itself do something to interrupt the (next) smtp-idle (or let it quickly return).  Maybe by setting a variable or call the interrupt function, only IF there is a job to do.

Something like limiting the number of retries for jobs would be needed anyway, so maybe fill the progress variable with the next job id to do?
