### ISSUE TITLE
app icon: "new messages count" overlay (badge count)

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#340]
Looks like an overlay showing the number of new messages is what many users look for, and is a reason for complains like: "I'm not getting any new messages".

~~Other apps seem to solve this (by adapting the icon themselves?) and create the same display behavior as in older OS versions?~~

**Comment by testbird** [comment]
The feature seems to be called "badge count", unfortunately I have no idea how this works.

**Comment by t-oster** [comment]
It looks like bade icons are:

- Not possible in Android via standard API
- Not recommended in Android because they are an iOS pattern, while android has the status bar for it
- Can only be achieved via custom launchers or using a widget

Source: https://stackoverflow.com/a/17565479/2858218

So the only option in my opinion is providing a widget which looks like the app icon and just starts the app. However the widget would have to be manually added by the user to the homescreen.

**Comment by r10s** [comment]
> but this won't work on stock Android.

then it's no option :) i think Delta Chat should always work fine without Google.

**Comment by t-oster** [comment]
To be clear this means on stock android it would fall back to just the app icon.

**Comment by r10s** [comment]
ahh, i see :)

**Comment by violoncelloch** [comment]
There are also launchers which count the unread notifications and create badges for all apps based on this...

**Comment by r10s** [comment]
might be, but there is also some active support in delta chat ... https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/NotificationsController.java#L738 ... but this is a mess ...

**Comment by testbird** [comment]
Looks like replacing the custom code with that lib, supporting all the different "workarounds" (and likely any stock android solution once possible) would be the way.

**Comment by t-oster** [comment]
Does not work on my Android (Oukitel K600 Plus, Android 7), so I won't implement this ;(

**Comment by testbird** [comment]
I could not find any custom-rom +  f-droid support for badges either. :-(
What about the widget option you mentioned, could that work with all devices?

**Comment by nutpantz** [comment]
https://developer.android.com/training/notify-user/badges

**Comment by testbird** [comment]
Saw badges get shown in android 8.

Is there already another issue that the permanent notification is sometimes visible and counted for the badge?
