### ISSUE TITLE
Missing notification tray icon

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android#341]
HI

I am not sure what it is called but there  used to be notification area bar where it said deltachat was running. Now it is neither there nor the setting for battery optimisations thing. 

I am using  deltachat-v0.18.2 on Lollipop.

thanks

**Comment by r10s** [comment]
we try a mode where both are not needed :)
- we use IMAP-IDLE as long as possible
- the permanent notification is only added as needed and typically not visible (it is typically added when the device is not used and the screen is off, this is a little experimental)

**Comment by gerroon** [comment]
@r10s 

I see but it was there before. So you guys removed it in the current release? Not that I needed it myself, I thought maybe it was not intentional.

**Comment by r10s** [comment]
@gerroon yes, we _try_ to get rid of it.
it was just there to allow Delta Chat receiving messages in background - under Android, esp. Google-Android, most apps will be killed when the device falls into doze mode.

These killed apps have the possibility to wake up via an timer every some minutes to eg. check for new messages in case of Delta Chat.

Google says, this is to save battery, however, a long-poll IDLE command probably saves more battery that doing a poll every some minutes, so we try to find a way to get a way around these useless restrictions ...
