### ISSUE TITLE
"localhost" as HELO/EHLO parameter leads to SMTP error

### ISSUE THREAD

**Issue by msk7-ripe** [deltachat/deltachat-android#342]
**Delta Chat version** 0.18.2

**Expected behavior** SMTP login

**Actual behavior** 
SMTP login error due to usage of "localhost" string as HELO/EHLO parameter.

**Comment**
Some strict-tuned mailservers require HELO/EHLO parameter to be FQDN as per RFC.

**Steps to reproduce the problem**
1. Setup new account to mailserver with SMTP logging on 
2. See "localhost" as EHLO parameter in server log

**What to fix**
Use domain name from email as EHLO parameter or make possible to input it directly in account setup.

**Comment by r10s** [comment]
moved to https://github.com/deltachat/deltachat-core/issues/223

**Comment by r10s** [comment]
thank you for your post, i've moved it to deltachat-core where it fits better imho :)
