### ISSUE TITLE
can not send or receive images

### ISSUE THREAD

**Issue by iminto** [deltachat/deltachat-android#3430]
Neither Android nor Windows clients can send or receive images, but text messages are normal.
It got stuck there and the picture couldn't be sent out

- Android version:14.0
- Delta Chat version: 1.48.0

1.46.0 is ok.

<img width="634" alt="delta" src="https://github.com/user-attachments/assets/b372b65b-59f3-4799-948b-0c5c56c42803">

**Comment by adbenitez** [comment]
that image doesn't show it is not possible to send images, could you record an small video of:
- go to the android app, 
- enter a chat, 
- select/attach an image,
- click send

then go to advanced settings and there is a "view log" option, click there and save the log file, then attach it here (you may want to anonymize the addresses that appear in it) alternatively send the log in private to me here:
https://i.delta.chat/#F2175B65C599D9AB58FDBE35A1D2B46E62A29658&a=friendscaaj3%40testrun.org&n=adb&i=_vLu0fUI53k&s=teNGaPzemPW

**Comment by iminto** [comment]
I get it，it's not a bug，but an user experience. 
﻿ 
When  I send up a picture,must add some text. 
You can't just send pictures separately

**Comment by adbenitez** [comment]
you DO can send images without any text, for example I just sent this one in the latest release for android 1.48.3:

![image](https://github.com/user-attachments/assets/903a9295-ba9d-408b-a443-8e61002f62d6)

**Comment by iminto** [comment]
I am so stupid. When I select a picture, the picture will be displayed in the chat dialog interface, but I still need to click the "send" button.

Some other software I have used do not have this interaction, so I am confused

**Comment by gerryfrancis** [comment]
@iminto Never mind, but thank you for coming back 👍 - and enjoy Delta Chat! :)
