### ISSUE TITLE
helpme add domain pls

### ISSUE THREAD

**Issue by jmsecurity05** [deltachat/deltachat-android#344]
hello if someone can help me I need to add a domain to delta to be automatic when you put user name u pass tnx

**Comment by jmsecurity05** [comment]
hello friend you can help me to add a domain to delta chat to be configured automatically I thank you

**Comment by t-oster** [comment]
You need to 

- find your SMTP/IMAP data,
- Create an XML like this https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration/FileFormat/HowTo
- Submit it here https://bugzilla.mozilla.org/enter_bug.cgi?format=guided#h=dupes|Webtools|ISPDB%20Database%20Entries like described here https://developer.mozilla.org/de/docs/Mozilla/Thunderbird/Autokonfiguration#ISPDB

**Comment by t-oster** [comment]
If it is your private domain, you can also just server your XML at `autoconfig.<your-domain>` or provide the MX record if the provider is already in the database (see https://developer.mozilla.org/de/docs/Mozilla/Thunderbird/Autokonfiguration)

**Comment by jmsecurity05** [comment]
No tunderbirt is Android client

**Comment by t-oster** [comment]
I know but DeltaChat uses the same mechanism and database as Thunderbird for autoconfig.

**Comment by jmsecurity05** [comment]
oh ok excuse my ignorance I'm not professional in this tell me then how should I proceed? I'm use apk editor and Android?

**Comment by jmsecurity05** [comment]
hello friend I ask you a little help please I've been trying for 5 nights and I do not really know how to do it I already have the XML file edited with the parameters but I do not know how to upload it so you can explain or help me upload the XML file Thank you

**Comment by r10s** [comment]
@jmsecurity05 if there are any open questions, feel free to use the user forum at https://support.delta.chat/ :)
