### ISSUE TITLE
Add my domain 

### ISSUE THREAD

**Issue by jmsecurity05** [deltachat/deltachat-android#345]
hello can help me to add a domain to delta chat to be configured automatically I thank you

**Comment by t-oster** [comment]
why are you writing twice??? duplicate of #344 . I already answered your question and you should provide more information.

**Comment by jmsecurity05** [comment]
Sorry sorry I want to add this domain to delta so that it is configured only with the mail and the password
jmsecuritypgp.com

 

imappro.zoho.com

993

smtp.zoho.com

465

**Comment by jmsecurity05** [comment]
No tunderbirt is Android
