### ISSUE TITLE
Do not send the message right away when content sharing was done from other apps

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android#347]
Hi

It would be very nice if DC does not send the message right away when some content is shared from other apps, it makes it impossible to add/ edit the content, it has to be a new message and this is confusing to non dc conversing situations.

**Comment by r10s** [comment]
i do not really understand this issue. when would you send the message? or do you suggest to modify already sent messages?

**Comment by gerroon** [comment]
Well the issue is, lets say you share a url link/content etc from another another app, it sends it as a separate message, it does not give me the chance to add additonal message, it sends it right away, and that looks like multiple emails to the other side if they are just using an email client.

**Comment by r10s** [comment]
ah, i see. like adding a description to an image.

**Comment by gerroon** [comment]
Yeah, exactly. GIve the user a chance to edit the message with sahred content before posting it.

**Comment by testbird** [comment]
Same "see in edior" preview might also be good when sending attachments from within DC.

**Comment by r10s** [comment]
i think most of these issues are targeted by the changes to the imap-jobs in v0.18.0 and newer versions.

**Comment by adbenitez** [comment]
I (and my friends) need this because we use an email service that have a cost, and we need to see the size of the voice messages (and other media) before sending it, since de size determine how much will cost the message.
