### ISSUE TITLE
FILL500 is sometimes slow if webxdc is closed and reopened multiple times in a row

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#3488]
It looks like WebRTC instances from previous run are not garbage collected and new FILL500 waits for them to get freed up or something like this.

Maybe if we don't reuse WebView and create a new one each time, the problem will be solved.
I.e. using this approach: https://developer.android.com/develop/ui/views/layout/webapps/webview#add-webview-oncreate
Currently Android code uses https://developer.android.com/develop/ui/views/layout/webapps/webview#add-webview-layout

**Comment by adbenitez** [comment]
would be interesting to see if the WebxdcActivity is actually destroyed for you before you click the webxdc again
