### ISSUE TITLE
[security] ship updated library dependencies

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#349]
See:
> https://f-droid.org/de/2018/06/22/this-week-in-fdroid-w25.html
> Telegram-FOSS security update due to lots of ffmpeg vulnerabilities.

The shipped versions have already become too old, and need security updates as news suggest.

Could the build system check for or tie in updates?

**Comment by r10s** [comment]
no, we cannot update the Telegram-codebase. We've did too many changes, fixes and cleanup there.
even if, this would be possible, i do not think it would help on problems as #55

in the past, from time to time, i've checked the then up to date telegram-code with the one used when forking (was Telegram 3.10.1 (821)) - there were only few changes in the code, mainly new features that have no worth in Delta Chat (eg. their sticker-server, their bot-server). i've not seen any code being refactored, simplified or so on.

however, i have not checked the most recent versions (maybe someone else has :)

**Comment by testbird** [comment]
I only meant the libs, security updates for [here](https://github.com/deltachat/deltachat-android/tree/master/MessengerProj/jni), ffmpeg in particular.

**Comment by r10s** [comment]
ahh, i see, yes, this makes sense.
we leave this issue open to not forget this :)

**Comment by r10s** [comment]
in the core, the build-system is heavily reworked, so this issue can be closed now. thanks for pointing out :)
