### ISSUE TITLE
Oversized Emojis

### ISSUE THREAD

**Issue by hofrichter** [deltachat/deltachat-android#3490]
- Android version: 14
- Device: Nokia G42 5G
- Delta Chat version: 1.50.2
- Expected behavior: "normal" size of emoji
- Actual behavior: emojis became really huge (ladnscapemode
- Steps to reproduce the problem: seems to be persistent and only sometimes normal (smaller emojies). I don't know, when it disapears, but sometimes it looks ok. May be the Zoomlevel-Setup for fonts (one step larger, than default android settings) could be a problem.
- Screenshots:
![Landscape-Mode-DeltaChat](https://github.com/user-attachments/assets/85843d6a-bc65-4eff-ba86-a98c1fe30149)
![Portrait-Mode-DeltaChat](https://github.com/user-attachments/assets/1577a508-1878-447d-ab16-c15058dd3b8d)

**Comment by adbenitez** [comment]
hi @hofrichter thanks for reporting, I can also reproduce the problem
