### ISSUE TITLE
The connectivity screen permanently displays the inbox updating

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-android#3510]
## Expected behavior:

The connectivity screen displays the inbox updating. Once this is complete, it will show that DC is connected to it.

## Actual behavior:

The connectivity screen permanently displays the inbox updating. Otherwise the account functions normally. The problem occurs with a GMX account.

## Logs:

Maybe this part of the log is important:

DeltaChat: [accId=5] src/imap.rs:309: IMAP got rate limited, waiting for 0h 0m 59s until can connect.

Android 15
DC-Android 1.50.3

## Screenshots:

![image_2024-12-20_21-22-59](https://github.com/user-attachments/assets/302ff8df-c551-467b-a2bf-56f7e65998ee)

**Comment by gerryfrancis** [comment]
Maybe a duplicate: https://github.com/deltachat/deltachat-core-rust/issues/6355

I suggest to close here and wait for the next release. If it does not fix the issue, we can open it anytime again, of course.

**Comment by adbenitez** [comment]
> Maybe a duplicate: [deltachat/deltachat-core-rust#6355](https://github.com/deltachat/deltachat-core-rust/issues/6355)
> 
> I suggest to close here and wait for the next release. If it does not fix the issue, we can open it anytime again, of course.

agree, lets close, also this is not an Android issue, next time should be opened in the core repo if it is still a problem, thanks  for reporting!
