### ISSUE TITLE
Failed with multiple different email hosts

### ISSUE THREAD

**Issue by sweetfirekitsune** [deltachat/deltachat-android#352]
Originally I attempted to use one of my Outlook accounts, and this failed with an Error 27 (if that means anything...) I thought that there was issues with the autoconfig file, so I attempted to manually enter the information for Outlook server to no avail.

I created a new email with the provider Yandex and it doesn't seem to be signing in either.

Yes I have turned on IMAP on the client side to enable DeltaChat to work (I've used the Outlook account with Thunderbird and it synced fine) and I checked Yandex too and IMAP is _enabled by default!_

I don't know what/if I'm doing something wrong. If people could help me out by saying which email provider they use and if it works/doesn't work with DeltaChat, that would be wonderful.

**Comment by r10s** [comment]
hi @sweetfirekitsune ,

thank you for your post.

error #27 is issued when the IMAP LIST or XLIST command fails - so the login itself has worked?

in general, eg. yandex should work, so maybe there is sth. else going wrong. not sure. are you using the most recent Delta Chat version? which Android version do you use? did you have look at the log (it's partly at "Settings / About / Info", for the full log, you'll need adb and logcat)

to check, which providers work in general, we have started a list here:
https://github.com/deltachat/deltachat-core/wiki/Provider-overview

**Comment by sweetfirekitsune** [comment]
Oops, sorry about that I completely forgot :unamused:

I'm running Android 6.0 and Delta Chat Version 0.18.2 (gained from FDroid)

I've dealt with logcat before but I remember that it showed a **lot** of personal data, am I okay to filter the PII out manually out of the DeltaChat and is there a way to use logcat to show only DeltaChat info?

**Comment by r10s** [comment]
The log from "Settings / About / Info" only show the Delta Chat info, however, it may still contain the e-mail-address (password is replaced by ***)

**Comment by sweetfirekitsune** [comment]
With the settings you mention, do you mean the system settings or the settings for DeltaChat, because if it is the latter, I can't reach them due to the login failing and if you are talking about the former, there is no such setting in my phone :sweat:

**Comment by r10s** [comment]
with "Settings / About / Info"  i mean the log excerpt shown in Delta Chat. if you cannot setup Delta Chat at all, you have to use the system log via adb or so.

**Comment by sweetfirekitsune** [comment]
I gave up with trying to get Gmail and/or Outlook to work, so I just used an old Yahoo account as a stop gap until I have a different email provider.

If I have any problems with the new email provider, I'll (hopefully be able to) reopen this issue.

I'm planning on using this new provider at the start of next year.
