### ISSUE TITLE
already readed mails stay in the inbox

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#353]
If I receive a (replyed) message, this message is shown in the inbox (k9 on my normal device or Thundrbird) until DC come online on my test device. Then, if DC come online, this message will moved to the "DeltaChat" folder.

I think this is the normal behavior.

But if I I read this message first in K9 or Thunderbird on my PC before DC come online this message will not trigger a push message notification in DC and also this message will not moved to the "DeltaChat" folder.

Not even if I mark it as unread manually.

DC Version 0.18.2

**Comment by Hocceruser** [comment]
Personally, I think that it makes sense that "old" mails stay where they are and only new ones are moved. I would even be confused if mails that have always been in the inbox were moved to another folder when DC is installed.

**Comment by webratte** [comment]
I don't agree.
This mails are part of a chat history.
And I think its more confused if a few mails of this chat history in the DeltaChat folder.

And a few (maybe readed by accident because the push notification in k9 on the same device was faster then DC) are in the inbox.

And another thing.
I would like to mark all DC mails as read via sive filter (I use a explicitly mailadress for DC). If DC would treat this mails as new  (push and move) e.G. by compare if this mail already in the locale history of the device. 

I never would notice this mails in other mail clients. Only in DC. And so it would feel like a stand alone messenger.
Not like a mail client 😉

**Comment by testbird** [comment]
Yep, search for "ToDo first" in https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy

**Comment by webratte** [comment]
@testbird
thank you. I has not realized this doc exist.
It sounds like a lot of work.

good luck 😉

**Comment by testbird** [comment]
Well, most of the things are already there in one way or the other, it's the alignment of the parts that's going to deliver it.

**Comment by testbird** [comment]
The strategy has been compiled from a lot of issues, and there is no need to implement all (e.g. 2xPUSH) in one go to make things work nicely.

**Comment by testbird** [comment]
That scheme is also included in https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy, but as you wrote, it needs multiple idle/push connections (2xPUSH  requirement on deltachat and the server), and would thus only make sense in a second step.
https://github.com/deltachat/deltachat-core/issues/117

**Comment by testbird** [comment]
Related issue: https://github.com/deltachat/deltachat-core/issues/117

**Comment by webratte** [comment]
Thank you again.

As I said before. I'm not a Tech user 😉

An there so much issues releated to each other...

**Comment by testbird** [comment]
> An there so much issues releated to each other...

Yes, that's the reason the wiki documens exist... To stay ahead of them and find the most consistent solution.

Thank you for reporting, and even more for thinking about solutions!
It's good to see you thought support the documented strategy.

**Comment by webratte** [comment]
I like the idea behind DeltaChat to use the already existing SMTP infrastructure.

E.G. no extra costs for servers....

And now I wait for the first release in PlayStore. This version I can share to my much less tech friends 😀

I know, this is off topic. But I must say it.

**Comment by testbird** [comment]
You're welcome. :-)

**Comment by r10s** [comment]
targeted by https://github.com/deltachat/deltachat-core/milestone/2

closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
