### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by jmsecurity05** [deltachat/deltachat-android#357]
**Delta Chat version**

**Expected behavior**

**Actual behavior**

**Steps to reproduce the problem**

1. …
2. …

**Screen snapshots**

**Debug logs**
<details>
<summary>Logs</summary>

```
<!--
If applicable, debug logs can be copied from within the Delta Chat app: 

Open the _Settings_ menu -> _About_ -> _version number|Info_.

Alternatively from the Android system log:

` adb logcat -v time -s DeltaChat `

This log contains private data (e.g. mail address, provider information) which shall be removed or anonymised prior to posting.
-->


```
</details>

**Comment by r10s** [comment]
hi @jmsecurity05 , thank you for your post, a similar discussion was also started at #275 therefore we close this one.
