### ISSUE TITLE
Keyboards appears too breifly to type

### ISSUE THREAD

**Issue by kdltr** [deltachat/deltachat-android#360]
**Delta Chat version**

0.18.2 on Android 7.1.2

**Expected behavior**

When taping an input field, the on-screen keyboard should appear to let the user type the relevant informations, such as email address and password.

**Actual behavior**

When taping an input field, the on-screen keyboard appears breifly before disappearing again, making it impossible to type anything.

**Comment by r10s** [comment]
maybe related to #315

**Comment by hirschnase** [comment]
I closed the dupliate issue #365 - let me know if I can help testing.

**Comment by r10s** [comment]
@hirschnase thanks a lot
