### ISSUE TITLE
Feature: Reencode media to adjust bandwidth constraints

### ISSUE THREAD

**Issue by nicopace** [deltachat/deltachat-android#361]
As a user that has a bandwidth-constraint connectivity (mobile or rural) I would need to reencode media before sharing in order to get the most out of my connection (and to be charged as little as possible).

It could be a global setting, or a per-sharing config, or both (a setting could be 'ask me about reencoding every time' or 'use this default').

This should apply to image, video and audio, and not to text or documents.

Also very useful would be if it could be per-conversation, respecting the constraints of the receiving client. 

This also applies to email size restrictions done by smtp servers.

**Comment by r10s** [comment]
hi @nicopace - thank you for your post :)

in fact, images as well as videos are already recoded before sending to achieve a smaller file size.

(to send them as originals you have to attach images/videos as files via the "attach button" right of the "send message" field.

**Comment by nicopace** [comment]
That is great!
Compression level should be configurable.
also, are you using OPUS codec for audio? it is the best!

**Comment by r10s** [comment]
well, as mentioned above, the user has already the options "compressed" and "original".
not sure, if more options are really needed for compression.

we should consider that it is not only be the sender to decide this but _also_ the receiver (the sender may have a very good internet connection but the receiver has to pay for every byte ...)

therefore, the current defaults are set to "rather small":
- images are scaled to a maximal width/height of 1280 pixels
- images are recoded using 90% jpeg-quality
- typically this results in images of about 200 KB while having still a reasonable quality
- roughly, these are also the values used by some other messengers

letting the user tweaking these values may result in a little gain, however, may also have the danger of larger images - which may result in costs at the receivers side then ...

regarding the audio-codec: yes: we're using opus :)

**Comment by nicopace** [comment]
And what about the videos?

**Comment by r10s** [comment]
videos are encoded with the main goal to keep the video below ~20 MB (or whatever is currently returned by [sys.msgsize_max_recommended](https://deltachat.github.io/api/classdc__context__t.html#ada7a19d3c814ed5f776a24006259395d)
