### ISSUE TITLE
"Connected to..." notification shown when unlocked for some time

### ISSUE THREAD

**Issue by Hocceruser** [deltachat/deltachat-android#362]
**Delta Chat version**
0.18.2 (F-Droid); Android 7.1.2 (SDK 25)

**Expected behavior**
The notification should not be shown when the screen is on(if I understood everything correctly)

**Actual behavior**
When I use my phone after some time a "Connected to..." notification is shown. When I lock and unlock the screen, the notification disappears. **Update:** This is the case only sometimes, sometimes it stays there

**Steps to reproduce the problem**
1. use my phone while DC is running :-) **Update**: rotate the screen while DC running in background

I do not know if it works for you...

**Screen snapshots**

![screenshot](https://user-images.githubusercontent.com/18012815/42759036-d0380d94-8905-11e8-8440-9ca21b111cb5.png)

**Comment by r10s** [comment]
@Hocceruser yes, you understood correctly. the idea is to add the notification when the screen is switched off and to discard it when the screen is switched on again. we can regard the notification to protected delta chat from being affected by the doze mode; as doze mode is not entered while the screen is active, it is not needed then.

however. i also noticed it popping up here and there, if anyone can give advices about how to reproduce this. this would be great.

my observations:
- switching the screen off an on again discards the notification (not 100% sure about this)
- bringing the app to foreground does not discard the notification
- the notification can be swiped away - normally, this is not not possible with the permanent foreground notification (also not 100% sure about this)

**Comment by Hocceruser** [comment]
To your observations:

* switching the screen off an on again definitely _sometimes_ discards the notification, but as far as I remember, not always
* yes, the notification can be swiped away
