### ISSUE TITLE
 UX consitency and cleanup

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#363]
Some of the following things to clean up the user interface have already been mentionend in other context, and one was already implemented, but here is a run-through going all the way in the same direction:

This pretty much cleans up the main screen (chat list) and its menu, and should provide everything in context.

 - [x] New group and new secure group creation has already been merged into a single "new chat" option.

 - [ ] "Show QR-code" menu entry from the main menu could be made obsolete by always showing the own qr-code below the name and address entry fields on the "new conatact" entry page (available through "new chat" or the "+" button).

 - [ ] "Scan QR-code" activity should also "show qr", by showing ~a button~~ the QR scanner in the same activity right below the own qr code.

 - [ ] The merged *show and scan* "Scan QR-code" from the "new contact" page could additionally be available in the menu within already existing chats, for direct access.

 - [ ] (The "contact requests" from the menu should move into the footer area and shwo "X Incoming Emails" by default. Separate issue: https://github.com/deltachat/deltachat-core/issues/48)

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
