### ISSUE TITLE
Keyboard not visible, no input possible (first run / settings)

### ISSUE THREAD

**Issue by hirschnase** [deltachat/deltachat-android#365]
When I start the app for the first time, I see the settings screen. When I tap on an input field, the keyboard flickers and disappears immediately, so I can not do any input on any field. Using a Samsung S8+ with the lastest Android Version/Patches from Samsung.

**Comment by webratte** [comment]
Hi @hirschnase 

it seems this is a duplicate of https://github.com/deltachat/deltachat-android/issues/360

**Comment by hirschnase** [comment]
@webratte you're right. closing the issue. I worked around it by connecting a bluetooth keyboard. however, maybe other users will try it and fail completely and give up.
