### ISSUE TITLE
Matrix Email Bridge

### ISSUE THREAD

**Issue by kaktux** [deltachat/deltachat-android#366]
Hi there,

this is kind of a question and a suggestion. Thinking about the discussion of how to add video and call function to delta chat but also about how to make its network wider (where i like the matrix bridging idea) - i looked up the matrix bridges already existing.

And stumbled upon [Matrix Email Bridge](https://github.com/kamax-io/matrix-appservice-email).

So - not beeing a programmer i wondered if this somehow can be used with delta chat.
a) it may give the option to use video and calls via matrix
b) it connects to other messengers via the matrix network - which i personally do not see as competition - but extension (e.g. through other bridges delta chat users then can write to people using other messengers).

If this can be used like i imagine - i don't know. But throwing ideas into the room won't hurt ;)

**Comment by r10s** [comment]
hi @kaktux , thank you for your post.
it's not clear how audio/videos calls can be added to delta, however, i am not sure if this bridge can help on this issue.

general suggestions are also available at https://github.com/deltachat/deltachat-core/issues/44 - so i think to is better to pick up the discussion there - or go directly to the new discussion forum at  https://support.delta.chat :)

**Comment by binarymaster** [comment]
@kaktux in case you're interested, here's corresponding issue on Matrix side: https://github.com/turt2live/matrix-wishlist/issues/212

Also here: https://support.delta.chat/t/idea-add-deltachat-to-matterbridge/481
