### ISSUE TITLE
maintain awareness that DC is "E-Mail" capable

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#368]
Deltachat does not make the regular (non-technical) users sufficiently aware -- they keep "forgetting" that they can easily reach out to literally everybody using this chat app!

It means that the deltachat UI is not yet making the best job yet, to leverage the possible **network effects**.

Circumstances like the following repeatedly show that this is an important point: Increasing the visibility of the email feature in the current deltachat project presentation and application. These kind of misunderstandings happen sometimes just a week after explicitly telling the new users personally about how DC works:

* "Oh yes, that messager I only have installed for <you / our group / special topic>"
* But why did you have to use webmail (and not deltachat) to send that attatchment to X? "Oh, I didn't know I could do it with deltachat."

What are ways to improve the awareness of the user and letting him leverage the email network feature?

  * Mention "E-Mail" more often within the app?
     * "New **Email-** Chat"?
        * ... Send new **Email-chat** message to ..."?
     *  ~~"Add Contact"~~ "New (Email-?)Address"?
     * ~~"Verified Contact"~~ "Verified (Email-?) Address"?
     * ~~"Contact Requests"~~ "Unnapproved/Incoming Emails" https://github.com/deltachat/deltachat-core/issues/48

  * Move the naming of "Delta chat" itself closer to the Email-chat spec? "Delta Chat-Mail"? E-Chat, ...??? ideas?
  * ...?

**Comment by r10s** [comment]
good point, we should keep this in mind esp. for usertesting (@kermoshina)

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
