### ISSUE TITLE
option to go offline

### ISSUE THREAD

**Issue by thomaspeterthiede** [deltachat/deltachat-android#370]
Hello,

i read #297 but i have an other reason to have the possibilty to go offline/disconnect.
i know several situation i dont want to get any chat "pling pling pling",
eg i am driving on highway or i am hiking or in meeting etc and i need still to have internet connection eg on highway for traffic informations for the navigation app but i totally dont want to disturb by any chats, eg on highway it can be an safty thing not to disturb by chat.
it is not the thing of spend battery power.
also at hiking or riding.. i want to load map tiles via internet connection but i dont want to have chat messages for relaxing or to have full concentration on my girl friend, and many other situations.
so an offline option is one the most important thing to decide for dc, like in conversations.

thee idea of dc to use the e-mailserver is great!!!!!!!

**Comment by testbird** [comment]
There may be an option to lower the importance in the operating system: Settings -> Apps -> Notification

**Comment by webratte** [comment]
Hi @testbird

Yes, this option exists.

But it would be more comfortable if I could go offline direct inside the App.

I also use www.kontalk.org 
There is a option for offline mode.
I very often use this option in the way as @thomaspeterthiede describe

**Comment by Ampli-fier** [comment]
> i know several situation i dont want to get any chat "pling pling pling",

You can have that already with Delta Chat:

Per Chat: Open a chat and click the three dots -> Mute notifications
Whole app: Settings -> Notifications and sounds. One can change Normal and Group message behaviour separately.

**Comment by thomaspeterthiede** [comment]
"Settings -> Apps -> Notification" that is nNOT an Option, to go every this way it is awful.
Mute notifications is also not an option, only to have the chance to simple disconnect.
for me it is the main reason i read in top, but an other discribed in #297 to lower power, in situations like hiking to spned power only for thirten actions on smartphone.
this all reasons togehter is the way to descide to go on dc or not, or only to use conversations.

these are the reasons for me to go away from whatsapp. ther are many apps on android they have the possibility to close the apps, eg my navigations app, or my offline map app Locus pro, and so on and so on.
There is no reason not to implement an option for disconnec. i think that is charming for many users.

have a nice day, not so sunny an warm..
greetings
Thomas

**Comment by thomaspeterthiede** [comment]
please also look on #371
they belong together in a thirten way

**Comment by Hocceruser** [comment]
Well, I think that "Settings -> Notifications and sounds" is quite forward and if there was a straighter option (like, three vertical dots -> Mute), then there would be the danger that users could accidentally click it and wonder why there are no notifications any more. 
Also, IMO this would make DC's UI less clear.

Three more remarks:
- You can also do "App-Info (in the Android settings) -> FORCE STOP. There are also 3rd party apps that simplify this. It will keep DC from doing anything until you launch it.
- Android has a "Do not disturb" mode, disabling notification sounds.
- Android has a Data Saver mode (Settings -> Data usage -> Data Saver), preventing background apps from establishing mobile internet connections.

**Comment by thomaspeterthiede** [comment]
Settings -> Notifications and sounds"   it is no way for normal user.  it is a question to programm an app comfortable. the "danger" arguement isn't one.
do not disturb and all other suggestion are to complicated and only one: a  flimsy excuse not to prgramm this.
i wrote it, in MANY apps are an offline or close button, so what?????????
what is so complicated to implicated in dc???

**Comment by webratte** [comment]
I absolutely agree with @thomaspeterthiede

**Comment by r10s** [comment]
closing this for now, of course, discussion can on https://support.delta.chat
