### ISSUE TITLE
multiple accounts

### ISSUE THREAD

**Issue by thomaspeterthiede** [deltachat/deltachat-android#371]
hello,

i am asking for implementing not only an offlinebutton like #370 but also the possibility for more than one account, every account can seperately disconnected like conversations.
my intend is the use for different social groups..family, job, sport clubs etc .
so i can use seperate e-mail accounts and i can disconnect eg account for job when i am at family etc.
that will be very great.

thank you for your work

**Comment by csb0730** [comment]
But I think this request is double?!

**Comment by thomaspeterthiede** [comment]
ok, you are right, then closing it.
