### ISSUE TITLE
Rotate keys automatically

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-android#372]
Delta Chat needs a way to set expiration dates for keys it generates and rotate them automatically. I think it is the closest thing to forward secrecy that can be implemented on top of OpenPGP.

Deleting messages for which the key has expired can serve as a weak substitution for self-destructing messages requested in #99.

Related issue in Autocrypt: https://github.com/autocrypt/autocrypt/issues/242

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat

**Comment by monperrus** [comment]
Yes, support for auto-rotating keys would be an excellent step towards forward secrecy in Delta Chat. Not "perfect forward secrecy", but [opportunistically](https://en.wikipedia.org/wiki/Opportunistic_encryption) good enough. 

/cc @teythoon @missytake
