### ISSUE TITLE
Yandex SMTP login fails

### ISSUE THREAD

**Issue by saddy001** [deltachat/deltachat-android#377]
This is the latest version (0.19.0). On first start, the login fails for yandex:

> SMTP.login failed for user test@yandex.com (Login failed)

All settings are set to automatic. Explicit SMTP security STARTTLS also fails. 

This is the logcat:
> 08-10 21:27:51.224 I/DeltaChat(27195): -------------------- Activity started --------------------
> 08-10 21:27:51.225 I/DeltaChat(27195): *** LaunchActivity.onResume()
> 08-10 21:28:02.050 I/DeltaChat(27195): Interrupting IMAP-IDLE...
> 08-10 21:28:02.051 I/DeltaChat(27195): IMAP-IDLE ended.
> 08-10 21:28:02.052 I/DeltaChat(27195): IMAP-jobs started...
> 08-10 21:28:02.052 I/DeltaChat(27195): IMAP-job #1, action 900 started...
> 08-10 21:28:02.069 I/DeltaChat(27195): Configure ...
> 08-10 21:28:02.075 I/DeltaChat(27195): Testing https://autoconfig.yandex.com/mail/config-v1.1.xml?emailaddress=test%40yandex.com ...
> 08-10 21:28:02.589 I/DeltaChat(27195): Got autoconfig: 0 test@yandex.com:0:imap.yandex.com:993 test@yandex.com:0:smtp.yandex.com:465 IMAP_SSL SMTP_SSL
> 08-10 21:28:02.589 I/DeltaChat(27195): Trying: test@yandex.com test@yandex.com:***:imap.yandex.com:993 test@yandex.com:***:smtp.yandex.com:465 AUTH_NORMAL IMAP_SSL SMTP_SSL
> 08-10 21:28:03.134 I/DeltaChat(27195): IMAP-server imap.yandex.com:993 SSL-connected.
> 08-10 21:28:03.228 I/DeltaChat(27195): IMAP-login as test@yandex.com ok.
> 08-10 21:28:04.081 I/DeltaChat(27195): SMTP-server smtp.yandex.com:465 SSL-connected.
> 08-10 21:28:04.157 I/DeltaChat(27195): Trying SMTP-Login workaround "test@yandex.com"...
> 08-10 21:28:04.233 E/DeltaChat(27195): SMTP-login failed for user test@yandex.com (Login failed)
> 08-10 21:28:04.235 I/DeltaChat(27195): IMAP disconnected.
> 08-10 21:28:04.235 I/DeltaChat(27195): IMAP-jobs ended.
> 08-10 21:28:04.236 W/DeltaChat(27195): Not configured, cannot connect.
> 08-10 21:28:04.237 W/DeltaChat(27195): Not configured, cannot connect.
> 08-10 21:28:04.237 I/DeltaChat(27195): IMAP-IDLE started...
> 08-10 21:28:04.237 I/DeltaChat(27195): IMAP-fake-IDLEing...
> 08-10 21:28:11.166 I/DeltaChat(27195): -------------------- on receive timer --------------------

It's pretty easy to create a yandex account for testing, no phone number needed.

With Thunderbird, IMAP works as ecpected (same user/pw).

**Comment by r10s** [comment]
moved this issue to https://github.com/deltachat/deltachat-core/issues/245
