### ISSUE TITLE
feature: allow other jpg upload

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-android#378]
hi,

allow other than jpg to send, e.g. gif

sash

**Comment by r10s** [comment]
not sure if i understand the feature request and what is "upload" in this sense.
however, sending gif-images is possible with Deltachat-Android.

**Comment by g6094199** [comment]
![grafik](https://user-images.githubusercontent.com/37833326/44336186-f5b24f80-a476-11e8-923d-2e6bfdcc648e.png)

**Comment by r10s** [comment]
@g6094199 can you send this gif to r10s@b44t.com please?

**Comment by testbird** [comment]
At least the shipped video libs are certainly in need of security updates.

**Comment by r10s** [comment]
we're currently switching the ui from telegram-ui to signal-ui, so, all this will work a little different.
