### ISSUE TITLE
project re-organization and "Email-chat" naming

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#379]
I see new deltachat repos and work on a new frontend, bindings etc.
As I and others have reported before, and re-occurring consistently, I see the perception that new users and devs get when they first hear about "deltachat" is mainly "yet another different chat app". The name has nothing that connotes its best and unique features.

It has also become apparent that the solution of the problems that deltachat solved along its journey (backwards compatible and optionally separated autocrypt push email) are really quite universal. Something that should not get hidden as if it were part of a brand segregation strategy.

The common notion for properly federated messaging could just be, and I think should become: " just reach me over Email-chat". And installing an Email-chat application can be seen as a step to ease email handling by quite an order of magnitude, instead of installing yet another messenger.

Later, due to the backwards compatibility, the notion could change back again to "just reach me over Email", as more and more MUAs start making use of the -core library and bindings.

The complete and more correct technical term for "deltachatting" might be something like "using the Autocrypt and Email-chat specs", but that's likely a little too much.

Thus, in conjuction with the current re-arrangements and before publishing v1.0, I think it would be good to sincerely consider this, and at least renaming the -core lib, if not better also the front-end application to "Email-chat". The work of renaming will certainly be rewarded by a much better perception.

* Users won't be surprised when asked for their email-address after installing the "Email-chat" app.
* It is much more apparent that "Email-chat" users can "reach the world"
* Devs and actually any person that will hear about the "Email-chat" app, or capability (lib), are immediately pointed much closer to getting the proper picture.
* ...

**Comment by stefan-niedermann** [comment]
Just an idea, but if you are thinking about changing the name, i'd throw "Jet-Mail" into the discussion. It sounds like "Chat-Mail" if one is talking about it and it suggests to be super quick like a jet ;-)

**Comment by webratte** [comment]
If Deltachat really should be renamed, I think the idea of @stefan-niedermann sounds like a really good name 👍

**Comment by testbird** [comment]
I like the "jet" idea. :-) What about **Email-Jet**
* sounds like the [Email-chat spec](https://github.com/deltachat/spec/blob/master/spec.md#email-chat-specification)
* respects that mail and email are different things
* technically, Email-chat is not the quickest chat, and can not be, however, it provides a fast UI for email

If the point is a meaningful name, that conveys correctly describing information about the app's unique feature. Email-Jet may not hit the nail 100% in terms of technical correctness, but improves in all ways I could think of.

**Comment by testbird** [comment]
jet-mail is already taken (in use and registered)
email-chat or chat-mail

**Comment by happyreacer** [comment]
how about the name "infinity chat"? it is boundless from one provieder

**Comment by testbird** [comment]
But the last sugguestion also seems bountlessly off from conveying anything closer to Email-chat. ;-)

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
