### ISSUE TITLE
Unsatisfactory compatibility to other email clients

### ISSUE THREAD

**Issue by tapete** [deltachat/deltachat-android#381]
1. Other email clients like K9 can group conversations by the message subject. As deltachat changes the subject of each message, this feature does not work in K9 and may annoy K9 users when chatting with deltachat users.

2. If I use deltachat and other mail apps like thunderbird, some messages are moved to the DeltaChat IMAP folder and some are not. In the end it is a pain to find the mails.

3. If I use deltachat for conversations with my boss, the message subject "Chat: ..." looks quite shady.

Just some thoughts..

**Comment by r10s** [comment]
hi @tapete thank you for your post.

i think most of the issue is already covered by https://github.com/deltachat/deltachat-core/issues/72 and the other core-issues labeled "spec" https://github.com/deltachat/deltachat-core/labels/spec , so i would tend to regard this one as a duplicate.

**Comment by tapete** [comment]
Hi r10s, thanks for the link to the specs. This issue can be closed.
