### ISSUE TITLE
do not send email address unencrypted, even to third parties, without asking

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#384]
The auto configuration transmits the user's complete email address, unencrypted, and not only to the own email providers' server.

* The default query to public databases (not the email providers' domain) may have to be done generically (not include personal user name).
* Unencrypted requests (http) may have to be disabled, or really only be used if explicitly allowed in advanced configuration.

**Comment by r10s** [comment]
first of all, the email address is only passed to the email providers' server. it is not passed to other servers (eg. when autoconfig.thunderbird.net is checked, the address is not  passed, only the general server configuration is looked up)

wrt. unencrypted requests:
do you know if we can really skip the unencrypted requests? or can you do a research on this? i think there are some servers only supporting http://autoconfig.domain/... 

we should then balance the advantages/disadvantages carefully. some thoughs:

- the unencrypted users email address is used in every single mail send and received (!) and is passed to servers not under the control of the user.
- how much privacy does the user win, if the single, autoconfigure request is skipped? - with the possible disadvantage that the initial configuration will fail.

**Comment by testbird** [comment]
(Ok, I'm sorry if I wrongly pointed to the public server query.)

I think the situation has changed, with the new EU regulation, fortunately.

Deltachat is simply not allowed to send this kind of data unencrypted (possibly not even as opt-in).

When email is passed to smtp servers, the transport is also required to be encrypted (SSL/TLS/STARTTLS), everything else would be wrong.

> how much privacy does the user win, if the single, autoconfigure request is skipped? - with the possible disadvantage that the initial configuration will fail.

Deltachat may inform the user that the encrypted automatic configuration was not possible, and the user should please contact the email provider to enable it, and supply the server details for manual configuration in the meantime.

**Comment by r10s** [comment]
a pragmatic workaround would be just to skip the emailaddress if it is used without https.
- static configuration files will keep working
- servers who _really_ have a script running checking for the emailaddress (to be honest, i've never seen one) seems to be more maintained and will also be reachable with https by chance.

@testbird  however, nevertheless, i am interested why it may not be _allowed_ ...

**Comment by r10s** [comment]
changes are done by https://github.com/deltachat/deltachat-core/commit/a128a0ed694473867998e0d0776446f53b3e2ce4

**Comment by testbird** [comment]
Thank you for the changes, sorry only now I realize I could have contributed that patch myself.

I'm also no lawyer, I just thought it would not be good, especially for a email-chat standard project.

Legally I am not sure how development counts as an organization, what I meant mostly is if DC is used to communicate in some organization, even a darts club, it is not allowed to send out member addresses.

**Comment by r10s** [comment]
thank you for https://github.com/deltachat/deltachat-core/pull/241 , i also thought about this, and yes, it makes some sense :)

**Comment by r10s** [comment]
there are real-live-problems with the decision of skipping the email for the http-requests, see https://github.com/deltachat/deltachat-android/issues/384
