### ISSUE TITLE
Regression: cannot send messages on poor network connection

### ISSUE THREAD

**Issue by MMurzik** [deltachat/deltachat-android#386]
**Delta Chat version 0.20.0**

Before version 0.20.0 if a message was sent and connection to the mail server broke due to poor internet connectivity, Delta Chat would be sending this message over and over again, so it would definitely be delivered sooner or later, when connectivity improves.
Now, with the new "function" in version 0.20.0 to give up sending after a number of retries, reliable  delivery of messages on poor connection is no more possible. When the mail server is inaccessible for some time (e.g. on a subway, or at the countryside, or even in flight mode), Delta Chat simply gives up sending these messages. That makes me constantly re-check if all messages were sent, and if not re-send it manually. It is inconvinient. And before version 0.20.0 I can simply send a message, forget about it, and to be sure that it will be delivered 100%
Please add option in settings to restore old behavior of Delta Chat to try sending unsent messages indefinite number of times. Thank you.

**Comment by csb0730** [comment]
Would raise an issue but here it is!

Now if a message cannot be send there is a red ! at message right corner. But there is no possiblity to start resending !

There should be a possibility to resend again or an automatism which guarantees message delivery at next online status again!

I think this BUG is now a result of stopping delivery in case of resending of too big attachments!?

This is really a bug now!

**Comment by csb0730** [comment]
At least - manual resend feature absolutely necessary !!

**Comment by MMurzik** [comment]
And what about *temporary* server errors? I think in that case Delta Chat should notify user about the problem and also keep retrying. What if the problem will be fixed in some time?

**Comment by testbird** [comment]
Right, good point, keep retrying with the longer intervals if only a temporary error status was returned.

**Comment by r10s** [comment]
thank you very much for the posts, i moved it to https://github.com/deltachat/deltachat-core/issues/265 as it is deltachat-core related.
