### ISSUE TITLE
FR: Move originating email to chat folder

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-android#387]
Hi

Here is a situation

You get an email from non chat friend for the first time. DC intercepts it but leaves the message in inbox. You reply to this message in DC, therefor it becomes part of DC conversation. Then the initial originating message that your friend sent you in the first place should be moved to the chats folder as well.

thanks

**Comment by testbird** [comment]
Yes. So what's the whole picture then?
https://github.com/deltachat/deltachat-core/wiki/IMAP-strategy

1) Messages that are approved to be displayed in a chat, should be moved by DC when status changes to "seen", if they have not been moved by a server filter yet.
1) But (Email) Messages that are read in the "Incoming Emails" (aka contact requests) should only be marked as "seen" and stay in the INBOX.
1) Neverthless, (email) messages that are replied to after reading them in the "Incoming Emails" (aka contact requests) should be moved to the email chat folder.

Maybe the messages in the email chat folder could get sorted into sub-folders that correspond to the chat partner and groups? To make it much easier to locate specific email chat correspondence from within classic MUAs.

**Comment by testbird** [comment]
You might want to change the issue template to point feature requests to the forum.

**Comment by r10s** [comment]
good point, we should update this.

**Comment by testbird** [comment]
Concerning this issue, though, I think it's a valid issue with the email handling in the current implementation. It breaks threats into parts on the server.

My addition to have sub-folders in the chat folder, for better access by classic MUAs, could be a feature request.

**Comment by testbird** [comment]
The forth sub-point of `4) Have a max. chat message length configuration option` at https://github.com/deltachat/deltachat-core/wiki/Use-Cases was actually intented to cover the problem of this issue.

The idea was that distinguishing based on the size allows for a default separation between "starting a chat" based on some incoming email (leaving longer classic emails in the INBOX to be answered by classic MUAs) and "claimiing a chat" (moving all messages into the chat folder).

What do you think?

**Comment by r10s** [comment]
this is targeted by https://github.com/deltachat/deltachat-core/milestone/2

closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
