### ISSUE TITLE
space of hidden system status bar is not used

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#392]
if the system status bar is hidden, this additional space is not used by the app.
noticed on lineage 14.1 with android 7.1 - but probably this is also true for other android version as the app paints much on its own instead of using system controls where possible.

**Comment by testbird** [comment]
> the app paints much on its own instead of using system controls where possible

What could have been the considerations? security, portability, ...?

**Comment by r10s** [comment]
> What could have been the considerations? security, portability, ...?

the code came originally from the telegram messenger and was only adapted for delta chat.

so - i don't know. but i could say that the reasons were probably neither security nor portability.
