### ISSUE TITLE
Sending Pictures on slow connections

### ISSUE THREAD

**Issue by bokf** [deltachat/deltachat-android#393]
On slow or missing connections pictures are not sent and I get a white exclamation mark in a red square. 

I understand this symbol, that deltachat gave up sending. The picture should be sent automatically as soon as the connection is back again. At the moment I have to look and check if the picture is sent and resend it myself manually if it is not the case. But if I am in an area with poor network coverage I do not notice when I have network connection for a short time. So it would be nice, if the picture would be sent automatically after lost connection.

Another phenomena I had is that the picture was sent endless times! For example 20 times the same picture to the same recipient in a group chat and other group members didnt recieve it at all. I think this was also due to slow network connection.

Used version v0.20.0
![screenshot_2018-09-17-08-48-46_cr1](https://user-images.githubusercontent.com/25562831/45614284-537f8a80-ba69-11e8-8eb4-fe6896dc0227.png)
![screenshot_2018-09-17-08-48-46_cr2](https://user-images.githubusercontent.com/25562831/45614297-5bd7c580-ba69-11e8-9f2e-f6b91710fb37.png)
![screenshot_2018-09-17-08-48-46_cr3](https://user-images.githubusercontent.com/25562831/45614300-5ed2b600-ba69-11e8-95ca-4c1ede3c3e65.png)

**Comment by csb0730** [comment]
I saw the same behaviour under bad network conditions too. DC gave up sending with the proposed sign.
See `dc_jobs.c` around line number 626. There is defined to use 3 retries and then give up.
There is described too, that send errors in case of bad network conditions not would rise retry counter! But what if network status wouldn't be detected stable? I suspect this could be an issue and dc gives up too early.

I modified this setting from 3 to 5 and making a trial right now!

=> but all this only describes a too early give up sending, not too many sends!

**Comment by csb0730** [comment]
Making a self trial with following code extension in dc_job.c:

`			#define JOB_RETRIES 5   // set from 3 to 5 (20181007cs)

			int is_online = dc_is_online(context)? 1 : 0;
			
			// 20181015cs: catch unstable online state
			// int tries_while_online = dc_param_get_int(job.param, DC_PARAM_TIMES, 0) + is_online;
			int tries_while_online = dc_param_get_int(job.param, DC_PARAM_TIMES, 0);
			
			// only if two times consecutively state is "online" increase value,
			// otherwise decrease (unstable state)
			// means: if state is changing several times on and off
			if (last_online_state && is_online) {
				tries_while_online++;
			} else {
				if (tries_while_online > 0) {
					tries_while_online--;
					dc_log_info(context, 0, "%s-job #%i online state unstable try decreased, now #%i", THREAD_STR, (int)job.job_id, tries_while_online);
				}
			}
			last_online_state == is_online;
			// 20181015cs end

`
If I'll have any news I will come back :-)

**Comment by r10s** [comment]
closing this in favor to https://github.com/deltachat/deltachat-core/issues/265

**Comment by csb0730** [comment]
Hi @r10s and @testbird,
see my comment and changes from Oct 18. I've tested v.0.20.0 (self compiled apk) while four weeks now and see no problems anymore :-)

I saw issue [https://github.com/deltachat/deltachat-core/pull/417](https://github.com/deltachat/deltachat-core/pull/417) now but I think my approach is a little bit easier than that.
Has anyone did a review of my approach?

**Comment by testbird** [comment]
Obviously my last sentence was wrong as no imap connection is there if offline, but just keeping the same retry interval continuously (23 minute imap renewal) should not require much more power as when being online, would it?.

**Comment by testbird** [comment]
The best handling of the problem would also depends on the underlying feature to continue interrupted smtp transmissions, is that supported?

Possibly
https://tools.ietf.org/html/rfc1830
https://tools.ietf.org/html/rfc3030
