### ISSUE TITLE
Can't sigh up to support.delta.chat (activation email not sent)

### ISSUE THREAD

**Issue by Hocceruser** [deltachat/deltachat-android#394]
Now I had to open an issue here :disappointed: 

What I tried: 
- Sign up with the same email address I am using for GitHub -> no activation email received, can't log in
- Sign up with GitHub (using oauth) -> "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?" (I did approve authorization but I guess that the problem was that I previously tried to sign up with the same email address)
- Sign up using a 10minutemail address -> again, no activation email was received.

From which server are the activation emails sent? Maybe they are not accepted by some email servers (GMX and 10minutemail)?

**Comment by Ampli-fier** [comment]
I also did not receive the activation email. 
I tried yesterday evening with two different mail provider -> No Luck

**Comment by r10s** [comment]
@Hocceruser @Ampli-fier yes, there are issues with the activation, unfortunately, we did non have the time to figure this out yet.

@lefherz, who thankfully set up the awesome forum, want to have a look at it but he us currently busy.

i would like to just disable the activation for now, however, i did not find an option for this. if anyone has experience with discourse, any hints are welcome.

btw. @Hocceruser, @Ampli-fier - if you're interesting in being moderators in the forum, please let me know. it's just that we'd like to have some people that can react if sth. is there that requires reaction :)

**Comment by r10s** [comment]
moved to https://github.com/deltachat/deltachat-pages/issues/98

**Comment by Hocuri** [comment]
> btw. if you're interesting in being moderators in the forum, please let us know. it's just that we'd like to have some people that can react if sth. is there that requires reaction :)

Slightly OT :wink:, anyway: Well, I do not know how much spare time I will have in, like, half a year, but you could just make me a moderator for now and I'll see what I can do. 
IMHO some consistent rules (like, when to delete a comment) would be useful though (not that urgent).
