### ISSUE TITLE
How to run two independent instances of Delta Chat (or any app)

### ISSUE THREAD

**Issue by rizzopablo** [deltachat/deltachat-android#395]
Hi, I found a way to do the subject, very easy: look for the "Shelter" app on F-Droid.
Best regards.

**Comment by r10s** [comment]
cool :)

**Comment by kollokollo** [comment]
This has in principle always been easy: One needed only trwo versions of the app with a slightly different (full-)name.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
