### ISSUE TITLE
Messing up pictures between chats

### ISSUE THREAD

**Issue by bokf** [deltachat/deltachat-android#399]
I noticed the behaviour that pictures I have sent appeared in a different chat. The first time I noticed it was when I made a backup and restore and switched the versions. This is not nice but understandable. But I think it also appeared when I deleted chats? Maybe other users have also experienced the same behavior?

**Comment by r10s** [comment]
older core versions did not always copy images to the internal database, so that such situations might have happen for the current f-droid version.

the upcoming android-dev version uses a core that always copy files so that this issue should be fixed there.
