### ISSUE TITLE
Reset key of contact

### ISSUE THREAD

**Issue by muelli** [deltachat/deltachat-android#404]
I noticed that the app crashes when I want to send a message to a certain contact.
For a reason unknown to me delta decides to encrypt the email. I guess that this crashes the app (cf. https://github.com/deltachat/deltachat-core/issues/333).

I thought I'd start over by deleting the chat to the contact.  But then re-creating a chat again attampts to send an encrypted email.

How can I make delta forget about the key for a contact s.t. it will send a plaintext email?

**Comment by r10s** [comment]
> How can I make delta forget about the key for a contact s.t. it will send a plaintext email?

when you receive an unencryption mail from the recipient or if you disable "prefer encrypt" in the settings, messages will be sent without end-to-end-encryption (using transport encryption then).

**Comment by muelli** [comment]
> when you receive an unencryption mail from the recipient 
This is not an option, of course.

> or if you disable "prefer encrypt" in the settings
You mean, globally? The "prefer end-to-end encrypted" setting?
This seems to be rather heavy handed given that only one contact causes the crash.

Can I make Delta.chat forget everything about a given contact?  That would be good to withstand forensic analyses.

**Comment by r10s** [comment]
@muelli currently - nor really. i find this topic interesting, maybe just open a thread on this at https://support.delta.chat ?

**Comment by muelli** [comment]
nah. I'm not keen on maintaining yet another persona somewhere.  Especially for something that seems like a bug to me.

**Comment by r10s** [comment]
you can log in there with your github account ;)

**Comment by r10s** [comment]
wrt bug: i agree, however, the bug is already filed at https://github.com/deltachat/deltachat-core/issues/333 and this issue is more a discussion about a workarounds imho

**Comment by muelli** [comment]
> you can log in there with your github account ;)

sure. but then I'm frowning upon signing up at yet another place. And by quickly glancing over the ToS and Privacy Policy I better not do that. I like not be spied on when I read or write posts.



> the bug is already filed at [deltachat/deltachat-core#333](https://github.com/deltachat/deltachat-core/issues/333)

I believe it's a separate issue about the app crashing.  I don't think this is directly related to the ability to delete everything the app think it knows about a certain contact. Even if the app didn't crash randomly, it still doesn't offer to be amnesic wrt a certain contact. And I may very well have the desire to remove traces about having been in touch in someone.
In fairness though, my primary desire is for the  app to not suffer from memory safety issues even in normal use.

**Comment by r10s** [comment]
okay, i think we will keep this in mind then :)
