### ISSUE TITLE
Cant move DS to a new device with keeping existing chats

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-android#405]
**Delta Chat version**

0.20.0 on Android One

**Expected behavior**

Moving to a new Phone.

- Install DC to the new phone (eg. via FDroid)
- Connect DC to the existing mailbox
- Send Autocrypt-Setup-Message from the old Phone
- Enter the PIN Code into the ne installed DC
-DC should (optionally?) scan the mailbox for existing chats and displays them as on the old phone

**Actual behavior**

- DC should (optionally?) scan the mailbox for existing chats and displays them as on the old phone...does not work as expected by me.

Is this a intended behaviour? Whats the showstopper not scanning/showing the "old" messages?

Sash

**Comment by r10s** [comment]
delta chat currently does not scan for old mails. however, you can export/import a backup at settings / advanced.

**Comment by r10s** [comment]
closing this here, feel free to discuss new features in the support forum at https://support.delta.chat
