### ISSUE TITLE
If the screen goes black during Autocrypt Setup Message, the security number is lost

### ISSUE THREAD

**Issue by b3yond** [deltachat/deltachat-android#409]
**Delta Chat version**

v0.20.0

**Expected behavior**

When I initiate the Autocrypt Setup transfer, I have all the time I need to copy the security code from my Android phone to my other device.

**Actual behavior**

When the screen goes black after a while, because I didn't touch the screen, and I unlock the phone again, the security code is gone. I can't finish copying it if I forgot to tap the phone once in a while.

**Steps to reproduce the problem**

1. open Deltachat on Android
2. initiate Autocrypt Setup Message
3. don't touch the phone for a minute or so

**Comment by r10s** [comment]
this should be fixed in 0.100.0
