### ISSUE TITLE
Idea: combine with Meshenger for webrtc video chat

### ISSUE THREAD

**Issue by rizzopablo** [deltachat/deltachat-android#410]
Look at this project: 

https://github.com/dakhnod/Meshenger

**Comment by r10s** [comment]
@rizzopablo very interesting link, thank you very much :+1:

**Comment by angelo-fuchs** [comment]
We should definitely look into the Web RTC connection function:
https://github.com/dakhnod/Meshenger/blob/master/app/src/main/java/d/d/meshenger/RTCCall.java

Besides that, I don't see much overlap / cooperation between the two apps. Meshenger is Local-Network P2P; Delta is Internet & Server based IMAP; Both cool, but different.

**Comment by r10s** [comment]
i would also suggest to shift this discussion / feature-proposal away from the issue tracker to the forum. it's otherwise handing around for months here ...
