### ISSUE TITLE
Consider checking airplane mode?

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-android#412]
I'm currently in patagonia spending a few days at a time in the mountains.  As one does these days using osm-and to navigate on my phone (still carrying paper maps and compass around ;))  But I noticed that even though the phone is in airplane mode deltachat is still creating the socket and trying to receive connections.  Would it be possible to check the state of airplane mode and react to this?  This could be more complex as there probably also is something one should do to handle data-saver mode etc.

**Comment by ralphtheninja** [comment]
@r10s Maybe transfer to `android-ii`?

**Comment by r10s** [comment]
we can leave it here as the rough plan is to upload the android-dev to this repo (see https://github.com/deltachat/deltachat-android-ii/issues/230) and move the issues from `android-ii` here :)

**Comment by r10s** [comment]
> But I noticed that even though the phone is in airplane mode deltachat is still creating the socket and trying to receive connections. Would it be possible to check the state of airplane mode and react to this?

well, in general, yes. however, this would be quite some effort - distinguish between different types of offline, which tends to bugs that might be hard to catch. also after all, i am also pretty sure, that different devices may behave differently on this, firewalls etc.

so, for now, it seems more reasonable to just try to get a connection from time to time - through the backoff method, at least, this should not be done every second.

i'd suggest, that, if needed, we can continue discussing this in the forum and/or, as needed come back here when other things are more settled (whenever that will be ;)
