### ISSUE TITLE
Creating an in-chat photo does not produce shown result.

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#415]
Help Wanted: Unclear if that happens on all phones, please test and report.

- Modell: FP1U
- Android-Version: 4.2.2 (Jelly Bean)
- Kernel: 3.4.5
- API Version: 17

When I make a photo in the chat and I use the front camera (pointing at me) then the small screen at the bottom shows e.G. my beard. But when I then make the picture a frame far higher is chosen.

It is very certainly connected to my phone as I can't screenshot the effect (but made a video, see attachment)

A "solution" if this is only affects old phones would be to not allow the 'half-camera' on phones that don't properly support it (most likely phones with API Level < 21 / KitKat and older)

[vokoscreen-2019-01-21_15-03-27.zip](https://github.com/deltachat/deltachat-android-ii/files/2779190/vokoscreen-2019-01-21_15-03-27.zip)

**Comment by Boehrsi** [comment]
Just checked on a Samsung S7 with Android 8 and everything seems to be fine. Checked also on a OnePlus 5T with Android 9 and there's a little difference visible (the bottom preview shows a little bit less than the actual image taken). On an emulator with 4.4 there is also just a small difference notable. I think it's related some how to aspect ratios and the used camera hardware / software.

**Comment by r10s** [comment]
also could not reproduce that. 
maybe we should ignore that.

**Comment by r10s** [comment]
deciding for the latter for now :)
it seems to affect only older phones/android-versions, if we get more reports we can reopen this issue and think it over.
