### ISSUE TITLE
Incognito Keyboard does not work

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#417]
- Modell: FP1U
- Android-Version: 4.2.2 (Jelly Bean)
- Kernel: 3.4.5
- API Version: 17

1. Go to Settings -> Privacy
2. Activate Inkognito-Keyboard
3. Go to chat
4. Enter nonsense Word (e.G. "Zorg")
5. Tap center area of keyboard twice to store it.
6. Leave DeltaChat
7. Go to some text App (e.G. Notes)
8. Enter "Zor" -> "Zorg" is displayed as suggestion

Same behavior if app is forced stopped and restarted after changing the settings (and using a new word)

Expected behavior:
Entering a "new" word should either not give the option for saving or should fail to save.

**Comment by angelo-fuchs** [comment]
This seems a twofold problem:
1. My Phone does not support it (unknowable to DC afaics)
2. The german text suggest that its a forced value but it actually is a kind request (that can be ignored)

**Comment by r10s** [comment]
the flag as such makes sense, however, it may be ignored by the used system or installed keyboard and we do not even know this.

so, i think adding a hint for the translators to take care about the wording can close this issue.
