### ISSUE TITLE
Profile name field showing empty when editing if account was imported

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#423]
Just a little "not the big deal" detail:
If users imported they account to the new version of DC, when they try to edit the profile is name the field is empty if they imported the account instead of setting this inside the app, if they set this inside the new app, when trying to edit the name field, the current name is kept in the field, this makes me thing that there are an error here since if the name was taken from the backup, the field is shown empy when editing it (ONLY WHEN TRYING TO EDITING IT)

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.91
- Steps to reproduce the problem: In a "fresh" install of DC 0.91, import a backup from DC 0.20 (set the profile name on DC 0.20 before making the backup), go to edit the profile name, the field is empty

**Comment by r10s** [comment]
@adbenitez one more time - thanks again for this detailed and very detailed and helpful issue descriptions. fixed in #659
