### ISSUE TITLE
Remove superflous "Are you sure" question

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#425]
When starting a new chat, after entering a new E-Mail Address one can hit 'New Contact'.

Then one is asked: "Do you want to chat with ..." in an infobox that needs additional interaction.

I suggest we remove that infobox / question.

99% of the time I want to and this is just another click I have to do. 1% Its a mistake and I can leave the chat empty and it will fade to nothingness (or I can delete it, if needed).

**Comment by r10s** [comment]
not that sure if the question is superflous; it prevents accidentially clicks that are very easy to do while scrolling through the list. also the question is in-sync with the question asked when clicking on an e-mail address; it makes some sense to have a similar behavior, imho.

however, just my opinion, but we should continue the discussion in the forum at https://support.delta.chat/
