### ISSUE TITLE
Chat UI not touch friendly

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#427]
Some buttons are a bit hard to tap, as you can see in the screenshot, the "x" button on the image is small, the edit image (pencil) button is too close to the send button so it is easy to send the image accidentally, the emoji icon's padding is small making it hard to tap.

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.97.1
- Screenshots:
![screenshot_20190103-115039](https://user-images.githubusercontent.com/24558636/50660608-6366a000-0f6e-11e9-85e7-411e4a5623af.png)

**Comment by angelo-fuchs** [comment]
@r10s @adbenitez Can this issue be closed?

**Comment by r10s** [comment]
not yet, the emoji-button can indeed be at least wider.
however, it's might be a bit tricky to move margins to paddings and needs also some of testing.

**Comment by adbenitez** [comment]
The emoji icon have no padding in the default state of the textedit when the user types more lines of text the padiding grows.

**Comment by Hocuri** [comment]
> maybe, in mid-term, we can also skip the edit button completely and open the editor on _any_ click in the image (currently, the _editor_ lacks some functions available in the _preview_ so, for now, this is not an option)

I like this idea, as well as the bigger round edit button.

From my experience, it is not just the emoji button, it is:
- The back button in the upper left corner 
- The input message area (could be higher)
- The add photo, record voice message and emoji buttons

It is possible to tap all of them but it could be better, especially as there would be enough space around them. IIRC this was better in the old Telegram-UI. And @adbenitez  yes, there are two millimeters of unused space over and over the emoji button on my device.

**Comment by adbenitez** [comment]
@Hocuri some friends also complained about the back button!!! I had not encountered this issue since I use my phone is back button instead of the app is button, also I think the add photo, record voice message buttons could have more padding but I didn't keep complaining about here because I think this touch problem is more related to UI unresponsiveness, since some times the buttons don't work even when I am sure I am touching their epicenter ;) 
see:  #435

**Comment by Hocuri** [comment]
This did never happen to me, it just took some time until DC reacted. Anyway, the touch areas could be bigger as can be seen at your screenshot: https://github.com/deltachat/deltachat-android/issues/427#issuecomment-451462213

**Comment by r10s** [comment]
i think the back-button has system-size and style (both, the one in the navigation area and the one in the title bar).

**Comment by adbenitez** [comment]
that is why I think it is more a unresponsiveness issue...

**Comment by Hocuri** [comment]
I don't think so, in other apps the area is much bigger (see attached screenshots)

**Comment by Hocuri** [comment]
I don't think so, in other apps the area is much bigger: 
![sc_dc](https://user-images.githubusercontent.com/18012815/52768759-a9635900-302e-11e9-9223-19ccc86beaa6.png)
![sc_sf](https://user-images.githubusercontent.com/18012815/52768768-ac5e4980-302e-11e9-90fc-b85e0246d956.png)

**Comment by r10s** [comment]
@Hocuri thanks!
