### ISSUE TITLE
Invite should allow to enter emails directly

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#429]
When I use the 'Invite friends' view and click 'Share' I'm offered to share with deltachat (cool) but then I see the existing chats and have no option to enter a custom E-Mail Address.

I'd prefer to have a section on the first screen, below 'Share' where I can just enter E-Mail address(es) which then are each individually added as contacts and a chat opens for them in the chat list with the message I typed as the first message sent.

**Comment by r10s** [comment]
i think, there is no need to invite people where the email-address is already known.
you can just start chatting with them.

**Comment by hpk42** [comment]
On Tue, Mar 26, 2019 at 12:08 +0000, björn petersen wrote:
> i think, there is no need to invite people where the email-address is already known.
> you can just start chatting with them.

Let's drop the "invite" menu entry. Each outgoing
message contains a link to delta.chat, that's enough.  

We specifically advertise that people can use any e-mail
address and, if anything, i'd rather introduce a descriptive text/graphic 
to this effect when the initial chatlist view is empty (or almost empty). 

Maybe directly entering/pasting an e-mail address on an empty-chatlist 
screen could make sense at some point. But for now we can just disable
the "invite friends" activity.

**Comment by r10s** [comment]
the "invite friends" is mainly for contacting people where the email address is _not_ known.

just saying, in general, i also think  we can drop the function at all :)

**Comment by hpk42** [comment]
On Tue, Mar 26, 2019 at 05:52 -0700, björn petersen wrote:
> the "invite friends" is mainly for contacting people where the email address is _not_ known.

ah right, forgot that you can use TG/signal/whatsapp for invitations --
but as discussed between us, those users can not join as easily as they
can with the mobile number-based messengers. 

> just saying, in general, i also think  we can drop the function at all :)

disabling it and seeing if there are folks missing it is a good move IMHO.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/790
