### ISSUE TITLE
Show waveform as slider for voice-messages

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#430]
The one from Telegram with the waveforms instead of the current slider.
Our M tester complained about that after upgrading to android dev.

Also IMHO the waveform progress looks better than the slider.

**Comment by r10s** [comment]
while i also think that a waveform would be nice, it seems to be quite some effort and would result in additional maintainance etc.

so i am closing this for now, however, we can continue the discussion in at https://support.delta.chat/
