### ISSUE TITLE
Confusing clickpath on invite friends

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#431]
- Modell: FP1U
- Android-Version: 4.2.2 (Jelly Bean)
- Kernel: 3.4.5
- API Version: 17

1. Go to Settings
2. Go to "Invite Friends"
3. Hit 'Back' Icon on top left

Result: You are sent to Chat Overview.

Expected: You are sent to Settings

Note: Using the 'Back' Button on the phone works as expected and brings you back to settings.

**Comment by r10s** [comment]
issue can be close as the "invite friends" activity is no longer available, see https://github.com/deltachat/deltachat-android/pull/790 for some reasons.
