### ISSUE TITLE
Notification sound still played even if the message is from active chat

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#432]
Notification sound is played even when the message is from the current active chat, in the old 0.20 version a soft bubble sound was played in this cases if I remember well, is this an error or it is intended to happens??

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.92
- Expected behavior: while I am in a chat I don't receive noisy sounds notifications of the messages I am already seeing. 
- Actual behavior: a noisy sound notification is played unnecessarily.
- Steps to reproduce the problem: Just tell someone to send you a message, wait in the chat room until you receive the message.

**Comment by r10s** [comment]
i think this is included in #451 now
