### ISSUE TITLE
ask the user if he wants to disable battery-"optimisation"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#433]
without battery-"optimisations" there is no need to add the permanent notification.

maybe we should ask the user (after a day using delta, maybe, i wouldn't annoy him at once) if he wants to disable them. there is already the class DozeReminder that could help on this, i just did not delete it :)

however, i would say this is of low priority.

**Comment by angelo-fuchs** [comment]
For newer Phones (API 26+) this could help: https://developer.android.com/reference/android/Manifest.permission#REQUEST_COMPANION_RUN_IN_BACKGROUND but I haven't read it thoroughly.

**Comment by r10s** [comment]
"companion app" - never heard of this. thanks for pointing this out.
