### ISSUE TITLE
sharing files does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#434]
sharing images works, however, when trying to sharing random files (just tried with *.bak from the amaze file manager) delta is not offered in the list. this worked with the old f-droid-version, however.

also, sharing URLs still lack the title, this also worked with the old f-droid-version.

**Comment by angelo-fuchs** [comment]
@r10s Should we add this to Jan2019?

**Comment by r10s** [comment]
i think jan2019 is done so far :)
but we can handle this with high priority. should not be that hard.

**Comment by violoncelloCH** [comment]
something for the project playOne?

**Comment by r10s** [comment]
> something for the project playOne?

added it there as "optional", we'll see if someone is targeting it :)

**Comment by Boehrsi** [comment]
I would look into that one on Friday :).

**Comment by r10s** [comment]
great!

**Comment by Boehrsi** [comment]
The general problem is that the Signal code base isn't able to handle multiple shared files at once and that's what some of the messengers do. I'm adjusting that.

**Comment by r10s** [comment]
cool. as we do not have a method to stage multiple files, i think, as a quick-fix, it would be okay to ask the user "do you want to sent 3 files to _chat?_" after selecting a chat.

**Comment by Boehrsi** [comment]
I'm nearly done with that one. Just the permission handling for required cases and some string adjustments are missing.

**Comment by Boehrsi** [comment]
Did the last adjustments and will now test if everything is working fine. This ticket should definitely be ready this week.

**Comment by r10s** [comment]
cool :)

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/759 - @Boehrsi great job! and of course, my initial comment - "should not be that hard." - was wrong in the end :)

**Comment by adbenitez** [comment]
@Boehrsi  +1
