### ISSUE TITLE
New UI is unresponsive

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#435]
I was thinking the buttons were hard to tap(and opened an issue about it:  #203), but it was actually related to unresponsiveness in the Delta Chat UI, I was thinking it was just me because I have a low RAM device, but now a friend upgraded to 0.98 and is complaining about this and he has a device with 3GB of RAM. I(and my friend) sometimes have to tap a button(ex. emoji keyboard, camera, etc) several times before it finally react to the click event, also in general the UI feels much more slow than in 0.20. My friend also says scrolling in chats felt slow and described the UI as "clumsy".

I think this is related with the imap/smtp threads, Often when I have experienced this I was sending/receiving messages... but I'm not sure about this...

- Platform (android/blackberry/anbox): 6.0 and 8.1
- Device: BLU(RAM:458MB) and Xiaomi(RAM:3GB)
- Delta Chat Version: 0.98

**Comment by angelo-fuchs** [comment]
On my phone the performance improved rapidly with use, so after about 5 minutes of use (after a restart of the phone) the switches between screens were down to 1.5 secs (which is a little bit worse then delta 0.20 but not much). I tried probing around if I can remove some elements - And I could, but it didn't make much of an impact. Effort ongoing, but I don't see a fast solution to this anytime soon.

**Comment by adbenitez** [comment]
Not sure if this is useful, but some days ago while seeing the logs, I found a message that said: "Skipped 55 frames! The application may be doing too much work on its main thread."
Screenshot:
![screenshot_20190128-205352](https://user-images.githubusercontent.com/24558636/52011063-01358800-24a5-11e9-8b00-b010e46e3643.png)
