### ISSUE TITLE
Update target SDK Version

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#436]
Our targetSdkVersion is currently 25.
For deployment in Googles Play store we will need at least 26 at the moment but should consider doing more then that.

Also our current gradle version is lagging behind, we should check if we can get more up-to-date on that as well.

While we are at it, we should check if we can upgrade our dependency versions as well, many seem dated and it would be beneficial to have an overview of what we have, why we need it and what the best version for us is.

This should not happen as long as we still have code in the codebase that is scheduled to be deleted (like SmsDatabase or similar).

I'd target Mid-January for it.

**Comment by r10s** [comment]
> I'd target Mid-January for it.

good prediction, btw!

**Comment by r10s** [comment]
issues as expected :) first one: notifications stop working since the sdk change: https://github.com/deltachat/deltachat-android/issues/708

**Comment by Ampli-fier** [comment]
Probably worth checking the Signal commits for this. Had the Impression this was done for 'them'.
