### ISSUE TITLE
View pictures in full screen

### ISSUE THREAD

**Issue by bokf** [deltachat/deltachat-android#438]
When I open a picture from the chat I get some informations in the top bar, reducing the size of the picture.

![foto](https://user-images.githubusercontent.com/25562831/51485799-3fdd8b00-1d9f-11e9-911a-3b439cd2aba6.png)

In other programs by tapping on the picture I can change the view from full screen to reduced view with informations and vice versa. Would be nice to have also here the possibility to change to full screen by tapping on the picture.

**Comment by violoncelloCH** [comment]
I think it would be good to use the full display space for the image already initially and show status bar, top menu bar and the bar with the home and back button (depending on the android version) semitransparent... then on click or zoom all these ui elements should be hidden...

**Comment by r10s** [comment]
this issue is stale, moreover, feature requests should better go to https://support.delta.chat - feel free to continue the discussion there.
