### ISSUE TITLE
dark mode needs some tweaking

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#439]
when things are settled a bit, i think we should tweak the colors in the dark mode a bit.

also i'd like to have a plain dark background as the default background, not the wallpaper as in the light mode.

**Comment by sitzer** [comment]
in darkmode the cursor-indidactor bubble is grayish as in the lightmode. 
When I edit a text that is several lines long and i move to the first line, the indicator is hard to see...
Signal for example uses a light blue indicator -> better contrast....
System: Lineage 15

**Comment by Simon-Laux** [comment]
![screenshot_20190214-175042__01](https://user-images.githubusercontent.com/18725968/52802995-549cfe00-3081-11e9-8029-ea48a65283b4.jpg)

**Comment by Jikstra** [comment]
<Fist of Satan> I think the dark theme is hard on the eyes (it is hard to distinguish the cursor or text selections from the background). And transparant status bubbles (date etc.) might be not a good idea with custom backgrounds (images).

![EmymyewDcOuPoRpbLWYeLuFr](https://user-images.githubusercontent.com/34889164/54427151-f0ba3380-4719-11e9-9673-e4effdde7d71.jpg)
![EhNoaNDNcTrEQYhSZhlVDcAB](https://user-images.githubusercontent.com/34889164/54427154-f31c8d80-4719-11e9-897f-27a90e105c32.jpg)

**Comment by adbenitez** [comment]
"invite a friend" view is not changed in dark mode

**Comment by r10s** [comment]
closed by #811
