### ISSUE TITLE
auto-correction in server input field should be disabled

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#441]
not sure if this can be disabled or if it is only a behavior on my moto-g:

when entering a server in the RegistrationActivity, after typing eg. `imap.` the input field changes it to `IMAP.` - for whatever reason ...

**Comment by violoncelloCH** [comment]
I would like to try to do this... could you point me to the right file? :)

**Comment by violoncelloCH** [comment]
and it works!
should I do the same for the login-name fields? there you potentially type something like prename.lastname@example.com and it would be changed to Prename. too...
