### ISSUE TITLE
show "new message marker"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#447]
when entering a chat, there should be a marker above the first unread message.

this marker can disappear when sending messages and is also not important while chatting (unless the last messages is not visible due to scrolling away, cmp #731)

however, when the screen goes off and on again and new messages arrive in between, the marker should appear.

the last parameter for [dc_get_chat_msgs() (marker1before)](https://c.delta.chat/classdc__context__t.html#a51353ff6b85fa9278d2ec476c3c95eda) can help on this issue.

**Comment by adbenitez** [comment]
is this implemented??? it was weird, but yesterday I have seen a dark marker and if I remember well a text saying the number of unread messages, but that is the first and only time I have seen this marker, it was kind of an illusion, please tell my I am not driving crazy!!!!

**Comment by r10s** [comment]
afaik it's not yet implemented ;)

but maybe there is a hidden view that pops up only every 42 days or so for a fragment of a second :)

**Comment by violoncelloCH** [comment]
![img_20190301_131250](https://user-images.githubusercontent.com/22591354/53657313-23622780-3c56-11e9-8da0-f8d6d8dd3797.png)
@adbenitez are you talking about this thing?
It's strange, because it appeared above a message I sent myself... and I sadly don't know how to reproduce, but at least I've been fast enough to take a screenshot when it appeared the second time...

**Comment by adbenitez** [comment]
violoncello I am "offline" could you send the image to adbenitez@nauta.cu ??
I was so amazed that I could not take the screenshot, also this happened only once to me.

**Comment by r10s** [comment]
@violoncelloCH thanks, interesting, so it's already there, but just not displayed accordingly

@adbenitez so you were not dreaming or driving crazy but you have very good eyes :)

**Comment by r10s** [comment]
so, basically, the "new message marker" is there but not shown.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/940
