### ISSUE TITLE
refine document messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#448]
- [x] display in blue as for the old t'gram-version
- [x] the file-attach icon should also be in blue
- [x] staging area should be improved

see also https://github.com/deltachat/deltachat-android/issues/522

**Comment by violoncelloCH** [comment]
shouldn't there be #522 referenced instead of #153 ? That's possibly mixed up because of issue moving from deltachat-android-ii to deltachat-android, isn't it?

**Comment by r10s** [comment]
@violoncelloCH yip, thanks, corrected this.

/me thinks the issue moving of github can still be improved :)
