### ISSUE TITLE
Message order mixed on multi-client setup

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#452]
I have started to use DC v0.91 and when messages started to be synchronized to the new app then some of them lost the correct chronological order, and I ended up with chats having this look:
>[Yesterday]
>\<some messages>
>[Today]
>\<some messages>
>[Yesterday]
>\<the rest of messages from yesterday>
>[Today]
>\<the rest of messages from today>

Look at this as a warning that something may be wrong, since I can provide more data and this issue is a bit useless. Also I have imported a backup prior to the sync, maybe that could be related.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.91

**Comment by angelo-fuchs** [comment]
@r10s Should this issue be transferred to deltachat-core? Seems like not much -android can do about it

**Comment by r10s** [comment]
this should be fixed by the effort to https://github.com/deltachat/deltachat-android/issues/631- it were only the headlines that were superfluous and were related to the sending time, not to the receiving time (the list is always sorted by receiving time)
