### ISSUE TITLE
visual feedback missing when changing contact notifications

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#453]
Changing the notification sound and vibrate options for a contact have no visual effect in the settings, they are set in the background but not visually in the contact is settings, in the case of the vibrate option if you go back an open the settings again it is updated with the user selection but the sound option still don't show the selected value.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.92
- Steps to reproduce the problem: Go to a contact is profile and try to change the the notification sound  and vibrate options, they are changed internally but not visually.

**Comment by r10s** [comment]
related issue: https://github.com/deltachat/deltachat-android/issues/715

**Comment by r10s** [comment]
i think as the profile is reworked now, it make sense to have a closer look at this (the corresponding code parts are not copied, so we rescued the bug while reworking the profile ;)

**Comment by cyBerta** [comment]
fixed in PR https://github.com/deltachat/deltachat-android/pull/935
