### ISSUE TITLE
video recording

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#454]
we should consider bringing video recording to delta-dev (it is there in the current tg/f-droid verison).

while recording as such is very simple (only an activity), the harder part is the recoding - resulting files should not be larger than `dcContext.getConfig("sys.msgsize_max_recommended")` bytes (about 17 mb or so).

the telegram-ui recoded using ffmpeg c-lib, however, i think we should try doing this with a java-lib first, maybe exoplayer can also recode.
EDIT: in any case, it also makes sense to update the exoplayer at a given time, eg. signal updated to 2.8.4 at https://github.com/signalapp/Signal-Android/commit/db9bfb4b2fa5be22416ff959533ea677fe5dae49

finally, it would be really nice to get the cut-video-activity from the telegram-version :)

**Comment by angelo-fuchs** [comment]
wrt min sdk: We can also disable features if the older SDK doesn't support them. (So users on old phones would get a DeltaChat that has all the features their phones can do, but "fancy" stuff is only for more current phones)

**Comment by cyBerta** [comment]
The repository was moved and VideoEditorActivity can be found here [here](https://github.com/deltachat/deltachat-android-old/blob/master/MessengerProj/src/main/java/com/b44t/messenger/VideoEditorActivity.java)

**Comment by r10s** [comment]
@cyBerta iirc it will take some time until the work on this will start from you site. to not block the issue until then, i've unassigned you for now. feel free to reassign when work on this has really started.

**Comment by r10s** [comment]
closed by #883 :)
