### ISSUE TITLE
video preview thumbnail

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#455]
video preview is still missing in the chatview as well in the media overview. in the "sliding" view, however, it is there.

not sure if it is needed to cache one or if generating on the fly is fast enough. in the "sliding view", however, i did not notice any delay.

currently, only a play-button is show in the chatview as well as in the media overview; this play button shall stay as an overlay over the thumbnail.

related: #165

**Comment by florianhaar** [comment]
I will look at this

**Comment by r10s** [comment]
closed by #883
