### ISSUE TITLE
After autocrypt exchanging private key messages are still not readable

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#457]
**Delta Chat version**

0.0.6

**Expected behavior**

I can read encrypted messages after i did an autocrypt sync. Doesn't make any difference if I sync with desktop or "old android" client.

**Actual behavior**

It still says "Message was encrypted for another setup"

**Steps to reproduce the problem**

1. …
2. …

**Screen snapshots**

**Debug logs**
<details>
<summary>Logs</summary>

```

<!--
If applicable, debug logs can be copied from within the Delta Chat app: 

Open the _Settings_ menu -> _About_ -> _version number|Info_.

Alternatively from the Android system log:

` adb logcat -v time -s DeltaChat `

This log contains private data (e.g. mail address, provider information) which shall be removed or anonymised prior to posting.
-->

```
</details>

**Comment by r10s** [comment]
i think this works meanwhile, please re-open if not.
