### ISSUE TITLE
relatively slow change from ChatList to single Chat view? 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#458]
Am currently using dev (0.0.3) on a Moto-G4  and i find there is a slight but noticeable delay when touching a contact in the chatlist view -- before the selected chat opens.  Subjectively the current TG-based version is faster there ... Does anyone know, is it easy to profile what is going on?  Found this reddit-thread which sounds interesting but it's a tad old and contains some hints maybe: 
https://www.reddit.com/r/androiddev/comments/2e5kfn/what_do_you_guys_do_about_slow_loading_between/

**Comment by r10s** [comment]
i think we can close this one in favor to the broader https://github.com/deltachat/deltachat-android/issues/435
