### ISSUE TITLE
Low quality contact picture

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#463]
In the Profile view, the contact picture is shown with a really bad quality, just like the little avatar was zoomed.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.98.2
- Screenshots:

**Contact picture in the phone Contacts app:**
![contact-pic-original](https://user-images.githubusercontent.com/24558636/51490638-e3b44000-1d79-11e9-9605-0e4f83a9d368.png)

**Contact picture in Delta Chat:**
![contact-pic-dc](https://user-images.githubusercontent.com/24558636/51490666-f6c71000-1d79-11e9-8939-7b54a1ba7839.png)

**Comment by Boehrsi** [comment]
The commit fixes the problem, but sadly only for newly imported / loaded contacts. @r10s is there a way to import contacts again or to reload the contact images?

**Comment by r10s** [comment]
no, afaik, there is no way to re-import without putting much more effort in the issue. i'd say it's the fix is fine and reasonable. thanks :)
