### ISSUE TITLE
Disable / customize footer / Topic prefix

### ISSUE THREAD

**Issue by jbacksch** [deltachat/deltachat-android#47]
Option to disable or customize footer / topic prefix

**Comment by r10s** [comment]
It is planned to make the footer customisable.

The subject prefix `Chat:` will stay equal for all users to make it easier to filter such messages in other e-mail-clients (regard this analogue to `Re:` or `Fwd:`)

However, if there are better ideas than `Chat:` - maybe we will change it globally as long as Delta Chat in beta state.

**Comment by rizzopablo** [comment]
The prefix could be Chat by default, but configurable too... just a thought.

**Comment by r10s** [comment]
> The prefix could be Chat by default, but configurable too... just a thought.

What would be the advantage to let the user configure the prefix?

I only see the disadvantage, that incoming messages cannot be easily filtered if one sender uses "Chat:", the other "Message:" and the next one "Heinz:"

**Comment by stefan-niedermann** [comment]
You often communicate with users that do not use Delta Chat. Therefore it could be not adequate if you respond to e. g. business emails or your non-tech-family could be confused.
I think too, it should be optional or at least be customizable, like "Message from `my-name`" or so.
Another point is that chat may work in english and german, but in other languages there may be used other words (or is `chat` translated, too? - this would be another argument that there is no problem to make it customizable).

**Comment by rizzopablo** [comment]
I use the X-Mailer header to filter chat messages, not the subject.

**Comment by LordTyrius** [comment]
Maybe an option to mark chats where the recipient does not use delta chat would solve this, by allowing different behavior for subject/footer?

**Comment by r10s** [comment]
- The footer is customizable since the last version.

- regarding the `Chat:` prefix: We see it similar to `Re:` and `Fwd:` and would like it becoming a standard that can be used eg. for easy filtering and is just a well known mark. An exitable prefix would not help on this point.

**Comment by r10s** [comment]
see also #97

**Comment by testbird** [comment]
Actually, the english `Chat:` prefix may work in many cases, but never for all (it may have other meaning in another language, or even no meaning with another alphabet.)

So it doesn't seem a good idea to rely on it, it should be translatable. TI may be a good idea to only fully rely on a well defined e-chat spec version compliance indicating header.

**Comment by kevincox** [comment]
It's also worth noting that the `Chat:` prefix isn't useful for filtering in gmail since the search tools don't support prefix matches. Since this is one of the largest email providers it seems like this basically eliminates the utility.

**Comment by r10s** [comment]
i opened a new issue there this discussion can be more focused at https://github.com/deltachat/deltachat-core/issues/136
