### ISSUE TITLE
Picture Viewer quality is not corresponding to resolution

### ISSUE THREAD

**Issue by bokf** [deltachat/deltachat-android#55]
I have noticed, that the pictures a resized to ca. 1280x960 pixel. If I open the pictures by tapping on it, the quality is not corresponding to this resolution. If I open the same picture outside of Delta Chat, the quality is much better. Opening the picture on a tablet in Delta Chat the picture is not very clear and not nice to look at. I would like the internal viewer to show all the pixels or use an external picture viewer.

**Comment by r10s** [comment]
Thank you for your report, I've also notices this issue some day - but forgot it in between.

I will fix this ASAP.

**Comment by r10s** [comment]
NB: In between, you can display images in high-quality by **long-pressing** them and then select **Open** from the upper right menu.

**Comment by angelo-fuchs** [comment]
Hypothesis: In ChatMessageCell:1428 -> The thumb image and the actual image are the same on first load.
Maybe the actual image gets thumbed, but stored under the original size of the image in the list of images (or the image in cache gets overwritten by the thumb)

**Comment by angelo-fuchs** [comment]
Seems like "photoImage.setNeedsQualityThumb(true)" does it...

**Comment by testbird** [comment]
Noticed a newly received photo first looked blured in chat, and clicking it opened if fine in zoomable in full view, but going back into the chat it switched to fine in the chat, unzoomable blurred in full screen.
