### ISSUE TITLE
Emojis / smilies selection no longer scrollable

### ISSUE THREAD

**Issue by lombard0** [deltachat/deltachat-android#56]
After writing ":D :) :p  :@" plus some smilies from selection menu, selection menu for smilies doens't show up properly. It is only possible to hit categories, which leads to different emojis (e.g. bell = teddy bear, car = banana, but randomly changing), see also screenshot:

http://fs5.directupload.net/images/170321/6mibtjrc.png

I'm using v0.1.21 and Blackberry OS 10.3.2.2836

**Comment by r10s** [comment]
I cannot reproduce this on Android, and I do not have a Blackberry test device. Can anyone confirm this issue on blackberry? 
Or maybe someone has a still working blackberry device that is no longer needed? We're always looking for [test devices](https://delta.chat/en/support#donate).
