### ISSUE TITLE
Don't open keyboard after open the contactlist

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#601]
It's nerved if the keyboard opening immediately after I open the contact list.

The keyboard should opening first if I tap into the search field.

Dev-version 0.0.9

**Comment by licaon-kter** [comment]
Here's one thought: I didn't know how to add a contact because it's not clear that **it's an input field**, it looks like the _titlebar_ of that view.

While groups get special buttons, this input field works both as _search_ and as _add_ ?
