### ISSUE TITLE
flaky message sending delays

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#602]
Sending failures (like an unstable router in the network or temporary server errors) can delay sending to occur much later than intended (even days) after everything works again.

I guess what happens is that first in several iterations the *random* delay is shorter than the time passed since the original job creation (may happen in about half the cases?), and thus the retry occurs immediately and the failure count increases quickly, until after several iterations the delay "shoots up" (due to randomization with exponential bounds) to many minutes or even hours.

A possible and straightforward solution should be possible with four small code changes, see https://github.com/deltachat/deltachat-core/pull/446#issuecomment-441385285

---

Following is a summary from past discussions, about a solution to *continuously and deterministically* ensure that messages are
* sent as soon as possible, but battery saving starts to set in after a while as
* attempts are reduced with 3.33 minute timeouts, if traveling weak flaky networks,
* and 10 minutes timeouts, if the network connection is stable (possibly longer lasting server/routing problems).
* While a new local network connection (wifi) and dc_maybe_network() also causes **all** messages to be sent immediately.

To limit traffic:
* Permanent errors from the smtp server should cancel a job immediately (Looks as if message size and space errors are already catched.)
* It should be possible to continue interrupted transmissions. (I don't know if the smtp library supports this feature.)

To send ASAP and save battery: 
* If there is no network connection available at all, of course no attempts should ever be made.
* With a network available, start doing rather quick retries to process all jobs (one pass goes through the whole queue in the order of creation, failing individual jobs). With simple delays between the passes and only up to max. 7 seconds between retries (no randomization required).
* Every pass starts with the oldest message, but goes on trying the next later messages if one message fails, to keep the message order if possible.
* To save battery, count the number of uncompleted passes with a "circuit breaker" that interrupts ("opens") the retry loop for longer periods (e.g. from 6 up to 10 fails => 30 seconds,  up to 14 => 1 minute, up to 20 => 5 minutes, and 10 minutes beyond 20 fails)
* When the circuit is "open" (waiting), also block any newly active online status (volatile weak flaky network connection) from triggering an immediate retry, only allow a single retry (pass) after the circuit breaker has already waited for 1/3 of the current timeout ("half-open" circuit state).
* However, a call to dc_maybe_network() (e.g. new wifi connection) should cause a new pass of retries immediately.
* Temporarily failing messages may be canceled after being in the loop for some amount of time since creation, but because servers cancel messages with transient smtp failures usually only after a couple of days have passed, the local canceling may be better left completely to the user of the local device (to avoid that long vacations etc. without network lead to automatically canceled messages while the user would still be able to control the actions)

See https://dzone.com/articles/understanding-retry-pattern-with-exponential-backover

**Comment by adbenitez** [comment]
this is still an issue, we(Cuba) are sometimes experimenting long delays in sending with DC, the only way to avoid them is to restart the app and it is quickly sent

**Comment by testbird** [comment]
Yes, regrettably,  the delays on error are too long sometimes and also mixing up messages too much for a chat app.

But straightforward actionable items exist. :-)
 (https://github.com/deltachat/deltachat-core/pull/446#issuecomment-441385285)

**Comment by testbird** [comment]
Note, there is really no need for stats and "research" if the problem is confirmed and a clearly identified result of the code.

**Comment by adbenitez** [comment]
I receive a lot of complains from users about Delta Chat taking too long to send, and even sometimes it seems to take forever, and also problems receiving, people keeps killing&restarting the app quite often to make it work faster, this seems to be a problem specific of slow unstable networks ,

related: https://github.com/deltachat/deltachat-android/issues/788

**Comment by testbird** [comment]
On the IMAP side with its continuous connection it may make sense to base the keep-alive timeout also on a get_keep-alive_offset() that starts short and only gets longer if there are no interruptions (stable network conditions).
