### ISSUE TITLE
Telegram-like command keyboard

### ISSUE THREAD

**Issue by dzervas** [deltachat/deltachat-android#62]
I want to use deltachat as a bot controller, so it would be nice to be able to send an email from the bot with a custom header and the client displays the available commands as quick-send links (see https://core.telegram.org/file/811140184/1/5YJxx-rostA/ad3f74094485fb97bd).

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
