### ISSUE TITLE
Better folder management

### ISSUE THREAD

**Issue by dzervas** [deltachat/deltachat-android#63]
I'd love to see a more customized folder management.

I want to be able to set deltachat to watch only the "chat" folder (emails that start with "Chat:" will be moved to "chat" folder from sieve or other mail filtering that a server runs).

I'd also like the ability to automatically move all the chats to Chat folder, rather just copy.

**Comment by r10s** [comment]
see https://github.com/deltachat/deltachat-core/issues/47
