### ISSUE TITLE
Lock pattern UI error

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#644]
If the screens turns off while inside a chat and user turn it on (before it locks) Delta Chat shows a black screen (the pattern screen) with all text and the pattern dot grid invisible, user must "guess" where the dots are...

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.98.2
- Steps to reproduce the problem: go to display settings and set the sleep timeout to the minimum value, go to Delta Chat and open a chat, wait the screen turns off, turn it on and you will see the pattern screen but with all text and dots are not visible
- Screenshots:
![screenshot_20190117-180129](https://user-images.githubusercontent.com/24558636/51548507-71556580-1e36-11e9-9aa9-3f7a56408fce.png)

**Comment by testbird** [comment]
> Delta Chat shows a black screen (the pattern screen)

Are you sure signal/deltachat is grabing the screen? Hoped it's the system's grid?

**Comment by adbenitez** [comment]
@testbird when the screen go off, but before it blocks, there are an interval that if you press the on/off hardware button of your phone, the screen turns on but you are not asked for your phone pattern, so yes it is Delta Chat, also it is exactly if you are inside a chat, if you are in the chat list this doesn't happen

**Comment by testbird** [comment]
Thanks, now I got it.

**Comment by Boehrsi** [comment]
While investigating #464 and #649 I tried to reproduce the issue and wasn't able to do that. I tried it with an older device and a Samsung S7. Both behaved just normal (the screen turns dark, but the lock isn't activated yet, so pushing the hardware on/off button just brings back the normal screen with the actucal content).
As already mentioned above we just request the system to show the lock screen, no matter how it looks and no matter how the actual security settings are. I sadly think we can't do much about this.

**Comment by angelo-fuchs** [comment]
@adbenitez When you turn you device off in that scenario and then on again (sleep / wakeup; not power off / on) does the screen work as expected?
Can you use the Home Button on your phone to leave DC?
If so and you enter DC again after that, does the Screen show normal or blank?

**Comment by adbenitez** [comment]
@angelo-fuchs  I do not turn off the device, the screen turns off itself, before the system locks the screen there are an interval when if you press the power button the screen turns on again without needing to unlock the phone, here is where Delta Chat, which was the foreground app, shows this black screen, as **it is delta chat** 
**I can minimize de app** and keep working with my device which **was never locked**

**Comment by adbenitez** [comment]
@angelo-fuchs  report part 2:
when this happens and I minimize the app, when I go back to the app **the chat list is shown(unprotected)** even when I was inside a chat, then when I tap a chat the normal pattern screen is shown.

**Comment by adbenitez** [comment]
actually  **part 2** is happening always when I minimize the app, not only when the black screen is shown!! I think I had already reported  this anyway... can't remember well...

**Comment by Boehrsi** [comment]
@adbenitez it's Delta Chat which triggers the displaying of the screen, as the app requests the system to show the lock screen as soon as it's not in the foreground anymore. So as soon as the system gives the signal that the app is not shown anymore the lock gets applied (obviously with a kind of broken UI). 

There is no need that the device starts locking itself in general, to apply the Delta Chat locking behavior. So it's totally normal that you can minimize and use your device without problems, even if Delta Chat requested the lock, as the lock is only applied to the Delta Chat app, not you device in general.
Regarding your part 2, yes you already reported that (#649) and it should be "already" fixed, but it's not merged yet as it's in review. It's possible that #649 also helps with this problem, but as I wasn't able to reproduce it i neither can verify nor can I confirm that. 

Btw. I'm still trying to find a way to also get this broken behavior to see how it can be fixed.

**Comment by adbenitez** [comment]
Daniel if as you say, the system is the one failing and Delta Chat just trigger the lock screen, and since this is only happening in my phone at the moment, I recommend closing this, at least until this happens to someone else.

**Comment by r10s** [comment]
also tried to reproduce this without success.

however, with chance, might be that this issue is fixed or changed in a way by https://github.com/deltachat/deltachat-android/pull/706 :)
