### ISSUE TITLE
Low quality emojis

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#647]
The two people I helped to install 0.98.2, complains about the low quality of the emojis in the new version, the emojis look like zoomed with pixelated borders that make them look old and with low quality, especially for the new feature of showing emoji-only message bigger (BTW, they really liked this)
The emoji images in the source repository looks fine in a PC at work.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU  
- Screen: height(pixels):854, width:480 (density:1.5, densityDpi: 240)
- Delta Chat Version: 0.98.2
- Screenshots:
![screenshot_20190122-171205](https://user-images.githubusercontent.com/24558636/51570673-a9c46600-1e6d-11e9-8ef4-d6f2b7a4f1eb.png)
![screenshot_20190122-173203](https://user-images.githubusercontent.com/24558636/51570688-b21ca100-1e6d-11e9-81b0-c32cf10f3e66.png)

**Comment by r10s** [comment]
interesting. for whatever reason, the scaling is pixelated, have not seen this on devices i am using here yet.

**Comment by r10s** [comment]
i think this issue is a bit stale and without further information, for reproducing there is no actionable item.
