### ISSUE TITLE
gravatar support

### ISSUE THREAD

**Issue by rafaelmr2** [deltachat/deltachat-android#65]
Hi, 
I our webmails (SOGo and Roundcube) we have support to gravatar. It's possible to add feature to Delta?
Thanks.

**Comment by r10s** [comment]
Of course it is possible to add this feature. Just looking for anyone who can implement this ...

**Comment by stefan-niedermann** [comment]
Connecting a proprietary service without opt-in? Might this be a privacy issue?

**Comment by r10s** [comment]
Well, currently, we do not have this feature. I only mentioned that it is _possible_ to add such things. And you're correct, if one offers such a feature, it should be opt-in.

_I_ think, _I_ would not implement it for myself.

Instead, I have the idea to select avatars for groups that are send to all group members as normal mails then (similar to the "group name changes" that are already implemented this way).

If this is implemented, maybe we can find a way to handle normal chats similar.

**Comment by r10s** [comment]
All in all I think, this would be a large loss of privacy, I do not believe this is a good idea for a decentralised service. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
