### ISSUE TITLE
restore from backup? missing? v.100

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#652]
I've backuped all my chats, but I have not found a way to restore then?
Is it missing?
I've done the keys separately and that was fine

**Comment by webratte** [comment]
If you install the current DC version 0.100.0 from the scratch, you got the option to restore your backup.

I did it a few minutes ago this way and it works fine.

**Comment by nutpantz** [comment]
I just get the same screen again(it refreshes).it does not work for me. Note4 android 6

**Comment by nutpantz** [comment]
Ok worked on the third try.. No idea why it did not work before.. I'll cheat data and try a few more times

**Comment by r10s** [comment]
export+backup should only be needed if you upgrade from android-dev, upgrading from 0.20 should work without.

import is only possible during setup.

will add a line to the changelog.
