### ISSUE TITLE
own name reset on editing after export/import

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#653]
the following is true only after an export/import:

the name is used correctly from the database, however, when editing it at "settings / own profile", it is always shown as empty.

i assume the name is stored somewhere in the android-preferences _and_ in the core-database, however, read only from the android-preferences.

after the name is edited the first time, everything is fine again.

i would check the same for the profile image btw.

**Comment by adbenitez** [comment]
I think I reported this time ago :-P

**Comment by r10s** [comment]
@adbenitez for whatever reason, i did not found it yesterday, now i got it :) 

closing this issue in favor to the original reported by @adbenitez then, https://github.com/deltachat/deltachat-android/issues/423
