### ISSUE TITLE
While typing, image removal icon not visible

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#662]
I suggest we move the red X from the image so that it always stays in visible area. (Meaning: It stays where it is, as long as that position is visible and moves down into the visible area if not)

When I add an image (that is tall, like a screenshot) and write text for it, I cannot see the X to remove the image.  I can also not scroll to get up to the X.
![image_edit_with_keyboard](https://user-images.githubusercontent.com/10619521/51760498-d2956700-20ca-11e9-8dcf-58fe02cea8b4.png)

I need to minimize the keyboard before seeing the X.
![image_edit](https://user-images.githubusercontent.com/10619521/51760528-e50fa080-20ca-11e9-8fd3-5e79600bde00.png)

**Comment by r10s** [comment]
i would not add scrolling here as the area above the staged image is already scrolled

maybe the image could be scaled to fit the space above the keyboard, however, this may also cause some flickering/jumping and may cause different irritations. also on small screens, the scaled image would become very small.

things will become even more complicated/gickering/jumping if more text is typed in as the input field grows in height then - there may be just no place left. 

otoh - well, the image is fully visible again when the user hits the back-key. 
ui-wise, when the user starts typing a text, he already does not find the image _that_ bad :)

so, i would just leave things as they are now. alternatives are complicated and might result in other problems.

**Comment by adbenitez** [comment]
As @r10s said at this point user probably don't want to delete the image, but I think anyway this should be possible, so here comes my suggestion:
What about showing a dialog with options "edit" and "remove" when user long press the image???

**Comment by adbenitez** [comment]
or well, since edit is always accessible perhaps just showing a dialog with text: "Do you want to remove the image?"

**Comment by r10s** [comment]
left lower corner for closing also sounds also very unexecpected to me. would be also close to the emoji-toggler and maybe raise a bunch of other ux problems. i would not go for it.

**Comment by adbenitez** [comment]
good point, perhaps just pressing the back button as you suggested is good enough and will avoid a lot of other problems...
