### ISSUE TITLE
crop images before sending

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#664]
All users I have shared Delta Chat v0.100 with, complain about the new image editor, the old image editor (I guess it is the system build-in one) has options to crop the image, this is not possible now with this new image editor.
They mostly want to crop the image to reduce the size, so options for scaling, or selecting image quality/compression (ex. high, medium, low) would be really appreciated.

- Delta Chat Version: 0.100

**Comment by r10s** [comment]
yeah, would be great if this is re-added. could be a simple option just below the current painting options.

**Comment by r10s** [comment]
wondering if this is supported by the system - at least the avatars selected for a group or self can be cropped.

**Comment by r10s** [comment]
yip, came over that these days, there is a system-intent that does this. not sure, if it is the easiest way to support that, however.

**Comment by cyBerta** [comment]
> wondering if this is supported by the system - at least the avatars selected for a group or self can be cropped.

Nope. It's an library that is used to crop the avatar images. (com.soundcloud.android:android-crop:0.9.1)

**Comment by r10s** [comment]
k, i see. integrating the sources to our code may make sense, at least if there is no other easy-enough-to-use lib. still, i would peek to the signal code before - maybe cropping is added there already :)

anyway, i think the place where cropping should be added should be below the other edit-options:
 
<img src=https://user-images.githubusercontent.com/9800740/60275309-04209180-98fa-11e9-9dfd-c182b2e42aa7.png width="300">
