### ISSUE TITLE
Signature text cleared in profile settings

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#666]
If I change my signature text and later I decide to set it back to the original value, when I save the changes the signature text is removed/cleared like if it is not possible for an user to set the default text as a value for it.

- Platform (android/blackberry/anbox): Android 6.0
- Device:BLU
- Delta Chat Version: 0.100

**Comment by r10s** [comment]
thanks for reporting, changed the behavor in the core as this makes things also easier for desktop/ios at a later point
