### ISSUE TITLE
Unclear who is working on what issue

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#668]
If I see all these issues I think it's time to make development more clear for developers and users.
There are many issues open but it's not clear who is working on what issue and what is the time line.

There should be a plan who's working on what issue with what timeline to prevent double or unnecessary workload.

Any ideas?

**Comment by csb0730** [comment]
Maybe open a wiki for that?

**Comment by r10s** [comment]
in general, i think we try to use the github **Assignees**-function to indicate who wants to work on an issue. or at least add an corresponding statement.

issues where no one is assigned to may not have someone that cares about just in that moment.

if someone wants to work on an issue and does not have write access (yet) may just drop a comment to the issue so that someone else can assign him.

**Comment by r10s** [comment]
also, of course, not all issues will result in sth. being done. or it is unclear what to do. many issues start with a discussion about what should be done at all, https://github.com/deltachat/deltachat-android/issues/662 is an good example.

wrt a time line - well that's probably harder :)

**Comment by angelo-fuchs** [comment]
I try to garden the labels a bit to make it more clear. If someone starts changing code for an issue one should assign oneself to it. Until anybody is assigned its relatively safe to assume nobody is code-wise working on it.

- [Bugs](https://github.com/deltachat/deltachat-android/labels/bug) should be worked on, I prioritize (and expect others to prioritize) them over
- [Feature Requests](https://github.com/deltachat/deltachat-android/labels/feature%20proposal) which denote stuff we don't do yet, but someone would like us to.
- [Discussions](https://github.com/deltachat/deltachat-android/labels/discussion) are, at least for me, the least important issues. This marks stuff that we should talk about that may (or may not) result in any action.
- [Cleanup](https://github.com/deltachat/deltachat-android/labels/cleanup) marks stuff that I personally work on them before I work on Feature Requests, but that's just me.

Regarding Timeline: When Its Done (or when someone pays me for it). For further discussion I refer to The Mythical Man Month.

**Comment by angelo-fuchs** [comment]
@csb0730 Is it more clear now who is working on what? Can we close this issue?

**Comment by violoncelloCH** [comment]
> wrt a time line - well that's probably harder :)

how about using milestones for the upcoming versions?
so just create milestones for v0.100.1, v0.100.2, v0.101, v1.0 and so forth... then you just add issues to these milestones (by priority)... 
once you want to release v0.100.1 and there are still open issues left for the corresponding milestone, you simple move all of those remaining ones to v0.100.2 or whatever...

I think milestones in combination with assignments make up a great but simple planning management.

**Comment by ralphtheninja** [comment]
@csb0730 Note that there are meta projects like https://github.com/orgs/deltachat/projects/7 which allow you to gather issues across different repositories, since we try to keep development somewhat in sync across different delta chat implementations.

I don't know about everyone's background, but it might be the case that some people on "the outside" have a more traditional background when it comes to project management etc. Lack of clarity and information can be a source of frustration and we all feel this, but this is also somewhat part of the open source and free software style.

It's not a team of 20 to 50 people working 40 hours per week solely on delta chat issues, some people make drive by contributions etc so for that reason it's difficult to run a project in a traditional way. Also, not everyone is doing paid work. Please just keep this in mind :)

**Comment by violoncelloCH** [comment]
> @csb0730 Note that there are meta projects like https://github.com/orgs/deltachat/projects/7 which allow you to gather issues across different repositories, since we try to keep development somewhat in sync across different delta chat implementations.

@ralphtheninja these projects are not public (I have the "contributor" label and can't access it either)... is this intended this way?

**Comment by ralphtheninja** [comment]
> @ralphtheninja these projects are not public (I have the "contributor" label and can't access it either)... is this intended this way?

Nope, it _should_ be public imo. Will fix.

**Comment by ralphtheninja** [comment]
@violoncelloCH Please try again.

**Comment by violoncelloCH** [comment]
@ralphtheninja thanks! now it's public!
note, that's the only project which is public now... should the others be public too?

**Comment by r10s** [comment]
there are no others projects atm :)

**Comment by violoncelloCH** [comment]
Ahh then everything is fine... just thought because @ralphtheninja wrote "meta projects like"...

**Comment by csb0730** [comment]
@angelo-fuchs & everyone
Yes, it's now more clear for me :) ... and @ralphtheninja please see this issue here not so strict in matters of timeline. That's not so important IMHO.

In general it's interesting for people what are the next issues which will be attacked. So I find @violoncelloCH 's proposal very useful for everyone:

> I think milestones in combination with assignments make up a great but simple planning management.

The most important thing is, that - because of limited resources - it should be prevented, that someone works on an issue, but don't knows that someone else is working on the same issue too. It's frustrating at the end to invest hours of time to throw it away.

If we can have this information somewhere in a transparent way this issue can be closed :-)

(Will now check .../deltachat/projects/7)

**Comment by csb0730** [comment]
Checked "../projects/7"

But I assume a simple _NEXT_MILESTONES.md_ or a simple Assignee indicator at issue (@r10s) could help and would be sufficient?

**Comment by angelo-fuchs** [comment]
@csb0730 Cool. We already have the Assignee indicator (whenever someone works on a thing, s/he assigns it to themselves).
We had a lengthy discussion on IRC yesterday about milestones and in general are opposed. One thing I will do today is move the feature requests to the forum (where they actually belong) so the github issue tracker is for bugs and new features someone is actively working on, right now.

That way its also clear what is currently worked on (in terms of features) and what not.

**Comment by csb0730** [comment]
Hi @angelo-fuchs
the Assignee indicator is great :-)
This makes development really more transparent for everyone!

Thanks a lot :-)
