### ISSUE TITLE
Label Gardening

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#671]
We have 15 Labels: https://github.com/deltachat/deltachat-android/labels/

I'm quite certain we don't need them all so I suggest to cull the following:

- [anbox](https://github.com/deltachat/deltachat-android/labels/anbox) - only one closed question. We don't have other active system tags and I don't think we need them.
- [blackberry](https://github.com/deltachat/deltachat-android/labels/Blackberry) - No questions and we don't have other system tags for it. I don't think we need them.
- [targeted in android-dev](https://github.com/deltachat/deltachat-android/labels/targeted%20in%20android-dev) android dev is now android normal, so this become obsolete.

I'm unclear about what

- [question](https://github.com/deltachat/deltachat-android/labels/question) is actually about and if we need it. If **yes**: Someone in the know should please add a description what distinguishes questions from discussions, bugs and feature-proposals. If **no**: We should cull it too.

PS: This issue is considered completed as soon as either all four labels are taken care of or a week has passed and nobody cared.

**Comment by r10s** [comment]
i do not have a strong opinion about an exact label list, i think we should just add labels as needed as yes, it may make some sense to remove completely unused labels.

however, label-deletion makes information harder to access.

eg. it is handy for the upcoming blog post or other statistic reasons to see which issues were targeted in by the switch to the signal ui - this is no longer possible when the label is deleted.  
so, i would suggest not to delete targeted-in-android-dev _just now_. i sill use it actively for searching and we've also used it as links here and there.  

we can delete targeted-in-android-dev after some time, however, i would leave it now (of course, no new issues will be tagged with it)

backberry / anbox otoh can be deleted imo.

the "question" tag - well i would leave it, although it is close to discussion, it makes things a bit clearer.

btw. the color of the question/discussion/feature-proposal is not by random. in general, this light-yellow indicates that these issues typically do not contain a concreate actionable item and will probably be close - or, of course, may turn into another issue :)

**Comment by angelo-fuchs** [comment]
@r10s Could you come up with a better explanation of "question"?

**Comment by r10s** [comment]
well, it's a question :) i do not have a more concrete definition or so, but as it was used in the past sounds reasonable to me - "Adjust or remove address object?" - "KeyCachingService superfluous?" - "what is the '/patches' folder needed for?" - "for what exact reason is SASL needed?".

it may indicate one maintainer has a question to other ones. or to indicate sth. where some more research is needed.

of course, all these are also discussions in a way. maybe, for questions it's maybe more probable that they can be resolved by some facts whereas discussions may include more opinions. but, of, course, it's not black-white :)

@angelo-fuchs however, i can live without the question tag, no problem, got your point as well. so i would leave the decision whether to remove/leave/rename/whatever to you.

**Comment by angelo-fuchs** [comment]
@r10s I leave it. Thank you for the input. When I can come up with a good description, I will add it.
