### ISSUE TITLE
contact avatar not updated in Chats list  and contacts list views

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#677]
I have updated the picture of a contact in my phone contacts app, now the old avatar is shown in some views in Delta Chat, but it shown properly on a 1x1 chat with that contact, see the screenshot.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.100
- Screenshots:

![screenshot_20190126-002555](https://user-images.githubusercontent.com/24558636/51862759-4b840100-230d-11e9-84f5-78d860eef3c2.png)

**Comment by angelo-fuchs** [comment]
Does that change when you restart the phone / force kill delta?

**Comment by adbenitez** [comment]
I restarted the phone, (I had tried killing the app time ago) but this doesn't work, this is happening since  several days ago, and seems a permanent issue, will try changing the avatar again to see what happens.

**Comment by angelo-fuchs** [comment]
@adbenitez I can reproduce this.
To get the avatar I had to hit the '+' Icon on the Conversation List. Only after that the contact avatars were synchronized.

**Comment by adbenitez** [comment]
yeah! that used to work for me, but now it doesn't, but probably has nothing to do with DC

**Comment by adbenitez** [comment]
I have done a factory reset, and start testing this again:
1. loaded contacts with avatar in DC.
2. edited a contact and removed his avatar picture.
**STATE:** contact avatar was updated in-chat and in contacts list(new chat activity), but still is the old picture in chat list.
3. pressed the '+' button to check if this force an avatar sync, as suggested by @angelo-fuchs 
**STATE:** same as previous.
4. closed Delta Chat and reopened it.
**STATE:** same as previous.
5. restarted the phone.
**STATE:** same as previous.

**Comment by r10s** [comment]
in general, the system avatars are updated only when entering the contact-list.

in addition to that, there were some caching problems that are fixed in between, so with chance, this is also fixed in the upcoming 0.500.0 ;)

if not, we can re-open.
