### ISSUE TITLE
Image shown in wrong day in gallery(all media)

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#685]
in a group chat, there was only one picture posted that day, (under the label "Today" as shown in the first screenshot) but in the gallery (all media) two images are shown under the header "today" one of them was from yesterday and isn't shown in the "yesterday" section (see the second screenshot)

- Platform (android/blackberry/anbox): Android 6.0
- Device:BLU
- Delta Chat Version:0.100
- Screenshots:

chat view:
![screenshot_20190126-115158](https://user-images.githubusercontent.com/24558636/52014634-0f3bd680-24ae-11e9-9f90-5e7eec2d1ec3.png)

all media:
![screenshot_20190126-115218](https://user-images.githubusercontent.com/24558636/52014674-2b3f7800-24ae-11e9-8442-e8afc012784f.png)

**Comment by adbenitez** [comment]
will do, it is happening again for other two pictures

**Comment by adbenitez** [comment]
this screenshots are all from 2 new pictures, the messages details are NOT from the old ones:
today pic:
![screenshot_20190131-082713](https://user-images.githubusercontent.com/24558636/52077259-96488780-255e-11e9-9063-e38bd0ddc469.png)
yesterday pic is shown under today header:
![screenshot_20190131-082629](https://user-images.githubusercontent.com/24558636/52077263-98124b00-255e-11e9-8c52-22735440c55b.png)
today pic is info:
![screenshot_20190131-133547](https://user-images.githubusercontent.com/24558636/52077272-9ea0c280-255e-11e9-86f5-b75ccd8ecc60.png)
yesterday pic is info:
![screenshot_20190131-082849](https://user-images.githubusercontent.com/24558636/52077274-a06a8600-255e-11e9-85c6-3699f3abaf6b.png)

**Comment by angelo-fuchs** [comment]
Thanks! I will investigate this more, Pic Info helped.

**Comment by angelo-fuchs** [comment]
Problem is somewhere here:
org/thoughtcrime/securesms/database/loaders/BucketedThreadMediaLoader.java:88

**Comment by angelo-fuchs** [comment]
Okay, now I have it figured out: 
"Today" means "Last 24 hours"
"Yesterday" is the 24 hours before that
"This week" means "In the last 7*24 hours until yesterday"
"This month" is the same for 30 days.

I have to think about this.

**Comment by r10s** [comment]
i would not change the wording, this is just fine. but we can define
- "today" as "today since midnight" 
- "yesterday" as "yesterday between 00:00 and 24:00"
and so on.

"this month" being (from today) 13. Jan to 13. Feb is a bit weird.
