### ISSUE TITLE
clean up: remove protobuf 

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#687]
I was stumbling over the protobuf folder. According to @angelo-fuchs protobuf is not used in delta chat and thus related files should be removed.

**Comment by angelo-fuchs** [comment]
I just grepped through the code and couldn't find anything for it. @cyBerta Could you make a PR with removing it?

**Comment by r10s** [comment]
fixed by https://github.com/deltachat/deltachat-android/pull/690
