### ISSUE TITLE
indicate audio message duration initially

### ISSUE THREAD

**Issue by violoncelloCH** [deltachat/deltachat-android#688]
If you receive a voice message, you want to know the duration of the audio. Currently deltachat shows 00:00 and starts counting upwards from there. I think it should show the whole duration initially and only after clicking play, it should be set to 00:00 and start counting...

Platform (android/blackberry/anbox): android
- Device: honor 8
- Delta Chat Version: 0.100.0
- Expected behavior: show full duration of audio message initially
- Actual behavior: 00:00 is shown; you don't know the length of the audio before playing it

**Comment by adbenitez** [comment]
I was annoyed by this and always forget to open the issue, +1
