### ISSUE TITLE
GIF images won't display

### ISSUE THREAD

**Issue by CompuRoot** [deltachat/deltachat-android#691]
Animated attached GIF files displayed as a big empty white box.

- Platform: android
- Devices: Samsung, Honor 
- Delta Chat Version: 0.20 (official from f-droid)
- Expected behavior: Either show an image of show it as attachment as it works for PDF files
- Actual behavior: White box instead of picture
- Steps to reproduce the problem: Ask some1 to send to DeltaChat any animated GIF file 

On a long press to empty white box that shows instead of picture and choosing from menu "Open" in gallery shows GIF image without any problem on any devices we have tried.

**Comment by r10s** [comment]
@CompuRoot thanks for the report. is this be behavior still true for 0.100.0? (there should be an update on f-droid)

**Comment by webratte** [comment]
For me it works fine.
Animated gifs will shown correctly.

Huawei nova
Androd 7
DeltaChat 0.100.0

**Comment by r10s** [comment]
for me it also works, closing this for now. we can re-open when the problem still exists.
