### ISSUE TITLE
prepare for gplay

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#697]
- [x] create an organisational-gplay-account

- [x] check, if we want to go to the gplay-beta-channel first

- [x] create and use a release-key to sign; this one should also be used to sign the apk-downloads on github (which can also get the gplay applicationId then), cmp #651

- [x] modify applicationId to `chat.delta` or so. take care that for f-droid, `com.b44t.messenger` stays unchanged to avoid a bad user experience there

- [x] upload apk

- [x] prepare some text + screenshots

**Comment by webratte** [comment]
> Too many apps already whre the applicationID has no obvious connection to the app's name.

IMHO 90% of the users not interested in the AppID.

So the devs should check how much is to do, to change the ID and is it really needed.

**Comment by r10s** [comment]
yip, after some discussions these day, we'll  go to beta channel first.

**Comment by webratte** [comment]
It seems you have no courage to create a Google play account :-P

Believe me, that is not that complicated.
I did it already for my own (boring) App ;-)

Or don't you find a person in authority?

**Comment by r10s** [comment]
@webratte thanks for encouragements! in fact me personally has not much experiences with gplay :)

however, currently, the issues we're targeting are the changes wrt "tiny" things needed for the oreo-target, see https://github.com/orgs/deltachat/projects/8 - eg. the bit annoying forced-usage of NotificationChannels.

**Comment by webratte** [comment]
@r10s I know there a some other open issues. I follow your work on GitHub.

But still I think you should not wait too long for first (Beta) release in Google play store.

It's absolutely important for making DeltaChat famous.

I belive currently it's a messenger for geeks and nerds ;-)
Only a soonish release in Google play store can change it.

By my estimation of your division of work this could be done by @hpk42

Isn't it?

**Comment by hpk42** [comment]
On Sun, Feb 10, 2019 at 07:11 -0800, webratte wrote:
> @r10s I know there a some other open issues. I follow your work on GitHub.
> 
> But still I think you should not wait too long for first (Beta) release in Google play store.
> 
> It's absolutely important for making DeltaChat famous.
> 
> I belive currently it's a messenger for geeks and nerds ;-)
> Only a soonish release in Google play store can change it.
> 
> By my estimation of your division of work this could be done by @hpk42

yes and no.  i can not help too much currently. 
But i think google beta could happen the coming week ;)

**Comment by webratte** [comment]
Hi @all 
to motivate you I have created a initial draft forgerman wikipedia.
I think I will offer it to wikipedia after V.1.0 and 1000 downloads in play store.
So I believe we will have enough relevance and wikipedia will accept my article.

In the meantime everybody can help to refine and correct this aricle.

Please take a look to my draft:
https://de.wikipedia.org/wiki/Benutzer:Webratte/Artikelentwurf

**Comment by nath5394** [comment]
I do have a gplay dev account, if this could help you to release a beta and/or stable apk 😉

**Comment by hpk42** [comment]
On Mon, Feb 11, 2019 at 00:32 -0800, nath5394 wrote:
> I do have a gplay dev account, if this could help you to release a beta and/or stable apk 😉 

We'll only give out signing rights to people we personally know and
who have contributed already. So there is a possible future in which 
you could sign deltachat releases ;)

**Comment by r10s** [comment]
we're in:

installation, requires the browser to be logged into a google account:
https://play.google.com/apps/testing/chat.delta

common information:
https://play.google.com/store/apps/details?id=chat.delta
