### ISSUE TITLE
No feedback when blocking contact

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#699]
When user go to a contact's profile and select to block the contact, the menu option should change to "Unblock contact" this will provide feedback to the user, also instead of keep offering to block a contact that is already blocked, offering to unblock is more useful, imho.

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.100
- Steps to reproduce the problem: Go to a contact is profile, block him, the profile still shows "Block contact", you may be a bit confused by this.

**Comment by florianhaar** [comment]
I work on this today

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/704
