### ISSUE TITLE
English text on contact requests (should be German)

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android#714]
On Version 0.100 (fresh install from fDroid).

When I set up my Account (login successful) before I started any chat I opened the "Contact Requests"
On the German Installation this message appears below "Kontaktanfragen" (but still in the header)

"Press message to start chatting"

**Comment by r10s** [comment]
this is already translated, https://github.com/deltachat/deltachat-android/commit/cd5aa0b9c16eb538a9a2bf4a4ebad937ea1f15d3#diff-5a07a86be0448f1f8a28975afa42b8a2L141, however, the translation could be polished :)

in general, there are tons of missing translation strings, i would suggest not to open issues for that here (unless the strings are not translatable by the code)

**Comment by angelo-fuchs** [comment]
@r10s Okay, I was not in the code atm and I don't know if that text stays when I get the first entries there. So I made this issue more to be sure that I don't forget it :) Cool if its already done.

**Comment by r10s** [comment]
@angelo-fuchs sure, np :)
also polished german a bit and unified "du" -> "sie", however, avoiding these cases where possible.
