### ISSUE TITLE
use NotificationChannels as they are supposed to?

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#715]
the Notification.Builder methods setSound(), setLights(), setPriority(), setVibrate(), setDefaults(), setPriority(), ... are no longer working in android 8 (aka oreo aka API level 26).

instead there are corresponding NotificationChannel methods. however, the NotificationChannel cannot be changed or deleted programmatically but should be changed by the system once created. this can be done using the intent ACTION_CHANNEL_NOTIFICATION_SETTINGS, which, however, does not support changing the led color or patterns.

currently, [we hack around this by using new channel-ids](https://github.com/deltachat/deltachat-android/pull/711) when the settings are changed in the corresponding delta chat dialog; this is seems to be also the thing eg. signal does. (the hack currently does not include different sounds in different chats, btw)

however, maybe we should go more the android-way and create a default-notification-channel and separate chat-notification-channels as needed and direct the user to the system setting to tweak sounds or whatever.
(for systems <oreo we should provide a fallback-settings dialog then).

the disadvantage would be that the user can no longer change eg. the led color and probably also some other settings, depending on the system (but we can still set a default led color :).

sources:
https://developer.android.com/reference/android/app/Notification.Builder
https://developer.android.com/reference/android/app/NotificationChannel

**Comment by Ji-eF** [comment]
AFAICT, LED color can be changed on Android 9

**Comment by r10s** [comment]
> LED color can be changed on Android 9

in the system settings? that would be cool. at least on my nexus4 with lineage android 8.1 this option is missing.

**Comment by angelo-fuchs** [comment]
I'm personally all for using the "Standart"-compliant way, but don't have a phone that has a sufficiently high droid.
