### ISSUE TITLE
mailto:-links without address should work as "share"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#716]
while mailto-links with e-mail addresses work line a charme since https://github.com/deltachat/deltachat-android/issues/473, mailto:-links without e-mail addresses (sth. as `mailto:?subject=bla&body=blub`, used eg. on golem.de) currently do not work as expected.

these links open the contact list; once a contact is selected, however, the proposed text is gone.

i think these links should work in the same way as sharing: offering the chatlist and adding the text as draft. the user can click "send" or modify the text before sending then.

**Comment by angelo-fuchs** [comment]
[Testlink](mailto:?subject=foo&body=bar) for easier testing.

**Comment by Boehrsi** [comment]
Will have a look :).

**Comment by r10s** [comment]
great :)

**Comment by Boehrsi** [comment]
Should be fixed by https://github.com/deltachat/deltachat-android/pull/724

**Comment by r10s** [comment]
should be fixed by https://github.com/deltachat/deltachat-android/pull/724
