### ISSUE TITLE
GlideApp...getI() must not be called from main thread

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#720]
got two crashes wrt notifications on nexus4/android 8.1/oreo

the crashes were assertions from the Glide module; saying "You must call this method on a background thread":
https://gist.githubusercontent.com/r10s/28ef216fad00e1e1fd467cac71daa804/raw/84bc8797f71e3aeda23083197302ff157b6a3378/gistfile1.txt

tracing back the log, it's probably [SingleRecipientNotificationBuilder.setThread()](https://github.com/deltachat/deltachat-android/blob/master/src/org/thoughtcrime/securesms/notifications/SingleRecipientNotificationBuilder.java#L75) which calls GlideApp...get(), probably from the main thread and not from a background thread.

wondering why the app does not crash all the time.

**Comment by r10s** [comment]
another log with the same error: https://gist.githubusercontent.com/r10s/7ad00b262298e789a5d4721740387d25/raw/dca6c0695109b3d178ef1b9a7a6e84c6aab9f792/gistfile1.txt

**Comment by r10s** [comment]
related: https://stackoverflow.com/questions/38670507/glide-error-java-lang-illegalargumentexception-you-must-call-this-method-on-a#38702691

**Comment by angelo-fuchs** [comment]
I'll look into this.

**Comment by r10s** [comment]
i think MessageNotifier.updateVisibleThread() should be run from a thread or call updateNotifications() in a thread.
