### ISSUE TITLE
if not at the end of the chat, do not scroll down on new messages

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#731]
When I am on a group and people are actively posting, it is really hard to read at my peace while this new post come out, since the view is scrolled.
IMO if the scroll frame is not at the end of the chat, the frame should not be scrolled, since this makes messages really hard to read if they are constantly moving, it is stressing for users.

- Platform (android/blackberry/anbox): Android
- Delta Chat Version: 0.101.1

**Comment by r10s** [comment]
i think this is related to https://github.com/deltachat/deltachat-android/issues/447 (
add "new message marker") - if the scroll position is _not_ the end and new messages arrive, the marker should be added just before the first new message (same as if eg. the screen is off in between or another app was active)

**Comment by r10s** [comment]
finally, this is fixed, thanks @adbenitez for reporting and  @cyBerta for helping fixing that :)
