### ISSUE TITLE
Group with 1 member not shown as group

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#732]
Seems like groups with 1 member aren't shown as group in the chats list, they still are groups, it is just that their 'group icon indicator' isn't shown in the chat list.

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.101.1
- Screenshot:
![group 1 mem](https://user-images.githubusercontent.com/24558636/53107997-3d886100-3504-11e9-8081-29b9caf5b841.png)

**Comment by Boehrsi** [comment]
Will have a look right now.

**Comment by r10s** [comment]
great, thanks for fixing :)
