### ISSUE TITLE
open vCard in contact app

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#738]
- Platform (android/blackberry/anbox): Android
- Device: Huawei nova
- Delta Chat Version: 0.101.1
- Expected behavior: open a attached vCard should always offer "open with the system contact app" to import this vCard.
- Actual behavior: the "system contact app" will only offered if the vCard include only a mail address. If there are more informations e.g. phone number or address included in this vCard the option "open with system contact app (address book) will not offered.
- Steps to reproduce the problem: receive a vCard with only a mail address inside and open it. It works as expected.

Now receive a vCard with a postal address inside. I don't work as expected (on my phone).

See also the screenshots:

![img_20190223_053855](https://user-images.githubusercontent.com/6864851/53281734-eebe0f80-372d-11e9-884e-931e23bc6748.png)
![img_20190223_054006](https://user-images.githubusercontent.com/6864851/53281735-fda4c200-372d-11e9-8fdb-2ab7ad88a70c.png)

**Comment by FH-Inway** [comment]
Could this be related to #740 ?

**Comment by Boehrsi** [comment]
I will have a look why this is happening.
