### ISSUE TITLE
Check how unrecognized attachments are handled

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#740]
see https://support.delta.chat/t/unrecognized-attachments/279

iirc some older version (0.9somwhat) of  Delta Chat sent wrong mimetypes, might be related to that.

**Comment by chklump** [comment]
I think, the #741 at least fixes the first part of the referenced forum thread.

**Comment by r10s** [comment]
that was quick :)

**Comment by adbenitez** [comment]
check https://support.delta.chat/t/unrecognized-attachments/279/5?u=adbenitez

**Comment by r10s** [comment]
i think this very generic issue can be closed, in general, attachments work.
