### ISSUE TITLE
log should be reachable during onboarding

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#744]
i would suggest to add the "view log" button (as a blue link) to the end of the "advanced" section.

**Comment by adbenitez** [comment]
this would be useful since server registration is a common place for errors, I had needed access to this log in the registration view more than once.

**Comment by florianhaar** [comment]
I will tackle this today

**Comment by r10s** [comment]
@florianhaar thanks again, this can be closed by https://github.com/deltachat/deltachat-android/pull/758 now :)
