### ISSUE TITLE
received .webp image are not shown

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#748]
Some friend started sending me some stickers images with extension .webp, the received images are not shown as images in Delta Chat but as attachments, but if I take one of those images and send it, they are shown as normal images (with preview)

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.101.1

**Comment by Boehrsi** [comment]
I will have a look why this behaves wrong.

**Comment by Boehrsi** [comment]
I tried to reproduce that and on both devices (Android 8.0 and 4.4) I wasn't able to reproduce that problem. Does that still happen in version 0.200.0?

**Comment by adbenitez** [comment]
just sent one image to a friend and he sent back an screenshot with the image shown as attachment, while I sent it and from the sender side looks normal, both use Delta Chat 0.200.0
if you wanna test, send a webp to me: adbenitez@nauta.cu

**Comment by adbenitez** [comment]
preferible something small like the image I used for the test: https://github.com/chai2010/webp/blob/master/testdata/2_webp_a.webp

**Comment by Boehrsi** [comment]
Okay, thanks for the information. I will continue testing with your test images on Friday. :+1:

**Comment by Boehrsi** [comment]
I'm now able to reproduce the behavior and I'm on it to fix it.
