### ISSUE TITLE
Can't login when username contains an @

### ISSUE THREAD

**Issue by hendi** [deltachat/deltachat-android#750]
- Platform (android/blackberry/anbox): Android
- Delta Chat Version: v0.101.1

My email address is "info@example.com", and I enter the IMAP and SMTP credentials manually. I have to logiin with my full email address and entered that as IMAP login. But I get an error message saying that "info" couldn't login.

This is correct, since I must login as "info@example.com", not as "info".

It looks like the app only sends the part in front of the @ sign to the login server.

**Comment by r10s** [comment]
hi @hendi only if `info@example.com` does not work, the domain part is stripped and the part before the `@` is tried.

so, maybe something else is wrong with the server settings?

**Comment by hendi** [comment]
Thanks, I used the wrong password.

Maybe put the information in the dialog in this case? E.g.:

"Could login with info@example.com (maybe wrong password?), trying login with info instead... that failed as well."

**Comment by r10s** [comment]
yip, we should check if we can be more clearer here. i've opened an issue for that, see https://github.com/deltachat/deltachat-core/issues/594, closing this one.
