### ISSUE TITLE
Unused "New chat" option on groups's profile

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#754]
When you go to a groups is profile view there are an option called "New chat", for a contact this bring you to they active 1x1 chat or create it if it doesn't exist. but for groups this option seems not to have much sense, currently the option does nothing on click/tap for groups, so even if it was there intentionally, it doesn't work.

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.101.1
- Screenshots:

![screenshot_20190223-005740](https://user-images.githubusercontent.com/24558636/53753291-e036cd00-3e7e-11e9-9d9b-74f063bfcf41.png)

**Comment by Boehrsi** [comment]
Makes sense, I would say we just hide it for groups. Also fine for you @r10s?

**Comment by r10s** [comment]
tested https://github.com/deltachat/deltachat-android/pull/766 and it works as expected. thanks - also for the again excellent report :)
