### ISSUE TITLE
QR verification: No "Verified" sign shown for existing contact

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#757]
- Platform (android/blackberry/anbox):
- Device:
- Delta Chat Version:
- Expected behavior: Show a "Verified" sign
- Actual behavior: No "Verified" sign (checkmark on blue background) is shown in the Chats list or in the 1:1 chat activity, just in the contacts list (when pressing the Floating Action Button)
- Steps to reproduce the problem: Scan an existing contact's QR code

**Comment by r10s** [comment]
1:1 chats are no verified chats as also messages with other or no keys show up here. therefore they do not have a verification mark.

however, you can create a verified group with a single verified member - which will have the verification mark then.

**Comment by r10s** [comment]
discussion can continue in the forum, for now, here is no actionable item.
