### ISSUE TITLE
possiblity to clear folder (delete all messages)

### ISSUE THREAD

**Issue by zoff99** [deltachat/deltachat-android#76]
now it's hard to select 200 messages, one at a time and delete them.
can you add and option "delete all messages" or "expunge folder" or something similar please

**Comment by zoff99** [comment]
but i can not delete all the messages in the standard "Mailbox"

**Comment by r10s** [comment]
As mentioned in #144 I can imaging a "Select all messages" options and let the user do what he wants to do with the selection - including deletion. This would diminish the problem about _which_ messages are deleted when deleting a chat - only Delta-Chat-messages, Delta-and-normal-messages etc.

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
