### ISSUE TITLE
sharing links crashes

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#762]
to reproduce: share a link eg. from Firefox Focus to Delta Chat.

this bug was introduced by merging https://github.com/deltachat/deltachat-android/pull/759 and is not yet released.

**Comment by webratte** [comment]
Is this already released in V.304.0?

For me sharing links dosn't work.

**Comment by r10s** [comment]
the mentioned change is available in the most recent versions.

does it crash for you?

the "sharing of links" as such may be very different from browser to browser - up to not working at all. however, it shall not crash :)

apart from that, the whole sharing & forwarding is [currently refactored at all](https://github.com/deltachat/deltachat-android/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AfwdAndShare+), so it is probably not worth researching much more here currently

**Comment by webratte** [comment]
OK, thank you for your reply.

sharing from browsers works fine.
It crashed by sharing from this app:

https://play.google.com/store/apps/details?id=de.badischezeitung.smart

I will wait until your mentioned issues are closed and report again.

OK?

**Comment by r10s** [comment]
> OK?

yip, that would be great. we can try the badische zeitung again, then.

**Comment by webratte** [comment]
Hi,
I just tested it with my linked App and DC version 0.500.0

It still doesn't work.
There are also other News Apps who using (probably) the same software as Badische Zeitung.
So I think this issue also concerns other Apps.

Maybe this issue should be reopened

**Comment by r10s** [comment]
i'd suggest to open a new, concrete issue.
this one was very generic and is fixed, indeed.

**Comment by webratte** [comment]
OK, I will do that.
