### ISSUE TITLE
Forwarding message with [...] sections doesn't share the content but the string "[..]"

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#768]
When forwarding in Delta Chat a message like:
```
El 2018-12-20 13:04, adb escribió:
> Hi!!!! 👋

```

The original message's content isn't forwarded, instead it is sent the text that is shown in Delta Chat is message bubble:
```
---------- Forwarded message ----------
From: Delta Chat

El 2018-12-20 13:04, adb escribió: [...]

-- 
Enviado con mi aplicación de mensajería Delta Chat: https://delta.chat

```

- Platform (android/blackberry/anbox): Android
- Device: BLU
- Delta Chat Version: 0.200.0
- Expected behavior: the original content of the message is delivered, including lines starting with '>'
- Actual behavior:   Delta Chat sends the literal string "[...]" instead of the original content.
- Steps to reproduce the problem: try to fordward a message with a "[...]" section, ex. a message that was replied from a classic MUA. or that contains lines starting with '>'

**Comment by adbenitez** [comment]
not sure if this is handled by Android or by Core??

**Comment by r10s** [comment]
it is handled in the core and it affects only non-delta-to-delta-communication

however, i think this is okay-ish as it is now - forwarding things that are not on the screen "in the bubble" is somewhat unexpected or would at least raise different, maybe larger problems. imagine users forwarding things they've not even seen on their own. i would not go to this direction.

however, maybe the truncating as such can be improved.

**Comment by webratte** [comment]
What about instead the [...] show a text like:
 "There is a hidden content. Longpress ->info to show the hidden text".

**Comment by adbenitez** [comment]
if this is the intended behavior, please fill free to close (I am offline)

**Comment by adbenitez** [comment]
webratte or just "show more" but well I guest that will suit better a forum feature request

**Comment by r10s** [comment]
yip, it's the intended behavior, this should be shifted to the forum.
