### ISSUE TITLE
Questions (bugs?) regarding location streaming

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-android#769]
I installed the .apk @r10s provided. If I install it I see the new "On-demand location streaming" setting. I see the map icon in chats. But even with enabled location streaming and switching between different users I see no marker on the map. I also don't see an option to close the map. I have to go to the home screen (with hardware button) and then can switch to deltachat again.

When I chat from desktop with an user on android with enabled location streaming no location data is send to the desktop (I'm on the branch with the location stream enabled node bindings of course) or at least I don't see any in the sqlite db.

But maybe I just don't understand how this is suppose to work. What does "on demand" mean and how can I "demand" the location streaming?
Is the feature described somewhere?

**Comment by r10s** [comment]
> Is the feature described somewhere?

not yet. it's not even alpha :) some hints:

- you see only the location of group members who share their own location
- to share ones location, click the "attach button" (the paper clip right of the message field) and select location
- currently, locations are collected and the last location is sent together with normal messages. this location is shown on the map (this is currently about to be improve in the core).

from the code view, all this looks like the following:

- a click on "share my location" in a chat calls `dc_send_locations_to_chat(chat_id)`
- after that, android pushes the gps location on changes using `dc_set_location(latitude, longitude)`  - this function returns `true` as long as more locations are "needed".

the core will collect locations and send them out the the chats as needed.

- to render the map, for each group member `dc_get_locations(chat_id, contact_id)` can be called to get a track

**Comment by cyBerta** [comment]
@nicodh is it ok, to close this question? The last days location streaming has been improved and we talked about this feature in person.

**Comment by nicodh** [comment]
yes
