### ISSUE TITLE
yandex.ru - manual settings 

### ISSUE THREAD

**Issue by guland2000** [deltachat/deltachat-android#77]
yandex.ru - manual settings,
So i am trying to set my mail from yandex.ru manually and it is shown me Error (see picture)
Basic settings for i**map: 
imap.yandex.ru
 SSL
 993**
for **smtp:
smtp.yandex.ru
SSL
465**
Login i used like just _name_ and like **name@yandex.ru** (with part of _@yandex.ru_ sometimes it is required for some services)
![s70419-164655](https://cloud.githubusercontent.com/assets/10272327/25184415/a54a8972-251a-11e7-9efb-8b72ffec6316.jpg)
![s70419-163743](https://cloud.githubusercontent.com/assets/10272327/25184407/a0739240-251a-11e7-8cb6-d0829932b7fc.jpg)
![Uploading S70419-164655.jpg…]()
![s70419-165226](https://cloud.githubusercontent.com/assets/10272327/25184423/a98bb362-251a-11e7-87be-c7d5b3481178.jpg)

**Comment by guland2000** [comment]
Auto settings does not accepted.
Maybe i do something wrong?!

**Comment by kskarthik** [comment]
Tried `STARTSSL` option ? I too had similar issue when login with https:disroot.org mail 

 `STARTSSL` worked for me

**Comment by guland2000** [comment]
Error
![s70420-111913](https://cloud.githubusercontent.com/assets/10272327/25224829/465358e6-25c8-11e7-9c96-615385ce2f26.jpg)

**Comment by kskarthik** [comment]
Problem fixed yet?

**Comment by guland2000** [comment]
Not yet

**Comment by r10s** [comment]
Hm, I've tried yandex.com some weeks ago and everything was just fine using SSL, see https://github.com/r10s/deltachat-android/issues/52 , I re-tried it today, and _sending_ fails. However, _receiving_ is fine. Can you confirm this?

(I've been using a yandex.com but yandex.ru address)

**Comment by r10s** [comment]
Correction: Mails from yandex.com are send and do arrive - however, for whatever reason, they are delayed sometimes. But, all in all, they seem to work someway.

I've not tested yandex.ru.

**Comment by blelop** [comment]
When you obscure different parts of a word like lycoris it is trivial to reassemble the word. ;)

**Comment by r10s** [comment]
AFAIK, yandex works without any problems now.
