### ISSUE TITLE
self recorded voice-messages cannot be replayed

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#772]
Recently replaced v0.15.0 of DC at a friend by v0.200.0.

Steps done:
- export backup
- delete v0.15.0
- install v0.200.0 from Google Play
- import backup 
- change email address to new one

after that tried voice-message recording (v0.15.0 worked fine)

- Delta Chat Version: v0.200.0 Google Play
record a voice-message and send it.

- Expected behavior:
If pushing on it should be replayed again.

- Actual behavior:
voice-message is not played

**Comment by r10s** [comment]
the format of the voice messages has changed from 0.90 to 0.100, not sure about 0.15, however.
i do not think it is worth to put much effort into this, esp. as the messages as such are not gone but are on the server and should be playable also on android from delta chat when an appropriate player is installed.

**Comment by csb0730** [comment]
Ok to close this now.

This is not a general issue and new recorded messages are working :-)



Am 18.04.19 um 02:31 schrieb björn petersen:
