### ISSUE TITLE
CI apk builds 

### ISSUE THREAD

**Issue by stmllr** [deltachat/deltachat-android#773]
To improve testing, we could build apk development snapshots using CI services, e.g. travis, circleci, ...

**Comment by adbenitez** [comment]
I have been dreaming with this for a while +1
this will be really useful

**Comment by hpk42** [comment]
Are you up for helping with this @stmllr ? 

I just created  https://github.com/deltachat/deltachat-core/pull/639  btw -- commits/reviews welcome ;)

**Comment by r10s** [comment]
as the issue tracker should show only things actually being working on i close this for now.

**Comment by link2xt** [comment]
Moving this to "Resurrection completed", as there are nightlies now: https://download.delta.chat/android/nightly/
