### ISSUE TITLE
Add automatic media download 

### ISSUE THREAD

**Issue by abasifreke50** [deltachat/deltachat-android#779]
I have used the Delta chat application for quite some time now, and I'll love to make a suggestion.

Going through the Delta application, there's no feature called the automatic media download. I believe it will be good to have this feature on the delta chat application.

What is automatic media download  feature ?

Well I thought of this feature today while conversing with my friend tobi. We were sharing pictures which we took in an event yesterday so it struck me that there is no feature on the delta chat which provides control over the media files shared within the platform.

I'm suggesting that automatic media download feature should be included, and when it is done, it should provide options to control how media files are downloaded when share.

The developers should make available an option to choose between WiFi, cellular and never when downloading a media file. Thank you

**Comment by hpk42** [comment]
Hello @abasifreke50 -- there are some considerations on how to organize media storage between people in a chat group.  Not sure it's exactly what you are asking for. In any case please rather discuss on the forum (https://support.delta.chat).  With this github issue tracker here we track concrete development activities or bugs, but not high level features.
