### ISSUE TITLE
Random? invisible notifications

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#784]
I had experimented like 3 times for now, a random invisible notification from Delta Chat, the notification is like shown but the actual notification dialog is invisible, to show this more graphically I had bring this screenshots with me. My guess is that this has something to do with the new way to do this with "channels".

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Screenshots:

### When the message arrives the notification is issued with all system effects but the actual notification is not there:
![notif-1](https://user-images.githubusercontent.com/24558636/54957941-8cbe1900-4f2a-11e9-9c1a-ea7162dc743d.png)

### When the notification effect ends, and the notification is "hidden" , there are no icon in the top bar:
![Screenshot_20190316-192821](https://user-images.githubusercontent.com/24558636/54958133-27b6f300-4f2b-11e9-8fa6-2caf7ad2548d.png)

### Finally if I check the notifications "dock" the notification is there!
![notif-3](https://user-images.githubusercontent.com/24558636/54957950-90ea3680-4f2a-11e9-8464-2696a03f87e1.png)

**Comment by adbenitez** [comment]
this had not happened more in recent versions, seems to be magically solved ;)
closing for now

**Comment by r10s** [comment]
cool ;) and: thanks for re-checking this!
