### ISSUE TITLE
Fordwarding a message repeats date tag

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#785]
When I forward a message the date tag is repeated, look at the screenshot for a more visual feedback.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Screenshots:
![fordwarding](https://user-images.githubusercontent.com/24558636/54959766-829f1900-4f30-11e9-96b5-26da12384330.png)

**Comment by r10s** [comment]
might be related to https://github.com/deltachat/deltachat-android/issues/419

i also think, the share/forward list is not updated after sharing/forwarding. this definitely needs some more love :)

**Comment by r10s** [comment]
i assume this is also fixed by #895? please re-open if not :)
