### ISSUE TITLE
Notification isn't removed until leaving chat

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#786]
When I receive a message, if I tap in the notification to go to the chat, or if I manually open the chat, the notification isn't dismissed, it stays there until I go out of the chat, to the chats list. 

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0

**Comment by r10s** [comment]
isn't that a duplicate of #725?

**Comment by adbenitez** [comment]
yes, this is a duplicate, sorry didn't find that issue,
closed in favour of #725
