### ISSUE TITLE
Painting image with the pincel in the editor isn't working on some devices

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#787]
This bug report was made by a friend:

- Platform (android/blackberry/anbox): Android Oreo 8.1
- Device: Samsung Galaxy J7 Pop
- Delta Chat Version: 0.200.0
- Expected behavior: Select the brush and paint some lines
- Actual behavior: When trying to paint with the brush nothing is painted
- Steps to reproduce the problem: This don't happens in all devices
- Screenshots:
After trying to paint with several colours:
![deltachat-2019-03-16-161025](https://user-images.githubusercontent.com/24558636/54960789-82a11800-4f34-11e9-8c1d-e294e42f6f5e.jpg)

**Comment by r10s** [comment]
see also https://support.delta.chat/t/editing-not-working/397

**Comment by r10s** [comment]
can someone with the error tell if this is working using signal on the same device? (we're using basically the same activities as signla for painging on images)

**Comment by cyBerta** [comment]
relates to #664 and PR #987. Maybe we can tackle this issue after merging #987 .

**Comment by cyBerta** [comment]
@adbenitez can you / your friend check if that issue is still valid in the next release including the new cropping feature and generally updated source code for image editing?

**Comment by adbenitez** [comment]
hi @cyBerta I can't reproduce, but I will ask him to check this

**Comment by r10s** [comment]
in the forum, this issues is reported to being solved - https://support.delta.chat/t/editing-not-working/397/16 :)

**Comment by r10s** [comment]
thanks everyone for helping on this tricky bug :)
