### ISSUE TITLE
how to turn off oauth or whatever

### ISSUE THREAD

**Issue by nutpantz** [deltachat/deltachat-android#789]
The newest android update has stopped dela chat from working.
Everything worked fine before, now all I get is an error from the Google server.. What do I have to turn off so it works just as before with just a username and password? And no dont point me to info on setting up Google for oath or any 2fa junk.

**Comment by r10s** [comment]
oauth2 is not used automatically for already configured accounts.

so, you can hit "cancel" when being asked if you want to use oauth2 and enter the normal credentials.

no actionable item, so this is closed for now. discussion on that can be continued at https://support.delta.chat/

**Comment by nutpantz** [comment]
It must be used automatically because I can no longer connect to my account with delta chat

**Comment by r10s** [comment]
can you please check if auth2 is really enabled at "settings / my profile (click on your name) / password and account settings / advanced / authorisation method" - if so, you can disable it there and use the normal login.

**Comment by nutpantz** [comment]
Authorisation method is either "automatic" or "oath2".  There is no off.
I'm going to have to blow this thing off and start fresh..  
How can there be no "off"?

**Comment by r10s** [comment]
as there must always be an authorisation, "off" does not really makes sense.
automatic is just fine :)

**Comment by nutpantz** [comment]
Well it can't be just fine, because I can't log in anymore after using delta chat for over a year with this account. If I didn't have my keys backed up into pgpkeyring and k9mail I would have no access to my account and everyone I talk to on delta chat.

**Comment by r10s** [comment]
fine in the sense that the app will ask whether to use oauth2 or not.

**Comment by nutpantz** [comment]
It's not asking, and I can't get in... So either the setting does not work, or "automatic" does not work.
Either way.. I have to disagree with your use of the term "fine"
I'll disable delta chat and hope the next update fixes this issue.

**Comment by hpk42** [comment]
On Tue, Mar 26, 2019 at 16:25 +0000, nutpantz wrote:
> It's not asking, and I can't get in... So either the setting does not work, or "automatic" does not work.
> Either way.. I have to disagree with your use of the term "fine"
> I'll disable delta chat and hope the next update fixes this issue.

still i think that "automatic" does not make much sense here -- OAUTH2
is also kind of automatic.  Maybe bettter "oauth2" and "manual credentials"? 

Let's try to find a way so that @nutpantz can get access
to his account again. It's understandably very frustrating to have used it for
one year and then being shut off. 

@nutpantz: could you make a backup (under advanced settings),
then switch to "automatic" and change your e-mail to an intermediate
other e-mail address (even if it fails) and then change back to your current one,
and this time click "cancel" when asked to use simplified setup? 

somebody other ideas how to get back access to the account?

**Comment by nutpantz** [comment]
Its in automatic now. I've tried using a backup with the new version and I've tried down grading to the last version restoring backup and updating. I've switched from auto to oath and back not more a few times. All are no go. One of my chat buddies had the same problem but he was able to restore a backup up get back working again. I'm to frustrated with it right now up even look at it any more..
But thanks for the help. 
While I'm not a idiot, this needs a little more idiot proofing.

**Comment by r10s** [comment]
i've just tested creating a new gmail account with both, "oauth2" and "normal" (the latter requires to enable "less secure apps") - it worked for me.
so at least, it does not seems to be a general issue.

**Comment by nutpantz** [comment]
It's like I said, a buddy was able to get his to work after oath2 was on after updating, but I'm stuck for some reason.. With no way to force it off. If I have up I'll start fresh, but that is a massive pain.
I know the account works fine because k9mail still checks it and I can still read and write mail from k9mail. But k9 mail was my back up for delta chat after I pushed a lot of people to adopt delta chat. I love no servers and open standards for encrypted communications...
Hopeful my hassles will get things fixed for future users..

**Comment by hpk42** [comment]
On Tue, Mar 26, 2019 at 16:57 +0000, björn petersen wrote:
> i've just tested creating a new gmail account with both, "oauth2" and "normal" (the latter requires to enable "less secure apps") - it worked for me.
> so at least, it does not seems to be a general issue.

@r10s did you test going back from oauth2 to normal?

**Comment by r10s** [comment]
> @r10s did you test going back from oauth2 to normal?

just tested it now - works as expected. of course, one has to enter the correct account password in this case (when "less secure apps" are enabled - otherwise, if 2fa is enabled, the generated application password)

**Comment by adbenitez** [comment]
your issue seems to be a bug I had that a message is sending forever abd I was having this error, you must to find that message and delete it and restart the app, that worked for me
