### ISSUE TITLE
handle own avatar independently from local device's address book

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#792]
In the moment there is an inconsistent handling regarding avatar thumbnails.
- For groups it's handled independent from local address book. Simply choose a picture in group settings from galery and that's it.
- For single chats own avatar isn't to be changed in chat's settings. Only by defining a picture at devices address book lets you change avatar.

It should be possible to set an individual avatar for every single chat by DC independent from devices address book. Same as for group settings.

**Comment by r10s** [comment]
yip, this is a known issue, see https://github.com/deltachat/deltachat-core/issues/444.

in fact, the core already offers the needed api-functions ([dc_set_config("selfavatar")](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d) and [dc_get_profile_image()](https://c.delta.chat/classdc__contact__t.html#a2ebee8ac3729e4db85041eaf35bfce73)) and they are also already used by android correctly.

however, currently, this works only for the "Me"-chat as the core just does not send the changes out yet.

closing this issue as there is no actionable item for android; for the core see https://github.com/deltachat/deltachat-core/issues/444
