### ISSUE TITLE
file/photo can not be shared/forwarded to a new contact

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#795]
- Delta Chat Version: 0.200

Looking at a photo gallery app I wanted to share a picture with the person standing next to me.

Then I tap on "share" and select "Delta Chat", but it won't let me enter the new email address. 

There is no "entry bar" at the top, and no "new group" button, like on the normal "new chat" screen that allows selecting from the address book **and** creating a new address (group).

**Comment by r10s** [comment]
yip, in general, i would suggest to use the normal chatlist-activity for selecting the chat to share with. 

this way, we would get the search-function as well as the new-chat-function that would allow entering an email-address then.

**Comment by testbird** [comment]
Yes, the chatlist-activity may even be better than the "new chat". Then entering existing chats could still work as usual, opening the chat with the new message in the editor.

**Comment by r10s** [comment]
only using the "new chat" screen is no option as you cannot share to existing chats/groups from there. we had this in the very beginning and this was even more annoying :)

**Comment by csb0730** [comment]
Ok, #859 is covered with comment at May 28 from r10s.
So this issue will cover that too.

@r10s is this a difficult extension? I mean this is a function I need personally more often!

**Comment by r10s** [comment]
i'd also like to see this working, of course.

it's probably not that difficult, however, it is some work and it's all about prioritization :)

**Comment by testbird** [comment]
What are your planned prioritiies, actually?

Looking at the list of closed issues, now, months after the transition to the signal codebase, there is unfortunately an insignificant amount that actually fixes a basic problem filed by a user. (Considering that only maybe 2% provide feedback rather than just uninstall, such feedback is very valuable.) 

Because you closed a lot of issues during the transition without fixing, please make sure that more fundamental [usage-problems](https://support.delta.chat/t/wiki-use-cases-chat-rules-and-configuration-options/122) are taken care off, because none of them is open on github anymore. But these still prevent adoption and successful usage, and are thus more grave or urgent to fix than a limited flaw in a specific feature.

**Comment by r10s** [comment]
see https://github.com/deltachat/deltachat-android/issues/891
