### ISSUE TITLE
Location data needs to be "normalized"

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-android#797]
After having a field test with the location streaming enabled it turned out, that there are many points off my route. See attached screenshots. I think the data has to be "normalized" based on time and location gap.
Found this at stackoverflow: https://stackoverflow.com/questions/47991613/locationmanager-and-jumping-coordinates

I also attached a gps track made on the same trip, but with apemap. So both apps got the same location data, but apemap somehow ignored the outliers...

I'm not sure if that has to/could be done in core or in the app...

![Screenshot_20190329_084106_wmdev apps navBrowser](https://user-images.githubusercontent.com/1428457/55217311-83210380-51ff-11e9-91ee-2139c8f9c73b.jpg)
<img width="1100" alt="Bildschirmfoto 2019-03-29 um 08 39 46" src="https://user-images.githubusercontent.com/1428457/55217333-90d68900-51ff-11e9-8ee8-82fcd728c44e.png">

**Comment by r10s** [comment]
yip, this can probably be optimized. there is also [dc_array_get_accuracy()](https://c.delta.chat/classdc__array__t.html#a12804ce7eadf0f85f266da829f9ccc1b), maybe simply ignoring points which are too inaccurate already has a good impact.

however, while it is a nice feature to have, in general, maybe we should also not focus too much on the tracks. i think the most important things are the last positions and messages having positions.

**Comment by WinterB1860** [comment]
Tracks do at least provide the ability to troubleshoot accuracy for the general features.


I personally hope that once basic location sharing on messages becomes stable that the ability to record tracks isn't removed but enhanced to do similar functions as [OsmAnd Online GPS Tracker](https://osmand.net/blog/osmand-tracker-0-4-released) (OsmAnd Telegram location sharing)
But that sort of feature would specifically require tracks being recorded locally to the phone and saved/backed up.

**Comment by r10s** [comment]
i think this is mitigated by relying completely on the gps sensor, i've not seen weired graphs since we've disabled getting locations from wifi/mobile networks.

if this is still an issue, however, we should re-open it on core, i think normalisation would also be needed from desktop/ios.
