### ISSUE TITLE
delete from server

### ISSUE THREAD

**Issue by beatnickgr** [deltachat/deltachat-android#80]
Currently the incoming message appears both in DeltaChat and the normal email client (creating a flood in the inbox).
Please add an option to delete the incoming message from server.

**Comment by kskarthik** [comment]
When you delete chats on app, Related mails will also be removed from server

**Comment by kskarthik** [comment]
Which mail are you using? I found this issue on gmail so far...

**Comment by kskarthik** [comment]
BTW this issue is more or less related to https://github.com/r10s/deltachat-core

**Comment by beatnickgr** [comment]
You're speaking about mails being deleted from server when DELETED from app.
I want it when RECEIVED, so that I can still access the message from the app, without seeing it in my inbox.

**Comment by kskarthik** [comment]
Just like WA. Only client side msg storage. Nice idea.. But, the dev wants to sync msgs like telegram across all devices...

**Comment by kskarthik** [comment]
Again, This leads to a bug. Because all mails are received on deltachat including non-chat mails, this causes to clean up inbox totally.

**Comment by beatnickgr** [comment]
Only the mails DISPLaYED in deltachat should be deleted from server.
Telegram offers a "secret chat" which is only between 2 devices and no trace on server. But it's a different technology.

**Comment by zoharsnir** [comment]
Maybe the solution can be a user configurable option?

This is a show stopper for me. Sure it works for tech savvy people that can easily create mail filters to handle it. It doesn't work for most of the general non-tech population who never created a mail filter before or doesn't even know what it's used for. As I do want to chat with non-tech savvy people (without turning myself into their filter-and-email-related-helpdesk) this effectively rules this out for me.

**Comment by r10s** [comment]
I do not really get the point.

Especially for non-tech people it is very handy that all Delta Chat-related mails are moved automatically into the folder "Chats" (unless you're using gmail, but that's another issue). 

Why should they create a filter at all? And for what?

**Comment by beatnickgr** [comment]
Because i don't have a "chat" folder, so when i open my thunderbird 
these messages appear in my inbox.

I'd like to opt out from seeing chat messages in Thunderbird, seeing 
them in my Deltachat is enough for me.

**Comment by r10s** [comment]
> I'd like to opt out from seeing chat messages in Thunderbird, seeing them in my Deltachat is enough for me.

But this does not work properly without losing the ability to talk to non-Delta Chat MUAs. 
Eg. assume AliceUsingDeltaChat gets a message from BobUsingThunderbird. AliceUsingDeltaChat answers using Delta Chat and BobUsingThunderbird answers again.
If Alice later on goes to her Thunderbird, she would see only 2 messages in the conversation. This is bad.
You'll run into complicated cases that you cannot explain to the user when deleting messages. However, we did not find an solution for this.

However, we already _found_ a solution for _this_ issue, the "Chats"-folder.

_Another_ issue, is that the "Chats"-folder does not work for you. I think _this_ is the problem we should try to fix.

Which provider are you using? Have you tries to re-install Delta Chat? Can you reproduce the behaviour on other devices?

**Comment by beatnickgr** [comment]
I'm using https://mail.espiv.net/
Because of this issue I have uninstalled Delta Chat 2 months ago (after asking those 2 contacts to use other IM) and didn't try on other devices.

**Comment by r10s** [comment]
Does anyone else uses this provider or is willing to test it?

**Comment by zoharsnir** [comment]
> Delta Chat-related mails are moved automatically into the folder "Chats" (unless you're using gmail, but that's another issue).

I wasn't even aware this is the expected behavior and yes, I'm using gmail.
Is there a solution to the chat folder in gmail?

**Comment by r10s** [comment]
> Is there a solution to the chat folder in gmail?

Not yet, but we will have  look on this sooner or later. As a workaround, you can create a filter in Gmail that moves all subjects containing "Chat:" to another folder.

**Comment by r10s** [comment]
i think this issue can be closed, it is partly handled by #108 (fix Chats folder, avoid flooding the inbox) and by #22 (delete old messages).

also, automatically deleting messages just read from the INBOX would foreclose multi-client usage or would make it at least harder.
