### ISSUE TITLE
Add FAQ and search feature within the settings feature

### ISSUE THREAD

**Issue by abasifreke50** [deltachat/deltachat-android#803]
#### Proposal Description
Within my one year with Delta chat application, I have witnessed a lot of improvement in its features. I’d love to suggest two features which I believe will be a plus to the platform and also to its users.

* FAQ(Frequently asked questions) feature.
* Search feature.

If you've been using most applications developed in this era, you've seen the FAQ feature within its settings likewise the search feature.

I believe the Delta chat application deserves a FAQ feature due to the fact that its features are numerous, and this will offer a means to it understand.

#### FAQ feature
The FAQ feature is a feature that houses all the possible questions and answers that could be asked about a project. I know there's a help feature on the delta chat application, the problem I have with it is that it takes you to a website. The FAQ should be developed in a way that it is independent of the platform's website. It should be a standalone feature which could be accessible even with an internet connection. It should have all the possible questions and answers about the delta chat application.

#### Search feature
I know a search feature sounds trivial, but I believe it's a necessity on the delta chat application. The delta chat application has various features which could be hard to locate especially for the novices. Having the search feature within the settings feature will be an added advantage to its users.

The search should be developed in a way that it works hand-in-hand with the FAQ feature. When a user searches for a feature, the feature should be displayed alongside the FAQ associated with the searched feature. The search feature should have suggestions starting from the first alphabet typed by the user.

#### Benefits

It is without doubts that the delta chat application is surging for dominance, having the suggested features implemented on the platform will be a major breakthrough for the developers, its users and the platform itself.

In my belief, the FAQ feature will provide a means to access different questions and answers pertaining to a particular feature or features with or without an internet connection. 

The search feature will also be a blessing to the platform and its users. When the search feature is developed to display suggestions pertaining to each alphabet typed by the users, it will improve accessibility. When the search feature is developed to display the FAQ associated with the searched feature, it will be easier for a user to have a succinct understanding of the search feature through it already asked and answered questions.

Thank you.

**Comment by r10s** [comment]
hi  @abasifreke50 thank your for your post.

we've also thought about putting the faq's into the app so that it is accessible offline, however, imho the main issue with the faq's is currently not the medium but that the content is outdated and incomplete.
are you up helping in this issue?

a search function could also be handy, however, not sure if android can help on this point. the settings dialog is more or less standard, maybe there is a "make options searchable" flag ;)

apart from that, this issue tracker is not really for feature proposals.
therefore i would suggest to move this post to https://support.delta.chat/ and close it hre.

**Comment by r10s** [comment]
just noticed, it is already moved to https://support.delta.chat/t/add-faq-and-search-feature/342 :)
