### ISSUE TITLE
Forwarding image from image viewer doesn't work

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#805]
When I go to the "all media" view, to find an image and tap it, the Delta Chat's image viewer is shown, it has two buttons one to save the image and another to forward the image? or full message?(I expect the image only), if I select to forward the image I am driven to the chat I had selected to forward the image, but the forwarded message isn't shown and isn't sent.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: tap in any image in chat or in the "all media" view to get the dc is image viewer, try to forward the image.

**Comment by Boehrsi** [comment]
I will have a look why this behaves wrong. :+1:

**Comment by cyBerta** [comment]
For now the forwarding from the image viewer will forward the whole message. It was implemented like that in #818 and will stay like that after the refactoring.

**Comment by cyBerta** [comment]
PR #895
