### ISSUE TITLE
Swiping out element in chat list leave white space in dark mode

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#807]
Ok, maybe I am a bit extremist with this, but when you swipe out a chat form the chat list(to archive it) the empty space is not in dark mode, this is something that is only visible for some seconds so feel free to close this issue if you think it is trivial.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Screenshots:
![Screenshot_20190330-170100](https://user-images.githubusercontent.com/24558636/55349819-a3afbe80-5488-11e9-9f95-faff06cb2cf1.png)

**Comment by r10s** [comment]
and another great bug report :) i think when targeting this issue, on can also have a look at #439 and the other issues linked from there.

**Comment by r10s** [comment]
fixed by #811
