### ISSUE TITLE
Some contacts lists not readable in dark mode

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#808]
Seems like the font colour is not changed for the contact lists shown when sharing a contact, nor for the blocked contacts list.
related: #806 #807 #439

- Platform (android/blackberry/anbox): ANdorid 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Screenshots:
### Sharing a contact in dark mode:
![Screenshot_20190330-210234](https://user-images.githubusercontent.com/24558636/55353302-f9886480-5490-11e9-9a86-126bba910f70.png)
### Blocked contact list:
![Screenshot_20190331-141156](https://user-images.githubusercontent.com/24558636/55353495-6f8ccb80-5491-11e9-85b7-5d64032514d4.png)

**Comment by r10s** [comment]
thanks for reporting! i think when targeting this issue, on can also have a look at #439 and the other issues linked from there.

**Comment by r10s** [comment]
fixed by #811
