### ISSUE TITLE
[UX] Make easier to block a contact in Contact Requests view

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#809]
When an user taps in a message in Contact Requests view, they are offered to chat with that contact or to cancel/go-back to block the contact they must guess that the hard-to-tap little avatar of the contact is clickable and then in the contact profile view look for the block option, get another dialog, and finally block the contact. It would be nice if in the dialog that is shown when tapping the message an option to block is provided.

- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: tap a contact request in the Contact Requests view
- Screenshots:
I propose something like this:
![Screenshot_20190330-210612](https://user-images.githubusercontent.com/24558636/55354989-1161e780-5495-11e9-98ed-85ba03c34649.png)

**Comment by r10s** [comment]
@adbenitez thanks for the suggestion, in fact, this is missing and useful. and also the "start chat" dialogs are unified this way.

will be implemented by #993
