### ISSUE TITLE
Delete quote

### ISSUE THREAD

**Issue by beatnickgr** [deltachat/deltachat-android#81]
My own message appears in their reply. Example:

= = = = = = 
My previous message.
= = = = = = 
Their last message
At this date, my email said:
My previous message.
= = = = = = 

Solution could be, if my email is in one line, then delete this line and all lines after.

**Comment by kskarthik** [comment]
Can you attach any screenshot of this issue ?

**Comment by beatnickgr** [comment]
I won't upload private data here, but i've updated my first post, maybe it's clearer now?

**Comment by r10s** [comment]
> Solution could be, if my email is in one line, then delete this line and all lines after.

Wouldn't this delete the whole mail? :-)

However, in fact, Delta Chat does some things to abandon (hopefully) useless lines, eg. the following mails will be shortened to "Important text"

```
Important text

----- Original Message -----
blabla
```
or

```
Important text

abc@def.com wrote:
> bla bla bla
```

See https://github.com/r10s/deltachat-core/blob/master/src/mrsimplify.c#L274 for the code details.

Unfortunately, there is no 100% "mark" that can be used to recognize unimportant stuff. Delta Chat does its best, and, of course, the code is far away from being perfect. However, every change should be done with care - and based upon real-world example-mails (anonymized, if required).

**Comment by beatnickgr** [comment]
My own email abc@def.com is in the line between the "important stuff" and the "blabla" (usually with the timestamp).
So deleting this line and all the following could be a solution.

**Comment by r10s** [comment]
Well as, shown in the second example, this happens under some circumstances. Without real examples, it's hard to say something. But everyone is welcome to create a pull request :-)
