### ISSUE TITLE
Archived chats entry shown in list to forward a message

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#810]
If user select to forward a message they get the chat list to select one of them, at the end of the list the archived chat option is shown, user expectation is that if the option is there it will allow to forward a message to archived chats, but when tapping the option nothing happens, if this option is useless because it isn't allowed to forward a message to an archived chat I recommend to hide it here to avoid confusing the user.

- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: select a message and tap in the forward button, go to the end of the list.
- Screenshots:
![Screenshot_20190327-223708](https://user-images.githubusercontent.com/24558636/55355353-08bde100-5496-11e9-83e8-55bae69771ad.png)

**Comment by hpk42** [comment]
I'd like to throw in that @xeniax's UX testing report https://delta.chat/en/2019-03-30-uxreport
on page 19 says "Most users do not need or do not understand the need
for archiving conversations. It may makes sense to drop this at some
point or at least not invest much work in it".  Personally, using lots 
of chats (>200) i virtually never archive so happen to concur with the finding.

**Comment by adbenitez** [comment]
I found the archiving feature fine, as you see I use it a lot, if users go mad because a not-the-big-deal "Invite friend" feature got removed, I don't wanna see what they will say if this is removed ;)

**Comment by adbenitez** [comment]
Anyway I understand what you mean, this is trivial, I have done my part here, feel free to close :)

**Comment by r10s** [comment]
i think when targeting https://github.com/deltachat/deltachat-android/issues/891 this should be fixed as well. however, leaving this open for now.

**Comment by cyBerta** [comment]
fixed with d737e6f7f8c34a03d40f6f0b31bd9852171bba25

**Comment by cyBerta** [comment]
PR  #895
