### ISSUE TITLE
Log view background not changed in dark mode

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#812]
In dark mode if user go to the log view, they can't see the log text, the font colour is changed to white, but the background isn't changed to black, so the text is the same colour as the background.
Related:  #806 #807 #439 #808 

- Platform (android/blackberry/anbox): Android 6.0
- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: set theme to dark, go to settings/advanced/View log
- Screenshots:
![Screenshot_20190401-215736](https://user-images.githubusercontent.com/24558636/55404782-abbe3b80-5526-11e9-9dad-37c543898199.png)

**Comment by adbenitez** [comment]
closing this just checked it was solved here #811

**Comment by r10s** [comment]
great, in fact, i'd like to make the dark-mode really usable in the next version :)
