### ISSUE TITLE
Make it possible for users to search through messages using the calendar tool

### ISSUE THREAD

**Issue by abasifreke50** [deltachat/deltachat-android#815]
Today I was wondering how I could help improve the delta chat application and I came up with something.

After using the delta chat for over 6 months, I have noticed that it is not possible to search through a particular message due to the lack of a search feature embedded within the search interface. I'm suggesting that the developers should include a search feature within the chat interface so that users can search through messages by choosing a day. When the search feature is clicked, it should display a calendar for a user to pick a specific date to search for a message.

**Comment by r10s** [comment]
closed on favor to https://support.delta.chat/t/make-it-possible-for-users-to-search-through-messages-using-the-calendar-tool/351 - in general, feature proposals and discussions should go to the forum.
