### ISSUE TITLE
Wrong group picture shown in group settings

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#817]
I was added to a group, someone set an image for the group, which is shown in the chat list, and in-chat(inside the chat of the group) and when I touch the group name in that view it is also fine, but when I tap on the group icon to add/remove someone, an old picture (that once was the image of another group) is shown instead of the right group avatar.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: I don't know how this is happening, so it seems random, but has happened before with other groups, I just can't figure it out why.
- Screenshots:
### Real group avatar:
![Screenshot_20190404-124844](https://user-images.githubusercontent.com/24558636/55580246-25515780-56e8-11e9-878e-0c51bea571ee.png)
### Wrong avatar:
![Screenshot_20190404-124837](https://user-images.githubusercontent.com/24558636/55580235-1f5b7680-56e8-11e9-9242-fbf320fdfd66.png)

**Comment by r10s** [comment]
we've disabled some glide-caches in the past, might be that this does not affect images already present on the device.

might be related to https://github.com/bumptech/glide/issues/3544

**Comment by adbenitez** [comment]
had the same issue again yesterday, with the same group, pattern:
- lets call the buggy group X and the other unrelated group from where the images are taken group Y
- as I reported, I changed the image y1 of group Y for image y2 and in group X image y1 was shown in group X is settings
- now again, I changed the image y2 of group Y for image y3 and in group X image y2 was shown in group X is settings

**Comment by adbenitez** [comment]
also happened to another group just now, after a member was added, the picture was a really old picture that once was the picture of the same group "Y"

**Comment by Boehrsi** [comment]
I will try to reproduce and fix the problem.

**Comment by r10s** [comment]
@Boehrsi cool. i have also noticed that.
it happens also with the self-avatar that can be set i settings/profile - changing the avatar here should also change the avatar shown in the "Me"-chat, however, the update does not arrive there.

**Comment by r10s** [comment]
fixed by https://github.com/deltachat/deltachat-android/pull/924
