### ISSUE TITLE
A few more UX issues

### ISSUE THREAD

**Issue by allo-** [deltachat/deltachat-android#820]
I tried the new release again and want to give some UX feedback (trying to act like a beginner), as I read you're doing tests specially for UX. Here is what I would try to improve in version 0.200.0

- Platform: Android
- Delta Chat Version: 0.200.0

-----

When adding a contact, you need to type in a textfield at top, that is hard to recognize as text field, because it looks like a screen header. The page would profit from a static "Add contact" button like the "add group" buttons, either in addition or as only option.
All three buttons should have more distinctive icons than a ``+``, so you can choose the right one intuitively.

![](https://user-images.githubusercontent.com/1482341/55638145-d62e2400-57c6-11e9-9d1d-b5dcd69ca002.png)
![](https://user-images.githubusercontent.com/1482341/55638454-83a13780-57c7-11e9-8b39-b3824f9ea5ca.png)

In addition it is confusing how to abort adding a contact, e.g., to add a group instead. Touching the left-arrow goes back to the previous screen, even when it is placed next to the input field. The x does work, even when it is more commonly associated with "close" (possibly going back to the previous screen?). This could all be solved by adding a button "add contact" instead of this indirect flow.

In contrast, when adding a group, the screen looks like this:
![Screenshot_20190405-163816](https://user-images.githubusercontent.com/1482341/55638605-e09ced80-57c7-11e9-9cf6-f15a53e85f00.png)

Here is a lot of white space, which could be used to list the contacts, that can be added to the group (and possibly a textbox for filtering the list), instead of of opening a second screen.

Finally, the "archive" icon when selecting conversations is not obvious at all. I do not even know what the icon should depict, and especially do not know what function it may have. It is not available in the "..." menu, so I cannot read what label may match the icon, either.

-----

I do not know, if you may already have some of the issues on your roadmap, I just thought when I am trying it again I use the opportunity for some "first impression" feedback before I get used to the way Delta chat handles these functions and do not notice the issues anymore.

**Comment by r10s** [comment]
hi @allo- thanks for your impressions. in general, however, the forum at https://support.delta.chat is a better place for such discussions and feature requests.

**Comment by r10s** [comment]
@allo- a great report, btw :) :+1:

**Comment by allo-** [comment]
You're welcome.

> this is used for the selected group members, so it is not wasted. and having a full list here makes an overview about the selected members harder.

This makes sense and is just not visible when creating the first group. But maybe this should be unified. adding, removing, and listing group members need the same list. So maybe list them there and have an "edit" button, that activates an in-place edit function and provide list filters for reducing large lists of contacts.

> wrt the contrast of the input field: this is typical for a "placeholder", i think if one would add this in a normal text color, it would be even unclearer that there is something to input.

As a power user I know this. But I needed a second look and it "feeled" not correct.  
One of the problems may be, that you are using two different flows on the same screen:
- Adding a contact in-place
- Adding a group in a new activity

Possibly it would be more intuitive to use the textbox at the top, when there are no other add-buttons. But personally I think I would prefer an explicit button. The button may show a hidden contact list with a list filter that works for adding new addresses as well.  
I cannot clearly say what I would like best, without seeing it.

> maybe we should add this to another row and use a normal title bar

Then it would not need a second look to see that it is no title bar. But I think this would waste screen space and there are probably other solutions with the same effect. For example a black-on-white textbox in a pane with the darkblue background would easily be recognized as "here is an input element". Too bad, there is not enough space on most devices to put a label before the box and thus combine title bar and input in one row.

> wrt the "new contact" button that is not available by default: the flow is that the user has to input and email-address, and click the "new contact" button or some of the other "exitsting contact buttons".

The problem here is, that you provide an action, that is invisible by default. The user does not know, that the action will become available when he types in an e-mail address. And when he suspects that typing in the address may allow some actions, he does not know what actions will be unlocked.

A compromise could be a greyed-out button, but I think I would prefer either a button and a second screen or a button that shows an error message when it is pressed and the user did not input an address. This would work best with an input box that is clearly an required element, i.e, that is somewhere on the page and a black-on-white input and not a decent element in the navigation area.

Another slightly inconsistent thing: One of the actions depends on the input (add user), the other one (create group) does not.

Testing right now I noticed something that can help: If I type some text, the button appears and its help text says "type in an e-mail address above" as long as the text is no valid e-mail address, then it changes to "user@domain".  
What about always showing the button together with the text, that clearly indicates that you need to type in an e-mail address for it to work? This could even work with a greyed-out button instead of a button with a error message.

I think I will have a look at the forums later. I just wanted to post my impression and the screenshots somewhere for now, so you have it.

**Comment by testbird** [comment]
> Another slightly inconsistent thing: One of the actions depends on the input (add user), the other one (create group) does not.

The "create group" can also require to add a new email address in the process.

If the problem is the mixed-mode "search/create" in the (navigation) title, and the mixed selection/addition + mode changing in the list...

Then, I'd imagine an activity titled "select contacts" for a new chat, 
* showing a checkbox list of existing contacts
* sorting all selected ones to the top, with a separating line before the non-selected
* two buttons in the footer area:
   * a "search/create" button, opens the keyboard with a text entry filter field applied to the list, together with a button, to create a new contact with the entered address.
   * a "start chat" or "start group chat" depending on the number of selected contacts.

**Comment by allo-** [comment]
Let's continue the discussion in the forum thread: https://support.delta.chat/t/a-few-more-ux-issues/367
