### ISSUE TITLE
Empty notification for voice and image messages

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#821]
Received a voice message, but the notification is says nothing, it is just empty

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Expected behavior: Something like a text "Voice message", or "Audio" in the notification
- Screenshots:
![Screenshot_20190404-193535](https://user-images.githubusercontent.com/24558636/55653101-741bf180-57bb-11e9-9521-066ea406205f.png)

**Comment by violoncelloCH** [comment]
same for Images I think...

**Comment by Boehrsi** [comment]
I will have a look and will try to make the messages a bit more meaningful :).

**Comment by violoncelloCH** [comment]
It could just say:
📷 Picture – [optional message text]
🎤 Voice message

**Comment by Boehrsi** [comment]
Right, I plan to reuse the messages we already use in the chat list (as preview) if an image / video / audio message is received, as those messages already contain an icon + some informational text.
