### ISSUE TITLE
Dark Theme improvements

### ISSUE THREAD

**Issue by Ampli-fier** [deltachat/deltachat-android#823]
- Platform: Android
- Device: Any
- Delta Chat Version: 0.200.0

I am currently working on a few improvements:

- Set a Conversation list item divider
- Change the Color for the round button at the bottom of the Conversation list (Start Chat/Group)
- Prepare a default background image (same as for the Light theme)
- ...

**Comment by hpk42** [comment]
cool! FYI bjoern is away on vacation but @cyberta can
also give feedback i guess ;)

**Comment by r10s** [comment]
yeah, i am on vacation :) so only short: wrt "default background image in dark theme": maybe just leave it as black. we used the "same as for the Light theme" before, however, imho it did not fit well.

**Comment by cyBerta** [comment]
I can review your changes when you submit the PR.

**Comment by Ampli-fier** [comment]
Submitted PR #828

**Comment by Ampli-fier** [comment]
Resolved by #828 + #842 + #845
