### ISSUE TITLE
Date labels has wrong position after changing screen orientation

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#825]
If you change the screen orientation while in a chat, the "date labels" are not aligned correctly (see the screenshot)

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.200.0
- Steps to reproduce the problem: enter a chat, change screen orientation.
- Screenshots:
![Screenshot_20190407-161812](https://user-images.githubusercontent.com/24558636/55816497-5a7ef080-5ac0-11e9-9da3-3c7ef7a6cb6b.png)

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/958
