### ISSUE TITLE
New map feature test report

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#826]
I just started to test the new map feature (DC 0.250) sadly I had not Internet so I could no test too much, 
I recommend to display some message in the map area something like "Connection unavailable" if there are no connection, instead of showing an empty screen.
I found a bug, I don't know if is a constant bug or just because I was offline:
If I go to the map view, and give a tap to the "blue circle"(sorry don't remember how this is called) or if you swipe it and leave it at that right corner, the app crashes (see the screenshot) 

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.250
- Screenshots:
![Screenshot_20190409-121208](https://user-images.githubusercontent.com/24558636/55817291-34f2e680-5ac2-11e9-8cf9-401d22b0553a.png)

**Comment by adbenitez** [comment]
here is a log file
[log.txt](https://github.com/deltachat/deltachat-android/files/3065696/log.txt)

**Comment by cyBerta** [comment]
Thanks for the report! fixed with commit https://github.com/deltachat/deltachat-android/pull/829/commits/f78293a3ae8c7cc5bfc5de3f3a4d2f397e316a78
