### ISSUE TITLE
Disable the "Give me permission to read contacts" dialog after it has been shown once

### ISSUE THREAD

**Issue by Hocceruser** [deltachat/deltachat-android#83]
If the user denies the read-contacts permission, Delta Chat will show a dialog in which it explains what it needs the permission for. But this dialog is shown again after every reboot, which I think is annoying. 
I see no reason for which this could be useful because the user can still change his decision my enabling the permission in the system settings. (And if the user does not read the message properly, he probably won't do it if you show him again and again, either.)

**Comment by licaon-kter** [comment]
Yep, I would like tthis too.
