### ISSUE TITLE
Do I need to add myself when creating a group?

### ISSUE THREAD

**Issue by allo-** [deltachat/deltachat-android#833]
When creating a group, I can check or uncheck "Me" in the list of group members.

![group_creation](https://user-images.githubusercontent.com/1482341/56082858-862a0f80-5e0d-11e9-907b-a169d4abc1fc.png)
("(Me)" added as translation for the german "Ich" in the screenshot)

I am not sure, what happens, when I uncheck myself, but usually I would expect to be part of any group I create.

So either the entry is redundant and confusing, or I do not really understand why there is a function to create a group without being part of the group.  
(There may be use cases for this, but they are not obvious for an average user)

**Comment by r10s** [comment]
i think it's fine that "Me" is shown as a group member in the group list, however, i agree it does not make much sense to remove yourself when creating a group (after creation, however, you can leave a group - you are no longer member of this group then and "Me" won't appear in the list)

**Comment by allo-** [comment]
I think I would just remove the checkbox next to "Me" (and possibly place "me" at the top of the list).

Does it even work to create a group without being a member? When you send a group mail, others add you to the list of recepients automatically, don't they?

**Comment by r10s** [comment]
> Does it even work to create a group without being a member? 

it won't work as the group is created by the initial mail sent by the group creator.

therefore, the checkbox beside "Me" should better be removed or disabled. however, i would leave the entry as such to clearify that there is no need to add yourself explicitly.

**Comment by adbenitez** [comment]
just leave "me" checked but disabled so user can't change it and becomes obvious that you will be a member of a group you are creating and that you can't do it otherwise
