### ISSUE TITLE
simplify location-history slider

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#837]
iirc, currently ...

- the map opens with both positions of the slider rightmost and the slider is half colored and has the label "24 hours". in this mode, the last known positions of the last 24 hours are shown, but not positions with messages.

- if the left (starting point in time) part of the slider is dragged to thiss 24 hour mark, this shows the last known positions and the positions with messages.

i think this is a bit confusing. i would open the map already in the seconds mode and show last positions and positions with messages by default.

at a later point, maybe we can have a switch that hides messages with positions, however, for now, this seems not to be needed.

@cyBerta, please correct if i am wrong :)

**Comment by cyBerta** [comment]
fixed with b20878d2bce82d96def0c02bb4b40b229a9fb498
