### ISSUE TITLE
Please ASK before degrading anything!

### ISSUE THREAD

**Issue by JRHaigh** [deltachat/deltachat-android#84]
When sharing images to Delta Chat, they are degraded without the user's consent and the user isn't even _informed_ that this is happening! Apparently this is also the case for videos.
&nbsp;&nbsp;&nbsp;&nbsp;Instead, upon sending multimedia larger than a threshold value, the user should be warned of the size of the message, informed of the threshold, and asked whether they want Delta Chat to automatically degrade the multimedia. Messages smaller than the threshold are sent verbatim without question, but the degrade and send function should still be accessible from the menu.
&nbsp;&nbsp;&nbsp;&nbsp;Furthermore, users should be able to set their preference for the ‘don't ask threshold’ in Delta Chat's settings, which I suggest should default to 10MB.
&nbsp;&nbsp;&nbsp;&nbsp;Here's a rough outline of what I think the 2 dialogue boxes should look like:

Large message warning dialogue box:
> Warning: The message you are about to send is 17.3MB. Would you like Delta Chat to degrade the message to be smaller than 10MB?
> [Cancel] [No, send verbatim] [Yes, degrade and send…]

Degrade and send dialogue box:
> What size would you like the message to be degraded to?
> 9.94MB? [smaller] [bigger]
> [Cancel] [Degrade and send]

**Comment by r10s** [comment]
Well, I always have people in mind that do not know anything about such things.

I do not want to annoy people with questions they cannot answer ...

Most people who want to send 10 photos with a messenger, do not care about quality. It should just be good enough and fast (this has nothing to do with issue #55 - this is a bug that will be fixed, so the overall image quality will be better than now :-))

People who really wants to send the original data (often ten times larger in size with current cameras!) can use the "Attach files" function which sends the data uncompressed.

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
