### ISSUE TITLE
Documents not shown in all media view

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#846]
I received a pdf, and also a txt in a chat, I went to the "all media" view to see how this will look in the documents tab, but the tab is empty, is this a bug, or what is considered a document in DC?

- Platform (android/blackberry/anbox): Android 6.0
- Delta Chat Version: 0.200.0

**Comment by r10s** [comment]
this view is just not yet implemented. maybe we should disable it for now.

**Comment by r10s** [comment]
will be targeted together with #428
