### ISSUE TITLE
Embed hashes of originals in metadata of degraded multimedia

### ISSUE THREAD

**Issue by JRHaigh** [deltachat/deltachat-android#85]
Please embed at least the SHA-256 and BTIH of original multimedia files in the metadata of degraded multimedia files. This is a prerequisite to allow these ‘preview’ images and videos to be retroäctively upgraded to their verbatim quality when the opportunity arises, such as via a peer-to-peer solution or when seen in another email.

**Comment by JRHaigh** [comment]
If degraded images could be retroäctively upgraded then there'd be no need to [ask before degrading](https://github.com/r10s/deltachat-android/issues/84).

**Comment by r10s** [comment]
Apart from privacy questions that may arise - unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
