### ISSUE TITLE
attachments with spaces in file name are not handled correctly

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#854]
If an pdf attachment has spaces in filename, text editor is started in spite of pdf viewer.
pdf attchments with no spaces in file name are handled correctly.

- Platform (android 4.1.2):
- Device: Samsung S3 mini
- Delta Chat Version: 0.200.0 self compiled with sources from 10.04.19
- Expected behavior: pdf viewer should be used to open file
- Actual behavior: text viewer is used to open file and screen is frozen until os decides to close app.

**Comment by csb0730** [comment]
hint: this was not an issue in v0.20.0

**Comment by Boehrsi** [comment]
I will have a look why this is happening.

**Comment by Boehrsi** [comment]
The linked commit should fix the problem.
