### ISSUE TITLE
Send picture by default in full resolution - by user setting

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#855]
v.0.200.0

There should be the user setting to sent pictures in full resolution (no compression)

This is not existent in current version.

**Comment by webratte** [comment]
I agree with you.

As a workaround you can send pictures send as "file". In this case it will sendet as uncompressed.

See also the discussion in the forum:

https://support.delta.chat/t/ideas-for-image-compression-feature/313

**Comment by r10s** [comment]
yip, you can send pictures without compression as files.
closing this as the discussion is already started in the forum, including pros+cons. we should continue the discussion there.

**Comment by csb0730** [comment]
Ok, but adding a user setting isn't so tricky I think. In the moment there is a setting to set compression ratio. Why don't add a choice for "no compression" ?

Wouldn't close that here.

**Comment by csb0730** [comment]
Or at least reduce compression ratio for the lesser ratio level.
I have the feeling that ratio had been changed since v0.20.0, isn't it?

**Comment by r10s** [comment]
afaik there were no significant changes.
