### ISSUE TITLE
log view - improve readability

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#857]
v0.200.0

- text is so small, that it's quite unreadable at smaller device (S3 mini)
- No timestamp included. This makes issue assignment more difficult or even impossible.
- Proposal: Introduce a button to save current log to file in download dir.

**Comment by r10s** [comment]
yip, in fact, the font size could be a bit larger.
also a "save to downloads" might be handy.
wrt the timestamp: don't get it - there should be a timestamp in front of each and every line.

**Comment by csb0730** [comment]
Hi Björn,

yes, a timestamp in front of every line would be really helpful.

Maybe You can add it?



Am 19.04.19 um 23:34 schrieb björn petersen:

**Comment by r10s** [comment]
> Maybe You can add it?

hm, the log is created by [calling `logcat -d`](https://github.com/deltachat/deltachat-android/blob/19da5cde8a99c4d7c04b6601890a0df396ba1072/src/org/thoughtcrime/securesms/LogViewFragment.java#L89) which prepends MONTH-DAY HOUR-MINUTE-SECOND on each line for me and for many logs i've seen. however, in fact, some logs look a bit different and miss eg. the timestamp, see eg. https://github.com/deltachat/deltachat-android/issues/782 - seems as if the system is using different defaults there - or the users have tweaked the defaults in a way.

maybe we can be more specific for the logcat command line options. i am happy for any pr on this issue :)

**Comment by r10s** [comment]
possible logcat-options are shown at https://developer.android.com/studio/command-line/logcat, however, for now i am not up for figuring this out.

**Comment by csb0730** [comment]
Added updates from Ampli-fier's pr to my local sources. Will test.

**Comment by r10s** [comment]
wrt the font size: i've just played around a bit. yes, it is small - and the "S3 mini" won't help on this :)

however, i've used a slightly larger font and use a non-monospace one - i do not want the text to get wider than before as this would break more log entries into two lines which results in even worse readability.

**Comment by csb0730** [comment]
Results: tweaks around date and time are working fine :-)
I think at least this is really solved now.

Regarding text size: @r10s - you should not invest many time in that. A non-monospaced font is not the best for log file view but anyway examination at phone itself is very difficult because of the very big size of the log in current view.
 Would it be possible to place cursor by default at the end of log?
I mean, if something happens You need to scroll through complete huge log until reaching interesting point. If You could change that, this would really help I think.

**Comment by adbenitez** [comment]
the log is static, so there are no need to go to the end since nothing new gets added, if you want to refresh/update the log you must go back and the tap "View log" again
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by csb0730** [comment]
@adbenitez 
I think You didn't catch my intention: If a crash or something strange happens then You'll find related logs always at or near end of current log. If You want to have a quick overview what happens You need to go always at the end of log (and this is not very handy if log is huge and presents always the beginning).

You know now?

**Comment by adbenitez** [comment]
the log don't grow big because it is a ring log, it gets overridden, and when you reopen the log after a crash new stuff is added so the error isn't at the end,
that said, I have nothing against your proposal, I am neutral with this, I was just giving some points to you to consider this :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
