### ISSUE TITLE
text size of input field does not grow with message text size

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#858]
v0.200.0

If message text size is changed from default to a bigger size (better readability) text size of input field keeps standard size.

This is hard to read at smaller device. Text size for input field should grow or shrink along with choosen message text setting.

**Comment by r10s** [comment]
well the "message font size" is explicit for the message font size.

for the other text fields, delta chat respect the system settings for the font:

<img src=https://user-images.githubusercontent.com/9800740/56444872-e8e24600-62fa-11e9-91f6-6e18941f4c5b.png width=200> <img src=https://user-images.githubusercontent.com/9800740/56444871-e8e24600-62fa-11e9-879a-c3cf59aca6df.png width=200>

(if one feels the text input is too small, this is probably true for a tons of other text input fields on the device; therefore using a larger font for that seems to be practical)

i think, this is sufficient, however, feel free to discuss this in the forum :)

**Comment by csb0730** [comment]
Ok, thanks for that hint.

I've overseen that system font can be adapted to the needs.

This is really sufficient because that controls both: message text and
input field :-)



Am 19.04.19 um 23:31 schrieb björn petersen:
