### ISSUE TITLE
Search function for contact at screen "<== Forward to" is missing

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#859]
v0.200.0

This function was available at v0.20.0 (Telegram ui).
It's important to have in case of long contact/chatlist.

Maybe related to #443 ?

**Comment by r10s** [comment]
i do not understand what you mean with _"Search function for contact at screen "<== Forward to" is missing "_

**Comment by hpk42** [comment]
i know the problem ;)  When you forward a message then you can 
select a chat to forward to.  But you can't search a chat/contact
there ... if you are trying to forward to someone you haven't chatted
to for a while it means scrolling down and looking very carefully ...

**Comment by r10s** [comment]
ahh, i see. the same functionality is missing for sharing from extern.

however, there is already an issue for that; i've made #795 a bit more precise wrt forwarding.
