### ISSUE TITLE
Latest fdroid version crashes on android 4.4 when opening a chat

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#863]
latest deltachat-android version (0.300.0) crashes when i try to open a chat.
Phone: android 4.4.4 (fairphone 1)

This does not happen when i use the 0.201.0 gplay version from github.

**Comment by r10s** [comment]
afaik, there is no version 0.300.0 and no version 0.201.0. i assume you're reporting that 0.301.0 from frdoid crashes while 0.301.0 (or 0.200.0) from gplay works.

can you post the log here?
and some more details? does every chat crash? or just some? does using a fresh account/install help? did you do an upgrade?

i just tried an upgrade on my testphone and it works as expected.

**Comment by r10s** [comment]
also just tested a fresh installation; woᴙks for me :) :)

**Comment by adbenitez** [comment]
same issue reported by an user, I have the log trapped in delta chat, but I can't copy it because it is collapsed "[...]" and I can't copy it, :( but it is an error with XML inflating stuff, I will ask the user to resend the log to another email address

**Comment by adbenitez** [comment]
got it:

```
E/AndroidRuntime(29852): FATAL EXCEPTION: main
E/AndroidRuntime(29852): Process: chat.delta, PID: 29852
E/AndroidRuntime(29852): java.lang.RuntimeException: Unable to start activity ComponentInfo{chat.delta/org.thoughtcrime.securesms.ConversationActivity}: android.view.InflateException: Binary XML file line #187: Error inflating class org.thoughtcrime.securesms.components.AnimatingToggle
```

full log:
[crash.log](https://github.com/deltachat/deltachat-android/files/3104082/crash.log)

**Comment by r10s** [comment]
is [a known error](https://github.com/deltachat/deltachat-android/issues/480). hum, we need better testing esp. on older phones.

however, i'll fix it and do a new release.

**Comment by adbenitez** [comment]
cool! I got already 3 more users reporting the same issue, good to know it is under control already :)

**Comment by r10s** [comment]
and also good to know that kitkat seems to be in use, iirc we were discussing about dropping the support.

**Comment by r10s** [comment]
new release: https://github.com/deltachat/deltachat-android/releases/tag/v0.301.1 - will be on gplay and fdroid soonish ...
