### ISSUE TITLE
Implement Hashtags 

### ISSUE THREAD

**Issue by kskarthik** [deltachat/deltachat-android#88]
Hashtags are helpful to sort out topics in groups as well as individual chats. Implementing them would be an added benefit along with existing search function.

**Comment by blelop** [comment]
this is a tag:

#tag

it is pronounced "tag".

Notice how both delinators are silent: ", and #

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
