### ISSUE TITLE
Backup password entry window not movable / Backup-Passworteingabefenster nicht verschiebbar

### ISSUE THREAD

**Issue by icke68746** [deltachat/deltachat-android#880]
- Platform (Android 4.1.2):
- Device: Neptune Pine
- Delta Chat Version: 0.302.1 (probably all)
- Expected behavior: Backup password input window can still be moved up
- Actual behavior: Backup password entry window not movable
- Steps to reproduce the problem: Log in using a device with a screen resolution of 320x240 pixels or smaller
- Screenshots: attached
- Logs: -

Hello,
when I want to backup/import with DeltaChat, the password entry field is not visible because my screen is too small (320x240). I then have to rotate the screen so that I can request the keyboard by typing into the (then visible) password entry field.

Greetings Mike
Automatic translation with deepl.com

------Original:-----
- Gerät: Neptune Pine (Android 4.1.2)
- Delta Chat Version: 0.302.1 (wahrscheinlich alle)
- Erwartetes Verhalten: Backup-Passworteingabefenster noch oben verschiebbar
- Tatsächliches Verhalten: Backup-Passworteingabefenster nicht verschiebbar
- Schritte, um das Problem zu reproduzieren: Mit einem Gerät mit einer Bildschirmauflösung von 320x240 Pixel oder kleiner anmelden
- Screenshots: angehängt
- Protokolle: -

Hallo,
wenn ich mit DeltaChat ein Backup erstellen/importieren möchte, ist das Passworteingabefeld nicht sichtbar, weil mein Bildschirm zu klein ist (320x240). Ich muß den Bildschirm dann drehen, damit ich die Tastatur durch tippen ins (dann sichtbare) Passworteingabefeld anfordern kann.

Gruß Mike
![Screenshot_2019-04-30-19-07-15](https://user-images.githubusercontent.com/36864290/56980454-b519e280-6b7c-11e9-8101-a20601665f31.png)

**Comment by r10s** [comment]
hm, the password entry comes from the system as far as i know (eg. if you disable the device-protection, not password entry is shown), so i am not sure if we can do something on this issue.
