### ISSUE TITLE
let manually downloaded and not updated APKs expire after some time

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#885]
we allow downloading and installing APKs direcly from github, sometimes we also provide testing APKs via other channels.

however, as these APKs are not updates they may to cause problems after a while. eg. we have APKs that cause group-splits still around although some around this bug are already fixed for a while.

an auto-update might be possible, however, this would not work for APKs given on special channels for testing purposes. also this leaks some information, requires some server work etc.

an easy to implement alternative might be to just check if the APK does  not come from a channel that provides updates after. if so, the APK expires eg. after 2 month. 

i think there is no need to avoid starting and using the APK, a clear informational message that the APK is probably too old. the message, however, has to  be annoying enough, i think about sth. in the chatlist (similar to the request to allow battery-usage) that cannot be clicked away

to detect APKs that are not updatable, see
https://stackoverflow.com/questions/11072079/how-to-know-if-an-app-has-been-downloaded-from-google-play-or-amazon
(while f-droid has its own applicationId, however, playstore and github downloads are equal. dev-versions always have `.beta` in their name, however. there are already a bunch of possibilities)

**Comment by csb0730** [comment]
I think too:
- a clear informational message is ok
- prevent using is not ok

Timing should be extended (6 month?)

There should be an easy way to switch off this feature in sources.

**Comment by Boehrsi** [comment]
If this is not that urgent I would have a look in the next weeks. :)

**Comment by r10s** [comment]
next week is great :)
from the ui-side, i would suggest to go the same way as the DozeReminder that is shown from [ConversationListFragment::updateReminders()](https://github.com/deltachat/deltachat-android/blob/7c8ef694676e748b5068bdb396b5468445ac79b4/src/org/thoughtcrime/securesms/ConversationListFragment.java#L199) (and maybe add an function that makes the reminder non-discardable so that it is annoying enough to update at some time)

**Comment by Boehrsi** [comment]
@r10s due to holidays / vacation the earliest date for the completion of this task is next week, not this week. Sorry for the confusion. Would this be also fine? Otherwise someone else should take over this issue I would say.

**Comment by r10s** [comment]
@Boehrsi nice holidays i'd say :)
the issue is not urgent and i am pretty sure, it is still open when you're back - so, have a good time!

**Comment by hpk42** [comment]
On Wed, May 29, 2019 at 09:30 -0700, Daniel wrote:
> @r10s due to holidays / vacation the earliest date for the completion of this task is next week, not this week. Sorry for the confusion. Would this be also fine? Otherwise someone else should take over this issue I would say.

next week is fine i think, enjoy holidays ;)

**Comment by r10s** [comment]
closed by #945 - great job, @Boehrsi , excellet :)
