### ISSUE TITLE
Add a button on the map to center own location.

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#888]
Add a button to center own location on the map.

- Platform (android/blackberry/anbox): Android 7.0
- Device: Huawei nova
- Delta Chat Version: 0.303.0
- Expected behavior: option  to show own position in the center of the map by tab a button.
- Actual behavior: If I move the map I have to manually search for own position.

**Comment by r10s** [comment]
there are many things missing; let's discuss feature proposals in the forum.
