### ISSUE TITLE
Add a button to jump to first message in chat

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#892]
When you are in a chat there is a round button at right bottom of chat (>>) to jump to last message in chat.
What is missing is the same button (<<) but to jump to first message in chat.

With former telegram UI this was possible to use the search function, enter nothing and search.
This gets You to the beginning of a chat.

**Comment by r10s** [comment]
yip. however, i am more thinking about a scrollbar that can really be used as such (as in the contact list)

**Comment by r10s** [comment]
as the issue tracker should show only things actually being working on, i close this for now.

in general, for feature-requests, the forum should be used.

**Comment by csb0730** [comment]
For myself I did a button to jump in big steps against 1st message (10% steps). Similar to button to jump to bottom of a chat, but more flexible.
I have some chats which have > 1000 msgs and here it helps very much for me :-).

Will do a PR for that.

**Comment by r10s** [comment]
i think, the button will come back when the search gets impemented.
