### ISSUE TITLE
cannot open any conversation, problem with keys

### ISSUE THREAD

**Issue by gilcu3** [deltachat/deltachat-android#893]
- Platform (android/blackberry/anbox): android 9
- Device: xiaomi redmi note 6 pro
- Delta Chat Version: 0.303
- Expected behavior: open conversation
- Actual behavior: crashing when I open a conversation
- Steps to reproduce the problem: open app, open any conversation
- Screenshots:
- Logs: https://pastebin.com/D5D9H8qz

**Comment by r10s** [comment]
thanks for filing this issue, it should already be fixed by https://github.com/deltachat/deltachat-android/pull/890 ; the fix will be part of the upcoming releases then.

**Comment by gilcu3** [comment]
> thanks for filing this issue, it should already be fixed by #890 ; the fix will be part of the upcoming releases then.

then after updating to next release, I will have access to conversations again, or I would have to fresh install it?

**Comment by r10s** [comment]
you should just have access to your conversations. i am wondering where the bug come from, however, the corrsponding code was just a relict from the original signal code that i removed a few days before coincidentally :)

@gilcu3 would be great if you can test if the following works correctly for you
https://share.riseup.net/#-7dbwncuvMDYbavP9yCErQ - it is a 0.303 without the bug

**Comment by gilcu3** [comment]
I am using delta chat from f-droid repo, if you make the build compatible with it I will test it right away :)

**Comment by r10s** [comment]
> I am using delta chat from f-droid repo, if you make the build compatible with it I will test it right away :)

sorry, this is not possible. fdroid signs the apk with their keys. the developers do not have these keys.

**Comment by r10s** [comment]
but you can do an export in the fdroid apk and leave it installed.
the linked apk from above can be installed without fdroid being unsinstalled and you can import the backup there.

**Comment by gilcu3** [comment]
the export function doesn't work either, it shows a toast saying "Authentication Failed"... I had tested that before when I realized if I reinstalled app and configured everything again it worked as usual, just had to lose my previous local conversations.

**Comment by r10s** [comment]
just [released 0.304](https://github.com/deltachat/deltachat-android/releases/tag/v0.304.0) - this should be on fdroid soonish then (was withing 48 hours or so for the last versions which is quite fast compared to delays we had before)

**Comment by gilcu3** [comment]
> just [released 0.304](https://github.com/deltachat/deltachat-android/releases/tag/v0.304.0) - this should be on fdroid soonish then (was withing 48 hours or so for the last versions which is quite fast compared to delays we had before)

Indeed version 0.304 allows me to open conversation again, thanks. The other problem remains though, when I press Manage keys, or Backup, it opens the security pattern, and after I correctly enter it, it shows a toast saying Authentication problem. Log  [here](https://pastebin.com/H6zc04nt)

**Comment by r10s** [comment]
@Boehrsi maybe you can have a look at that?

@gilcu3 however, i think we should treat this as a separate issue; the initial problem is solved - would be great if you can file a new issue for that.

**Comment by gilcu3** [comment]
> @Boehrsi maybe you can have a look at that? maybe it is reproducible in an emulator.
> 
> @gilcu3 however, i think we should treat this as a separate issue; the initial problem is solved - would be great if you can file a new issue for that.

done #899

**Comment by r10s** [comment]
thanks!
