### ISSUE TITLE
on Android 4, the Settings screen looks weird and misses some padding

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#894]
![photo_2019-05-08_04-36-49](https://user-images.githubusercontent.com/34889164/57345370-ed0bc180-714a-11e9-9ae4-6b4a2f0b74b0.jpg)

Telegram in comparison:
![photo_2019-05-08_04-40-50](https://user-images.githubusercontent.com/34889164/57345528-77ecbc00-714b-11e9-956b-a6c5afba9d34.jpg)

Icon/Text of settings is really close to the screen border. Not sure if this is specific to my old device.

**Comment by r10s** [comment]
> Not sure if this is specific to my old device.

i think so, also noticed that for android 4.x. not totally sure, what the reason for that is, however, whatever the fix might be, this may result in keeping two layout files which results in additional maintenance then. so i am not sure if it is worth the effort.
there are already lots of workarounds to avoid android 4 crashes, eg. https://github.com/deltachat/deltachat-android/pull/865 :/

@Jikstra otoh - is only the settings main page that looks weird to you?

**Comment by r10s** [comment]
wrt Telegram: well they paint everything on their own and do not use the typical views. this makes the app unusable for screen readers and so on (we're in contact with some blind people that test such things)

**Comment by Jikstra** [comment]
> @Jikstra otoh - is only the settings main page that looks weird to you?

The loading dialog/popup with that rotating circle thing is also misaligned. But that's all I came across.

> this may result in keeping two layout files which results in additional maintenance then. 

So maybe not worth it. I'm fine with having it not 100% polished on older devices.

**Comment by Ampli-fier** [comment]
I am wondering if the results from an Android Studio Code Inspection give valuable hints regarding behavior on older Android Versions:

![DC-Code_Inspection_Result](https://user-images.githubusercontent.com/22896574/57405756-884e7680-71df-11e9-9324-53a391ece971.jpg)

(The total amount of errors/warnings depends on the selected Checks)

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/954
