### ISSUE TITLE
Move some "advanced" options to "non-advanced"

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-android#898]
as of 0.304.0 we have many options under "advanced".  Here is a list -- i mark those bold that i think could be moved to non-advanced. 

- send autocrypt setup message
- prefer end-to-end encryption
- **email-interaction (show classic / contacts / all)** -> Chats and Media? 
- IMAP folder handling (moves) 
- **outgoing image quality** -> Chats and Media? 
- **on-demand location streaming** -> Chats and Media? 
- **backup** -> Chats and Media? or a new top-level "account" where also privacy/security settings would be part of? (like in whatsapp)
- manage keys
- view log 

If in doubt i think we should orient the settings structure towards what whatsapp and telegram do. 

At the same time i think that all the options marked bold here should be available on Delta Chat Desktop as well -- and apart from location streaming, also on the upcoming https://github.com/orgs/deltachat/projects/10 ios releases let's open issues there once this issue is settled.  @jikstra @nayooti @ralphtheninja @nicodh @Simon-Laux

**Comment by r10s** [comment]
- i think "email-interaction", "outgoing image quality" indeed can be moved to Chats and Media. it makes much sense and is pretty easy. the latter i'd suggest to change to "outgoing media quality" that will also change voice-messages and video quality then.

- the on-demand-location-streaming option will go away anyway as soon as it loses its "experimental" state, so i would leave ti there

- moving "backup" to chats and media makes some sense, but is a bit more work as it shares much code with "manage keys". so i would not do this just now. i am pretty sure, people will find it. compared to the remaining efforts and understandings needed for a backup export/import, this is the simplest step anyway :)   
wrt a top-level-account-page: we have this already, at least sort of: a click on your name/the avatar shows your settings. but, indeed, maybe this needs a clearer naming.
