### ISSUE TITLE
Manage keys and Backup not working on android miui/xiaomi

### ISSUE THREAD

**Issue by gilcu3** [deltachat/deltachat-android#899]
- Platform (android/blackberry/anbox): Android 9 MIUI 10.3
- Device: xiaomi redmi note 6 pro
- Delta Chat Version: 0.304
- Expected behavior: Manage keys and Backup work properly
- Actual behavior: Authentication failed toast appears
- Steps to reproduce the problem: Press on Manage keys and Backup options, then enter security pattern as needed.
- Screenshots:
- Logs: [log](https://pastebin.com/H6zc04nt)

**Comment by r10s** [comment]
@Boehrsi maybe you can have a look at that? maybe it is reproducible in an emulator.

**Comment by gilcu3** [comment]
@r10s it seems it is indeed a problem with MIUI as I get the same error when trying to change Pattern in Settings. So I'm closing the issue....

**Comment by r10s** [comment]
@gilcu3 thanks for figuring that out and for closing. this will save us a lot of work.
