### ISSUE TITLE
fix sharing of multiple images

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#901]
Currently the PersistentBlobProvider seems to be buggy so that images are not always copied or loaded completely during the share process of multiple files at the same time. It results in half-drawn images getting shared.

**Comment by r10s** [comment]
i did some recent cleanup there, maybe this is releated? https://github.com/deltachat/deltachat-android/pull/890

however, we should not revert the changes; they are needed as there were bugs in the (unused!) crypto parts which were some signal-relicts.

**Comment by r10s** [comment]
just an idea: as this seems to happen for multiple images only - may it be that the PersistentBlobProvider gives that same id-or-whatever to all of them?

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/913
