### ISSUE TITLE
adapt or remove minify/proguard

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#905]
EDIT: some action is needed, see video-recoding issue below.

currently, the app uses "proguard" which was introduced when we adapted the signal code, see https://developer.android.com/studio/build/shrink-code#enabling-gradle.

from time to time, i run into problems with proguard - something is not working, needs adaption and so on. just now warnings as "W/dex2oat: Method processed more than once" - they go away when proguard is disabled.

also, searching a bit on stackoverflow & co, proguard tends to cause problems if not configured and maintained correctly - and currently it is unmaintained here in delta afaik :)

i am wondering if it is worth the effort. before signal we have not used proguard, the obfusucation is not needed and if i look at the proguard configuration file ([this one](https://github.com/deltachat/deltachat-android/blob/master/proguard.cfg), there a bunch), it seems to me as if even optimization is disabled (EDIT: unused functions might be stripped of anyway).

@Boehrsi @cyBerta @hpk42 what's your stance on this?

**Comment by r10s** [comment]
i think, the actionable item in this issue is mainly to check how much smaller the apk with proguard really is. if it is significant, we should streamline all the proguard-files to a single one, i think most of them are not needed at all, and document them a bit.

**Comment by r10s** [comment]
well, again some problems: the video recoding is not working with minifyEnabled. costs me 2 hours to find out that this is the reason. and will probably some more effort to adapt minify/proguard and add some exceptions.

just tried it: when removing minifyEnabled and the proguard files, the apk is 1.5mb larger. so, i'd say we leave this optimization for now until someone really takes care.

**Comment by hpk42** [comment]
On Mon, May 13, 2019 at 05:58 -0700, björn petersen wrote:
> well, again some problems: the video recoding is not working with minifyEnabled. costs me 2 hours to find out that this is the reason. and will probably some more effort to adapt minify/proguard and add some exceptions.
> 
> just tried it: when removing minifyEnabled and the proguard files, the apk is 1.5mb larger. so, i'd say we leave this optimization for now until someone really takes care.

1.5mb (so around 6% size increase) sounds acceptable if such debugging problems 
are caused by it.  Probably makes sense if someone systematically looks at 
"minimizing" apk size instead of going with this unmaintained proguard-setting.

**Comment by r10s** [comment]
did a pr https://github.com/deltachat/deltachat-android/pull/909
