### ISSUE TITLE
Share my location

### ISSUE THREAD

**Issue by guland2000** [deltachat/deltachat-android#93]
Will be great to have function **see/send/share location** with others.

**Comment by kskarthik** [comment]
Yeah. +1

**Comment by r10s** [comment]
+1

**Comment by Hocceruser** [comment]
It is already possible to share your location via oher apps, like OSMAnd:
1. Tap on the point where your location is shown on the map -> a pop-up "your location" pops up
2. Tap on the "share" button
3. Tap on "Send"
4. Tap on Delta Chat

Of course this is more complicated than it could be but at least it works.
If you do not want to install OSMAnd there are other, smaller apps only to share your location. This one should work, for example:
https://play.google.com/store/apps/details?id=com.sktapp.sharemylocation

**Comment by kskarthik** [comment]
@r10s this is what I can help you at the best with this issue https://stackoverflow.com/questions/8194233/open-street-maps-api-for-android#8194446

**Comment by allo-** [comment]
I think you can send some kind of location intent, which opens the default maps application for choosing a location. This would avoid the need for the location permission.

**Comment by Hocceruser** [comment]
I did not think about this until you mentioned it but of course it is another problem that location permission will decrease some user's trust in Delta Chat because they think that it could send their location to some server without their knowledge. 
If there is no such location intent, this might be an argument not to implement location sharing.

**Comment by allo-** [comment]
Conversations solved this with a plugin as separate app, which you can install if you like to send your location.

**Comment by r10s** [comment]
Unless there are some volunteers working on this issue, for now, this is out of scope IMHO. However,  the idea stays available via https://github.com/deltachat/deltachat-android/wiki .
