### ISSUE TITLE
Change default english signature text

### ISSUE THREAD

**Issue by KylePiira** [deltachat/deltachat-android#936]
Currently the default string for the English email signature is "Sent with my Delta Chat Messenger: https://delta.chat" however, this sounds somewhat awkward. I would petition to change it to something like "Sent via Delta Chat Messenger: https://delta.chat".

See https://github.com/deltachat/deltachat-desktop/pull/824 for more details.

**Comment by testbird** [comment]
With "via" the line sounds like you sent the message to deltachat (https://delta.chat) and it was then forwarded to the recipient. What about "sent from" or "written with"?

**Comment by KylePiira** [comment]
@testbird Yeah, I think something like "sent from" would work well.

**Comment by r10s** [comment]
no idea if the current signature sounds funny, i am no native english speaker :) however, as this also affects desktop and ios, i would suggest to discuss this in the forum at https://support.delta.chat
