### ISSUE TITLE
mailto links with a body but no subject

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-android#937]
`mailto:email@example.com?body=content`
- Expected behavior: `content` in the text input field
- Actual behavior: `null\ncontent` in the text input field
- Steps to reproduce the problem: open `mailto:email@example.com?body=content`

**Comment by adbenitez** [comment]
also support for mailto links inside delta chat is missing

**Comment by Boehrsi** [comment]
I will try to fix that one today.

**Comment by r10s** [comment]
great to see this fixed :)
