### ISSUE TITLE
zoho.com, imap

### ISSUE THREAD

**Issue by blelop** [deltachat/deltachat-android#94]
Either errors with smtp auth or credential. Two accounts I use with K9 that are not working with this app. Password copied to/from clipboard

zoho is a paid platform with some free optioms like email.  Imap must be manually enabled from web interface.  

I can create a demo account if needed as like gmail and yahoo zoho "requires" legacy sms text number :( using the same services spammers would use disposable sms number.. proving that it's not securing diddleysquat

**Comment by QiangF** [comment]
FYI. Zoho doesn't support the common authetication mechnism. 
https://forums.zoho.com/topic/cannot-authenticate-smtp-session-when-using-delta-chat

**Comment by Shetlanders** [comment]
unlike the zoho forum topic I am not using 2FA ergo I am not generating application specific passwords.

I have enabled IMAP for this account.  I am using the alias to login with manual configuration. I have tried the base account.  

As this is domain hosted email my imap server is

imapPRO.zpho.com 

The smtp server is the same.  It is the same error as this ticket. I am using SSL and port 993.

All manual fields have been manually populated.


> PLAIN SASL Mechanism is in our roadmap

Would delta chat kindly provide a workaround option for such hosts as zoho?

**Comment by Shetlanders** [comment]
popup: error #6

**Comment by QiangF** [comment]
There is an update on zoho side:
https://forums.zoho.com/topic/cannot-authenticate-smtp-session-when-using-delta-chat

**Comment by r10s** [comment]
:) can anyone check if it works now?
