### ISSUE TITLE
webp images attached with .null extension on Android 4

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#949]
Some people using Android 4 devices had reported that sending webp images doesn't work for them, the webp images they send arrive to the peers as attached files with ".null" extension instead of ".webp", ex. file name: "image.null"

- Platform (android/blackberry/anbox): Android 4.2 (and others I don't know exactly the version)
- Device: -
- Delta Chat Version: 0.304.0

**Comment by Boehrsi** [comment]
I will try to reproduce that and if possible to fix it.

**Comment by csb0730** [comment]
@Boehrsi 
Please see #916 !
Maybe we have the same issue here?

**Comment by cyBerta** [comment]
@Boehrsi I fixed #916 and it's indeed the same error here. That's why I've fixed this issue now by the way, too.

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-android/pull/954
