### ISSUE TITLE
Simplify autocrypt syncing on initial startup

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-android#951]
The idea is if we install deltachat on a new device, by scanning the inbox we can probably easily determine if deltachat is already used. If it's used we can offer a screen in the setup "wizard" which prompts and leads the user through exchanging the autocrypt key. Of course this should also be skippable but also shown again if the device gets a message encrypted for another device.
 
"It seems like you're already using DeltaChat with other devices on this E-Mail Account. Do you want to keep in sync with them and be able to read those messages? Then please do this and that on your other device. Waiting for autocrypt setup message..."

**Comment by r10s** [comment]
this is described in more detail at https://autocrypt.org/level1.html#helping-users-get-started , so it is a known issue that is not yet done. same for a self-sent-test-messages that can find out that smtp and imap are really working as expected.

**Comment by r10s** [comment]
closing this for now, i think, we come to this sooner or later anyway.
