### ISSUE TITLE
back-button does not work when a chat is opened from search

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#959]
- search for something from the chatlist
- open a chat from the search results
- the back key does not bring you back to the chatlist (or to the search) but does nothing

only after opening delta from the app-icon leaves this state.

to fix that, the back-button should go to the chatlist _or_ to the search, whatever is easier.

**Comment by adbenitez** [comment]
can't reproduce on my Android 6, the system back button works fine (it is a hardware button in my phone) and the in-app back button (the arrow) works also, only the standard issue of sometimes having to tap it twice because seems hard to touch(the padding issue)

**Comment by r10s** [comment]
the padding issue is solved already :)
this is another one ...
