### ISSUE TITLE
Crash when switching activities during configuration

### ISSUE THREAD

**Issue by Toover** [deltachat/deltachat-android#96]
Protocol:
Start Delta Chat for the first time
Next, set a valid server configuration manually, and let the focus on one of the lineedits.
Do not confirm yet, instead use the home button to leave the app (I opened the browser also, but I don't think it is necessary to), and come back to Delta Chat.
Restarting the configuration kept my previous input (cool!) but the scroll is offset in an odd way that prevents me from reaching the lineedits at the bottom of the page (is it related?). Clicking to another lineedit crashes the app.

**Comment by r10s** [comment]
Thank you for your detailed report, this will help reproducing the error.

**Comment by r10s** [comment]
can you confirm that this still happens in the most recent version?

**Comment by Hocceruser** [comment]
I can't reproduce this, neither with v0.9.9 nor with the latest GitHub version

**Comment by r10s** [comment]
I cannot reproduce this either, @Toover feel free to re-open the issue if the problem still exists.
