### ISSUE TITLE
add a simple option to empty DeltaChat and/or INBOX on the server

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#966]
the option will go to advanced/experimental and there should be a harsh warning. 

@adbenitez o/

**Comment by r10s** [comment]
@hpk42 @adbenitez this is how it looks currently - any suggestions to the wording or so? ;)

<img src=https://user-images.githubusercontent.com/9800740/59954888-75d68680-9487-11e9-9f5f-377b7811d7a8.png width=300>

**Comment by webratte** [comment]
Will the first option really delete ALL messages in the inbox or just chat messages?

Delete ALL messages is really risky I believe.

Maybe users could think DC has a own inbox, but would lost all regular mails not only DC mails.

You know what I mean?!

**Comment by r10s** [comment]
it really deletes all messages. it is mainly to help users that have very restricted quota.

but yes, maybe we should point that out, I'll do a pr.

**Comment by r10s** [comment]
new text: https://github.com/deltachat/deltachat-android/pull/967/commits/b186a3fbd4cb4090b4024091c815981a232e3603

**Comment by webratte** [comment]
I'm not sure about that.
I believe DC should never touch the inbox.

Regular E mails should only deleted by regular E mails because this E mails are not visible in DC.

And probably user will still not know also invisible mails will be deleted.

I think it's really risky to annoy non tech users this way.

One wrong click and my inbox is cleared. Even of invisible E mails.

You should this discuss again.

**Comment by webratte** [comment]
And another scenario:

A user check his regular E mails only one time per week by a desktop client (e.g. Thunderbird) and has no mobil client on his phone.
I know people who do that this way 😉

Now he got a few mails in this time.
He will not know that there are new mails.

But DC will still delete this unreaded mails by using your new function.

Very risky as I said before.

**Comment by r10s** [comment]
what would be your concrete suggestions here? as said, the function as such _is_ needed by many users. if their server is full, they cannot receive or sent any message which seems to be even worse.

however, we can point it out, that the messages may not even be read.
maybe even "empty server folders" sounds too harmless. maybe the title should read "Delete all data from server" instead.

any ideas welcome :)

**Comment by r10s** [comment]
> Regular E mails should only deleted by regular E mails because this E mails are not visible in DC.

we can offer the "empty inbox" option only if "show all emails" is enabled. I think this should make he function less dangerous.

**Comment by webratte** [comment]
IMHO you should do nothing with the inbox.
Regular Mails will be under control of the user.

You should only work with the DC folder.

You could suggest: if the space is still rare to delete also regular mail by using a regular Mail client or the web interface.

If you still like delete regular mails be very carefully and use a big fat red warning 😉

**Comment by r10s** [comment]
I totally agree, it is a dangerous option.

> You could suggest: if the space is still rare to delete also regular mail by using a regular Mail client or the web interface.

well, might be that delta chat is the only client :)
and if the option "show all" is enabled, the non-chat-mails stuck in the inbox and are not moved to the DeltaChat folder.

however, with with the last commit, if the option "show all" is not enabled, the inbox-empty-option is not available.

**Comment by webratte** [comment]
Yes, this way you can minimize the risk to delete wrong mails by accident.

But still you should keep an eye on:
https://github.com/deltachat/deltachat-core/pull/595

It's a more user-friendly way to keep server space free 😉

**Comment by hpk42** [comment]
Let's wait for @adbenitez to comment on these options ...

**Comment by adbenitez** [comment]
Sorry @webratte but the clear INBOX is really needed, if you or others don't want to use it, just don't ;)
Users with chat-only settings may find also useful to delete all the spam and unwanted messages they may have in their chat-email address, so maybe it should be there even if email interactions is set to chat-only, I think the wording is pretty clear if something says "delete ALL messages in inbox folder" seems pretty clear to me, also this is an experimental feature, we are just experimenting here, lets see what are the results, I am pretty sure the results will be good ;)

**Comment by adbenitez** [comment]
BTW @r10s this looks better than I was imagining it, great work!!! :)

**Comment by adbenitez** [comment]
one thing that could make the clear INBOX option less dangerous is to delete only messages not marked as "recent", so if the inbox has 100 messages and the recent property is 10, then only messages from 1 to 90 should be deleted

**Comment by webratte** [comment]
The only thing I say is, delete "non chat messages" is very risky.

I hope you remember my warning after the first bad rating of a non tech user who lost a very important mail by using this option 😜

**Comment by adbenitez** [comment]
> The only thing I say is, delete "non chat messages" is very risky. I hope you remember my warning after the first bad rating of a non tech user who lost a very important mail by using this option stuck_out_tongue_winking_eye

hahahaha, if a dummy user go to the **advanced** menu and use an **experimental** option that says to delete **ALL** messages from their INBOX, well I think it is his fault.

**Comment by adbenitez** [comment]
as suggested by `since_` on the irc channel, maybe it is better to use the word "emails" instead of messages:
"Delete ALL emails in Inbox Folder"

**Comment by webratte** [comment]
I think the plan is to make the experimental things sometimes a standard feature.
Isn't it?

Of course, while it's experimental it's no problem.

**Comment by adbenitez** [comment]
in a future maybe we can have a more complex functionality like the auto-remove feature based on time

**Comment by adbenitez** [comment]
while we are talking here some mailboxes are blowing up, and I must say that when you have your inbox full you lost all messages people send to you while it is full, so it is equally dangerous or worse, not to have this option right now...

**Comment by hpk42** [comment]
indeed, this option is a temporary measure until automatic removals aka #595 arrive.

**Comment by webratte** [comment]
In this case...👍

**Comment by Ampli-fier** [comment]
Is it worth mentioning that this effects multi-device synchronization?
Better make sure to have all devices connected to the server once, right before the delete ...

> however, with with the last commit, if the option "show all" is not enabled, the inbox-empty-option is not available.

This is an indicator, but not 100% bullet proof :) The user might have switched back and forth in the past.

**Comment by webratte** [comment]
@hpk42 Did you link the right issue?

#595 seems to be wrong...

**Comment by adbenitez** [comment]
@webratte, he was talking about https://github.com/deltachat/deltachat-core/pull/595 on the core repo

**Comment by webratte** [comment]
@adbenitez

Thank you.
Now it's clear. And the link was really wrong.

**Comment by adbenitez** [comment]
yes he replied from email with `#595` and github had inserted a link to an issue with that number in this repo

**Comment by hpk42** [comment]
sorry for wrong link and thanks @adbenitez for correcting -- i confused repos ... 
maybe i could use https://github.com/rhysd/github-complete.vim or so to better avoid
these kinds of errors. 

On Mon, Jun 24, 2019 at 11:22 -0700, Asiel Díaz Benítez wrote:
> yes he replied from email with `#595` and github had inserted a link to an issue with that number in this repo

yes, sorry

**Comment by r10s** [comment]
> Users with chat-only settings may find also useful to delete all the spam and unwanted messages they may have in their chat-email address, 

okay, I think I'll revert the last commit that disallows emptying the inbox only if "show all" is selected. ux wise, this is also hard to explain and may lead to users changing options temporary.

I'll also change the wording to delete "ALL e-mails" to make things even clearer. maybe I'll add DANGER ZONE or so to the title :)

**Comment by r10s** [comment]
added a new screenshot at https://github.com/deltachat/deltachat-android/pull/967#issuecomment-505466217

**Comment by adbenitez** [comment]
I think it look REALLY explicit and dangerous now ;) so there shouldn't be any problems +1

**Comment by webratte** [comment]
@r10s great solution 👍
