### ISSUE TITLE
Disable signature

### ISSUE THREAD

**Issue by Toover** [deltachat/deltachat-android#97]
All my messages have an unwanted signature like "Sent with DeltaChat", and there is no way to remove it.

**Comment by r10s** [comment]
It's not unwanted, it's just to spread the work :-)

I think we should have an option for this, anyone to implement it?

**Comment by MichaIng** [comment]
Definitely support this. Best solution would be an adjustable signature, like most mail clients allow.

Moreover the standard signature should provide a Link (inside DeltaChat string) to http://delta.chat to make it more useful if one really wants to spread this interesting project.

**Comment by reno-a** [comment]
Hello,

As @MichaIng , I think a free appraisal / modification for signature would be a good idea.
And for the standard signature, the link to "delta.chat" would be desirable.

For spread this suberb project : (just my opinion)
We are not many who don't use GApps. Then, iIf you want diffuse this application at more people, this will go (sadly?) by Google-Play.

**Comment by zoff99** [comment]
ok for the first message, but on every single message.
that's spam

**Comment by rizzopablo** [comment]
Most personal emails I receive have the link to the antivirus the sender 
use in his windows, they even don't know how to avoid this, and nobody 
seems to care about it.

I would place the link in my signature if I could do it without need to 
recompile Delta.

**Comment by r10s** [comment]
Okay, I will make it editable.

I'm unsure whether adding a link to the signature will increase the risk to be marked as spam. I would not risk this, maybe here are some experts about this around?

Moreover, I'd like to change the default text to:

    -- 
    Sent with my Delta Chat Messenger. Please excuse my brevity.

I think this gives a little more sense to the signature. What do you think?

**Comment by rizzopablo** [comment]
Hi Björn, I agree editable signature is a good thing to have.


I've maintained web hosting servers and fighted spam for over 13 years, 
I don't see a text url in a signature as a risk. Otherwise antivirus, 
facebook, twitter and many others wouldn't use signature links 
extensively. Spamassasin wouldn't add spam points for this in a usual 
configuration (and if it does we'll see it inmediately). Also, we are 
yet a very small community of users I gess, it won't make noticeably noise.


Best regards

Pablo

**Comment by r10s** [comment]
Another idea: Maybe we should make signatures displayable in Delta Chat, eg. in the profile. However, this would require additional parsing and is out of scope of this issue. Maybe later.

But maybe we should sightly change the default text to make sense to be displayed independently of the message in future (without the "sent with my"), maybe:

    -- 
    I am using the Delta Chat messenger. Please excuse my brevity.

But I am no english native speaker ...

**Comment by r10s** [comment]
I would also like a different name to "Signature" then. Maybe something like "Slogan" or "Remark"?

**Comment by reno-a** [comment]
"Signature" seems the most understanding. But I also like "Slogan".

**Comment by r10s** [comment]
@reno-a: If the text is only displayed in the footer, signature is the best wording.

However, I think it can make sense to display it also in the profile as follows:

![image](https://user-images.githubusercontent.com/9800740/28213348-f3ff3832-68a5-11e7-8c56-4e0c650fc602.png)

Here, the term "Signature" is not the best choice, IMHO. "Slogan" may fit into both cases.

**Comment by rizzopablo** [comment]
Nice idea :)

14 de julio del 2017 7:13, "Björn Petersen"  escribió:
	Another idea: Maybe we should make signatures displayable in Delta Chat, eg. in the profile. However, this would require additional parsing and is out of scope of this issue. Maybe later.

	But maybe we should sightly change the default text to make sense to be displayed independently of the message in future (without the "sent with my"), maybe:

	-- I am using the Delta Chat messenger. Please excuse my brevity. 

	But I am no english native speaker ...

**Comment by r10s** [comment]
Okay, the signature will be editable as the "Status" text in 0.9.4, a little preview:

![screenshot_20170717-003501](https://user-images.githubusercontent.com/9800740/28251925-0c5deb92-6a88-11e7-9e08-defed8eab453.png)

**Comment by reno-a** [comment]
@r10s Thanks for all. It's exactly what we need.

**Comment by r10s** [comment]
See also https://github.com/deltachat/deltachat-android/issues/97 for a discussion about the default text ...
