### ISSUE TITLE
show GIF's in notification bar

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#974]
on newer Android Versions, it should be possible to display animated GIF's using AnimationDrawable and custom notification views that include an image view.

**some useful resources** 
* restrictions about the supported classes of remote views (=> notification layout) https://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout
* using an AnimationDrawable without animation-list xml resource: https://stackoverflow.com/questions/10149487/animationdrawable-programmatically-without-animation-list-xml/10151505
* ideas how to convert GIFs to AnimationDrawables: https://github.com/Hipmob/gifanimateddrawable

**Comment by cyBerta** [comment]
start animation in remote views: https://stackoverflow.com/questions/48642800/start-animation-in-remoteviews

**Comment by r10s** [comment]
to be honest, i am not sure if i would like to see an animated gif in the notification bar. a simple text "gif image" would do the job.

**Comment by cyBerta** [comment]
With the latest updates you will even see an image of the GIF as a preview!

**Comment by r10s** [comment]
i think an unanimated gif is fine. i am only afraid about animations in the notification bar.
