### ISSUE TITLE
play voice messages from notification bar

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-android#975]
Of course this is not urgent but would be a nice to have. 
There are tons of open-source examples out there that  show how to play, stop, skip music from the notification bar.

**Comment by adbenitez** [comment]
that will work if there are only 1 new message, but if there are several, they are collapsed in one notification, so most the time users will not enjoy this good feature anyway :(

**Comment by r10s** [comment]
yip, i also think this is not that useful in many cases. and i would not add unneeded complexity to parts that are already that complex.

**Comment by cyBerta** [comment]
> that will work if there are only 1 new message, but if there are several, they are collapsed in one notification, so most the time users will not enjoy this good feature anyway :(

This is only true for older Android versions. Newer support stacked notifications that are expandable. By expanding a notification group you can perform actions on each notification (= each message).

**Comment by cyBerta** [comment]
Closing for now anyways.

**Comment by adbenitez** [comment]
wow, cool then!
