### ISSUE TITLE
Setting "Show classic emails" not working (any more)

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#977]
DC v0.304.0 (github version from Jun 12)
Android 4.1.2

If setting "Show classic emails" is changed from default to "All" new value is not saved.

If settings screen is closed after change and switch back to screen again is shows default "No, chats only" again.

This behaviour has been working fine (v0.200.0) until the setting is moved to new menu location.

**Comment by r10s** [comment]
@csb0730 good catch! thanks for filing the bug!

fixed that by #979

**Comment by csb0730** [comment]
@r10s 

double checked - it's working - great job :-)

Thanks

**Comment by r10s** [comment]
@thanks for re-checking!

**Comment by monperrus** [comment]
in the UI, "Chats and media"/"Show classic emails" is conceptually related to the options of "Advanced"/"Imap folder handling". 

In particular, one touches both when one wants to use DeltaChat as a full email client.

What about moving them together in the same configuration block, either in "Email interation" or in "Folder handling"?

**Comment by r10s** [comment]
yes, maybe, however, the latter are more technical details that are harder to understand and are more related to server details not under control of the user, so not really "user options".

btw. on ios, we have far less "settings section", eg. "Show classic emails" is a top-level thing there. if this works out nicely for the users, maybe we can cleanup android at some point as well.

**Comment by monperrus** [comment]
I'm exactly along the same line we need something super easy and usable.

Today, to use DeltaChat as email client (and not only as chat app), we need two changes in two different screens:

* set "Chats and media"/"Show classic emails" to "all"
* uncheck Advanced/"automatically moves to DeltaChat folder"

My initial proposal is to move them close to each other. From a usability perspective, we may even go further, with one configuration item "How to use DeltaChat"
  * option 1: "as a chat app" (meaning "automatically moves to DeltaChat folder" = true)
  * option 2: "as an email app" (meaning "show all emails" and "automatically moves to DeltaChat folder" = false)

**Comment by r10s** [comment]
@monperrus thanks for your ideas :) maybe we can continue the discussion at https://support.delta.chat - also because this is cross-platform-related.

**Comment by monperrus** [comment]
OK, moving to the support channel, starting with https://support.delta.chat/t/configuration-recommendation-for-using-delta-chat-as-an-email-client

thanks a lot for your fast answers!

**Comment by adbenitez** [comment]
oh please don't! over here we use delta chat as a email client (email interactions set to "all") but like to move all messages to the DeltaChat folder, I don't get how keeping them in the INBOX help you to use Delta Chat as your email reader, it is good to have the tons of chat messages tidy in a dedicated folder that you can visualize in your other email clients anyway, having chats and classic emails cluttered in the INBOX isn't good IMHO

**Comment by adbenitez** [comment]
ah sorry this was moved to the forum, I am reading from email, sorry
