### ISSUE TITLE
warn when trying to use outlook.com or hotmail.com addresses

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#981]

**Comment by webratte** [comment]
Maybe this warning should also added to the Google play store listing?

**Comment by r10s** [comment]
i think showing it in the app is sufficient - and a huge ux-improvement. if this seems not to be enough, we can iterate from there.

**Comment by webratte** [comment]
I thought a user who know this before installation is not frustrated to much if it not work as expected with outlook.com.

But probably your right. DC is still listed as beta.
