### ISSUE TITLE
File name out of bubble in quick reply view

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#983]
The screenshot talks by itself ;)

- Platform (android/blackberry/anbox): Android 6
- Delta Chat Version: 0.500.0
- Screenshots:
![Screenshot_20190627-204914](https://user-images.githubusercontent.com/24558636/60341877-ec8aec80-997d-11e9-8739-81cdd10a898a.png)

**Comment by webratte** [comment]
Is this also in full screen?

And another question just out of curiosity:
How can I shrink a window as you it did?

I never saw that before.

**Comment by adbenitez** [comment]
this windows appears when you press the "reply" button on the notification, this allow you to quickly reply to a message without leaving your current app when a delta-message arrive, in the background is k9 the app I was using while the message arrived, I replied and then quickly keep with my work, if you are using an older version of android maybe this feature isn't available and when you press "reply" a full screen window is shown, but I can't confirm this theory :)

**Comment by webratte** [comment]
Ahh, thank you.
I never used the replay option via notification.
I always open the App via desktop icon.

I use Android 7. So it should also work for me.
I will try it the next time.

**Comment by r10s** [comment]
i also have never seen that :)
in general, i do not really think it is useful to have the whole view in the notification area.

**Comment by adbenitez** [comment]
I think this only works when you have message from a single chat, when you have new messages from more than 1 chat this functionality is hidden so you have less chances to discover it

**Comment by adbenitez** [comment]
> in general, i do not really think it is useful to have the whole view in the notification area.

it isn't the whole view in the notification area, it is more like a Dialog view, this kind of view that exists in Android that just use a part of the screen and has transparent background

**Comment by adbenitez** [comment]
and I think it is useful in some cases, when you are busy and just want to reply quickly "I am busy, reply you later", this applies also when you are in a chat, and want to reply quickly to other people without leaving the important chat

**Comment by adbenitez** [comment]
anyway, since this is like an eclipse (only possible if you have only one chat with new messages) I think it isn't worth the effort for so little real use.

**Comment by r10s** [comment]
okay, thanks for explaining :)

**Comment by cyBerta** [comment]
This view is only shown for older Android versions that doesn't support notification reply actions and was developed by Signal.

**Comment by cyBerta** [comment]
So @r10s and me decided to remove that fallback solution completely for the sake of simplicity of the code.
