### ISSUE TITLE
imap port number

### ISSUE THREAD

**Issue by MarkusEckerl** [deltachat/deltachat-android#985]
- Platform (android/blackberry/anbox):
- Device:
- Delta Chat Version:
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by MarkusEckerl** [comment]
Platform (android/blackberry/anbox): android
    Device: vernee apollo x25
    Delta Chat Version: 0.500.0
    Expected behavior:  Use the port number that was entered in the setup dialog.
    Actual behavior: The port for the IMAP server could be entered but the application does not use the entered port number. Always only port number 143 is used!
    Steps to reproduce the problem: try the setup dialog
    Screenshots:
    Logs:

**Comment by r10s** [comment]
i fact, the app tries port 143 only if the entered port does not work.

but i agree that this is a bit weird, esp. if final failures are reported for a port that is not entered.

**Comment by r10s** [comment]
comparable issue: https://github.com/deltachat/deltachat-android/issues/1086

closing this now, there is no actionable item for android, but we will probably fix that in rust-core.
