### ISSUE TITLE
Can't record video

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android#986]
this is a report from an user, he wasn't able to record video, description given by user:
when tapping in the record button the screen goes blank and then the chatlist is shown

- Platform (android/blackberry/anbox): Android 6.0
- Device: HUAWEI CAM-L21 (CAM-L21)
- Delta Chat Version: 0.500.0
- Logs:
[2019-06-28-13-31.txt](https://github.com/deltachat/deltachat-android/files/3347240/2019-06-28-13-31.txt)

**Comment by r10s** [comment]
the log shows some connection problems to nauta.cu, this is proably unrelated, however, at least this one should be fixed.

the video-thingie needs a retry, in between many things and components have changes, so maybe things are working now :)

**Comment by adbenitez** [comment]
at this time I don't even know/remember which user was the one reporting this, so I think we can close it until someone else complains ;)
