### ISSUE TITLE
no "new message marker"

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#988]
- Platform (android/blackberry/anbox): Android 7.0
- Device: Huawei nova
- Delta Chat Version: 0.500.0
- Expected behavior: show "new message" marker if there are new unreaded messages in a chat.
- Actual behavior: no "new message" marker

**Comment by r10s** [comment]
note that the "new message marker" is currently displayed only if you're in chatview AND the app goes to background and foreground again AND in between messages arrive.

**Comment by webratte** [comment]
Thank you.
This way it works.

So this issue can be closed.
