### ISSUE TITLE
can't play voice message (Android 8.0.0)

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#989]
- Android: 8.0.0:
- Device: Huawei P10, Y7
- Delta Chat Version: 0.500.0 Google Play

- Expected behavior:
Incoming voice message should be played

- Actual behavior:
Voice message isn't played. Instead a grey toast "Fehler" is displayed. 

See attached log.
[2019-07-04-16-11.txt](https://github.com/deltachat/deltachat-android/files/3360529/2019-07-04-16-11.txt)

**Comment by csb0730** [comment]
I found the same problem (and #990 too) at the two different Huawei devices. Maybe the problem is limited to this device or Android 8.0.0 ? 

Maybe this is the interesting part of the log:

07-04 16:09:39.823  2435  2435 V AudioManager: playSoundEffect   effectType: 0
07-04 16:09:39.853  2435  2435 W MediaPlayer: Couldn't open http://127.0.0.1:34956/4b82b7e13c0666281513232fa7b9fce6: java.io.FileNotFoundException: No content provider: http://127.0.0.1:34956/4b82b7e13c0666281513232fa7b9fce6
07-04 16:09:39.854  2435  2435 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@78babb9): Cookies: null
07-04 16:09:39.854  2435  2435 I MediaPlayerNative: setDataSource(http://127.0.0.1:34956/4b82b7e13c0666281513232fa7b9fce6)
07-04 16:09:39.864  2435  2457 V MediaHTTPService: makeHTTPConnection: CookieManager(java.net.CookieManager@e2491ec) exists.
07-04 16:09:39.864  2435  2457 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@78babb9): cookieManager: java.net.CookieManager@e2491ec Cookies: null
07-04 16:09:39.879  2435  2435 W MediaPlayer: Couldn't open http://127.0.0.1:33838/1bc0798e8c08f96a90246f8053574c63: java.io.FileNotFoundException: No content provider: http://127.0.0.1:33838/1bc0798e8c08f96a90246f8053574c63
07-04 16:09:39.879  2435  2435 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@ee0abfe): Cookies: null
07-04 16:09:39.879  2435  2435 I MediaPlayerNative: setDataSource(http://127.0.0.1:33838/1bc0798e8c08f96a90246f8053574c63)
07-04 16:09:39.879  2435  2655 I AttachmentServer: Header: connection : Keep-Alive
07-04 16:09:39.879  2435  2655 I AttachmentServer: Header: host : 127.0.0.1:34956
07-04 16:09:39.879  2435  2655 I AttachmentServer: Header: accept-encoding : gzip
07-04 16:09:39.879  2435  2655 I AttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 8.0.0)
07-04 16:09:39.880  2435  2655 I AttachmentServer: headers: HTTP/1.1 200 OK
07-04 16:09:39.880  2435  2655 I AttachmentServer: Content-Type: audio/aac
07-04 16:09:39.880  2435  2655 I AttachmentServer: Accept-Ranges: bytes
07-04 16:09:39.880  2435  2655 I AttachmentServer: Content-Length: 88593
07-04 16:09:39.880  2435  2655 I AttachmentServer: Connection: Keep-Alive
07-04 16:09:39.880  2435  2655 I AttachmentServer: 
07-04 16:09:39.905  2435  2457 V MediaHTTPService: makeHTTPConnection: CookieManager(java.net.CookieManager@e2491ec) exists.
07-04 16:09:39.905  2435  2457 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@ee0abfe): cookieManager: java.net.CookieManager@e2491ec Cookies: null
07-04 16:09:39.912  2435  2658 I AttachmentServer: Header: connection : Keep-Alive
07-04 16:09:39.913  2435  2658 I AttachmentServer: Header: host : 127.0.0.1:33838
07-04 16:09:39.913  2435  2658 I AttachmentServer: Header: accept-encoding : gzip
07-04 16:09:39.913  2435  2658 I AttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 8.0.0)
07-04 16:09:39.913  2435  2658 I AttachmentServer: headers: HTTP/1.1 200 OK
07-04 16:09:39.913  2435  2658 I AttachmentServer: Content-Type: audio/aac
07-04 16:09:39.913  2435  2658 I AttachmentServer: Accept-Ranges: bytes
07-04 16:09:39.913  2435  2658 I AttachmentServer: Content-Length: 129250
07-04 16:09:39.913  2435  2658 I AttachmentServer: Connection: Keep-Alive
07-04 16:09:39.913  2435  2658 I AttachmentServer: 
07-04 16:09:39.922  2435  2457 D MediaPlayerNative: Message: MEDIA_ERROR(100), ext1=MEDIA_ERROR_UNKNOWN(1), ext2=0x80000000
07-04 16:09:39.923  2435  2457 E MediaPlayerNative: error (1, -2147483648)
07-04 16:09:39.923  2435  2457 D MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
07-04 16:09:39.923  2435  2457 D MediaPlayerNative: [notify] : [1216] callback application
07-04 16:09:39.935  2435  2457 D MediaPlayerNative: Message: MEDIA_ERROR(100), ext1=MEDIA_ERROR_UNKNOWN(1), ext2=0x80000000
07-04 16:09:39.935  2435  2457 E MediaPlayerNative: error (1, -2147483648)
07-04 16:09:39.935  2435  2457 D MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
07-04 16:09:39.935  2435  2457 D MediaPlayerNative: [notify] : [1216] callback application
07-04 16:09:39.964  2435  2435 E MediaPlayer: Error (1,-2147483648)
07-04 16:09:39.964  2435  2435 I MediaPlayer: [HSM] stayAwake false uid: 10141, pid: 2435
07-04 16:09:39.964  2435  2435 E MediaPlayer: Error (1,-2147483648)
07-04 16:09:39.965  2435  2435 I MediaPlayer: [HSM] stayAwake false uid: 10141, pid: 2435

**Comment by csb0730** [comment]
Seems to be related to Huawei phones? It seems so!
Is anyone out there who can confirm this?

**Comment by adbenitez** [comment]
probably related to #1161 ???

**Comment by r10s** [comment]
@csb0730 can you please retry with Delta Chat 1.0?

**Comment by r10s** [comment]
closing this one in favor to the newer report at https://github.com/deltachat/deltachat-android/issues/1161
