### ISSUE TITLE
voice message can't be exported to file

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#990]
- Platform: Android 8.0.0:
- Device: Huawei P10
- Delta Chat Version: 0.500.0 Google Play

- Expected behavior:
When saving a voice message by disk symbol it should be saved to a .aac file either in folder "music" or "downloads".
 
- Actual behavior:
It seems that export is done but file cannot be found.

- Steps to reproduce the problem:
Mark a voice message by long tap, tap at disk symbol to export, do it, then no file can be found.

**Comment by csb0730** [comment]
At export dialog there is no hint to what folder the file is exported.

**Comment by r10s** [comment]
fixed by #1195
