### ISSUE TITLE
Can't select a file attachment from folder

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-android#991]
- Platform Android 4.1.2:
- Device: S3 mini
- Delta Chat Version: v0.304.0
- Expected behavior:
When using the paper-clip to select a file attachment I want to select the desired file from the desired folder or at least from folder "Downloads".
- Actual behavior:
This is not possible at all. You can only choose files from Galery, Contacts, MP3-Player or Music Tracks.

- Screenshots:
![Screenshot](https://user-images.githubusercontent.com/30560716/60688780-8c350700-9eb7-11e9-8e23-4970b760fa0d.png)

**Comment by r10s** [comment]
there is no file-manager in delta chat. instead, the system-intent to select files is started - typically, this comes with the system, however, if there is none (or maybe it was uninstalled), there is not much delta chat can do (the dialog above is the system dialog).

however, the good news is that you can install an app that implement the needed file-manager intent, not sure, which one will fit for android4, but there are some: http://ddg.co/?q=android+file+manager

**Comment by r10s** [comment]
as there is no actionable item, i suggest to close this issue.
if you need more help, please refer to https://support.delta.chat

**Comment by csb0730** [comment]
Ok, then the situation is clear. I'll play around with that issue but yes, we can close it here now.
