### ISSUE TITLE
remove swipe-to-archive

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#992]
while archiving as such is useful to many people, including me :), the swipe-left-archive gesture is more annoying than helpful. we've heard this several times that chats were archived accidentally.

of course, this could be improved eg. by forcing a second click or so, however, these swipe gestures are more usual on mac, on android, a long-click is much more common (and also used for the other functions as delete, info, etc.)

as archiving is already today available via long-click, we can remove swipe-to-archive completely.

**Comment by N1N74** [comment]
Hello, I wanted to see if there is any interest in re-introducing this as a toggle-able settings. I never accidentally swipe on chats and I use this feature in apps like gmail and found it very useful as it is a quick way to dismiss unimportant emails which I seem to get a lot of. 
It would be even more convenient if left and right swipes are distinguished and the action for each can be configured.

**Comment by r10s** [comment]
there are no plans nor many requests in reintroducing swipe.

note, that we support quite some android versions from 4.1 to today, depending on manufactors, some of them also use "swipe to go back" and/or having different quality in detection of gestures. that would be easily mixed in and can also be tricky wrt maintenance.

but it was also not tried recently as our few resources are spent elsewhere.

so, i am a little sceptical if that is worth the effort. but, if you like you can add a feature proposal at https://support.delta.chat

**Comment by N1N74** [comment]
I think it's not too bad, because the issue can be mitigated by leaving this feature off by default and because even google allows it with gmail. I guess I'll try my shot on the forum and see if many people also prefer this, and it's totally understandable if you don't think it's worth it.

Thanks for the quick response! ^^

**Comment by monperrus** [comment]
Gmail's swipe-to-delete is super useful and saves a lot of time, it would be great to have in DeltaChat.
