### ISSUE TITLE
Cannot Get ItTo Work With G-Mail

### ISSUE THREAD

**Issue by puppykickr** [deltachat/deltachat-android#994]
- Platform:  android
- Device:  ZTE 558VL
- Delta Chat Version:  .304.0
- Expected behavior:  open app and use it
- Actual behavior:  app opens and a toast pops up saying that it can't log in
- Steps to reproduce the problem:  open app and wait for toast error message
- Screenshots:
- Logs:

device=ZTE Z558VL (Z558VL)
android=7.1.1 (20171114.151732, Z558VLV1.0.0B06)
sdk=25
memory=13M (21.42% free, 256M max)
memoryClass=128
host=newsuper8
applicationId=com.b44t.messenger
app=Delta Chat 0.304.0-fat
ignoreBatteryOptimizations=true

deltachat_core_version=v0.43.0
sqlite_version=3.26.0
sqlite_thread_safe=1
libetpan_version=1.8
openssl_version=1.0.1t
rpgp_enabled=0
compile_date=May  8 2019, 04:18:45
arch=32
number_of_chats=1
number_of_chat_messages=4
messages_in_contact_requests=2646
number_of_contacts=208
database_dir=/data/user/0/com.b44t.messenger/files/messenger.db
database_version=55
blobdir=/data/user/0/com.b44t.messenger/files/messenger.db-blobs
display_name=(puppykicker)
is_configured=1
entered_account_settings=xxxxxxxxxxxxx@gmail.com 0:***:0:0 0:0:0:0 0
used_account_settings=xxxxxxxxxxxxxxx@gmail.com xxxxxxxxxxxxxx@gmail.com:***:imap.gmail.com:993 xxxxxxxxxxxxx@gmail.com:***:smtp.gmail.com:465 OAUTH2 IMAP_SSL SMTP_SSL
inbox_watch=1
sentbox_watch=1
mvbox_watch=1
mvbox_move=1
folders_configured=3
configured_sentbox_folder=[Gmail]/Sent Mail
configured_mvbox_folder=DeltaChat
mdns_enabled=1
e2ee_enabled=1
private_key_count=1
public_key_count=1
fingerprint=9735D6520361B6B806077F138705831A65882289

--------- beginning of main
07-05 10:48:37.040   380   380 W PassphraseRequiredActionBarActivity: onCreate(null)
07-05 10:48:37.050   380   380 D Typeface: fontPath: 
07-05 10:48:37.170   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@dc18716
07-05 10:48:37.170   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3936897
07-05 10:48:37.200   380   380 W PassphraseRequiredActionBarActivity: onResume()
07-05 10:48:37.200   380   380 D Typeface: fontPath: 
07-05 10:48:37.240   380   476 E OpenGLRenderer: void android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface *) to create EGLSurface com.b44t.messenger/org.thoughtcrime.securesms.ConversationListActivity
07-05 10:48:39.130   380   476 E OpenGLRenderer: void android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface *) to create EGLSurface PopupWindow:ce9937d
07-05 10:48:40.900   380   380 W PassphraseRequiredActionBarActivity: onPause()
07-05 10:48:40.930   380   380 W PassphraseRequiredActionBarActivity: onCreate(null)
07-05 10:48:40.950   380   380 D Typeface: fontPath: 
07-05 10:48:40.960   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2f7a92a
07-05 10:48:40.960   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@97a031b
07-05 10:48:40.980   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2f263fc
07-05 10:48:40.980   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@c938a85
07-05 10:48:40.990   380   380 W PassphraseRequiredActionBarActivity: onResume()
07-05 10:48:40.990   380   380 D Typeface: fontPath: 
07-05 10:48:41.040   380   476 E OpenGLRenderer: void android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface *) to create EGLSurface com.b44t.messenger/org.thoughtcrime.securesms.ApplicationPreferencesActivity
07-05 10:48:41.360   380   476 D OpenGLRenderer: endAllActiveAnimators on 0x9450fb00 (MenuPopupWindow$MenuDropDownListView) with handle 0x9382ac80
07-05 10:48:47.850   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@bcad8ab
07-05 10:48:47.850   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2a48b08
07-05 10:48:53.560   380   380 W PassphraseRequiredActionBarActivity: onPause()
07-05 10:48:53.600   380   380 D Typeface: fontPath: 
07-05 10:48:53.610   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@717841e
07-05 10:48:53.610   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@c7894ff
07-05 10:48:53.630   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@62eb191
07-05 10:48:53.630   380   380 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@321f8f6
07-05 10:48:53.630   380   380 D Typeface: fontPath: 
07-05 10:48:53.680   380   476 E OpenGLRenderer: void android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface *) to create EGLSurface com.b44t.messenger/org.thoughtcrime.securesms.LogViewActivity
07-05 10:48:53.780   380   476 D OpenGLRenderer: endAllActiveAnimators on 0x92e22100 (RippleDrawable) with handle 0x95249cb0

Logs may contain private data 
which shall be removed or anonymised prior to posting.
-->

**Comment by r10s** [comment]
have you tried using gmail without oauth2 using plain imap?

however, can you please ask in the support forum for help, https://support.delta.chat ?
and please also specify for concrete what you're doing, which screen are shown, are you using gmail or gsuite etc.

if the outcome is that there is an error in the app, this can result in an issue in the bug tracker here.

**Comment by r10s** [comment]
also wondering that the log says "is_configured" and that there are some chats, btw. however, as mentioned, this suits better in the "mutual help" section of the forum.

**Comment by puppykickr** [comment]
The chats that are there are from months ago.

The app has not worked with G-Mail for quite some time.

I have not been able to use Delta Chat at all since mid March.

I just uninstalled all updates to the G-Mail app and now I just use that
because it is much less hassle.

Sure, the dark theme option that Delta Chat provides is nice, but it does
nothing for me if the app is not compatible with my device.

Here I had sent out e-mail after email, and thought they were being sent,
when they were not.

One day the app worked, and the next day it didn't.

And it hasn't worked since March.

Grant Ryan Swan
(puppykicker)

**Comment by nutpantz** [comment]
I've had most of my delta chat contacts have issues with oauth2 "magically" turning on after some updates of delta chat. Then everybody had to manually go into delta chat and set it to automatic (there is no option for force oauth2 off) AND go into Google and turn on "less secure apps access" AGAIN. You might have to check those to keep delta chat working for gmail.

**Comment by puppykickr** [comment]
@nutpantz
I have been through this mess multiple times before.

I recently just uninstalled Delta Chat because it wasn't working anyway, and now I see that there is an indication of some sort in my G-mail settings (that wasn't there before) about Delta Chat.

I don't know what it is.

I am not going to fool with it.

Either an app works or it doesn't.

As it is, having to constantly check and recheck settings in multiple venues just isn't my thing, I just want the frigging e-mail to work.

I am not even using the G-mail app any longer, having switched to accessing my G-mail account through WebApps.

I have actually been able to both rid my devices of multiple buggy apps and control 3rd party access by using WebApps.

**Comment by nutpantz** [comment]
I don't blame you for getting out, I don't blame delta chat either.  I blame oauth2 and how Google has set it up, and everyone who promotes anything other than good long passwords. I do blame delta chat a little for having only a "automatic"setting and no "just off" only option for oauth2

**Comment by r10s** [comment]
@nutpantz gmail can be used without oauth2, i've just tried it and created a summary at https://support.delta.chat/t/oauth/568

still, hoping that google fixes this issue soon and/or get in contact with us :)

**Comment by puppykickr** [comment]
I just plain loathe Google-   what they do and how they do it.

My solution is to currently just use WebApps.

I can eliminate many apps, not need to log in or out, and control 3rd party access.
